### ISSUE TITLE
Sequential Task with errors flow are not handle

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#1]
```yaml
id: errors
namespace: org.floworc.tests

tasks:
- id: failed
  type: org.floworc.core.tasks.scripts.Bash
  commands:
  - 'exit 1'
  errors:
  - id: 2nd
    type: org.floworc.core.tasks.debugs.Echo
    format: second {{task.id}}
```

The errors will not be triggers, need to be global to work or on `FlowableTask`
