### ISSUE TITLE
Restart marks a failed execution as successful

### ISSUE THREAD

**Issue by yuri1969** [kestra-io/kestra#1032]
### Expected Behavior

Restarting a failed execution which fails again during the restart attempt should remain FAILED since that is the state of the latest execution.

### Actual Behaviour

Restarting a failed execution which fails again during the restart attempt is marked as SUCCESS in case the flow definition contains an error handler (either global or local). This leads to not being able to detect and restart the failing executions effectively.

### Steps To Reproduce

1. Execute a failing flow which got an error handler defined
2. Select the failed execution and restart it
3. The workflow is marked as SUCCESS

### Environment Information

- Kestra Version: 0.6.1-SNAPSHOT as of Feb 28th
- Operating System (OS / Docker / Kubernetes): Docker

### Example flow

```
id: RestartWithGlobalErrorHandlerTest
namespace: io.kestra.tests
disabled: false
tasks:
  - id: failStep
    type: "io.kestra.core.tasks.scripts.Bash"
    description: "This fails"
    commands:
      - 'exit 1'
errors:
  - id: errorHandler
    type: io.kestra.core.tasks.debugs.Echo
    format: I'm failing {{task.id}}
    level: INFO
```

```
id: RestartWithLocalErrorHandlerTest
namespace: io.kestra.tests
disabled: false
tasks:
  - id: seq
    type: io.kestra.core.tasks.flows.Sequential
    tasks:
      - id: failStep
        type: "io.kestra.core.tasks.scripts.Bash"
        description: "This fails"
        commands:
           - 'exit 1'
    errors:
      - id: errorHandler
        type: io.kestra.core.tasks.debugs.Echo
        format: I'm failing {{task.id}}
        level: INFO
```

**Comment by yuri1969** [comment]
Potentially related - when a failed workflow gets restarted a timed out ERROR attempt is kept marked as RUNNING for an oddly long time period.
![KESTRA_RETRY](https://user-images.githubusercontent.com/13468636/222168312-3cf652e4-403e-40ec-a850-e940f94e7047.PNG)

**Comment by tchiotludo** [comment]
Good catch, we will look at this soon, thanks for the report

**Comment by tchiotludo** [comment]
Potentially related also [here](https://kestra-io.slack.com/archives/C03FQKXRK3K/p1678109298164549?thread_ts=1678102693.974129&cid=C03FQKXRK3K) 
With this source:
```yaml
id: webhooks_test
namespace: my.test.flows

triggers:
  - id: webhook
    type: io.kestra.core.models.triggers.types.Webhook
    key: 4wjtkzwVGBM9yKnjm3yv8m

tasks:
  - id: logging
    type: io.kestra.core.tasks.debugs.Echo
    format: "{{ trigger.body.data }}"
```
Webhook request:
```
curl --location --request POST 'http://localhost:8080/api/v1/executions/webhook/my.test.flows/webhooks_test/4wjtkzwVGBM9yKnjm3yv8m' \
--header 'Content-Type: application/json' \
--data-raw '{
    "data": "value"
}'
```
Process:
- trigger and verify that the flow successed
- change solution to make te flow fail
- trigger and verify that the flow fail
- correct the flow definition
- trigger and verify that the flow successed
- restart the previous execution that fail (it fail again.. ok)
- restart again the previous exection that fail (block in running state)

[Capture vidéo du 2023-03-06 14-15-50.webm](https://user-images.githubusercontent.com/2064609/223349963-1baa55fc-341a-452f-b731-e9948724a51c.webm)
