### ISSUE TITLE
Provide a task to fail a flow

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#1053]
### Feature description

Provide a `Fail` task that will fail the flow unconditionally.

This can be convenient for switch to fail on un-wanted values.

We can also provide a condition for fine-grain failure.

**Comment by loicmathieu** [comment]
Task example:

```yaml
id: fail
type: io.kestra.core.taks.flow.Fail
#optional condition that is at true by default so fail un-conditionnaly
condition: {{outputs.previous.value == "you must fail"}}
```
