### ISSUE TITLE
Trigger based on Events 

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#1066]
WIP ! 

Maybe a flow can emits events: 
```yaml 
  - id: onlyNoInput
    type: io.kestra.core.tasks.events.Emit
    name: 'myEventTable1' 
    args: 
      customData: "{{ outputs.myTask.value }}"
```

And flow can listen to events: 
```yaml
triggers:
  - id: listenFlow
    type: io.kestra.core.models.triggers.types.Flow
    inputs: 
      fromEvents: "{{ events.customData }}"
    conditions:
      - type: io.kestra.core.models.conditions.types.Event
        name: 'myEventTable1' 
```

This will allow more fine grained triggering based on internal processing like tables generated, file created?

**Comment by anna-geller** [comment]
linking a similar idea https://github.com/kestra-io/kestra-ee/issues/252

**Comment by anna-geller** [comment]
An alternative solution would be to leverage already existing flow outputs and add a trigger allowing users to react to specific Execution outputs and optional metadata conditions attached to them:

```yaml
id: metadata
namespace: dev

tasks:
  - id: marketingCosts
    type: io.kestra.plugin.gcp.bigquery.LoadFromGcs
    destinationTable: "myDataset.myTable"

outputs:
  - id: bigquery_table
    type: STRING
    value: "{{ outputs.marketingCosts.destinationTable }}"
    metadata:
      gcsBucket: gs://myBucket/myFile.csv
      rows: "{{ outputs.marketingCosts.rows }}"
```

React to the event:

```yaml
id: myflow
namespace: myteam
description: Save and Execute the flow

tasks:
  - id: send_alert
    type: io.kestra.core.tasks.log.Log
    message: |
      {{trigger.event}}
      {{trigger.event.metadata}}

triggers:
  - id: listenFlow
    type: io.kestra.core.models.triggers.types.events.Output
    conditions:
      - id: namespace
        type: ExecutionNamespaceCondition
      - id: metadata
        type: io.kestra.core.models.conditions.types.OutputCondition
        condition: "{{trigger.event.metadata.rows < 1000}}"
```
