### ISSUE TITLE
Autocompletion didn't work when modifying the task type

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#1077]
### Expected Behavior

Autocompletion should always work on the `type` task property.

### Actual Behaviour

For example, use this flow definition:

```yaml
id: hello
namespace: io.kestra.tests

tasks:
  - id: hello
    type: io.kestra.core.tasks.debugs.Echo
    format: Hello World
```

When you update the `type` attribute and try to use the autocompletion, it only propose `io.kestra.core.tasks.debugs.Echo`, you have to remove the `type` property and rewrite it to be able to use autocompletion.

### Environment Information

- Kestra Version: 0.8.0-SNAPSHOT
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):
