### ISSUE TITLE
[UI] Show an error in the editor when a FILE-type input has a default value attached to it

### ISSUE THREAD

**Issue by Skraye** [kestra-io/kestra#1091]
### Expected Behavior

When a type file input is defined, it can not have a default value. An error should be thrown.

### Actual Behaviour

When a type file input is defined, it can have a default value.

### Environment Information

- Kestra Version: 0.8.0-SNAPSHOT

**Comment by anna-geller** [comment]
FWIW it seems to be handled fairly well during execution:

![image](https://github.com/kestra-io/kestra/assets/86264395/18ba7855-0d43-4b61-9cce-e4d7114b990f)

I agree that it would be nice to show an error directly in the editor though, as this flow input is not valid when it's set to an arbitrary string value 

```yaml
id: file_defaults
namespace: test

inputs:
  - name: myfile
    type: FILE
    defaults: mydefaul value

tasks:
  - id: hello
    type: io.kestra.core.tasks.log.Log
    message: "{{ inputs.myfile }}"
```
