### ISSUE TITLE
Inputs can have duplicated name

### ISSUE THREAD

**Issue by Skraye** [kestra-io/kestra#1092]
### Expected Behavior

An error should be thrown when two inputs are defined with the same name (before execution).

### Actual Behaviour

Inputs can have duplicated name

### Steps To Reproduce

```yaml
id: a-flow
namespace: some.namespace
inputs:
  - name: first_input
    required: true
    type: STRING
  - name: first_input
    required: true
    type: INT
tasks:
  - id: taskOne
    type: io.kestra.core.tasks.log.Log
    message: "{{ inputs.first_input }}"
```

### Environment Information

- Kestra Version: 0.8.0-SNAPSHOT
