### ISSUE TITLE
Implement if-else task

### ISSUE THREAD

**Issue by yuri1969** [kestra-io/kestra#1098]
### Feature description

Currently, Kestra features the `io.kestra.core.tasks.flows.Switch` task acting as a value-based _switch_ statement. This allows diverting the execution path based on a resolved value. However, a simple binary conditional requires a lot of boilerplate code.

The current approach to execute a simple task conditionally is illustrated bellow:

```yaml
  - id: run-X-when-necessary
    type: io.kestra.core.tasks.flows.Switch
    value: "{{ inputs contains 'aVariableConnectedToX' ? 'RUN' : 'SKIP' }}"
    cases:
      RUN:
        - id: run-X
          type: io.kestra.core.tasks.debugs.Echo
          description: "Run X"
          format: "Running X with {{ inputs.aVariableConnectedToX }}..."
    defaults:
      - id: skipping-X
        type: io.kestra.core.tasks.debugs.Echo
        description: "Switch requires to have a task to execute"
        format: "Skipping X..."
```

It would be great to have a simple task acting as the classic _if-else_ statement allowing the following notation:
```yaml
- id: run-X-when-necessary
  type: io.kestra.core.tasks.flows.If
  test: "{{ inputs contains 'aVariableConnectedToX' }}"
  then:
    - id: run-X
      type: io.kestra.core.tasks.debugs.Echo
      description: "Run X"
      format: "Running X with {{ inputs.aVariableConnectedToX }}..."
```
or
```yaml
- id: run-X-when-necessary
  type: io.kestra.core.tasks.flows.If
  test: "{{ inputs contains 'aVariableConnectedToX' }}"
  then:
    - id: run-X
      type: io.kestra.core.tasks.debugs.Echo
      description: "Run X"
      format: "Running X with {{ inputs.aVariableConnectedToX }}..."
  else:
    - id: run-Y
      type: io.kestra.core.tasks.debugs.Echo
      description: "Run Y"
      format: "Running Y..."
```

The `test` condition should use a _truth_ value - empty string being evaluated to false, etc.
