### ISSUE TITLE
Trigger validation : Missing Property "disabled"

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#1100]
### Expected Behavior

In the Flow editor, when there is a trigger a validation warning is displayed.

This can be reproduce with the following flow description

```
id: polling-trigger
namespace: io.kestra.tests

triggers:
  - id: polling
    type: io.kestra.plugin.gcp.bigquery.Trigger
    interval: PT10S
    fetch: true
    sql: |
      SELECT DATETIME(datehour) as date, title, views FROM `bigquery-public-data.wikipedia.pageviews_2023` 
      WHERE DATE(datehour) = current_date() and wiki = 'fr' and title not in ('Cookie_(informatique)', 'Wikipédia:Accueil_principal', 'Spécial:Recherche')
      ORDER BY datehour desc, views desc
      LIMIT 10

tasks:
  - id: hello
    type: io.kestra.core.tasks.log.Log
    message: Hello World
```

### Environment Information

- Kestra Version:
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):
