### ISSUE TITLE
The Pause task triggers the global error handler

### ISSUE THREAD

**Issue by yuri1969** [kestra-io/kestra#1103]
### Expected Behavior

The `io.kestra.core.tasks.flows.Pause` task should trigger the global handler only in case of setting the `timeout` property. Using just the `delay` property should not trigger an error.

### Actual Behaviour

The `io.kestra.core.tasks.flows.Pause` task triggers the defined global error handler immediately when being executed.

### Steps To Reproduce

1. Paste the example flow.
2. Execute the flow.
3. Observe the Gantt/Logs.

### Environment Information

- Kestra Version: 0.7.1
- Operating System (OS / Docker / Kubernetes): CentOS
- Java Version (If not docker): openjdk version "11.0.18" 2023-01-17 LTS

### Example flow

```yaml
id: pauseDelayAndErrors
namespace: io.kestra.tests
description: Illustrate the Pause task with a delay set triggers the global error handler
disabled: false

tasks:
  - id: wait-20-sec
    type: io.kestra.core.tasks.flows.Pause
    description: "Wait 20 sec"
    delay: PT20S
    tasks:
      - id: waiting-done
        type: io.kestra.core.tasks.debugs.Echo
        description: "Resume executing"
        format: I'm done waiting!

errors:
  - id: failed-echo
    type: io.kestra.core.tasks.debugs.Echo
    description: "Log the error"
    format: I'm failing {{task.id}}
```
