### ISSUE TITLE
The Pause task fails to resume

### ISSUE THREAD

**Issue by yuri1969** [kestra-io/kestra#1114]
### Expected Behavior

After the defined delay the Pause task should resume and continue with execution of its listed tasks.

```yaml
  - id: wait-and-resume
    type: io.kestra.core.tasks.flows.Pause
    description: "Wait 20 sec and then resume"
    delay: PT20S
    tasks:
       - ...
```

### Actual Behaviour

The Pause task _tends to_ fail resuming and executing its defined tasks. This happens mostly when the system is under load - a stream of new executions comes in.

The failure is not deterministic. For example, out of 7500 executions only 37% ended as FAILED on a Pause task. The rest was SUCCESS.

The execution's overall state is FAILED but the last state in _Logs_ states PAUSED.

Kestra executor server logs contain the following error:

> WARN #033[0;39m #033[35mpool-2-thread-1#033[0;39m #033[36mi.k.core.models.executions.Execution#033[0;39m [namespace: io.kestra.tests] [flow: TEST] [execution: 2DdFl4faeB4GWZKB46YY4n] Flow failed from executor in 00:07:43.218 with exception 'Execution must be terminated to be restarted, current state is 'RUNNING' !'

This looks like a race condition mixing the execution states order.

### Steps To Reproduce

1. Define an execution featuring the Pause task with a delay defined
2. Load Kestra with a stream of new executions
3. Filter FAILED executions
4. Check Kestra executor logs

### Environment Information

- Kestra Version: 0.7.1
- Operating System (OS / Docker / Kubernetes): CentOS
- Java Version (If not docker): openjdk version "11.0.18" 2023-01-17 LTS
