### ISSUE TITLE
webserver crashes with 502 error with task "load from gcs"

### ISSUE THREAD

**Issue by eregnier** [kestra-io/kestra#112]
triggering flow like

```yaml
id: bla
namespace: my.ns
revision: 6
tasks:
  - id: load_from_gcs
    type: org.kestra.task.gcp.bigquery.LoadFromGcs
    destinationTable: project.dataset.test_load_from_gcs
    format: AVRO
    csvOptions: {}
    avroOptions:
      useAvroLogicalTypes: true
    from:
      - gs://bucket/sample_gcs_to_bq.csv
```

crashes web server with 502 error (it automatically restarts then)

![image](https://user-images.githubusercontent.com/5399780/81912464-e66e2080-95ce-11ea-8569-4aa9a9fed846.png)
