### ISSUE TITLE
Display flow description in Overview when no exexutions

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#1161]
### Feature description

On the Overview tab : display the flow description even if there is no execution yet.

UI : add the description box (like when it appears when there is an execution) on top of the current white box with "ready to see your Kestra flw in action ?..."

**Comment by Ben8t** [comment]
current view 


![Image](https://github.com/kestra-io/kestra/assets/46634684/e1cf177c-f663-40bf-9553-00016d2d3071)

**Comment by Ben8t** [comment]
@Ben8t spec

**Comment by anna-geller** [comment]
still doesn't work

quick win

```yaml
id: test42
namespace: company.team
description: |
  # This is a description
  Test hello there
tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀
```
