### ISSUE TITLE
Trigger files from internal storage cannot be retrieved from the Execution Overview

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#1176]
### Expected Behavior

On the execution Overview tab, if a triggre produces a file there is a link to the file on the tab that should works.

### Actual Behaviour

The link didn't works

### Environment Information

- Kestra Version: 0.9.0-SNAPSHOT
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

### Example flow

```
id: trigger-wikipedia
namespace: io.kestra.tests

triggers:
  - id: wikipedia
    type: io.kestra.plugin.gcp.bigquery.Trigger
    sql: |
      SELECT DATETIME(datehour) as date, title, views FROM `bigquery-public-data.wikipedia.pageviews_2023` 
      WHERE DATE(datehour) = current_date() and wiki = 'fr' and title not in ('Cookie_(informatique)', 'Wikipédia:Accueil_principal', 'Spécial:Recherche')
      ORDER BY datehour desc, views desc
      LIMIT 10
    store: true
    interval: PT1M

tasks:
  - id: write-csv
    type: io.kestra.plugin.serdes.csv.CsvWriter
    from: "{{trigger.uri}}"


```
