### ISSUE TITLE
Add a GitHub plugin

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#1214]
### Feature description

This part of the dbt Setup could be abstracted away into an independent GitHub plugin:

```yaml
      - id: bash
        type: io.kestra.core.tasks.scripts.Bash
        commands:
          - git clone https://github.com/<< organization >>/dbt-project .
        dockerOptions:
          image: bitnami/git:latest
        inputFiles:
          sa.json: |
            { service account json key }
        warningOnStdErr: false
```

In addition, this would allow:
- adding authentication to private GitHub repositories via **Personal Access Token**
- running arbitrary business logic encapsulated into a standalone script (e.g. Python ETL script)
- allow checkout **custom branch**

Nice to have: allow clone only **subdirectory**
