### ISSUE TITLE
Rearrange the order of columns in the Metrics tab

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#1221]
### Feature description

Here is an example flow to reproduce the issue:

```yaml
id: partitions
namespace: dev
description: Process partitions in parallel

tasks:
  - id: getPartitions
    type: io.kestra.core.tasks.scripts.Python
    inputFiles:
      main.py: |
        from kestra import Kestra
        partitions = [f"file_{nr}.parquet" for nr in range(1, 10)]
        Kestra.outputs({'partitions': partitions})

  - id: processPartitions
    type: io.kestra.core.tasks.flows.EachParallel
    value: '{{outputs.getPartitions.vars.partitions}}'
    tasks:
      - id: partition
        type: io.kestra.core.tasks.scripts.Python
        inputFiles:
          main.py: |
            import random
            import time
            from kestra import Kestra
            
            filename = '{{ taskrun.value }}'
            print(f"Reading and processing partition {filename}")
            nr_rows = random.randint(1, 1000)
            processing_time = random.randint(1, 20)
            time.sleep(processing_time)
            Kestra.counter('nr_rows', nr_rows, {'partition': filename})
            Kestra.timer('processing_time', processing_time, {'partition': filename})
```            

This flow processes data in parallel from multiple partitions and stores the result metadata as metrics. It would be more readable/understandable if the Tags column was at the end so that name of the metric and its value are next to each other:

![image](https://user-images.githubusercontent.com/86264395/235889740-fee2a6a0-28f5-4d2d-9ca3-dfd8e66b285d.png)
