### ISSUE TITLE
Pause task in a EachParallel never terminates

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#1223]
### Expected Behavior

When using Pause task is a EachParallel all task terminates.

### Actual Behaviour

When using Pause task is a EachParallel only the first task terminals, the others runs forever.

### Environment Information

- Kestra Version:
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

### Example flow

```
id: "each-pause"
namespace: "io.kestra.tests"

tasks:
  - id: each
    type: io.kestra.core.tasks.flows.EachParallel
    value: ["toto", "tata", "titi"]
    tasks:
      - id: pause
        type: io.kestra.core.tasks.flows.Pause
        delay: PT1S
        tasks:
          - id: log
            type: io.kestra.core.tasks.log.Log
            message: Hello World
```
