### ISSUE TITLE
dbt plugin is broken in the latest release

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#1260]
### Expected Behavior

![image](https://github.com/kestra-io/kestra/assets/86264395/1ef4db8c-1df3-4d47-b785-da81e56767bc)

### Actual Behaviour

See https://github.com/kestra-io/plugin-dbt/blob/3b53b3b0e22a812dcc0dc4c50837d0016826627c/src/main/java/io/kestra/plugin/dbt/cli/AbstractDbt.java#L77

### Environment Information

- Kestra Version: 0.9.0
- Operating System (OS / Docker / Kubernetes): docker develop full image

### Example flow

```yaml
id: gitflow
namespace: dev
tasks:
  - id: dbt
    type: io.kestra.core.tasks.flows.Worker
    tasks:
    - id: clone-repository
      type: io.kestra.plugin.git.Clone
      url: https://github.com/dbt-labs/jaffle_shop
      branch: main
  #    username: <username>
  #    password: <personnalAccessToken>
    - id: dbt-setup
      type: io.kestra.plugin.dbt.cli.Setup
      profiles:
        jaffle_shop:
          outputs:
            dev:
              type: bigquery
              dataset: kestraio
              fixed_retries: 1
              keyfile: sa.json
              location: US
              method: service-account
              priority: interactive
              project: kestraio
              threads: 8
              timeout_seconds: 300
          target: dev
      requirements:
        - dbt-bigquery
      inputFiles:
          sa.json: |
            {"type":"service_account","project_id":"kestraio","private_key_id":"..."}
    - id: dbt-build
      type: io.kestra.plugin.dbt.cli.Build
      debug: true
```
