### ISSUE TITLE
Provide more comprehensive template for flow creation init

### ISSUE THREAD

**Issue by brian-mulier-p** [kestra-io/kestra#1271]
### Feature description

It would be great to have this template instead of the existing one since flows need at least one task to be valid
```
id: ""
namespace: ""
tasks:
  - id: ""
    type: ""
```

**Comment by Ben8t** [comment]
+ removing quotes by default

**Comment by anna-geller** [comment]
+1 to quotes and also it would be nice to have it prefilled to make it even easier e.g. 

```yaml
id: helloThere
namespace: dev
tasks:
  - id: hello
    type: io.kestra.core.tasks.log.Log
    message: Kestra team wishes you a great day! 👋
```
what do you think? this way, opening the editor would be even more encouraging! :)
