### ISSUE TITLE
Docker task improvement

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#1276]
### Feature description

Docker options are sometimes a bit verbose. Could be interesting to reach less verbosity or find a workaround.
For example here is a default. `taskDefault` setup for Python on a custom Docker image

```yaml
taskDefaults:
  - type: io.kestra.core.tasks.scripts.Python
    values:
      virtualEnv: false
      commands:
        - python main.py
      runner: DOCKER
      dockerOptions:
        image: custom_python
        pullImage: false
```
