### ISSUE TITLE
Create a Flowable task type Dag with dependsOn

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#1288]
### Discussed in https://github.com/kestra-io/kestra/discussions/1143

This kind of heavy dependent graph is complicated to do in Kestra: 
![SimpleGraph](https://g.gravizo.com/svg?%20digraph%20G%20{%20start%20-%3E%20a0;%20start%20-%3E%20b0;%20start%20-%3E%20c0;%20start%20-%3E%20d0;%20start%20-%3E%20e0;%20a0%20-%3E%20a1_0;%20a0%20-%3E%20a1_1;%20a0%20-%3E%20a1_2;%20a1_1%20-%3E%20a2_0;%20a1_1%20-%3E%20a2_1;%20b0%20-%3E%20bc1_0;%20c0%20-%3E%20bc1_0;%20bc1_0%20-%3E%20bc2;%20c0%20-%3E%20c1_1;%20c1_1%20-%3E%20e2;%20e0%20-%3E%20e1;%20e1%20-%3E%20e2;%20start%20[shape=Mdiamond];%20}%20))

My suggest is to create a [Flowable task](https://kestra.io/docs/concepts/flows#flowable-task) is will have this structure : 

```yaml
type: io.kestra.core.tasks.flows.Dag
tasks: 
  - task: 
      id: a 
      type: io.kestra.core.tasks.debugs.Return
  - task: 
      id: b 
      type: io.kestra.core.tasks.debugs.Return
  - task: 
      id: c
      type: io.kestra.core.tasks.debugs.Return
    dependsOn : 
      - a
      - b
  - task: 
      id: d
      type: io.kestra.core.tasks.debugs.Return
    dependsOn : 
      - c
```

That will allow more complex dag to be created with out the pain of build manually dependencies.
