### ISSUE TITLE
Nested metrics don't show up in Flow Metric tab

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#1297]
### Expected Behavior

All metrics should be available at the Flow Metric levels, even nested one

### Actual Behaviour

When an execution have nested tasks (for example if task), sub task don't show up in the main Metric dashboard.

![image](https://github.com/kestra-io/kestra/assets/46634684/5eab7a83-5418-4842-8715-5305017c57ee)
![image](https://github.com/kestra-io/kestra/assets/46634684/6db6e531-c5af-4c39-8043-7767d42b0f07)

### Environment Information

- Kestra Version: 0.9.0
- Operating System (OS / Docker / Kubernetes): Docker
- Java Version (If not docker):

### Example flow

```  
- id: isLoading
    type: io.kestra.core.tasks.flows.If
    condition: "{{ inputs.is_load == 'true' }}"
    then:
      - id: load
        type: io.kestra.plugin.gcp.bigquery.LoadFromGcs
        from:
          - '{{ outputs.extract.uri}}'
        destinationTable: "kestra-dev.scraping_demo.cars_data_{{ taskrun.startDate | date('YYYYMMdd') }}"
        autodetect: true
        format: JSON
        
```
