### ISSUE TITLE
Download logs button seems to freeze

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#1320]
### Expected Behavior

When trying to download logs, nothing happens. I validated that my browser doesn't block it -- can someone try to reproduce?

### Actual Behaviour

![image](https://github.com/kestra-io/kestra/assets/86264395/6025c076-07e9-4a07-8a06-bee67b4613d1)

### Environment Information

- Kestra Version: 0.9.0 (develop full image)
- Operating System (OS / Docker / Kubernetes): M1 mac with Kestra running in Docker

### Example flow

```yaml
id: dbtDuckDBVenv
namespace: dev
tasks:
  - id: dbt
    type: io.kestra.core.tasks.flows.Worker
    tasks:
      - id: clone-repository
        type: io.kestra.plugin.git.Clone
        url: https://github.com/dbt-labs/jaffle_shop
        branch: main
      - id: dbt-setup
        type: io.kestra.plugin.dbt.cli.Setup
        profiles:
          jaffle_shop:
            outputs:
              dev:
                type: duckdb
                path: ':memory:'
            target: dev
        requirements:
          - dbt-duckdb==1.4.1
      - id: dbt-build
        type: io.kestra.plugin.dbt.cli.Build
        debug: true
```
