### ISSUE TITLE
Killing a Pause task didn't interrupt the task

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#1326]
### Expected Behavior

Killing a Pause task interrupt the task.

### Actual Behaviour

When you kill a flow with a Pause task, the task is not interrupted, the pause wait for the delay.
Child tasks of the pause task are correctly killed (not executed)

### Environment Information

- Kestra Version: 0.9.0-SNAPSHOT
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

### Example flow

```yaml
id: "wait-with-pause"
namespace: "io.kestra.bugs"

tasks:
  - id: wait
    type: io.kestra.core.tasks.flows.Pause
    delay: PT30S
    tasks:
    - id: log
      type: io.kestra.core.tasks.log.Log
      message: Hello World
```
