### ISSUE TITLE
Support pullPolicy ifNotPresent for docker image

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#1395]
### Expected Behavior

```yaml
id: modalDockerBashTest
namespace: dev
inputs:
  - name: script
    type: FILE
    required: true
  - name: pull
    type: BOOLEAN
    defaults: false # THIS 
tasks:
  - id: bash
    type: io.kestra.core.tasks.scripts.Bash
    commands:
      - modal run modal_getting_started.py
    inputFiles:
      main.py: "{{inputs.script}}"
    dockerOptions:
      image: modal
      pullImage: "{{inputs.pull}}" # THIS
    runner: DOCKER
    env:
      MODAL_TOKEN_ID: "{{envs.modal_token_id}}"
      MODAL_TOKEN_SECRET: "{{envs.modal_token_secret}}"
```

### Actual Behaviour

![image](https://github.com/kestra-io/kestra/assets/86264395/47af4fe0-19e0-4d24-ae60-d994b2078454)

### Environment Information

- Kestra Version:
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):
