### ISSUE TITLE
Inputs with default values should not be required. Template's inputs are gone after saving

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#1396]
### Expected Behavior

When using this template:

```yaml
id: modalGitTemplate
namespace: prod
description: |
  Build an image: docker build -t modal . --platform linux/amd64
  FROM python:3.10-slim
  RUN pip install --no-cache-dir modal-client
  then the modal image is referenced below as a locally available image
inputs:
  - name: repository
    type: STRING
    defaults: "https://github.com/anna-geller/modal"
    required: false
  - name: branch
    type: STRING
    defaults: main
    required: false
  - name: script
    type: STRING
    defaults: getting_started.py
    required: false
  - name: username
    type: STRING
    defaults: anna-geller
    required: false
  - name: dockerImage
    type: STRING
    defaults: modal
    required: false
tasks:
  - id: setup
    type: io.kestra.core.tasks.flows.Worker
    tasks:
      - id: cloneRepository
        type: io.kestra.plugin.git.Clone
        branch: "{{inputs.branch}}"
        password: "{{envs.github_access_token}}"
        url: "{{inputs.repository}}"
        username: "{{inputs.username}}"
      - id: runModal
        type: io.kestra.core.tasks.scripts.Bash
        commands:
          - modal run {{inputs.script}}
        dockerOptions:
          image: "{{inputs.dockerImage}}"
          pullImage: false
        env:
          MODAL_TOKEN_ID: "{{envs.modal_token_id}}"
          MODAL_TOKEN_SECRET: "{{envs.modal_token_secret}}"
        runner: DOCKER
````

The first unexpected issue was that inputs were gone after saving:

![image](https://github.com/kestra-io/kestra/assets/86264395/1bbbcdc2-9270-46bd-a57e-c1abdc56a785)

In order to use this template (written e.g. by another person), I need to know which inputs are available and what are their default values. The current behavior is that inputs are gone from the template as soon as I save the template.

### Inputs need to be redeclared to work: unexpected behavior

I'd expect that this would be enough to use the template:

```yaml
id: modalGitFromTemplate
namespace: prod
tasks:
  - id: modal
    type: io.kestra.core.tasks.flows.Template
    namespace: prod
    templateId: modalGitTemplate
    args:
      script: getting_started.py
```
But atm all inputs must be redefined here, making me question why I would use a template rather than a subflow.

I'd expect that templates behave like subflows:
- Template'able flow defines a set of tasks that are parametrized with `inputs`
- The Template task calls them in a flow by only overwriting inputs that are needed

### Environment Information

- Kestra Version: develop full image on 0.9.0

**Comment by loicmathieu** [comment]
Templates cannot have inputs, the save should have been denied with a validation error.

Inputs can only be added to a flow, which is logical as templates are used in a task (so after flow execution creation which is the time the inputs are handled).

**Comment by anna-geller** [comment]
Thx, is there a way to configure a template to allow overriding only some values when needed as in here?

```yaml
id: modalGitFromTemplate
namespace: prod
tasks:
  - id: modal
    type: io.kestra.core.tasks.flows.Template
    namespace: prod
    templateId: modalGitTemplate
    args:
      script: getting_started.py
```

I'm looking for a way to build this in a modular way so that my template has the entire task configuration that is needed and I can only override those when necessary

**Comment by anna-geller** [comment]
Using subflows allows me to solve that problem, so there is no blocker for the modularity use case:

```yaml
id: modalFlowParametrizedParent
namespace: prod
tasks:
  - id: modal-getting-started
    type: io.kestra.core.tasks.flows.Flow
    namespace: prod
    flowId: modalGitTemplate
    inputs:
      path: getting_started.py
    wait: true
    transmitFailed: true
```

but this makes me wonder why I would ever use templates rather than calling a "templated" flow in another flow with a subflow (`io.kestra.core.tasks.flows.Flow` task)? :)

**Comment by loicmathieu** [comment]
>but this makes me wonder when I would ever use templates rather than calling a "templated" flow in another flow with a subflow (io.kestra.core.tasks.flows.Flow task)? subflows seem to be way more powerful atm than templates :)

Yes subflows are more powerful but also a little more complex to use and have different performance characteristic (as they will be more orchestration behind them).

> Thx, is there a way to configure a template to allow overriding only some values when needed as in here?

You can use the ternary operator to use a variable from the template args or a default:

```
id: modalGitTemplate
namespace: prod
tasks:
  - id: setup
    type: io.kestra.core.tasks.flows.Worker
    tasks:
      - id: runModal
        type: io.kestra.core.tasks.scripts.Bash
        commands:
          - modal run {{parent.outputs.args.script != null ? parent.outputs.args.script : 'script.py'}}
```
    
See https://kestra.io/docs/developer-guide/variables/operator/ternary-operator
