### ISSUE TITLE
Update guided tour Flow

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#1399]
### Feature description

```yaml
# Flow declaration with a mandatory unique identifier, a namespace, and an optional description.
# Flow identifier are unique inside a namespace.
id: welcomeKestra
namespace: demo
description: Welcome to Kestra!

# Flow inputs: each input has a name, a type, and an optional default value.
inputs:
  # We define one input of name 'user' with a default value 'Data Engineer'
  - name: user
    type: STRING
    defaults: Kestra user

# List of tasks that will be executed one after the other.
# Each task must have an identifier unique for the flow and a type.
# Depending on the type of the task, you may have to pass additional attributes.
tasks:
  # This is one of the simplest task: it display a message in the log.
  # The message is passed thanks to the 'message' attribute.
  # We use the variable from the 'input' : {{ and }} are separator of a Pebble expression in which we can access variables.
  - id: hello
    type: io.kestra.core.tasks.log.Log
    message: Hey there, {{ inputs.user }}!

  # This is task run a bash command
  # Here we just 'echo' a message, using again the input variable
  - id: goodbye
    type: io.kestra.core.tasks.scripts.Bash
    commands: 
      - echo See you soon, {{ inputs.user }}!

# To trigger the Flow we use the 'triggers' property
triggers:

  # Here we use a special trigger type 'Schedule' to schedule the Flow every minute
  - id: everyMinute
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "*/1 * * * *"
    inputs:
     name: Kestra master user
```
