### ISSUE TITLE
Show max rather than sum when using the `EachParallel` task

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#1402]
### Expected Behavior

When running 3 script tasks in parallel, I'd expect the aggregated `pandasTransform` task to show the MAX runtime i.e. the time of the longest task, rather than the sum of all tasks, because they were running in parallel:

![image](https://github.com/kestra-io/kestra/assets/86264395/757bba67-b853-487e-882b-fcb02808cb4d)

### Actual Behaviour

flow

```yaml
id: pandas
namespace: dev
tasks:
  - id: csv
    type: io.kestra.core.tasks.flows.EachParallel
    value: ["https://raw.githubusercontent.com/dbt-labs/jaffle_shop/main/seeds/raw_customers.csv", "https://raw.githubusercontent.com/dbt-labs/jaffle_shop/main/seeds/raw_orders.csv", "https://raw.githubusercontent.com/dbt-labs/jaffle_shop/main/seeds/raw_payments.csv"]
    tasks:
    - id: pandasTransform
      type: io.kestra.core.tasks.scripts.Python
      inputFiles:
        data.csv: "{{taskrun.value}}"
        main.py: |
          import pandas as pd
          df = pd.read_csv("data.csv")
          df.info()
      requirements:
        - pandas
```

### Environment Information

- Kestra Version: 0.9.0
