### ISSUE TITLE
Deprecate listeners in favor of triggers

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#1409]
### Feature description

this pattern will be deprecated:

```yaml
id: slackFailureNotifications
namespace: prod
tasks:
  - id: fail
    type: io.kestra.core.tasks.scripts.Bash
    commands:
      - exit 1
listeners:
  - conditions:
      - type: io.kestra.core.models.conditions.types.ExecutionStatusCondition
        in:
          - FAILED
    tasks:
      - id: slack
        type: io.kestra.plugin.notifications.slack.SlackExecution
        url: {{envs.slack_webhook}}
        channel: "#general"
```

in favor of triggers:
```yaml
id: slack-global
namespace: com.kestra.monitoring

tasks:
  - id: send
    type: io.kestra.plugin.notifications.slack.SlackExecution
    url: "{{ namespace.slack.webhook }}"
    channel: "C02U601DNAJ"
    username: "Kestra"
    iconEmoji: ":kestra:"
    executionId: "{{ trigger.executionId }}"

triggers:
  - id: listen
    type: io.kestra.core.models.triggers.types.Flow
    conditions:
      - type: io.kestra.core.models.conditions.types.ExecutionStatusCondition
        in:
          - FAILED
          - WARNING
      - type: io.kestra.core.models.conditions.types.ExecutionNamespaceCondition
        namespace: com.kestra
        prefix: true
```

cc @Ben8t backlog
