### ISSUE TITLE
Invalid yaml don't have any error message 

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#1437]
```yaml
id: "valid"
namespace: "com.kestra.lde"
tasks:
  - id: "plan"
    type: "io.kestra.core.tasks.scripts.Bash"
    inputFiles:
      variables.tf: | 
        test
      variables.tf: | 
        test
    commands: 
      - ls 
```
