### ISSUE TITLE
When disabling the schedule from the form, an error is raised

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#1439]
### Expected Behavior

disabling from the code works, but not from the form

![image](https://github.com/kestra-io/kestra/assets/86264395/e5194dc9-3a4e-4e52-b235-27445a8a09c8)

quick example to reproduce:

```yaml
id: helloParametrizedSchedulesMultiple
namespace: prod

inputs:
  - name: user
    type: STRING
    defaults: Data Engineer
    required: false

tasks:
  - id: hello
    type: io.kestra.core.tasks.log.Log
    message: Hello {{ inputs.user }} from Kestra!

triggers:
  - id: quarterHourly
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "*/15 * * * *"
    disabled: true
    inputs:
     name: user
  - id: everyMinute
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "*/1 * * * *"
    inputs:
     name: user
     value: custom value
```

### Actual Behaviour

![image](https://github.com/kestra-io/kestra/assets/86264395/1d0bb46c-edd6-42bb-8fb2-4d450a1bcc94)

![image](https://github.com/kestra-io/kestra/assets/86264395/23284783-354d-4522-bbba-a2a79a03a7c8)

### Environment Information

- Kestra Version: 0.9.2
