### ISSUE TITLE
Add SECRET-type input

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#1442]
### Feature description

Currently, when we want to have a flow input that holds sensitive information (password, secrets, ...) it will be displayed in the flow execution form when entering the input and in the execution overview tab in the inputs section.

It would be great for security reason to hide the sensitive information from the UI.

## Implementation idea:
Provide a `SECRET` input type, this type of input will not be shown in the UI and will have a password input in the execution form when entering the input value.
We can also mandate base64 of the input but it may makes thinks complicated.

An alternative would be to add a `sensitive=true` property to all inputs making it available for all type of inputs but there is little advantage as a date for ex is not sensitive and a string can still holds any type of value.

**Comment by anna-geller** [comment]
Adding a note that the issue seems to cover multiple features:
1. `inputs`: if the user has sensitive input information, adding a `SECRET`-type input might be a great solution
2. `logs`: when using Secrets, their contents should be obfuscated in the log outputs

To give a specific example for the latter - this flow:

```yaml
id: secrets
namespace: dev
tasks:
  - id: db
    type: io.kestra.core.tasks.log.Log
    message: this is my DB password {{ secret('DB_PASSWORD') }}
```

might output: `this is my DB password *******` without actually logging the output value
