### ISSUE TITLE
Add the autogenerated webhook key to the Flow details page

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#1461]
### Expected Behavior

According to the documentation, a webhook secret key would be generated automatically based on a generated hash. 

Mimimum example:

```yaml
id: ci-cd
namespace: prod
tasks:
  - id: log
    type: io.kestra.core.tasks.log.Log
    message: test
triggers:
  - id: github-webhook
    type: io.kestra.core.models.triggers.types.Webhook
    key: "thisIsASecretKey123" # using "{{secret('WEBHOOK_KEY')}}" doesn't work atm
```

### Actual Behaviour

Currently, this doesn't happen. 

Passing the key from a secret also currently doesn't work.

![image](https://github.com/kestra-io/kestra/assets/86264395/8a621b0b-90df-45e2-815d-78533b0397d1)

### Environment Information

- Kestra Version: 0.9.3 develop-full image, EE also
