### ISSUE TITLE
Flow with multiple flows conditions triggered while the conditions are not met (based on predecessors status)

### ISSUE THREAD

**Issue by jeremycopinlm** [kestra-io/kestra#1472]
### Expected Behavior

Some flow with a flow type trigger and multiple condition type. It's waiting for several jobs to be in SUCCESS status before being triggered.

### Actual Behaviour

We have an execution example in which one of the flow's predecessors is in KILLED status, and the others are in SUCCESS status.
But the condition seems not not be respected resulting in the flow being triggered despite that.

### Environment Information

- Kestra Version: 0.8.1

### Example flow
```yaml
triggers:
- id: multiple-listen-flow
  type: io.kestra.core.models.triggers.types.Flow
  conditions:
  - type: io.kestra.core.models.conditions.types.MultipleCondition
    id: multiple
    window: 86400.0
    windowAdvance: 0.0
    conditions:
      flow1:
        type: io.kestra.core.models.conditions.types.ExecutionFlowCondition
        namespace: some_namespace
        flowId: flow1
     flow2:
        type: io.kestra.core.models.conditions.types.ExecutionFlowCondition
        namespace: some_namespace
        flowId: flow2
     flow3:
        type: io.kestra.core.models.conditions.types.ExecutionFlowCondition
        namespace: some_namespace
        flowId: flow3
      success:
        type: io.kestra.core.models.conditions.types.ExecutionStatusCondition
        in:
        - SUCCESS
```
