### ISSUE TITLE
Infinite loop with subflow

### ISSUE THREAD

**Issue by Skraye** [kestra-io/kestra#1474]
### Expected Behavior

Created a recursive flow create an infinite loop :

```
id: "flow-a"
namespace: "dev"
tasks:
  - id: log
    type: io.kestra.core.tasks.log.Log
    message: hello
  - id: subflow
    type: io.kestra.core.tasks.flows.Flow
    flowId: flow-a
    namespace: dev
```

### Environment Information

- Kestra Version: 0.10.0-snapshot
