### ISSUE TITLE
[SCRIPT 🐍] `LocalFiles` task

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#1478]
### Feature description

_Part of the the Script Workflow revamp_

`LocalFiles` is a task that let users write "inline" files in Kestra. It can used in `WorkingDirectory` or to pass complex files to other tasks (see DSL and example).
Also it can expose files to Kestra Outputs (see DSL and example).

## DSL

```yaml
type: LocalFiles
inputs:
  [Array of files] accessible from {{ outputs.<taskid>.inputs.<filename>}}
outputs:
  [Array of files] accessible from {{ outputs.<taskid>.outputs.<filename> }}
```

## Examples

1. Inside a `WorkingDirectory` - inputs are accessible directly as part of the working directory
```yaml
id: working_directory
type: WorkingDirectory
tasks:
  - id: local_file
    type: LocalFile
    inputs:
      main.py: |
        print("Hello World!")

  - id: run_python
    type: RunPython
    commands:
      - python main.py
```

2. Through outputs

```yaml
  - id: local_file
    type: LocalFile
    inputs:
      main.py: |
        print("Hello World!")

  - id: run_python
    type: RunPython
    commands:
      - python {{ outputs.local_file.inputs['main.py'] }}
```

3. Exposing files.
In this example a Python task create a files inside a `WorkingDirectory`then outputs are exposed through `outputDir` 

```yaml
id: working_directory
type: WorkingDirectory
tasks:

  - id: run_python
    type: RunPython
    commands:
      - pip install requests pandas
    script: |
      import requests
      import pandas as pd
      import io
      data = requests.get("https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv").content
      df = pd.read_csv(io.StringIO(data.decode('utf-8')))
      df.assign(d='2023-06-01').to_csv("{{outputDir()}}/processed_data.csv", index=False)
```
Here data is written to the task outputDir in a file names "processed_data.csv" (so all files written in `outputDir` are exposed in outputs, so users could retrieve them with `outputs.my_task.outputDir["data.csv"]` for example)

---

💡 This feature could be directly linked to the a Multifile Editor feature. We could imagine each time the user click on the task, the right pane open a full editor where he can edit his files smoothly.
