### ISSUE TITLE
[SCRIPT 🐍] `Script` task

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#1479]
### Feature description

_Part of the the Script Workflow revamp_

`Script` is a task to run any kind of script in Kestra.

## DSL

```yaml
type: Script
script:
  [multiline YAML]
commands:
  [Array of string for commands]
dockerImage: [String]
dockerOptions:
  registry: [String]
  pullPolicy: always | if-not-present | never
```

outputs could be exposed thanks to a `outputDir` object, i.e. user could do

```
  pd.to_csv("{{outputDir()}}/data.csv")
```

## Examples

1. 
```yaml
id: run_docker
type: Script
dockerImage: some_image
dockerOptions:
  registry: dockerhub
  pullPolicy: if-not-present
commands:
  - python main.py
```

2.

```yaml
id: working_directory
type: WorkingDirectory
tasks:
  - id: clone
    type: gitClone
    uri: https://github.com/my_repo

  - id: run_specific_bin
    type: Script
    dockerImage: r-base   
    commands:
      - Rscript -e 'install.packages("tidyverse")'
      - Rscript process.R
```
