### ISSUE TITLE
[SCRIPT 🐍] `Python`

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#1480]
### Feature description

_Part of the the Script Workflow revamp_

`Python` is a task that inherit from `Script` task (#1479 ). It let users run python scripts with default value in some properties

## DSL

```yaml
type: Python
script:
  [multiline YAML]
commands:
  [Array of string for commands]
dockerImage: [String] with a default one (probably stable python 3.11)
dockerOptions:
  registry: [String]
  pullPolicy: always | if-not-present | never
```

## Examples

1. 
```yaml
- id: run_python
    type: Python
    script: |
       print("Hello World!")
```

2.

```yaml
id: working_directory
type: WorkingDirectory
tasks:
  - id: local_file
    type: LocalFile
    files:
      main.py: |
        print("Hello World!")

  - id: run_python
    type: RunPython
    commands:
      - python main.py
```

3.

```yaml
  - id: run_python
    type: RunPython
    commands:
      - pip install requests pandas
    script: |
      import requests
      import pandas as pd
      import io
      data = requests.get("https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv").content
      df = pd.read_csv(io.StringIO(data.decode('utf-8')))
      df.assign(d='2023-06-01').to_csv("data/processed_data.csv", index=False)
```

4.

```yaml
id: working_directory
type: WorkingDirectory
tasks:
  - id: clone
    type: GitClone
    url: https://github.com/repo

  - id: run_python
    type: Python
    commands:
      - pip install -r requirements.txt
      - python main.py
```
