### ISSUE TITLE
[SCRIPT 🐍] `Bash` task

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#1481]
### Feature description

_Part of the the Script Workflow revamp_

`Bash` is a task that inherit from `Script` task (#1479 ). It the same as the `Python` one (#1480) but for bash
## DSL

```yaml
type: Bash
script:
  [multiline YAML]
commands:
  [Array of string for commands]
dockerImage: [String] with a default one (probably stable ubuntu)
dockerOptions:
  registry: [String]
  pullPolicy: always | if-not-present | never
```

## Examples

1. 
```yaml
- id: run_bash
    type: bash
    script: |
       #!/bin/bash
       echo 'Hello World'
```

2.

```yaml
id: working_directory
type: WorkingDirectory
tasks:
  - id: local_file
    type: LocalFile
    files:
      script.sh: |
        echo 'Hello World'

  - id: run_bash
    type: Bash
    commands:
      - /bin/bash script.sh
```

3.

```yaml
  - id: run_bash
    type: Bash
    commands:
      - echo 'Hello World'
```
