### ISSUE TITLE
Logging for all task types

### ISSUE THREAD

**Issue by vivane** [kestra-io/kestra#1487]
### Feature description

It would be helpful to have logging property as a standard option for all types of tasks. User might want to record some intermediate information at tasks. This could be useful when logs are monitored and filtered in the system like Elastic or Datadog.

Currently, this is achieved with using "_io.kestra.core.tasks.log.Log_" task. For example:

```
id: test-file
namespace: com.acxiom.vivane.tests

inputs:
  - name: text
    type: STRING

tasks:
  - id: log-1
    type: io.kestra.core.tasks.log.Log
    level: INFO
    message: "Received {{inputs.text}}"
  - id: log-2
    type: io.kestra.core.tasks.log.Log
	level: INFO
    message: "Input is {{inputs.text is json ? 'JSON object' : 'plain text'}}"
  - id: record-file
    type: io.kestra.core.tasks.scripts.Bash
    outputFiles:
      - outFile
    commands:
      - echo {{inputs.text}} >> {{outputFiles.outFile}}
      - echo '::{"outputs":{"sample":"'$(head -c 5 {{outputFiles.outFile}})'"}}::'
      - echo '::{"outputs":{"size":"'$(stat -c %s {{outputFiles.outFile}})'"}}::'
  - id: log-3
    type: io.kestra.core.tasks.log.Log
	level: DEBUG
    message: "Recorded: {{outputs['record-file'].vars.size}} bytes, sample: {{outputs['record-file'].vars.sample}}"
```

If there would be a logging option for all tasks, the flow might look something like following:

```
id: test-file
namespace: com.acxiom.vivane.tests

inputs:
  - name: text
    type: STRING

tasks:
  - id: record-file
    type: io.kestra.core.tasks.scripts.Bash
    outputFiles:
      - outFile
    commands:
      - echo {{inputs.text}} >> {{outputFiles.outFile}}
      - echo '::{"outputs":{"sample":"'$(head -c 5 {{outputFiles.outFile}})'"}}::'
      - echo '::{"outputs":{"size":"'$(stat -c %s {{outputFiles.outFile}})'"}}::'
	logs:
		- INFO: "Received {{inputs.text}}"
		- INFO: "Input is {{inputs.text is json ? 'JSON object' : 'plain text'}}"
		- DEBUG: "Recorded: {{outputs['record-file'].vars.size}} bytes, sample: {{outputs['record-file'].vars.sample}}"

```
