### ISSUE TITLE
Auth to Google Artifact Registry fails even when using `OauthAccessToken`

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#1489]
### Expected Behavior

Example flow:

```yaml
id: gcpArtifactRegistry
namespace: dev
tasks:
  - id: setup
    type: io.kestra.core.tasks.flows.Worker
    tasks:
      - id: cloneRepository
        type: io.kestra.plugin.git.Clone
        branch: main
        url: https://github.com/anna-geller/kestra-flows
      
      - id: fetchAuthToken
        type: io.kestra.plugin.gcp.auth.OauthAccessToken
        projectId: geller
        serviceAccount: "{{envs.gcp_creds}}"

      - id: runModal
        type: io.kestra.core.tasks.scripts.Bash
        commands:
          - python python-scripts/etl_script.py
        dockerOptions:
          image: europe-west3-docker.pkg.dev/geller/flows/python:latest
          dockerConfig: |
            {
              "auths": {
                "europe-west3-docker.pkg.dev": {
                    "username": "_json_keyfile",
                    "password": "{{outputs.fetchAuthToken.accessToken.tokenValue}}"
                    }
              },
              "credHelpers": {
                "europe-west3-docker.pkg.dev": "gcloud"
              }
            }
        runner: DOCKER
```

### Actual Behaviour

![image](https://github.com/kestra-io/kestra/assets/86264395/5b8d5b5f-cd06-4df7-abde-803523ad4f39)

Without running one of these commands (either gcloud auth or docker login) before, it won't work:

```bash
gcloud auth configure-docker europe-west3-docker.pkg.dev
cat mykey.json | docker login -u _json_key --password-stdin https://europe-west3-docker.pkg.dev
```

it might be required to either:
1. add the gcloud CLI plugin https://github.com/orgs/kestra-io/projects/3/views/1?filterQuery=gcloud&pane=issue&itemId=27437640
2. add the Docker plugin https://github.com/orgs/kestra-io/projects/3/views/1?pane=issue&itemId=30479463 

to support it?

### Environment Information

- Kestra Version: develop-full docker 0.10.0

**Comment by tchiotludo** [comment]
I think this one could work reading [this](https://cloud.google.com/container-registry/docs/advanced-authentication#token):  
```yaml 
        dockerOptions:
          image: europe-west3-docker.pkg.dev/geller/flows/python:latest
          dockerConfig: |
            {
              "auths": {
                "europe-west3-docker.pkg.dev": {
                    "username": "oauth2accesstoken",
                    "password": "{{outputs.fetchAuthToken.accessToken.tokenValue}}"
                    }
              }
            }
``` 
`OauthAccessToken` provide access token as I know. 

or this one (that remove the need of `OauthAccessToken` tasks before: 
```yaml 
        dockerOptions:
          image: europe-west3-docker.pkg.dev/geller/flows/python:latest
          dockerConfig: |
            {
              "auths": {
                "europe-west3-docker.pkg.dev": {
                    "username": "_json_keyfile",
                    "password": {{json(envs.gcp_creds) | json | json }}
                    }
              }
            }
        runner: DOCKER
```
Tricky one, where we 
- read the json key to object 
- write it as json 
- write the json as string that will be properly encode and espace to be inserted into the json string. 

Tricky I would admit :thinking:
