### ISSUE TITLE
Add flow-level retry functionality

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#1496]
Add the same retry functionality to a flow as it currently exists on a task.

**Comment by Ben8t** [comment]
I like the idea, would the MVP could be adding the `retry` prop already accessible at task level to the flow level ?

Or did you have more idea in mind 🤔 ?

```
retry: 
    type: constant
    interval: PT0.25S
    maxAttempt: 5
    maxDuration: PT1M
    warningOnRetry: true
```

**Comment by anna-geller** [comment]
The initial idea was to allow rerunning a flow when Execution ends in a Failed state, but after discussing with Ludo, it seems we are aiming for a behavior where retries can be defined on a flow level as a global configuration for tasks but it would then retry any task that fails rather than restarting a flow -- does it make sense? :D 

essentially I understood it in away that it would work as a sort of taskDefaults but for all tasks in a flow rather than for only specific task types

**Comment by Ben8t** [comment]
Ok thanks for the precision -  I think we could do both :

* retry the whole flow
* retry only failed tasks


```yaml
retry:
  scope: flow | task
  type:
  interval: 
  ....
```
