### ISSUE TITLE
Global configuration for `taskDefaults` (using a wildcard `*`)

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#1499]
### Feature description

Sometimes, it's useful to add (or even enforce) a global configuration that is applicable to all tasks from a given plugin or even all plugins.

## Global task configuration for all tasks

If you want to enforce a global policy e.g. a global retry policy to ensure that by default all tasks get retried twice with a 5-minute pause in between:

```yaml
taskDefaults:
  - type: io.kestra.* # global defaults applicable to all core tasks and all plugins
    values:
      retry:
        type: constant # type: string
        interval: PT5M # type: Duration
        maxDuration: PT1H # type: Duration
        maxAttempt: 3 # type: int
        warningOnRetry: true # type: boolean, default is false
```

## Global defaults to reuse credentials or configuration

E.g. to reuse the Google Service Account for multiple GCP-related tasks, the wildcard would be helpful:

```yaml
- type: io.kestra.plugin.gcp.*
  values:
    serviceAccount: '{{ namespace.gcp.serviceAccount }}'
- type: io.kestra.plugin.googleworkspace.*
  values:
    serviceAccount: '{{ namespace.gcp.serviceAccount }}'
```

**Comment by anna-geller** [comment]
possible since 0.14 using plugin prefix:

```yaml
- type: io.kestra.plugin.gcp
  values:
    serviceAccount: '{{ namespace.gcp.serviceAccount }}'
- type: io.kestra.plugin.googleworkspace
  values:
    serviceAccount: '{{ namespace.gcp.serviceAccount }}'
```
