### ISSUE TITLE
Create a failed Execution if we cannot create an execution from any trigger

### ISSUE THREAD

**Issue by stm4lm** [kestra-io/kestra#1533]
### Feature description

If some trigger is misconfigured, create a failed Execution rather than just logging that execution couldn't be created.

Provide a friendly error message showing why Execution failed or couldn't be created and what specifically is misconfigured on the trigger.

The problem : 
When there is a problem in a trigger definition, like a mistyped value by example, the job is not executed. Instead, the trigger enter in a loop and a warning is written to the log until the trigger is corrected 

The solution : 
Don't run test in the trigger, and let the job do it : Execute the job anyway, and put the status to failed due to the error encountered. This would stop polluting logs and allow users to view the problem by monitoring their execution plan

**Comment by tchiotludo** [comment]
Actually, we log [here](https://github.com/kestra-io/kestra/blob/227a161b328d6592003b2b8efe43c7d519276b5d/core/src/main/java/io/kestra/core/schedulers/AbstractScheduler.java#L306) the failed evaluation and kept the trigger as is. 
If it's a schedule, the message will be displayed on each evaluation (so every second).

example of failed trigger: 

```yaml
id: test
namespace: io.kestra.failed

inputs:
- name: date
  type: DATE

tasks:
 - id: "log"
  type: "io.kestra.core.tasks.log.Log"
  level: WARN
  message: "{{task.id}} > {{taskrun.startDate}}"

triggers:
- id: schedule
  type: org.kestra.core.models.triggers.types.Schedule
  cron: * * * * *
  inputs:
    start_date: "invalid"
```
