### ISSUE TITLE
While task

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#1540]
### Feature description

Create a while task with condition

Example of usage : paginate over an API

**Comment by anna-geller** [comment]
It might be helpful to list some examples of which plugins would be used with While task

**Risks and drawbacks:**
1. Violates the declarative approach 
2. It seems most useful with script tasks, which can implement while loops directly within a script
3. Can lead to zombie tasks and issues
4. Users could use it instead of Triggers which already poll for condition

Given you mentioned a web scraping use case, perhaps worth considering a more generic HTTP Trigger instead?

**Comment by anna-geller** [comment]
big fan of solving it via triggers like https://github.com/kestra-io/kestra/issues/1785 

not a fan of While loops :) too many things that can go wrong this way + potentially heavy resource utilization

**Comment by anna-geller** [comment]
thanks for adding more context, that's very helpful

**Comment by anna-geller** [comment]
Proposed syntax using the same configuration (and functionality?) as `retry` to rerun tasks -- this should lead to fewer things required to learn and look up. The name of the property can be `loop`, and the user can leverage the default `timeout` property to avoid a never-ending loop. Lastly, to avoid the definition of looping tasks before creating a condition and within looping, ideally, it should be enough to add only a list of task IDs:

```yaml
  - id: loop_until
    type: io.kestra.core.tasks.flows.While
    condition: "{{ outputs.get_file.count == 1 }}"
    timeout: PT10M
    loopTaskIds:
      - id: get_file
      - id: log
    loop: # 1:1 copy of the retry property but must be different to also support retries - TBD
      type: constant # type: string
      interval: PT10S # type: Duration
      maxDuration: PT1H # type: Duration
      maxAttempt: 5 # type: int
      warningOnRetry: false # type: boolean, default is false
```

Full example flow — the first two tasks are added for reproducibility; they could be invoked in a different flow. A better flow would be waiting for an external process (e.g. AWS/Azure batch job task) to complete: 

```yaml
id: while_loop
namespace: dev

tasks:
  - id: download
    type: io.kestra.plugin.fs.http.Download
    uri: https://raw.githubusercontent.com/kestra-io/datasets/main/csv/orders.csv

  - id: set_state
    type: io.kestra.core.tasks.states.Set
    namespace: true
    name: orders
    data:
      orders: "{{ outputs.download.uri }}"

  - id: get_file
    type: io.kestra.core.tasks.states.Get
    name: orders
    namespace: true

  - id: log    
    type: io.kestra.core.tasks.log.Log
    message: waiting for the state store file to be processed and deleted by another flow

  - id: loop_until
    type: io.kestra.core.tasks.flows.While
    condition: "{{ outputs.get_file.count == 1 }}"
    timeout: PT10M
    loopTaskIds:
      - id: get_file
      - id: log
    loop: # 1:1 copy of the retry property but must be different to also support retries - TBD
      type: constant # type: string
      interval: PT10S # type: Duration
      maxDuration: PT1H # type: Duration
      maxAttempt: 5 # type: int
      warningOnRetry: false # type: boolean, default is false
```

**Comment by loicmathieu** [comment]
I don't understand the syntax and it didn't fit in our existing model for flowable tasks.
Here the flow will execute the tasks download, set_state, get_file and log prior to entering the loop which is a kind of goto ... when we usually defines runnable tasks inside a flowable tasks.

I would prefer this syntax that avoids to learn a new syntax:

```yaml
id: while_loop
namespace: dev

tasks:
  - id: loop_until
    type: io.kestra.core.tasks.flows.While
    condition: "{{ outputs.get_file.count == 1 }}"
    timeout: PT10M
    tasks:
         - id: download
            type: io.kestra.plugin.fs.http.Download
            uri: https://raw.githubusercontent.com/kestra-io/datasets/main/csv/orders.csv
        
          - id: set_state
            type: io.kestra.core.tasks.states.Set
            namespace: true
            name: orders
            data:
              orders: "{{ outputs.download.uri }}"
        
          - id: get_file
            type: io.kestra.core.tasks.states.Get
            name: orders
            namespace: true
        
          - id: log    
            type: io.kestra.core.tasks.log.Log
            message: waiting for the state store file to be processed and deleted by another flow
            loop: # 1:1 copy of the retry property but must be different to also support retries - TBD
      type: constant # type: string
      interval: PT10S # type: Duration
      maxDuration: PT1H # type: Duration
      maxAttempt: 5 # type: int
      warningOnRetry: false # type: boolean, default is false
```
