### ISSUE TITLE
Allow external_revision for flows created from CI/CD (e.g. GITHUB_SHA or custom versioning scheme)

### ISSUE THREAD

**Issue by yuri1969** [kestra-io/kestra#1547]
### Feature description

To allow tracking the flow changes directly in Kestra UI/API it is required to be able to specify a custom _flow version_ besides the auto-incremented internal flow revision. This way it would be possible to actually see and track the flow change from the Kestra UI back to the specific external change request, etc.

For example, flows imported via CI/CD have a Git commit ID associated or use semantic versioning. This information should be accessible in Kestra UI/API.

Similarly flows edited via the web UI editor should allow specifying a version before saving the flow change.

The existing execution/flow labels could be leveraged - eg. `git/version: 2.1.1`.

Related to [867](https://github.com/kestra-io/kestra/issues/867) and [1325](https://github.com/kestra-io/kestra/issues/1325).

**Comment by anna-geller** [comment]
@yuri1969 WDYT about using labels for that purpose? we were talking about it via Slack with @Melkaz and labels seem to fit the requirement very well, as you could filter for specific Executions of a custom version this way. We could investigate how to make that easier to add e.g. a Git commit SHA flow label from CI/CD and Terraform without having to modify the flow code.

**Comment by yuri1969** [comment]
@anna-geller Using execution labels would still keep the editor's _diff view_ present the internal numeric flow versions, right? If so, I would still find that style of versioning confusing.

**Comment by anna-geller** [comment]
TODOs to address it:
- [ ] **Backend change**: extend the flows table with a new varchar column `external_revision` (while still keeping kestra's regular integer `revision` that is always incremented)
- [ ] **Frontend change**: in the Revisions tab, show external revision in addition to regular revision 
- [ ] **CI/CD change**: 
  - [ ] extend terraform [flow resource](https://registry.terraform.io/providers/kestra-io/kestra/latest/docs/resources/flow) with an optional `external_revision` property
  - [ ] extend the [deploy GitHub Action](https://github.com/kestra-io/deploy-action) with optional external_revision field that can be set to e.g. `${{ github.sha }}` by the user

**Comment by anna-geller** [comment]
FYI @AcevedoR moving to the next cycle and removing your assignment as realistically, you have 1 week support + 1 week before vacation so not feasible to finish

**Comment by Ben8t** [comment]
@nkwiatkowski here are some examples:

### Terraform

```
resource "kestra_flow" "example" {
  namespace = "company.team"
  flow_id   = "my-flow"
  external_revision = <any value, i.e., up to the user>
  content   = <<EOT
id: my-flow
namespace: company.team
inputs:
  - name: my-value
    type: STRING

variables:
  first: "1"

tasks:
  - id: t2
    type: io.kestra.core.tasks.log.Log
    message: first {{task.id}}
    level: TRACE

pluginDefaults:
  - type: io.kestra.core.tasks.log.Log
    values:
      message: third {{flow.id}}
EOT
}
```

### GitHub Action

```
name: Kestra CI/CD
on: 
  workflow_dispatch:

jobs:
  kestra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: deploy
        uses: kestra-io/deploy-action@master
        with:
          namespace: prod
          directory: ./flows
          resource: flow
          external_revision: ${{ github.sha }}
          server: ${{ secrets.KESTRA_HOST }}
          user: ${{ secrets.KESTRA_USER }}
          password: ${{ secrets.KESTRA_PASSWORD }}
          delete: false
```

### From the API globally speaking, and so with plugins e.g. TenantSync

No change on the plugin DSL itself afaik, the API should automatically fill the new `external_revision` property if it's present in the flow definition

```
## No change here, flows with property external_revision filled will be deployed properly and the external revision will appear in the Revisions tab, in addition to regular revision
id: tenant_sync_git
namespace: system
tasks:
  - id: sync
    type: io.kestra.plugin.git.TenantSync
    sourceOfTruth: GIT
    whenMissingInSource: DELETE
    protectedNamespaces:
      - system
    url: https://github.com/fdelbrayelle/plugin-git-qa
    username: fdelbrayelle
    password: "{{ secret('GITHUB_ACCESS_TOKEN') }}"
    branch: main
    gitDirectory: kestra
    kestraUrl: "http://localhost:8080"
    auth:
      username: "{{ secret('KESTRA_USERNAME') }}"
      password: "{{ secret('KESTRA_PASSWORD') }}"
```

If you see this need more discussion on the plugin side, please schedule a meeting with me/ludo/francois.
