### ISSUE TITLE
Unable to change status for a running execution 

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#1561]
On this running execution, we should be allows to change status off the last running task to mark as killed, failed. 
The button is disabled on the gantt page, why?  

```yaml
{
  "id": "KiGuMzhCkG5e4615nfXFK",
  "namespace": "dbt",
  "flowId": "details-dbt",
  "flowRevision": 1,
  "taskRunList": [
    {
      "id": "6JjbCaGky7L5SCOpod1aUK",
      "executionId": "KiGuMzhCkG5e4615nfXFK",
      "namespace": "dbt",
      "flowId": "details-dbt",
      "taskId": "log",
      "attempts": [
        {
          "state": {
            "current": "SUCCESS",
            "histories": [
              {
                "state": "CREATED",
                "date": "2023-06-15T12:00:00.500Z"
              },
              {
                "state": "RUNNING",
                "date": "2023-06-15T12:00:00.500Z"
              },
              {
                "state": "SUCCESS",
                "date": "2023-06-15T12:00:00.529Z"
              }
            ],
            "duration": "PT0.029S",
            "startDate": "2023-06-15T12:00:00.500Z",
            "endDate": "2023-06-15T12:00:00.529Z"
          }
        }
      ],
      "state": {
        "current": "SUCCESS",
        "histories": [
          {
            "state": "CREATED",
            "date": "2023-06-15T11:59:59.837Z"
          },
          {
            "state": "RUNNING",
            "date": "2023-06-15T12:00:00.485Z"
          },
          {
            "state": "SUCCESS",
            "date": "2023-06-15T12:00:00.529Z"
          }
        ],
        "duration": "PT0.692S",
        "startDate": "2023-06-15T11:59:59.837Z",
        "endDate": "2023-06-15T12:00:00.529Z"
      }
    },
    {
      "id": "5mZlpTPIQJETTdJBpZwdpK",
      "executionId": "KiGuMzhCkG5e4615nfXFK",
      "namespace": "dbt",
      "flowId": "details-dbt",
      "taskId": "executeDBT",
      "attempts": [
        {
          "state": {
            "current": "RUNNING",
            "histories": [
              {
                "state": "CREATED",
                "date": "2023-06-15T12:00:01.176Z"
              },
              {
                "state": "RUNNING",
                "date": "2023-06-15T12:00:01.176Z"
              }
            ],
            "duration": "PT0S",
            "startDate": "2023-06-15T12:00:01.176Z"
          }
        }
      ],
      "state": {
        "current": "RUNNING",
        "histories": [
          {
            "state": "CREATED",
            "date": "2023-06-15T12:00:01.124Z"
          },
          {
            "state": "RUNNING",
            "date": "2023-06-15T12:00:01.173Z"
          }
        ],
        "duration": "PT0.049S",
        "startDate": "2023-06-15T12:00:01.124Z"
      }
    }
  ],
  "variables": {
    "schedule": {
      "date": "2023-06-15T12:00:00Z",
      "next": "2023-06-15T12:15:00Z",
      "previous": "2023-06-15T11:45:00Z"
    }
  },
  "state": {
    "current": "RUNNING",
    "histories": [
      {
        "state": "CREATED",
        "date": "2023-06-15T11:59:59.554Z"
      },
      {
        "state": "RUNNING",
        "date": "2023-06-15T11:59:59.837Z"
      }
    ],
    "duration": "PT0.283S",
    "startDate": "2023-06-15T11:59:59.554Z"
  },
  "originalId": "KiGuMzhCkG5e4615nfXFK",
  "trigger": {
    "id": "schedule",
    "type": "io.kestra.core.models.triggers.types.Schedule",
    "variables": {
      "date": "2023-06-15T12:00:00Z",
      "next": "2023-06-15T12:15:00Z",
      "previous": "2023-06-15T11:45:00Z"
    }
  }
}
```
