### ISSUE TITLE
WorkingDirectory should work with flowable tasks too

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#1573]
### Feature description

Use case: I want to clone a Git repository into a working directory, then trigger multiple script tasks in parallel. All these script tasks need access to the code from the repository so cloning it multiple times adds extra overhead
currently, this use case is not possible, even though it seems quite basic

**Comment by anna-geller** [comment]
with the addition of Namespace Files editor + inputFiles + outputFiles + namespaceFiles properties, this seems less urgent as it's doable now  

example:

```yaml
id: parallel_python
namespace: blueprint

tasks:
  - id: parallel
    type: io.kestra.core.tasks.flows.EachParallel
    value: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"]
    tasks:
      - id: python
        type: io.kestra.plugin.scripts.python.Commands
        namespaceFiles: 
          enabled: true
        runner: DOCKER
        docker:
          image: ghcr.io/kestra-io/pydata:latest
        commands:
          - python parametrized.py --num {{ workerTaskrun.value }}
```


closing for now
