### ISSUE TITLE
Allow providing custom inputs when resuming a Paused task (human in the loop)

### ISSUE THREAD

**Issue by vivane** [kestra-io/kestra#1581]
## Scope

- [ ] add `onResume` to the `Pause` task allowing to provide custom inputs when resuming the execution. 
- [ ] add a UI form on Resume akin to the one when creating a new Execution from the UI. When you resume the execution from the UI, you can provide the required inputs in a form. Those inputs are validated against the schema defined in the Pause task and stored in internal storage (as regular inputs) so that you can use them in the subsequent tasks.
- [ ] store those user-provided values as outputs of the Pause task. E.g. to access the input reason in the flow below, you can use the familiar outputs syntax `{{ outputs.waitForApproval.onResume.reason }}`

```yaml
id: vacation_approval_process
namespace: dev

inputs:
  - id: request.name
    type: STRING
    defaults: Rick Astley

  - id: request.start_date
    type: DATE
    defaults: 2024-07-01

  - id: request.end_date
    type: DATE
    defaults: 2024-07-07

  - id: slack_webhook_uri
    type: URI
    defaults: https://reqres.in/api/slack

tasks:
  - id: sendApprovalRequest
    type: io.kestra.plugin.notifications.slack.SlackIncomingWebhook
    url: "{{ inputs.slack_webhook_uri }}"
    payload: |
      {
        "channel": "#vacation",
        "text": "Validate holiday request for {{ inputs.request.name }}. To approve the request, click on the `Resume` button here http://localhost:28080/ui/executions/{{flow.namespace}}/{{flow.id}}/{{execution.id}}"
      }

  - id: waitForApproval
    type: io.kestra.core.tasks.flows.Pause
    onResume:
      - id: approved
        description: Approve the request?
        type: BOOLEAN
        defaults: true
      - id: reason
        description: Reason for approval or rejection?
        type: STRING
        defaults: Approved

  - id: approve
    type: io.kestra.plugin.fs.http.Request
    uri: https://reqres.in/api/products
    method: POST
    contentType: application/json
    body: "{{ inputs.request }}"

  - id: log
    type: io.kestra.core.tasks.log.Log
    message: Status is {{ outputs.waitForApproval.onResume.reason }}. Process finished with {{ outputs.approve.body }}
```

## Use case

Currently, pause task - _io.kestra.core.tasks.flows.Pause_ - does not allow user to provide any additional input/output to adjust the data processing once flow resumes.

Consider following scenario:
1. Flow loads the file and infers its schema.
2. Then, flow pauses letting user a chance to review the schema and decide on fields which should be transformed/loaded/discarded/etc.
3. After, flow should proceed processing with user decision.

It would be useful if:
1. Pause task would define some output which could be referred by subsequent tasks. The output should be optional if no input is required.
2. UI/API would provide a way to define some input (in form of JSON object, for example) when status of pause task is changed to be running. This input would go into the pause task output and could be used by the rest of the flow.

This could be implemented as a completely new task - say, _io.kestra.core.tasks.flows.Input_ - leaving existing pause task to work as initially designed.
