### ISSUE TITLE
Empty inputs are not added to the list of inputs

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#1587]
### Issue description

As example, see the followning flow:

```yaml
id: trial
namespace: iss.trial
inputs:
- name: givenName
  type: STRING
  required: false
tasks:
- id: if
  type: io.kestra.core.tasks.flows.If
  condition: "{{inputs.givenName}}"
  then:
    - id: when-true
      type: io.kestra.core.tasks.log.Log
      message: 'Condition was true'
  else:
    - id: when-false
      type: io.kestra.core.tasks.log.Log
      message: 'Condition was false'
```

It didn't work as if the `givenName` input is not set, it will not be added to the list of inputs so the `inputs` variable will be missing (or if other inputs exist, the `inputs.givenName` variable will be missing). 

To make it work we must use the coalescing operator so the condition becomes:
```yaml
condition: "{{inputs.givenName ?? false}}"
```

This can be surprising and more complex than needed.

Maybe we can add non-set inputs in the list of inputs with a null value.
