### ISSUE TITLE
Flow with `taskDefaults` can't be saved

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#1610]
### Expected Behavior

![image](https://github.com/kestra-io/kestra/assets/86264395/9f9408ed-96c8-4cc9-a21e-340eada47f4c)

example flow to reproduce:

```yaml
id: airbyteCloudDbt
namespace: dev

tasks:
  - id: data-ingestion
    type: io.kestra.core.tasks.flows.Parallel
    tasks:
      - id: salesforce
        type: io.kestra.plugin.airbyte.cloud.jobs.Sync
        connectionId: e3b1ce92-547c-436f-b1e8-23b6936c12ab
      - id: google-analytics
        type: io.kestra.plugin.airbyte.cloud.jobs.Sync
        connectionId: e3b1ce92-547c-436f-b1e8-23b6936c12cd
      - id: facebook-ads
        type: io.kestra.plugin.airbyte.cloud.jobs.Sync
        connectionId: e3b1ce92-547c-436f-b1e8-23b6936c12ef
  
  - id: dbt
    type: io.kestra.core.tasks.flows.WorkingDirectory
    tasks:
    - id: cloneRepository
      type: io.kestra.plugin.git.Clone
      url: https://github.com/dbt-labs/jaffle_shop
      branch: main
    
    - id: dbt-build
      type: io.kestra.plugin.dbt.cli.Build
      runner: DOCKER
      dbtPath: /usr/local/bin/dbt
      dockerOptions:
        image: ghcr.io/kestra-io/dbt-bigquery:latest
      inputFiles:
        .profile/profiles.yml: |
          jaffle_shop:
            outputs:
              dev:
                type: bigquery
                dataset: your_big_query_dataset_name
                fixed_retries: 1
                keyfile: sa.json
                location: EU
                method: service-account
                priority: interactive
                project: your_big_query_project
                threads: 8
                timeout_seconds: 300
            target: dev
        sa.json: |
          {{envs.gcp_creds}}

taskDefaults:
  - type: io.kestra.plugin.airbyte.cloud.jobs.Sync
    values:
      url: http://host.docker.internal:8000/
      token: "{{envs.airbyte_cloud_api_token}}"
```

### Environment Information

- Kestra Version: 0.10.0 develop
