### ISSUE TITLE
Wrong input type error message is not self eplanatory

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#1632]
### Expected Behavior

When a wrong input type is written, the error message must told about input.

### Actual Behaviour

The error message is cryptic, see

![image](https://github.com/kestra-io/kestra/assets/1819009/9790338a-4e43-448c-9cdf-e52e8e1977c9)

### Environment Information

- Kestra Version: 0.9.0
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

### Example flow

```yaml
id: "get_flow"
namespace: "data.integration.flows"
inputs:
  - name: uri
    type: String
tasks:
  - id: get_data
    type: io.kestra.core.tasks.scripts.Bash
    commands:
      - echo "$API_TOKEN"
      - "flow run {{ inputs.uri }}"
    env:
      API_TOKEN: MIIEvgIBADANBgkqhkiG9w0BAQE---FAASCBKgwgg
```
