### ISSUE TITLE
OpenAI plugin

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#1633]
The initial scope may only include: 

1. [Chat Completion](https://platform.openai.com/docs/guides/gpt/chat-completions-api) task - this will already allow functionality such as translation as well.
2. [Image generation](https://platform.openai.com/docs/guides/images) task

Example flow syntax based on the API:

1. Completion:

```yaml
id: chatCompletion
namespace: dev
tasks:
  - id: questionAnswering
    type: io.kestra.plugin.openai.completion.Create
    !apiKey: mykey
    model: "gpt-3.5-turbo-0613" should be the default for now
    !prompt: What is kestra.io?
    temperature: 0.2 # float number between 0 and 2, default can be set to 1
    messages: a list of dictionaries (list of maps - see example below) 
      - role: system
        content: "You are a helpful assistant."
      - role: user
        content: prompt (it should take the value from the "prompt" argument above)
```

`!` shows the required attributes. The rest can use sensible defaults. For the `messages` the default should be set to `[{"role": "system", "content": "You are a helpful assistant."}, {"role": "user", "content": prompt}]`

Example in Python:

```python
import openai
import os

from dotenv import load_dotenv, find_dotenv

load_dotenv(find_dotenv())

openai.api_key = os.getenv("OPENAI_API_KEY")


def get_completion(prompt: str, model: str = "gpt-4") -> str:
    messages = [{"role": "user", "content": prompt}]
    response = openai.ChatCompletion.create(
        model=model,
        messages=messages,
        temperature=0.5,
    )
    print(response)
    return response.choices[0].message["content"]


instructions = f"""
Translate the text below to French:
Good morning, how are you today?
"""
message = get_completion(instructions)
print(message)
```

2. Image generation with DALL-E

```yaml
id: imageGeneration
namespace: dev
tasks:
  - id: cuteCat
    type: io.kestra.plugin.openai.image.Create
    !apiKey: mykey
    !prompt: A cute cat
    size: 256x256
```

By default, this flow would generate a single image and download it from the request to internal storage.

Here is an example in Python:

```python
from dotenv import load_dotenv, find_dotenv
import openai
import os
import requests


load_dotenv(find_dotenv())

openai.api_key = os.getenv("OPENAI_API_KEY")


def download_image(URL: str, filename: str) -> None:
    response = requests.get(url, stream=True)
    if response.status_code == 200:
        with open(filename, "wb") as file:
            for chunk in response.iter_content(1024):
                file.write(chunk)
    else:
        print(f"Failed to download image. Status code: {response.status_code}")


def generate_image(prompt: str, size: str = "512x512") -> None:
    response = openai.Image.create(prompt=prompt, n=1, size=size)
    url = response["data"][0]["url"]
    filename = prompt.lower().replace(" ", "_") + ".jpg"
    download_image(url, filename)


generate_image("A cute cat")
```
