### ISSUE TITLE
Copy Flow button is not working anymore

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#1693]
### Expected Behavior

When I hit the Copy button on the flow page, a new flow with the same content should be created

### Actual Behaviour

The "default" flow is created with the following content: 

```
id: hello-world
namespace: dev
tasks:
  - id: hello
    type: io.kestra.core.tasks.log.Log
    message: Kestra team wishes you a great day! 👋
```

### Steps To Reproduce

1. Go to the editor of an existing flow
2. Click on Actions -> Copy

### Environment Information

- Kestra Version: 0.10.0
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):
