### ISSUE TITLE
Moving outside task in place of a Dag subtask which others depend on break everything

### ISSUE THREAD

**Issue by brian-mulier-p** [kestra-io/kestra#1697]
### Actual Behaviour

Here I moved "hello" task which was outside, in place of the "b" task which is a dependance of "a" task.

It breaks everything -> yaml editor was properly updated (although incorrect due to missing dependency) while the topology looks buggy and can't move my "hello" task except by drag&dropping on the underneath "b" task which moves back the "hello" task outside and "b" task inside due to flow becoming valid again
![image](https://github.com/kestra-io/kestra/assets/37618489/f9c5309f-d5b8-40c1-aac4-ff4fe8a4bea0)

### Steps To Reproduce

Create a Dag task with two task, including one which is dependant of the other
Create a task outside of the Dag
Move the outside task in place of the dependance task

-> If you move the outside task on a dag task which has no dependency it works properly

### Environment Information

- Kestra Version: 0.10.0-SNAPSHOT
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

### Example flow

```
id: hello-worldf
namespace: dev
labels:
  some: flowLabel
tasks:
  - id: dag
    type: io.kestra.core.tasks.flows.Dag
    tasks:
      - task:
          id: a
          type: io.kestra.core.tasks.flows.Flow
          namespace: dev
          flowId: hello-world
        dependsOn:
          - b
      - task:
          id: b
          type: io.kestra.core.tasks.scripts.Bash
          commands:
            - "sleep 5"
      - task:
          id: c
          type: io.kestra.core.tasks.log.Log
          message: Ended all
        dependsOn:
          - a
  - id: hello
    type: io.kestra.core.tasks.log.Log
    message: Kestra team wishes you a great day! 👋
```
