### ISSUE TITLE
Debezium MySQL plugin task does not capture any records

### ISSUE THREAD

**Issue by alexnikitchuk** [kestra-io/kestra#1728]
### Expected Behavior

Debezium MySQL plugin task must do an initial snapshot as configured and capture all the records from the configured table.

### Actual Behaviour

Debezium MySQL plugin task does not capture any records and also does not show any meaningful logs.
Here is what I see 
<img width="1701" alt="image" src="https://github.com/kestra-io/kestra/assets/8694829/d0f5a238-517a-4b82-9b24-339f3ab8c024">

Also outputs are empty:
<img width="1362" alt="image" src="https://github.com/kestra-io/kestra/assets/8694829/cdee18f2-fe2e-4cc0-ad41-2f3dd29b0092">

### Steps To Reproduce

- Run Kestra
- setup flow
- trigger execution

### Environment Information

- Kestra Version: 0.10.0
- Operating System (OS / Docker / Kubernetes): MacOS 13.4 /Docker
- Java Version (If not docker): N/A

### Example flow

```
id: test-pipeline
namespace: dev
tasks:
  - id: "capture"
    type: "io.kestra.plugin.debezium.mysql.Capture"
    serverId: "5401"
    snapshotMode: INITIAL
    properties:
      snapshot.locking.mode: none
    hostname: db.host.com
    port: "3306"
    username: user
    password: pass
    maxRecords: 10
    deleted: ADD_FIELD
    deletedFieldName: "is_deleted"
    metadata: ADD_FIELD
    metadataFieldName: "metadata"
    key: ADD_FIELD
    ignoreDdl: true
    format: WRAP
    includedTables: ".*Tenant"
```
