### ISSUE TITLE
Add an Apache Beam plugin

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#1737]
### **Repository**
This feature should be implemented in the following repository:  
👉 [https://github.com/kestra-io/plugin-beam](https://github.com/kestra-io/plugin-beam)

---

### **Summary**
Implement a Kestra plugin to execute **Apache Beam** pipelines, providing a unified model for **batch** and **streaming** data processing, compatible with major **runners** (Flink, Spark, Dataflow, etc.).

This plugin will:
- Execute Beam pipelines **declared in YAML** (inline or from a file),
- Dynamically select the **runner** and **SDK** (Java or Python),
- Transpose **Beam metrics** into Kestra’s native metrics system.

---

## 🎯 Goals
- Create native **Beam Tasks** for Kestra.  
- Support **YAML definition** either inline or via an external file.  
- Manage **runners** as a portable `enum`.  
- Integrate **Beam metrics** into Kestra’s metric system (`runContext.metric`).  
- Support **multi-SDK (Java / Python)** for both ETL and AI/RAG workflows.

---

### 1. `io.kestra.plugin.beam.BeamPipeline`
Executes a complete Beam pipeline from either a YAML file or an inline YAML definition.

#### 🔧 Inputs
| Field | Type | Description |
|--------|------|-------------|
| `file` | `string` *(optional)* | Path to a YAML file in the flow workspace (`/flows/...`) |
| `definition` | `string` *(optional)* | Inline YAML content describing the Beam pipeline |
| `runner` | `BeamRunner` *(enum)* | Runner used (see enum below) |
| `sdk` | `BeamSDK` *(enum)* | SDK to use: `JAVA` or `PYTHON` |
| `options` | `map<string, string>` *(optional)* | Beam options (`project`, `region`, `tempLocation`, etc.) |
| `runnerConfig` | `map<string, any>` *(optional)* | Runner-specific configuration (see examples below) |
| `requirements` | `list<string>` *(optional)* | Python packages to install if `sdk=PYTHON` |

> **Note:** Either `file` **or** `definition` must be provided — not both.  
> This constraint will be validated using `@AssertTrue` within the plugin.

#### 📤 Outputs
- Beam execution logs  
- **Transposed metrics into Kestra**  
- Output PCollections (if applicable)

---

## 🧮 Enum BeamRunner
```java
public enum BeamRunner {
    DIRECT,
    FLINK,
    SPARK,
    DATAFLOW
}
```
> - **DIRECT**: Local runner (testing, CI/CD)  
> - **FLINK**: Cluster or Docker-based streaming execution  
> - **SPARK**: Distributed batch runner  
> - **DATAFLOW**: Managed GCP runner for large-scale workloads

---

## 🧭 Runner Execution Contexts

| Runner | Environment | How it runs | Requirements | Typical Use Case |
|--------|--------------|--------------|----------------|------------------|
| **DIRECT** | Local | Runs directly within the Kestra worker JVM using the `DirectRunner` | No extra setup | Unit testing, quick validation, CI/CD |
| **FLINK** | Cluster / Docker | Submits the pipeline to a running **Flink cluster** via REST API or job JAR | Flink cluster accessible via `flinkRestUrl` | Real-time streaming, stateful ETL |
| **SPARK** | Cluster / YARN / K8s | Launches jobs via `spark-submit` or REST API | Spark cluster or Spark-on-K8s setup | Large-scale batch ETL |
| **DATAFLOW** | Managed Cloud (GCP) | Submits job to **Google Cloud Dataflow** using Beam’s DataflowRunner | GCP credentials, region, project ID | Scalable managed batch/streaming pipelines |

---

### 🔥 Example 1 — Spark Runner
```yaml
tasks:
  - id: run-beam-spark
    type: io.kestra.plugin.beam.BeamPipeline
    sdk: JAVA
    runner: SPARK
    runnerConfig:
      master: spark://spark-master:7077
      deployMode: cluster
      sparkHome: /opt/spark
      jarPath: /app/jars/beam-job.jar
      driverMemory: 2g
      executorMemory: 4g
      executorCores: 2
      additionalArgs:
        - "--conf"
        - "spark.sql.shuffle.partitions=200"
    options:
      tempLocation: s3://my-bucket/tmp/
      project: analytics
```

---

### 🌊 Example 2 — Flink Runner
```yaml
tasks:
  - id: run-beam-flink
    type: io.kestra.plugin.beam.BeamPipeline
    sdk: JAVA
    runner: FLINK
    runnerConfig:
      executionMode: cluster
      flinkRestUrl: http://flink-jobmanager:8081
      parallelism: 8
      savepointDir: s3://my-bucket/savepoints/
      checkpointDir: s3://my-bucket/checkpoints/
      jarPath: /app/jars/beam-job.jar
      stateBackend: rocksdb
    options:
      tempLocation: s3://my-bucket/tmp/
      project: real-time-pipeline
```

---

### ☁️ Example 3 — Dataflow Runner
```yaml
tasks:
  - id: run-beam-dataflow
    type: io.kestra.plugin.beam.BeamPipeline
    sdk: JAVA
    runner: DATAFLOW
    runnerConfig:
      projectId: my-gcp-project
      region: europe-west1
      tempLocation: gs://my-bucket/tmp/
      stagingLocation: gs://my-bucket/staging/
      serviceAccountKey: /secrets/gcp-sa.json
      update: false
      maxWorkers: 10
      workerMachineType: n1-standard-4
      network: default
      subnetwork: regions/europe-west1/subnetworks/default
    options:
      jobName: kestra-beam-dataflow
```

---

### 🧠 Implementation Note for Plugin Developers
Each runner configuration could be modeled as a **typed POJO**, e.g. `SparkRunnerConfig`, `FlinkRunnerConfig`, `DataflowRunnerConfig`.  
The plugin deserializer can load the correct configuration class based on the selected runner.

Example pseudo-code:
```java
switch (runner) {
    case FLINK -> FlinkExecutor.submit(flinkConfig, pipeline);
    case SPARK -> SparkExecutor.submit(sparkConfig, pipeline);
    case DATAFLOW -> DataflowExecutor.submit(dataflowConfig, pipeline);
    default -> pipeline.run();
}
```

---

## 📈 Beam → Kestra Metrics Integration

The plugin will map Beam’s native metrics (`Counters`, `Distributions`, `Gauges`) to Kestra metrics through the `RunContext`.

### 🔄 Core Logic
```java
for (MetricResult<Long> counter : result.metrics().queryMetrics(null).counters()) {
    runContext.metric(Counter.of(counter.name().getName(), counter.attempted()));
}
```

### 🔢 Mapping
| Beam Metric Type | Kestra Metric Type | Example |
|------------------|--------------------|----------|
| `Counter<Long>` | `Counter.of(String, long)` | `recordsProcessed` |
| `Distribution` | `Timer.of(String, duration)` | `processingLatency` |
| `Gauge` | `Gauge.of(String, double)` | `memoryUsage`, `queueDepth` |

> This mapping will expose Beam KPIs directly in Kestra’s dashboards, alerts, and execution graphs.

---

## 📚 References
- [Beam YAML SDKs](https://beam.apache.org/documentation/sdks/yaml/)  
- [Beam Programming Guide](https://beam.apache.org/documentation/programming-guide/)  
- [Kestra Plugin Development Guide](https://kestra.io/docs/developer-guide/plugin-development)
