### ISSUE TITLE
Infinite loop in the executor if a flowable task fail

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#1745]
### Expected Behavior

Even if a flowable task fail, there should not be any infinite loop in the executor.

### Actual Behaviour

The executor entre an infinite loop as it will not be able to return the next task to run so the same task will be executed again and again.

### Environment Information

- Kestra Version: 0.10
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

### Example flow

```yaml
id: infinite-looping
namespace: bug
tasks:
- id: channel
  type: io.kestra.core.tasks.flows.EachParallel
  tasks:
  - id: type
    type: io.kestra.core.tasks.flows.EachParallel
    tasks:
    - id: vision
      type: io.kestra.core.tasks.flows.EachParallel
      tasks:
      - id: metaseg_date
        type: io.kestra.core.tasks.flows.EachParallel
        tasks:
          - id: if
            type: io.kestra.core.tasks.flows.If
            condition: "{{parents[0].taskrun.value == 'CUMULATIVE' and {% for entry in json(taskrun.value) %}{{ entry.key }}{% endfor %}== 'NEW_MONTH'}}"
            then:
              - id: when-true
                type: io.kestra.core.tasks.log.Log
                message: 'Condition was true'
            else:
              - id: when-false
                type: io.kestra.core.tasks.log.Log
                message: 'Condition was false'
        value: "[{\"NEW_MONTH\":\"2018-01-01\"}, {\"NEW_YEAR\":\"2018-01-01\"}, {\"EXISTING\":\"2018-01-01\"}]"
      value: "[\"MONTHLY\", \"CUMULATIVE\"]"
    value: "[\"INHABITANT\", \"MEMBERS\"]"
  value: "[\"OFFLINE_ONLY\", \"ONLINE_ONLY\", \"OMNICANAL\"]"
```
