### ISSUE TITLE
Kestra will 

### ISSUE THREAD

**Issue by baogorek** [kestra-io/kestra#1751]
### Expected Behavior

I'm running locally on an ubuntu box and I put the command `bash` in a shell op. The execution hangs forever without any output or indication that something is wrong. This also happens when you use `su`. I realize these commands probably shouldn't be used in the first place, but if they are, I would expect the system to fail instead of hang.

### Actual Behaviour

The execution runs forever without any output.

### Steps To Reproduce

./kestra-0.10.0 server local

Flow:
```
id: i-will-hang-forever
namespace: prod
tasks:
  - id: daily-fact
    type: io.kestra.core.tasks.flows.WorkingDirectory
    tasks:
    - id: bash
      type: io.kestra.core.tasks.scripts.Bash
      commands:
        - bash
        - echo "hello"
 ```

### Environment Information

- Kestra Version: 0.10.0
- Operating System (OS / Docker / Kubernetes): Ubuntu 20.04.6 LTS
- Java Version (If not docker): openjdk 17.0.7

### Example flow

See Steps to Reproduce

**Comment by anna-geller** [comment]
Running only `bash` will enter an interactive terminal session, waiting for further input, which explains why the execution "hangs" :) 

If you want to run a specific bash script, try: `bash yourscript.sh` and this will solve the issue

alternatively, you can pass an entire content of the bash script like so: 

```yml
id: hello-bash
namespace: dev
tasks:
  - id: hello
    type: io.kestra.plugin.scripts.shell.Script
    runner: PROCESS
    script: |
      #!/bin/bash
      echo "Hey there"
      echo "Today's date is:"
      date
```
