### ISSUE TITLE
Allow displaying non-aggregated metrics

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#1753]
### Feature description

Often, I want to see all metrics values over time rather than just seeing an aggregated value such as min/max/sum/avg. It would be great to support it. 

Simple reproducer:
```yml
id: outputsMetricsPython
namespace: dev
inputs:
  - name: attempts
    type: INT
    defaults: 10

tasks:
  - id: py
    type: io.kestra.plugin.scripts.python.Script
    warningOnStdErr: false
    docker:
      image: ghcr.io/kestra-io/pydata:latest
    script: |
      import timeit
      from kestra import Kestra

      attempts = {{inputs.attempts}}
      modules = ['pandas', 'requests', 'kestra', 'faker', 'csv', 'random']
      results = {}

      for module in modules:
          time_taken = timeit.timeit(f'import {module}', number=attempts)
          results[module] = time_taken
          Kestra.timer(module, time_taken, tags=dict(nr_attempts=attempts))

      Kestra.outputs(results)
```

![image](https://github.com/kestra-io/kestra/assets/86264395/266f1443-7af2-4b3e-bdb3-9c547aa5491e)
