### ISSUE TITLE
Docker container memory allocation is higher than defined in the spec

### ISSUE THREAD

**Issue by ale13jo** [kestra-io/kestra#1756]
### Expected Behavior

Honor thread definition to allocate containers within the pod.

### Actual Behaviour

Pods shutdown because unhealthy state due oom errors.

### Steps To Reproduce

1. Use K8s deployment (not standalone) with Postgres
2. Set your workers to thread=3 in your deployment manifesto.
3. No HPA configured.
4. Create a simple flow A with 3 identical tasks for python script using runner Docker, DockerOptions: memory 500MB, with simple sleep(30s) 
5. Create another flow B to trigger flow A by scheduling every minute.
6. Since the flow shall take 90 seconds to complete, the docker allocation should wait to deploy, but the new containers will be deployed anyway.

The [issue](https://github.com/kestra-io/kestra/issues/1755) could be related.

### Environment Information

- Kestra Version: 0.9+
- Operating System (OS / Docker / Kubernetes): K8s
- Java Version (If not docker):

**Comment by tchiotludo** [comment]
Can you share the flow please, seems to be weird

**Comment by anna-geller** [comment]
Next steps: reproduce and validate if the issue persists in 0.11.0

1. Create a small Kestra deployment as described in the issue. docker allocation should wait to deploy, but if the issue persists, the new containers will be deployed anyway.
2. Create the following flows: flowA and flowB and see whether this leads to issues as described


```yaml
id: flowA
namespace: dev

tasks:
  - id: task1
    type: io.kestra.plugin.scripts.python.Script
    docker:
      image: python:3.11-slim
      memory: 
        memory: 500MB
    script: |
      import time
      print("Sleeping for 30 seconds...")
      time.sleep(30)

  - id: task2
    type: io.kestra.plugin.scripts.python.Script
    docker:
      image: python:3.11-slim
      memory: 
        memory: 500MB
    script: |
      import time
      print("Sleeping for 30 seconds...")
      time.sleep(30)

  - id: task3
    type: io.kestra.plugin.scripts.python.Script
    docker:
      image: python:3.11-slim
      memory: 
        memory: 500MB
    script: |
      import time
      print("Sleeping for 30 seconds...")
      time.sleep(30)
```

and flowB

```yaml
id: flowB
namespace: dev
tasks:
  - id: flowA
    type: io.kestra.core.tasks.flows.Flow
    namespace: dev
    flowId: flowA

triggers:
  - id: flowA
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "*/1 * * * *"
```
