### ISSUE TITLE
Allow adding Execution labels based on input values

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#1760]
## Problem

Imagine the flow with the following input:

```yaml
id: yohann
namespace: dev
inputs:
  - name: ticketKey
    type: STRING
    defaults: Yohann

tasks:
  - id: ticket
    type: io.kestra.core.tasks.log.Log
    message: processing ticket {{ inputs.ticketKey }}! 
```

When processing thousands of executions, many of them for the same ticket, it would be useful to filter for all executions related to a specific ticket (i.e. to a specific input value).

## Possible implementation

Add an "Inputs" filter allowing filtering for specific key-value pairs of input values -- similarly to how this is currently implemented for Labels:
![image](https://github.com/kestra-io/kestra/assets/86264395/ccc21e29-ed2f-49fa-adcc-0c6e7c5c8fca)
