### ISSUE TITLE
Add `disabled: true` flag on the `LocalFiles` task

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#1761]
### Expected Behavior

Using this flow example (you can reproduce it directly), the `inputFiles` task is executed and is not skipped despite the disabled flag set to True. 

```yaml
id: pandasETLnew
namespace: blueprint

tasks:
  - id: wdir
    type: io.kestra.core.tasks.flows.WorkingDirectory
    tasks:
      - id: extractCsv
        type: io.kestra.plugin.scripts.python.Script
        script: |
          import pandas as pd
          data = {
              'Column1': ['A', 'B', 'C', 'D'],
              'Column2': [1, 2, 3, 4],
              'Column3': [5, 6, 7, 8]
          }
          df = pd.DataFrame(data)
          df.to_csv("data.csv", index=False)
        warningOnStdErr: false
        docker:
          image: ghcr.io/kestra-io/pydata:latest

      - id: outputFiles
        type: io.kestra.core.tasks.storages.LocalFiles
        outputs:
          - "*.csv"

      - id: inputFiles
        type: io.kestra.core.tasks.storages.LocalFiles
        disabled: true
        inputs:
          data.csv: "{{outputs.outputFiles.uris['data.csv']}}"

      - id: transformAndLoadCsv
        type: io.kestra.plugin.scripts.python.Script
        script: |
          import pandas as pd
          df = pd.read_csv("data.csv")
          df['Column4'] = df['Column2'] + df['Column3']
          df.to_csv("final_result.csv", index=False)
        warningOnStdErr: false
        docker:
          image: ghcr.io/kestra-io/pydata:latest
```

### Actual Behaviour

![image](https://github.com/kestra-io/kestra/assets/86264395/50c53f48-1262-4ad1-8091-e755d1475780)

### Environment Information

- Kestra Version: develop full image 0.10.1
