### ISSUE TITLE
Ensure that `newLine: false` on `JsonWriter` results in a `.json` file rather than `.jsonl`

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#1773]
### Issue description

reproducer:

```yaml
id: apiJSON
namespace: dev

tasks:
  - id: download
    type: io.kestra.plugin.fs.http.Download
    uri: https://gorest.co.in/public/v2/users

  - id: toJSON
    type: io.kestra.plugin.serdes.json.JsonWriter
    from: "{{outputs.download.uri}}"
    newLine: false
```
![image](https://github.com/kestra-io/kestra/assets/86264395/fa4d37d4-d34e-47ed-a0b7-cf99980160c9)
