### ISSUE TITLE
Allow keeping original file format without ION serialization for files stored in internal storage

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#1784]
## Problem

Passing data between tasks (e.g., between the Extract and Load step) requires persisting data to internal storage first. Usually, data is first converted to the ION format. 

However, this often overcomplicates simple use cases where the user wants to download a file and use it in its original file format. 

## Example
Here is an example that illustrates the problem:

```yaml
id: downloadParquetFile
namespace: dev

tasks:
  - id: downloadFile
    type: io.kestra.plugin.fs.http.Download
    disabled: true
    uri: https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2023-04.parquet

  - id: s3
    type: io.kestra.plugin.aws.s3.Download
    accessKeyId: "{{ secret('AWS_ACCESS_KEY_ID') }}"
    secretKeyId: "{{ secret('AWS_SECRET_ACCESS_KEY') }}"
    region: "eu-central-1"
    bucket: kestraio
    key: raw/yellow_tripdata_2023-04.parquet

  - id: processDownloadedFile
    type: io.kestra.plugin.scripts.python.Script
    docker:
      image: ghcr.io/kestra-io/pydata:latest
    script: |
      import pandas as pd

      df = pd.read_parquet("{{outputs.s3.uri}}")
      df.head()
```

The parquet file in both`http.Download` and `s3.Download` loses its original format and cannot be used in the Python script task without first converting it from ION back to parquet. 

This violates users' expectations, as anyone using the download tasks would expect the downloaded files to be stored in their original format.

## Possible solutions

1. Add an additional flag `keepOriginalFormat: true` to tasks such as Download tasks.
2. Keep the original file format by default and make the transition to ION an optional step: `convertToION: true`

**Comment by anna-geller** [comment]
notes from @loicmathieu:

- all tasks that emit data (like Query tasks) by default use the ION format. You can then use the serdes plugin to switch to a different format.
- tasks that fetch files (S3, GCS, Azure Blob, HTTP Download) will just store the file as is in the internal storage, if the extension is not preserved the file will be with the extension .tmp **it's a known issue**.

For Databricks DBFS Download the extension is preserved, see [here](https://github.com/kestra-io/plugin-databricks/pull/6/files#diff-ba7a64bb1cf3cdfec288ee08743fc12e6612e346a9bb1c6496640ccb42c0e34dR68-R70).
The same should be done for ex for GCS, which didn't preserve it, see [here](https://github.com/kestra-io/plugin-gcp/blob/master/src/main/java/io/kestra/plugin/gcp/gcs/Download.java#L54).

**Comment by anna-geller** [comment]
Even if the original file format is preserved, I believe this won't work:

```yaml
  - id: processDownloadedFile
    type: io.kestra.plugin.scripts.python.Script
    docker:
      image: ghcr.io/kestra-io/pydata:latest
    script: |
      import pandas as pd

      df = pd.read_parquet("{{outputs.s3.uri}}")
      df.head()
```
because the extension kestra:/// is kept and Python can't read it unless it would map to something like /tmp/tempdir/executionId/myfile.paruqet

adding WorkingDirectory at the top level + preserving the original file format might be good enough as a solution though
