### ISSUE TITLE
Improve mapping of original file paths to paths in internal storage on `LocalFiles` and file detection triggers

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#1788]
### Feature description

When using `LocalFiles.outputs` the Outputs expose `uris` as the dict : 

```
{
  "file.csv": "kestra:///some_folder/file.csv",
   "file.csv": "kestra:///some_folder/file.csv",
   "file.csv": "kestra:///some_folder/file.csv",
}
``` 

However to pass those data to a Each like task we need a proper object, something like :

```
[
  {"file.csv": "kestra:///some_folder/file.csv"},
  {"file.csv": "kestra:///some_folder/file.csv"},
  {"file.csv": "kestra:///some_folder/file.csv"},
]
```

The trick now is to use something like `{{ outputs.hello.value | jq('to_entries | map({( .key ): .value})' ) | jq('.[][]') }}` to get the good result.

Would it be possible to create a new Peeble function to parse such original object to a map of objects ?

**Comment by anna-geller** [comment]
can you share a full reproducer? I think you can store e.g. all files into sth like `"out/*.csv"` and then in the next task you can list all files in "out", and return those in a Bash or Python script as outputs for Each task

**Comment by Ben8t** [comment]
hum it doesn't change anyting

```yaml
id: test_out
namespace: dev

tasks:
  - id: workingDir
    type: io.kestra.core.tasks.flows.WorkingDirectory
    tasks:
    - id: bash
      type: io.kestra.core.tasks.scripts.Bash
      commands:
        - mkdir -p sub/dir
        - echo "Hello from Bash" >> sub/dir/bash1.txt
        - echo "Hello from Bash" >> sub/dir/bash2.txt
    - id: outputFiles
      type: io.kestra.core.tasks.storages.LocalFiles
      outputs:
        - sub/**
 ```

Each tasks need array of value (`value` prop) but `LocalFiles.uris` is an object (not a list of object)

**Comment by anna-geller** [comment]
seems to work?

```yaml
id: test_out
namespace: dev

tasks:
  - id: workingDir
    type: io.kestra.core.tasks.flows.WorkingDirectory
    tasks:
    - id: bash
      type: io.kestra.core.tasks.scripts.Bash
      commands:
        - mkdir -p sub/dir
        - echo "Hello from Bash" >> sub/dir/bash1.txt
        - echo "Hello from Bash" >> sub/dir/bash2.txt
        - echo "Hello from Bash" >> sub/dir/bash3.txt
        - echo "Hello from Bash" >> sub/dir/bash4.txt

    - id: out
      type: io.kestra.core.tasks.storages.LocalFiles
      outputs:
        - sub/**

    - id: list
      type: io.kestra.plugin.scripts.shell.Commands
      runner: PROCESS
      commands:
        - echo {{outputs.out.uris | jq('.[]')}}
    
  - id: each
    type: io.kestra.core.tasks.flows.EachParallel
    value: "{{outputs.out.uris | jq('.[]')}}"
    tasks:
      - id: return
        type: io.kestra.core.tasks.debugs.Return
        format: "{{taskrun.value}}"
```
