### ISSUE TITLE
Simplify `EachParallel` with `WorkingDirectory` child tasks

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#1809]
### Issue description

This flow works:

```yaml
id: reproducer
namespace: dev

tasks:
  - id: parallel
    type: io.kestra.core.tasks.flows.EachParallel
    value: ["1", "2", "3", "4", "5", "6"]
    tasks:
      - id: seq
        type: io.kestra.core.tasks.flows.Sequential
        tasks:
        - id: pythonScripts
          type: io.kestra.core.tasks.flows.WorkingDirectory
          tasks:
            - id: cloneRepository
              type: io.kestra.plugin.git.Clone
              url: https://github.com/kestra-io/scripts
              branch: main
            - id: python
              type: io.kestra.plugin.scripts.python.Commands
              runner: DOCKER
              docker:
                image: ghcr.io/kestra-io/pydata:latest
              commands:
                - python etl/parametrized.py {{ parents[0].taskrun.value }}
```

however, it seems that it should already work without having to add the `Sequential` task, because `WorkingDirectory` already runs everything sequentially. However, without Sequential, the `taskrun.value` cannot be accessed:

```yaml
id: reproducer
namespace: dev

tasks:
  - id: parallel
    type: io.kestra.core.tasks.flows.EachParallel
    value: ["1", "2", "3", "4", "5", "6"]
    tasks:
      - id: pythonScripts
        type: io.kestra.core.tasks.flows.WorkingDirectory
        tasks:
          - id: cloneRepository
            type: io.kestra.plugin.git.Clone
            url: https://github.com/kestra-io/scripts
            branch: main
          - id: python
            type: io.kestra.plugin.scripts.python.Commands
            runner: DOCKER
            docker:
              image: ghcr.io/kestra-io/pydata:latest
            commands:
              - python etl/parametrized.py {{ taskrun.value }}
```

this gives - `Missing variable: 'value' on 'python etl/parametrized.py {{ taskrun.value }}' at line 1`

cc @loicmathieu
