### ISSUE TITLE
Add links to child executions on the parent task triggering subflows

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#1815]
### Feature description

Try the following flow example:

```yaml
id: parallelSubflows
namespace: dev
tasks:
  - id: parallel
    type: io.kestra.core.tasks.flows.EachParallel
    value:
      - flow1
      - flow2
      - flow3
    tasks:
      - id: subflow
        type: io.kestra.core.tasks.flows.Flow
        namespace: dev
        flowId: "{{taskrun.value}}"
        wait: true
        transmitFailed: true
```

When running it, the logs will only show execution IDs - it would be great to add either a clickable URL to child executions (preferable) or log the full URL to the child execution page:
![image](https://github.com/kestra-io/kestra/assets/86264395/5a313bf8-27dc-4e8b-a7c7-ab08b16c2f76)

Atm, the topology view will provide a link only to the first execution:

![image](https://github.com/kestra-io/kestra/assets/86264395/6983730e-f436-4522-a4d6-9a4ed9e72d88)

and it also doesn't render the child execution ID properly:
![image](https://github.com/kestra-io/kestra/assets/86264395/671d7565-7117-4f36-be6b-0cd60abdc899)

**Comment by anna-geller** [comment]
maybe I'm using an anti-pattern here? 

this explicit version doesn't have any of these issues -- the link is properly displayed and the execution ID is properly rendered:

```yaml
id: parallelSubflowsExplicit
namespace: blueprint
tasks:
  - id: parallel
    type: io.kestra.core.tasks.flows.Parallel
    tasks:
      - id: flow1
        type: io.kestra.core.tasks.flows.Flow
        namespace: dev
        flowId: flow1
      - id: flow2
        type: io.kestra.core.tasks.flows.Flow
        namespace: dev
        flowId: flow2
      - id: flow3
        type: io.kestra.core.tasks.flows.Flow
        namespace: dev
        flowId: flow3
        
taskDefaults:
  - type: io.kestra.core.tasks.flows.Flow
    values:
      namespace: dev
      wait: true
      transmitFailed: true
```
