### ISSUE TITLE
JSON inputs with empty or null values should be serialized 

### ISSUE THREAD

**Issue by brian-mulier-p** [kestra-io/kestra#1825]
### Actual Behaviour

Following this PR https://github.com/kestra-io/kestra/pull/1674, we now serialize null / empty values of inputs. However when the input type is JSON, the actual input value is serialized by the default ObjectMapper which removes empty / null values.

See https://kestra-io.slack.com/archives/C03FEC452NQ/p1690446173575159

### Environment Information

- Kestra Version:
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

**Comment by loicmathieu** [comment]
The slack discussion disapeared can you provide more details please?

**Comment by yuri1969** [comment]
@loicmathieu I don't recall the issue exactly, although it concerns JSON inputs being unexpectedly culled:

```yaml
id: empty-json-values
namespace: company.team

inputs:
  - id: emptyKey
    type: JSON
    #defaults: '{ "foo": "" }' # FIXME: this fails
    defaults: '{ "foo": "bar" }' # this works
    required: false
    description: >
      The key `foo` is emtpy, but it gets removed during the deserialization phase.

tasks:
  - id: hello
    type: io.kestra.core.tasks.log.Log
    message: "{{ inputs['emptyKey']['foo'] }}"
```
