### ISSUE TITLE
Align the `Dag` task syntax with the typical Kestra task syntax

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#1839]
### Feature description

The recently introduced `Dag` task is helpful, but using it is cumbersome as it requires peculiar indentation, which is not aligned with the typical Kestra syntax.

The proposed syntax is:

```yaml
id: DAG
namespace: dev
tasks:
  - id: dag
    type: io.kestra.core.tasks.flows.Dag
    concurrent: 3
    tasks:
      - id: t1
        type: io.kestra.core.tasks.log.Log
        message: hello

      - id: t2
        type: io.kestra.core.tasks.log.Log
        message: hello       
        dependsOn: t1

      - id: t3
        type: io.kestra.core.tasks.log.Log
        message: hello
        dependsOn: t1

      - id: t4
        type: io.kestra.core.tasks.log.Log
        message: hello
        dependsOn: 
          - t2
          - t3
```

This is:
- simpler to define in a flow than the current `Dag` task syntax
- aligned with how other tasks work in Kestra e.g. `WorkingDirectory` or `Parallel` tasks, with child tasks being configured as a list and extra property defining `dependencies`. 

cc @tchiotludo as discussed
