### ISSUE TITLE
New Plugins: Cloud Query

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#1862]
https://www.cloudquery.io/

Seems that the solution is expanding to other things that query cloud account

```yaml
id: "bash"
type: "io.kestra.core.tasks.scripts.Bash"
runner: DOCKER
inputFiles:
  config.yml: |
    kind: source
    spec:
      name: "sharepoint"
      registry: "github"
      path: "koltyakov/sharepoint"
      version: "v1.7.1"
      tables: ["*"]
      destinations: ["meilisearch"]
      spec:
        auth:
          strategy: "addin"
          creds:
            siteUrl: "url"
            clientId: "id"
            clientSecret: "secret"
            realm: "realm"
        lists:
          Shared Documents:
            select:
              - FileLeafRef -> file_name
              - FileRef -> file_path
              - FileDirRef -> file_dir
              - Author/Title -> author
              - File/Length -> file_size(mb)
              - EncodedAbsUrl -> file_url
            expand:
              - File
              - Author
            alias: "shareddocs"
    ---
    kind: destination
    spec:
      name: meilisearch
      registry: github
      path: cloudquery/meilisearch
      version: "v1.1.0"
      write_mode: "overwrite"
      spec:
        api_key: "api-key"
        host: "host"
dockerOptions:
  image: ghcr.io/cloudquery/cloudquery:latest
  entryPoint: [ "" ]
warningOnStdErr: false
commands:
  - 'ls {{ workingDir }}'
  - '/app/cloudquery sync {{ workingDir }}/config.yml --log-console'
```

Need to save [the state inside Kestra](https://www.cloudquery.io/docs/advanced-topics/managing-incremental-tables)

**Comment by anna-geller** [comment]
only worth noting that would be nice to use the new Shell task as a basis for the plugin :) 

```yaml
id: cloudquery
namespace: dev

tasks:
  - id: wdir
    type: io.kestra.core.tasks.flows.WorkingDirectory
    tasks:
      - id: config
        type: io.kestra.core.tasks.storages.LocalFiles
        inputs:
          config.yml: |
            kind: source
            spec:
              name: aws
              path: cloudquery/aws
              version: "v22.4.0"
              tables: ["aws_s3*", "aws_ec2*", "aws_ecs*", "aws_iam*", "aws_glue*", "aws_dynamodb*"]
              destinations: ["postgresql"]
              spec:
            ---
            kind: destination
            spec:
              name: "postgresql"
              version: "v5.0.3"
              path: "cloudquery/postgresql"
              write_mode: "overwrite-delete-stale"
              spec:
                connection_string: ${PG_CONNECTION_STRING}

      - id: cloudQuery
        type: io.kestra.plugin.scripts.shell.Commands
        runner: DOCKER
        env:
          AWS_ACCESS_KEY_ID: "{{ secret('AWS_ACCESS_KEY_ID') }}"
          AWS_SECRET_ACCESS_KEY: "{{ secret('AWS_SECRET_ACCESS_KEY') }}"
          AWS_DEFAULT_REGION: "{{ secret('AWS_DEFAULT_REGION') }}"    
          PG_CONNECTION_STRING: "postgresql://postgres:{{secret('DB_PASSWORD')}}@host.docker.internal:5432/demo?sslmode=disable"
        docker:
          image: ghcr.io/cloudquery/cloudquery:latest
          entryPoint: [""]
        warningOnStdErr: false
        commands:
        - /app/cloudquery sync config.yml --log-console
```
