### ISSUE TITLE
[UI] Boolean input always have a value

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#1904]
### Expected Behavior

Boolean inputs should be able to have no value.

### Actual Behaviour

When executing a flow that have a boolean input from the UI, the execution will always have a value for the input even if it has a default value or is not mandatory.
This is because the UI uses a Switch with true/false so no-value or undefined didn't exist.

As the input is always send, if it's optional or with a default value of true, it will be set to false which is not what we want.

### Environment Information

- Kestra Version:
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

### Example flow

Launching this flow from the UI will output false in the logs whereas true should be outputted as the default of the input is true.

```
id: hello-world
namespace: dev
inputs:
  - name: clear_landing_before
    type: BOOLEAN
    required: true
    defaults: true
tasks:
  - id: echo_input
    type: io.kestra.core.tasks.debugs.Echo
    format: "{{inputs.clear_landing_before}}"
```
