### ISSUE TITLE
Multiple condition on flow trigger does not handle consistently the flow state

### ISSUE THREAD

**Issue by sboisgontier-lmfr** [kestra-io/kestra#1917]
### Expected Behavior

I have a flow that need to have two flows dependencies in success, to run.
More precisely: 
- Given flow A and B in success state during the last time window, flow C will be trigger and run
- Given flow A in error and flow B in success state during the last time window, flow C will **not** be trigger and will not run
- Given flow A and flow B in error state during the last minute, flow C will **not** be trigger and will not run

### Actual Behaviour

When flow A is in error state and flow B is in success state, flow C will run when it should not.

### Steps To Reproduce

In the same time window configured in flow C:
1. Run flow A that will fail
2. Run flow B that will succeed
3. Check that flow C has been executed when it should not

### Environment Information

- Kestra Version: 0.9.8

dep graph:
![image](https://github.com/kestra-io/kestra/assets/113910656/f387eba5-bdfd-4b87-8602-6f2a57dfc92a)

### Example flow

Time window for testing: 1 minute
```yaml
id: trigger_test
namespace: my.namespace

tasks:
  - id: test
    type: io.kestra.core.tasks.log.Log
    message: "OK"

triggers:
  - id: multiple-listen-flow
    type: io.kestra.core.models.triggers.types.Flow
    conditions:
      - type: io.kestra.core.models.conditions.types.ExecutionStatusCondition
        in:
          - SUCCESS
      - id: multiple
        type: io.kestra.core.models.conditions.types.MultipleCondition
        window: PT1M
        windowAdvance: PT0S
        conditions:
          flow_a:
            type: io.kestra.core.models.conditions.types.ExecutionFlowCondition
            namespace: my.namespace
            flowId: flow_a
          flow_b:
            type: io.kestra.core.models.conditions.types.ExecutionFlowCondition
            namespace: my.namespace
            flowId: flow_b

```

flow A:
```yaml
id: flow_a
namespace: my.namespace

tasks:
  - id: test
    type: io.kestra.core.tasks.log.Log
    message: "OK"
  - id: fail
    type: io.kestra.core.tasks.executions.Fail
```

flow B:
```yaml
id: flow_b
namespace: my.namespace

tasks:
  - id: test
    type: io.kestra.core.tasks.log.Log
    message: "OK"
  #- id: fail
  #  type: io.kestra.core.tasks.executions.Fail
```
