### ISSUE TITLE
dbt plugins bugs when running

### ISSUE THREAD

**Issue by Amjadshuk** [kestra-io/kestra#1918]
### Expected Behavior

Starting command with pid 1867 [bash -c dbt --log-format json run --project-dir app/dbt/dbt_project  --profiles-dir /tmp/kestra-wd/tmp/3auueg256ofXFXVH4FCMIB/.profile --threads 8]
![dbt_plugins](https://github.com/kestra-io/kestra/assets/95579722/355b2ed4-b88d-4b37-ad35-ebd562d26191)

### Actual Behaviour

Starting command with pid 1867 [bash -c dbt --log-format json --project-dir app/dbt/dbt_project run --profiles-dir /tmp/kestra-wd/tmp/3auueg256ofXFXVH4FCMIB/.profile --threads 8]
![dbt_plugins](https://github.com/kestra-io/kestra/assets/95579722/8c9e6022-6b3b-4092-a66b-b882c2627e65)

### Environment Information

- Kestra Version:
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

**Comment by anna-geller** [comment]
Can you share your flow definition? If you use the `io.kestra.plugin.dbt.cli.DbtCLI` task, it should work

**Comment by Amjadshuk** [comment]
> 

id: dbt
type: io.kestra.plugin.dbt.cli.Run
dbtPath: dbt
inputFiles:
  profiles: "dbt_project:\r

    \  target: dev\r

    \  outputs:\r

    \    dev:\r

    \      type: postgres\r

    \      schema: postgres\r

    \      host: 192.168.100.10\r

    \      port: 5443\r

    \      user: postgres\r

    \      password: admin"
interpreter: bash
projectDir: app/dbt/dbt_project
thread: 8

**Comment by anna-geller** [comment]
can you try this instead:

```yaml
id: community
namespace: dev

tasks:
  - id: dbtRun
    type: io.kestra.plugin.dbt.cli.DbtCLI
    runner: PROCESS
    profiles: |
      dbt_project:
          outputs:
            dev:
              ...
    commands:
      - dbt run --project-dir app/dbt/dbt_project
```

I assume here that you run it in process where your dbt project is baked into the Kestra Docker image, but if you want to run dbt in Docker, try this:

```yaml
id: dbtGitDockerPostgres
namespace: blueprint

tasks:
  - id: dbt
    type: io.kestra.core.tasks.flows.WorkingDirectory
    tasks:
      - id: cloneRepository
        type: io.kestra.plugin.git.Clone
        url: https://github.com/kestra-io/dbt-demo
        branch: main

      - id: dbtCore
        type: io.kestra.plugin.dbt.cli.DbtCLI
        docker:
          image: ghcr.io/kestra-io/dbt-postgres:latest
        profiles: |
          jaffle_shop:
            outputs:
              dev:
                type: postgres
                host: myhostname.us-east-1.rds.amazonaws.com
                user: "{{secret('POSTGRES_USER')}}"
                password: "{{secret('POSTGRES_PASSWORD')}}"
                port: 5432
                dbname: postgres
                schema: public
                threads: 8
                connect_timeout: 10
            target: dev
        commands:
          - dbt deps
          - dbt build
```
