### ISSUE TITLE
Make task ID unique per task type, not per flow

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#1922]
Prioritization: not urgent, but it would be a great UX improvement if this would be implemented one day

### Feature description

Currently, the task ID must be unique per flow. From the UX, it makes certain things more difficult. In the example below, some definitions need to be repeated (not DRY). 

![image](https://github.com/kestra-io/kestra/assets/86264395/3cc0cd1a-c5dc-4cde-a8e7-e1ee43f3abbc)

```yaml
id: 02_dbt_bigquery_ml
namespace: dev

description: |
  Make sure to replace `geller` with your GCP project ID both in this flow and in the dbt profiles.yml.

inputs:
  - name: limit
    description: Number of rows to train the model
    type: INT
    defaults: 1000

  - name: nr_days_fcst
    description: Nr of days in the future to generate forecast for
    type: INT
    defaults: 30

  - name: tbl_name
    description: where to store the final sales forecast table from ML task
    type: STRING
    defaults: forecast_sales

variables:
  url: https://huggingface.co/datasets/kestra/datasets/resolve/main/jaffle-parquet/{{task.id}}.parquet

tasks:
  - id: bq-load-in-parallel
    type: io.kestra.core.tasks.flows.Parallel
    tasks:
      - id: ingest_raw_customers
        type: io.kestra.core.tasks.flows.Sequential
        tasks:
          - id: raw_customers
            type: io.kestra.plugin.fs.http.Download
            uri: "{{vars.url}}"

          - id: raw_customers_load
            type: io.kestra.plugin.gcp.bigquery.Load
            from: "{{ outputs.raw_customers.uri}}"
            destinationTable: geller.dwh.raw_customers

      - id: ingest_raw_items
        type: io.kestra.core.tasks.flows.Sequential
        tasks:
          - id: raw_items
            type: io.kestra.plugin.fs.http.Download
            uri: "{{vars.url}}"

          - id: raw_items_load
            type: io.kestra.plugin.gcp.bigquery.Load
            from: "{{ outputs.raw_items.uri}}"
            destinationTable: geller.dwh.raw_items

      - id: ingest_raw_orders
        type: io.kestra.core.tasks.flows.Sequential
        tasks:
          - id: raw_orders
            type: io.kestra.plugin.fs.http.Download
            uri: "{{vars.url}}"

          - id: raw_orders_load
            type: io.kestra.plugin.gcp.bigquery.Load
            from: "{{ outputs.raw_orders.uri}}"
            destinationTable: geller.dwh.raw_orders

      - id: ingest_raw_products
        type: io.kestra.core.tasks.flows.Sequential
        tasks:
          - id: raw_products
            type: io.kestra.plugin.fs.http.Download
            uri: "{{vars.url}}"

          - id: raw_products_load
            type: io.kestra.plugin.gcp.bigquery.Load
            from: "{{ outputs.raw_products.uri}}"
            destinationTable: geller.dwh.raw_products

      - id: ingest_raw_stores
        type: io.kestra.core.tasks.flows.Sequential
        tasks:
          - id: raw_stores
            type: io.kestra.plugin.fs.http.Download
            uri: "{{vars.url}}"

          - id: raw_stores_load
            type: io.kestra.plugin.gcp.bigquery.Load
            from: "{{ outputs.raw_stores.uri}}"
            destinationTable: geller.dwh.raw_stores

      - id: ingest_raw_supplies
        type: io.kestra.core.tasks.flows.Sequential
        tasks:
          - id: raw_supplies
            type: io.kestra.plugin.fs.http.Download
            uri: "{{vars.url}}"

          - id: raw_supplies_load
            type: io.kestra.plugin.gcp.bigquery.Load
            from: "{{ outputs.raw_supplies.uri}}"
            destinationTable: geller.dwh.raw_supplies

taskDefaults:
  - type: io.kestra.plugin.gcp.bigquery.Load
    values:
      format: PARQUET
      serviceAccount: "{{ secret('GCP_CREDS') }}"
      projectId: geller
      writeDisposition: WRITE_TRUNCATE
```
