### ISSUE TITLE
Add `allowWarnings` boolean flag to the core task property allowing to mark a task run as Success despite warnings

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#1926]
Often some tasks emit warnings that are not important enough to prevent marking the task execution as Success. 

We should add a property `allowWarnings` (or if you prefer `ignoreWarnings`) = a boolean flag to allow a task run with warnings to be marked as Success:

```yaml
id: fail
namespace: company.team
tasks:
  - id: warn
    type: io.kestra.plugin.core.execution.Fail
    allowFailure: true
    allowWarnings: true
```
