### ISSUE TITLE
warningOnRetry shows up even with no retry/failure

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#1929]
### Expected Behavior

`warningOnRetry` should only shows a warning when an actual retry is done

### Actual Behaviour

The following Flow ends on warning state while there is no retry or failure

```
  - id: this-does-not-retry
    type: io.kestra.plugin.scripts.shell.Commands
    runner: PROCESS
    commands:
      - 'echo "foo"'
    retry:
      type: constant
      interval: PT0.25S
      maxAttempt: 2
      maxDuration: PT1M
      warningOnRetry: true
```
     
![image](https://github.com/kestra-io/kestra/assets/46634684/ee6cb4de-fb1f-4149-bfd8-462c88ef7390)

### Environment Information

- Kestra Version:
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):
