### ISSUE TITLE
Enhance the Guided Onboarding

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#1936]
### Feature description

Some folks getting started with Kestra still don't know how to use Python in combination with other tasks. 

It's worth changing the onboarding example to this one (or a similar one):

```yaml
id: hello-world
namespace: dev

inputs:
  - name: user
    type: STRING
    defaults: Kestra user

tasks:
  - id: log
    type: io.kestra.core.tasks.log.Log
    message: Hey there, {{ inputs.user }}!

  - id: api
    type: io.kestra.plugin.fs.http.Request
    uri: https://dummyjson.com/products

  - id: python
    type: io.kestra.plugin.scripts.python.Script
    docker:
      image: python:slim
    beforeCommands:
      - pip install polars
    warningOnStdErr: false
    script: |
      import polars as pl
      data = {{outputs.api.body | jq('.products') | first}}
      df = pl.from_dicts(data)
      df.glimpse()
      df.select(["brand", "price"]).write_csv("{{outputDir}}/products.csv")

  - id: sqlQuery
    type: io.kestra.plugin.jdbc.duckdb.Query
    inputFiles:
      in.csv: "{{ outputs.python.outputFiles['products.csv'] }}"
    sql: |
      SELECT brand, round(avg(price), 2) as avg_price
      FROM read_csv_auto('{{workingDir}}/in.csv', header=True)
      GROUP BY brand
      ORDER BY avg_price DESC;
    store: true  

triggers:
  - id: everyMinute
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "*/1 * * * *"
```

Why this example?
1. It shows common tasks: calling REST APIs, running Python scripts and SQL queries
2. Running Python scripts and installing custom dependencies -- this example is lightweight as it only installs Polars which is only ~20 MB library
3. Passing data between tasks using `outputs`
4. Using `outputDir` and `workingDir`
5. Showing how to use `jq()` function to manipulate outputs to get the data you want
6. Showing outputs and the **Preview** feature -- the final DuckDB task will store a beautifully formatted markdown table when clicking on the preview
7. Showing how standard tasks (Request task) can work together with Script and Query tasks

It would also be great to point to Blueprints at the end of the Onboarding Guide to show how people can continue with Kestra after running this first flow
