### ISSUE TITLE
Theme mode "Sync with system"

### ISSUE THREAD

**Issue by Nico-Kestra** [kestra-io/kestra#1949]
### Feature description

Add a third option for the theme: "Sync with system"

**Comment by CGaneshKumar2002** [comment]
Hi @MilosPaunovic If this is still open, can I contribute to this one? I'd appreciate if you assign me if that's the case. Thanks!

**Comment by MilosPaunovic** [comment]
Go for it @CGaneshKumar2002! 🚀

**Comment by Ben8t** [comment]
@CGaneshKumar2002 did you succeed to make any progress on this :) ?

**Comment by CGaneshKumar2002** [comment]
No progress since I've not started, I will be starting on it today @Ben8t

**Comment by CGaneshKumar2002** [comment]
Hey @MilosPaunovic, @Ben8t I actually found a working solution, but however when I change my system theme the changes are not getting dynamically updated unless I refresh (in diff pages except settings). Is this effect desirable or should the solution involves dynamically updating even without a refresh? I'd appreciate if you give me the details, Thanks!

**Comment by MilosPaunovic** [comment]
I think that it would require some serious workarounds to achieve dynamic reactions to change in system theme.

It would be enough to have an option to choose the `System theme` and then the Kestra would use the theme the system is currently using.

**Comment by CGaneshKumar2002** [comment]
Good then, I have implemented that solution. Let me raise a PR so that you can check and give feedback. I've currently named the option "Sync With System" as per the issue title, so I hope it's okay. 

![image](https://github.com/user-attachments/assets/180c4c0b-5e55-46c1-9bbc-53bbb95d6b2c)

**Comment by CGaneshKumar2002** [comment]
Hey @MilosPaunovic, I've raised a PR for this one, Kindly look into it and let me know your feedback. I'd appreciate if you add "hacktoberfest-accepted" label so that it counts towards my contribution.

**Comment by MilosPaunovic** [comment]
@CGaneshKumar2002 I will look at the PR on Monday, but we don't add those kind of labels to issues, unfortunately.

**Comment by MilosPaunovic** [comment]
This is now merged, keep up the great work @CGaneshKumar2002! 🚀

**Comment by Nico-Kestra** [comment]
This mode seems to create issues.
For example, here on the OSS, the colors are incorrect.
<img width="1757" alt="Capture d’écran 2024-10-29 à 13 56 11" src="https://github.com/user-attachments/assets/50d711ba-88ed-4199-a127-4293398045fe">


On the EE, some charts are not displaying.
<img width="1787" alt="Capture d’écran 2024-10-29 à 13 55 47" src="https://github.com/user-attachments/assets/762f0bef-734a-4734-a64a-2f99b48865c8">

**Comment by MilosPaunovic** [comment]
@CGaneshKumar2002 Could you have another look at this?

**Comment by CGaneshKumar2002** [comment]
@MilosPaunovic, @Nico-Kestra  Yeah I will try to look into it. Can I possibly get the expected scenario screenshots? Also kindly give some input regarding how to replicate this issue, since I'm working with local server I can't actually see the data in other tabs as it leads me into "page not found" window. I'd appreciate if you provide those details

![image](https://github.com/user-attachments/assets/37b9433f-067f-4939-8c72-2dfc9bbd0c92)

**Comment by MilosPaunovic** [comment]
Hey @CGaneshKumar2002,

Create and execute any flow, may use this as an example:

```
id: hello_world
namespace: tutorial
description: Hello World
inputs:
  - id: user
    type: STRING
    defaults: Rick Astley
tasks:
  - id: first_task
    type: io.kestra.plugin.core.debug.Return
    format: thrilled
  - id: second_task
    type: io.kestra.plugin.scripts.shell.Commands
    commands:
      - sleep 0.42
      - echo '::{"outputs":{"returned_data":"mydata"}}::'
  - id: hello_world
    type: io.kestra.plugin.core.log.Log
    message: |
      Welcome to Kestra, {{ inputs.user }}! 
      We are {{ outputs.first_task.value}} to have You here!
triggers:
  - id: daily
    type: io.kestra.plugin.core.trigger.Schedule
    disabled: true
    cron: 0 9 * * *
```

Then go to Settings, change both `Theme mode` and `Editor theme` to `Sync with System` value and open main Dashboard, charts will be black
