### ISSUE TITLE
Mark disabled tasks and triggers as disabled/skipped in the topology view

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#1966]
### Feature description

In the previous topology view, disabled tasks and triggers were crossed off. Now, they are displayed the same way as not disabled ones. Is this intentional?

Reproducer:

```yaml
id: welcome
namespace: dev
inputs:
- name: user
  type: STRING
  defaults: Kestra user

tasks:
- id: hello
  type: io.kestra.core.tasks.log.Log
  message: Hey there, {{ inputs.user }}!
  disabled: true

- id: api
  type: io.kestra.plugin.fs.http.Request
  uri: https://dummyjson.com/products

- id: python
  type: io.kestra.plugin.scripts.python.Script
  docker:
    image: python:slim
  beforeCommands:
    - pip install polars
  warningOnStdErr: false
  script: |
    import polars as pl
    data = {{outputs.api.body | jq('.products') | first}}
    df = pl.from_dicts(data)
    df.glimpse()
    df.select(["brand", "price"]).write_csv("{{outputDir}}/products.csv")

- id: sqlQuery
  type: io.kestra.plugin.jdbc.duckdb.Query
  inputFiles:
    in.csv: "{{ outputs.python.outputFiles['products.csv'] }}"
  sql: |
    SELECT brand, round(avg(price), 2) as avg_price
    FROM read_csv_auto('{{workingDir}}/in.csv', header=True)
    GROUP BY brand
    ORDER BY avg_price DESC;
  store: true

triggers:
- id: everyMinute
  type: io.kestra.core.models.triggers.types.Schedule
  cron: "*/1 * * * *"
  disabled: true
  inputs:
    name: Kestra pro user
```

![image](https://github.com/kestra-io/kestra/assets/86264395/c3d9587d-9178-4b29-9228-6fab9e2b97b2)

for executions, it seems OK, as skipped tasks have no status:
![image](https://github.com/kestra-io/kestra/assets/86264395/1a4db146-8516-4242-82b2-7c6711eda3ac)
