### ISSUE TITLE
Provide batch/streaming Flows and Executions data for analytics

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#1985]
### Feature description

We have the following user request on Slack that can be summarized as "As a user, I'd like to export the Executions data to build a custom analytical dashboard around which flows succeed/fail"

![image](https://github.com/kestra-io/kestra/assets/86264395/74c3a30c-4e41-40e0-971e-3789262ca763)

When it comes to the specific implementation, there are many options that can be considered:

1. Selecting Executions in a bulk-action style and clicking on "export as CSV/JSON" 
2. A dedicated task allowing to optionally specify a namespace, execution labels, and date range and output that data to internal storage (URI output)

Not a detailed spec yet, just opening for discussion for now.

**Comment by anna-geller** [comment]
The following is already possible in the EE edition with Kestra:

1. Get flow data -- `kestra_flow` topic

```yaml
id: flows-to-bigquery
namespace: prod

tasks:
  - id: consume
    type: io.kestra.plugin.kafka.Consume
    properties:
      auto.offset.reset: earliest
      bootstrap.servers: prd-kafka.database.svc.cluster.local:9092
    topic: kestra_flow
    valueDeserializer: JSON

  - id: transform
    type: io.kestra.plugin.scripts.nashorn.FileTransform
    from: "{{ outputs.consume.uri }}"
    script: |
      var jacksonMapper = Java.type('io.kestra.core.serializers.JacksonMapper');
      delete row['headers'];

      var value = row['value']

      row['id'] = value['id']
      row['namespace'] = value['namespace']
      row['revision'] = value['revision']
      row['deleted'] = value['deleted']
      row['value'] = jacksonMapper.ofJson().writeValueAsString(value)

  - id: avroWriter
    type: io.kestra.plugin.serdes.avro.AvroWriter
    from: "{{ outputs.transform.uri }}"
    description: convert the file from Kestra internal storage to avro.
    schema: |
      {
        "type": "record",
        "name": "Root",
        "fields":
          [
            { "name": "id", "type": ["null", "string"] },
            { "name": "namespace", "type": ["null", "string"] },
            { "name": "revision", "type": ["null", "string"] },
            { "name": "deleted", "type": ["null", "string"] },
            { "name": "value", "type": ["null", "string"] }
          ]
      }

  - id: load
    type: io.kestra.plugin.gcp.bigquery.Load
    avroOptions:
      useAvroLogicalTypes: true
    destinationTable: geller.dwh.flows
    format: AVRO
    from: "{{outputs.avroWriter.uri }}"
    writeDisposition: WRITE_TRUNCATE
    serviceAccount: "{{ secret('GCP_CREDS') }}"
    projectId: geller

triggers:
  - id: schedule
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "0 10 * * *"
```

2. Get executions data -- `kestra_execution` topic

```yaml
id: executions-to-bigquery
namespace: prod

tasks:
  - id: consume
    type: io.kestra.plugin.kafka.Consume
    properties:
      auto.offset.reset: earliest
      bootstrap.servers: prd-kafka.database.svc.cluster.local:9092
    topic: kestra_execution
    valueDeserializer: JSON
    maxRecords: 100

  - id: transform
    type: io.kestra.plugin.scripts.nashorn.FileTransform
    from: "{{ outputs.consume.uri }}"
    script: |
      var jacksonMapper = Java.type('io.kestra.core.serializers.JacksonMapper');
      delete row['headers'];

      var value = row['value']

      row['id'] = value['id']
      row['originalId'] = value['originalId']
      row['deleted'] = value['deleted']
      row['namespace'] = value['namespace']
      row['flowId'] = value['flowId']
      row['flowRevision'] = value['flowRevision']
      row['taskRunList'] = value['taskRunList']
      row['variables'] = value['variables']
      row['state'] = value['state']['current']
      row['state_history'] = value['state']['histories']
      row['duration'] = value['state']['duration']
      row['startDate'] = value['state']['startDate']
      row['endDate'] = value['state']['endDate']
      row['trigger_id'] = value['trigger']['id']
      row['trigger_type'] = value['trigger']['type']
      row['trigger_variables'] = value['trigger']['variables']
      row['value'] = jacksonMapper.ofJson().writeValueAsString(value)

  - id: avroWriter
    type: io.kestra.plugin.serdes.avro.AvroWriter
    from: "{{ outputs.transform.uri }}"
    description: convert the file from Kestra internal storage to avro.
    schema: |
      {
        "type": "record",
        "name": "Root",
        "fields":
          [
            { "name": "id", "type": ["null", "string"] },
            { "name": "originalId", "type": ["null", "string"] },
            { "name": "deleted", "type": ["null", "string"] },
            { "name": "namespace", "type": ["null", "string"] },
            { "name": "flowId", "type": ["null", "string"] },
            { "name": "flowRevision", "type": ["null", "string"] },
            { "name": "taskRunList", "type": ["null", "string"] },
            { "name": "variables", "type": ["null", "string"] },
            { "name": "state", "type": ["null", "string"] },
            { "name": "state_history", "type": ["null", "string"] },
            { "name": "duration", "type": ["null", "double"] },
            { "name": "startDate", "type": ["null", "string"] },
            { "name": "endDate", "type": ["null", "string"] },
            { "name": "trigger_id", "type": ["null", "string"] },
            { "name": "trigger_type", "type": ["null", "string"] },
            { "name": "trigger_variables", "type": ["null", "string"] },
            { "name": "value", "type": ["null", "string"] }
          ]
      }

  - id: load
    type: io.kestra.plugin.gcp.bigquery.Load
    avroOptions:
      useAvroLogicalTypes: true
    destinationTable: geller.dwh.executions
    format: AVRO
    from: "{{outputs.avroWriter.uri }}"
    writeDisposition: WRITE_TRUNCATE
    serviceAccount: "{{ secret('GCP_CREDS') }}"
    projectId: geller

triggers:
  - id: schedule
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "0 11 * * *"
```
