### ISSUE TITLE
[UI] Overlap between + and task icon in topology

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#1992]
### Actual Behaviour

![image](https://github.com/kestra-io/kestra/assets/46634684/e9baf12a-5131-498c-b558-edcb4fbf198a)

### Steps To Reproduce

```yml
id: retries
namespace: training

tasks:
  - id: failed
    type: io.kestra.core.tasks.scripts.Bash
    commands:
      - 'if [ "{{taskrun.attemptsCount}}" -eq 4 ]; then exit 0; else exit 1; fi'
    retry:
      type: constant
      interval: PT0.25S
      maxAttempt: 5
      maxDuration: PT1M
      warningOnRetry: true

errors:
  - id: never-happen
    type: io.kestra.core.tasks.debugs.Echo
    format: Never happened {{task.id}}
```

### Environment Information

- Kestra Version:
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

**Comment by anna-geller** [comment]
seems no longer to be the case

please reopen if you see this persist

![image](https://github.com/kestra-io/kestra/assets/86264395/26b05ef9-5bf2-4ee2-aec6-9c5cd3fb734c)


```yaml
id: retries
namespace: training

tasks:
  - id: fail
    type: io.kestra.plugin.scripts.shell.Commands
    commands:
      - 'if [ "{{taskrun.attemptsCount}}" -eq 4 ]; then exit 0; else exit 1; fi'
    retry:
      type: constant
      interval: PT0.25S
      maxAttempt: 5
      maxDuration: PT1M
      warningOnRetry: true

errors:
  - id: never-happen
    type: io.kestra.core.tasks.log.Log
    message: Never happened {{task.id}}
```
