### ISSUE TITLE
Extend `errors` with a failed task ID(s) and, if possible, also the stack trace(s) of the failed task(s)

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2000]
## Problem

Users would like to access the stack trace of a failed task within the notification message.

## Example

Using the following flow:

```yaml
id: onFailureAlert
namespace: blueprint

tasks:
  - id: fail
    type: io.kestra.plugin.scripts.shell.Commands
    runner: PROCESS
    commands:
      - exit 1

errors:
  - id: slack
    type: io.kestra.plugin.notifications.slack.SlackIncomingWebhook
    url: "{{ secret('SLACK_WEBHOOK') }}"
    payload: |
      {
        "channel": "#alerts",
        "text": "Failure alert for flow {{ flow.namespace }}.{{ flow.id }} with ID {{ execution.id }}"
      }
```

the Slack task configured within the `errors` section should be able to retrieve the stack trace of the task `fail` to send a more informative failure notification

## Possible implementation

Because it may not be technically feasible for a failed task to emit the stack trace as an output variable, we should attempt to at least output the failed task ID.
