### ISSUE TITLE
Raise an error in the editor when both `cron` and `interval` properties are defined in a `Schedule` trigger

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2005]
## Problem

When a trigger is defined using both CRON and interval as follows:

```yaml
triggers:
  - id: everyMinute
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "*/1 * * * *"
    interval: "PT1M"
```

it results in no scheduled executions according to user report: https://kestra-io.slack.com/archives/C03FQKXRK3K/p1693486310182389 

## Possible resolution

Display a warning, or even better, raise an error within the editor if both properties are defined at the same time.

Additionally, it's worth introducing an extra logic to handle it directly within the `Schedule` trigger itself.
