### ISSUE TITLE
Add support for a map of `labels` in the flow validator

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2006]
### Feature description

We want to support both options for the definition of `labels`.

1. A list of key-value pairs:

```yaml
id: myflow
namespace: dev
labels:
  - key: team
    value: data
  - key: project
    value: dwh
```

2. A map of labels:

```yaml
id: myflow
namespace: dev
labels:
  team: data
  project: dwh
```

Initially, option 2 was the default. 
Now, option 1 is the default and the validator complains when using the Map syntax. 

Both work, but the validator currently only accepts the first option.

Both options are valid. This issue is to bring back support for the Map of labels on the schema for both web validator and VS Code extension.
