### ISSUE TITLE
Docker plugin to build and publish Docker images to remote container registries

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2011]
## Problem

Several users requested support for Docker to use Kestra for their build pipelines. They would like to build images from a custom Dockerfile and push them to remote container registries, including:
- AWS ECR
- Google Artifact Registry
- Azure Container Registry
- GitHub Container Registry (package registry ghcr.io)
- DockerHub

## Implementation

Add a Docker plugin allowing to sequentially execute a list of commands `docker build`, `docker tag`, `docker login` and `docker push`. This helps support:

1. Many CI/CD and infrastructure management use cases without requiring additional infrastructure build tools
2. Script tasks packaged into a Docker image without the need to push images to a registry first (faster feedback loops)

## Out of scope for the initial implementation

Supporting running containers from the image using `docker run` is out of scope, for now, due to potential difficulties in managing the container lifecycle this way.

### Docker Build plugin

We should use this SDK to build the plugin https://github.com/docker-java/docker-java 

The only required property is a list of `tags`. The `dockerfilePath` can be, by default, set to "." to search in the current working directory. 

See the intended usage and the description of desired properties in the flow below:

```yaml
id: hello-docker
namespace: dev

tasks:
  - id: wdir
    type: io.kestra.core.tasks.flows.WorkingDirectory
    tasks:
      - id: build
        type: io.kestra.core.tasks.storages.LocalFiles
        inputs: 
          Dockerfile: |
            FROM kestra/kestra:latest-full
            USER root
            RUN apt-get update -y && apt-get install pip -y
            RUN pip install --no-cache-dir pandas requests kestra boto3

      - id: docker
        type: io.kestra.plugin.docker.Build
        dockerfile: this property is a path to a file, not a Dockerfile content as a string. We expect that with the new Editor, the path will be more common than inline scripts. For now, it could be explicitly passed using outputs e.g. "{{ outputs.build.outputFiles['Dockerfile'] }}". If we can't file a path to a file, we assume that the user passed a Dockerfile inline
        platform: optional array of strings indicating the platform; might be set by default to "linux/amd64"
        push: optional boolean property, set to false by default; if set to true, allows to push the image to a remote container registries
        credentials:  # optional list of maps allowing to specify credentials to authenticate with the remote container registry e.g. for GCP + GHCR:
          - registry: europe-west3-docker.pkg.de
            username: oauth2accesstoken
            password: "{{outputs.fetchAuthToken.accessToken.tokenValue}}"
          - registry: ghcr.io/myorg
            username: myuser
            password: mypassword-or-pat
        tags: # required list of tags provided as a list 
          - kestra/demo:latest
          - kestra/demo:v0.12.0
        buildArgs: # optional map of build arguments
          MY_ARG: my argument value
          BUILDKIT_INLINE_CACHE: 1
          HTTP_PROXY: http://10.20.30.2:1234
        labels: # optional list of metadata label strings for the image in the key=value format e.g.:
          - key1=value1
          - org.opencontainers.image.source=https://github.com/kestra-io/examples
          - org.opencontainers.image.description="Image with the latest pandas, requests and scikit-learn Python packages"
```

Anticipated usage:

```yaml
id: dockerBuild
namespace: dev

tasks:
  - id: wdir
    type: io.kestra.core.tasks.flows.WorkingDirectory
    tasks:
      - id: repo
        type: io.kestra.plugin.git.Clone
        url: https://github.com/kestra-io/examples
        branch: main

      - id: docker
        type: io.kestra.plugin.docker.Build
        dockerfilePath: dockerfiles/pydata.Dockerfile
        tags:
          - your_dockerhub_username/yourimage:latest
        push: true
        credentials: 
          registry: https://index.docker.io/v1/ # default so can be skipped if DockerHub
          username: your_dockerhub_username
          password: dckr_pat_xxxxx # e.g. passed using "{{ secret('REGISTRY_PASSWORD') }}"
```
