### ISSUE TITLE
Labels are not created correctly when deployed by Terraform

### ISSUE THREAD

**Issue by yvrng** [kestra-io/kestra#2037]
### Expected Behavior

When deploying a flow using Terraform, I want the labels to be created correctly.

If I wrote labels in a flow, using the key/value representation, such as
```yaml
labels:
  env: prd
  country: FR
```

I want them to be created as following, in the target Kestra server:
```yaml
labels:
  env: prd
  country: FR
```

### Actual Behaviour

Instead of the expected behavior, the flows created by Terraform don't contain labels. Instead, we get a list with an empty object.

```yaml
labels:
- {}
```

We get this unexpected behavior for any flow.

### Environment Information

- Kestra Version: 0.11.0
- Operating System (OS / Docker / Kubernetes): Kubernetes
- Kestra TF Operator Version: 0.7.0
