### ISSUE TITLE
[UI] Hide values passed via `secret()` function from the logs, inputs and outputs

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2046]
## Problem

Motivating story: "Is there a way to prevent users from logging the secret value?"

It would be great if the flow shown below would output something like `this is my DB password *******` without actually logging the output value.

```yaml
id: secrets
namespace: dev
tasks:
  - id: db
    type: io.kestra.core.tasks.log.Log
    message: this is my DB password {{ secret('DB_PASSWORD') }}
```

## Use cases to consider for the implementation

Secrets should be obfuscated:

1. If Kestra **automatically logs** a secret (e.g., DEBUG log) for troubleshooting purposes
2. If a task, e.g. the Flow task, receives a secret value such as `{{ secret('MY_SECRET') }}` as **input**
3. If a user, for some reason, outputs the Secret, it should also be obfuscated
4. If a user logs the secret as in the previous section; It may not always be possible for Kestra to know that a specific value is considered a Secret, e.g., when a user prints some value from a Python script to `stdout` -- in those cases, Kestra should do a **best-effort attempt** to obfuscate the secret value.

Example for the second use case:

```yaml
id: db
namespace: dev

tasks:
  - id: db
    type: io.kestra.core.tasks.flows.Flow
    namespace: dev
    flowId: myflow
    inputs:
      myInputParameter: "{{ secret('DB_PASSWORD') }}"
```

Example for the third use case:

```yaml
id: db
namespace: dev

tasks:
  - id: outputPassword
    type: io.kestra.core.tasks.debugs.Return
    format: "{{ secret('DB_PASSWORD') }}"
```
