### ISSUE TITLE
[UI] Add arrow description in conditional branching on the `Switch` task

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2072]
### Feature description

Consider the following workflow:

```yaml
id: switch
namespace: dev

inputs:
  - name: language
    type: STRING
    defaults: English

tasks:

  - id: render-language
    type: io.kestra.core.tasks.flows.Switch
    value: "{{ inputs.language }}"
    cases:
      French:
        - id: french
          type: io.kestra.core.tasks.debugs.Return
          format: "The input is {{ inputs.language }}"
      German:
        - id: german
          type: io.kestra.core.tasks.debugs.Return
          format: "The input is {{ inputs.language }}"
    defaults:
      - id: english
        type: io.kestra.core.tasks.debugs.Return
        format: "The input is {{ inputs.language }}"
```

It would be user-friendly if the `cases` can be added next to the arrows as follows:

![image](https://github.com/kestra-io/kestra/assets/86264395/e291b8cc-83da-4b5c-aedb-ac83151e6085)

**Comment by anna-geller** [comment]
quick win if supported by our graph library

**Comment by AnkitAnandMastery17** [comment]
@anna-geller hey, can i work on this issue?

**Comment by anna-geller** [comment]
Yes for sure! We'd love your contribution

**Comment by MilosPaunovic** [comment]
Hi @AnkitAnandMastery17,

Since there hasn't been any progress on the issue, I've unassigned you for now. If you decide to work on it and open a PR, let me know, and I'll be happy to reassign it to you.

In the meantime, the issue is open for anyone in the community who would like to take it on! 🚀

**Comment by anna-geller** [comment]
moved to the next cycle as confirmed that it's not a quick win, open for contribution in the meantime as Milos said :)

**Comment by abhishekgogoi** [comment]
Hi @anna-geller, I want to work on this issue. Can you assign this task to me ? Thanks.

**Comment by MilosPaunovic** [comment]
Hi @abhishekgogoi, is there any progress on this?

**Comment by MilosPaunovic** [comment]
Hi @abhishekgogoi,

As there hasn't been any progress or updates on this, I'll unassign you for now. However, if you do open a PR, it will be reviewed, and you'll be reassigned if no one else handles it in the meantime.

Thanks for all the efforts so far! 🍀

**Comment by AdekeyeAdeniyi** [comment]
@anna-geller 
Please I need a bit more information regarding this issue.

**Comment by MilosPaunovic** [comment]
@AdekeyeAdeniyi I've just assigned you to https://github.com/kestra-io/kestra/issues/8965, so let's wrap that one first before taking anything else.

**Comment by harshit240205** [comment]
@anna-geller can I work on this issue ?

**Comment by MilosPaunovic** [comment]
Go for it @harshit240205, but bare in mind the change might need to be made in our other repository - https://github.com/kestra-io/ui-libs/.

**Comment by MilosPaunovic** [comment]
Hey @harshit240205, are there any updates on this?

**Comment by MilosPaunovic** [comment]
Hi @harshit240205,

As there hasn't been any progress or updates on this, I'll unassign you for now. However, if you do open a PR, it will be reviewed, and you'll be reassigned if no one else handles it in the meantime.

Thanks for all the efforts so far! 🍀

**Comment by vvivekranjan** [comment]
@anna-geller can I work on this issue?

**Comment by vvivekranjan** [comment]
I need more information about this issue. Can you put me in the right direction?

**Comment by MilosPaunovic** [comment]
It's probably needing a change in our other repository, https://github.com/kestra-io/ui-libs, as we do Topology stuff from there.

**Comment by vvivekranjan** [comment]
Does it mean I have to make a change in both the repositories?  There are a lot of files in the ui-libs repository. It's very time-consuming to find that one file we have to make a change to.

**Comment by MilosPaunovic** [comment]
Thank you for your effort so far @vvivekranjan! 🍀

**Comment by kanankotwani28** [comment]
Hi @MilosPaunovic  👋
I’d like to work on this issue. Could you please assign it to me?

**Comment by MilosPaunovic** [comment]
Hi @kanankotwani28,  

You're already assigned to another issue in our repository, and we usually assign only one at a time to new contributors. Let's make sure to wrap that one up before jumping onto another.  🚀

**Comment by kanankotwani28** [comment]
@MilosPaunovic I resolved that issue and my PR is approved . Can I work on this now since I am not assigned to another issue?

**Comment by MilosPaunovic** [comment]
Hey @kanankotwani28, are there any updates on this?

**Comment by MilosPaunovic** [comment]
Hi @kanankotwani28,

As there hasn't been any progress or updates on this, I'll unassign you for now. However, if you do open a PR, it will be reviewed, and you'll be reassigned if no one else handles it in the meantime.

Thanks for all the efforts so far! 🍀

**Comment by MilosPaunovic** [comment]
This is still open to external contributors as a `good first issue` in our repository. One note though, the change will have to be made inside the https://github.com/kestra-io/ui-libs repository, and can be tested via `npm link`.

**Comment by harshit240205** [comment]
Hi @MilosPaunovic I want to work on this issue, can you please assign this to me ?

**Comment by MilosPaunovic** [comment]
Absolutely, go for it @harshit240205! 🚀

**Comment by MilosPaunovic** [comment]
Hey @harshit240205, are there any updates on this?

**Comment by harshit240205** [comment]
On it try to complete it by the EOD.

**Comment by MilosPaunovic** [comment]
Hi @harshit240205,

As there hasn't been any progress or updates on this, I'll unassign you for now. However, if you do open a PR, it will be reviewed, and you'll be reassigned if no one else handles it in the meantime.

Thanks for all the efforts so far! 🍀

**Comment by xkaper001** [comment]
Hi @MilosPaunovic, I'd like to take this up.

**Comment by MilosPaunovic** [comment]
Absolutely, go for it @xkaper001! 🚀

As stated above, the change will have to be made inside the https://github.com/kestra-io/ui-libs repository, and can be tested via `npm link`.

**Comment by MilosPaunovic** [comment]
Hey @xkaper001, are there any updates on this?

**Comment by xkaper001** [comment]
Hey @MilosPaunovic, I’m still working on it. I’ll try to give an update in a day or two.

**Comment by xkaper001** [comment]
Hey @MilosPaunovic, I have worked upon this and am at a point which needs your clarification.

When I added the simple default label I looked like this:-

[1] For 3 cases

![before-for-3](https://github.com/user-attachments/assets/775e727c-5938-4310-97be-40b17ec47e62)

[2] For 4 cases

![before-for-4](https://github.com/user-attachments/assets/8ed46daf-48cc-409a-b6ea-6249b98aa0cc)

[3] I updated it to look like this

![after](https://github.com/user-attachments/assets/7a04300d-bf3b-4777-addf-da4df5084871)

[4] Using BezierPath would make it look something like this
![bezier-example](https://github.com/user-attachments/assets/cf7f306a-ef8d-45d8-b2f9-3941f299762d)

Which one should I go with?

**Comment by MilosPaunovic** [comment]
Nice work! 🚀 

I'd go with option 3, but can you move it a bit up, to not cover the line itself but be a pixel or two above it?

**Comment by xkaper001** [comment]
Cool Cool

This is how it looks now.

Vertically:
![now-vert](https://github.com/user-attachments/assets/d87cbfb8-ca99-4675-a142-80f27cc2c8e3)

Horizontally:
![now-hor](https://github.com/user-attachments/assets/323e1bc6-75c7-49ba-b411-b86cb5077578)

Any changes in horizontal view? (I mean yeah label’s on the line but taking it out of the line, it would kinda look out of context. maybe.. just my opinion ig :))

**Comment by MilosPaunovic** [comment]
Yup, agreed. This looks perfect now. Can you raise a PR with the changes?

**Comment by xkaper001** [comment]
@MilosPaunovic Created the PR - https://github.com/kestra-io/ui-libs/pull/1036

**Comment by flcarre** [comment]
PR open here: https://github.com/kestra-io/ui-libs/pull/1195

**Comment by Pradumnasaraf** [comment]
QA done ✅. Working as expected

```yaml
id: switch
namespace: company.dev
description: Switch task example for Kestra 2.0

inputs:
  - id: language
    type: STRING
    defaults: English
    required: true

tasks:
  - id: render_language
    type: io.kestra.plugin.core.flow.Switch
    value: "{{ inputs.language }}"
    cases:
      French:
        - id: french
          type: io.kestra.plugin.core.debug.Return
          format: "The input is {{ inputs.language }}"
      German:
        - id: german
          type: io.kestra.plugin.core.debug.Return
          format: "The input is {{ inputs.language }}"
    defaults:
      - id: english
        type: io.kestra.plugin.core.debug.Return
        format: "The input is {{ inputs.language }}"
```

<img width="1368" height="1080" alt="Image" src="https://github.com/user-attachments/assets/17a50aa9-4c9a-428d-8a36-33f6194a0db6" />
