### ISSUE TITLE
Odd Gantt chart after restarting an execution featuring Pause

### ISSUE THREAD

**Issue by yuri1969** [kestra-io/kestra#2084]
### Actual Behaviour

Restarting a failed execution featuring a failing task within the `io.kestra.core.tasks.flows.Pause`  task makes the Gantt chart duplicate the `io.kestra.core.tasks.flows.Pause` task. The task seems to be somehow stuck (doesn't fail/complete).

![image](https://github.com/kestra-io/kestra/assets/13468636/580242b6-41b9-4c61-9f1f-d180bbb8bd0a)

### Steps To Reproduce

1. Save the included flow
2. Run the flow - it fails after 5s of being paused
3. Restart the failed flow
4. Check the Gantt chart

### Environment Information

- Kestra Version: 0.11.0
- Operating System (OS / Docker / Kubernetes): AL2023
- Java Version (If not docker): 17

### Example flow

```
id: pause
namespace: io.kestra.tests

tasks:
  - id: hello
    type: io.kestra.core.tasks.log.Log
    message: Pre-pause

  - id: wait-for-something
    type: io.kestra.core.tasks.flows.Pause
    delay: PT5S
    tasks:
      - id: fail-here
        type: io.kestra.core.tasks.executions.Fail

      - id: hello-post-pause
        type: io.kestra.core.tasks.log.Log
        message: Post-Pause
```
