### ISSUE TITLE
Subflow task logs are not shown

### ISSUE THREAD

**Issue by brian-mulier-p** [kestra-io/kestra#2098]
### Actual Behaviour

See https://demo.kestra.io/ui/executions/io.kestra.bmu/call-simple-subflow/2euoLKmgwfLH0lAlHu9uU/logs where there is no logs boxes due to Subflow tasks not producing any attempt making it a edge case

### Environment Information

- Kestra Version: 0.12.0-SNAPSHOT
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

### Example flow

```
id: call-simple-subflow
namespace: io.kestra.bmu
tasks:
  - id: subflow
    type: io.kestra.core.tasks.flows.Flow
    flowId: simple-subflow
    namespace: io.kestra.bmu
```

```
id: simple-subflow
namespace: io.kestra.bmu
tasks:
  - id: hello
    type: io.kestra.core.tasks.log.Log
    message: Kestra team wishes you a great day! 👋
```
