### ISSUE TITLE
Failing task with error handler in a DAG will hang forever leading to zombie execution

### ISSUE THREAD

**Issue by brian-mulier-p** [kestra-io/kestra#2111]
### Actual Behaviour

See https://demo.kestra.io/ui/executions/io.kestra.bmu/dag-test-error/2lJMuZsJdIvt7GqobvxeQR/gantt
It only happens if we add an error handler, without it a failing task will stop the execution properly

### Environment Information

- Kestra Version: 0.12.0-SNAPSHOT
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

### Example flow

```
id: dag-test-error
namespace: io.kestra.bmu
tasks:
- id: dag
  type: io.kestra.core.tasks.flows.Dag
  tasks:
  - task:
      id: Log
      type: io.kestra.core.tasks.log.Log
      message: Some log
    dependsOn:
    - failing
  - task:
      id: failing
      type: io.kestra.core.tasks.executions.Fail
  errors:
  - id: error
    type: io.kestra.core.tasks.log.Log
    message: error handler
```
