### ISSUE TITLE
Allow `errors` tasks on Runnable tasks

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2116]
### Feature description

Currently, the custom per-task error handling with `errors` is only possible when using Flowable tasks. This might be a little surprising for the user at first: "Why does only Parallel task among those tasks allow adding custom error handling?" (see the image)

It would be nice to allow that for all tasks for more flexibility.

![image](https://github.com/kestra-io/kestra/assets/86264395/ce480720-a2aa-470d-9830-21c5e6792746)

**Comment by loicmathieu** [comment]
You should wrap your task in a Sequential: https://kestra.io/plugins/core/tasks/flows/io.kestra.core.tasks.flows.sequential

Only flowable tasks can handle errors per design. I'm not saying it's not possible but it may again be a big change.

**Comment by anna-geller** [comment]
most orchestrators have some sort of on-error callback allowing to react to a specific task's failure; currently, kestra lacks that functionality and the issue here is a request to change that behavior to allow any task to have custom error handling

**Comment by Ben8t** [comment]
Flow example that works for flowable (first parallel task) but not for runnable (second task):

```yaml
id: llama_284166
namespace: company.team

tasks:
  - id: parallel
    type: io.kestra.plugin.core.flow.Parallel
    values:
      - 1
      - 2
    tasks:
      - id: hello1
        type: io.kestra.plugin.core.log.Log
        message: "{{ taskrun.value }} - {{ inputs.test }}"
    errors:
      - id: case_hwne_error
        type: io.kestra.plugin.core.log.Log
        message: "there is an error"

  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀
    errors: # this doesn't exists for runnable
      - id: case_hwne_error
        type: io.kestra.plugin.core.log.Log
        message: "there is an error"
```

**Comment by anna-geller** [comment]
it would also need frontend changes in the topology

**Comment by anna-geller** [comment]
We should remove `errors` property on Flowable tasks and as the top-level flow property https://github.com/kestra-io/kestra-ee/issues/3557

It's already possible to react to error of any specific task using `afterExecution` with `runIf`:

```yaml
id: alerts_demo
namespace: company.team

tasks:
  - id: mytask
    type: io.kestra.plugin.core.execution.Fail

afterExecution:
  - id: onFailure
    runIf: "{{execution.state == 'FAILED' and execution.failure.taskId == 'mytask' }}" # execution.failure.taskId doesn't exist yet but we should consider sth like that
    type: io.kestra.plugin.notifications.slack.SlackIncomingWebhook
    url: https://hooks.slack.com/services/xxx
    payload: |
      {
        "text": "Oh no, {{flow.namespace}}.{{flow.id}}.{{execution.failure.taskId}} failed!!!"
      }
```
