### ISSUE TITLE
File preview doesn't show data for some subflow's FILE inputs 

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2123]
### Expected Behavior

Reproducer

1. Subflow:

```yaml
id: file
namespace: dev

inputs:
  - name: file
    type: FILE

tasks:
  - id: file
    type: io.kestra.plugin.scripts.shell.Commands
    runner: PROCESS
    commands:
      - cat {{ inputs.file }}
```

2. Parent flow:
```yaml
id: eachItemRows
namespace: dev

tasks:
  - id: extract
    type: io.kestra.plugin.fs.http.Download
    uri: https://raw.githubusercontent.com/kestra-io/datasets/main/csv/orders.csv

  - id: split
    type: io.kestra.core.tasks.storages.Split
    from: "{{ outputs.extract.uri }}"
    rows: 1 # also try running this with 2 
  
  - id: each
    type: io.kestra.core.tasks.flows.EachParallel
    value: "{{ outputs.split.uris }}"
    tasks:
      - id: subflow
        type: io.kestra.core.tasks.flows.Flow
        namespace: dev
        flowId: file
        inputs:
          file: "{{ taskrun.value }}"
        wait: true
        transmitFailed: true
```

I believe the issue might be caused by CSV file headers

https://share.descript.com/view/nH4woU2zNMv

### Environment Information

- Kestra Version: 0.12.0

**Comment by anna-geller** [comment]
same when using input from JDBC query passed to the same subflow 

```yaml
id: each_item_rows
namespace: dev

tasks:
  - id: extract
    type: io.kestra.plugin.jdbc.duckdb.Query
    sql: |
      INSTALL httpfs;
      LOAD httpfs;
      SELECT *
      FROM read_csv_auto('https://raw.githubusercontent.com/kestra-io/datasets/main/csv/orders.csv', header=True);
    store: true

  - id: split
    type: io.kestra.core.tasks.storages.Split
    from: "{{ outputs.extract.uri }}"
    rows: 1
  
  - id: each
    type: io.kestra.core.tasks.flows.EachParallel
    value: "{{ outputs.split.uris }}"
    tasks:
      - id: subflow
        type: io.kestra.core.tasks.flows.Flow
        namespace: dev
        flowId: file
        inputs:
          file: "{{ taskrun.value }}"
        wait: true
        transmitFailed: true
```

**Comment by GideonStowell** [comment]
@Skraye 
I am trying to hunt down info on how to pass files as an input to a subflow and this example is the only solid example I have found so far. 
Do you know if there is a way for me to pass a file by name or even directly to the input?
here is what I am trying:

parent flow
```
- id: subflow
  type: io.kestra.plugin.core.flow.Subflow
  flowId: subflow
  namespace: test
  inputs:
    env_file: | #this is a be a YAML file
    GITHUB_USER: 'myuser'
```
subflow
```
inputs:
  - id: env_file
    type: FILE
    required: true

tasks:
  - id: "onepass"
    type: io.kestra.plugin.scripts.shell.Commands
    taskRunner:
      type: io.kestra.plugin.core.runner.Process
    logLevel: ERROR
    commands:
      - cat {{ inputs.env_file }} 
```

The error I get when I run this is like so :

```
env_file: Invalid input for `env_file`, Illegal character in scheme name at index 6: GITHUB_USER: 'myuser'
```

this seems like a yaml validation thing to be and I have tried a variety of other variations but can't seem to get it to recognize the input file as a file.

Any help would be greatly appreciated!
