### ISSUE TITLE
Add Gotenberg plugin to interact with PDF files

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2124]
### Feature description

https://github.com/gotenberg/gotenberg

**Comment by anna-geller** [comment]
plugin seems not needed - can be solved via a Blueprint:

```yaml
id: gotenberg
namespace: dev

description: |
  You can start your Gotenberg API server using:
  docker run --rm -p 3000:3000 gotenberg/gotenberg:7
  For more information, see the [documentation](https://gotenberg.dev/docs/getting-started/installation)

variables:
  server: https://demo.gotenberg.dev # http://localhost:3000
  template: https://sparksuite.github.io/simple-html-invoice-template/

tasks:
  - id: pdf
    type: io.kestra.plugin.scripts.shell.Commands
    runner: PROCESS
    warningOnStdErr: false
    commands:
      - curl --request POST '{{vars.server}}/forms/chromium/convert/url' --form 'url="{{vars.template}}"' -o {{ outputDir }}/myfile.pdf
```
