### ISSUE TITLE
Add `registry`, `username` and `password` to the `docker` property

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2125]
## Current behavior

Currently, to pass credentials to a private container registry, the user has to pass the entire JSON config, which might be cumbersome. Examples:

GCP Artifact Registry:
```yaml
      - id: analyzeSales
        type: io.kestra.plugin.scripts.python.Script
        script: ...
        docker:
          image: yourGcpRegion-docker.pkg.dev/YOUR_GCP_PROJECT_NAME/flows/python:latest
          config: |
            {
              "auths": {
                "europe-west3-docker.pkg.dev": {
                    "username": "oauth2accesstoken",
                    "password": "{{outputs.fetchAuthToken.accessToken.tokenValue}}"
                  }
              }
            }
```

AWS ECR:

```yaml
  - id: py
    type: io.kestra.plugin.scripts.python.Commands
    docker:
      image: 338306982838.dkr.ecr.eu-central-1.amazonaws.com/data-infastructure:latest
      config: |
        {
          "auths": {
            "338306982838.dkr.ecr.eu-central-1.amazonaws.com": {
                "username": "AWS",
                "password": "{{outputs.aws.vars.token}}"
              }
          }
        }
    commands:
      - python --version # e.g. python yourscript.py
```

## Proposal

Add `registry`, `username` and `password` to the `docker` property:

```yaml
  - id: python
    type: io.kestra.plugin.scripts.python.Commands
    docker:
      image: 338306982838.dkr.ecr.eu-central-1.amazonaws.com/data-infastructure:latest
      registry: "338306982838.dkr.ecr.eu-central-1.amazonaws.com"
      username: AWS
      password: "{{outputs.aws.vars.token}}"
    commands:
      - python --version # e.g. python yourscript.py
```
