### ISSUE TITLE
The `disabled` flag is not respected on a WorkingDirectory task and leads to a never-ending Execution

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#2128]
```yaml 
      - id: wdir
        type: io.kestra.core.tasks.flows.WorkingDirectory
        tasks:
          - id: log 
            type: io.kestra.core.tasks.log.Log
            message: "{{ taskrun }}"
            disabled: true
```

the log task will start

**Comment by anna-geller** [comment]
I can reproduce this on the `develop` branch:

```yaml
id: hello-log
namespace: dev
tasks:
  - id: wdir
    type: io.kestra.core.tasks.flows.WorkingDirectory
    tasks:
      - id: log 
        type: io.kestra.core.tasks.log.Log
        message: "{{ taskrun }}"
        disabled: true
```

The log is printed, and the execution seems to be stuck in a running state due to `WorkingDirectory` never finishing 

![image](https://github.com/kestra-io/kestra/assets/86264395/121e67fd-3bbc-44b0-aa53-8f448a59bd5e)
