### ISSUE TITLE
Allow subflows to generate and pass outputs in the same way as functions can return data

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2133]
## Problem

Passing data between subflows is difficult and makes decoupled patterns to some extent challenging. Currently, the parent flow needs to know the internals of the child flow, including the task ID and output name. It would be easier if the child flow could expose or _return_ specific data as the output of the flow.

See the example below:

![image](https://github.com/kestra-io/kestra/assets/86264395/bf8cd660-ae0b-465f-b238-cda6b8fbcec2)

![image](https://github.com/kestra-io/kestra/assets/86264395/b5c885aa-e48b-49e0-b6a3-8b8cc95c3a64)

1. child flow

```yaml
id: flow1
namespace: blueprint
tasks:
  - id: returnData
    type: io.kestra.core.tasks.debugs.Return
    format: this is a secret message returned from {{flow.id}}
```

2. parent flow

```yaml
id: passDataBetweenSubflows
namespace: blueprint

tasks:
  - id: flow1
    type: io.kestra.core.tasks.flows.Flow
    namespace: blueprint
    flowId: flow1
    wait: true
    outputs:
      dataFromChildFlow: "{{outputs.returnData.value}}"
  
  - id: log
    type: io.kestra.core.tasks.log.Log
    message: "{{outputs.flow1.outputs.dataFromChildFlow}}"
```

## Proposal

Add a new `outputs` property on the flow level, allowing to pass data by key in the format: 
`{{ outputs.subflow_task_id.output_key}}`. 

Here is an example of a child flow returning outputs via an arbitrary key name:

child flow:

```yaml
id: flow1
namespace: dev

tasks:
  - id: returnData
    type: io.kestra.core.tasks.debugs.Return
    format: this is a secret message returned from {{flow.id}}

outputs:
  key_name: "{{ outputs.returnData.value }}"
```

the parent flow can easily access that value by key without having to know its internals:

```yaml
id: passDataBetweenSubflows
namespace: blueprint

tasks:
  - id: flow1
    type: io.kestra.core.tasks.flows.Subflow
    namespace: dev
    flowId: flow1
    wait: true
  
  - id: log
    type: io.kestra.core.tasks.log.Log
    message: "{{outputs.flow1.key_name}}"
```

⚠️ The outputs of the child flow will be propagated to the subflow task by key only if `wait: true`. 

## Implications

This will be especially important to simplify an optional "reduce" step when performing a map-reduce-like operation iterating over a list of values and executing a bunch of subflow executions that may optionally return data that can be aggregated/zipped/"reduced" at the end of the parent flow using the `ForEachItem` pattern: https://github.com/kestra-io/kestra/issues/2131 

## UI-side changes

The flow execution outputs will be stored in internal storage. It will require adding outputs on the Executions overview tab:

![image](https://github.com/kestra-io/kestra/assets/86264395/2fe15b06-c3bf-43a0-a6ec-3c8588a5b840)

**Comment by loicmathieu** [comment]
There is already too much things in the output.
Maybe a function that can access the parent execution and gather the output will do this trick? This would avoid copying the parent outputs inside the child output.

```yaml
  - id: log
    type: io.kestra.core.tasks.log.Log
    message: "{{parentOutpu('key_name')}}"
```

**Comment by anna-geller** [comment]
Outputs will consist of:
- `keys` which are strings 
- `values` which are serialized objects (e.g. it can be an array passed downstream, serialized as a JSON string)

A more complex object passed as output - discussed with Ludo yesterday:

1) child flow
```yaml
id: flow1
namespace: dev

tasks:
  - id: returnData
    type: io.kestra.core.tasks.debugs.Return
    format: this is a secret message returned from {{flow.id}}

  - id: complexOne
    type: io.kestra.core.tasks.debugs.Return
    format: "{{ range(0, 10) }}"

outputs:
  simple: "{{ outputs.returnData.value }}"
  complex: "{{ outputs.complexOne.value }}" # JSON string on the consumer side, but array [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] on the producer side 
```

2) the parent flow can access output values by keys without having to know the child flow's internals:

```yaml
id: passDataBetweenSubflows
namespace: blueprint

tasks:
  - id: flow1
    type: io.kestra.core.tasks.flows.Subflow
    namespace: dev
    flowId: flow1
    wait: true

  - id: log
    type: io.kestra.core.tasks.log.Log
    message: "{{ outputs.flow1.simple }}"
#    message: "{{outputs.flow1.vars.simple}}" # worst case with vars

  - id: log2
    type: io.kestra.core.tasks.log.Log
    message: "{{ outputs.flow1.complex }}" # on the consumer side, use "{{ json(outputs.flow1.complex)[0] }}" to get specific values from a JSON string containing an array
```

**Comment by anna-geller** [comment]
As part of this issue, we will mark the outputs property as deprecated:

```yaml
id: passDataBetweenSubflows
namespace: blueprint

tasks:
  - id: flow1
    type: io.kestra.core.tasks.flows.Flow
    namespace: blueprint
    flowId: flow1
    wait: true
    outputs: # when specified, warning in the UI that it's deprecated
      dataFromChildFlow: "{{outputs.returnData.value}}"
  
  - id: log
    type: io.kestra.core.tasks.log.Log
    message: "{{outputs.flow1.outputs.dataFromChildFlow}}"
```
