### ISSUE TITLE
[UI] Adjust the Gantt view to track progress of massively parallel subflow executions required by the `ForEachItem` task

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2135]
### Feature description

When executing several thousands of executions created from the `ForEachItem` task https://github.com/kestra-io/kestra/issues/2131, the current Gantt view isn't particularly helpful. For such use cases, it's more important to see at a glance how many child executions have been created, how many of them were successful or not, and how many are still in progress. Design:

![Gantt (2)](https://github.com/kestra-io/kestra/assets/86264395/1de318fe-f4fc-4ebf-9b56-64344662ab38)

(when hovering over any of those bars, it will show how many executions are currently in any given state)

Show paginated logs from parent execution and all child executions -> show item instead of only child execution ID:

![image](https://github.com/kestra-io/kestra/assets/86264395/d5290d21-04b5-4e57-b8b0-9aacc1f0597a)

Warning: need to check with Brian how to handle the paginated logs. For now, no way to display large nr of logs in real time in the browser. 

Alternative: only show group for:

1. Created iterations
2. In progress
3. Completed (will filter Executions table for Success, Failed, Warning, Killing, Killed)

I was thinking about adding a search bar to filter for executions directly from here + a filter to filter for specific states only, but this requires a table and it seems potentially easier if such a table filtered by a state would be provided as a link to each of these states (see the icon next to the number)

**Comment by anna-geller** [comment]
we can already start working on it using the Split task for now:

```yaml
id: each_item_csv
namespace: dev

tasks:
  - id: extract
    type: io.kestra.plugin.fs.http.Download
    uri: https://raw.githubusercontent.com/kestra-io/datasets/main/csv/orders.csv

  - id: split
    type: io.kestra.core.tasks.storages.Split
    from: "{{ outputs.extract.uri }}"
    rows: 10
  
  - id: each
    type: io.kestra.core.tasks.flows.EachParallel
    value: "{{ outputs.split.uris }}"
    tasks:
      - id: subflow
        type: io.kestra.core.tasks.flows.Flow
        namespace: dev
        flowId: file
        inputs:
          file: "{{ taskrun.value }}"
        wait: true
        transmitFailed: true
```
