### ISSUE TITLE
The output preview should display nested JSON output as plain JSON rather than object

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2166]
### Explain the bug

Currently, when the output is a nested JSON output, the output preview shows it as an object:

https://share.descript.com/view/wcXlNE9n3wg

The same applies to outputs of several new tasks that return JSON, incl. SurrealDB and EventBridge PutEvents task (those are for which I could validate the output preview issue)

### Environment Information

- Kestra Version: 0.12.0 
- Operating System and Java Version (if not using Kestra Docker image): develop-full image

## Reproducer

[install surrealDB](https://surrealdb.com/docs/introduction/start) and start: `surreal start memory -A --auth --user root --pass root`

```yaml
id: surreal_db
namespace: blueprints

tasks:
  - id: article
    type: io.kestra.plugin.surrealdb.Query
    query: |
      CREATE article SET
        created_at = time::now(),
        author = author:john,
        title = 'Lorem ipsum dolor',
        text = 'Donec eleifend, nunc vitae commodo accumsan, mauris est fringilla.',
        account = (SELECT VALUE id FROM account WHERE name = 'ACME Inc' LIMIT 1)[0]
      ;

  - id: author
    type: io.kestra.plugin.surrealdb.Query
    query: |
      CREATE account SET
      name = 'ACME Inc',
      created_at = time::now()
      ;

  - id: query
    type: io.kestra.plugin.surrealdb.Query
    query: SELECT * FROM article, account;
    fetchType: STORE

  - id: query_conditional
    type: io.kestra.plugin.surrealdb.Query
    query: SELECT * FROM article WHERE author.age < 30 FETCH author, account;
    fetchType: STORE

taskDefaults:
  - type: io.kestra.plugin.surrealdb.Query
    values:
      host: localhost
      database: test
      namespace: test
      username: root
      password: root
```
