### ISSUE TITLE
[UI] BOOLEAN-type inputs are not interepreted correctly

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2169]
### Explain the bug

This input is valid and should not raise any warnings:

![image](https://github.com/kestra-io/kestra/assets/86264395/c75d216f-164b-4b75-8528-763efb5ac296)

What's more important to fix is that this default input value set to `true` is currently interpreted as `false`:
![image](https://github.com/kestra-io/kestra/assets/86264395/551f05fb-1edd-43ae-a540-a9cdf0b16cae)

Simple reproducer:

```yaml
id: test
namespace: dev

inputs:
  - name: user
    type: STRING
    defaults: Rick Astley
  - name: flag
    type: BOOLEAN
    defaults: true

tasks:
  - id: hello
    type: io.kestra.core.tasks.log.Log
    message: got inputs {{ inputs.user }} and {{ inputs.flag }}
```

### Environment Information

- Kestra Version: 0.12.0 develop full
