### ISSUE TITLE
Flow with an EachParallel with failing tasks ends before all tasks ends

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#2179]
### Explain the bug

Given the following flow:

```yaml
id: each-parallel-subflow-notfound
namespace: io.kestra.tests

tasks:
  - id: 1_each
    type: io.kestra.core.tasks.flows.EachParallel
    value:
      - value-1
      - value-2
    tasks:
      - id: subflow-not-exist
        type: io.kestra.core.tasks.flows.Flow
        flowId: "{{ taskrun.value }}"
        namespace: dev
        wait: true
```

Using the JDBC runner, the flow ends in FAILED before all subtasks of the EachParalle tasks ends.
This can be seen in the following unit test: `JdbcRunnerTest.eachParallelWithSubflowMissing()`.

### Environment Information

- Kestra Version: 0.12.0-SPNASHOT
- Operating System and Java Version (if not using Kestra Docker image):
