### ISSUE TITLE
Long Logs tab loading time for too many taskruns

### ISSUE THREAD

**Issue by brian-mulier-p** [kestra-io/kestra#2188]
### Explain the bug

See this flow
```
id: hello-world-each
namespace: dev
tasks:
  - id: hello
    type: io.kestra.core.tasks.flows.EachSequential
    value: "{{range(0, 200)}}"
    tasks:
      - id: a
        type: io.kestra.core.tasks.log.Log
        message: testing out logs
```

which produces many taskruns and results in a long loading time when entering Logs tab

### Environment Information

- Kestra Version:
- Operating System and Java Version (if not using Kestra Docker image):

**Comment by anna-geller** [comment]
I can reproduce

```yaml
id: hello-world-each
namespace: dev
tasks:
  - id: hello
    type: io.kestra.plugin.core.flow.EachSequential
    value: "{{range(0, 200)}}"
    tasks:
      - id: a
        type: io.kestra.plugin.core.log.Log
        message: testing out logs
```

even though the new `ForEach` task is a bit faster:

```yaml
id: hello-world-each
namespace: dev
tasks:
  - id: hello
    type: io.kestra.plugin.core.flow.ForEach
    values: "{{range(0, 200)}}"
    concurrencyLimit: 1
    tasks:
      - id: a
        type: io.kestra.plugin.core.log.Log
        message: testing out logs
```
