### ISSUE TITLE
Edit the execution's input parameters.

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#2197]
### Feature description

The use case is rather simple:
* to have a flow requiring input parameters
* an execution of this flow successfully processes n tasks
* the execution fails at a (n+1) task
* the reason for the failure was an error in the input parameter
* now you are able to Replay tasks of the execution, but you are unable to change/fix the incorrect input parameter and then Replay => start an entirely new execution

Being able to edit input parameters && Replay the tasks "from the middle of flow" would be great for flows featuring long running and/or non-idempotent tasks.

cc @yu

**Comment by iamviqar** [comment]
@Ben8t I would like to attempt this

**Comment by MilosPaunovic** [comment]
It's all yours @iamviqar! :rocket:

**Comment by iamviqar** [comment]
Thanks @MilosPaunovic , do we any sample flow or reproducible steps to get started on this

**Comment by MilosPaunovic** [comment]
@Ben8t would be the best person to provide the sample flow here.

**Comment by Ben8t** [comment]
Here is a reproducer:

```yaml
id: replay_inputs
namespace: company.team

inputs:
  - id: test
    type: STRING
    required: true
tasks:
  - id: log1
    type: io.kestra.plugin.core.log.Log
    message: '{{inputs.test}}'

  - id: if
    type: io.kestra.plugin.core.flow.If
    condition: '{{ inputs.test == "Hello" }}'
    then:
      - id: log2
        type: io.kestra.plugin.core.log.Log
        message: "correct input"

    else:
      - id: error
        type: io.kestra.plugin.core.execution.Fail   
```
Here we would like to being able to edit input parameters and replay the failing tasks

![image](https://github.com/user-attachments/assets/f7524daf-0116-4241-8030-f131d4ef7645)
