### ISSUE TITLE
Graph not generated or issue not displayed

### ISSUE THREAD

**Issue by Skraye** [kestra-io/kestra#2203]
### Explain the bug

Title :arrow_up: 
The graph is not generated and no issue seems to appear
![image](https://github.com/kestra-io/kestra/assets/37600690/00d61ea2-f303-4430-b31a-85eb3c9689da)

![image](https://github.com/kestra-io/kestra/assets/37600690/038baa34-8644-4d44-891d-71d7e7a3cb17)

the flow :
```
id: trigger-multiplecondition-listener
namespace: com.kestra.yann
#
#inputs:
#  - name: from-parent
#    type: STRING

tasks:
  - id: only-listener
    type: io.kestra.core.tasks.debugs.Return
    format: "childs"

triggers:
  - id: multiple-listen-flow
    type: io.kestra.core.models.triggers.types.Flow
#    inputs:
#      from-parent: '{{ outputs.only.value }}'
    conditions:
      - type: io.kestra.core.models.conditions.types.ExecutionStatusCondition
        in:
          - SUCCESS
      - id: multiple
        type: io.kestra.core.models.conditions.types.MultipleCondition
        window: P1D
        windowAdvance: P0D
        conditions:
          flow-a:
            type: io.kestra.core.models.conditions.types.ExecutionFlowCondition
            namespace: io.kestra.tests
            flowId: trigger-multiplecondition-flow-a
          flow-b:
            type: io.kestra.core.models.conditions.types.ExecutionFlowCondition
            namespace: io.kestra.tests
            flowId: trigger-multiplecondition-flow-b

```

### Environment Information

- Kestra Version: 0.12.0
