### ISSUE TITLE
Stream sys.stdout in script tasks faster

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2212]
### Feature description

The following script using a logger will stream logs immediately:

```yaml
id: loguru
namespace: blueprints

inputs:
  - name: nr_logs
    type: INT
    defaults: 1000

tasks:
  - id: reproducer
    type: io.kestra.plugin.scripts.python.Script
    warningOnStdErr: false
    docker:
      image: ghcr.io/kestra-io/pydata:latest
    script: |
        from loguru import logger
        from faker import Faker
        import time
        import sys

        logger.remove()
        logger.add(sys.stdout, level="INFO")
        logger.add(sys.stderr, level="WARNING")


        def generate_logs(fake, num_logs):
            logger.debug("This message will not show up as the log level is set to INFO")
            logger.warning("Starting to generate log messages")
            for _ in range(num_logs):
                log_message = fake.sentence()
                logger.info(log_message)
                time.sleep(0.1)
            logger.warning("Finished generating log messages")


        if __name__ == "__main__":
            faker_ = Faker()
            generate_logs(faker_, int("{{ inputs.nr_logs }}"))
```

But using `print()` will load them in batches roughly every 20 seconds:

```yaml
id: printer
namespace: dev

inputs:
  - name: nr_logs
    type: INT
    defaults: 1000

tasks:
  - id: reproducer
    type: io.kestra.plugin.scripts.python.Script
    warningOnStdErr: false
    runner: DOCKER
    docker:
      image: ghcr.io/kestra-io/pydata:latest
    script: |
      from faker import Faker
      import time
      import sys

      def generate_logs(fake, num_logs):
          print("Starting to generate log messages", file=sys.stderr)
          for _ in range(num_logs):
              log_message = fake.sentence()
              print(log_message)
              time.sleep(0.1)
          print("Finished generating log messages", file=sys.stderr)

      if __name__ == "__main__":
          faker_ = Faker()
          generate_logs(faker_, int("{{ inputs.nr_logs }}"))
```

TODO: investigate if we can get logs immediately even using the second option
