### ISSUE TITLE
Add a Terraform plugin to simplify infrastructure deployment from Git

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2236]
This plugin should be able to run terraform commands.

Implementation might be similar to this example: https://demo.kestra.io/ui/blueprints/community/141 

We assume that user has a remote backend already configured e.g. using S3, GCS or Terraform Cloud backend

**Comment by anna-geller** [comment]
copy of the blueprint for easier access:

```yaml
id: git_terraform
namespace: blueprint

tasks:
  - id: git
    type: io.kestra.core.tasks.flows.WorkingDirectory
    tasks:
      - id: clone_repository
        type: io.kestra.plugin.git.Clone
        url: https://github.com/anna-geller/kestra-ci-cd
        branch: main

      - id: variables
        type: io.kestra.core.tasks.storages.LocalFiles
        inputs:
          terraform.tfvars: |
            username            = "cicd"
            password            = "{{ secret('CI_CD_PASSWORD') }}"
            hostname            = "https://demo.kestra.io"

      - id: terraform
        type: io.kestra.plugin.scripts.shell.Commands
        docker:
          image: hashicorp/terraform
          entryPoint: [""]
        beforeCommands:
          - terraform init
        commands:
          - terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: "{{ secret('AWS_ACCESS_KEY_ID') }}"
          AWS_SECRET_ACCESS_KEY: "{{ secret('AWS_SECRET_ACCESS_KEY') }}"
          AWS_DEFAULT_REGION: "{{ secret('AWS_DEFAULT_REGION') }}"
```
