### ISSUE TITLE
Add `allowFailure` boolean flag to the core task

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2248]
### Feature description

Currently, the `AllowFailure` task requires nesting, which might be difficult to use in already nested tasks.

The proposal is to add `allowFailure` flag like so:

```yaml
  - id: fail_1
    type: io.kestra.plugin.scripts.shell.Commands
    allowFailure: true
    runner: PROCESS
    commands:
      - exit 1
```

Full example showing the proposed and the already existing option:
```yaml
id: demo
namespace: dev

tasks:
  - id: fail_1
    type: io.kestra.plugin.scripts.shell.Commands
    allowFailure: true
    runner: PROCESS
    commands:
      - exit 1

  - id: allow_failure
    type: io.kestra.core.tasks.flows.AllowFailure
    tasks:
      - id: fail_2
        type: io.kestra.plugin.scripts.shell.Commands
        runner: PROCESS
        commands:
          - exit 1
  
  - id: console
    type: io.kestra.plugin.scripts.shell.Commands
    runner: PROCESS
    commands:
      - echo "this will run since previous failure was allowed ✅"
  
  - id: fail
    type: io.kestra.plugin.scripts.shell.Commands
    runner: PROCESS
    commands:
      - echo "failing and blocking downstream tasks" && exit 1
  
  - id: will_never_run
    type: io.kestra.plugin.scripts.shell.Commands
    runner: PROCESS
    commands:
      - echo "this will never run ❌"
```
