### ISSUE TITLE
taskDefaults is not working

### ISSUE THREAD

**Issue by spanhotra** [kestra-io/kestra#2260]
### Explain the bug

I have the below Flow with default method set to POST and a task with method set to GET.
Expected Behavior is to GET but it is using POST.

```yaml
id: sample-from-code
namespace: edmcode
tasks:
- uri: https://httpbin.org/get
  allowFailed: false
  method: GET
  id: sample-http-call-1
  type: io.kestra.plugin.fs.http.Request
disabled: false
taskDefaults:
- type: io.kestra.plugin.fs.http.Request
  forced: false
  values:
    method: POST
```

### Environment Information

- Kestra Version: 0.12.0
- Operating System and Java Version (if not using Kestra Docker image): Using Docker

**Comment by anna-geller** [comment]
Thanks for reporting this. I was able to reproduce. Commenting out task defaults here correctly uses GET

```yaml
id: sample-from-code
namespace: edmcode
tasks:
  - uri: https://httpbin.org/get
    allowFailed: false
    method: GET
    id: sample-http-call-1
    type: io.kestra.plugin.fs.http.Request

# taskDefaults:
#   - type: io.kestra.plugin.fs.http.Request
#     # forced: false
#     values:
#       method: POST
```

![image](https://github.com/kestra-io/kestra/assets/86264395/008510e9-3fe4-445e-943a-9a6579bd5ce1)
