### ISSUE TITLE
Deprecate `tasks` property from the Pause task or make it optional or both

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2264]
### Feature description

The Pause task has a `tasks` property which is not needed. Compare the two examples below.

the current one

```yaml
id: human_in_the_loop
namespace: dev

tasks:
  - id: before_approval
    type: io.kestra.core.tasks.debugs.Return
    format: output data that needs to be validated before continuing the execution
  
  - id: pause
    type: io.kestra.core.tasks.flows.Pause
    tasks:
     - id: run_post_approval
       type: io.kestra.plugin.scripts.shell.Commands
       runner: PROCESS
       commands:
        - echo "manual approval received! continuing the execution"

  - id: post_resume
    type: io.kestra.core.tasks.debugs.Return
    format: "{{task.id}} > {{taskrun.startDate}}"
```

and this one:

```yaml
id: human_in_the_loop
namespace: dev

tasks:
  - id: before_approval
    type: io.kestra.core.tasks.debugs.Return
    format: output data that needs to be validated before continuing the execution
  
  - id: pause
    type: io.kestra.core.tasks.flows.Pause

  - id: run_post_approval
    type: io.kestra.plugin.scripts.shell.Commands
    runner: PROCESS
    commands:
    - echo "manual approval received! continuing the execution"

  - id: post_resume
    type: io.kestra.core.tasks.debugs.Return
    format: "{{task.id}} > {{taskrun.startDate}}"
```

they are both functionally equivalent as all tasks, whether children of Pause or not, are put on hold until you resume the execution
