### ISSUE TITLE
Introduce parent-child relation among executions

### ISSUE THREAD

**Issue by yuri1969** [kestra-io/kestra#2266]
### Feature description

It'd be cool to leverage the existing UI elements for visualizing _parent - child_ relations between different executions. Currently, the UI supports the standard _flow - subflow_ relation.

The impl should make it possible to start a new execution while being able to specify its parent executions (plural).

---

Subflows are the current first choice. However, there are cases where subflows are not really usable.

### Additional ad-hoc processing

1. Run several batches of data processing in a flow
2. A processing error gets reported a few days later
3. Additional ad-hoc processing is required
4. Run ad-hoc processing flow - the original processing executions could be pointed to as parent executions

### Generic pre-processor pattern

Employ a generic pre-processing flow which fabricates products used by many different flows.

The logic is often rather complicated - hence the need for DRY. The following example illustrates a very simple pre-processor:

```yaml
id: ibm-normalizing-preprocessor
namespace: io.kestra.tests
description: Generic normalization flow

inputs:
  - type: FILE
    name: IBM_FILE

tasks:
 - id: ibm-to-utf
   type: io.kestra.plugin.scripts.shell.Commands
   commands:
      - "tr -d '\r\n' < '{{ inputs.IBM_FILE }}' | iconv -f 'Cp500' -t 'UTF-8' > '{{outputDir}}/UTF_FILE'"
```

The pre-processing flow above is used for ~20 completely different flows which accept UTF-8 data. Different flows require different sets of input properties:

```yaml
id: flow-a
namespace: io.kestra.tests
description: Flow using pre-processor's data

inputs:
  - type: FILE
    name: UTF_FILE
  - type: STRING
    name: fooA
  - type: BOOLEAN
    name: barA
```

```yaml
id: flow-b
namespace: io.kestra.tests
description: Flow using pre-processor's data

inputs:
  - type: FILE
    name: UTF_FILE
  - type: JSON
    name: fooB
  - type: JSON
    name: barB
  - type: STRING
    name: bazB
```

If those flows are invoked as subflows of the pre-processor, the pre-processor flow would have to aggregate all the inputs in order to pass them to the different subflows.

Invoking the pre-processor flow and then invoking the subsequent processing flow in a parent-child manner wouldn't introduce the coupling.
