### ISSUE TITLE
Webhook trigger : allow to specify condition on payload to trigger execution

### ISSUE THREAD

**Issue by aballiet** [kestra-io/kestra#2267]
### Feature description

For some APIs we might want to check a condition (key exists, value is a specific one we are interested in) to decide to trigger our flow or not.

Currently this is doable within the flow definition but add some complexity, still generate flow execution and pollute history.

=> Can be nice to have an optional parameter `payloadCondition` which would contain our condition.

Flow could look like : 

```YAML
triggers:
  - id: webhook
    type: io.kestra.core.models.triggers.types.Webhook
    key: 4wjtkzwVGBM9yKnjm3yv8r
    payloadCondition: {{ trigger.body.pull_request.comments_url ?? true : false }}
```

**Comment by anna-geller** [comment]
Great idea to add event filters! We'd only need to make it a bit more flexible to allow: 
- filtering for specific header and body properties
- multiple filters e.g. filter on both header and body or multiple body filters

Some examples of how other tools approach it:
- [Azure DevOps](https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/resources-webhooks-webhook-filters-filter?view=azure-pipelines)
- [Close.com](https://developer.close.com/resources/webhook-subscriptions/webhook-filters/)

Proposed syntax:
```yaml
triggers:
  - id: github
    type: io.kestra.core.models.triggers.types.Webhook
    key: ThisIsaSuperSecretKey42
    conditions:
      - type: io.kestra.core.models.conditions.types.WebhookCondition
        body: "{{ pull_request.comments_url ?? true : false }}"
        headers:
          X-GitHub-Event: pull_request
```

**Comment by anna-geller** [comment]
@aballiet just talked to the team and this will be a little bit more complex to handle. @loicmathieu said he will help with that

the planned syntax is to use already existing variable condition:
```yaml
id: webhook_test
namespace: prod
tasks:
  - id: hello
    type: io.kestra.core.tasks.log.Log
    message: "{{ trigger.body }}"

triggers:
  - id: eventBridge
    type: io.kestra.core.models.triggers.types.Webhook
    key: ThisIsaSuperSecretKey42
    conditions:
      - type: io.kestra.core.models.conditions.types.VariableCondition
        expression: "{{ trigger.body.github.pull_request.comments_url != null }}"
      - type: io.kestra.core.models.conditions.types.VariableCondition
        expression: "{{ trigger.headers.X-GitHub-Event.0 == 'pull_request' }}"
```
