### ISSUE TITLE
Allow to trigger a flow according to multiple flows with different state

### ISSUE THREAD

**Issue by sboisgontier-lmfr** [kestra-io/kestra#2270]
### Feature description

Kestra allows us to trigger a flow on multiple flow condition, but they have to be on the same state. It is not possible to chose a state by flow trigger condition.

For example, if my flow has to run if the flow A is in error and the flow B is successful, I cannot do in one go. 

I would like to be able to do something like that:
```yaml
triggers:
  - id: multiple-listen-flow
    type: io.kestra.core.models.triggers.types.Flow
    conditions:        
      - id: multiple
        type: io.kestra.core.models.conditions.types.MultipleCondition
        window: P1D
        windowAdvance: P0D
        conditions:
          flow-a:
            type: io.kestra.core.models.conditions.types.ExecutionFlowCondition
            namespace: io.kestra.demo
            flowId: multiplecondition-flow-a
            in:
              - SUCCESS
          flow-b:
            type: io.kestra.core.models.conditions.types.ExecutionFlowCondition
            namespace: io.kestra.demo
            flowId: multiplecondition-flow-b
            in:
              - SUCCESS
              - ERROR 
```

**Comment by tchiotludo** [comment]
Maybe we could add a `AndCondition` like the [OrCondition](https://kestra.io/plugins/core/conditions/io.kestra.core.models.conditions.types.orcondition)?

it will be more flexible I think

**Comment by sboisgontier-lmfr** [comment]
I tried to rewrite the example above with an And / Or condition
I did not manage to write something that is handling every state.
And it looks like very verbose compare to the example.
So it seems less flexible and more verbose / less low code. :sweat_smile: 

Do you have a solution? maybe I missed something with And / Or

**Comment by sboisgontier-lmfr** [comment]
Ah !! You mean this? 

```yaml
triggers:
  - type: io.kestra.core.models.conditions.types.OrCondition
    conditions:
      - type: io.kestra.core.models.conditions.types.AndCondition
        conditions:
          - id: listen-flow-a
            type: io.kestra.core.models.triggers.types.Flow
            conditions:
              - type: io.kestra.core.models.conditions.types.ExecutionStatusCondition
                in:
                  - SUCCESS
              - type: io.kestra.core.models.conditions.types.ExecutionFlowCondition
                namespace: io.kestra.demo
                flowId: multiplecondition-flow-a
          - id: listen-flow-b
            type: io.kestra.core.models.triggers.types.Flow
            conditions:
              - type: io.kestra.core.models.conditions.types.ExecutionStatusCondition
                in:
                  - SUCCESS
              - type: io.kestra.core.models.conditions.types.ExecutionFlowCondition
                namespace: io.kestra.demo
                flowId: multiplecondition-flow-b
      - type: io.kestra.core.models.conditions.types.AndCondition
        conditions:
          - id: listen-flow-a
            type: io.kestra.core.models.triggers.types.Flow
            conditions:
              - type: io.kestra.core.models.conditions.types.ExecutionStatusCondition
                in:
                  - SUCCESS
              - type: io.kestra.core.models.conditions.types.ExecutionFlowCondition
                namespace: io.kestra.demo
                flowId: multiplecondition-flow-a
          - id: listen-flow-b
            type: io.kestra.core.models.triggers.types.Flow
            conditions:
              - type: io.kestra.core.models.conditions.types.ExecutionStatusCondition
                in:
                  - ERROR
              - type: io.kestra.core.models.conditions.types.ExecutionFlowCondition
                namespace: io.kestra.demo
                flowId: multiplecondition-flow-b
```

**Comment by sboisgontier-lmfr** [comment]
I had in mind something like this ideally: 
```yaml
triggers:
  - id: multiple-listen-flow
    type: io.kestra.core.models.triggers.types.MultipleFlows
    window: P1D
    windowAdvance: P0D
    flows:
      flow-a:
        namespace: io.kestra.demo
        flowId: multiplecondition-flow-a
        in:
          - SUCCESS
      flow-b:
        namespace: io.kestra.demo
        flowId: multiplecondition-flow-b
        in:
          - SUCCESS
          - ERROR 
    conditions:
      - [other conditions...]
```

**Comment by tchiotludo** [comment]
The verbose version is working as expected?

**Comment by sboisgontier-lmfr** [comment]
With OrCondition accepting AndCondition, I suppose.

**Comment by anna-geller** [comment]
This will be possible in 0.20 (naming can change as we still iterate on it):

```yaml
id: myflow
namespace: company.team

triggers:
  - id: wait_for_upstream
    type: io.kestra.plugin.core.trigger.Flow
    conditions:
      - id: poll_for_flows
        type: io.kestra.plugin.core.condition.ExecutionsCondition
        preconditions:
          - namespace: company.team
            flowId: myflow1
            states: [SUCCESS, WARNING]
          - namespace: company.team
            flowId: myflow2
            states: [SUCCESS]

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: I'm triggered after two flows!
```
