### ISSUE TITLE
Date input should be able to have dynamic defaults value

### ISSUE THREAD

**Issue by Tagnard** [kestra-io/kestra#2287]
### Feature description

I want the input field of type Date to be able to have a default value of **now**, and it takes the date when the flow was executed.

**Comment by anna-geller** [comment]
works already when using a STRING input with a dynamic default input

```yaml
id: test
namespace: test

inputs:
  - id: "date"
    type: "STRING"
    defaults: "{{ now() }}"
```
