### ISSUE TITLE
Add a Dataform plugin

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2303]
### Feature description

Ideally, we should support both, the OSS project that allows using dataform for Snowflake, Redshift, BQ and more: https://github.com/dataform-co/dataform + https://docs.dataform.co/dataform-cli

```yaml
id: dataform
namespace: dev

tasks:
  - id: wdir
    type: io.kestra.core.tasks.flows.WorkingDirectory
    tasks:
      - id: clone_repo
        type: io.kestra.plugin.git.Clone
        url: https://github.com/dataform-co/dataform-example-project-bigquery
      - id: creds
        type: io.kestra.core.tasks.storages.LocalFiles
        inputs:
          .df-credentials.json: "{{ secret('GCP_CREDS') }}"

      - id: stack_overflow
        type: io.kestra.plugin.scripts.node.Commands
        beforeCommands:
          - npm i -g @dataform/cli
        commands:
          - dataform compile
          - dataform run
```

and the GCP Dataform service: https://cloud.google.com/dataform?hl=en
