### ISSUE TITLE
Kill API does not mark the Flow as "Killed" if Retry is associated to the Task.

### ISSUE THREAD

**Issue by spanhotra** [kestra-io/kestra#2308]
### Explain the bug

Below is my yaml

```yaml
id: sample-from-code
namespace: test
description: This is a sample Task.
tasks:
- tasks:
  - uri: ""
    body: ""
    contentType: application/json
    method: GET
    sslOptions:
      insecureTrustAllCertificates: true
    allowFailed: false
    description: Test Task
    timeout: P1D
    id: response_b8fc7ab6-69c8-430a-b2a5-3d1830bc75d9
    retry:
      delayFactor: 5
      maxInterval: PT10M
      interval: PT5S
      maxAttempt: 1000
      warningOnRetry: true
      maxDuration: P1D
      type: exponential
    type: io.kestra.plugin.fs.http.Request
  id: b8fc7ab6-69c8-430a-b2a5-3d1830bc75d9
  type: io.kestra.core.tasks.flows.Sequential

```

When the task gets into the retry mode. 
If I call a Kill API,
1. The response code is 204
2. It gets killed after the attempt iteration, but is marked as Failed instead of Killed

### Environment Information

- Kestra Version: 0.12.0
- Operating System and Java Version (if not using Kestra Docker image): Kestra Docker
