### ISSUE TITLE
Trigger conditions are not showing up when typing them in the low-code form

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#2311]
Reproducer:
```yaml
id: myflow
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 

triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "*/5 * * * *"
```

try adding `conditions`: 
![image](https://github.com/kestra-io/kestra/assets/2064609/6c113f5c-5040-43e1-8024-d86d134708a4)

![image](https://github.com/user-attachments/assets/2298de9f-81a1-4222-be39-77ed3a0ea240)

---

In the no code they also shows up on the right

![Screenshot 2025-01-29 at 10 58 43](https://github.com/user-attachments/assets/cda71d64-7bea-4e57-8a99-143c050f06ba)
