### ISSUE TITLE
[UI] Topology form shows an error message about any trigger added from the form as invalid trigger type

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2312]
### Explain the bug

![image](https://github.com/kestra-io/kestra/assets/86264395/67f878ba-d441-48f5-8508-a564a1d0d6cb)

the flow can be saved and everything works fine, only UI form shows this error 

## Reproducer

any flow - just add a trigger from the UI

```yaml
id: hello-world
namespace: dev
tasks:
  - id: hello
    type: io.kestra.core.tasks.log.Log
    message: Kestra team wishes you a great day! 👋
triggers:
  - id: everyMin
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "*/1 * * * *"
```

### Environment Information

- Kestra Version: 0.13.0
- Operating System and Java Version (if not using Kestra Docker image):
