### ISSUE TITLE
EE Namespace Variables unclear usage

### ISSUE THREAD

**Issue by TomCools** [kestra-io/kestra#2316]
### Issue description

I was trying to use the EE Namespace Variables in my flow. I had configured them as your pages suggest:

```
https://kestra.io/docs/administrator-guide/configuration/others#kestravariablesglobals

kestra:
  variables:
    globals:
      env: dev
```

Yet in my workflow, the flow fails because it can not find the variables. Just printing the {{ globals }} in a simple echo task returns {}. So it could find the variable but it seems to be empy. 

--

My hope is that the documentation on this one could be improved, or even have a pop-up to explain how this is supposed to work.
