### ISSUE TITLE
Consider adding support for evaluating filters and functions in variables

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2329]
### Feature description

It's a common question from the community wondering why something like this won't work:

```yaml
variables:
  yesterday: "{{ trigger.date ?? execution.startDate | dateAdd(-1, 'DAYS') }}"
  input_or_yesterday: "{{ input.your_input_name ?? execution.startDate | dateAdd(-1, 'DAYS') }}"
```

We should check if it might be possible to support evaluating such expressions in variables
