### ISSUE TITLE
Extend the automatically generated release notes with a dedicated section for breaking changes

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2331]
### Feature description

This needs a new step in the release workflow https://github.com/kestra-io/kestra/blob/develop/.github/workflows/main.yml to at least send us a reminder to edit the autogenerated release notes with that extra section

**Comment by anna-geller** [comment]
done

```yaml
      - name: Flow to add BC
        if: startsWith(github.ref, 'refs/tags/v')
        continue-on-error: true
        run: |
          curl --location "http://18.153.185.126:8080/api/v1/executions/webhook/product/release_notes/${{secrets.KESTRA_WEBHOOK_KEY}}" \
          --header 'Content-Type: application/json'
```
