### ISSUE TITLE
Add flow-level include/exclude filtering

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2341]
We want to **inject all namespace files by default** into a flow execution context. Because scripts are usually small files in the range of just a few KB, the added latency to fetch them into the execution context should be negligible.

However, this may _sometimes_ be not necessary (your flow doesn't use any namespace files) or lead to slower execution time when you do have thousands of files fetched from some monorepo. 

Therefore, we want to support an include/exclude pattern similar to the following:

```yaml
id: myflow
namespace: dev

namespaceFiles:
  include:
    - "**"  # Matches zero or more directories - used to fetch all Namespace Files for execution
    - "project1/**"  # fetch files from internal storage
  exclude:
    - "project1/*.sql"
```
