### ISSUE TITLE
A `taskDefaults` override is not working on `docker.pullPolicy`

### ISSUE THREAD

**Issue by yuri1969** [kestra-io/kestra#2364]
### Explain the bug

A non-forced `taskDefaults` setting do not override the `docker.pullPolicy` property of `io.kestra.plugin.scripts.shell.Commands`.

From a quick debugger session it looks like the task's `docker.pullPolicy` is set to the default value `ALWAYS` as if it was declared that way in the YAML. Therefore it doesn't get overridden by any non-forced `taskDefaults` setting.

```yaml
id: hello-world
namespace: dev

tasks:
 - id: commands
   type: io.kestra.plugin.scripts.shell.Commands
   runner: DOCKER
   docker:
     image: "ubuntu:20.04" # change to an image you haven't pulled
   commands:
     - 'echo "foo"'

taskDefaults:
- type: io.kestra.plugin.scripts.shell.Commands
  values:
    docker:
      pullPolicy: NEVER
```

### Environment Information

- Kestra Version: v0.13.0 as of Oct 20rd 2023
- Operating System and Java Version (if not using Kestra Docker image):
