### ISSUE TITLE
Add `namespace_files` resource to the Deploy Action to allow for Namespace Files deployment from GitHub CI/CD

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2369]
The ideal outcome would be to allow deploying both flows and namespace files from the same CI/CD workflow.

The action for flows already exists here: https://github.com/kestra-io/deploy-action -- the user points all flows from a given `directory` to be deployed to a given `namespace`. We should enrich that action with a `namespace_files` resource:

```yaml
      - name: deploy-prod
        uses: kestra-io/deploy-action@develop
        with:
          namespace: prod
          directory: ./src # defaults to deploy all files from the branch - possible?
          resource: namespace_files

# This will deploy all files in that directory except for files that match the regex defined in .kestraignore
```

## Ignore not needed files
Users will usually have flows and custom files within the same branch that may not need to be deployed to kestra. Therefore, it should be possible to define which files should be skipped from being deployed to kestra as Namespace Files e.g. using `.kestraignore` file.

Example of `.kestraignore` file (works the same way as `.gitignore`):

```
flows/
Dockerfile
docker-compose.yml
*.md
```

This example will skip all flows, markdown files, and Docker-related files from being deployed. All other files from the branch will be deployed to kestra as Namespace Files.
