### ISSUE TITLE
Add Ansible plugin

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2373]
The plugin repository has been created here: https://github.com/kestra-io/plugin-ansible 

We could provide a dedicated task to run playbooks in a similar way to the Ansible Python API:

```python
PlaybookExecutor(playbooks=[playbook_path], 
                        inventory=inventory, 
                        variable_manager=variable_manager,
                        loader=loader, 
                        passwords={}) 
```

However, there are so many ways to use Ansible that it seems better to provide a more generic `AnsibleCLI` task and allow users to leverage the same commands they use locally for orchestration.

---

## Proposed syntax

```yaml
id: ansible
namespace: dev

tasks:
  - id: setup
    type: io.kestra.core.tasks.flows.WorkingDirectory
    tasks:
      - id: local_files
        type: io.kestra.core.tasks.storages.LocalFiles
        inputs: 
          inventory.ini: "{{ read('inventory.ini') }}"
          myplaybook.yml: "{{ read('myplaybook.yml') }}"

      - id: ansible_task
        type: io.kestra.plugin.ansible.cli.AnsibleCLI
        docker:
          image: cytopia/ansible:latest-tools
        commands:
          - ansible-playbook -i inventory.ini myplaybook.yml
```

Once we support Namespace Files without the `read()` function, the CLI task will become even more intuitive, as the code below will be everything needed (apart from the Ansible project synced as namespace files):

```yaml
id: ansible
namespace: dev

tasks:
  - id: ansible_task
    type: io.kestra.plugin.ansible.cli.AnsibleCLI
    docker:
      image: cytopia/ansible:latest-tools
    commands:
      - ansible-playbook -i inventory.ini myplaybook.yml
```

---

## Testing the functionality

Ansible is a Python package, and it's already possible to orchestrate playbooks this way:

```yaml
id: ansible
namespace: dev

tasks:
  - id: setup
    type: io.kestra.core.tasks.flows.WorkingDirectory
    tasks:
      - id: local_files
        type: io.kestra.core.tasks.storages.LocalFiles
        inputs: 
          inventory.ini: |
            localhost ansible_connection=local
          myplaybook.yml: |
            ---
            - hosts: localhost
              tasks:
                - name: Print Hello World
                  debug:
                    msg: "Hello, World!"

      - id: ansible
        type: io.kestra.plugin.scripts.python.Commands
        warningOnStdErr: false
        docker:
          image: cytopia/ansible:latest-tools
        commands:
          - ansible-playbook -i inventory.ini myplaybook.yml
```

---

## Docker image

Red Hat doesn't provide any official Docker image for Ansible. However, we could use  https://hub.docker.com/r/cytopia/ansible (GitHub https://github.com/cytopia/docker-ansible) as someone nice already maintains various packages (kudos!). TBD whether it's OK to use this image in production or whether we need to maintain our images or add `beforeCommands` to install everything at runtime.
