### ISSUE TITLE
The `shell.Commands` task can't be validated 

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2379]
### Explain the bug

Using the 0.13.0 snapshot of both the develop branch and shell plugin
https://share.descript.com/view/5wcQUvzF5J2

same issue with Maven plugin https://mvnrepository.com/artifact/io.kestra.plugin/plugin-script-shell/0.12.0 

```yaml
id: bash_test
namespace: dev

tasks:
  - id: hello
    type: io.kestra.plugin.scripts.shell.Commands
    commands:
      - echo hello
```

I cannot save this flow.

I couldn't reproduce on preview so might be either Mac issue or I need to throw away my laptop 😄 

![image](https://github.com/kestra-io/kestra/assets/86264395/8ea31f93-3ec5-481e-b918-ccc123b1bcb7)

https://preview-oss.kestra.io/ui/executions/dev/bash_test/3CZtB98df1SOnHiSItv4jz/logs

### Environment Information

- Kestra Version: develop
