### ISSUE TITLE
Extend the `read()` Pebble function to allow reading an internal storage file from the current execution as a string value

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2380]
### Feature description

Often, users need to use Shell commands or custom scripts only to read a file from internal storage URI and grab some properties from JSON as raw values:

```yaml
  - id: lambdaResult
    type: io.kestra.plugin.scripts.shell.Commands
    runner: PROCESS
    commands:
      - cat {{outputs.lambda.uri}} | jq -r '.body'
```

It would be nice to have a function e.g. `{{ read_json(output.lambda.uri) }}` allowing to process specific values from that JSON in all dynamic fields without the need for extra script task steps
