### ISSUE TITLE
Add a Flow trigger to allow custom behavior when a given number of executions is in a specific state

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2386]
### Feature description

In the PR https://github.com/kestra-io/kestra/pull/2371, we're introducing `concurrencyLimit` property.

```yaml
concurrencyLimit: # null by default
  maxConcurrency: 1 # unlimited by default, otherwise a positive int
  behavior: QUEUE # possible values are QUEUE, CANCEL, FAIL
```

As a follow-up, we also want to support taking action if a specific number of executions reaches a certain condition. Example:

```yaml
id: concurrency_check
namespace: dev
tasks: 
  - id: myaction

triggers:
  - id: listen
    type: io.kestra.core.models.triggers.types.Flow
    conditions:
      - type: io.kestra.core.models.conditions.types.ExecutionStatusCondition
        in:
          - RUNNING
      - type: io.kestra.core.models.conditions.types.ExecutionFlowCondition
        namespace: prod
        flowId: important_flow
      - type: io.kestra.core.models.conditions.types.MaxConcurrency # Naming and implementation TBD
        maxConcurrency: 1
        behavior: CANCEL # cancel any new execution
```

This will allow users to e.g. cancel any new runs and send an alert anytime there is more than 1 execution. 

Additionally, because this is a trigger condition, users have total flexibility to implement a global namespace-level concurrency limit to implement their SLA strategy, e.g.:

```yaml
id: global_concurrency_limit
namespace: dev
tasks: 
  - id: myaction

triggers:
  - id: listen
    type: io.kestra.core.models.triggers.types.Flow
    conditions:
      - type: io.kestra.core.models.conditions.types.ExecutionStatusCondition
        in:
          - RUNNING
      - type: io.kestra.core.models.conditions.types.ExecutionNamespaceCondition
        namespace: prod
        prefix: true
      - type: io.kestra.core.models.conditions.types.MaxConcurrency # Naming and implementation TBD
        maxConcurrency: 100
        behavior: QUEUE # queue any new execution after reaching the limit of 100 executions in a namespace
```
