### ISSUE TITLE
Add a more fine-granular condition allowing to only trigger some action (e.g. alert) when a flow fails more than X times in a row

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2397]
### Feature description

An alternative (or additional) solution could be flow-level retries: https://github.com/kestra-io/kestra/issues/1496 

```yaml
triggers:
  - id: failed_prod_workflows
    type: io.kestra.core.models.triggers.types.Flow
    conditions:
      - type: io.kestra.core.models.conditions.types.ExecutionStatusCondition
        in:
          - FAILED
          - WARNING
      - type: io.kestra.core.models.conditions.types.ExecutionNamespaceCondition
        namespace: prod
        prefix: true
      - type: io.kestra.core.models.conditions.types.ExecutionCount
        count: 3
      # trigger the alert when the flow fails more than 3 times in a row
```
