### ISSUE TITLE
Add a SQL Mesh plugin

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2400]
With the new editor, it will be fairly easy to support orchestrating SQL Mesh in the same way as we do it with the Terraform CLI task.

Repo: https://github.com/TobikoData/sqlmesh

A blog showing their cool UI: https://tobikodata.com/sqlmesh-ui.html 

## Proposed syntax

Use the `ghcr.io/kestra-io/sqlmesh:latest` as default docker image.

```yaml
id: transform
namespace: dev
tasks:
  - id: sqlmesh
    type: io.kestra.plugin.sqlmesh.cli.SQLMeshCLI
    commands:
      - sqlmesh init duckdb
```

All other properties of the Python Commands like beforeCommands, docker, warningOnStdErr, etc should be supported.
