### ISSUE TITLE
Store Outputs (files and variables) generated in script tasks to internal storage immediately, rather than only after a successful task completion

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2407]
### Feature description

Currently, the output generated in the following task will not be captured:

```yaml
id: outputs
namespace: io.kestra.tests

tasks:
 - id: print
   type: io.kestra.plugin.scripts.shell.Commands
   commands:
      - echo "test1" > {{outputDir}}/test1.txt
      - exit 1 # processing of 'test1' fails
```

This is because outputs are currently only sent to internal storage after the task has been successfully completed. This makes troubleshooting difficult. To some extent, it defeats the purpose of the Output Preview feature, as it's most useful in a situation when something fails and you need to troubleshoot. 

Note: it applies to both:
- files e.g. `{{ outputDir }}` and `{{ outputFiles }}`
- variables stored as Outputs e.g. `{{ outputs.mytask.myvariable }}`

**Comment by anna-geller** [comment]
other example: allow to output something even though the python task fails:

```yaml
id: re_raise
namespace: dev
tasks:
  - id: hello
    type: io.kestra.plugin.scripts.python.Script
    runner: PROCESS
    script: |
      from kestra import Kestra
      try:
        # Deliberately causing a division by zero error
        result = 1 / 0
      except Exception as e:
        exception_message = str(e)
        # Outputting the exception message using Kestra's outputs method
        Kestra.outputs({"exception": exception_message})
        # Reraising the exception to ensure the script fails
        raise e
```
