### ISSUE TITLE
Add Modal plugin

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2413]
[Modal](https://modal.com/) provides excellent UX for serverless Python applications. It automatically builds container images and provisions infrastructure in the public cloud (AWS, Oracle and more) within seconds. There is no need for users to build container images manually and to provision infrastructure. Users only need to create an API token and use modal decorators in their scripts to define the infrastructure specification, incl. how much memory to allocate, and whether to run something on CPU or GPU, which packages to install etc:

```
pip install modal-client
modal token new
```

It dynamically builds container images and provisions infrastructure - no need for CI/CD, managing container image lifecycle etc. 

The new Editor will make it easy to schedule and orchestrate Python scripts written with Modal decorators as part of a bigger end-to-end pipeline. 

## Proposed minimal plugin syntax

```yaml
id: modal
namespace: dev

tasks:
  - id: hello
    type: io.kestra.plugin.modal.cli.ModalCLI
    commands:
      - modal run scripts/gpu.py
    env:
      MODAL_TOKEN_ID: "{{ secret('MODAL_TOKEN_ID') }}"
      MODAL_TOKEN_SECRET: "{{ secret('MODAL_TOKEN_SECRET') }}"
```

It can be built on top of the Python Commands task, similar to the `AnsibleCLI`, but using the image `ghcr.io/kestra-io/modal:latest`.

More info available here: http://localhost:8080/ui/blueprints/56
