### ISSUE TITLE
[UI] Inputs are not displayed in the Executions table

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2436]
### Explain the bug

![image](https://github.com/kestra-io/kestra/assets/86264395/a9af3f8f-1996-4e1a-85ae-6e8961b1c07e)

Simple reproducer:

```yaml
id: hello-world
namespace: dev

inputs:
  - name: greeting
    type: STRING
    defaults: hello

tasks:
  - id: hello
    type: io.kestra.core.tasks.log.Log
    message: "{{ inputs.greeting }}, kestra team wishes you a great day!"
```

### Environment Information

- Kestra Version: 0.13.0
- Operating System and Java Version (if not using Kestra Docker image):
