### ISSUE TITLE
The error "Unable to read a file that didn't belong to the current execution" is raised for the current execution

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2442]
### Explain the bug

Reproducer

Subflow:

```yaml
id: subflow_raw_string_input
namespace: qa

inputs:
  - name: string_input
    type: STRING
    defaults: hey there

tasks:
  - id: for_each_item
    type: io.kestra.core.tasks.debugs.Return
    format: "{{ inputs.string_input }}"
```

Parent reading the file for the current batch using the `read()` function and passing it to the subflow as raw string input:
```yaml
id: each_parent
namespace: qa

tasks:
  - id: extract
    type: io.kestra.plugin.jdbc.duckdb.Query
    sql: |
      INSTALL httpfs;
      LOAD httpfs;
      SELECT *
      FROM read_csv_auto('https://raw.githubusercontent.com/kestra-io/datasets/main/csv/orders.csv', header=True);
    store: true

  - id: each_raw
    type: io.kestra.core.tasks.flows.ForEachItem
    items: "{{ outputs.extract.uri }}"
    namespace: qa
    flowId: subflow_raw_string_input
    wait: true
    transmitFailed: true
    batch: 
      rows: 10
    inputs:
      string_input: "{{ read(taskrun.items) }}"
```

![image](https://github.com/kestra-io/kestra/assets/86264395/7c5994ae-d9f4-4589-af43-d6b101a20037)

### Environment Information

- Kestra Version: 0.13.0
