### ISSUE TITLE
Treat the Paused state the same way as Running with respect to concurrency limits

### ISSUE THREAD

**Issue by yuri1969** [kestra-io/kestra#2455]
### Explain the bug

Correct me if I'm wrong, but it seems the `io.kestra.core.tasks.flows.Pause` task doesn't follow the concurrency limits introduced by #2371.

Flows having the `Pause` task should follow the limitations imposed by the flow `concurrency` block. This means execution of the whole flow should finish before allowing the others to execute.

---

Launching 4 executions of the following flow results in two distinct sets of run times - one pair of executions got queued and waited in the _Created_ state for the other one to finish:

```yaml
id: shell-pause
namespace: company.team

concurrency:
  behavior: QUEUE
  limit: 2

tasks:
  - id: pre-pause
    type: io.kestra.core.tasks.log.Log
    message: Pre-pause
 
  - id: sleep
    type: io.kestra.plugin.scripts.shell.Commands
    commands:
      - sleep 10

  - id: post-pause
    type: io.kestra.core.tasks.log.Log
    message: Post-pause
```

OTOH, when you spawn multiple (4+) executions of the following flow the results are an odd combination of run times unlike the flow above:

```yaml
id: task-pause
namespace: company.team

concurrency:
  behavior: QUEUE
  limit: 2

tasks:
  - id: pre-pause
    type: io.kestra.core.tasks.log.Log
    message: Pre-pause

  - id: sleep
    type: io.kestra.core.tasks.flows.Pause
    delay: PT10S
    tasks:
      - id: post-pause
        type: io.kestra.core.tasks.log.Log
        message: Post-pause
```

### Environment Information

- Kestra Version: 0.13.0-SNAPSHOT as of Nov 6th 2023
- Operating System and Java Version (if not using Kestra Docker image): Linux Temurin 17.0.8
