### ISSUE TITLE
Add a task allowing to download, upload or delete specific Namespace Files

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2461]
Possible usage syntax:

```yaml
id: python
namespace: dev

tasks:
  - id: scripts
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      - id: fetch_scripts_from_parent_namespace
        type: io.kestra.plugin.core.namespace.Files
        action: DOWNLOAD # default; alternative options in the Enum property: UPLOAD, DELETE
        namespace: dev.shared
        files: # list of RegEx strings or specific file paths
          - "project1/*.py"

      - id: python
        type: io.kestra.plugin.scripts.python.Commands
        warningOnStdErr: false
        containerImage: ghcr.io/kestra-io/pydata:latest
        commands:
          - python project1/etl.py
```

On EE, we ensure that users can only download/upload/delete files from a different namespace if there are no restrictions in Allowed Namespaces.

**Comment by anna-geller** [comment]
minimal example with Azure batch for Yohann:

```yaml
id: azure
namespace: sg

tasks:
  - id: scripts
    type: io.kestra.core.tasks.flows.WorkingDirectory
    tasks:
      - id: fetch_scripts_from_parent_namespace
        type: io.kestra.core.tasks.namespace.NamespaceFiles
        action: DOWNLOAD # default; alternative options in the Enum property: UPLOAD, DELETE
        namespace: dev
        files: # list of RegEx strings or specific file paths
          - "project1/*.py"

      - id: python
        type: io.kestra.plugin.scripts.python.Commands
        warningOnStdErr: false
        docker:
          image: ghcr.io/kestra-io/pydata:latest
        commands:
          - python project1/etl.py
      
      - id: azure_batch
        type: io.kestra.plugin.azure.batch.job.Create
        endpoint: https://***.francecentral.batch.azure.com
        account: <batch-account>
        accessKey: <access-key>
        poolId: <pool-id>
        job:
          id: <job-name>
        tasks:
        - id: env
          commands:
          - python project1/first_script.py
          environments:
            ENV_STRING: "{{ inputs.first }}"
```
