### ISSUE TITLE
Add a flatten Pebble filter to allow to turn a list of lists into a flat list 

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2463]
### Feature description

Using first usually works just fine: `{{ json(read(outputs.extract.uri)) | jq('map(.detail | fromjson | .message)') | first }}`

![image](https://github.com/kestra-io/kestra/assets/86264395/ba21e7b9-3d84-4bb3-b576-682867af9719)

But may not be immediately intuitive. It's worth adding a `flatten` filter.

Full reproducer: 

```yaml
id: extract_json
namespace: dev
tasks:
  - id: extract
    type: io.kestra.plugin.fs.http.Download
    uri: https://huggingface.co/datasets/kestra/datasets/raw/main/json/app_events.json
  
  - id: read_json
    type: io.kestra.core.tasks.log.Log
    message: "{{ json(read(outputs.extract.uri)) }}"

  - id: parse_json
    type: io.kestra.core.tasks.log.Log
    message: "{{ json(read(outputs.extract.uri)) | jq('map(.detail | fromjson | .message)') | first }}"
```
