### ISSUE TITLE
Render flow variables before rendering the flow tasks

### ISSUE THREAD

**Issue by yuri1969** [kestra-io/kestra#2466]
### Feature description

There are use cases for flow `variables` containing dynamic values. This brings problems with "nested" usage in templates.

Rendering the `variables` before passing them to the flow renderer might solve this. However, doing this _might_ bring side effects.

---

For example, one would define a dynamic file name used through the flow's tasks as:

```yaml
variables:
  fileName: "foo-{{ inputs['input']['key'] }}-{{ execution.id }}"
```

---

Minimal flow example:

```yaml
id: map-test
namespace: io.kestra.test

inputs:
  - name: input.key
    type: STRING
    defaults: 'value'

variables:
  fileName: "{{ inputs['input']['key'] }}"

tasks:
  - id: write
    type: "io.kestra.core.tasks.debugs.Return"
    format: "foo"

  - id: read
    type: "io.kestra.core.tasks.debugs.Return"
    format: "{{ outputs.write.get(vars.fileName) }}" # FIXME: returns an empty string
```

**Comment by anna-geller** [comment]
Normally, variables are rendered recursively, meaning that if a variable contains another variable, the inner variable will be resolved first. Can you share a specific use case that is blocking you?

**Comment by anna-geller** [comment]
I also didn't fully understand the use of the .get() method here, only value is available 

![image](https://github.com/kestra-io/kestra/assets/86264395/56255fea-aadc-411d-bee9-a3042e474a90)

**Comment by yuri1969** [comment]
@anna-geller You are right, the example flow doesn't illustrate the feature very well.

Following flow doesn't resort to use `get()`:

```yaml
id: map-test-cplx
namespace: io.kestra.test

inputs:
  - name: input.key
    type: STRING
    defaults: 'FOO'

variables:
  # Holds file name referenced by multiple tasks
  fileName: "{{ inputs['input']['key'] }}-{{ execution['id'] }}-bar"

tasks:
  - id: write
    type: io.kestra.plugin.scripts.shell.Commands
    description: Write to a file - its name is dynamic.
    commands:
      - "echo 'TEST' > '{{ outputDir }}/{{ vars['fileName'] }}'"

  # ...

  - id: read
    type: io.kestra.plugin.scripts.shell.Commands
    description: Read from the file used in the previous task - its name is still dynamic.
    commands:
      - "cat '{{ outputs['write']['outputFiles'][vars['fileName']] }}'" # FIXME: the value of vars['fileName'] doesn't get fully resolved

taskDefaults:
  - type: io.kestra.plugin.scripts.shell.Commands
    values:
      runner: PROCESS
```

---

The main motivation behind this scheme is to prevent output files being named constantly. This brings issues with downloaded outputs having the same name, etc.

**Comment by yuri1969** [comment]
Closing as the https://github.com/kestra-io/kestra/pull/2588 PR fixed this issue. QAed using v0.13.4.

**Comment by loicmathieu** [comment]
Reopened because the fix has been reverted in https://github.com/kestra-io/kestra/pull/2754

**Comment by anna-geller** [comment]
will this PR help solve the issue? https://github.com/kestra-io/kestra/pull/2770

**Comment by anna-geller** [comment]
closing the issue as all these patterns are now possible:

```yaml
id: map-test
namespace: io.kestra.test

inputs:
  - name: input.key
    type: STRING
    defaults: 'value'

variables:
  fileName: "{{ inputs['input']['key'] }}"

tasks:
  - id: read
    type: "io.kestra.core.tasks.debugs.Return"
    format: "{{ render(vars.fileName) }}"
```

and the second use case - we don't support rendering nested outputFile - for that, we recommend using inputFiles property and then accessing the nested file by name:

```yaml
id: map-test-cplx
namespace: io.kestra.test

inputs:
  - name: input.key
    type: STRING
    defaults: 'FOO'

variables:
  # Holds file name referenced by multiple tasks
  fileName: "{{ inputs['input']['key'] }}-{{ execution['id'] }}-bar"

tasks:
  - id: write
    type: io.kestra.plugin.scripts.shell.Commands
    description: Write to a file - its name is dynamic.
    commands:
      - "echo 'TEST' > '{{ outputDir }}/{{ render(vars.fileName) }}'"

  - id: read
    type: io.kestra.plugin.scripts.shell.Commands
    inputFiles: "{{ outputs.write.outputFiles }}"
    commands:
      - cat '{{ render(vars.fileName) }}'

taskDefaults:
  - type: io.kestra.plugin.scripts.shell.Commands
    values:
      runner: PROCESS
```
