### ISSUE TITLE
Nested directories of Namespace Files lose their object prefix

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2480]
### Explain the bug

Reproducer: start `docker run --rm -it -p 28080:8080  kestra/kestra:develop-full  server local`

Run:
```yaml
id: ci
namespace: prod

variables:
  host: http://host.docker.internal:28080/

tasks:
  - id: deploy
    type: io.kestra.core.tasks.flows.WorkingDirectory
    tasks:
      - id: clone
        type: io.kestra.plugin.git.Clone
        url: https://github.com/kestra-io/scripts
        branch: main

      - id: deploy_files
        type: io.kestra.plugin.scripts.shell.Commands
        warningOnStdErr: false
        runner: PROCESS
        commands:
          - /app/kestra namespace files update prod etl/data_lake/ --server={{vars.host}}
```

### Environment Information

- Kestra Version: develop full
- Operating System and Java Version (if not using Kestra Docker image):
