### ISSUE TITLE
The enabled flag on `namespaceFiles` should not have any default property

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2512]
### Feature description

Currently, enabled is by default set to true:

![image](https://github.com/kestra-io/kestra/assets/86264395/3f0d8441-e7db-45f3-ab1b-fc05c4c9d7ee)

This may cause confusion as it sounds like kestra would load all namespace files by default into the task's working directory. This is not intended. 

TODO: there should be no default value on enabled flag (null rather than true)

**Comment by loicmathieu** [comment]
Today as `enabled` is true by default you can write:

```yaml
namespaceFiles:
  include:
  - subdir/**
 ```

If we remove this default value we will need to add the value for each usage of namespace file:

```yaml
namespaceFiles:
  enabled: true
  include:
  - subdir/**
 ```
