### ISSUE TITLE
When a file provided as `items` property cannot be split into batches, the execution ends in an error without any log message explaining why this task failed

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2517]
We should raise a friendly error message if the value of the `items` property is not a valid Kestra's internal storage URI. Trying to pass a string that is not a URI doesn't raise any error/warning. The task fails with no information explaining why it failed. It would be great to add extra info for troubleshooting e.g. "It looks like you didn't pass the correct value to the `items` property. Make sure that you set this to an internal storage URI, such as a FILE input or output URI from the previous task."

## Reproducer

subflow:
```yaml
id: orders
namespace: prod

inputs:
  - name: order
    type: STRING

tasks:
  - id: read_file
    type: io.kestra.plugin.scripts.shell.Commands
    runner: PROCESS
    commands:
      - cat "{{ inputs.order }}"

  - id: read_file_content
    type: io.kestra.core.tasks.log.Log
    message: "{{ read(inputs.order) }}"
```

parent: 

```yaml
id: orders_batch
namespace: prod

tasks:
  - id: extract
    type: io.kestra.plugin.fs.http.Download
    uri: https://huggingface.co/datasets/kestra/datasets/resolve/main/json/user_events.json

  - id: each
    type: io.kestra.core.tasks.flows.ForEachItem
    items: "{{ read(outputs.extract.uri) }}" # at runtime, we should give a friendly error message that this is not a valid internal storage file's URI
    batch:
      rows: 1
    namespace: prod
    flowId: orders
    wait: true
    transmitFailed: true
    inputs:
      order: "{{ taskrun.items }}"
```

![image](https://github.com/kestra-io/kestra/assets/86264395/4a12795f-6383-40ed-a9fa-2d042485f4b2)

![image](https://github.com/kestra-io/kestra/assets/86264395/c473f97c-453f-4d3c-91d9-39b1b259ef85)
