### ISSUE TITLE
Splitting a CSV or JSON file as `items` on the `ForEachItem` results in too many items

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2519]
Taking a CSV or JSON input currently doesn't work as expected due to a potential lack of logic for splitting those specific file types. 

1. Trying to split a CSV file into rows will treat the header as a row to iterate over
2. Trying to split a JSON list of items will split them based on a `\n` character instead of splitting them by list items.

## Reproducer 

subflow:
```yaml
id: orders
namespace: prod

inputs:
  - name: order
    type: STRING

tasks:
  - id: read_file
    type: io.kestra.plugin.scripts.shell.Commands
    runner: PROCESS
    commands:
      - cat "{{ inputs.order }}"

  - id: read_file_content
    type: io.kestra.core.tasks.log.Log
    message: "{{ read(inputs.order) }}"
```

parent: 

```yaml
id: orders_batch
namespace: prod

tasks:
  - id: extract
    type: io.kestra.plugin.fs.http.Download
    description: | 
      1) for CSV, the header counts into rows and there is currently no way to exclude the header. 
      2) with JSON, even when using a separator, it still splits items by new-line characters instead of list items, resulting in 86 records instead of only 21 records
    uri: https://huggingface.co/datasets/kestra/datasets/resolve/main/json/user_events.json
    # uri: https://raw.githubusercontent.com/kestra-io/datasets/main/csv/orders.csv

  - id: extract1
    type: io.kestra.plugin.jdbc.duckdb.Query
    description: ION input works ✅ 
    disabled: true
    sql: |
      INSTALL httpfs;
      LOAD httpfs;
      SELECT *
      FROM read_csv_auto('https://raw.githubusercontent.com/kestra-io/datasets/main/csv/orders.csv', header=True);
    store: true

  - id: each
    type: io.kestra.core.tasks.flows.ForEachItem
    items: "{{ outputs.extract.uri }}" 
    batch:
      rows: 1
    namespace: prod
    flowId: orders
    wait: true
    transmitFailed: true
    inputs:
      order: "{{ taskrun.items }}"
```
