### ISSUE TITLE
A flow named `files` mixed up with namespace files

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#2526]
### Explain the bug

Namespace files creates files inside the `/my/namespaces/files` directory.
Imagine the following flow:
```yaml
id: files
namespace: dev
tasks:
  - id: extract
    type: io.kestra.plugin.gcp.bigquery.Query
    sql: |
      SELECT DATETIME(datehour) as date, title, views FROM `bigquery-public-data.wikipedia.pageviews_2023` 
      WHERE DATE(datehour) = DATE_SUB(CURRENT_DATE(), INTERVAL 1 DAY) and wiki = 'fr' and title not in ('Cookie_(informatique)', 'Wikipédia:Accueil_principal', 'Spécial:Recherche')
      ORDER BY datehour desc, views desc
      LIMIT 10
    store: true
```

Its execution files will be visible inside the namespace files editor which is not a good idea for various reasons.

We discuss this issue internally and we will move namespace files prefix directory to `_files` ~and prevent starting a flow and a namespace by `_` which is a breaking change~.

EDIT: flows and namespace are slugify so we don't need to prevent starting a flow with `_`.

### Environment Information

- Kestra Version:
- Operating System and Java Version (if not using Kestra Docker image):
