### ISSUE TITLE
Paused execution state should count to concurrency limits on JDBC

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2534]
### Explain the bug

Currently, Paused state still doesn't count to concurrency limits as it should, at least on JDBC 

## Reproducer

```yaml
id: flow-paused-concurrency
namespace: dev
concurrency:
  limit: 1
  behavior: CANCEL
tasks:
  - id: pause
    type: io.kestra.core.tasks.flows.Pause
    delay: PT30S
    tasks:
      - id: task-pause
        type: io.kestra.core.tasks.log.Log
        message: hello
```

![image](https://github.com/kestra-io/kestra/assets/86264395/0072c6dc-cbb1-4aa6-8994-b1c32a7aa8b5)

## Works with Kafka

The same works correctly with Kafka. @loicmathieu please cross-check, I was convinced we've tackled this already

![image](https://github.com/kestra-io/kestra/assets/86264395/7eeea195-d88e-4a1e-a126-5be5cd458bf9)
