### ISSUE TITLE
Allow launching task in a dedicated Pod

### ISSUE THREAD

**Issue by aballiet** [kestra-io/kestra#2536]
### Feature description

Currently Kestra launches tasks on a Worker pod which can handle several tasks at once (limit is set by `--thread` option).

In order to provide more flexibility for resource management and scaling, we should allow users to create heavy tasks in dedicated pods. Airbyte is doing it to enable easier scaling.

Feature could be similar as : 

```YAML
id: "pod_create"
type: "io.kestra.plugin.kubernetes.PodTaskCreate"
namespace: default
metadata:
  labels:
    my-label: my-value
spec:
  task: 
    id: dbt-build
    type: io.kestra.plugin.dbt.cli.DbtCLI
    docker:
      image: ghcr.io/kestra-io/dbt-duckdb
    commands:
      - dbt build
  resources:
    limits:
      cpu: "1"
    requests:
      cpu: 500m
```

For implementation details, we would need to be able to upload a file working directory inside the pod
