### ISSUE TITLE
Add a `retryOn` property allowing to specify retry conditions such as a specific exception/error type

### ISSUE THREAD

**Issue by Melkaz** [kestra-io/kestra#2555]
### Feature description

Hello,

The retry mechanism allows a task to be automatically re-executed upon error.
Unfortunately, it seems we cannot catch specific errors and handle them differently.

For example, if a job on a cloud-based executor (e.g. AWS Batch, Azure Batch, GCP) fails because the service crashes or if something is wrong in the code running in those computing nodes, the event will be treated the same by Kestra.
Being able to define which follow-up to perform based on the error would be great. Continuing the previous example, one may want to re-submit to the cloud-based executor is the error is due to a network issue, while you wouldn't want to retry if the error originated from your POORLY developed software (not that I know anything about that).

Cheers,

Y.

**Comment by anna-geller** [comment]
This one might be challenging to implement in a language-agnostic framework like kestra. Example:

```yaml
id: py
namespace: dev
tasks:
  - id: hello
    type: io.kestra.plugin.scripts.python.Script
    runner: PROCESS
    retryOn: 
     - ValueError
    script: |
      raise ValueError("Something went wrong")
```

This will not work as the Java exception for this will be: `io.kestra.plugin.scripts.exec.scripts.runners.ScriptException: Command failed with code 1`

![image](https://github.com/kestra-io/kestra/assets/86264395/47c474f6-32a1-4a7b-b6ad-965ccf84c3cb)
