### ISSUE TITLE
Require basic auth `username` to be a valid email address + add validation to ensure a valid email address format

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2563]
### Feature description

```yaml
        kestra:
          server:
            basic-auth:
              enabled: false
              username: myuser
              password: mypassword
```

In this case, we should throw an exception that the username `myuser` is not a valid email address. 

See https://github.com/kestra-io/kestra/pull/2564
