### ISSUE TITLE
Discrepencies between manual and trigger execution in variabe handling

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#2585]
### Explain the bug

Depending if the execution is run manually or via a trigger, the `vars.period` variable doesn't have the same behavior; especially on the `replace` Pebble method:

```yaml
id: copine_voyage_troubleshoot
namespace: dev

variables:
  period: "{{ schedule.date ?? execution.startDate | dateAdd(-1, 'DAYS') | date('yyyy-MM') }}"

tasks:

  - id: debug
    type: io.kestra.core.tasks.log.Log
    message: "Period: {{ vars.period }}, {{ vars.period | replace({'-': ''}) }}, {{ vars.period | replace({'2023': 'toto'}) }}"

triggers:
  - id: schedule
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "0 12 1 * *"
    backfill:
      start: 2023-08-01T00:00:00Z
```

When running manually (working fine, except for the "toto" replacement):
![image](https://github.com/kestra-io/kestra/assets/46634684/4102a0a7-675f-49bb-b560-e752e3ed4558)

When running from trigger (here backfill schedule):

![image](https://github.com/kestra-io/kestra/assets/46634684/c68c1e3c-880b-4eb3-8c36-145fd6e70498)

### Environment Information

- Kestra Version: 0.13.0
- Operating System and Java Version (if not using Kestra Docker image):

**Comment by Ben8t** [comment]
Seems like the `replace` method doesn't handle string/datetime very well

![image](https://github.com/kestra-io/kestra/assets/46634684/61f28a37-3156-42ec-9a21-aedecbc13adc)

**Comment by loicmathieu** [comment]
Reopened because the fix has been reverted in https://github.com/kestra-io/kestra/pull/2754

**Comment by anna-geller** [comment]
closing as with the render function (non-recursive behavior), both manual and scheduled executions generate identical results:

```yaml
id: copine_voyage_troubleshoot
namespace: dev

variables:
  period: "{{ schedule.date ?? execution.startDate | dateAdd(-1, 'DAYS') | date('yyyy-MM') }}"

tasks:
  - id: debug
    type: io.kestra.core.tasks.log.Log
    message: |
      Period: {{ render(vars.period) }}
      {{ render(vars.period) | replace({'-': ''}) }}
      {{ render(vars.period | replace({'-': ''})) }}
      {{ render(vars.period) | replace({'2023': 'toto'}) }}
      {{ render(vars.period | replace({'2023': 'toto'})) }}

triggers:
  - id: schedule
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "*/1 * * * *"
```

@Ben8t please open a new issue if you see any usage patterns not being feasible with the new behavior in 0.14.0
