### ISSUE TITLE
Re-enabled Schedule trigger prevents triggering new executions

### ISSUE THREAD

**Issue by yuri1969** [kestra-io/kestra#2587]
### Explain the bug

The `Schedule` trigger can be disabled in a similar fashion as other triggers. This feature is employed to temporarily stop scheduled flows from executing.

The concern is re-enabling a disabled schedule trigger when no backfill of "missed" executions is desired. E.g. in case of having a `*/2 * * * *` schedule disabled for a few days.

The `lateMaximumDelay` property should help to reduce the backfill. Instead, it prevents spawning of new executions after the trigger re-enabling.

# Reproduction Steps

Create the following flow:

```yaml
id: hello-world-trigger
namespace: dev

triggers:
  - id: cron-per-minute
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "* * * * *"
    disabled: false # enabled; then disabled; then enabled again
    description: >
      This schedule aims to emulate a plain cron.
      * Disabled trigger doesn't spawn any new execution when the timer hits.
      * Enabled trigger does spawn new executions when the timer hits.
    lateMaximumDelay: PT10S # reduce backfill

tasks:
  - id: hello
    type: io.kestra.core.tasks.log.Log
    message: Kestra team wishes you a great day! 👋
```

1. Keep the scheduler running for >1 min after saving the flow
1. Disable the trigger via `disabled: false`
1. Wait for >1min after saving the flow
1. Re-enable the trigger via `disabled: true`
1. Wait >1min after saving the flow
1. No new executions are spawned

After removing the `lateMaximumDelay` the backfill appears and new executions are spawned properly.

### Environment Information

- Kestra Version: 0.12.3 & H2 standalone
- Operating System and Java Version (if not using Kestra Docker image): Windows + Temurin 17
