### ISSUE TITLE
Error: Couldn't expand subflow - Unable to find subflow namespace_flowId for task flow_task_id

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2623]
### Explain the bug

![image](https://github.com/kestra-io/kestra/assets/86264395/52f8afdc-3b8e-4908-b302-cd3c46dc8a56)

on the develop currently 

child:
```yaml
id: child
namespace: qa

inputs:
  - name: test
    type: STRING

tasks:
  - id: hello
    type: io.kestra.core.tasks.log.Log
    message: "input: {{inputs.test}}"
```

parent:

```yaml
id: parent
namespace: qa

tasks:
  - id: flow1
    type: io.kestra.core.tasks.flows.Flow
    namespace: qa
    flowId: child
    wait: true
    transmitFailed: true
    inputs:
      test: "Flow 1"

  - id: flow2
    type: io.kestra.core.tasks.flows.Flow
    namespace: qa
    flowId: child
    wait: true
    transmitFailed: true
    inputs:
      test: "Flow 2"

  - id: flow3
    type: io.kestra.core.tasks.flows.Flow
    namespace: qa
    flowId: child
    wait: true
    transmitFailed: true
    inputs:
      test: "Flow 3"
```

### Environment Information

- Kestra Version: latest
- Operating System and Java Version (if not using Kestra Docker image):
