### ISSUE TITLE
Cannot invoke "String.equals(Object)" because the return value of "io.kestra.core.models.flows.Flow.getTenantId()" is null

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2624]
### Explain the bug

on EE without a default tenant 

![image](https://github.com/kestra-io/kestra/assets/86264395/5dd6fcd2-2a48-4221-8e1b-e4f1d03fe10b)

## reproducer

child:
```yaml
id: child
namespace: qa

inputs:
  - name: test
    type: STRING

tasks:
  - id: hello
    type: io.kestra.core.tasks.log.Log
    message: "input: {{inputs.test}}"
```

parent:

```yaml
id: parent
namespace: qa

tasks:
  - id: flow1
    type: io.kestra.core.tasks.flows.Flow
    namespace: qa
    flowId: child
    wait: true
    transmitFailed: true
    inputs:
      test: "Flow 1"

  - id: flow2
    type: io.kestra.core.tasks.flows.Flow
    namespace: qa
    flowId: child
    wait: true
    transmitFailed: true
    inputs:
      test: "Flow 2"

  - id: flow3
    type: io.kestra.core.tasks.flows.Flow
    namespace: qa
    flowId: child
    wait: true
    transmitFailed: true
    inputs:
      test: "Flow 3"
```

### Environment Information

- Kestra Version:
- Operating System and Java Version (if not using Kestra Docker image):
