### ISSUE TITLE
Perform a benchmark of how many executions a specific JDBC setup can handle as alternative to Kafka

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2626]
### Feature description

- Postgres with X configuration can handle X concurrent executions
- Postgres with Y configuration can handle X concurrent executions
- Postgres with Z configuration can handle X concurrent executions
- MySQL with X configuration can handle X concurrent executions
- etc.

**Comment by smunteankestra** [comment]
I can start a load test with JMeter for this, but would require some hep with the Postgres specifications - meaning what configs we expect and why

**Comment by paulgrainger85** [comment]
I don't think we necessarily need to go deep into Postgres/MYSQL tuning for this benchmark. Best use "out-of-the-box" settings or anything our engineers deem best practices only. 

I think the dimensions we should benchmark against are
- Versions: PG 16, MYSQL 8.0.38 (prioritise PG first)
- CPU / RAM (2CPU 8GB and 4CPU 16GB to start)
- Cloud Service (AWS RDS, Azure Flexible Server for PG, Google Cloud SQL - in that order of priority)
- (Stretch goal) EBS vs local disk - e.g AWS i3 has locally attached NVMe

**Comment by smunteankestra** [comment]
@paulgrainger85 
Good point, thanks

Environment used: ran the docker compose with postgres lcated in e2e-tests-ee/docker/data
I've setup for the first load test 1 million of executions  🥇  and of course it failed, at about 250k execution triggers Kestra still responded with 200 code - btw- used the simplest flow - the hello world one :) 

on the second attempt -  used 200 parallel users, with a lopp count of 100 - meaning expecting 20k executions, and they succeeded! but duration is quite high - most likely they went in queue and where eventually finish 
![image](https://github.com/user-attachments/assets/d80ef527-d529-4f30-888c-5c23ba92d71e)
![image](https://github.com/user-attachments/assets/c2ebbbc6-80b7-4779-89da-48ffaedc3dd4)


now should I increase the users/executions untill kestra crushes? 
and about the flow I assumed Hello world flow  would work, do we need a more complex flow?

**Comment by anna-geller** [comment]
Flow we can use:

```yaml
id: benchmark
namespace: company.team

inputs:
  - id: myinput
    type: STRING
    defaults: hello
  
  - id: myboolean
    type: BOOLEAN
    defaults: true

tasks:
  - id: parallel
    type: io.kestra.plugin.core.flow.Parallel
    tasks:
      - id: if
        type: io.kestra.plugin.core.flow.If
        condition: "{{ inputs.myboolean }}"
        then:
          - id: scripts
            type: io.kestra.plugin.core.flow.Sequential
            tasks:
              - id: shell
                type: io.kestra.plugin.scripts.shell.Commands
                commands:
                  - echo "hello from {{ task.id }}"
                taskRunner:
                  type: io.kestra.plugin.core.runner.Process
              - id: python
                type: io.kestra.plugin.scripts.python.Script
                script: |
                  from kestra import Kestra
                  Kestra.outputs({'executionDate': '{{ execution.startDate }}'})
                taskRunner:
                  type: io.kestra.plugin.core.runner.Process

      - id: process_data
        type: io.kestra.plugin.core.flow.Sequential
        tasks:
          - id: query
            type: io.kestra.plugin.core.http.Download
            uri: https://huggingface.co/datasets/kestra/datasets/resolve/main/ion/employees.ion

          - id: to_csv
            type: io.kestra.plugin.serdes.csv.IonToCsv
            from: "{{ outputs.query.uri }}"

          - id: to_excel
            type: io.kestra.plugin.serdes.excel.IonToExcel
            from: "{{ outputs.query.uri }}"
```

**Comment by anna-geller** [comment]
how we test: as soon as you reach 50% of CPU, you reach the max for that configuration

**Comment by anna-geller** [comment]
to trigger 1000s of executions we can use ForEachItem:

```yaml
id: benchmark_parent
namespace: company.team

inputs:
  - id: nr_executions
    type: INT
    defaults: 1000

tasks:
  - id: shell
    type: io.kestra.plugin.scripts.shell.Script
    outputFiles:
      - images.csv
    script: | 
      seq -f "kestra/myimage:v%g" 1 {{inputs.nr_executions}} > images.csv

  - id: hello
    type: io.kestra.plugin.core.flow.ForEachItem
    items: "{{ outputs.shell.outputFiles['images.csv'] }}"
    flowId: benchmark
    namespace: company.team
    wait: true
    transmitFailed: true
    inputs:
      myinput: "{{ read(taskrun.items) }}"
```
