### ISSUE TITLE
Allow ForEachItem to read the raw item instead of file

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2628]
### Feature description

```yaml
    labels:
      url: "{{ fromJson(taskrun.items).html_url }}"
      # url: "{{ read(taskrun.items) | jq('.html_url') | first }}"
```
