### ISSUE TITLE
Add a dedicated task allowing to set custom Execution Labels from a flow

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2632]
### Feature description

Possible syntax:

```yaml
id: labels_test
namespace: dev

inputs:
  - name: myinput
    type: STRING

tasks:
  - id: labels
    type: io.kestra.core.tasks.executions.Labels
    labels:
      mykey: "{{ inputs.myinput }}"
```

This will also address this request in a straightforward and explicit manner https://github.com/kestra-io/kestra/issues/1760 as it's otherwise difficult to sometimes add labels from inputs (nested JSON etc)

Additionally, this task allows setting execution labels based on specific task outputs, flow progress, etc. - many use cases enabled by adding this.
