### ISSUE TITLE
Duplicated subflow logs when the parent flow is in error

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#2641]
### Explain the bug

When a parent flow is in error, for ex when outputs are defined that are incorrect, the logs displays multiple time the subflow logs.

Take this flow by example (with a subflow that exist and works):
```yaml
id: subflow
namespace: company.team
tasks:
  - id: flow
    type: io.kestra.core.tasks.flows.Flow
    flowId: hello-world
    namespace: company.team
    wait: true
    outputs:
      missing: "{{vars.missing}}"
```

![image](https://github.com/kestra-io/kestra/assets/1819009/7eb0f1f3-0c00-417c-85bb-be3e651b58a5)

### Environment Information

- Kestra Version: 0.14-SNAPSHOT
- Operating System and Java Version (if not using Kestra Docker image):
