### ISSUE TITLE
Output the count of namespace files

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2647]
### Feature description

We now have several tasks interacting with namespace files. It would be great to add a count of all files in a namespace.

Example:

```yaml
id: push
namespace: dev

inputs:
  - name: commit_message
    type: STRING
    defaults: my commit message

tasks:
  - id: push
    type: io.kestra.plugin.git.Push
    commitMessage: "{{ inputs.commit_message }}"
    branch: feature
    url: https://github.com/anna-geller/kestra
    username: anna-geller
    password: xxxx
    inputFiles:
      hello.txt: hello from a flow
```

Here we could share how many files from that namespace were pushed to Git.
