### ISSUE TITLE
Webhook conditions are sometimes not evaluated correctly

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2649]
### Feature description

Using the following trigger:

```yaml
triggers:
  - id: GitHub
    type: io.kestra.core.models.triggers.types.Webhook
    key: xxxxxxxx
    conditions:
      - type: io.kestra.core.models.conditions.types.VariableCondition
        expression: "{{ trigger.body.pull_request.user.login ?? trigger.body.issue.user.login != 'dependabot[bot]' }}"
```

with a GitHub webhook subscribed to both pull requests and issues returns 204 responses instead of 200 when using payload with `trigger.body.issue.user.login` being a normal user (it happened with my user login `anna-geller`).

This is unexpected, as 204 in this condition should only happen for dependabot. 

The error may not always appear. Some webhooks are properly delivered and some unexpectedly return 204.
