### ISSUE TITLE
Provide a flow configuration allowing to create a failed execution on wrong inputs

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2650]
### Feature description

Related to this issue: https://github.com/kestra-io/kestra/issues/1533, we may also consider creating a failed execution if provided inputs were invalid.  

Currently, kestra doesn't create any execution when inputs don't pass validation. However, sometimes it's desirable to create a failed execution in such a scenario. We may add a dedicated property on each input or on a flow level (TBD)

some examples worth exploring - `behavior` property on each input, similar to concurrency: 

```yaml
id: hello
namespace: dev

inputs:
  - name: mynumber
    type: INT
    behavior: FAIL # SKIP is default

tasks:
  - id: hello
    type: io.kestra.core.tasks.log.Log
    message: "{{inputs.mynumber}}"
```

or flow-level `invalidInputs` Enum:

```yaml
id: hello
namespace: dev
invalidInputs: FAIL # SKIP is default

inputs:
  - name: mynumber
    type: INT

tasks:
  - id: hello
    type: io.kestra.core.tasks.log.Log
    message: "{{inputs.mynumber}}"
```

**Comment by loicmathieu** [comment]
For executions created by the Scheduler (Schedule and Polling Triggers) there will be a failed execution (since 0.15).

But for executions created by webhook or from the API, the webook and API call will fail.

Do you still want something different?

**Comment by anna-geller** [comment]
yes, I've heard request of some users wanting to fail an execution if wrong inputs were provided rather than rejecting creating an execution

imagine:
```yaml
id: hello
namespace: dev

inputs:
  - name: myurl
    type: URI

tasks:
  - id: hello
    type: io.kestra.core.tasks.log.Log
    message: "{{inputs.myurl}}"
```

and try to launch it with input "ABC" - it will reject creating an execution with a message "Illegal argument: Invalid URI format for 'myurl' for 'abc'" instead of creating a failed execution. let me cross-check if this still is an issue
