### ISSUE TITLE
ExecutionFlowCondition breaks the Dependencies view

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2654]
### Feature description

I currently have the following Dependencies for the alert flow:

![image](https://github.com/kestra-io/kestra/assets/86264395/ff92ab70-1287-4c34-9e39-cbfed6bc969b)

As soon as I want that this flow also alerts me on failure of a `clean up` flow from the `system` namespace (different namespace than in the other condition), the trigger breaks.

```yaml
id: alert
namespace: system

tasks:
  - id: send
    type: io.kestra.plugin.notifications.slack.SlackExecution
    url: "{{ secret('SLACK_WEBHOOK') }}"
    channel: "#general"
    executionId: "{{trigger.executionId}}"

triggers:
  - id: listen
    type: io.kestra.core.models.triggers.types.Flow
    conditions:
      - type: io.kestra.core.models.conditions.types.ExecutionStatusCondition
        in:
          - FAILED
          - WARNING
      - type: io.kestra.core.models.conditions.types.ExecutionNamespaceCondition
        namespace: product
        prefix: true
      - type: io.kestra.core.models.conditions.types.ExecutionFlowCondition
        flowId: cleanup
        namespace: system
```

Adding that last `ExecutionFlowCondition` condition breaks the dependency view (nothing is shown under Dependencies anymore across the instance). Full code https://github.com/kestra-io/product-automations

**Comment by anna-geller** [comment]
we need to document that you need to use Or condition here

```yaml
id: alert
namespace: system

tasks:
  - id: send
    type: io.kestra.plugin.notifications.slack.SlackExecution
    url: "{{ secret('SLACK_WEBHOOK') }}"
    channel: "#general"
    executionId: "{{trigger.executionId}}"

triggers:
  - id: listen
    type: io.kestra.core.models.triggers.types.Flow
    conditions:
      - type: io.kestra.core.models.conditions.types.ExecutionStatusCondition
        in:
          - FAILED
          - WARNING
      - type: io.kestra.core.models.conditions.types.OrCondition
        conditions:
          - type: io.kestra.core.models.conditions.types.ExecutionNamespaceCondition
            namespace: product
            prefix: true
          - type: io.kestra.core.models.conditions.types.ExecutionFlowCondition
            flowId: cleanup
            namespace: system
```
