### ISSUE TITLE
Add Apache Camel plugin and implement initial task(s) and trigger(s)

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2708]
### Feature description

Camel supports many useful connectors: https://camel.apache.org/components/4.0.x/index.html 

Once concrete use case from the user: use Camel to retrieve users from LDAP, then perform some action (such as scheduling an onboarding workflow for the employee's first day) for each user matching filter criteria. 

Early discussions - sth like this would be possible:

```yaml
id: dropbox_to_bq
namespace: dev

tasks:
  - id: source
    type: io.kestra.plugin.camel.connectors.Dropbox
    from: "dropbox://myfile.csv"
    # to: outputs.source.uri # optional - default internal storage. Alternatively provide the destination to: "s3://kestraio/myfile.csv"

  - id: to_bq
    type: io.kestra.plugin.gcp.bigquery.Load
    from: "{{outputs.source.uri}}"
```
