### ISSUE TITLE
Add an API endpoint and a task allowing to disable a trigger (optionally based on a condition)

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2717]
### Feature description

Imagine the following flow:

```yaml
id: http
namespace: dev

tasks:
  - id: slack
    type: io.kestra.plugin.notifications.slack.SlackIncomingWebhook
    url: "{{ secret('SLACK_WEBHOOK') }}"
    payload: |
      {
        "channel": "#general",
        "text": "The price is now: {{ json(trigger.body).price }}"
      }

triggers:
  - id: http
    type: io.kestra.plugin.fs.http.Trigger
    uri: https://fakestoreapi.com/products/1
    responseCondition: "{{ json(response.body).price <= 110 }}"
    interval: PT30S
```

This flow checks every 30 seconds if the price of an item drops below a certain price point. Once it does, it will send a Slack alert and disable the trigger (_We no longer need to poll for the status, as the condition is satisfied!_)

It would be great to add a POST API endpoint `/api/v1/triggers/toggle/by-query` and a task with equivalent functionality e.g.:

```yaml
      - id: disable_schedule
        type: io.kestra.core.tasks.triggers.Toggle
        namespace: dev
        flowId: http
        triggerId: http
        enabled: false # true to reenable
```

Full flow example for the same scenario:

```yaml
id: http
namespace: dev

tasks:
  - id: slack
    type: io.kestra.plugin.notifications.slack.SlackIncomingWebhook
    url: "{{ secret('SLACK_WEBHOOK') }}"
    payload: |
      {
        "channel": "#general",
        "text": "The price is now: {{ json(trigger.body).price }}"
      }
  
  - id: if
    type: io.kestra.core.tasks.flows.If
    condition: "{{ json(trigger.body).price <= 110 }}"
    then:
      - id: disable_schedule
        type: io.kestra.core.tasks.triggers.Toggle
        namespace: dev
        flowId: http
        triggerId: http
        enabled: false # true to reenable

triggers:
  - id: http
    type: io.kestra.plugin.fs.http.Trigger
    uri: https://fakestoreapi.com/products/1
    responseCondition: "{{ json(response.body).price <= 110 }}"
    interval: PT30S
```

Once the condition is satisfied, the trigger is disabled.

**Comment by anna-geller** [comment]
this might be a quicker workaround once the state store gets added as a condition:

```yaml
id: http
namespace: dev

tasks:
  - id: slack
    type: io.kestra.plugin.notifications.slack.SlackIncomingWebhook
    url: "{{ secret('SLACK_WEBHOOK') }}"
    payload: |
      {
        "channel": "#general",
        "text": "The price is now: {{ json(trigger.body).price }}"
      }
  
  - id: if
    type: io.kestra.core.tasks.flows.If
    condition: "{{ json(trigger.body).price <= 110 }}"
    then:
      - id: setState
        type: io.kestra.core.tasks.states.Set
        data:
          'disabled': true

triggers:
  - id: http
    type: io.kestra.plugin.fs.http.Trigger
    uri: https://fakestoreapi.com/products/1
    responseCondition: "{{ json(response.body).price <= 110 }}"
    interval: PT30S
    - conditions:
      - type: io.kestra.core.models.conditions.types.state.Get
        condition: "{{ disabled != true }}"
```

**Comment by anna-geller** [comment]
alternative option (less favorable but solves the immediate pain): at first, only provide the functionality within this task:

```yaml
id: http
namespace: dev

tasks:
  - id: slack
    type: io.kestra.plugin.notifications.slack.SlackIncomingWebhook
    url: "{{ secret('SLACK_WEBHOOK') }}"
    payload: |
      {
        "channel": "#general",
        "text": "The price is now: {{ json(trigger.body).price }}"
      }

triggers:
  - id: http
    type: io.kestra.plugin.fs.http.Trigger
    uri: https://fakestoreapi.com/products/1
    responseCondition: "{{ json(response.body).price <= 110 }}"
    interval: PT30S
    stopPollingAfterSuccess: true # false by default -- name TBD
```

**Comment by anna-geller** [comment]
Next steps:
1. stopAfterSuccess boolean
2. Update trigger endpoint
3. UI change with toggle, unlock and Backfill Executions
4. Reevaluate after user feedback if we need the Toggle task and state store to store previous trigger conditions

**Comment by anna-geller** [comment]
to add more info from today's meeting with @brian-mulier-p and @tchiotludo: 
- we added an issue here https://github.com/kestra-io/kestra/issues/2964 for a generic `stopAfter` success property for all triggers
- we want to add the `Toggle` task allowing to disable a specific trigger (as shown below) via an API call (i.e. without changing the source code)
- we want to support more advanced use cases based on Flow trigger e.g. if a specific critical flow (or if any flow from a "prod" namespace) ends in a FAILED state, send a Slack alert + disable a trigger of that flow 
- for now, automatic reenabling of trigger is out of scope - user needs to reenable the trigger manually once they are ready

```yaml
      - id: disable_schedule
        type: io.kestra.core.tasks.triggers.Toggle
        namespace: dev
        flowId: http
        triggerId: http
        enabled: false # true to reenable
```
