### ISSUE TITLE
Correct conditions to use "{{ trigger.date }}" as the default value for the `date` property

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2719]
### Feature description

Currently the `date` property on conditions is required. Example:

```yaml
triggers:
  - id: schedule
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "0 11 * * 1"
    scheduleConditions:
      - type: io.kestra.core.models.conditions.types.DayWeekInMonthCondition
        date: "{{ trigger.date }}" # THIS IS CURRENTLY REQUIRED TO MAKE THE CONDITION WORK
        dayOfWeek: "MONDAY"
        dayInMonth: "FIRST"
```

This was done in the past because this property could have been used by both listeners and triggers. 

Given that listeners are deprecated, we should change this to use `date: "{{ trigger.date }}"` by default and make `date` an optional property.

It's not user-friendly to require the user to know such details about trigger variables when conditions currently can only be used with triggers.
