### ISSUE TITLE
Each Task need to many usage of jq

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#275]
```yaml
id: query
namespace: my.namespace
revision: 18
tasks:
  - id: get_num_service_from_liste_matrice
    type: org.kestra.task.gcp.bigquery.Query
    sql: |
      SELECT url, code
      FROM ....
      
    fetch: true
  - id: loop_on_liste_matrice_service
    type: org.kestra.core.tasks.flows.EachSequential

    tasks:
     - "..." 
           
    value: "{{jq outputs.get_num_magasin_from_liste_matrice.rows \".[].code\" }}"
```

jq is mandatory here, I would hope each can be simply : 
```yaml
    value: "{{  outputs.get_num_magasin_from_liste_matrice.rows  }}"
```
