### ISSUE TITLE
Using 'include' fails when injecting namespaceFiles

### ISSUE THREAD

**Issue by tdragon6** [kestra-io/kestra#2755]
### Explain the bug

When I wanted to inject the `test` directory in namespaceFiles, I used the `include` keyword according to the documentation, but the `test` directory was not injected successfully as expected.

```
id: test
namespace: test

tasks:
    - id: test
      type: io.kestra.plugin.scripts.python.Commands
      namespaceFiles:
        enabled: true
        include:
          - "test/**"
      commands:
        - ls -R /tmp/kestra-wd
```

<img width="1020" alt="image" src="https://github.com/kestra-io/kestra/assets/95691624/254d7cc5-0672-4f06-9d9f-a41a404e442d">

<img width="690" alt="image" src="https://github.com/kestra-io/kestra/assets/95691624/1032613e-be10-49e0-a028-0cc41d2ab3a0">

### Environment Information

- Kestra Version: v0.13.8
- Operating System and Java Version (if not using Kestra Docker image): docker

**Comment by anna-geller** [comment]
thanks so much for the issue! I can reproduce

**Comment by anna-geller** [comment]
temporary workaround: adding leading `/` in the `include` solves the issue

```yaml
id: test
namespace: dev

tasks:
    - id: test
      type: io.kestra.plugin.scripts.python.Commands
      namespaceFiles:
        enabled: true
        include:
          - "/test/**"
      commands:
        - ls test/ .
```
![image](https://github.com/kestra-io/kestra/assets/86264395/d3a844ef-3357-457a-9c6b-b9d49bb01f2d)
