### ISSUE TITLE
Extract data from Cassandra into a csv file, and load it into BigQuery

### ISSUE THREAD

**Issue by smantri-moveworks** [kestra-io/kestra#2771]
### Blueprint title

Extract data from Cassandra into a csv file, and load it into BigQuery

### Source code

```yaml
id: loadCassandraDataToBigquery
namespace: blueprint

tasks:
  # The data from https://gist.githubusercontent.com/Ben8t/f182c57f4f71f350a54c65501d30687e/raw/940654a8ef6010560a44ad4ff1d7b24c708ebad4/salary-data.csv has been pushed into Cassandra for this example. 
  - id: query_cassandra
    type: io.kestra.plugin.cassandra.Query
    session:
      endpoints:
        - hostname: localhost
          port: 9042
      localDatacenter: datacenter1
    cql: |
      SELECT salary_id, work_year, experience_level, employment_type, 
      job_title, salary, salary_currency, salary_in_usd, employee_residence,
      remote_ratio, company_location, company_size
      FROM test.salary
    store: true
  - id: write_to_csv
    type: io.kestra.plugin.serdes.csv.CsvWriter
    from: "{{ outputs.query_cassandra.uri }}" 
  - id: load_bigquery
    type: "io.kestra.plugin.gcp.bigquery.Load"
    from: "{{ outputs.write_to_csv.uri }}"
    destinationTable: "my_project.my_dataset.my_table"
    serviceAccount: "{{ secret('GCP_SERVICE_ACCOUNT_JSON') }}"
    projectId: "my_project"
    format: CSV
    csvOptions:
      fieldDelimiter: ","
      skipLeadingRows: 1
```

### About this blueprint

This flow extracts data from Cassandra table, writes it to a CSV file, and then loads the CSV data into BigQuery.

The data from the following public dataset is used in this example: https://gist.githubusercontent.com/Ben8t/f182c57f4f71f350a54c65501d30687e/raw/940654a8ef6010560a44ad4ff1d7b24c708ebad4/salary-data.csv

The GCP credentials are extracted from environment variable `GCP_SERVICE_ACCOUNT_JSON`. You need to create the table in BigQuery prior to executing this flow, or you can choose to create it via this flow by adding the schema to the BigQuery task.

### Tags (optional)

- Cassandra - BigQuery
