### ISSUE TITLE
Run query on Druid and process the resulting output using Pandas in a Python script

### ISSUE THREAD

**Issue by shrutimantri** [kestra-io/kestra#2788]
### Blueprint title

Run query on Druid and process the resulting output using Pandas in a Python script

### Source code

```yaml
id: loadDruidDataAndUseItInPythonScript
namespace: blueprint

tasks:
  - id: query_druid
    type: io.kestra.plugin.jdbc.druid.Query
    url: jdbc:avatica:remote:url=http://localhost:8888/druid/v2/sql/avatica/;transparent_reconnection=true
    sql: |
      SELECT __time as edit_time, channel, page, user, delta, added, deleted
      FROM wikipedia
    fetch: true
    store: true
  - id: write_to_csv
    type: io.kestra.plugin.serdes.csv.CsvWriter
    from: "{{ outputs.query_druid.uri }}" 
  - id: process_using_pandas
    type: io.kestra.plugin.scripts.python.Script
    beforeCommands:
      - pip install kestra pandas > /dev/null
    script: |
      import pandas as pd

      df = pd.read_csv("{{ outputs.write_to_csv.uri }}")
      df.head()
```

### About this blueprint

This flow will:
1.  Run a SQL query on Apache Druid.
2. Store the results from the query in a CSV file.
3. Read the CSV file and process it using Pandas.

Apache Druid can be setup locally by following the instructions mentioned on this page: https://druid.apache.org/docs/latest/tutorials/

### Tags (optional)

- Druid
- Pandas
