### ISSUE TITLE
[UI] Change trigger display to full trigger name instead of only first letter

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2789]
### Feature description

Since we've recently changed the Flow task to Subflow, there is now an overlap when displaying trigger info. Both a Schedule and Subflow task are displayed with the letter S, making it ambiguous: https://share.descript.com/view/BZoyxdRbv5N 

![image](https://github.com/kestra-io/kestra/assets/86264395/28601eac-29bd-447b-aac7-0fddb0884610)

Repro:

subflow:
```yaml
id: hello3
namespace: dev
tasks:
  - id: hello
    type: io.kestra.core.tasks.flows.Subflow
    flowId: hello2
    namespace: dev
```

scheduled:
```yaml
id: hello2
namespace: dev
tasks:
  - id: hello
    type: io.kestra.core.tasks.log.Log
    message: Kestra team wishes you a great day! 👋

triggers:
  - id: cron
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "* * * * *"
```

## Proposal
Display the full trigger name, not just the first letter

![image](https://github.com/kestra-io/kestra/assets/86264395/fafc535b-ff3f-4721-9ab5-d09d8d4c1a8c)
