### ISSUE TITLE
Add a Pebble filter to get values from JSON

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2807]
### Feature description

We currently have a `| keys` but no `| values` filter. Seems worth adding

**Comment by asdorsey** [comment]
According to #4032 this has been added, but as of the latest version of Kestra (currently v0.17.6), the filter is not present.

[kestra-execution-20240625135303-2V3DEMM0Qu5Ez91RG0jJRZ-1RVQ3G1eEBAlVnn4scYWjx.log](https://github.com/user-attachments/files/15975631/kestra-execution-20240625135303-2V3DEMM0Qu5Ez91RG0jJRZ-1RVQ3G1eEBAlVnn4scYWjx.log)

**Comment by anna-geller** [comment]
hey @asdorsey, this was indeed added but it wasn't released in the stable release yet. Try running kestra with the develop image `kestra/kestra:develop-full` and run this flow:

```yaml
id: expression
namespace: company.myteam
tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: "{{ {'this': 'foo', 'that': 'bar'} | values }}"
```

This should give you a list with foo and bar. 

The next stable release will be on 6th of August so best if you use develop image until then to use this expression.

Please ping me if you have any further questions
