### ISSUE TITLE
Using invalid Pebble syntax within a schedule trigger leads to excessive logging

### ISSUE THREAD

**Issue by yuri1969** [kestra-io/kestra#2811]
### Explain the bug

Using an invalid `VariableCondition` within a schedule trigger leads to a continuous stream of Pebble's `java.lang.RuntimeException`. This leads to excessive logging with related implications.

---

Saving the following flow invokes such exception featuring the `invalid operands for mathematical comparison [LESS_THAN]` message.

```yaml
id: hello-world-var-condition
namespace: company.team

triggers:
  - id: naive-schedule-condition
    type: io.kestra.core.models.triggers.types.Schedule
    description: Schedule featuring an invalid `VariableCondition`
    cron: "*/5 * * * * "
    scheduleConditions:
     - type: io.kestra.core.models.conditions.types.VariableCondition
       expression: "{{ trigger.date | date() < now() }}" # FIXME: invalid Pebble syntax leads to an extreme log spam

tasks:
  - id: hello
    type: io.kestra.core.tasks.log.Log
    message: Kestra team wishes you a great day! 👋
```

### Environment Information

- Kestra Version: v0.14.0-SNAPSHOT as of Jan 5th 2024
- Operating System and Java Version (if not using Kestra Docker image): Corretto 17
