### ISSUE TITLE
Allow description on input fields on flow

### ISSUE THREAD

**Issue by eregnier** [kestra-io/kestra#282]

**Comment by tchiotludo** [comment]
Easy one here :) 
```yaml
inputs:
  - name: "wrong one"
    description: "what is this ?"
```
and add the info on the ui execute tabs :)
