### ISSUE TITLE
Read the csv file and produce each line item into RabbitMQ

### ISSUE THREAD

**Issue by shrutimantri** [kestra-io/kestra#2822]
### Blueprint title

Read the csv file and produce each line item into RabbitMQ

### Source code

```yaml
id: read_orders
namespace: blueprint

tasks:
  - id: csv
    type: io.kestra.plugin.fs.http.Download
    uri: "https://raw.githubusercontent.com/kestra-io/datasets/main/csv/orders.csv"

  - id: csv_to_ion
    type: io.kestra.plugin.serdes.csv.CsvReader
    from: "{{ outputs.csv.uri }}"

  - id: each
    type: io.kestra.core.tasks.flows.ForEachItem
    items: "{{ outputs.csv_to_ion.uri }}"
    batch:
      rows: 1
    namespace: prod
    flowId: orders
    wait: true # wait for the subflow execution
    transmitFailed: true # fail the task run if the subflow execution fails
    inputs:
      order: "{{ taskrun.items }}"
```

```yaml
id: produce_to_rabbitmq
namespace: blueprint

inputs:
  - name: order
    type: STRING

tasks:
  - id: publish_to_rabbitmq
    type: "io.kestra.plugin.amqp.Publish"
    url: amqp://guest:guest@localhost:5672/
    exchange: test-queue
    from:
    -  data: "{{ read(inputs.order) }}"
```

### About this blueprint

This blueprint has two flows: `read_orders` and `produce_to_rabbitmq`.

`read_orders` reads the csv file from a URL, converts it into ion, and generates an execution of `produce_to_rabbitmq` flow for each line item of the ion file.

`produce_to_rabbitmq` publishes the record into an exchange of RabbitMQ.

Execute the `read_orders` flow in order to execute this blueprint. This flow execution will, in turn, automatically trigger the `produce_to_rabbitmq` flow for each record.

You can run RabbitMQ locally using Docker with the following command:
```bash
docker run -it --rm --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:latest
```

You can open the RabbitMQ UI locally on `http://localhost:15672/` and login using `guest`/`guest`.

### Tags (optional)

- RabbitMQ
- AMQP
