### ISSUE TITLE
Invalid retry configuration could fail the Worker

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#2835]
### Explain the bug

The following flow will fail the worker:

```yaml
id: flow_2
namespace: edmcode
tasks:
  - id: "bash"
    type: "io.kestra.core.tasks.scripts.Bash"
    inputFiles:
      script.sh: |
        #!/bin/bash
        n=$(date +"%M")
        if ((n % 2 == 0)); then
            echo "$n is even"
            ((result = 1 / 0))
        else
            echo "$n is odd"
        fi
    commands:
    - /bin/bash script.sh
    retry:
      type: constant
      interval: PT1M
      maxAttempt: 3
      maxDuration: PT1M
```

### Environment Information

- Kestra Version: 0.13
- Operating System and Java Version (if not using Kestra Docker image):
