### ISSUE TITLE
Global task defaults not keeping the letter case

### ISSUE THREAD

**Issue by yuri1969** [kestra-io/kestra#2844]
### Explain the bug

I've been wondering whether this issue should be attributed to Kestra or the upstream. Reporting here anyways.

---

The letter case of task defaults provided via the application config is not handled 1:1 for certain values. An example to illustrate the issue follows.

Kestra task defaults config defining an environment value `AB_VALUE` set:

```yaml
kestra:
  tasks:
    defaults:
      - type: "io.kestra.plugin.scripts.shell.Commands"
        values:
          env:
            AB_VALUE: "test"
```

However, printing the `env` from a `io.kestra.plugin.scripts.shell.Commands` task results in `aB_VALUE` being printed instead.

---

Here is a unit test [TaskGlobalDefaultConfigurationTest.patch](https://github.com/kestra-io/kestra/files/14521109/TaskGlobalDefaultConfigurationTest.patch)

### Environment Information

- Kestra Version: 0.14.0-SNAPSHOT as of Jan 12th 2024
- Operating System and Java Version (if not using Kestra Docker image):
