### ISSUE TITLE
Add a generic ExportFlows task

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2867]
## Problem

Some users want to extract all flows and all versions of specific flows. We may provide that as a dedicated task

## Proposed syntax

```yaml
id: export_flows
namespace: dev

tasks:
  - id: export
    type: io.kestra.core.tasks.namespace.ExportFlows # only fetched from the current namespace
    childNamespaces: true # true by default — whether to include flows from child namespaces
    pastRevisions: false # false by default — whether to include past revisions of each flow
    # outputs ION with columns: namespace, flowId, revision, content. 1 row per flow
```

## Workaround until then

```yaml
id: export_flows
namespace: dev

tasks:
  - id: get_zipfile
    type: io.kestra.plugin.fs.http.Download
    uri: http://host.docker.internal:28080/api/v1/flows/export/by-query?namespace=dev
    method: GET
    contentType: "application/json"

  - id: unzip
    type: io.kestra.plugin.compress.ArchiveDecompress
    algorithm: ZIP
    from: "{{outputs.get_zipfirele.uri}}"
```
