### ISSUE TITLE
Flow dependencies shows 0 dependencies even if there is some

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#2871]
### Explain the bug

For example, with the following two flows:

```yaml
id: subflow
namespace: company.team
tasks:
  - id: subflow
    type: io.kestra.core.tasks.flows.Subflow
    namespace: company.team
    flowId: hello-world
    wait: true
```

```yaml
id: hello-world
namespace: company.team
tasks:
  - id: hello
    type: io.kestra.core.tasks.log.Log
    message: Hello {{secret("hello")}}
  - id: fail
    type: io.kestra.core.tasks.executions.Fail
```

You see the following dependency view with 0 dependencies in the upper right corner even if there is some

![image](https://github.com/kestra-io/kestra/assets/1819009/d7356124-bd63-4112-ab27-615ffc3a5999)

### Environment Information

- Kestra Version:
- Operating System and Java Version (if not using Kestra Docker image):
