### ISSUE TITLE
Subflow logs sometimes aren't displayed / sometimes are doubled

### ISSUE THREAD

**Issue by brian-mulier-p** [kestra-io/kestra#2874]
### Explain the bug

![image](https://github.com/kestra-io/kestra/assets/37618489/01350cc8-2c6f-4e38-a541-e6726fc80bc5)
OSS preview tends to double the TaskRunDetails components while Cloud tends not to show any subflow logs until a reload has been done.

To reproduce the non-shown sublogs you have to open the Logs tab before the subflow taskrun has been created

### Environment Information

- Kestra Version:
- Operating System and Java Version (if not using Kestra Docker image):

**Comment by anna-geller** [comment]
> OSS preview tends to double the TaskRunDetails components while Cloud tends not to show any subflow logs until a reload has been done.

Interesting, do you have a theory on why this might be happening? afaik there are no differences in code between both versions

**Comment by brian-mulier-p** [comment]
I just put this here for reproducer purpose but the issue is probably due to some network latency which mandates an executionId to be in the outputs to show such subflow logs. It's probably a lack of watch somewhere. However idk why it can be doubled.

**Comment by Ben8t** [comment]
Not really able to replicate 🤔 

```yaml
id: pass_data_between_subflows
namespace: company.team

tasks:

  - id: wait
    type: io.kestra.plugin.scripts.shell.Commands
    taskRunner:
      type: io.kestra.plugin.core.runner.Process
    commands:
      - sleep 3
    
  - id: call_child_flow
    type: io.kestra.plugin.core.flow.Subflow
    namespace: company.team
    flowId: child_flow
    wait: true
  
  - id: log
    type: io.kestra.plugin.core.log.Log
    message: "{{ outputs.call_child_flow.outputs.data_from_child_flow }}"
```

```
id: child_flow
namespace: company.team
tasks:
  - id: return_data
    type: io.kestra.plugin.core.debug.Return
    format: this is a secret message returned from {{ flow.id }}
    
outputs:
  - id: data_from_child_flow
    type: STRING
    value: "{{ outputs.return_data.value }}" 
```

(Logs tab opened straight after execution)
![Image](https://github.com/user-attachments/assets/fbd07301-c104-406f-931c-17b00656e9bf)


@brian-mulier-p can you detail a bit more how to reproduce ?

**Comment by anna-geller** [comment]
@Ben8t the issue here is about logs and your subflow isn't logging anything - Return and Log is not the same. Try either using log task multiple times or use python task generating a bunch of logs in a child flow - might be a way to reproduce

**Comment by anna-geller** [comment]
@Ben8t I extended your reproducer to log more and the result is as follows:
1. On JDBC it works: https://share.descript.com/view/Kr0wFl2GdB3
2. On Elastic, it's indeed broken as @brian-mulier-p mentioned - see https://share.descript.com/view/jMBEaZfRy1j 


To reproduce, same parent flow but child flow producing logs + run it on Cloud or EE preview:

```yaml
id: child_flow
namespace: company.team
tasks:
  - id: log1
    type: io.kestra.plugin.core.log.Log
  - id: log2
    type: io.kestra.plugin.core.log.Log    
  - id: log3
    type: io.kestra.plugin.core.log.Log    
  - id: log4
    type: io.kestra.plugin.core.log.Log
  - id: log5
    type: io.kestra.plugin.core.log.Log
  - id: log6
    type: io.kestra.plugin.core.log.Log    
  - id: log7
    type: io.kestra.plugin.core.log.Log
  - id: log8
    type: io.kestra.plugin.core.log.Log
  - id: log9
    type: io.kestra.plugin.core.log.Log
  - id: return_data
    type: io.kestra.plugin.core.debug.Return
    format: this is a secret message returned from {{ flow.id }}
    
outputs:
  - id: data_from_child_flow
    type: STRING
    value: "{{ outputs.return_data.value }}" 

pluginDefaults:
  - forced: false
    type: io.kestra.plugin.core.log.Log
    values:
      message:
        - Kestra team wishes you a great day 
        - If you need some help, reach out via Slack    
        - Kestra team wishes you a great day 
        - If you need some help, reach out via Slack    
        - Kestra team wishes you a great day 
        - If you need some help, reach out via Slack    
        - Kestra team wishes you a great day 
        - If you need some help, reach out via Slack    
        - Kestra team wishes you a great day 
        - If you need some help, reach out via Slack    
        - Kestra team wishes you a great day 
```
