### ISSUE TITLE
Warn in the UI (e.g. when clicking on "Save") if a scheduled flow has inputs that have no defaults + no inputs set on the trigger

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2881]
## Use case
The following flow:

```yaml
id: missing_default
namespace: qa

inputs:
  - name: user
    type: STRING

tasks:
  - id: hello
    type: io.kestra.core.tasks.log.Log
    message: hey there {{ inputs.user }}! 👋

triggers:
  - id: every_minute
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "*/1 * * * *"
```

Will fail every minute because the user forgot to enter a default value: `Missing variable: 'inputs' on 'hey there {{ inputs.user }}!`

## Question
Can we provide a warning in the UI when an input is used somewhere within a scheduled flow even though it has no defaults + no inputs set on the schedule?

if not possible/easy to do, please close the issue

this is only to help users discover such issues as early as possible

**Comment by VTKop** [comment]
Hello! @anna-geller @MilosPaunovic, we have to pick up one more issue for the assignment as explained in issue #4490. Can I please be assigned to this issue as well?

**Comment by MilosPaunovic** [comment]
Is there any progress on this @VTKop?

**Comment by MilosPaunovic** [comment]
Hi @VTKop,

As there hasn't been any progress or updates on this, we'll unassign you for now. However, if you do open a PR, it will be reviewed, and you'll be reassigned if no one else handles it in the meantime.

Thanks for all the efforts so far! 🍀

**Comment by VTKop** [comment]
Hello! I'm sorry, I missed this message. We have made progress on the issue and will submit a pull request in the coming week!

**Comment by Pradumnasaraf** [comment]
QA done ✅. After this state, the user will not be able to save the flow. I hope that is expected. And the current updated flow:

```yaml
id: missing_default
namespace: qa

inputs:
  - id: a
    name: user
    type: STRING

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: hey there {{ inputs.user }}! 👋

triggers:
  - id: every_minute
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "*/1 * * * *"
```

<img width="1270" height="1080" alt="Image" src="https://github.com/user-attachments/assets/91536628-a053-4dd6-829a-54b1b4c97d8a" />
