### ISSUE TITLE
[UI] Grey out a disabled subflow

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2888]
### Feature description

![image](https://github.com/kestra-io/kestra/assets/86264395/8cd93bf3-d063-4c8e-a60d-e31922ac9cd8)

for now, it would only be greyed out if you set the Subflow task to disabled:

```yaml
id: parent
namespace: test
tasks:
  - id: child
    type: io.kestra.core.tasks.flows.Subflow
    namespace: test
    flowId: child
    wait: true
    disabled: true
```

We should do the same when the subflow itself is disabled

## Reproducer

To reproduce the issue, add the following two flows:

child:

```yaml
id: child
namespace: test
disabled: true
tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 
```

parent:

```yaml
id: parent
namespace: test
tasks:
  - id: child
    type: io.kestra.plugin.core.flow.Subflow
    namespace: test
    flowId: child
    wait: true
```
