### ISSUE TITLE
Feature Request: Implement IAM Roles for Service Accounts (IRSA) Support

### ISSUE THREAD

**Issue by dverzolla** [kestra-io/kestra#2914]
### Feature description

The current Helm configuration for Kestra requires minio-library for storage solutions. However, it has been identified that this implementation does not currently support for IRSA, which is an important feature for managing AWS permissions. The lack of IRSA support is limiting for environments that rely on fine-grained, role-based access control. I propose the integration of IRSA into Kestra's architecture to enhance security.

Just want to highlight that the `io.kestra.plugin.aws.s3.List` is compatible with AWS IRSA.
However, `io.kestra.plugin.fs.http.Download` does not currently support AWS IRSA.

I utilize `io.kestra.plugin.fs.http.Download` as a method to verify the correct configuration of Kestra's Internal Storage used with the Helm Package.

**Comment by fhussonnois** [comment]
Hi @dverzolla, we have added some enhancements on both the S3 plugin and S3 storage that bring AWS STS supports (already available on our 0.15.x bugfix releases). Basically, it is now possible to configure in place of traditional `accessKeyId`/`secretKeyId`:

```
# The Amazon Resource Name (ARN) of the role to assume. 
stsRoleArn: <>
# AWS STS External Id
stsRoleExternalId: <>
# AWS STS Session name.
stsRoleSessionName: <>
# AWS STS Session duration.
stsRoleSessionDuration
```

Then, we use the default AWS credentials provider chain that looks for credentials in this order:

- Environment Variables - AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY
- Web Identity Token credentials from system properties or environment variables
- Credential profiles file at the default location (~/.aws/credentials) shared by all AWS SDKs and the AWS CLI
- Credentials delivered through the Amazon EC2 container service if AWS_CONTAINER_CREDENTIALS_RELATIVE_URI" environment variable is set and security manager has permission to access the variable,
- Instance profile credentials delivered through the Amazon EC2 metadata service

Do these enhancements meet your needs?

Thank you!

**Comment by dverzolla** [comment]
Hey @fhussonnois, I will test at my side and will report here if any error. Thanks a lot.

**Comment by dverzolla** [comment]
Hi @fhussonnois, 

Just tested kestra (v16.6) with IRSA STS configuration. The pod is rightly configured:

```shell
kestra@kestra-standalone-77c5486989-8ztgw:/app$ env | grep AWS
AWS_DEFAULT_REGION=us-east-1
AWS_REGION=us-east-1
AWS_ROLE_ARN=arn:aws:iam::xxx:role/role_irsa_pagali_kestra
AWS_WEB_IDENTITY_TOKEN_FILE=/var/run/secrets/eks.amazonaws.com/serviceaccount/token  
```

I have installed `aws cli` into it and can list the s3 properly.

However, I don't know how to configure kestra. I've tried comment the `acessKey, secretKey` and that's not the way things work here. Any recommendation from your side how to test IRSA STS with kestra and minio client?

For testing, I'm using `io.kestra.plugin.fs.http.Download` plugin.

```yaml
      storage:
        type: minio
        minio:
          bucket: "devqa-pagali-kestra"
          port: "443"
          secure: "true"
          region: "us-east-1"
          endpoint: "s3.amazonaws.com"
          # accessKey: "xxx"
          # secretKey: "xxx"
```

**Comment by dverzolla** [comment]
Hi @fhussonnois, 

Just tested kestra (v16.6) with IRSA STS configuration. The pod is rightly configured:

```shell
kestra@kestra-standalone-77c5486989-8ztgw:/app$ env | grep AWS
AWS_DEFAULT_REGION=us-east-1
AWS_REGION=us-east-1
AWS_ROLE_ARN=arn:aws:iam::xxx:role/role_irsa_pagali_kestra
AWS_WEB_IDENTITY_TOKEN_FILE=/var/run/secrets/eks.amazonaws.com/serviceaccount/token  
```

I have installed `aws cli` into it and can list the s3 properly.

However, I don't know how to configure kestra. I've tried comment the `acessKey, secretKey` and that's not the way things work here. Any recommendation from your side how to test IRSA STS with kestra and minio client?

For testing, I'm using `io.kestra.plugin.fs.http.Download` plugin.

```yaml
      storage:
        type: minio
        minio:
          bucket: "xxx-kestra"
          port: "443"
          secure: "true"
          region: "us-east-1"
          endpoint: "s3.amazonaws.com"
          # accessKey: "xxx"
          # secretKey: "xxx"
```
