### ISSUE TITLE
Allow overriding the default subflow output behavior to avoid a breaking change

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2952]
### Feature description

With the configuration (as discussed):

```yaml
kestra:
  plugins:
    - type: io.kestra.core.tasks.flows.Subflow
      values:
        flowOutputs:
          enabled: true # default, but some customers can set it to false to keep the previous behavior
    - type: io.kestra.core.models.triggers
      values: 
        systemBackfills:
          enabled: true
```

We enable flow outputs to be accessed directly via `{{ outputs.flow_task_id.outputs.task_id }}` if set to true i.e. without having to define outputs on the Subflow task. 

if set to false, a user can still use the deprecated syntax that requires outputs to be specified on the Subflow (Flow) task:

```yaml

id: passDataBetweenSubflows
namespace: blueprint

tasks:
  - id: flow1
    type: io.kestra.core.tasks.flows.Subflow
    namespace: blueprint
    flowId: flow1
    wait: true
    outputs: # deprecated
      dataFromChildFlow: "{{outputs.returnData.value}}"
  
  - id: log
    type: io.kestra.core.tasks.log.Log
    message: "{{outputs.flow1.outputs.dataFromChildFlow}}"
```

**Comment by fhussonnois** [comment]
@anna-geller, currently it seems not possible to add the config:

```
kestra:
  plugins:
    - type: io.kestra.core.tasks.flows.Subflow
      values:
        flowOutputs:
          enabled: true
```

because, kestra already uses that config path for configuring maven repositories used to find plugins : 

```
kestra:
  plugins:
    repositories:
      central:
        url: https://repo.maven.apache.org/maven2/
```

So, eventually we can do this: 

```
kestra:
  plugins:
    defaults:
      - type: io.kestra.core.tasks.flows.Subflow
        values:
          flowOutputs:
            enabled: true
```

**Comment by anna-geller** [comment]
Good catch, sounds good 👍

**Comment by tchiotludo** [comment]
seems to be a good one:
```yaml
kestra:
  plugins:
    configurations:
```

**Comment by anna-geller** [comment]
@tchiotludo configurations could be interesting. However, we wanted to align this with task defaults:

```yaml
kestra:
  tasks:
    defaults:
    - type: io.kestra.core.tasks.log.Log
      values:
        level: ERROR
```

`defaults` seems preferable for consistency:
```yaml
kestra:
  plugins:
    defaults:
      - type: io.kestra.core.tasks.flows.Subflow
        values:
          flowOutputs:
            enabled: true
```

LMK if you have a strong opinion about the `configurations` wording
