### ISSUE TITLE
Deprecate scheduleConditions in favor of conditions

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2961]
### Feature description

can be done as part of Scheduler refactor

**Comment by anna-geller** [comment]
instead of:
```yaml
id: beverage_order
namespace: dev

inputs:
  - name: beverage
    type: STRING
    defaults: coffee

tasks:
  - id: order_beverage
    type: io.kestra.plugin.fs.http.Request
    uri: https://reqres.in/api/products
    method: POST
    contentType: application/json
    formData:
      beverage: "{{inputs.beverage}}"

  - id: set_labels
    type: io.kestra.core.tasks.executions.Labels
    labels:
      date: "{{trigger.date ?? execution.startDate | date('yyyy-MM-dd')}}"
      beverage: "{{inputs.beverage}}"

triggers:
  - id: workday
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "0 9 * * *"
    backfill:
      start: 2023-12-01T14:00:00Z
    scheduleConditions:
      - type: io.kestra.core.models.conditions.types.NotCondition
        conditions:
          - type: io.kestra.core.models.conditions.types.WeekendCondition

  - id: weekend
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "0 9 * * *" # every day at 9am
    backfill:
      start: 2023-12-01T14:00:00Z
    scheduleConditions:
      - type: io.kestra.core.models.conditions.types.WeekendCondition
    inputs:
      beverage: beer
```

change to this:

```yaml
id: beverage_order
namespace: dev

inputs:
  - name: beverage
    type: STRING
    defaults: coffee

tasks:
  - id: order_beverage
    type: io.kestra.plugin.fs.http.Request
    uri: https://reqres.in/api/products
    method: POST
    contentType: application/json
    formData:
      beverage: "{{inputs.beverage}}"

  - id: set_labels
    type: io.kestra.core.tasks.executions.Labels
    labels:
      date: "{{trigger.date ?? execution.startDate | date('yyyy-MM-dd')}}"
      beverage: "{{inputs.beverage}}"

triggers:
  - id: workday
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "0 9 * * *"
    backfill:
      start: 2023-12-01T14:00:00Z
    conditions:
      - type: io.kestra.core.models.conditions.types.NotCondition
        conditions:
          - type: io.kestra.core.models.conditions.types.WeekendCondition

  - id: weekend
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "0 9 * * *" # every day at 9am
    backfill:
      start: 2023-12-01T14:00:00Z
    conditions:
      - type: io.kestra.core.models.conditions.types.WeekendCondition
    inputs:
      beverage: beer
```
