### ISSUE TITLE
Add a new Runnable task — DynamicTask allowing to template the entire task definition even for non-dynamic properties

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2962]
Sometimes, we can't make specific properties dynamic because we want to offer type validation for integers, floats, booleans, or complex objects. This issue keeps coming more and more across various user requests (Databricks, Kubernetes PodCreate, and more).

The challenge is that: 
- _some_ users want to make almost every property dynamic. They care about making all inputs dynamic more than type safety. 
- for another type of user, that type safety and syntax/type validation while typing the declarative flow definition are important.

To offer a balanced approach, we may offer a new core task that allows users to fully dynamically generate a task definition. 

Name TBD, possible options:
- TemplatedTask
- DynamicTask

Given we disable [recursive rendering](https://kestra.io/docs/migrations/recursive-rendering#how-to-keep-the-previous-behavior) in the app globally, here it's also set to false by default.

```yaml
id: template
namespace: dev

inputs:
  - name: restartPolicy
    type: STRING

  - name: taskId
    type: STRING

tasks:
  - id: dynamic
    type: io.kestra.core.tasks.templating.TemplatedTask
    spec: |
      id: "{{ inputs.taskId }}"
      type: io.kestra.plugin.kubernetes.PodCreate
      namespace: default
      metadata:
        labels:
          my-label: my-value
      spec:
        containers:
        - name: unittest
          image: debian:stable-slim
          command: 
            - 'bash' 
            - '-c'
            - 'for i in {1..10}; do echo $i; sleep 0.1; done'
          {% if inputs.restartPolicy}
          restartPolicy: "{{ inputs.restartPolicy }}"
          {% endif %}
```

Note how, in this example, even task ID or task type can be dynamically generated at runtime based on user inputs, environment variables and more. 

In this example, the flow topology view will show the `DynamicTask` as a task type, while the execution topology will dynamically render that template into the right task type.

**Comment by kriko** [comment]
This would enhance the use of templated subflows, allowing to create subflows that use inputs to define it's behaviour.

**Comment by anna-geller** [comment]
TBD consider making it just one task as the implementation would be much easier/faster

**Comment by kriko** [comment]
Here's an example that could kind of work out of the box, dependent on the deserialization of YAML and type verification.
```
id: nested-parameters-from-inputs
namespace: test

inputs:
  - name: imagePullSecrets
    type: STRING
    # defaults: ""
    description: "Kubernetes GitLab Container Registry API access token"
    required: true

  # the following represents the object resources with nested structure as supported by Kestra
  - name: resources.limits.cpu
    type: STRING
    defaults: "1"
    required: true

  - name: resources.limits.memory
    type: STRING
    defaults: "1000Mi"
    required: true

  - name: resources.requests.cpu
    type: STRING
    required: false # note that this is optional and when not filled, it should be skipped in the definition (could be with a filter before passing the argument)

  - name: resources.requests.memory
    type: STRING
    required: false # note that this is optional and when not filled, it should be skipped in the definition (could be with a filter before passing the argument)

# using variables here to support other data types not supported by inputs, specifically lists
variables:
  env: # interpreted as an array of objects
    - name: VARIABLE_1
      value: "VALUE_1"
    - name: VARIABLE_2
      value: "VALUE_2"

  command: # interpreted as an array of strings
    - 'bash' 
    - '-c'
    - 'for i in {1..10}; do echo $i; sleep 0.1; done'

tasks:
  - id: pod
    type: "io.kestra.plugin.kubernetes.PodCreate"
    namespace: kestra
    spec:
      containers:
      - name: unittest
        image: debian:stable-slim
        command: {{ vars.command }}

        # env by definition is a list of strings
        # here we should be able to expand variables.env, which is also a list of strings
        env: {{ vars.env }} 

        # resources is an nested object
        # since in the input variable we have also defined a nested input "variable"
        # that follows the structure, we should be able to deserialize it just like YAML definition
        resources: {{ inputs.resources }}
        # here we should perhaps filter out any attributes with null values, when they are not defined in the inputs.

        # example of the original idea in this issue
        # optional, string based deserialization, maybe not the best way to handle this
        # this would require deserialization of a string to a nested YAML format
        imagePullSecrets: | 
          - name: "{{ inputs.imagePullSecrets }}"
```

All except for the last example should actually be similar to Kestra's best practice, however currently, this way it does not really work.

Even though the nested input and variables are correctly loaded as JSON objects/arrays, then the type verification and deserialization process happens in an order that prohibits this type of use.

The last option which is an example from Anna's post is one workaround to implement the end goal, but I'd actually prefer a more straight forward approach - not having to hard-code all the properties of the task definition, but pass them along as (almost) correctly typed objects.

This would allow manipulation of the objects between inputs, passing them to subflows and dynamically altering where necessary.

**Comment by kriko** [comment]
Perhaps a more concrete example could be the following, closely resembling our use-case.

### Templated subflow - a common flow to be called from specific implementations
```
id: templated-podcreate
namespace: test

inputs:
  - name: env
    type: JSON
    default: "[]"
    required: false
    description: "Optionally pass additional environment variables to PodCreate"

  - name: command
    type: JSON
    default: "[]"
    required: true
    description: "Pass specific commands to PodCreate"

  - name: imagePullSecrets
    type: STRING
    # defaults: ""
    description: "Kubernetes GitLab Container Registry API access token"
    required: true

  # the following represents the object resources with nested structure as supported by Kestra
  - name: resources.limits.cpu
    type: STRING
    defaults: "1"
    required: true

  - name: resources.limits.memory
    type: STRING
    defaults: "1000Mi"
    required: true

  - name: resources.requests.cpu
    type: STRING
    required: false # note that this is optional and when not filled, it should be skipped in the definition (could be with a filter before passing the argument)

  - name: resources.requests.memory
    type: STRING
    required: false # note that this is optional and when not filled, it should be skipped in the definition (could be with a filter before passing the argument)

variables:
  common_env: # here we define common environment variables that are added to the input env's
    - name: COMMON_1
      value: VALUE


tasks:
  - id: pod
    type: "io.kestra.plugin.kubernetes.PodCreate"
    namespace: kestra
    spec:
      containers:
      - name: unittest
        image: debian:stable-slim

        # k8s command by definition is a list of strings
        # here we should be able to expand variables.command, which is also a list of strings
        command: {{ vars.command }}

        # k8s env by definition is a list of objects (name, value as keys)
        # here we should be able to expand variables.common_env and add inputs.env, which is also a list of objects
        env: {{ vars.common_env | merge(inputs.env) }}

        # k8s resources is a complex nested object
        # since in the input variable "resources" we have also defined a nested input parameter
        # that follows the structure, we should be able to deserialize it just like YAML definition
        resources: {{ inputs.resources }}
        # here we should perhaps filter out any attributes with null values, when they are not defined in the inputs.

        # example of the original idea in this issue
        # optional, string based deserialization, maybe not the best way to handle this
        # this would require deserialization of a string to a nested YAML format
        # this could be done similarily as with env's example above
        imagePullSecrets: |
          - name: "common-secret" # predefined common pullsecret
          - name: "{{ inputs.imagePullSecrets }}"

```

### Specific flow that itself calls the templated subflow
```
id: run-podcreate
namespace: test

variables:
  env: # interpreted as an array of objects
    - name: VARIABLE_1
      value: "VALUE_1"
    - name: VARIABLE_2
      value: "VALUE_2"

  command: # interpreted as an array of strings
    - 'bash'
    - '-c'
    - 'for i in {1..10}; do echo $i; sleep 0.1; done'

tasks:
  - id: "load-table-kubernetes"
    type: "io.kestra.core.tasks.flows.Subflow"
    flowId: templated-podcreate
    namespace: test
    inputs: 
      env: {{ variables.env }} # passing additional envs to subflow that will be merged with common
      command: {{ variables.command }} # our specific command
      imagePullSecrets: "mypullsecret" # our specific pullsecret

      # resources.limits.cpu:       "1" # not passing, using default defined in subflow
      resources.limits.memory:    "128" # overwriting default defined in subflow
      resources.requests.cpu:     "0.5" # assigning a value to subflow optional input
      # resources.requests.memory:  ""  # not passing, not defined in subflow either, thus should not be passed to k8s
```

### Variable deserialization
Now as for variable interpolation or parsing goes, no preferences here, instead of:
```
        resources: {{ inputs.resources }}
```
it would be fine to use a filter
```
        resources: {{ inputs.resources | objectify }}
```
or a function, such as:
```
        resources: {{ json(inputs.resources) }}
```
or something like:
```
        resources: {{ deserialize(inputs.resources) }}
```

Thus type safety should remain, but it would be possible to pass complex parameters as values to task attributes like it is now possible with strings.
