### ISSUE TITLE
Add a generic `stopAfter` property allowing to disable any trigger after a SUCCESS (e.g. HTTP trigger condition) or FAILED (e.g. dependsOnPast behavior) execution

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2964]
### Feature description

Example syntax:

```yaml
id: hello-world
namespace: dev

tasks:
 - id: hello
   type: io.kestra.core.tasks.log.Log
   message: pausing a trigger after a success

triggers:
 - id: stopAfter
   type: io.kestra.core.models.triggers.types.Schedule
   cron: "0 9 * * *"
   stopAfter: # list of enum-type Execution states - can be set to any Execution states incl. multiple states as it's a list property, similarly to how ExecutionState condition on a Flow trigger accepts multiple possible states
     - SUCCESS # HTTP trigger as exist condition
     - FAILED # dependsOnPast for past Airflow users who want to disable the  executions until a broken pipeline gets fixed
```

**Important notes:**
- Ideally, disabling a trigger should generate a dedicated Audit log in EE e.g. "Trigger state action" with info which process/human disabled the trigger. For now, this doesn't seem feasible; see the comment below.
- This property is meant to be used primarily for a Schedule trigger + triggers with conditions incl. HTTP, JDBC, File Detection triggers; we will add it as a generic property for all triggers to stay flexible but just a note that for message queues, wehook or Flow triggers, this property is less relevant.
- We don't handle any automatic reenabling logic. After a trigger has been disabled, this generates a specific audit log and the user can then take some action based on it e.g. as part of https://github.com/kestra-io/kestra-ee/issues/809
