### ISSUE TITLE
Simplify the Debezium usage and documentation

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#2997]
### Feature description

Currently, Debezium triggers require a lot of setup.

Often, users expect that they can just point the plugin to their desired DB, and CDC will work out of the box to trigger the flow anytime there is a new row in the DB, like so:

```yaml
id: hello-world
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.scripts.shell.Commands
    commands:
      - cat "{{trigger.uris}}"

triggers:
  - id: listen-debezium
    type: io.kestra.plugin.debezium.postgres.Trigger
    hostname: host.docker.internal
    port: "5432"
    username: postgres
    password: "kestra"
    database: taxi
    pluginName: PGOUTPUT
    snapshotMode: INITIAL
    format: INLINE
    interval: PT3S
```
