### ISSUE TITLE
Add "in" and "not in" Pebble logical operator to check if some element exists within a list

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3023]
### Feature description

This will be very helpful in conditional branching and loop tasks that use some `condition`. It's very common to check if some element exists within a list or a dictionary and the contains can be sometimes awkward as it's inverse to what you would check. 

Example will clarify:

```yaml
id: hello-world
namespace: company.team
inputs:
  - id: myval
    type: STRING
    defaults: SUCCESS
tasks:
  - id: hello
    type: io.kestra.core.tasks.log.Log
    message: "{{ ['SUCCESS', 'FAILED'] contains inputs.myval }}" # this works 
    # message: "{{ inputs.myval in ['SUCCESS', 'FAILED'] }}" # but this is more natural
```

When checking for job status, you would check if the job status is within the list of exist statuses, rather than checking if the allowed statuses contains the current condition
