### ISSUE TITLE
Add a flowable core WhileLoop task

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3024]
## Context

Supporting while loops in an orchestrator can often be useful for workflows that require dynamic decision-making based on runtime conditions or external data sources. Use cases seen among our users:

1. **Blocking Calls for Job Status**: to manage long-running jobs or external processes, while loops periodically check the status of these jobs, effectively blocking the next task runs until the job is completed.
2. **Dynamic Conditions from External APIs**: workflows frequently depend on data or conditions retrieved from external APIs. While loops allow for polling these APIs until specific conditions are met, such as waiting for a dataset to be updated, a transaction to be confirmed, or a resource to become available.
3. **Scraping APIs and Webpages**: when extracting data from APIs or webpages, the total number of pages or data size might not be known upfront. While loops help fetch data until all pages have been scraped or a termination condition (like an empty response or a specific flag) is encountered.
4. **Waiting for Custom Events**: to synchronize with external events, such as file uploads, database triggers, or user actions, we typically recommend triggers as a solution. However, to give an alternative solution for custom events/systems, while loops provide a simple mechanism to wait for custom events before starting specific task runs.

🔥  This is a highly requested feature.

## Pagination

For pagination, the implementation will need to support the following common pagination methods:

- offset pagination e.g. `GET /items?limit=20&offset=100` e.g. the [Spotify API](https://developer.spotify.com/documentation/web-api/) uses offset pagination
    
  ```bash
  https://api.spotify.com/v1/artists/1vCWHaC5f2uS3yhpwWbIA6/albums?album_type=SINGLE&offset=20&limit=10
  ```
    
- basic keyset pagination e.g. `GET /items?limit=20` with pagination token e.g. used by [Twitter](https://developer.twitter.com/en/docs/twitter-api/pagination)
- advanced keyset pagination e.g. `GET /items?limit=20&after_id=20` → the update can increment the `after_id` by the limit value (here 20) for the next requests e.g.
    
    ```bash
    GET /items?limit=20&after_id=20
    GET /items?limit=20&after_id=40
    GET /items?limit=20&after_id=60
    GET /items?limit=20&after_id=80
    ```
    

### Properties

`initialLoopValues`

- Type: `object`
- Dynamic: ✔️
- Required: ✔️

> A map of arbitrary key-value pairs set as initial values and then updated in each loop iteration using the  `updatedLoopValues` property. The `updatedLoopValues` can update the initial value based on a task output or a custom pebble expression e.g. incrementing a page or a counter.
> 
> 
> The properties set within the `initialLoopValues` property serve as a starting point for the loop. You might want to start looping only from a specific `page` (*e.g. start fetching data from today*) and then keep incrementing that page until no pages are left or until a fewer number of pages than `per_page` are returned. When needed, the `initialLoopValues` property allows you to start fetching data at a specific `counter` or `page` value (*e.g. start at the last scraped page retrieved from a state store variable*) or a property value (*e.g. fetch data from an API starting from the `trigger.date`*).
> 
> Explicitly specifying the `initialLoopValues` and `updatedLoopValues` properties is equivalent to a while loop in any programming language with the benefit of being fully declarative.
> 
> For easy troubleshooting, Kestra logs (on a `DEBUG` level) the current `initialLoopValues` and `updatedLoopValues` values in each iteration. 
> 

`updatedLoopValues`

- Type: `object`
- Dynamic: ✔️
- Required: ✔️

> A map of arbitrary key-value pairs set as initial values in the `initialLoopValues` property and then updated in each loop iteration using this  `updatedLoopValues` property. See usage examples below to better understand the relation between the `initialLoopValues`, `updatedLoopValues` and `condition` properties.
> 

`condition`

- Type: `object`
- Dynamic: ✔️
- Required: ✔️

> An expression that must evaluate to `true` to continue the next iteration of the loop. You can think of it as the opposite of an exit condition:
- the `while` loop will start the next iteration if the condition is `true`
- the `while` loop stops immediately as soon as this condition is `false`.

This condition can take a variety of forms used in combination with the `initialLoopValues`/`updatedLoopValues` variables available in the execution context as task run values. For example, the `"{{taskrun.job_state != 'SUCCESS'}}"` condition will poll for the job status in each iteration and will exit the loop only once the desired status is reached. 

In the same way, you can iterate until you reach the last page in an API response, a specific HTTP status code, and more. You have a lot of flexibility to iterate based on the outputs of multiple tasks and `initialLoopValues`/`updatedLoopValues` variables. Check the examples below to see how you can build custom conditions.
> 

`loop`

- Type: `object`
- Dynamic: ✔️
- Required: ✔️

> The `loop` property is equivalent to the `retry` property. Having both `loop` and retries allow you to react to both successful and failed task run attempts. This property supports `constant`, `exponential` and a `random` interval between loop iterations in the same way you are familiar with from retries.
> 

## Examples

> This simple example initializes the `counter` variable and then increments it by 1 in each loop iteration, as specified on the `updatedLoopValues` property: `counter: "{{ taskrun.counter + 1 }}"`.  The condition `"{{ taskrun.counter < 10 }}"` ensures that we loop until the counter reaches the value 10. Value 10 serves as the exit condition. Based on this example, you can see that the `condition` serves a `while` and the `tasks` serve as `do` parts of a `do-while` loop in a programming language.
> 

```yaml
id: simple_counter
namespace: dev

tasks:
  - id: loop_until_10
    type: io.kestra.core.tasks.flows.WhileLoop
    initialLoopValues: 
      counter: 0
    condition: "{{ taskrun.counter < 10 }}"
    tasks: 
      - id: log_iteration
        type: io.kestra.core.tasks.log.Log
        message: "Current iteration: {{ taskrun.counter }}"
    updatedLoopValues:
      counter: "{{ taskrun.counter + 1 }}"
    loop: 
      type: constant 
      interval: PT1S
      maxDuration: PT30S 
```

> The following example demonstrates an asynchronous process checking for a condition. Here, we check for a job status and we loop until the job status reaches the `SUCCESS` state. The job can be any asynchronous process such as a Databricks, Spark, Airbyte, or AWS batch job.
> 

```yaml
id: check_for_job_status
namespace: dev

tasks:
  - id: databricks_job
    type: io.kestra.core.tasks.flows.WhileLoop
    initialLoopValues: 
      job_state: CREATED
    condition: "{{ taskrun.job_state != 'SUCCESS' }}"
    updatedLoopValues:
      job_state: "{{ outputs.poll.body | jq('.state.result_state') | first }}"
    tasks: 
      - id: poll
        type: io.kestra.plugin.fs.http.Request
        uri: https://reqres.in/api/job-status
        method: GET
        contentType: application/json
      - id: log_job_state 
        type: io.kestra.core.tasks.log.Log
        message: "Current iteration: {{ taskrun.job_state }}"
    loop: 
      type: constant # type: string
      interval: PT10S # type: Duration
      maxDuration: PT1H # type: Duration
      maxAttempt: 50 # type: int
```

> This example demonstrates offset pagination with `offset` and `limit` properties. Before the loop, we query the API for the total number of pages using the `Request` task. Then, the `WhileLoop` task will loop until the offset reaches the total count of items. Within the loop, we extract the data from an API using the `Download` task and the following task stores the output of the current loop iteration in S3. Note how we use an exponential loop type to avoid issues with rate limiting in subsequent API calls.
> 

```yaml
id: scrape_users_offset
namespace: dev

variables:
  base_url: https://reqres.in/api/users

tasks:
  - id: fetch_total
    type: io.kestra.plugin.fs.http.Request
    uri: "{{ vars.base_url }}"

  - id: while_loop
    type: io.kestra.core.tasks.flows.WhileLoop
    initialLoopValues: 
      offset: 0 
      limit: 100
    condition: "{{ taskrun.offset < json(outputs.fetch_total.body)['total_pages'] }}" 
    updatedLoopValues:
      offset: "{{ taskrun.offset + taskrun.limit }}"
    loop:
      type: exponential 
      maxAttempt: 500
      interval: PT1S
      maxInterval: PT10H
      delayFactor: 2
    tasks: 
      - id: fetch
        type: io.kestra.plugin.fs.http.Download 
        headers: 
          Authorization: "Bearer {{ secret('API_ACCESS_TOKEN') }}"
        uri: "{{ vars.base_url }}?offset={{ taskrun.offset }}&limit={{ taskrun.limit }}"
      - id: store_output_in_s3
        type: io.kestra.plugin.aws.s3.Upload
        from: "{{ outputs.fetch.uri }}"
        bucket: kestra-io
        region: "us-east-1"
        key: "data/{{ now() | date('yyyy_MM_dd')}}/{{taskrun.offset}}.json"


  - id: post_loop
    type: io.kestra.core.tasks.log.Log
    message: "This task can read data from all iterations from S3 and process or aggregate the results."
```

> This example shows API pagination with `page` and `per_page` (sometimes called header link paginator). We initialize the loop with the first page and define 20 items to fetch per page. Then, we loop until a page with less than 20 items, meaning no more new data is returned.
> 

```yaml
id: scrape_users
namespace: dev

variables:
  base_url: https://gorest.co.in/public/v2/users

tasks:
  - id: while_loop
    type: io.kestra.core.tasks.flows.WhileLoop
    initialLoopValues: 
      page: 1 
      per_page: 20
    condition: "{{ taskrun.per_page < 20 }}" 
    updatedLoopValues:
      page: "{{ taskrun.page + 1 }}"
      per_page: "{{ outputs.fetch.body.per_page }}" # this might be in the header
    tasks: 
      - id: fetch
        type: io.kestra.plugin.fs.http.Request 
        headers: 
          Authorization: "Bearer {{ secret('API_ACCESS_TOKEN') }}"
        uri: "{{ vars.base_url }}?page={{ taskrun.page }}&per_page={{ taskrun.per_page }}"
      - id: process_store_output
        type: io.kestra.core.tasks.debugs.Return
        format: "{{ outputs.fetch.body | jq('.[] | {id: .id, name: .name}') }}"
    loop: 
      type: constant # type: string
      interval: PT1S # type: Duration
      maxDuration: PT1H # type: Duration
      maxAttempt: 3600 # type: int

  - id: post_loop
    type: io.kestra.core.tasks.log.Log
    message: "This task can aggregate results from all loop iterations."
```

> This final example shows API pagination with `next_token` cursor (similar approach can be used with `hasMore`). Here, we loop over data fetched from the Twitter API which uses pagination token. The condition returns `true` if there is a `next_token` (next page). If true, we loop until all data is fetched (i.e. until the `next_token` is no longer returned = `null`). Within the `condition`, if the `jq` string returns `null`, the update expression will evaluate to empty `next_token`, ending the while loop. To avoid rate limits, this example uses a random `loop` interval and `retry` helps to restart the process when it fails.
> 

```yaml
id: twitter
namespace: dev

variables:
  base_url: "https://api.twitter.com/2/users/user_id/tweets?max_results=10&start_time={{ now() | dateAdd(-1, 'DAYS') }}"

tasks:
  - id: init
    type: io.kestra.plugin.fs.http.Request
    uri: "{{ render(vars.base_url) }}"
    headers: 
      Authorization: "Bearer {{ secret('API_ACCESS_TOKEN') }}"

  - id: if
    type: io.kestra.core.tasks.flows.If
    condition: | 
      {{ outputs.init.body | jq('.meta | has("next_token")') | first }}
    then:
      - id: while_loop
        type: io.kestra.core.tasks.flows.WhileLoop
        initialLoopValues: 
          pagination_token: |
            {{ outputs.init.body["meta"]["next_token"] }}
        condition: "{{ taskrun.pagination_token is not null }}"
        updatedLoopValues:
          pagination_token: "{{ outputs.fetch.body | jq('.meta.next_token') | first }}"
        tasks: 
          - id: fetch
            type: io.kestra.plugin.fs.http.Request
            headers: 
              Authorization: "Bearer {{ secret('API_ACCESS_TOKEN') }}"
            uri: "{{ render(vars.base_url) }}?pagination_token={{ taskrun.pagination_token }}"
        loop:
          type: random 
          maxAttempt: 500 # type: int
          minInterval: PT1S
          maxInterval: PT30S 
        retry:
          type: constant # type: string
          interval: PT5M # type: Duration
          maxDuration: PT10H # type: Duration
          maxAttempt: 500 # type: int
          warningOnRetry: true # type: boolean, default is false
  - id: post_loop
    type: io.kestra.core.tasks.log.Log
    message: "This task can aggregate results from all loop iterations."
```
