### ISSUE TITLE
Disabled a date calculate the wrong next date

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#3067]
- Before 
![image](https://github.com/kestra-io/kestra/assets/2064609/ce81b48d-b586-43ab-ab13-b591dedc9e66)
- I click on disabled 
- After
![image](https://github.com/kestra-io/kestra/assets/2064609/335fae96-dbda-48e4-9eb3-fa7ba41556db)

THe date is not relevant based on this schedule: 
```yaml
triggers: 
  - type: io.kestra.core.models.triggers.types.Schedule
    id: schedule
    cron: "0 0 * * *"
```
