### ISSUE TITLE
Removing a condition on a trigger didn't recompute the next execution date

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#3073]
### Describe the issue

For example with the following flow:

```
id: hello-schedule-condition-bug
namespace: company.team

triggers:
  - id: schedule
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "* * * * *"
    scheduleConditions:
     -  type: io.kestra.core.models.conditions.types.DayWeekInMonthCondition
        date: "{{ trigger.date }}"
        dayOfWeek: "MONDAY"
        dayInMonth: "FIRST"

tasks:
  - id: hello
    type: io.kestra.core.tasks.log.Log
    message: Schedule with condition
```

Due to the condition, the next evaluation date will be, for ex 2024-03-04 (as we are the 2024-02-15) and not in a minute.
Removing the condition didn't update the next evaluation date.

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):
