### ISSUE TITLE
Add a parameter to allow concurrent execution of any trigger (incl. schedule trigger)

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#311]
If a flow failed and it's not detected, the futur execution will be blocked forever until the user killed it.
For hourly based schedule, this don't make sense and we need to introduce an `allowConcurrent` for this case

**Comment by anna-geller** [comment]
bumping to P1 as it's required anyway + it would help with the Zombie situation reported by the community 🧟 

```yaml
triggers:
  - id: hourly
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "@hourly"
    allowConcurrent: true # false by default, set to true if you see Zombies 
# i.e. task runs stuck in a RUNNING state, preventing the start of next scheduled Executions
```
