### ISSUE TITLE
Passing JSON objects to child flows with ForEachItem fails with ION to JSON parsing

### ISSUE THREAD

**Issue by kriko** [kestra-io/kestra#3111]
### Describe the issue

Based on the documentation at [Example with the ForEachItem task reading file's content as a string](https://kestra.io/docs/faq/internal-storage#example-with-the-foreachitem-task-reading-files-content-as-a-string) and [The json() function](https://kestra.io/docs/faq/internal-storage#the-json-function) tried to implement the following, however it seems that parsing ION to JSON with the json() filter results in a failure of execution.

Best to describe with the following flows:

### Master flow: request
```
id: request
namespace: kestra.debug

tasks:
  - id: download
    type: "io.kestra.plugin.fs.http.Download"
    uri: "https://api.restful-api.dev/objects"
    contentType: "application/json"
    method: "GET"
    failOnEmptyResponse: true

  - id: json_to_ion
    type: io.kestra.plugin.serdes.json.JsonReader
    from: "{{ outputs.download.uri }}"
    newLine: false

  - id: for_each_item
    type: io.kestra.core.tasks.flows.ForEachItem
    items: "{{ outputs.json_to_ion.uri }}"
    batch:
      rows: 1
    namespace: kestra.debug
    flowId: item
    wait: true # wait for the subflow execution
    transmitFailed: true
    inputs:
      json: "{{ json(read(taskrun.items)) }}"
```

### Child flow: item
```
id: item
namespace: kestra.debug
inputs:
  - name: json
    type: JSON

tasks:
  - id: debug
    description: "Debug task run"
    type: "io.kestra.core.tasks.log.Log"
    level: INFO
    # disabled: true
    message: |
      id: {{ inputs.json.id }}
      name: {{ inputs.json.name }}
      data: {{ inputs.json.data }}
```      

Results in a failure in the main task:
```
io.pebbletemplates.pebble.error.PebbleException: Invalid json: Unexpected character ('i' (code 105)): was expecting double-quote to start field name
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 3] ({{ json(read(taskrun.items)) }}:1)
```

### Environment

- Kestra Version: 0.15.0-SNAPSHOT

**Comment by kriko** [comment]
There is a workaround to this issue, even though ForEachItem [documentation](https://kestra.io/plugins/core/tasks/flows/io.kestra.core.tasks.flows.foreachitem#items) suggests using the internal ION format, then the problem can be resolved by adding an additional step of transforming the ION stored data to JSON-L (json lines), which is also supported by ForEachItem task.

Fixed flow:
```
id: request
namespace: kestra.debug

tasks:
  - id: download
    type: "io.kestra.plugin.fs.http.Download"
    uri: "https://api.restful-api.dev/objects"
    contentType: "application/json"
    method: "GET"
    failOnEmptyResponse: true
    timeout: PT15S

  - id: json_to_ion
    type: io.kestra.plugin.serdes.json.JsonReader
    from: "{{ outputs.download.uri }}"
    newLine: false # regular json

  - id: ion_to_jsonl
    type: io.kestra.plugin.serdes.json.JsonWriter
    from: "{{ outputs.json_to_ion.uri }}"
    newLine: true # JSON-L

  - id: for_each_item
    type: io.kestra.core.tasks.flows.ForEachItem
    items: "{{ outputs.ion_to_jsonl.uri }}"
    batch:
      rows: 1
    namespace: kestra.debug
    flowId: item
    wait: true # wait for the subflow execution
    transmitFailed: true # fail the task run if the subflow execution fails
    inputs:
      json: "{{ json(read(taskrun.items)) }}"
```
