### ISSUE TITLE
[UI bug] Administration trigger set to disabled in the source code should not be toggle-able (the toggle should be greyed out/locked)

### ISSUE THREAD

**Issue by kriko** [kestra-io/kestra#3113]
### Issue description

I noticed that there seems to be no correlation between enabling or disabling triggers in the UI via Administration -> Triggers -> Enable/Disable toggle and the flow definition, where triggers can have a `disabled: true` flag which is also described in the [docs](https://kestra.io/docs/workflow-components/disabled#disabled-trigger).

Use case is to sync flows from Git, with triggers. Those triggers would be disabled by default (in the flow definition yaml), but perhaps can be turned on from the Administration Triggers UI.

Maybe it's still a new feature and being worked out. :)

Running on 0.15.0-SNAPSHOT

**Comment by anna-geller** [comment]
The toggle is independent of what is configured in the code. If you disable the trigger explicitly in your flow code, there is no other way to reenable it unless you change the source code again.

If `disabled: true` in the source code, you should not be able to toggle it on. It works on the Flow's Trigger page. However, you are right, this is indeed a bug on the Administration page: https://share.descript.com/view/ZUaJMVu2JJt

**Comment by anna-geller** [comment]
Repro: try any disabled trigger:

```yaml
id: hello-world
namespace: company.team
tasks:
  - id: hello
    type: io.kestra.core.tasks.log.Log
    message: Kestra team wishes you a great day! 👋

triggers:
  - id: schedule
    type: io.kestra.core.models.triggers.types.Schedule
    disabled: true
    cron: "* * * * *"
```

Then go to the Admin Trigger page and you will be able to toggle it, even though you shouldn't as it has no effect (explicitly disabled in code takes priority). 

![image](https://github.com/kestra-io/kestra/assets/86264395/9dd19a9a-2203-4449-bfeb-70146e42d6df)
