### ISSUE TITLE
FileTransform tasks didn't delete columns anymore

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#3121]
### Describe the issue

FileTransformTask should be able to delete a column by setting it to null.
This didn't work anymore (at least for Jython and Nashorn).

You can use the following flow with an input file in JSON with 2 columns colA and colB.

```yaml
id: testApi
namespace: test

inputs:
  - name: file
    type: FILE          # ColA - ColB

tasks:
 
  - id: readJsonFile
    type: io.kestra.plugin.serdes.json.JsonReader
    from: "{{ inputs.file }}"
    newLine: false

  - id: transformFile
    type: io.kestra.plugin.scripts.jython.FileTransform
    from: "{{ outputs.readJsonFile.uri }}"
    script: |
      logger.info('row: {}', row)
      row['colB'] = null
```

### Environment

- Kestra Version: 0.14
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by Skraye** [comment]
This is because in Python & JS you need to use respectively `del` and `delete`
Your example will remove the col if you use : 
```yaml
  - id: transformFile
    type: io.kestra.plugin.scripts.jython.FileTransform
    from: "{{ outputs.readJsonFile.uri }}"
    script: |
      logger.info('row: {}', row)
      del row['colB']
```
