### ISSUE TITLE
Docker runner doesn't correctly output values in Script tasks

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3127]
### Describe the issue

reproducer:

```yaml
id: test_send_param
namespace: tests
tasks:
  - id: task1
    type: io.kestra.plugin.scripts.python.Script
    runner: DOCKER
    beforeCommands:
      - pip install kestra
    script: |
      from kestra import Kestra

      print("1234\n\n")

      Kestra.outputs({'secrets': "test string"})
  - id: task2
    type: io.kestra.core.tasks.log.Log
    message: "{{ outputs.task1.vars.secrets }}"
```

### Environment

- Kestra Version: develop
