### ISSUE TITLE
Feature: provide core task for easily manipulating JSON structured data

### ISSUE THREAD

**Issue by fhussonnois** [kestra-io/kestra#3148]
## Motivation
Kestra relies on JSON structured data (e.g., Amazon ION) for exchanging outputs among flow tasks. Frequently, data processing entails applying transformations to JSON records (e.g., formatting, selection, aggregation).
Presently, achieving these transformations entails using the FileTransform task, which necessitates scripting in Javascript, Python, or Groovy. However, this approach isn't optimal for basic transformations and is not very user-friendly

## Proposition
Introduce a dedicated task in Kestra for JSON manipulation, leveraging solutions like [JSONata](https://try.jsonata.org/). This would empower users to perform data transformations efficiently using a powerful querying language, enhancing workflow simplicity and flexibility.

## Flow Example 

For example, using the following Flow:

```yaml
id: example
namespace: example
tasks:
- id: transformJson
  task: io.kestra.plugin.task.JSONataTransform
  # can be either a Kestra URI or a STRING
  from: {{ previousTask.outputs.uri }}
  expr: |
     {
        "order_id": order_id,
        "customer_name": customer_name,
        "total_price": $sum(items.(quantity * price_per_unit))
     }


```

with the given JSON input:

```json
{
  "order_id": "ABC123",
  "customer_name": "John Doe",
  "items": [
    {
      "product_id": "001",
      "name": "Apple",
      "quantity": 5,
      "price_per_unit": 0.5
    },
    {
      "product_id": "002",
      "name": "Banana",
      "quantity": 3,
      "price_per_unit": 0.3
    },
    {
      "product_id": "003",
      "name": "Orange",
      "quantity": 2,
      "price_per_unit": 0.4
    }
  ]
}
```

will output: 

```json
{
  "order_id": "ABC123",
  "customer_name": "John Doe",
  "total_price": 4.2
}
```
