### ISSUE TITLE
Add support for ENUM input TYPE

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3156]
Example syntax:

```yaml
id: input_values
namespace: dev

inputs:
  - id: enum
    type: ENUM
    defaults:
      - value1
      - value2
      - value3
```

Defaults are used to list available options to select from.

Use cases:
- allow external users to launch a flow only by leveraging predefined values from a list

Challenging extra part:
- we need to dynamically render those values in the dropdown

![image](https://github.com/kestra-io/kestra/assets/86264395/4c12758d-5c09-486b-9a2e-e053e920af71)
