### ISSUE TITLE
Validate whether rendering HTML in the logs is an intended behavior

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3159]
### Feature description

A security-conscious user was testing the limits of kestra and was trying to inject Javascript with simple methods. HTML was rendered in the UI when a taskrun's log produced HTML output. Is this intended or not?

 the <script> tag was htmlescaped, but other tags weren't

```yaml
id: html-injection-test
namespace: kestra.test
tasks:
  - id: hello
    type: io.kestra.core.tasks.log.Log
    message: |
      <h1>Heading1</h1>
      <img src="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==" onClick="javascript:alert('Running Javascript');" onLoad="javascript:alert('Running Javascript');" alt="Red dot" />
      <script>alert('Running Javascript')</script>
      <a href="javascript:alert('Running Javascript');" onClick="javascript:alert('Running Javascript');">Click me</a>
```

![image](https://github.com/kestra-io/kestra/assets/86264395/94bc8af9-701b-4ce4-9285-3c6c91cf046e)
