### ISSUE TITLE
Fix style of execution filter query labels

### ISSUE THREAD

**Issue by yuri1969** [kestra-io/kestra#3168]
Labels included in the execution filter query are not highlighted anymore - possibly related to `.el-tag--info`

## More context

how it should look like: grey labels and only highlight in purple when the color is found through search

![image](https://github.com/kestra-io/kestra/assets/86264395/57cc1bd6-86b6-4e44-b9a4-dea3631cfda6)

currently, we don't highlight the label:

![image](https://github.com/kestra-io/kestra/assets/86264395/f1595dfc-b0cb-400f-b336-b17c9553b167)

Video: https://share.descript.com/view/mtLYtzflBPJ

Reproducer:

```yaml
id: hello-labels
namespace: dev

description: before - this is 0.15 behavior

labels:
  category1: value1
  category2: value2
  category3: value3
  category4: value4
  category5: value5
  
tasks:
  - id: hello
    type: io.kestra.core.tasks.log.Log
    message: Kestra team wishes you a great day! 
```
