### ISSUE TITLE
Download from internal storage from ui are slow 

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#3179]
We have already see that download from file on the ui are slow (at least with GCS storage). 
The same download directly on google cloud storage console on GCP are full bandwidth, on kestra the download are at best to 200ko/s. 

We need to dig: 
- does every storage are affected or only google cloud storage 
- if all fixed the download 
- if not, fixed Google cloud storage

**Comment by loicmathieu** [comment]
I tested with the following flow using Cloud Storage locally, then tested preview-oss, preview-ee and our Cloud and in all cases the task execution and the download from the output is pretty quick (more than 10MB/s).

```yaml
id: gcs
namespace: com.kestra.lma
description: Save and Execute the flow

tasks:
  - id: gcs
    type: io.kestra.plugin.gcp.gcs.Download
    from: gs://kestra-public-examples/google-chrome-stable_current_amd64.deb
```

The issue may have been fixed by our latest library upgrades as I cannot reproduce it anymore.
