### ISSUE TITLE
The logs are not displayed in the right order

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3182]
### Feature description

![image](https://github.com/kestra-io/kestra/assets/86264395/d42ea126-a402-4176-b9fe-03578987d72f)

Reproducer:

```yaml
id: python-logs
namespace: dev.yann
tasks:
  - id: hello
    type: io.kestra.plugin.scripts.python.Script
    runner: PROCESS
    script: |
      import time
      for i in range(100):
        print(i)
        time.sleep(3) 
```
