### ISSUE TITLE
MultipleCondition seems to work only with SUCCESS flow

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#319]
If I wait for flows MultipleCondition, I expect the flow to be able to trigger even if the flow failed.

And need to have this condition: 

```yaml
          success:
            type: io.kestra.core.models.conditions.types.ExecutionStatusCondition
            in:
              - SUCCESS
```
It seems to be only working on `SUCCESS` status

Full example : 

```yaml
triggers:
  - id: multiple-listen-flow
    type: io.kestra.core.models.triggers.types.Flow
    conditions:
      - id: multiple
        type: io.kestra.core.models.conditions.types.MultipleCondition
        window: P1D
        windowAdvance: P0D
        conditions:
          success:
            type: io.kestra.core.models.conditions.types.ExecutionStatusCondition
            in:
              - SUCCESS
          flow-a:
            type: io.kestra.core.models.conditions.types.ExecutionFlowCondition
            namespace: io.kestra.tests
            flowId: trigger-multiplecondition-flow-a
          flow-b:
            type: io.kestra.core.models.conditions.types.ExecutionFlowCondition
            namespace: io.kestra.tests
            flowId: trigger-multiplecondition-flow-
```

**Comment by loicmathieu** [comment]
Just tried with the following 3 flows and it seems to works fine with FAILED flow:

```yaml
id: flow-multiple-trigger
namespace: myteam

triggers:
  - id: multiple-listen-flow
    type: io.kestra.core.models.triggers.types.Flow
    conditions:
      - id: multiple
        type: io.kestra.core.models.conditions.types.MultipleCondition
        window: P1D
        windowAdvance: P0D
        conditions:
          success:
            type: io.kestra.core.models.conditions.types.ExecutionStatusCondition
            in:
              - FAILED
          flow-a:
            type: io.kestra.core.models.conditions.types.ExecutionFlowCondition
            namespace: myteam
            flowId: flow-1
          flow-b:
            type: io.kestra.core.models.conditions.types.ExecutionFlowCondition
            namespace: myteam
            flowId: flow-2

tasks:
  - id: log
    type: io.kestra.core.tasks.log.Log
    message: "I'm using flow listeners"
```

```yaml
id: flow-1
namespace: myteam

tasks:
  - id: log
    type: io.kestra.core.tasks.log.Log
    message: "I'm flow 1"
  - id: fail
    type: io.kestra.core.tasks.executions.Fail
```

```yaml
id: flow-2
namespace: myteam

tasks:
  - id: log
    type: io.kestra.core.tasks.log.Log
    message: "I'm flow 2"
  - id: fail
    type: io.kestra.core.tasks.executions.Fail
```

Launchig flow-1 and flow-2 will trigger flow-multiple-trigger.
Worth noting that only one of the two flows needs to fail for the flow-multiple-trigger to be triggered as conditions are evaluated execution by execution.
