### ISSUE TITLE
Error logging is not clear when running an invalid script task.

### ISSUE THREAD

**Issue by JumaX** [kestra-io/kestra#3193]
### Describe the issue

**Task:**

Running a Python script task.

**Problem:**

When running a Python script task, if no code is present an error is thrown, however it fails to clearly identify what the issue is.

**Code:**

```
id: clickhouse_tfl_status_update
namespace: company.team
tasks:
  - id: get-tfl-status
    type: io.kestra.plugin.scripts.python.Script
    docker:
      image: python:slim
    beforeCommands:
    - pip install requests 
    warningOnStdErr: false
    script: |
```

**Error:**

![Screenshot 2024-03-01 at 10 39 59](https://github.com/kestra-io/kestra/assets/1376580/310a0d88-f322-4a86-b0be-3561086b1a6e)

### Environment

- Kestra Version: 0.150.0
- Operating System (OS/Docker/Kubernetes): Mac OS, Docker Desktop.
- Java Version (if you don't run kestra in Docker): N/A
