### ISSUE TITLE
For Each Item Partition inferior to number of items create more executions than expected

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#3207]
### Describe the issue

According to the documentation, the partition props should `Split a file into a fixed number of partitioned files.`. What about when this number is superior to the number of lines in the file?
It seems that the number of subflow executions is always that number whatever the file inputed.

Reproducer (inputs with a file of 3 lines will create 1000 executions):

```yaml
id: for-each-item
namespace: io.kestra.tests

inputs:
  - name: file
    type: FILE

tasks:
  - id: each
    type: io.kestra.core.tasks.flows.ForEachItem
    items: "{{ inputs.file }}"
    batch:
      partitions: 1000
    namespace: io.kestra.tests
    flowId: for-each-item-subflow
    wait: true
    transmitFailed: true
    inputs:
      items: "{{ taskrun.items }}"
```
![image](https://github.com/kestra-io/kestra/assets/46634684/6f584146-8e5d-4b89-9689-27e3ee9d6891)

![image](https://github.com/kestra-io/kestra/assets/46634684/bdb7d3c9-b61c-4c93-95d3-3f5593fbb6e6)

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):
