### ISSUE TITLE
ForEachItem should be considered as dependencies 

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#3210]
Standard `ForEachItem` 

```yaml 
id: for-each-item-no-wait
namespace: io.kestra.tests

inputs:
  - id: file
    type: FILE

tasks:
  - id: each
    type: io.kestra.core.tasks.flows.ForEachItem
    items: "{{ inputs.file }}"
    batch:
      rows: 4
    namespace: io.kestra.tests
    flowId: for-each-item-subflow
    wait: false
    transmitFailed: true
    inputs:
      items: "{{ taskrun.items }}"
```

is displaying any dependencies : 
![image](https://github.com/kestra-io/kestra/assets/2064609/62152bdf-e9db-4451-9c94-d34fe0411576)

It should be considered as a dependencies and don't break the dependencies graph
