### ISSUE TITLE
Some errors are not reported by validation while reported by the editor through JSON Schema

### ISSUE THREAD

**Issue by brian-mulier-p** [kestra-io/kestra#3220]
### Describe the issue

![image](https://github.com/kestra-io/kestra/assets/37618489/8fd81670-3560-4f4c-b60c-4f0d3adc9be9)
See above where an error is popped out (though it's seen as a warning in the editor) but our error tooltip is still green because the validation endpoint doesn't fail while the `commands` property is required. I guess it's because of an empty list generation upon an empty property is sent

### Environment

- Kestra Version: 0.16.0-SNAPSHOT
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by loicmathieu** [comment]
THis is a UI issue.
See for example:

```yaml
id: commandsValidation
namespace: company.team
tasks:
  - id: hello
    type: io.kestra.plugin.scripts.shell.Commands
    commands: []
```

The validate endpoint correctly send back a constraint violation:

```json
[
    {
        "flow": "commandsValidation",
        "namespace": "company.team",
        "index": 0,
        "constraints": "tasks[0].commands: must not be empty",
        "outdated": false,
        "deprecationPaths": [],
        "warnings": []
    }
]
```
