### ISSUE TITLE
Support BigQuery JSON columns 

### ISSUE THREAD

**Issue by zerobearing2** [kestra-io/kestra#3314]
### Feature description

We'd like to "select" JSON columns from BigQuery into the output. Currently when attempting a simple select that contains JSON column, we get the following error:
Example select:
```sql
select data from my_table limit 1
```

Error:
```
Invalid type 'JSON'
```

Example task:
```yaml
  - id: "query"
    type: "io.kestra.plugin.gcp.bigquery.Query"
    projectId: my-project
    serviceAccount: "{{secret('GCP_SERVICE_JSON')}}"
    fetchOne: true
    sql: |
      select data from my_table limit 1
```
