### ISSUE TITLE
Deprecate FlowNamespaceCondition and document `prefix` property in ExecutionNamespaceCondition

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3324]
### Feature description

Atm, we have 2 conditions that have almost identical functionality:
- https://kestra.io/plugins/core/conditions/io.kestra.core.models.conditions.types.executionnamespacecondition
- https://kestra.io/plugins/core/conditions/io.kestra.core.models.conditions.types.flownamespacecondition

But we tend to use + favor `ExecutionNamespaceCondition` (e.g. available in the [Alerting](https://kestra.io/docs/administrator-guide/monitoring#alerting) docs):

```yaml
id: failureAlertToSlack
namespace: prod.monitoring

tasks:
  - id: send
    type: io.kestra.plugin.notifications.slack.SlackExecution
    url: "{{ secret('SLACK_WEBHOOK') }}"
    channel: "#general"
    executionId: "{{trigger.executionId}}"

triggers:
  - id: listen
    type: io.kestra.core.models.triggers.types.Flow
    conditions:
      - type: io.kestra.core.models.conditions.types.ExecutionStatusCondition
        in:
          - FAILED
          - WARNING
      - type: io.kestra.core.models.conditions.types.ExecutionNamespaceCondition
        namespace: prod
        prefix: true # ❌  this is not a documented property, but one created as a shorthand for `comparison: PREFIX` 
```

![image](https://github.com/kestra-io/kestra/assets/86264395/780372bc-081d-47f1-bc5a-beba04804dfb)

`ExecutionNamespaceCondition` seems to be the right one for Flow Trigger use, and `FlowNamespaceCondition` seems to look at itself rather than the flow that triggers the execution: [https://github.com/kestra-io/kestra/blob/337f82fef92741eca4454890fcff50c714972770/[…]a/core/models/conditions/types/ExecutionNamespaceCondition.java](https://github.com/kestra-io/kestra/blob/337f82fef92741eca4454890fcff50c714972770/core/src/main/java/io/kestra/core/models/conditions/types/ExecutionNamespaceCondition.java#L55)

first early version: [https://github.com/kestra-io/kestra/blob/337f82fef92741eca4454890fcff50c714972770/[…]/java/io/kestra/core/models/conditions/types/FlowCondition.java](https://github.com/kestra-io/kestra/blob/337f82fef92741eca4454890fcff50c714972770/core/src/main/java/io/kestra/core/models/conditions/types/FlowCondition.java#L40) got deprecated to create ExecutionNamespaceCondition + the FlowCondition was renamed to FlowNamespaceCondition but currently there seems to be no more use case for it

plan:
- [ ] deprecate `FlowNamespaceCondition`
- [ ] document the `prefix` boolean property in the `ExecutionNamespaceCondition` to show that it's possible to use it (without removing the `comparison` property)
