### ISSUE TITLE
Updating a flow with a trigger seems to keep triggering upon an old revision

### ISSUE THREAD

**Issue by brian-mulier-p** [kestra-io/kestra#3329]
### Describe the issue

I used this flow
```
id: send_alert_when_price_drops48
namespace: dev

tasks:
  - id: slack
    type: io.kestra.core.tasks.log.Log
    message: "The price is now below the threshold: {{ json(trigger.encryptedBody).products[0].price }}"

triggers:
  - id: http48
    type: io.kestra.plugin.fs.http.Trigger
    uri: https://dummyjson.com/products/search?q=macbook-pro
    interval: PT1S
    encryptBody: true
    stopAfter:
      - SUCCESS
```

that I moved to this one
```
id: send_alert_when_price_drops48
namespace: dev

tasks:
  - id: slack
    type: io.kestra.core.tasks.log.Log
    message: "The price is now below the threshold: {{ trigger.encryptedBody }}"

triggers:
  - id: http48
    type: io.kestra.plugin.fs.http.Trigger
    uri: https://dummyjson.com/products/search?q=macbook-pro
    interval: PT1S
    encryptBody: true
    stopAfter:
      - SUCCESS
```

and it still fails about a JSON issue while the latest revision doesn't contain such function

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):
