### ISSUE TITLE
Add a new core task OutputValues as alternative to Return task

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3330]
### Issue description

It's a core task, commonly used to return data (not only for debugging)

**Comment by loicmathieu** [comment]
It may be better to create a new task with better naming and deprecate Return.

As the task is to add outputs to the execution naming it Outputs or Variables may be good.
```yaml
id: return
    type: io.kestra.core.tasks.outputs.OutputValue
    value: xyz
```

Or maybe the user may choose the name of the generated output, in this case better to offer a map like:

```yaml
id: return
    type: io.kestra.core.tasks.outputs.OutputValues
    outpus:
      output1: xyz
      output2: pwf
```

Maybe it's also better to replace Value(s) by Variable(s) this would be more discoverable
