### ISSUE TITLE
Return null if output cannot be retrieved instead of raising an error

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3363]
### Feature description

If flow outputs cannot be generated due to some tasks being skipped, it would be better to return null instead of failing the execution. 

Reproducer - running with `false` will work fine. Change to `true` and then the output cannot be generated due to the task being skipped:

```yaml
id: myflow
namespace: test

inputs:
  - id: check
    type: BOOLEAN
    defaults: false

tasks:
  - id: downstream
    type: io.kestra.core.tasks.flows.If
    condition: "{{ inputs.check == true }}"
    then:
      - id: stop
        type: io.kestra.core.tasks.log.Log
        message: stopping
    else:
      - id: continue
        type: io.kestra.plugin.scripts.shell.Script
        runner: PROCESS
        script: |
          echo 1 > res.jsonl 
        outputFiles:
          - "*.jsonl"

outputs:
  - id: results
    type: JSON
    value: "{{ outputs.continue.outputFiles }}"
```

this execution will fail with input `true`

**Comment by leonjza** [comment]
Thinking about this, I'd like to add two considerations.

1. Ideally, this behaviour is a configurable and not default. Having null could meaningfully indicate an erroneous condition in the logic that caused it, where the type system currently helps find such conditions.
2. In the case of an if/else, it would be great to have a final `outputs` populated by either conditionals code flow. Right now that is not as simple as defining multiple `continue` (from the example) steps as that is not allowed (as expected).

**Comment by kriko** [comment]
There is a workaround to this that I have been using.
By using Pebble  [null-coalescing](https://kestra.io/docs/concepts/expression/operator#null-coalescing) operator `??` you can substitute null values without throwing an exception. Here's an example where we substitute with null.
```
outputs:
  - id: results
    type: JSON
    value: "{{ outputs.continue.outputFiles ?? null }}"
```

**Comment by kriko** [comment]
Just as a follow up, but wanted to share how to apply this workaround in the case when there are multiple conditional tasks that may get executed and in the outputs, we have to determine which one to output.
```
id: myflow
namespace: test

inputs:
  - id: check
    type: BOOLEAN
    defaults: false

tasks:
  - id: downstream
    type: io.kestra.core.tasks.flows.If
    condition: "{{ inputs.check == true }}"
    then:
      - id: check_true
        type: io.kestra.plugin.scripts.shell.Script
        runner: PROCESS
        script: |
          echo "check was true" > res.jsonl 
        outputFiles:
          - "*.jsonl"
    else:
      - id: check_false
        type: io.kestra.plugin.scripts.shell.Script
        runner: PROCESS
        script: |
          echo "check was false" > res.jsonl 
        outputFiles:
          - "*.jsonl"

outputs:
  - id: results
    type: JSON
    value: "{{ outputs.check_true.outputFiles ?? outputs.check_false.outputFiles ?? null }}"
```
