### ISSUE TITLE
Add a warning in the UI when using a Flow trigger without specifying any conditions

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3395]
### Feature description

```yaml
triggers:
  - id: listenFlow
    type: io.kestra.core.models.triggers.types.Flow
```

Ideally, this should raise a warning: "This flow will be triggered for EVERY execution of EVERY flow on your instance. We recommend adding the conditions property to the Flow trigger."
