### ISSUE TITLE
Add a notification alert in case a task execution time exceeds a certain threshold

### ISSUE THREAD

**Issue by ar3thien** [kestra-io/kestra#3396]
### Feature description

I'm looking to have a workflow that execute remote ssh commands on certain machines. However for every ssh task, I need to be notified in case the command is taking more than a certain time. As an example: let's assume I run a remote ssh task to execute a calculation script on a remote server. The script is expected to finish in 2 hours. If the execution time crosses the 2 hours, but it's still running (slower than expected) and didn't fail, I need to be notified by email/discord/etc...

**Comment by anna-geller** [comment]
You can add a timeout on your SSH task — if the task will take longer than expected, it will be marked as failed:

```yaml
id: check_server_status
namespace: prod

tasks:
  - id: send_data
    type: "io.kestra.plugin.fs.ssh.Command"
    host: localhost
    port: "22"
    username: foo
    password: pass
    command: ls
    timeout: PT30M
```

Then, you can get alert for the failed task either using errors branch or using a Flow trigger as explained here: https://kestra.io/docs/administrator-guide/monitoring#alerting 

We plan to add SLA feature making that a bit easier to send alerts if some task or flow takes longer than you expect without failing the task https://github.com/kestra-io/kestra/issues/3350 

feel free to close the ticket if this solves the issue for you
