### ISSUE TITLE
[UI] Navigating between parent and child flow leads to a flaky screen

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3398]
### Describe the issue

see the video https://share.descript.com/view/6lnf9LpqSJ4

## Reproducer

child:

```yaml
id: child
namespace: myteam

inputs:
  - id: mydata
    type: STRING

tasks:
  - id: read_file
    type: io.kestra.plugin.scripts.shell.Commands
    runner: PROCESS
    commands:
      - cat "{{ inputs.order }}"

  - id: read_file_content
    type: io.kestra.core.tasks.log.Log
    message: "{{ read(inputs.order) }}"
```

parent:
```yaml
id: child
namespace: myteam

inputs:
  - id: mydata
    type: STRING

tasks:
  - id: read_file
    type: io.kestra.plugin.scripts.shell.Commands
    runner: PROCESS
    commands:
      - cat "{{ inputs.order }}"

  - id: read_file_content
    type: io.kestra.core.tasks.log.Log
    message: "{{ read(inputs.order) }}"
```

### Environment

- Kestra Version: develop
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):
