### ISSUE TITLE
KubernetesScriptRunner issues spotted during QA

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3400]
### Describe the issue

- [x]  outputs generated in a Python script are not captured as outputs in kestra yet — file outputs work, but variable outputs are printed to logs but not captured as outputs ([reproducer script](https://github.com/kestra-io/scripts/blob/main/generate_data/generate_orders.py)):
    
    ```yaml
    ::{"outputs": {"total_sum": 59980.539999999986, "average_order": 599.81}}::
    ```
    
- [x]  file outputs are not filtered out. When specified to capture CSV files, we get all files that were copied into a working directory, including all namespace files. Reproducer:
  ```yaml
  id: k8s_runner_qa
  namespace: myteam
  
  tasks:
    - id: generate_orders
      type: io.kestra.plugin.scripts.python.Commands
      namespaceFiles:
        enabled: true
      containerImage: ghcr.io/kestra-io/pydata:latest
      outputFiles:
        - "*.csv"
      commands:
        - python main.py
      scriptRunner:
        type: io.kestra.plugin.kubernetes.runner.KubernetesScriptRunner
        config:
          username: docker-desktop
          masterUrl: https://docker-for-desktop:6443
  ```
- [ ]  Some properties are marked as required even though they have default values. It seems they should be marked optional 

![image](https://github.com/kestra-io/kestra/assets/86264395/f7f2b31a-0e06-43a7-8119-494c5a8cadf0)

### Environment

- Kestra Version: develop
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):
