### ISSUE TITLE
[documentation error] ssh command page

### ISSUE THREAD

**Issue by johnsturgeon** [kestra-io/kestra#3431]
### Describe the issue

The example for the `ssh command` documentation is not syntactically correct.
https://kestra.io/plugins/plugin-fs/tasks/ssh/io.kestra.plugin.fs.ssh.command
```yaml
id: "command"
type: "io.kestra.plugin.fs.ssh.Command"
host: localhost
port: 22
username: foo
password: pass
command: ls
```
`command` should be 
```yaml
commands: 
  -ls
```

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):
