### ISSUE TITLE
Execution time of ForEachItem sub-flows

### ISSUE THREAD

**Issue by thomas-depierre-ntico** [kestra-io/kestra#3452]
### Describe the issue

Minor: For subflows launched by a ForEach Item, in the executions interface, the execution times of each sub-flow are cumulative. The ideal would be that the duration is only that of the execution

### Environment

- Kestra Version: 0.15.6
- Operating System (OS/Docker/Kubernetes): OS

**Comment by anna-geller** [comment]
hey, I cannot reproduce. As of Kestra 0.19.1, I see the correct execution of both parent and child flows here. Reproducer I used - see child flow in the description:

```yaml
id: orders_parallel
namespace: company.team
description: |
  id: orders
  namespace: company.team

  inputs:
    - id: order
      type: FILE

  tasks:
    - id: sleep
      type: io.kestra.plugin.scripts.shell.Commands
      commands:
        - sleep 5
      taskRunner:
        type: io.kestra.plugin.core.runner.Process

    - id: read_file_content
      type: io.kestra.plugin.core.log.Log
      message: "{{ read(inputs.order) }}"
    
    - id: ion_to_json
      type: io.kestra.plugin.serdes.json.IonToJson
      from: "{{ inputs.order }}"

    - id: jsonata
      type: io.kestra.plugin.transform.jsonata.TransformItems
      from: "{{ outputs.ion_to_json.uri }}"
      expression: |
        {
          "customer_name": customer_name,
          "total": total
        }

  outputs:
    - id: myoutput
      type: FILE
      value: "{{ outputs.jsonata.uri }}"

tasks:
  - id: extract
    type: io.kestra.plugin.jdbc.duckdb.Query
    sql: |
      INSTALL httpfs;
      LOAD httpfs;
      SELECT *
      FROM read_csv_auto('https://huggingface.co/datasets/kestra/datasets/raw/main/csv/orders.csv', header=True);
    store: true

  - id: for_each_item
    type: io.kestra.plugin.core.flow.ForEachItem
    items: "{{ outputs.extract.uri }}"
    batch:
      rows: 1
    namespace: company.team
    flowId: orders
    wait: true # wait for the subflow execution
    transmitFailed: true # fail the task run if the subflow execution fails
    inputs:
      order: "{{ taskrun.items }}"

  - id: ion_to_json
    type: io.kestra.plugin.serdes.json.IonToJson
    from: "{{ outputs.for_each_item_merge.subflowOutputs }}"
    newLine: false

  - id: merge
    type: io.kestra.plugin.core.storage.Concat
    files: "{{ read(outputs.ion_to_json.uri) | jq('map(.myoutput)') | flatten }}"
    separator: "\n"
```

![image](https://github.com/user-attachments/assets/052f20d8-fe31-4607-a78e-27ddc0bcf401)

If you still see the issue, please provide a reproducer so we can investigate
