### ISSUE TITLE
Rename the RUNNING to IN-PROGRESS within the ForEachItem execution visualisation to clarify it covers all states in progress rather than only RUNNING

### ISSUE THREAD

**Issue by thomas-depierre-ntico** [kestra-io/kestra#3453]
### Describe the issue

The subflows triggered by a ForEachItem are all indicated in "Running" even if they are in "Queued" (only for these 2 status)

### Environment

- Kestra Version: 0.15.6
- Operating System (OS/Docker/Kubernetes): OS

**Comment by anna-geller** [comment]
You're totally right! The `QUEUED` state is missing from the list of states. 
![image](https://github.com/user-attachments/assets/5e75d6e8-ec48-4837-9bce-5572450d0904)

Reproducer with a subflow within parent flow's description:

```yaml
id: orders_parallel
namespace: company.team
description: |
  id: orders
  namespace: company.team

  concurrency:
    behavior: QUEUE
    limit: 5

  inputs:
    - id: order
      type: FILE

  tasks:
    - id: sleep
      type: io.kestra.plugin.scripts.shell.Commands
      commands:
        - sleep 5
      taskRunner:
        type: io.kestra.plugin.core.runner.Process

    - id: read_file_content
      type: io.kestra.plugin.core.log.Log
      message: "{{ read(inputs.order) }}"
    
    - id: ion_to_json
      type: io.kestra.plugin.serdes.json.IonToJson
      from: "{{ inputs.order }}"

    - id: jsonata
      type: io.kestra.plugin.transform.jsonata.TransformItems
      from: "{{ outputs.ion_to_json.uri }}"
      expression: |
        {
          "customer_name": customer_name,
          "total": total
        }

  outputs:
    - id: myoutput
      type: FILE
      value: "{{ outputs.jsonata.uri }}"

tasks:
  - id: extract
    type: io.kestra.plugin.jdbc.duckdb.Query
    sql: |
      INSTALL httpfs;
      LOAD httpfs;
      SELECT *
      FROM read_csv_auto('https://huggingface.co/datasets/kestra/datasets/raw/main/csv/orders.csv', header=True);
    store: true

  - id: for_each_item
    type: io.kestra.plugin.core.flow.ForEachItem
    items: "{{ outputs.extract.uri }}"
    batch:
      rows: 1
    namespace: company.team
    flowId: orders
    wait: true # wait for the subflow execution
    transmitFailed: true # fail the task run if the subflow execution fails
    inputs:
      order: "{{ taskrun.items }}"

  - id: ion_to_json
    type: io.kestra.plugin.serdes.json.IonToJson
    from: "{{ outputs.for_each_item_merge.subflowOutputs }}"
    newLine: false

  - id: merge
    type: io.kestra.plugin.core.storage.Concat
    files: "{{ read(outputs.ion_to_json.uri) | jq('map(.myoutput)') | flatten }}"
    separator: "\n"
```

We discussed this internally, and the reason is that this is not the status of the EXECUTION per se but the status of the "view of the execution from the ForEachItem." -- we don't listen to all status changes of the sub-flow execution; we set it to RUNNING when we send it to the queue for execution.

**Next steps: we'll rename that RUNNING to IN-PROGRESS on the frontend-side to avoid confusion**
