### ISSUE TITLE
Using Edit Metadata feature results in removal of outputs from flow script

### ISSUE THREAD

**Issue by ssewell** [kestra-io/kestra#3468]
### Describe the issue

Open any flow that has an `outputs` section defined, select `Actions` -> `Edit Metadata`, then click the `Save` button in the modal panel that opens.

_Expected result_: No changes are made to the flow, since no changes to the Edit Metadata panel were made.
_Actual result_: The shown flow no longer has the `outputs` section defined as it has been removed from the script.

https://github.com/kestra-io/kestra/assets/2242776/688a3a07-ac64-4c64-8952-fe6f35b6199e

Here's the example script being used to demonstrate the behavior in the example above:
```yaml
id: get_github_version_example
namespace: home.lab
description: Obtains the latest release version given a repo
labels:
  area: subtask
inputs:
  - type: STRING
    id: user
    required: true
    description: Name of the user or organization on GitHub
  - type: STRING
    id: repo
    description: Name of the GitHub repository
    required: true
tasks:
  - id: get_latest_release
    type: io.kestra.plugin.fs.http.Request
    headers:
      Accept: application/json
      User-Agent: kestra
    uri: https://api.github.com/repos/{{inputs.user}}/{{inputs.repo}}/releases/latest
outputs: 
  - id: version
    type: STRING
    value: "{{outputs.get_latest_release.body | jq('.tag_name') | first}}"
```

### Environment

- Kestra Version: 0.5.10
- Operating System (OS/Docker/Kubernetes): Docker
- Java Version (if you don't run kestra in Docker):
