### ISSUE TITLE
Introduce functionality (dis)allowing to use the UI Editor to edit flows

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3496]
### Feature description

Some users expect flows to be not editable from the UI i.e. only allowing changes to be pushed to production namespace/tenant/instance via CI/CD, Git Sync system flow etc. 

To match the syntax of many other properties (e.g. `namespaceFiles`), we may add the `enabled` flag as follows:

```yaml
id: myflow
namespace: prod
editor:
  enabled: false
tasks:
...
```
