### ISSUE TITLE
Killing an execution in retrying step didn't set the retried task to killed

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#3511]
### Describe the issue

When an execution is in retrying state because a task failed and is configured retry, the execution is correctly set to killed but the task stay in retrying.

Example flow:

```yaml
id: restart
namespace: myteam

tasks:
  - id: fail
    type: io.kestra.core.tasks.executions.Fail
    retry:
      type: constant
      interval: PT10S
      maxAttempt: 3
```

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):
