### ISSUE TITLE
Flow level retry with CREATE_NEW_EXECUTION behavior let flowable tasks in running.

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#3512]
### Describe the issue

When there is a flow level retry with a behavior of CREATE_NEW_EXECUTION, the current execution ends up in `RETRIED` , personally I would ave let it in `FAILED` but it's open to discussion.

However if the failed task is inside a flowable, the flowable stay in RUNNING which is clearly a bug, it should at least be in RETRIED state.

Example flow:

```yaml
id: restart
namespace: myteam

inputs:
  - id: fail
    type: BOOLEAN
    defaults: false

retry:
  type: constant
  interval: PT1S
  maxAttempt: 3
  behavior: CREATE_NEW_EXECUTION

tasks:
  - id: if
    type: io.kestra.core.tasks.flows.If
    condition: "{{inputs.fail}}"
    then:
      - id: log-fail
        type: io.kestra.core.tasks.log.Log
        message: It will fail
      - id: fail
        type: io.kestra.core.tasks.executions.Fail
    else:
      - id: log-success
        type: io.kestra.core.tasks.log.Log
        message: It works
```

![image](https://github.com/kestra-io/kestra/assets/1819009/196f9c94-ba54-498b-a45f-a8aefba1ad52)

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):
