### ISSUE TITLE
FlowLabelsCondition didn't work

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#3517]
### Describe the issue

Try with the following two flows:

```yaml
id: flow-listener
namespace: myteam

tasks:
  - id: print_status
    type: io.kestra.core.tasks.log.Log
    message: hello World

triggers:
  - id: flow
    type: io.kestra.core.models.triggers.types.Flow
    conditions:
      - type: io.kestra.core.models.conditions.types.FlowNamespaceCondition
        namespace: myteam
      - type: io.kestra.core.models.conditions.types.FlowLabelsCondition
        labels:
          key: value
```

and

```yaml
id: hello-world
namespace: myteam

labels:
  key: value

tasks:
  - id: hellow-world
    type: io.kestra.core.tasks.log.Log
    message: Hello World
```

Executing the flow hellow-world didn't trigger the flow flow-listener.

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):
