### ISSUE TITLE
[Prefill feature] Inputs are not populated to the next execution for SECRET, BOOLEAN and MULTISELECT-type inputs 

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3523]
### Describe the issue

user feedback:

"when we want to replay an execution:
1. With a variable of type SECRET the encrypted value, the previously used value is set as input as an encypted value correctly, but during the execution, the input is not decrypted and can't be used
2. It doesn't prefill values for boolean inputs"

**Comment by anna-geller** [comment]
@smunteankestra can you try to reproduce please? if not, let's close

**Comment by smunteankestra** [comment]
having this flow error is returned: At my_secret_value: Invalid input for `my_secret_value`, Illegal base64 character 5f, but received `123`

```yaml
id: secret_issue_reproduction
namespace: company.team

inputs:
  - name: my_secret_value
    type: SECRET
    required: true

tasks:
  - id: log_secret_value
    type: io.kestra.plugin.core.log.Log
    message: "The secret value is: {{ inputs.my_secret_value }}"
```
