### ISSUE TITLE
SQS Trigger Executes Incorrect Flow Revisions

### ISSUE THREAD

**Issue by youssef-tec** [kestra-io/kestra#3533]
The AWS SQS Trigger in Kestra is exhibiting unexpected behavior where it executes previous revisions of a flow randomly instead of the latest version. The trigger configuration is as follows:

```yaml
triggers:
  - id: sqs
    type: io.kestra.plugin.aws.sqs.Trigger
    accessKeyId: "{{ secret('AWS_ACCESS_KEY_ID') }}"
    secretKeyId: "{{ secret('AWS_SECRET_ACCESS_KEY') }}"
    region: "eu-central-1"
    queueUrl: URL
    maxRecords: 1
```

While the trigger works as expected in terms of functionality, it inconsistently executes older revisions of the script rather than the latest one. This issue seems to occur particularly when there are multiple revisions of the flow.

**Steps to Reproduce:**
1. Set up a Kestra flow with the provided SQS trigger configuration.
2. Create multiple revisions of a flow.
3. trigger SQS event
4. Observe the trigger executing previous revisions randomly instead of the latest one.

**Additional Context:**
- The issue persists even when reducing the deployment to a single scheduler pod.
- Manually executing the flow using the execute button correctly utilizes the latest revision.
- Using a lambda function to process the event in SQS and trigger the Kestra job via webhook works as expected, indicating a potential issue with the SQS trigger.
- Upon inspecting the scheduler with `curl http://localhost:8081/scheduler`, an empty dictionary is returned, suggesting another underlying issue.

### Environment

- Kestra Version: 0.15.5
- Operating System (OS/Docker/Kubernetes): Kubernetes multi node
