### ISSUE TITLE
io.kestra.plugin.fs.smb.Uploads not working

### ISSUE THREAD

**Issue by roks531** [kestra-io/kestra#3538]
### Describe the issue

I have tried many different things to upload some postgresql dump files into my samba share using the `io.kestra.plugin.fs.smb.Uploads` plugin which should as per documentation upload multiple files into a specified samba share folder. First I thought the problem is with the outputFiles property from the shell plugin not read correctly or some wrong interpretation from my side, but if i try the exact same thing that is described in the documentation with a simple testing flow which downloads two csv files, I get the same error:

`2024-04-13 21:29:08.526
java.lang.ClassCastException: class java.util.ArrayList cannot be cast to class java.lang.String (java.util.ArrayList and java.lang.String are in module java.base of loader 'bootstrap')
	at io.kestra.plugin.fs.vfs.Uploads.run(Uploads.java:53)
	at io.kestra.plugin.fs.vfs.Uploads.run(Uploads.java:21)
	at io.kestra.core.runners.Worker$WorkerThread.run(Worker.java:769)`

The corresponding flow that i am using for testing and can easily be replicated doesn't work for me:

```
id: test
namespace: test

tasks:
  - id: download1
    type: "io.kestra.plugin.fs.http.Download"
    headers: 
      user-agent: "kestra-io"
    uri: "https://github.com/dsindy/kaggle-titanic/raw/master/data/test.csv"
  - id: download2
    type: "io.kestra.plugin.fs.http.Download"
    headers: 
      user-agent: "kestra-io"
    uri: "https://github.com/dsindy/kaggle-titanic/raw/master/data/test.csv"
  - id: upload
    type: io.kestra.plugin.fs.smb.Uploads
    from: 
      - "{{outputs.download1.uri}}"
      - "{{outputs.download2.uri}}"
    host: 192.168.1.100
    password: "{{secret('SAMBA_PASS')}}"
    to: "/Backups/test"
    username: user
```

I should mention that the `io.kestra.plugin.fs.smb.Upload` plugin that is uploading just one file is working as expected and that there is no problem on my smb side or other tasks involved.

### Environment

- Kestra Version: 0.16.0
- Operating System (OS/Docker/Kubernetes): Docker
- Java Version (if you don't run kestra in Docker): /
