### ISSUE TITLE
Retrieve the outputs of the triggering flow within the variables of the flow trigger

### ISSUE THREAD

**Issue by yvrng** [kestra-io/kestra#3559]
### Feature description

When using flow-based triggers, I would like to use values from the `outputs` of the triggering flow.

For example,

- **Flow A**, producing a value (available at `outputs.return.value` and `outputs.result`)
```yaml
id: flow-a
namespace: dev.yvrng
inputs:
  - id: message
    type: STRING
tasks:
  - id: return
    type: io.kestra.core.tasks.debugs.Return
    format: "{{ inputs.message }}"
outputs:
  - id: result
    type: STRING
    value: "{{ inputs.message }}"
```
- **Flow B**, consuming the result of **Flow A**
```yaml
id: flow-b
namespace: dev.yvrng
inputs:
  - id: message
    type: STRING
tasks:
  - id: log
    type: io.kestra.core.tasks.log.Log
    message: "{{ inputs.message }}"
triggers:
  - id: flow-a
    type: io.kestra.core.models.triggers.types.Flow
    conditions:
      - type: io.kestra.core.models.conditions.types.ExecutionNamespaceCondition
        namespace: dev.yvrng
    inputs:
      message: "{{ outputs.return.value }}"
```

Given this situation, instead of using `outputs.return.value`, I would like to use `outputs.result` in order to remove the `return` task (that remains a task that probably need to be executed on a worker)

**Comment by anna-geller** [comment]
Hey @yvrng, this would be a bit complex on the Flow trigger as flow-b only consumes trigger metadata `{{ trigger }}` rather than `outputs` (Subflow task has `outputs`, trigger doesn't have `outputs` but has `trigger` metadata). For passing data, it would be easier to use subflows: https://kestra.io/docs/workflow-components/outputs 

Is there some use case that would make it not viable for you to use subflows to pass data between flows?

**Comment by anna-geller** [comment]
For now, the flow trigger returns these values accessible on the `trigger` object:

```json
{
  "executionId": "4k1kM8K4VOWoxAO4J0lr2j",
  "state": "SUCCESS",
  "namespace": "dev",
  "flowId": "flow_a",
  "flowRevision": 2
}
```

It _might_ be technically feasible to support syntax like `{{ trigger.outputs.some_output_from_flow_a}}`. I'll ask @loicmathieu via Slack what he thinks

**Comment by yvrng** [comment]
Hi @anna-geller,

I'm not sure to understand what are trigger metadata. Currently, we can consume the `outputs` of tasks executed by a flow, but not its direct `outputs`. In my example, consuming `outputs.return.value` works well.

To answer your question: in our case, we use a lot subflows, but in this particular use-case it does not fit, because the output of `flow-a` can be consumed by more than one flow. Consumers are built dynamically, so it's easier to use flow triggers, this way the flows are decoupled.

**Comment by anna-geller** [comment]
this is what I meant by trigger metadata:

![image](https://github.com/kestra-io/kestra/assets/86264395/136d47e1-7a61-4fab-aa91-bc0b3dfa7a37)

**Comment by anna-geller** [comment]
> the output of flow-a can be consumed by more than one flow. Consumers are built dynamically, so it's easier to use flow triggers, this way the flows are decoupled.

Gotcha, this is a reasonable request, thanks for this context

**Comment by anna-geller** [comment]
If we add outputs to the Flow trigger to support fan-out based on data dependencies, we should add `ExecutionOutputCondition` to allow triggering a flow only if a specific output is generated 

```yaml
triggers:
  - id: flow_a
    type: io.kestra.core.models.triggers.types.Flow
    conditions:
      - type: io.kestra.core.models.conditions.types.ExecutionFlowCondition
        namespace: dev
        flowId: flow_a
      - type: io.kestra.core.models.conditions.types.ExecutionOutputCondition
        condition: "{{ trigger.outputs.result == 'hello world' }}"
```

(technically, it might be a 1:1 copy of VariableCondition but it would be clear that it's meant for outputs)
