### ISSUE TITLE
Dependencies tab shows 0 dependencies despite having one dependency

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3566]
### Describe the issue

![image](https://github.com/kestra-io/kestra/assets/86264395/5006b203-fca2-4ff6-8c5d-299a019238ac)

Repro (any flow with subflow):

```yaml
id: parent_flow
namespace: tutorial

tasks:
  - id: subflow
    type: io.kestra.core.tasks.flows.Subflow
    namespace: tutorial
    flowId: hello_world
```

and:

```yaml
id: hello_world
namespace: tutorial

inputs:
  - id: user
    type: STRING
    defaults: Rick Astley

tasks:
  - id: first_task
    type: io.kestra.core.tasks.outputs.OutputValues
    values:
      output1: thrilled
      output2: You

  - id: second_task
    type: io.kestra.plugin.scripts.shell.Commands
    commands:
      - sleep 0.1
      - echo '::{"outputs":{"returned_data":"mydata"}}::'

  - id: hello_world
    type: io.kestra.core.tasks.log.Log
    message: |
      Welcome to kestra, {{ inputs.user }}! 
      We are {{ outputs.first_task.values.output1}} to have {{ outputs.first_task.values.output1}} here!

triggers:
  - id: daily
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "0 9 * * *"
```

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):
