### ISSUE TITLE
Kestra on cloud that runs using Kafka is slower than Kestra on docker running locally

### ISSUE THREAD

**Issue by shrutimantri** [kestra-io/kestra#3572]
### Describe the issue

I am using the flow with ForEachItem task as shown on this page: https://kestra.io/plugins/core/tasks/flows/io.kestra.core.tasks.flows.foreachitem

Flow: orders_parallel
```
id: orders_parallel
namespace: prod

tasks:
  - id: extract
    type: io.kestra.plugin.jdbc.duckdb.Query
    sql: |
      INSTALL httpfs;
      LOAD httpfs;
      SELECT *
      FROM read_csv_auto('https://raw.githubusercontent.com/kestra-io/datasets/main/csv/orders.csv', header=True);
    store: true

  - id: each
    type: io.kestra.core.tasks.flows.ForEachItem
    items: "{{ outputs.extract.uri }}"
    batch:
      rows: 1
    namespace: prod
    flowId: orders
    wait: true # wait for the subflow execution
    transmitFailed: true # fail the task run if the subflow execution fails
    inputs:
      order: "{{ taskrun.items }}" # special variable that contains the items of the batch
```

Flow: orders
```
id: orders
namespace: prod

inputs:
  - id: order
    type: STRING

tasks:
  - id: read_file
    type: io.kestra.plugin.scripts.shell.Commands
    runner: PROCESS
    commands:
      - cat "{{ inputs.order }}"

  - id: read_file_content
    type: io.kestra.core.tasks.log.Log
    message: "{{ read(inputs.order) }}"
```

I execute `orders_parallel` flow in local, and on cloud. The execution in local takes ~8s, while the one in cloud takes ~2 min 15s. Here are the screenshots:
![Screenshot 2024-04-17 at 1 25 23 PM](https://github.com/kestra-io/kestra/assets/6594483/6bc7cce9-5fb8-4f61-bbd2-2b97fca063b0)
<img width="1718" alt="Screenshot 2024-04-17 at 1 25 14 PM" src="https://github.com/kestra-io/kestra/assets/6594483/6377abd0-f661-45a0-97e7-826b1ab913f8">

Flow link in cloud: https://us.kestra.cloud/ui/shruti/flows/edit/dev/orders_parallel

### Environment

- Kestra Version: 0.16.1
- Operating System (OS/Docker/Kubernetes): 2 setups: Docker in local, and Cloud
- Java Version (if you don't run kestra in Docker): N/A
