### ISSUE TITLE
Ensure that the Flow trigger cannot access outputs from the child execution

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3576]
### Feature description

Currently, you could implement the following pattern where the Flow trigger can access outputs from the child execution.

Flow A:

```yaml
id: flow_a
namespace: dev
tasks:
  - id: return
    type: io.kestra.core.tasks.outputs.OutputValues
    values:
      output1: myvalue

outputs:
  - id: result
    type: STRING
    value: "{{ outputs.return.values.output1 }}"
```

Flow B triggered after flow A should not be able to access outputs from flow A unless consuming it by trigger values: `{{ trigger.outputs.result }}`:

```yaml
id: flow_b
namespace: dev

inputs:
  - id: message
    type: STRING

tasks:
  - id: log
    type: io.kestra.core.tasks.log.Log
    message: "{{ inputs.message }}"

triggers:
  - id: flow_a
    type: io.kestra.core.models.triggers.types.Flow
    conditions:
      - type: io.kestra.core.models.conditions.types.ExecutionFlowCondition
        namespace: dev
        flowId: flow_a
    inputs:
      message: "{{ outputs.return.values.output1 }}" # it will fill the current message input of this flow_b 
# based on outputs of flow_a; however, this syntax will lead to confusion if this flow also has a task 
# called "return" = name collision. To access outputs from flow_a within executions of flow_b 
# you shpould use syntax: {{ trigger.outputs.result }}
```

This pattern is not desirable as it may lead to name conflicts and confusion. Imagine that flow_b has a task with ID "result" -- it's confusing whether "outputs.result" would take the result of flow_a or flow_b. 

We recommend disallowing such pattern and accessing outputs from the dependent (triggering flow) as e.g. here flow_a exclusively by using trigger values: `{{ trigger.outputs.flow_output_name }}`.
