### ISSUE TITLE
No longer interpreting envs in `variables`

### ISSUE THREAD

**Issue by mmlngl** [kestra-io/kestra#3589]
### Describe the issue

With an `instance_name` env set to `green-monster`, the following flow worked in `v0.13`:

```
id: hello-world
namespace: company.team

variables:
  instance_name: '{{ envs.instance_name }}'

tasks:
  - id: work
    type: io.kestra.core.tasks.log.Log
    message: "{{ envs.instance_name}} 👋"
    
  - id: notWork
    type: io.kestra.core.tasks.log.Log
    message: "{{ vars.instance_name}} 👋"
 ```
 
 Both tasks would output the same value: `green-monster` 👋.
 
 With `v0.16.1-full`, the outputs are different:
 - work: `green-monster` 👋
 - notWork: `{{ envs.instance_name }}` 👋
 
 It's like the variables are no longer being parsed.

### Environment

- Kestra Version: v0.16.1
- Operating System (OS/Docker/Kubernetes): Docker
- Java Version (if you don't run kestra in Docker): n/a

**Comment by mmlngl** [comment]
Just discovered [render](https://kestra.io/docs/concepts/expression/function#render).

This now works as expected:

```
id: hello-world
namespace: company.team

variables:
  instance_name: '{{ render(envs.instance_name) }}'

tasks:
  - id: work
    type: io.kestra.core.tasks.log.Log
    message: "{{ envs.instance_name}} 👋"
    
  - id: notWork
    type: io.kestra.core.tasks.log.Log
    message: "{{ render(vars.instance_name, recursive=true) }} 👋"
```
