### ISSUE TITLE
Add Slack `ResumeNotification` notification tasks — similar to `*Execution` tasks but intended to make it easy to resume a paused Execution

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3601]
Currently, kestra supports multiple `*Execution` tasks e.g. `SlackExecution`. Those plugins automatically generate a message such as:

![image](https://github.com/kestra-io/kestra/assets/86264395/7c20f141-3c83-45e4-b17a-65ac214ed189)

We want to add equivalent tasks for the `Pause/Resume` process. 

## Example ResumeNotification Task

Example for Slack:

```yaml
id: paused_test
namespace: company.team

tasks:
  - id: pause
    type: io.kestra.plugin.core.flow.Pause
    # rename deprecated "tasks" to tasksOnResume
    onPause: # Runnable task after Pause = the EXECUTION will be in PAUSED state, not in RESUMED
        type: io.kestra.plugin.notifications.slack.SlackExecution
        url: "{{ secret('SLACK_WEBHOOK') }}" # format: https://hooks.slack.com/services/xzy/xyz/xyz
        channel: "#general"
        executionId: "{{trigger.executionId}}"
        # LATER: link: "{{ appLink('appId') }}" # {{ executionLink() }}, by default: current execution -- follow up issue for the plugin team to enrich it with link allowing to use the App link
```

## Standard message template

The message template to resume execution might be:
    
```txt
Kestra workflow `{{ flow.id }}` is paused. 
Click [here](https:/host/ui/executions/{{ flow.namespace }}/{{ flow.id }}/{{ execution.id }}) 
to approve and resume the execution.
```

## Next steps

- PoC with one task `onPause`
- Plugin team to validate with Apps
