### ISSUE TITLE
Add a new API endpoint that will fetch and save Tutorial flows at server boot-time (unless disabled)

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3607]
### Feature description

To do:
- [ ] add an API endpoint that will fetch blueprints tagged as "Getting Started" and save them into the `tutorial` namespace at server boot-time
- [ ] add a configuration that allows disabling preloading example flows - see example syntax below

```yaml
kestra:
  tutorial-flows:
    enabled: true # true by default, can be set to false for production; OSS-only
```

Some extra notes:
- Those flows will be only preloaded in the OSS edition, EE users don't need it
- It's critical for the onboarding tour that those flows already exist in the instance. It's not enough to point to blueprints. The flows need to exist by default in a kestra instance so that new users trying the product for the first time see example workflows even if they skip the onboarding tour https://github.com/kestra-io/kestra/issues/3567
