### ISSUE TITLE
Disable warning on `volume-enabled` property and document how it should be configured

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3608]
### Feature description

For now, the right way is to use:

```yaml
kestra:
  plugins:
    configurations:
      - type: io.kestra.plugin.scripts.runner.docker.DockerTaskRunner
        values:
          volume-enabled: true
```

Before, it's used to be:
```yaml
kestra:
  tasks:
    scripts:
      docker:
        volume-enabled: true
```

Even if you configure it as shown in the first option, the script plugin will raise a warning:

![image](https://github.com/kestra-io/kestra/assets/86264395/d791df00-9b2b-4b17-8fd0-0d5538ab3b79)

We should find a way to suppress that warning and then fix the documentation:
https://kestra.io/docs/developer-guide/scripts/bind-mount (https://github.com/kestra-io/docs/issues/1255)
