### ISSUE TITLE
Add `dependsOn` to the SELECT/MULTISELECT-type inputs to allow one input to depend on the chosen value from another input

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3610]
Dynamic inputs help manage complex use cases where one input may depend on the chosen value from another input. 

## Example
Imagine that you want your end user to select the cloud provider first. Then, based on the chosen cloud provider, you want to show the services available for that cloud provider. The new `dependsOn` attribute in all SELECT-type inputs helps accomplish that:

```yaml
inputs:
  - id: cloud
    type: SELECT
    defaults: AWS
    values:
      - AWS
      - GCP
      - AZURE

  - id: services
    type: SELECT
    dependsOn:
     inputs: cloud
     condition: "{{ inputs.cloud == 'AWS' }}" # catch exception if not defined
    values: "{{ kv('SERVICE')[inputs.cloud] }}"

  - id: services2
    type: SELECT
    condition: "{{ inputs.cloud == 'AWS' }}" # catch exception if not defined
    values:
      - S3
      - EC2
      - RDS

  - id: services3
    type: SELECT
    condition: "{{ inputs.cloud == 'GCP' }}" # catch exception if not defined
    values:
      - GKE
      - GCS
      - BigQuery

  - id: services4
    type: SELECT
    condition: "{{ inputs.cloud == 'AZURE' }}" # catch exception if not defined
    values:
      - Azure VM
      - Azure Blob Storage
      - Azure SQL Database
```

The `services` input will be dynamically rendered based on the chosen cloud provider.

### **UI behavior**

When you execute this flow, the `services` input will be disabled until you select a value for the `cloud` input.

Once you select a value for the `cloud` input, the `services` input will show only the services available for the selected cloud provider. This dynamic rendering of dependent inputs allows you to select the correct service matching the previously chosen cloud provider.

### **Backend behavior**

Under the hood, Kestra will use a JSON schema with `oneOf` in the backend:

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "cloud": {
      "type": "string",
      "enum": ["AWS", "GCP", "AZURE"]
    },
    "services": {
      "type": "string",
      "enum": ["S3", "EC2", "RDS", "GKE", "GCS", "BigQuery", "Azure VM", "Azure Blob Storage", "Azure SQL Database"]
    }
  },
  "dependencies": {
    "cloud": {
      "oneOf": [
        {
          "properties": {
            "cloud": { "const": "AWS" },
            "services": {
              "type": "string",
              "enum": ["S3", "EC2", "RDS"]
            }
          }
        },
        {
          "properties": {
            "cloud": { "const": "GCP" },
            "services": {
              "type": "string",
              "enum": ["GKE", "GCS", "BigQuery"]
            }
          }
        },
        {
          "properties": {
            "cloud": { "const": "AZURE" },
            "services": {
              "type": "string",
              "enum": ["Azure VM", "Azure Blob Storage", "Azure SQL Database"]
            }
          }
        }
      ]
    }
  }
}

```

## Fetching SELECTed values from KV Store

Once we add the [KV Store](https://github.com/kestra-io/kestra/issues/3609), you can also fetch these values dynamically (related issue https://github.com/kestra-io/kestra/issues/283).

Imagine that the SELECT `values` are dynamic and need to be fetched from some external source like a database or file. You can create a flow that will regularly update the value for a given key. Then, you can reference that value by key in your dynamic input:

```yaml
id: myflow
namespace: dev
inputs:
  - id: cloud
    type: SELECT
    values: "{{ kv('CLOUD') }}" 

  - id: services
    type: SELECT
    dependsOn: cloud
    values: "{{ kv('SERVICES') }}"
```

Using keys:

```yaml
id: myflow
namespace: dev
inputs:
  - id: cloud
    type: SELECT
    values: "{{ kv('SERVICES') | keys }}" 

  - id: services
    type: SELECT
    dependsOn: cloud
    values: "{{ kv('SERVICES') }}"
```
