### ISSUE TITLE
Time Inputs not accepting the text string denoting time in defaults

### ISSUE THREAD

**Issue by shrutimantri** [kestra-io/kestra#3648]
### Describe the issue

As mentioned in the Inputs docs: https://kestra.io/docs/workflow-components/inputs, 
```
TIME: Must be a valid full [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) time without the timezone from a text string such as `10:15:30`.
```

So ideally, the below flow should have taken the default time as mentioned in the inputs defaults. But the flow does not accept this time in the inputs box on flow execution.

```yaml
id: inputs-flow-2
namespace: dev
description: Save and Execute the flow

labels:
  env: dev
  project: myproject

inputs:
  - id: time
    type: TIME
    defaults: "11:35:01"


tasks:
  - id: print_time
    type: io.kestra.core.tasks.log.Log
    message: time {{ inputs.time }}
```

![Screenshot 2024-04-30 at 7 28 42 PM](https://github.com/kestra-io/kestra/assets/6594483/e56a0fd4-ba21-4a39-b966-13d8ad8d74ec)

Ideally, the default value of "11:35:01" should have appeared in the time input box.

### Environment

- Kestra Version: 0.16.4
- Operating System (OS/Docker/Kubernetes): Docker
- Java Version (if you don't run kestra in Docker):
