### ISSUE TITLE
Duration inputs not accepting default value as expected

### ISSUE THREAD

**Issue by shrutimantri** [kestra-io/kestra#3649]
### Describe the issue

As mentioned in the Inputs docs: https://kestra.io/docs/workflow-components/inputs,

```
DURATION: Must be a valid full [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) duration from a text string such as `PT5M6S`.
```

So ideally, the below flow should have taken the default duration as mentioned in the inputs defaults. But the flow does not accept this duration in the inputs box on flow execution.

```yaml
id: inputs-flow-3
namespace: dev
description: Save and Execute the flow

labels:
  env: dev
  project: myproject

inputs:
  - id: duration
    type: DURATION
    defaults: "PT5M"


tasks:
  - id: duration
    type: io.kestra.core.tasks.log.Log
    message: duration {{ inputs.duration }}

  - id: sleep
    type: io.kestra.plugin.scripts.python.Commands
    commands:
      - sleep {{ inputs.duration }}
```

![Screenshot 2024-04-30 at 7 32 55 PM](https://github.com/kestra-io/kestra/assets/6594483/51a334af-356f-4afa-8d06-0db1fef1b6bc)

The input box for duration appears empty.

### Environment

- Kestra Version: 0.16.4
- Operating System (OS/Docker/Kubernetes): Docker
- Java Version (if you don't run kestra in Docker):
