### ISSUE TITLE
Flow On Windows OS shows warning message

### ISSUE THREAD

**Issue by paulgrainger85** [kestra-io/kestra#3658]
### Describe the issue

Executing a flow in Windows shows a warning message

```yaml
id: myflow
namespace: myteam
description: execute sample flow

labels:
  env: dev
  project: myproject

tasks:
  - id: send_data
    type: io.kestra.plugin.scripts.python.Commands
    interpreter: [pwsh, "-NoProfile", "-NonInteractive", "-Command"]
    runner: PROCESS
    commands:
      - python "C:\Users\paul\Documents\kestra\scripts\repex.py"

```

Warning message is as follows
```
Set-Variable: Missing an argument for parameter 'Exclude'. Specify a parameter of type 'System.String[]' and try again.
```

Note python script still executes as expected

### Environment

- Kestra Version: 0.16.5 (standalone)
- Operating System Windows 11
- Java Version 17
- Powershell version 7.4.2
