### ISSUE TITLE
dbt plugin won't output run_results.json when failed run

### ISSUE THREAD

**Issue by vitmrnavek** [kestra-io/kestra#3659]
### Describe the issue

I'm using plugin io.kestra.plugin.dbt.cli.DbtCLI in task and I'd like to have run_results.json in outputFiles so I can parse it later.

When task is successful, run_results are present in outputFiles. However, when task fails run_results are missing in outputFiles even when i use outputFiles variable, example below
```

      - id: dbtCore
        outputFiles: ["target/run_results.json"]
        type: io.kestra.plugin.dbt.cli.DbtCLI
        docker:
          image: ghcr.io/dbt-labs/dbt-snowflake:1.7.1
        commands:
          - dbt deps
          - dbt {{inputs.dbt_command}} --target {{inputs.dbt_target}} {% if inputs.selector is defined %} -s "{{ inputs.selector }}" {% endif %} {% if inputs.exclude is defined %} --exclude "{{ inputs.exclude }}" {% endif %}
```

### Environment

- Kestra Version: 0.16.1
- Operating System (OS/Docker/Kubernetes): Kubernetes
