### ISSUE TITLE
Add a proxy setting to git.Clone task allow cloning a repository in a Kuberntes Cluster behing a proxy

### ISSUE THREAD

**Issue by Trunken** [kestra-io/kestra#3663]
### Issue description

Hello,

currently we are trying to use Kestra as our orchestrator. We are running it inside a Kubernetes Cluster behind a proxy. Now we want to use the clone task but it does not work.

We already set up the env variables http_proxy, https_proxy and no_proxy in lowercase and uppercase but it did not help.

## Steps To Reproduce
See below

## Environment Information
Kestra Version: 0.14.0
Plugin version: 0.14.0
Operating System (OS / Docker / Kubernetes): Kubernetes
Example flow

## Code
```yaml  
id: test-clone
namespace: clone

tasks:
- id: "clone"
  type: "io.kestra.plugin.git.Clone"
  url: XXXX
  branch: main
  username: "{{ secret('GIT_USERNAME') }}"
  password: "{{ secret('GIT_ACCESSTOKEN') }}"
```

How do we have to configure the task so we can clone behind our proxy?

Thank you
