### ISSUE TITLE
Unprocessable Entity: Invalid entity: Invalid type: io.kestra.core.tasks.outputs.OutputValues

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3667]
### Describe the issue

![image](https://github.com/kestra-io/kestra/assets/86264395/1d128666-494a-4796-9a19-1ac35b409f62)

### Environment

- Kestra Version: develop-full
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by loicmathieu** [comment]
Work on preview OSS
![image](https://github.com/kestra-io/kestra/assets/1819009/992a0566-dc63-4b74-bcc8-d8983cd9f617)

```yaml
id: outputs_flow
namespace: myteam

tasks:
  - id: output_values
    type: io.kestra.core.tasks.outputs.OutputValues
    values:
      taskrun_data: "{{ task.id }} > {{ taskrun.startDate }}"
      execution_data: "{{ flow.id }} > {{ execution.startDate }}"

  - id: log_values
    type: io.kestra.core.tasks.log.Log
    message: |
      Got the following outputs from the previous task:
      {{ outputs.output_values.values.taskrun_data }}
      {{ outputs.output_values.values.execution_data }}
```
