### ISSUE TITLE
[Regression] Defaults seem to be ignored on inputs

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3668]
### Describe the issue

![image](https://github.com/kestra-io/kestra/assets/86264395/5fc1077f-1f1c-4ab4-8c48-529ab1d28275)

![image](https://github.com/kestra-io/kestra/assets/86264395/0edf6a94-348b-4306-a1fe-820087e3db83)

Repro: take any flow with inputs with defaults e.g.:

```yaml
id: hello_world
namespace: tutorial

inputs:
  - id: user
    type: STRING
    defaults: Rick Astley

tasks:
  - id: first_task
    type: io.kestra.core.tasks.outputs.OutputValues
    values:
      output1: thrilled
      output2: You

  - id: second_task
    type: io.kestra.plugin.scripts.shell.Commands
    commands:
      - sleep 0.42
      - echo '::{"outputs":{"returned_data":"mydata"}}::'

  - id: hello_world
    type: io.kestra.core.tasks.log.Log
    message: |
      Welcome to Kestra, {{ inputs.user }}! 
      We are {{ outputs.first_task.values.output1}} to have {{ outputs.first_task.values.output2}} here!
```

### Environment

- Kestra Version: develop-full
