### ISSUE TITLE
WorkingDirectory has outputFiles property but it doesn't actually capture outputFiles

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3693]
### Describe the issue

Reproducer: the dbt task should capture all files from the cloned Git directory as `outputFiles` property:

![image](https://github.com/kestra-io/kestra/assets/86264395/f152c77d-7279-498f-82ee-a7ac0f9add4e)

```yaml
id: git
namespace: tutorial

tasks:
  - id: dbt
    type: io.kestra.core.tasks.flows.WorkingDirectory
    outputFiles:
      - "**/*"
    tasks:
      - id: clone
        type: io.kestra.plugin.git.Clone
        url: https://github.com/kestra-io/dbt-example
        branch: main

  - id: list
    type: io.kestra.plugin.scripts.shell.Commands
    inputFiles: "{{ outputs.dbt.outputFiles }}"
    commands:
      - ls -R .
```

The log shows the files were captured:

![image](https://github.com/kestra-io/kestra/assets/86264395/5a7861e3-c1c4-4732-b7e5-b9dcadfc5fa0)

However, it captures nothing in outputs:

![image](https://github.com/kestra-io/kestra/assets/86264395/54f0bb09-82e6-470e-b9be-30c839475659)

![image](https://github.com/kestra-io/kestra/assets/86264395/6303260f-e0b3-4348-b61f-4ce1105e0c2e)

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):
