### ISSUE TITLE
Logs/Outputs are not consistently showing or being added to Outputs

### ISSUE THREAD

**Issue by japerry911** [kestra-io/kestra#3695]
### Describe the issue

I run a YAML flow with 4 tasks in a parallel GCP Cloud Batch Task Runner. These 4 tasks are Sub Flows. It prints logs/adds the single output about 70-80% of the time in Kestra, and 100% in GCP Logs, which makes me think it's something with Kestra core.

For output I run:
```
Kestra.outputs({"uuid_str": uuid_str})
```

For Example of Logs showing partially, but skipping output example:
![image](https://github.com/kestra-io/kestra/assets/21957238/cdc5478d-26de-49e8-9c23-b7f7ca410d21)

In this image, it shows my initial PRINT statements showing, but when it gets to `Kestra.outputs({"uuid_str": "..."})`, it does not show in this job, but showed in other jobs.

I checked the Docker Compose logs, and saw nothing, and GCP logs don't show a fail or anything.

Let me know if you need more context/details, happy to provide.

Thank you!

### Environment

- Kestra Version: v0.16.0
- Operating System (OS/Docker/Kubernetes): Docker/GCP Compute Engine VM
- Java Version (if you don't run kestra in Docker): n/a

**Comment by anna-geller** [comment]
Hi Jack, can you share the redacted version of the main flow and all subflows so we can try to reproduce? Thanks in advance

**Comment by japerry911** [comment]
```yaml
id: googleAds
namespace: prod
description: This flow fetches and lands data from Google Ads to BigQuery.

inputs:
  - id: start_date
    type: STRING
    required: true
    description: The start date to fetch data from Google Ads.
    validator: ^\d{4}-\d{2}-\d{2}$

  - id: end_date
    type: STRING
    required: true
    description: The end date to fetch data from Google Ads.
    validator: ^\d{4}-\d{2}-\d{2}$

tasks:
  - id: parallel
    type: io.kestra.core.tasks.flows.Parallel
    tasks:
      - id: fetch_customers_info
        type: io.kestra.core.tasks.flows.Subflow
        namespace: prod
        flowId: fetchAndLoadBqFromGcs
        wait: true
        inputs:
          fetch_command: src/integrations/google_ads/jobs/fetch_customers_info.py
          gcs_path_prefix: gs://REDACTED/google_ads/customers_info
          destination_table: REDACTED.landing_google_ads.customers_info
      - id: fetch_campaigns_info
        type: io.kestra.core.tasks.flows.Subflow
        namespace: prod
        flowId: fetchAndLoadBqFromGcs
        wait: true
        inputs:
          fetch_command: src/integrations/google_ads/jobs/fetch_campaigns_info.py
          gcs_path_prefix: gs://REDACTED/google_ads/campaigns_info
          destination_table: REDACTED.landing_google_ads.campaigns_info
      - id: fetch_campaigns_metrics
        type: io.kestra.core.tasks.flows.Subflow
        namespace: prod
        flowId: fetchAndLoadBqFromGcs
        wait: true
        inputs:
          fetch_command: src/integrations/google_ads/jobs/fetch_campaigns_metrics.py --start_date {{ inputs.start_date }} --end_date {{ inputs.end_date }}
          gcs_path_prefix: gs://REDACTED/google_ads/campaigns_metrics
          destination_table: REDACTED.landing_google_ads.campaigns_metrics
      - id: fetch_campaigns_pmax_video_metrics
        type: io.kestra.core.tasks.flows.Subflow
        namespace: prod
        flowId: fetchAndLoadBqFromGcs
        wait: true
        inputs:
          fetch_command: src/integrations/google_ads/jobs/fetch_campaigns_pmax_video_metrics.py --start_date {{ inputs.start_date }} --end_date {{ inputs.end_date }}
          gcs_path_prefix: gs://REDACTEDt/google_ads/campaigns_pmax_video_metrics
          destination_table: REDACTED.landing_google_ads.campaigns_pmax_video_metrics

```

main GoogleAds YAML, Flow that is Triggered

---

```yaml
id: fetchAndLoadBqFromGcs
namespace: prod
description: This is a sub flow that loads data to BigQuery from GCS after fetching data.

inputs:
  - id: fetch_command
    type: STRING
    required: true
    description: The command to fetch data

  - id: gcs_path_prefix
    type: STRING
    required: true
    description: The GCS path prefix to load data from
  
  - id: destination_table
    type: STRING
    required: true
    description: The destination table to load data to in BigQuery

tasks:
  - id: fetch_data
    type: io.kestra.plugin.scripts.python.Commands
    beforeCommands:
      - export PYTHONPATH=src
      - export GCP_PROJECT_ID=REDACTED
    commands:
      - python {{ inputs.fetch_command }}
  - id: load_bq_from_gcs
    type: io.kestra.plugin.gcp.bigquery.LoadFromGcs
    from:
      - "{{ inputs.gcs_path_prefix }}/{{ outputs.fetch_data.vars.uuid_str }}_*.parquet"
    destinationTable: "{{ inputs.destination_table }}"

taskDefaults:
  - type: io.kestra.plugin.scripts.python.Commands
    values:
      containerImage: us-central1-docker.pkg.dev/REDACTED/kestra-test/kestra-test:latest
      warningOnStdErr: false
      taskRunner:
        type: io.kestra.plugin.gcp.runner.GcpBatchTaskRunner
        projectId: REDACTED
        region: us-central1
        bucket: REDACTED

  - type: io.kestra.plugin.gcp.bigquery.LoadFromGcs
    values:
      writeDisposition: WRITE_APPEND
      createDisposition: CREATE_IF_NEEDED
      autodetect: true
      format: PARQUET
```

Sub Flow YAML
---

```python
from kestra import Kestra

from integrations.google_ads.fetch_data_and_load_to_gcs import (
    fetch_data_and_load_to_gcs,
)


def main():
    gaql_query = """
        SELECT
            customer_client.id
        FROM customer_client
        WHERE customer_client.manager = False
            AND customer_client.status = 'ENABLED'
    """

    mcc_ids = ["REDACTED"]

    uuid_str = fetch_data_and_load_to_gcs(
        customer_ids=mcc_ids,
        gaql_query=gaql_query,
        job_name="customers_info",
    )

    Kestra.outputs({"uuid_str": uuid_str})


if __name__ == "__main__":
    main()
```

Just a glimpse of where output is used. I basically fire off 4 of these at once and it happens 20-40% of the time, no outut. 


* I did not include serviceAccount: | .. in here , redacted that entirely, but it's in there.
* my apologies it's sloppy code right now, going to clean it up once I get it all working :D 

Let me know if you need anything else, thanks @anna-geller !!
