### ISSUE TITLE
UI doesn't let you select TIME or DURATION input types at execution if defaults set

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#3697]
### Describe the issue

When setting a default value for `TIME` or `DURATION`, the execute interface doesn't recognise them, and refuses to let you override it. If you remove the default values, the UI works as expected. If the `TIME` and `DURATION` don't support defaults, it would be helpful to show an error to the user. 

Also the duration type gives you a time picker in the UI, rather than a duration option:
![Screenshot 2024-05-10 at 11 42 24](https://github.com/kestra-io/kestra/assets/34094921/456dda8d-8847-470e-b320-dde756b9dc8c)

This doesn't work:

```yaml
inputs:
  - id: time
    type: TIME
    defaults: "11:01:01" 

  - id: duration
    type: DURATION
    defaults: PT2M
```

To get it to work, you need to remove the defaults but it's unclear that is the problem (see video):

```yaml
inputs:
  - id: time
    type: TIME

  - id: duration
    type: DURATION
```

https://github.com/kestra-io/kestra/assets/34094921/d1ee46dc-d6ac-4e7c-9967-1350a7bae99f

### Environment

- Kestra Version: 16.6
- Operating System (OS/Docker/Kubernetes): macOS
- Java Version (if you don't run kestra in Docker):
