### ISSUE TITLE
Debezium identifies all records but won't process more than 2GB worth of records

### ISSUE THREAD

**Issue by jgoguette** [kestra-io/kestra#3699]
### Describe the issue

Hello guys running into an issue.
I have an trigger that returned 8 million+ records as it's size.
However, when I run my execution about only 2 million records are being retrieved.
I'm batching the records by 500... so 500 * 3835 amounts to 1917500
Any ideas what could be wrong with my flow/task/trigger that it's not processing all 8 million records?

```
id: tophat2-mysql-connector-9
namespace: namespace

tasks:
  - id: trigger_sub_flow_for_cdc_events
    type: io.kestra.core.tasks.flows.ForEachItem
    items: "{{ trigger.uris['tophat2_staging.roas'] }}"
    batch:
      rows: 500
    namespace: namespace
    flowId: process_cdc_events
    wait: true
    transmitFailed: true
    inputs:
      data: "{{ taskrun.items }}"
      topic: "tophat2_roas"
      

triggers:
  - id: trigger_cdc_events_captured
    type: io.kestra.plugin.debezium.mysql.Trigger
    hostname: hostname
    password: "password"
    username: username
    port: "3306"
    ignoreDdl: true
    maxWait: 3600
    serverId: 9009
    format: INLINE
    snapshotMode: INITIAL
    includedTables:
      - tophat2_staging.roas

disabled: false
```

<img width="1176" alt="Screenshot 2024-05-07 at 2 17 11 PM" src="https://github.com/kestra-io/kestra/assets/88384557/dff07d2a-c841-46b7-b670-ec2880526473">
<img width="1176" alt="Screenshot 2024-05-07 at 2 17 58 PM" src="https://github.com/kestra-io/kestra/assets/88384557/f50f0f55-8ecc-4010-a076-7b749626107a">

### Environment

- Kestra Version: 0.16.6
- Operating System (OS/Docker/Kubernetes): Docker
- Java Version (if you don't run kestra in Docker):
