### ISSUE TITLE
Activities get stuck on "Created" if WORKER_GROUP doesn't exist / not running

### ISSUE THREAD

**Issue by johnkm516** [kestra-io/kestra#3706]
### Describe the issue

Activities using WORKER_GROUP for Kestra Enterprise get stuck on the "Created" status indefinitely if the WORKER_GROUP is not running / doesn't exist. The activity ignores all timeouts, and the flow will get stuck on "Running" status unless killed by the user.

Example : 
```
id: worker_group_test
namespace: dev

labels:
  env: dev

tasks:

  - id: wait
    type: io.kestra.plugin.scripts.shell.Commands
    commands:
      - sleep 10
    docker: {}
    runner: PROCESS
    timeout: 1
    workerGroup:
      key: NONEXISTANT_WORKER_GROUP
  - id: print_status
    type: io.kestra.core.tasks.log.Log
    message: hello
```

Expected Behavior : 

The activity should automatically fail if the activity is stuck on "Creating" for a set amount of time, or respect the timeout of the activity. 

### Environment

- Kestra Version: 0.16.6
- Operating System (OS/Docker/Kubernetes): Docker

**Comment by loicmathieu** [comment]
The timeout is handled by the Woker, as the worker group didn't exist; no worker will handle the task, so the timeout cannot be hit.

We have an opened issue in our internal repository about that but I keep this public one opened for you to have feedback.

**Comment by johnkm516** [comment]
> The timeout is handled by the Woker, as the worker group didn't exist; no worker will handle the task, so the timeout cannot be hit.
> 
> We have an opened issue in our internal repository about that but I keep this public one opened for you to have feedback.

Hi @loicmathieu , 
Thank you for your response. 

As worker groups can be on different server racks, I think there should be some sort of timeout outside of the task execution at the executor so that the flow fails if the task cannot be executed on the worker group. If the flow doesn't fail and continue indefinitely, it will be difficult to monitor and know if a flow is failing due to issues on a different VM or server rack where the worker group is located.

**Comment by johnkm516** [comment]
@anna-geller 

I'd like to bump this issue.

I have external contractors working with Kestra (who have never used Kestra before) and some of them are creating tasks mispelling the worker group key, or inputting some other data in the worker group key not fully understanding what the attribute does. Flows with tasks with worker group key that does not actually exist will run indefinitely, as the task will be stuck in the CREATED state and never get deployed as the worker group does not exist. I created a separate front-end issue to alleviate this here : #4755

Perhaps on the backend, instead of a timeout the executor could do a select query on the DB table used by the Cluster Monitor to check if there are any server instances with the worker group key that are in the state RUNNING, and fail the task if no such worker group key exists? I don't know the performance implications of having this select query before every task run in the executor, but it seems like the simplest solution.

**Comment by anna-geller** [comment]
We are planning to address this in 0.19.0, this will require creating a worker group via UI/API first, then it will be possible to have validation/autocompletion of the keys. We are tracking it internally in the EE repo https://github.com/kestra-io/kestra-ee/issues/1525

**Comment by johnkm516** [comment]
> We are planning to address this in 0.19.0, this will require creating a worker group via UI/API first, then it will be possible to have validation/autocompletion of the keys. We are tracking it internally in the EE repo https://github.com/kestra-io/kestra-ee/issues/1525

Would this validation/autocompletion make it so that the flow cannot be saved if the worker group does not actually exist? Would this only be handled on the frontend this way, or also on the backend? What would happen if I add the worker group in the UI/API first, but then after adding the worker group and saving to the Kestra DB I redeploy the cluster with the worker group key removed? 

Sorry for asking the questions here, and I'm sure the above are already addressed, but I'm curious how worker groups will be managed in 0.19 and I cannot read the internal issue you linked.

**Comment by anna-geller** [comment]
> Would this validation/autocompletion make it so that the flow cannot be saved if the worker group does not actually exist?

Yup, exactly 👍 

> Would this only be handled on the frontend this way, or also on the backend?

Afaik, mainly backend-driven, as the worker group will need to be created (sort of "registered") first. 

> What would happen if I add the worker group in the UI/API first, but then after adding the worker group and saving to the Kestra DB I redeploy the cluster with the worker group key removed?

The issue is mainly about the problem you reported, implementation is up to our backend engineers :) In terms of impact for you, the plan is that you have full control over what should happen with the task run (via `behavior` property) if for some reason no worker is currently polling for work for that worker group key. Example flow:

```yaml
id: worker_group
namespace: dev

tasks:
  - id: wait
    type: io.kestra.plugin.scripts.shell.Commands
    taskRunner:
      type: io.kestra.plugin.core.runner.Process
    commands:
      - sleep 10
    workerGroup:
      key: gpu
      behavior: FAIL # QUEUE or CANCEL
```
