### ISSUE TITLE
Improve the DURATION validation and UI display

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3710]
### Feature description

**UI side**: https://codesandbox.io/p/sandbox/react-duration-input-i7ekk?file=%2Fsrc%2Findex.js

**Validation**: ensure that the duration string is a valid ISO-type duration e.g. these are valid:
- PT2H = 2 hours
- P2D = 2 days
- P2W = 2 weeks
- P2M = 2 months

but this is not valid: PT3D = 3 dates with period timestamp is invalid

## More context

Try this flow:

```yaml
id: duration_repro
namespace: company.team

inputs:
  - id: duration
    type: DURATION
    defaults: PT1H

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: my {{ inputs.duration }}
```

it's not clear which units are intended here:
![image](https://github.com/user-attachments/assets/73878e8f-bec1-4b91-ba23-d64b962660d8)

When you set a larger duration period, the UI becomes very confusing:

![image](https://github.com/user-attachments/assets/e625ae42-ba45-43de-bcb0-2f4592ada822)

now try to enter a totally invalid duration as default like `PT3D`:
```yaml
id: duration_repro
namespace: company.team

inputs:
  - id: duration
    type: DURATION
    defaults: PT3D

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: my {{ inputs.duration }}
```

the UI misinterprets it as no duration set at all:

![image](https://github.com/user-attachments/assets/a54e1d24-70ca-42a8-91de-63f2e7be6450)

## Suggested solution

We should change the UI display to allow clearly specifying days, hours, minutes and perhaps also seconds:

![image](https://github.com/user-attachments/assets/b189a6e1-8b40-4353-868f-23134a5b0f4c)

and we should additionally provide an option to set a custom duration as a string, similarly to how we offer that for KV Store with duration-type property:
![image](https://github.com/user-attachments/assets/1572ca94-4088-4006-b78f-b9759594c5a6)
