### ISSUE TITLE
GCPBatchTaskRunner projectId not working with Pebble

### ISSUE THREAD

**Issue by japerry911** [kestra-io/kestra#3714]
### Describe the issue

```
variables:
  gcp_project_id: 'project id'

...
  taskRunner:
      type: io.kestra.plugin.gcp.runner.GcpBatchTaskRunner
      projectId: "{{ vars.gcp_project_id }}"
```

This returns that the task cannot access '{{ vars.gcp_project_id }}'. Also tried with Pebble IF conditional ({% if ...%} syntax.
```
io.grpc.StatusRuntimeException: PERMISSION_DENIED: Permission denied on resource project {{ vars.gcp_project_id }}.
```

The docs say it's a Dynamic Variable as well: 
[projectId](https://kestra.io/plugins/plugin-gcp/task-runners/runner/io.kestra.plugin.gcp.runner.gcpbatchtaskrunner#projectid)
Type: string
Dynamic: ✔️
Required: ❌
The GCP project ID.

Let me know if you need more context or have any questions! Thank you :D 

--- Also notice [containerImage](https://kestra.io/plugins/plugin-script-python/tasks/io.kestra.plugin.scripts.python.commands#containerimage) isn't allowing me to as well and is labeled as dynamic

### Environment

- Kestra Version: 0.16.6
- Operating System (OS/Docker/Kubernetes): Ubuntu Docker Compose GCP VM
- Java Version (if you don't run kestra in Docker): n/a
