### ISSUE TITLE
Editor is mixing value from differents inputs 

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#3716]
The monaco editor display value from others fields on `Edit Metadata`. 

Using this flow: 
```yaml 
id: get_github_version_example
namespace: home.lab
description: Obtains the latest release version given a repo
labels:
  area: subtask

variables: 
  name: bla

inputs:
  - type: STRING
    id: user
    required: true
    description: Name of the user or organization on GitHub
  - type: STRING
    id: repo
    description: Name of the GitHub repository
    required: true
tasks:
  - id: get_latest_release
    type: io.kestra.plugin.fs.http.Request
    headers:
      Accept: application/json
      User-Agent: kestra
    uri: https://api.github.com/repos/{{inputs.user}}/{{inputs.repo}}/releases/latest

taskDefaults:
  - type: io.kestra.plugin.scripts.python.Script
    values:
      docker:
        image: python:slim
        pullPolicy: ALWAYS
      runner: DOCKER

concurrency:
  behavior: FAIL
  limit: 1

outputs:
  - id: version
    type: STRING
    value: "{{outputs.get_latest_release.body | jq('.tag_name') | first}}"

```
If you open metadata editor, open first variable, you will see flow description and note the value `bla`

Probably due to: 
```
chunk-N376D7G6.js?v=62ed99f9:8329 Uncaught (in promise) Error: ModelService: Cannot add model because it already exists!
    at ModelService2._createModelData (chunk-N376D7G6.js?v=62ed99f9:8329:13)
    at ModelService2.createModel (chunk-N376D7G6.js?v=62ed99f9:8338:24)
    at doCreateModel (chunk-N376D7G6.js?v=62ed99f9:15945:23)
    at createTextModel (chunk-N376D7G6.js?v=62ed99f9:15942:10)
    at Object.createModel (chunk-N376D7G6.js?v=62ed99f9:16706:10)
    at Proxy.changeTab (MonacoEditor.vue:592:47)
    at async Proxy.initMonaco (MonacoEditor.vue:556:21)
```

Before new editor tabs, the problems don't happen.
