### ISSUE TITLE
URI path does not preserve "\" in CSVWriter plugin output on Windows

### ISSUE THREAD

**Issue by paulgrainger85** [kestra-io/kestra#3724]
### Describe the issue

Executing the following flow on Windows results in the following statement printed in the log:

```log
C:UserspaulAppDataLocalTemp1ImK0NcqbsxIcmzIlGsNUa14572494380012919038.tmp
```

The expected output would be 
```
C:\Users\paul\AppData\LocalTemp\1ImK0NcqbsxIcmzIlGsNUa\14572494380012919038.tmp
```

```
id: test
namespace: bug_report

tasks:
  - id: export
    type: io.kestra.plugin.jdbc.postgresql.Query
    url: jdbc:postgresql://host:port/db
    username: user
    password: ...
    store: true
    sql: SELECT * FROM test LIMIT 10

  - id: write_to_csv
    type: io.kestra.plugin.serdes.csv.CsvWriter
    from: "{{ outputs.export.uri }}"

  - id: process_output
    type: io.kestra.plugin.scripts.powershell.Script
    runner: PROCESS
    script: |
      echo "{{ outputs.export.uri }}"

```

### Environment

- Kestra Version: 0.15.8
- Operating System: Windows 11
- Java Version 
```
openjdk version "17.0.11" 2024-04-16
OpenJDK Runtime Environment Temurin-17.0.11+9 (build 17.0.11+9)
OpenJDK 64-Bit Server VM Temurin-17.0.11+9 (build 17.0.11+9, mixed mode, sharing)
```
