### ISSUE TITLE
Azure taskRunner fails because of `Cannot invoke "Object.toString()"`

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#3733]
### Describe the issue

![image](https://github.com/kestra-io/kestra/assets/46634684/cf5d760b-2f59-4c82-a62f-6d83f0c0d727)

```yaml
id: new-shell
namespace: myteam

tasks:
  - id: shell
    type: io.kestra.plugin.scripts.shell.Commands
    containerImage: ubuntu
    taskRunner:
      type: io.kestra.plugin.azure.runner.AzureBatchTaskRunner
      account: "batchunitest"
      accessKey: "XXX"
      endpoint: "XXX"
      poolId: "azure-unit-test"
    commands:
      - echo "Hello World"
```

### Environment

- Kestra Version: 0.17.0.SNAPSHOT
- Operating System (OS/Docker/Kubernetes): Docker MacOS
- Java Version (if you don't run kestra in Docker):
