### ISSUE TITLE
Accessing optional inputs should return null rather than resulting in an error

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3769]
### Feature description

Despite this PR https://github.com/kestra-io/kestra/pull/2358

The following flow: 
```yaml
id: my_flow_with_inputs
namespace: dev

inputs:
  - id: my_input
    type: STRING
    required: false
    
tasks:
  - id: print_input
    type: io.kestra.plugin.core.log.Log
    message: "{{ inputs.my_input }}"
```

still fails with:

```
Missing variable: 'inputs' on '{{ inputs.my_input }}' at line 1
Root attribute [inputs] does not exist or can not be accessed and strict variables is set to true. ({{ inputs.my_input }}:1)
```

instead of returning null.

Atm, it doesn't seem possible to set an input to `null` by default either, see:

```yaml
id: my_flow
namespace: dev

inputs:
  - id: my_input
    type: STRING
    defaults: null
    required: false

tasks:
  - id: first
    type: io.kestra.plugin.core.debug.Return
    format: "{{ inputs.my_input ?? null }}"

  - id: check
    type: io.kestra.plugin.core.flow.If
    condition: "{{ outputs.first.value is null }}"
    then: 
      - id: isnull
        type: io.kestra.plugin.core.log.Log
        message: it's a null
    else:
      - id: isnotnull
        type: io.kestra.plugin.core.log.Log
        message: still not null — {{ outputs.first.value }}
```

In the above flow, `inputs` is an empty map `{}` as if there would be no inputs, even though there is one, even explicitly set to `null`. 

Related to https://github.com/kestra-io/kestra/issues/3768

**Comment by loicmathieu** [comment]
I run the first example and it show this exception: `Missing variable: 'my_input' on '{{ inputs.my_input }}' at line 1` which is expected ad the variable `my_input` didn't exist. If you have the exception with the variable `inputs` it means you are not on the latest version of Kestra.

For the second point:

> In the above flow, inputs is an empty map {} as if there would be no inputs, even though there is one, even explicitly set to null.

`null` means no input, one possibility would be to switch run context variables serialization to ALWAYS (inputs will be included in this list) so variables set to null would be included.

**Comment by anna-geller** [comment]
Let's explore that option with ALWAYS or some alternatives then.  The goal is for both examples from the issue body to work in 0.17

**Comment by anna-geller** [comment]
great work @loicmathieu <3 I thought this would be way more complex, thx a lot!

![image](https://github.com/kestra-io/kestra/assets/86264395/4b94a497-e9a9-4c91-ab5d-15a2c4e07404)

this one also works as expected:
```yaml
id: my_flow
namespace: dev

inputs:
  - id: my_input
    type: STRING
    defaults: null
    required: false

tasks:
  - id: check
    type: io.kestra.plugin.core.flow.If
    condition: "{{ inputs.my_input is null }}"
    then: 
      - id: isnull
        type: io.kestra.plugin.core.log.Log
        message: it's a null
    else:
      - id: isnotnull
        type: io.kestra.plugin.core.log.Log
        message: not null
```

seems like nothing left to discuss regarding serialization so I'll cancel that meeting
