### ISSUE TITLE
Allow to pass input on a schedule 

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#378]
```yaml
triggers:
  - id: schedule
    type: org.kestra.core.models.triggers.types.Schedule
    inputs: 
      my-input: true
    conditions:
      - type: org.kestra.core.models.conditions.types.VariableCondition
        expression: "{{ eq \"prd\" globals.env }}"
    cron: 30 10 * * 3
```
