### ISSUE TITLE
Unable to use GKE for KubernetesTaskRunner

### ISSUE THREAD

**Issue by paulgrainger85** [kestra-io/kestra#3786]
### Describe the issue

I am unable to configure the KubernetesTaskRunner to use GKE. I am following the steps [here](https://kestra.io/docs/concepts/task-runners/types/kubernetes-task-runner)

```
kubectl config view --minify --flatten

apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <ca-data> 
    server: https://ip_address/
  name: gke_cluster_name
contexts:
- context:
    cluster: gke_cluster_name
    user: gke_cluster_name
  name: gke_cluster_name
current-context: gke_cluster_name
kind: Config
preferences: {}
users:
- name: gke_cluster_name
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args: null
      command: gke-gcloud-auth-plugin
      env: null
      installHint: Install gke-gcloud-auth-plugin for use with kubectl by following
        https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-access-for-kubectl#install_plugin
      interactiveMode: IfAvailable
      provideClusterInfo: true
```

Creating the task runner with the following flow config, following the documentation 
```
taskRunner:
      type: io.kestra.plugin.kubernetes.runner.KubernetesTaskRunner
      namespace: default
      pullPolicy: Always
      config:
        masterUrl: https://ip_address
        username: gke_cluster_name
        caCert: <ca-data>
```

Consistently gives the following error
```
Failure executing: GET at: https://<ip_address>/api/v1/namespaces/default/pods?labelSelector=domain.io%2Ftaskrun-id%3D6AFSVnZGU4ZEYfebcgIzML%2Cdomain.io%2Ftaskrun-attempt%3D0. Message: pods is forbidden: User "system:anonymous" cannot list resource "pods" in API group "" in the namespace "default"
```

### Environment

- Kestra Version: 0.16.6
- Operating System : Docker (host MacOS)
