### ISSUE TITLE
Rename VariableCondition to ExpressionCondition or just Condition/Expression

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3790]
### Issue description

we used to call Pebble expressions "Variables" but we no longer do it. Given we do the entire renaming in 0.17, worth renaming this one too https://develop.kestra.io/plugins/core/conditions/condition/io.kestra.plugin.core.condition.variablecondition 

Current:

```yaml
- conditions:
    - type: io.kestra.plugin.core.condition.VariableCondition
      expression: {{ unknown is defined }}
```

Perhaps we can do this instead?

```yaml
- conditions:
    - type: io.kestra.plugin.core.condition.Expression
      expression: {{ unknown is defined }}
```
