### ISSUE TITLE
Enhancements to the `WaitFor` — change iterationCount to start with 0 and fix the Return task

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3800]
### Feature description

Issues discovered during QA of the `WaitFor` task:

- [X] We should change the `iterationCount` to start with 0 instead of 1 to make the output feel more natural -- see the example here where it feels unnatural that we reach iterationCount 11 even though we explicitly specified that we should stop at 10 (we should never reach iteration bigger than 10 based on the condition below but ion fact atm we stop at iteration 11 because the condition is evaluated after the tasks finish)

```yaml
id: simple_counter
namespace: dev
 
tasks:
  - id: loop_until_10
    type: io.kestra.plugin.core.flow.WaitFor
    condition: "{{ outputs.loop_until_10.iterationCount <= 10 }}"
    tasks:
      - id: log_iteration
        type: io.kestra.plugin.core.log.Log
        message: "Current iteration: {{ outputs.loop_until_10.iterationCount }}"
    checkFrequency:
      interval: PT0.1S
      maxDuration: PT30S
```

- [X] the Return task doesn't render the Pebble expression correctly in the metrics tab

```yaml
id: example
namespace: myteam

tasks:
  - id: loop
    type: io.kestra.plugin.core.flow.WaitFor
    condition: "{{ outputs.return.value != '4' }}"
    tasks:
      - id: return
        type: io.kestra.plugin.core.debug.Return
        format: "{{ outputs.loop.iterationCount }}"
```

![image](https://uploads.linear.app/94448d51-ba32-420f-b3fd-ccff522d60f3/32cd20a4-6037-49a5-989e-cd9910547280/7d113034-d4af-4f4e-b4d8-a7e08b967900?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzk0NDQ4ZDUxLWJhMzItNDIwZi1iM2ZkLWNjZmY1MjJkNjBmMy8zMmNkMjBhNC02MDM3LTQ5YTUtOTg5ZS1jZDk5MTA1NDcyODAvN2QxMTMwMzQtZDRhZi00ZjRlLWI0ZDgtYTdlMDhiOTY3OTAwIiwiaWF0IjoxNzE2NDA4Njc0LCJleHAiOjMzMjg2OTY4Njc0fQ.XuMNP52DNqKR9qpfAE8MRiAx6-aOpgURfeFQ9dsLWTU)
