### ISSUE TITLE
Github push plugin issue with file replacement of file name in inputFiles

### ISSUE THREAD

**Issue by nikolicdragoslav** [kestra-io/kestra#3805]
### Feature description

Hello,

I am running into an issue where I generate a file based on some JSON event input. File name is created from JSON, so I don't know it pre-hand in order to hardcode it in **inputFiles** parameter of **io.kestra.plugin.git.Push**. 

Example input:
`{
  "version": "14",
  "created_by": "Jonh",
  "created_at": "2024-01-01: 01:01:01",
  "comments": "some comments for commit",
  "full_refresh": false,
  "flow_id": "testing_replace",
  "file_name": "testing_replace.yml"
}`

My code:
```
id: example
namespace: dev
inputs:
- id: event
  type: JSON
tasks:
- id: wdir
  type: io.kestra.core.tasks.flows.WorkingDirectory
  tasks:
  - id: printEvent
    type: io.kestra.core.tasks.log.Log
    message: "{{inputs.event}}"
  - id: cloneRepo
    type: io.kestra.plugin.git.Clone
    url: url
    username: user
    password: pass
    branch: main
  - id: generateFlow
    type: io.kestra.plugin.scripts.python.Commands
    beforeCommands:
     - pip install pyyaml
    namespaceFiles:
      enabled: true
    commands:
     - "python utilities/scripts/generate_flow.py '{{inputs.event}}' utilities/flow_templates/run_dbt_tags.yml"
  - id: outputFile
    type: io.kestra.core.tasks.storages.LocalFiles
    outputs:
     - "{{inputs.event.file_name}}"
  - id: printOutputs  
    type: io.kestra.core.tasks.log.Log  
    message: '{{outputs.outputFile.uris[inputs.event.file_name]}}' 
    
  - id: gitPush  
    type: io.kestra.plugin.git.Push  
    username: user 
    password: pass
    branch: main  
    commitMessage: "{{inputs.event.comments}}"  
    flows:  
      enabled: true  
      childNamespaces: true  
      gitDirectory: _flows  
    inputFiles:    
      _flows/"{{inputs.event.file_name}}": "{{outputs.outputFile.uris[inputs.event.file_name]}}"  
 
    addFilesPattern:  
    - _flows/"{{inputs.event.file_name}}"
```
The code above executes and finds no changes in git, while in git the file does not exist. I also have only one branch called main
When I print this variable:
`{{outputs.outputFile.uris[inputs.event.file_name]}}`
I get:
`kestra:///dev/example/executions/6PHO2VMiyCBhENUEGC20tz/tasks/outputfile/2JRqClceAawhJImh0K75Xg/testing_replace.yml`

For example, when hardcoded it works:
`inputFiles:
          _flows/output.yml:`

Thanks

**Comment by anna-geller** [comment]
Hey, I have great news, we've recently significantly improved the Git integration and your challenge will be solved in 0.17.0 release planned to launch on 4th of June. You can already test those new tasks by switching your docker image to develop: `kestra/kestra:develop-full`

Once this new task https://github.com/kestra-io/kestra/issues/2461 is added, you'll be able to do:

```yaml
id: example
namespace: dev

inputs:
- id: event
  type: JSON

tasks:
  - id: scripts
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      - id: generateFlow
        type: io.kestra.plugin.scripts.python.Commands
        outputFiles:
          - "{{ inputs.event.file_name }}"
        beforeCommands:
          - pip install pyyaml
        namespaceFiles:
          enabled: true
        commands:
          - python utilities/scripts/generate_flow.py '{{inputs.event}}' utilities/flow_templates/run_dbt_tags.yml    

      - id: upload_to_namespace
        type: io.kestra.plugin.core.namespace.Files
        action: UPLOAD 
        namespace: dev
        files: # list of RegEx strings or specific file paths
          - "{{ inputs.event.file_name }}"

  - id: git_push
    type: io.kestra.plugin.git.PushNamespaceFiles
    files: 
      - "{{ inputs.event.file_name }}"
    gitDirectory: _flows
    url: https://github.com/kestra-io/scripts 
    username: git_username 
    password: "{{ secret('GITHUB_ACCESS_TOKEN') }}"
    branch: dev 
```

**Comment by anna-geller** [comment]
Hi @nikolicdragoslav, 0.18 now supports your use case. Try something like this on the latest version: `docker pull kestra/kestra:latest`:

```yaml
id: example
namespace: dev

inputs:
- id: event
  type: JSON

tasks:
  - id: scripts
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      - id: generateFlow
        type: io.kestra.plugin.scripts.python.Commands
        outputFiles:
          - "{{ inputs.event.file_name }}"
        beforeCommands:
          - pip install pyyaml
        namespaceFiles:
          enabled: true
        commands:
          - python utilities/scripts/generate_flow.py '{{inputs.event}}' utilities/flow_templates/run_dbt_tags.yml    

      - id: upload_to_namespace
        type: io.kestra.plugin.core.namespace.UploadFiles
        namespace: dev
        filesMap: "{{ inputs.event.file_name }}" # or files

  - id: git_push
    type: io.kestra.plugin.git.PushNamespaceFiles
    files: 
      - "{{ inputs.event.file_name }}"
    gitDirectory: _flows
    url: https://github.com/kestra-io/scripts 
    username: git_username 
    password: "{{ secret('GITHUB_ACCESS_TOKEN') }}"
    branch: dev 
```
