### ISSUE TITLE
Autocompletion doesn't work for nested tasks

### ISSUE THREAD

**Issue by brian-mulier-p** [kestra-io/kestra#3819]
### Describe the issue

```
id: internal-storage
namespace: io.kestra.bmu
tasks:
  - id: wdir
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      - id: local_file
        type: io.kestra.plugin.core.storage.LocalFiles
        inputs:
          retrieve.py: "print('hello')"
      - id: local_file_to_internal
        type: io.kestra.plugin.scripts.shell.Commands
        outputFiles:
          - myFile.txt
        commands:
          - echo "Output myFile.txt to internalStorage"
```

you don't get autocompletion for outputs.local_file_to_internal

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):
