### ISSUE TITLE
Python script failing when temporary storage bindmount set to something other than /tmp

### ISSUE THREAD

**Issue by paulgrainger85** [kestra-io/kestra#3849]
### Describe the issue

This may apply to other scripting plugins too however was observed on python script plugin. 

Configure your Kestra instance via docker-compose and set the volumes as follows:

```
  kestra:
    image: kestra/kestra:latest-full
    pull_policy: always
    # Note that this is meant for development only. Refer to the documentation for production deployments of Kestra which runs without a root user.
    user: "root"
    command: server standalone --worker-thread=128
    volumes:
      - kestra-data:/app/storage
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/kestra-wd:/tmp/kestra-wd
...
```

Run a simple flow and observe that it succeeds, 
```
id: pythontest
namespace: demo

tasks:
  - id: pythondemo
    type: io.kestra.plugin.scripts.python.Script
    runner: DOCKER
    script: |
      import requests

      response = requests.get("https://google.com")
      print(response.status_code)
    beforeCommands:
      - pip install requests

```

Now, update the temporary storage bind mount to a different location and restart the kestra container, e.g.
```
      - /home/paul/tmp/kestra-wd:/tmp/kestra-wd
```

Execute the same flow as before and observe that it fails

### Environment

- Kestra Version: 0.16.8
- Operating System : Docker on Debian 12
