### ISSUE TITLE
Input of type FILE should preserve the file extension

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#3858]
### Describe the issue

Imagine the following flow:

```yaml
id: inputs
namespace: company.myteam

inputs:
  - id: payload.ion
    type: FILE
tasks:
  - id: log
    type: io.kestra.plugin.core.log.Log
    message: Hello World
```

The payload.ion input will create a file in the internal storage like: ` payload.ion_<uniqueId>.upl` so the file extension will be `upl` not `ion`.

There is two ways to fix that:
- Preserve the extension from the input name
- Allow to specify the extension when defining an input so it's not needed to have it in the input name

### Environment

- Kestra Version: 0.17.0-SNAPSHOT
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):
