### ISSUE TITLE
First click on "resume" in the execution page didn't work

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#3859]
### Describe the issue

Example flow:

```yaml
id: pause
namespace: company.myteam
description: Save and Execute the flow

tasks:
  - id: before
    type: io.kestra.plugin.core.log.Log
    message: I'm going to pause

  - id: pause
    type: io.kestra.plugin.core.flow.Pause

  - id: print_status
    type: io.kestra.plugin.core.log.Log
    message: I'm resuming now
```

On the first click on resume on the execution Overview page, it didn't work and the following error is displayed in the browser console:
```
index-D-uls3OS.js:14 TypeError: Cannot read properties of undefined (reading 'length')
    at Proxy.needInputs (index-D-uls3OS.js:386:15766)
    at mN.fn (index-D-uls3OS.js:10:9200)
    at mN.run (index-D-uls3OS.js:10:1522)
    at get value (index-D-uls3OS.js:10:9445)
    at Object.get [as needInputs] (index-D-uls3OS.js:14:16754)
    at Object.get (index-D-uls3OS.js:14:14904)
    at Proxy.click (index-D-uls3OS.js:386:14790)
    at zd (index-D-uls3OS.js:14:38)
    at Js (index-D-uls3OS.js:14:109)
    at tve (index-D-uls3OS.js:14:2221)
```

On the second cick it works.

### Environment

- Kestra Version: 0.17.0-SNAPSHOT
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):
