### ISSUE TITLE
WaitFor with 'maxIterations' is interupted too early

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#3861]
### Describe the issue

A WaitFor task with a `maxIterations` is interupted before doing the last iteration instead of after.

Example flow:

```yaml
id: waitfor
namespace: company.myteam

tasks:
  - id: loop
    type: io.kestra.plugin.core.flow.WaitFor
    condition: "{{ outputs.return.value == '4' }}"
    checkFrequency:
      maxIterations: 3
    tasks:
      - id: return
        type: io.kestra.plugin.core.debug.Return
        format: "{{ outputs.loop.iterationCount }}"
      - id: log
        type: io.kestra.plugin.core.log.Log
        message: "Loop {{outputs.loop.iterationCount}}"
```

Outputs:
![image](https://github.com/kestra-io/kestra/assets/1819009/3782810c-44f6-4e26-a8a0-b78d88015ac9)

### Environment

- Kestra Version: 0.17.0-SNAPSHOT
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):
