### ISSUE TITLE
Investigate a transient issue `Error: The flow or Execution you are looking for does not exist.`

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3864]
### Describe the issue

Usually, when you create a new execution, this error no longer appears. We should investigate more to find the root cause. 

![image](https://github.com/kestra-io/docs/assets/86264395/39b9a7f4-e79a-476b-b8a7-71381e8dbba4)

## Recent report

Hi All, when using kestra on a remote docker server, I get the following error on flow execution:
Error: The flow or Execution you are looking for does not exist.

I have created the environment using the docker compose yml file in github

```yaml
volumes:
  postgres-data:
    driver: local
  kestra-data:
    driver: local

services:
  postgres:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: kestra
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 10

  kestra:
    image: kestra/kestra:latest-full
    pull_policy: always
    # Note that this is meant for development only. Refer to the documentation for production deployments of Kestra which runs without a root user.
    user: "root"
    command: server standalone --worker-thread=128
    volumes:
      - kestra-data:/app/storage
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/kestra-wd:/tmp/kestra-wd
    environment:
      KESTRA_CONFIGURATION: |
        datasources:
          postgres:
            url: jdbc:postgresql://postgres:5432/kestra
            driverClassName: org.postgresql.Driver
            username: kestra
            password:
        kestra:
          server:
            basic-auth:
              enabled: false
              username: "admin@kestra.io" # it must be a valid email address
              password:
          repository:
            type: postgres
          storage:
            type: local
            local:
              base-path: "/app/storage"
          queue:
            type: postgres
          tasks:
            tmp-dir:
              path: /tmp/kestra-wd/tmp
          url: http://192.168.3.252:8080/
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_started
```

When I look at the logs, I don't see an error in the docker. Might it be something on the web UI?

### Environment

- Kestra Version: 0.16.6
- Operating System (OS/Docker/Kubernetes): macOS in docker
