### ISSUE TITLE
Dynamic execution labels from triggers

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#3876]
### Feature description

Currently, you can pass execution labels when starting an execution from the UI/API or a Webhook.
But you cannot do that from a Trigger as triggers automatically start executions so the list of labels is static and not dynamic.

But there is interesting use case for that, for example to add some identifier in a label extracted from the trigger message.

What we can do is to allow to define dynamic labels in a trigger that will allow using Pebble expression so the trigger output will be available to create the labels.

For example:

```yaml
id: trigger
type: io.kestra.plugin.jdbc.postgres.ReatimeTrigger
[...]
labels:
  key1: static value
  key2: "{{json(trigger.data).productId}}"
```

**Comment by anna-geller** [comment]
Thinking more, couldn't you do this instead?

```yaml
id: myflow
namespace: dev
labels:
  key1: static value
  key2: "{{json(trigger.data).productId}}"
tasks:
...
triggers:
...
```

There is also a Labels task, so it's already possible

**Comment by loicmathieu** [comment]
@anna-geller we cannot do as you propose as flow labels are static labels not dynamic, we copy flow labels into the execution at run time but flow labels are also used to filter flows for ex.

**Comment by Pradumnasaraf** [comment]
Working. QA done ✅. Sample code for docs cc @aj-emerich 

```yaml
id: dynamic_trigger_labels
namespace: qa.triggers

tasks:
  - id: show_labels
    type: io.kestra.plugin.core.log.Log
    message: "Execution labels: {{ labels }}"

triggers:
  - id: every_minute
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "* * * * *"
    labels:
      environment: production
      execution_year: "{{ now(format='YYYY') }}"
      triggered_on: "{{ trigger.date }}"

```

<img width="1278" height="1080" alt="Image" src="https://github.com/user-attachments/assets/27a64f19-e382-4edd-bf8f-7563ce7813c4" />
