### ISSUE TITLE
Add multiline text input support

### ISSUE THREAD

**Issue by yangkghjh** [kestra-io/kestra#3881]
### Feature description

Use case:
- Edit a yaml config file from web as a input file

**Comment by anna-geller** [comment]
can you say a bit more? it would help if you could share an example flow and some screenshots showing what's currently not feasible

**Comment by yangkghjh** [comment]
A textarea to input multi-line text content

Example - input a yaml config:

![image](https://github.com/kestra-io/kestra/assets/3609399/5ef6a93e-85c0-4741-aa14-d0858bd0fdb9)

**Comment by anna-geller** [comment]
interesting... we don't have YAML type input atm, but you can add multiline-STRING type input as follows:

![image](https://github.com/kestra-io/kestra/assets/86264395/2b380b3b-a60d-41fe-ae10-450ae1accd2b)


```yaml
id: myflow
namespace: company.myteam

inputs:
  - id: payload
    type: STRING

tasks:
  - id: print_status
    type: io.kestra.plugin.core.log.Log
    message: "{{ yaml(inputs.payload) }}"
```

does that solve it for you? multiline string should work out of the box
