### ISSUE TITLE
QA NamespaceFiles tasks

### ISSUE THREAD

**Issue by brian-mulier-p** [kestra-io/kestra#3888]
### Describe the issue

- [x]  NPE if you don't provide glob pattern (should be marked as '**' by default in doc and a null check should be done)

```
id: ns-files
namespace: company.myteam

tasks:
  - id: send_data
    type: io.kestra.plugin.core.namespace.DownloadFiles
    namespace: company
```

```
2024-05-30 17:39:43.035java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "this.files" is null
	at io.kestra.plugin.core.namespace.DownloadFiles.run(DownloadFiles.java:87)
	at io.kestra.plugin.core.namespace.DownloadFiles.run(DownloadFiles.java:33)
	at io.kestra.core.runners.WorkerTaskThread.doRun(WorkerTaskThread.java:77)
	at io.kestra.core.runners.AbstractWorkerThread.run(AbstractWorkerThread.java:56)
```

- [x]  files should be an object and should optionally be a single glob string OR an array of globs (see [this](https://github.com/kestra-io/plugin-git/blob/c34d213037429a0660537820fec1678ec6d3ef20/src/main/java/io/kestra/plugin/git/AbstractPushTask.java#L283-L286))
- [x] DownloadFiles `files` globs are expecting the full Kestra path, including the my/namespace/_files. It's an implementation detail that user should not be aware of, we should toNamespacedUri(namespace, null).relativize(path) . See below:
with this: 
![image](https://github.com/kestra-io/kestra/assets/37618489/414667fd-2960-48a2-8eb7-e3c159a97594)
This flow will not download anything
```
id: ns-files
namespace: company.myteam

tasks:
  - id: pullNsFiles
    type: io.kestra.plugin.core.namespace.DownloadFiles
    namespace: company
    files: 
      - "titi.txt"
```
but this will
```
id: ns-files
namespace: company.myteam

tasks:
  - id: pullNsFiles
    type: io.kestra.plugin.core.namespace.DownloadFiles
    namespace: company
    files: 
      - "/company/_files/titi.txt" # or "**titi.txt"
```

- [x] UploadFiles task `files` property should be required (NotNull)
- [x] Bad indent / example in UploadFiles task
![image](https://github.com/kestra-io/kestra/assets/37618489/cb4130a8-3386-4123-97e4-33b8bfc2d2a2)
- [x] Please CTRL + SHIFT + F for regex in your tasks, should be replaced with "glob patterns, especially in doc
- [x] Lacks doc for outputs format (eg. what do I get in `files` output of DownloadFiles task, it says object<string>, maybe add an example format)
- [x] UploadFiles.files: `Can be a list of String, containing both a regex or a URI. Providing a list required to specify a destination.
Can also be a Map where you can give a specific destination path for a specific URI, useful if you need to rename a file.` => `Can be a list of String (path, containing both a regex or a URI. Providing a list required to specify a destination.
Can also be a Map where you can give a specific destination path for a specific URI, useful if you need to rename a file.`
- [x] This will not work
```
- id: uploadNsFilesInline
    type: io.kestra.plugin.core.namespace.UploadFiles
    namespace: company.myteam.test
    files:
      upload/file.txt: "{{outputs.pullNsFiles.files['titi.txt']}}"
```
because we don't have a leading slash in files key. Please add the leading slash if it's not there as it's an implementation detail
- [x] UploadFiles example with {{ inputs.file }} lacks an input at top

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):
