### ISSUE TITLE
Docker volmune mounting broken

### ISSUE THREAD

**Issue by PintjesB** [kestra-io/kestra#3896]
### Describe the issue

Hi,

after some troubleshooting with Ludovic & Florian we have figured out that the volume passing settings is broken.

The documented 'new' way of doing it, doesn't work: https://kestra.io/docs/developer-guide/scripts/bind-mount

```
plugins:
            configurations:
              - type: io.kestra.plugin.scripts.runner.docker.DockerTaskRunner
                values:
                  volume-enabled: true # 👈 this is the relevant setting
```

The 'old' way of doing it, does work but produces a deprecated error: https://kestra.io/docs/configuration-guide/tasks#docker-configuration

```
kestra:
  tasks:
    scripts:
      docker:
        volume-enabled: true
```

### Environment

- Kestra Version: 0.16.6
- Operating System (OS/Docker/Kubernetes): Portainer running on ubuntu 18.04.6
