### ISSUE TITLE
Using AWS SQS Realtime Trigger to push events into DynamoDB

### ISSUE THREAD

**Issue by shrutimantri** [kestra-io/kestra#3907]
### Blueprint title

Using AWS SQS Realtime Trigger to push events into DynamoDB

### Source code

```yaml
id: sqs_realtime_trigger
namespace: blueprint

tasks:
  - id: insert_into_dynamoDB
     type: io.kestra.plugin.aws.dynamodb.PutItem
     accessKeyId: "{{ secret('AWS_ACCESS_KEY_ID') }}"
     secretKeyId: "{{ secret('AWS_SECRET_KEY_ID') }}"
     region: "eu-central-1"
     tableName: "orders"
     item:
       order_id: "{{ trigger.value | jq('.order_id') | first }}"
       customer_name: "{{ trigger.value | jq('.customer_name') | first }}"
       customer_email: "{{ trigger.value | jq('.customer_email') | first }}"
       product_id: "{{ trigger.value | jq('.product_id') | first }}"
       price: "{{ trigger.value | jq('.price') | first }}"
       quantity: "{{ trigger.value | jq('.quantity') | first }}"
       total: "{{ trigger.value | jq('.total') | first }}"
triggers:
  - id: "realtime_trigger"
     type: io.kestra.plugin.aws.sqs.RealtimeTrigger
     accessKeyId: "{{ secret('AWS_ACCESS_KEY_ID') }}"
     secretKeyId: "{{ secret('AWS_SECRET_KEY_ID') }}"
     region: "eu-central-1"
     queueUrl: "https://sqs.eu-central-1.amazonaws.com/000000000000/orders"
     serdeType: JSON
```

### About this blueprint

This flow will:

1. Get triggered every time the event lands onto AWS SQS queue with the [RealtimeTrigger](https://kestra.io/plugins/plugin-aws/triggers/io.kestra.plugin.aws.sqs.realtimetrigger)
2. The flow will push the data onto a table in DynamoDB

For this, create a SQS queue named `orders`. We will be producing JSON messages into the queue generated from the [orders.csv](https://huggingface.co/datasets/kestra/datasets/raw/main/csv/orders.csv). One sample produced message can be:

```
{"order_id": "1", "customer_name": "Kelly Olsen", "customer_email": "jenniferschneider@example.com", "product_id": "20", "price": "166.89", "quantity": "1", "total": "166.89"}
```

Create `orders` table in the DynamoDB.

We get the AWS access key and secret key from the secrets `AWS_ACCESS_KEY_ID` and `AWS_SECRET_KEY_ID`.

When you produce the message onto SQS queue, the flow will get triggered, and you can see that a corresponding new records gets into the DynamoDB table.

### Tags (optional)

- RealtimeTriggers
