### ISSUE TITLE
Add destination property to the DownloadFiles task and fix validation errors

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3920]
### Describe the issue

The engineering namespace has many scripts stored as namespace files. I want to download them within the marketing namespace:

```yaml
id: get_code_from_engineering
namespace: marketing

tasks:
  - id: download
    type: io.kestra.plugin.core.namespace.DownloadFiles
    namespace: engineering
    # destination: /scripts
    files:
      - "**"
```

Trying to run this flow (example from the docs) throws the following error:

```
Internal server error: HV000030: No validator could be found for constraint ‘jakarta.validation.constraints.NotEmpty’ validating type ‘java.lang.Object’. Check configuration for ‘tasks[0].files’
```

Additionally, adding a `destination` property would be useful — imagine you download scripts from `engineering` namespace, but you want to store them in a specific folder; this currently doesn't seem possible.

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):
