### ISSUE TITLE
Deleting a flow displays a warning that the flow have dependencies even if it didn't have any

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#3922]
### Describe the issue

For example, create this flow that didn't have any dependencies:

```yaml
id: realtime-pubsub-delete
namespace: company.myteam

triggers:
  - id: trigger
    type: io.kestra.plugin.gcp.pubsub.RealtimeTrigger
    projectId: methodical-mesh-238712
    topic: test-topic
    subscription: tes-subscription

tasks:
  - id: log
    type: io.kestra.plugin.core.log.Log
    message: "Received: {{trigger.data | base64decode}}"
```

When you try to delete it from the UI you have the following popup:
![image](https://github.com/kestra-io/kestra/assets/1819009/fa01d6a2-7fda-49e6-bc9d-a2ca41313797)

### Environment

- Kestra Version: 0.18.0-SNAPSHOT
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):
