### ISSUE TITLE
Default inputs not populating in 0.17.0

### ISSUE THREAD

**Issue by paulgrainger85** [kestra-io/kestra#3932]
### Describe the issue

Default inputs are not getting populated. See example flow then screenshot when flow is executed. It is not possible to edit the text box in the UI

```
id: inputs_test
namespace: pgdemo


inputs:
  - id: payload
    type: STRING
    defaults:
      - this is a value

tasks:
  - id: print
    type: io.kestra.plugin.core.log.Log
    message: this is "{{inputs.payload}}"
```

<img width="950" alt="image" src="https://github.com/kestra-io/kestra/assets/10284994/ec180c67-a56e-4f8a-a684-73c3a4acd341">

### Environment

- Kestra Version: 0.17.0
- Operating System: Docker
