### ISSUE TITLE
Option for disabling placeholders from inputFiles

### ISSUE THREAD

**Issue by Tohjuler** [kestra-io/kestra#3937]
### Feature description

A option to disable placeholders from the inputFiles in WorkingDirectory.
Ansible uses the same prefix for placeholder ``{}``,
so when importing the ansible file, it results in a failed workflow.

It could also be resulted by creating a function as ``readPlain``, that can be used as ``read`` but this where the placeholders are not replaced.

**Comment by anna-geller** [comment]
could you provide a reproducer flow that shows the issue when using WorkingDirectory with Ansible? 

There are also some alternative options for storing the Ansible files e.g. you can upload those as Namespace Files and this way you don't need to use the WorkingDirectory task

**Comment by Tohjuler** [comment]
Maybe i have misunderstood something then, because i have uploaded it as namespace files, but used WorkingDirectory to access them, i believed you needed that to access them.

But here is my workflow with the ansible playbook.
[prod_files.zip](https://github.com/user-attachments/files/15614636/prod_files.zip) 
just ask if you need anything else :)

**Comment by anna-geller** [comment]
this should work:

![image](https://github.com/kestra-io/kestra/assets/86264395/f638f5fc-e56c-4702-ba76-c98eec549522)

feel free to close the issue if this works for you 👍 

````yaml
id: Check-Diskspace
namespace: company.myteam
description: "Check if the disk usage is over 80% and if send notfy."

tasks:
  - id: ansible_task
    type: io.kestra.plugin.ansible.cli.AnsibleCLI
    inputFiles:
      inventory.ini: "{{ read('ansible-inventories/Main-Servers.ini') }}"
      playbook.yml: "{{ read('ansible-playbooks/check-diskspace.yml') }}"
      id_rsa: "{{ secret('DEFAULT_KEY') }}"
    namespaceFiles:
      enabled: true
    docker:
      image: cytopia/ansible:latest-tools
      pullPolicy: IF_NOT_PRESENT
      user: "1000"
    commands:
      - ansible-playbook -i inventory.ini --key-file id_rsa --extra-vars "hosts=default" playbook.yml
    env:
      ANSIBLE_HOST_KEY_CHECKING: "False"
      ANSIBLE_REMOTE_USER: "tohjuler"

triggers:
  - id: daily-runner
    type: io.kestra.plugin.core.trigger.Schedule
    cron: 0 1 * * *

errors:
  - id: Ntfy-Error
    type: io.kestra.plugin.core.http.Request
    body: A error happend with the Check-Diskspace workflow.
    method: POST
    uri: <url>

disabled: false
```
