### ISSUE TITLE
Databricks SQL Query broken with 0.17.1

### ISSUE THREAD

**Issue by aucubin** [kestra-io/kestra#3945]
### Describe the issue

Running a simple SQL Query with the databricks plugin is broken with 0.17.1.

![grafik](https://github.com/kestra-io/kestra/assets/17550349/7dcb310c-328f-45d5-943a-2d6e884348be)

I tested it with the following task:
```
tasks:
  - id: sql_query
    type: io.kestra.plugin.databricks.sql.Query
    accessToken: "{{ secret('DATABRICKS_PAT') }}"
    host: "{{ inputs.host }}"
    httpPath: "{{ inputs.httpPath }}"
    sql: SELECT 1
```

The same flow works with 0.16.6.

### Environment

- Kestra Version: 0.17.1
- Operating System (OS/Docker/Kubernetes): Docker and Kubernetes
- Java Version (if you don't run kestra in Docker):
