### ISSUE TITLE
File preview is wrong

### ISSUE THREAD

**Issue by brian-mulier-p** [kestra-io/kestra#3949]
### Describe the issue

So as expected, there was no review done on [this](https://github.com/kestra-io/kestra/pull/3863) before merge and it totally broke the file previews.

See this flow:
```
id: ion_file
namespace: company.myteam
description: Save and Execute the flow

labels:
  env: dev
  project: myproject

tasks:
  - id: wdir
    type: io.kestra.plugin.core.flow.WorkingDirectory
    inputFiles:
      single.ion: |
        "titi"
      multiple.ion: |
        "toto"
        "tutu"
      object.ion: |
        {name: "Bob"}
      objects.ion: |
        {name: "Bob"}
        {name: "Bobby"}
    outputFiles:
      - "*.ion"
    tasks:
      - id: log
        type: io.kestra.plugin.core.log.Log
        message: logging
```

Before your change @MilosPaunovic (so basically string are cut by characters which is not what we want but object previews work:
Single (incorrect)
![image](https://github.com/kestra-io/kestra/assets/37618489/02970165-b04c-4926-85b3-7cd996407eb4)
Multiple (incorrect)
![image](https://github.com/kestra-io/kestra/assets/37618489/8c8db4ea-4e90-414a-958b-36f6e191f216)
object (correct)
![image](https://github.com/kestra-io/kestra/assets/37618489/586f0cef-7711-4b6a-a12f-5084d3dc5342)
objects (correct)
![image](https://github.com/kestra-io/kestra/assets/37618489/52b352e3-36d2-4bb0-991c-8f5d10d2708a)

With your change:
Single (correct)
![image](https://github.com/kestra-io/kestra/assets/37618489/b6ab617e-ed55-4e27-af03-081c7b952acb)
Multiple (incorrect)
![image](https://github.com/kestra-io/kestra/assets/37618489/2ce55328-c4ba-45b1-8c5e-4e21c25c138d)
Object (incorrect)
![image](https://github.com/kestra-io/kestra/assets/37618489/7bdecefa-6aae-4611-97d8-062f10ad9c7a)
Objects (incorrect)
![image](https://github.com/kestra-io/kestra/assets/37618489/10007e4e-a28b-4b16-9922-87af8faa1837)

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):
