### ISSUE TITLE
Kafka plugin appears to be broken in Kestra 0.17.1

### ISSUE THREAD

**Issue by aku** [kestra-io/kestra#3957]
UPD: after a couple of restarts, including a fresh installation, it seems that the issue occurs sporadically
I guess, this issue can be closed unless I make a 100% reproducible test case

<strike>
### Describe the issue

I have a trigger that reads data from a Kafka (Redpanda in my case) topic. In Kestra 0.16.x I was able to pull data successfully.
In Kestra 0.17.x this trigger produces an infinite number of started\completed  events but does not pull any data and does not start a workflow. The only difference with previous version is added consumer group which is now a required parameter. 

I've experimented with several topics (different Kafka installations) and plugin params (interval, etc.) with no luck. Real-time trigger (which was the reason I've upgraded Kestra) works fine (though I can not stop\disable it, which is a pity)
I've updated both Kestra binaries (running in a standalone mode: 1 web server, 1 scheduler, 3 workers, 3 executors across several VMs) and plugins via `plugins install` command

<img width="1059" alt="image" src="https://github.com/kestra-io/kestra/assets/678596/c0fdae95-9fa9-47ad-86bc-84afba5546d7">

Here is my flow:
```yaml
id: test_kafka_transform3
namespace: test

tasks:
  - id: echo
    type: io.kestra.plugin.core.log.Log
    message: "{{ trigger.uri }}"

triggers:
  - id: read_orders_from_kafka
    type: io.kestra.plugin.kafka.Trigger
    keyDeserializer: STRING
    properties:
      bootstrap.servers: <REDACTED>
      sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="<REDACTED>" password="<REDACTED>";
      sasl.mechanism: SCRAM-SHA-256
      security.protocol: SASL_PLAINTEXT
    topic: kestra-orders
    pollDuration: PT5S
    interval: PT10S
    groupId: demo-group
    valueDeserializer: JSON

```

### Environment

- Kestra Version: 0.17.1
- Operating System (OS/Docker/Kubernetes): Ubuntu 12
- Java Version (if you don't run kestra in Docker): Java(TM) SE Runtime Environment (build 22.0.1+8-16)
</strike>
