### ISSUE TITLE
Set the root `/` as default for the destination property in the namespace.UploadFiles task

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3965]
### Feature description

Currently, if you skip the destination, the task will fail:

```yaml
id: upload_from_git
namespace: dev

tasks:
  - id: wdir
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      - id: git
        type: io.kestra.plugin.git.Clone
        url: https://github.com/kestra-io/scripts
        branch: main
  
      - id: upload
        type: io.kestra.plugin.core.namespace.UploadFiles
        namespace: dev
        files: 
          - etl/*
```

Instead, we should set it to root by default `destination: /`. I can recall we discussed this briefly @Skraye, still when using the task, the lack of default here is unintuitive/difficult to understand as a new user.

```yaml
id: upload_from_git
namespace: dev

tasks:
  - id: wdir
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      - id: git
        type: io.kestra.plugin.git.Clone
        url: https://github.com/kestra-io/scripts
        branch: main
  
      - id: upload
        type: io.kestra.plugin.core.namespace.UploadFiles
        namespace: dev
        destination: /
        files: 
          - etl/*
```
