### ISSUE TITLE
Kestra keeps using old revision of a flow

### ISSUE THREAD

**Issue by aku** [kestra-io/kestra#3970]
### Describe the issue

UPDATE: Active revision has been updated after I manually disabled and re-enabled the flow.
If it is intended behaviour please update your documentation or add some warning while editing a flow.
I expected that newly scheduled executions should pick up the latest revision available 

---
I have a flow which I have edited multiple times. The latest revision is 15. However, the system keeps using revision 7.

I had a "Log" task in my flow which I have removed several revisions ago.

<img width="1425" alt="image" src="https://github.com/kestra-io/kestra/assets/678596/4ae47fc0-97c6-4842-b7d8-0aa57aa3ad6a">

 I was surprised to see its output in fresh executions logs

![image](https://github.com/kestra-io/kestra/assets/678596/c24e6e09-875e-4ee3-90b1-111a3feb78a5)

When I checked the execution info I saw that the system keeps using old revision:

![image](https://github.com/kestra-io/kestra/assets/678596/73391777-181f-4965-a8b2-6f93a7dfc7c0)

I've tried to edit my flow one more time (rev 15, added "description" field) but it did not affect the system. Rev 7 is still being scheduled and executed.

Here is my flow:

```yaml
id: trigger_test
namespace: test
description: Test flow

tasks:
- id: transform_orders
  type: io.kestra.plugin.scripts.jython.FileTransform    
  from: "{{ trigger.uri }}"
  concurrent: 4
  script: [REDACTED]

- id: send_to_kafka
  type: io.kestra.plugin.kafka.Produce
  from: "{{ outputs.transform_orders.uri }}"   
  keySerializer: STRING
  valueSerializer: JSON
  properties: [REDACTED]
  topic:  [REDACTED]
  retry:
      type: exponential
      maxAttempt: 3
      interval: PT3S
      maxInterval: PT30S

pluginDefaults:
  - type: io.kestra.plugin.kafka.Trigger
    values:
      logLevel: WARN

triggers:
  - id: read_orders_from_kafka
    type: io.kestra.plugin.kafka.Trigger
    keyDeserializer: STRING
    valueDeserializer: JSON
    interval: PT5S
    topic: [REDACTED]
    groupId: [REDACTED]
    maxRecords: 7000
    properties: [REDACTED]


```

What am I missing here? How can I force the system to use recent revision?

### Environment

- Kestra Version: 0.17.1
- Operating System (OS/Docker/Kubernetes): Ubuntu 12
- Java Version (if you don't run kestra in Docker): jdk22
