### ISSUE TITLE
Secret is not populated as a header value in module io.kestra.plugin.core.http.Request

### ISSUE THREAD

**Issue by SystemFuchs** [kestra-io/kestra#3988]
### Describe the issue

Defined a token for a HTTP API request & wanted to use that token as a secret. I'm only getting an error message "Invalid header". Token is usable for the script as the **print_token** task shows the correct Bearer token. You will get the "Invalid header" error regardless which kind of header you try to populate with the secret. 

![image](https://github.com/kestra-io/kestra/assets/3988026/b6032fb4-a759-4b83-bc8e-ca58ad4f2b99)
![image](https://github.com/kestra-io/kestra/assets/3988026/e12320d1-613a-41a8-a254-a00782359403)

```yaml
id: ntfy_alert
namespace: dev
description: Send notification via ntfy

labels:
  env: dev

inputs:
  - id: title
    type: STRING
    required: true 
    defaults:
  - id: priority
    type: ENUM
    defaults: default
    values:
      - min
      - low
      - default
      - hight
      - urgent
  - id: tags
    type: STRING
    required: false
    defaults: 
  - id: actions
    type: STRING
    required: false
    defaults: "view , Kestra, https://abc.def.de"
  - id: data
    type: STRING
    required: false 
    defaults:

tasks:
  - id: print_token
    type: io.kestra.plugin.scripts.shell.Commands
    commands:
      - echo {{ secret('NTFY_TOKEN') }}
  - id: send_data
    type: io.kestra.plugin.core.http.Request
    uri: "https://abd.def.de/kestra"
    method: POST
    #contentType: application/html
    headers: 
      Authorization: "{{ secret('NTFY_TOKEN') }}"
      Title: "{{ inputs.title }}"
      Priority: "{{ inputs.priority }}"
      Tags: "{{ inputs.tags }}"
      Actions: "{{ inputs.actions }}"
    body: "{{ inputs.data }}"

  - id: print_status
    type: io.kestra.plugin.core.log.Log
    message: hello on {{ outputs.send_data.headers.date | first }}
```
### Environment

- Kestra Version: 0.17.1
- Operating System (OS/Docker/Kubernetes): Linux/Docker Compose
- Java Version (if you don't run kestra in Docker):
