### ISSUE TITLE
outputFiles with nested subdirectories is broken

### ISSUE THREAD

**Issue by kriko** [kestra-io/kestra#3991]
### Describe the issue

If a task generates output that is stored under subfolders and the file name under the subfolders is the same, then Kestra outputFiles mapping results in overlapping mapping which in return generates a situation where you wrong files are addressed.

Confirmed the bug with: v0.17.0, v0.17.1, v0.17.2.

### The result of outputFiles from a sample task:
```
{
    "output/3/output.txt": "kestra:///kestra/test/outputfiles-bug/executions/1y7RswIJBBWAQTtsvGBlT2/tasks/create/28XCfnHMDDgGSNCqVdG2nG/output.txt",
    "output/9/output.txt": "kestra:///kestra/test/outputfiles-bug/executions/1y7RswIJBBWAQTtsvGBlT2/tasks/create/28XCfnHMDDgGSNCqVdG2nG/output.txt",
    "output/4/output.txt": "kestra:///kestra/test/outputfiles-bug/executions/1y7RswIJBBWAQTtsvGBlT2/tasks/create/28XCfnHMDDgGSNCqVdG2nG/output.txt",
    "output/1/output.txt": "kestra:///kestra/test/outputfiles-bug/executions/1y7RswIJBBWAQTtsvGBlT2/tasks/create/28XCfnHMDDgGSNCqVdG2nG/output.txt",
    "output/2/output.txt": "kestra:///kestra/test/outputfiles-bug/executions/1y7RswIJBBWAQTtsvGBlT2/tasks/create/28XCfnHMDDgGSNCqVdG2nG/output.txt",
    "output/0/output.txt": "kestra:///kestra/test/outputfiles-bug/executions/1y7RswIJBBWAQTtsvGBlT2/tasks/create/28XCfnHMDDgGSNCqVdG2nG/output.txt",
    "output/6/output.txt": "kestra:///kestra/test/outputfiles-bug/executions/1y7RswIJBBWAQTtsvGBlT2/tasks/create/28XCfnHMDDgGSNCqVdG2nG/output.txt",
    "output/5/output.txt": "kestra:///kestra/test/outputfiles-bug/executions/1y7RswIJBBWAQTtsvGBlT2/tasks/create/28XCfnHMDDgGSNCqVdG2nG/output.txt",
    "output/7/output.txt": "kestra:///kestra/test/outputfiles-bug/executions/1y7RswIJBBWAQTtsvGBlT2/tasks/create/28XCfnHMDDgGSNCqVdG2nG/output.txt",
    "output/8/output.txt": "kestra:///kestra/test/outputfiles-bug/executions/1y7RswIJBBWAQTtsvGBlT2/tasks/create/28XCfnHMDDgGSNCqVdG2nG/output.txt"
}
```
note that they all point to the same internal storage location.

### a sample flow to illustrate the bug:
```
id: outputfiles_bug
namespace: kestra.test
description: Demonstrate a problem with outputfiles on Kestra 0.17

tasks:
  - id: "create"
    type: io.kestra.plugin.scripts.python.Script
    description: "Generate files with the same name under different subfolders."
    runner: PROCESS
    outputFiles:
      - "output/**"
    script: |
      from kestra import Kestra
      import os

      for i in range(10):
        path = os.path.join("output", str(i))
        os.makedirs(path, exist_ok=True)
        file_path = os.path.join(path, 'output.txt')
        print(f"Saving {i} to {file_path}")
        with open(file_path, 'w') as f:
          f.write(str(i))

  - id: log
    type: io.kestra.plugin.core.log.Log
    description: "Here we will see that different files point to the same internal storage location."
    message: "{{ outputs.create.outputFiles }}"

  - id: each
    type: io.kestra.plugin.core.flow.EachSequential
    value: "{{ outputs.create.outputFiles | keys }}"

    tasks:
      - id: each_log
        type: io.kestra.plugin.core.log.Log
        message: | 
          File: {{ taskrun.value }}
          Internal: {{ outputs.create.outputFiles[taskrun.value] }}
          Content: {{ read(outputs.create.outputFiles[taskrun.value]) }}

```

### Attached the log of flow output
[kestra-execution-20240611104701-1y7RswIJBBWAQTtsvGBlT2.log](https://github.com/user-attachments/files/15784122/kestra-execution-20240611104701-1y7RswIJBBWAQTtsvGBlT2.log)

### Environment

- Kestra Version: v0.17.0, v0.17.1, v0.17.2
- Operating System (OS/Docker/Kubernetes): Kubernetes
