### ISSUE TITLE
containerImage is not taken into account (Shell task runs with the default ubuntu image)

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3997]
flow uses image ghcr.io/kestra-io/ghcli:latest but kestra still runs the task with the default ubuntu image:

![image](https://github.com/kestra-io/kestra/assets/86264395/7969b560-2425-4f40-b14a-fca80c97be02)

```yaml
id: add_to_project
namespace: github

concurrency:
  behavior: QUEUE
  limit: 1

inputs:
  - id: github_url
    type: STRING
    defaults: https://github.com/kestra-io/kestra/issues/3621

variables:
  github_url: "{{ trigger.body.pull_request.html_url ?? trigger.body.issue.html_url ?? inputs.github_url }}"

tasks:
  - id: label
    type: io.kestra.plugin.core.execution.Labels
    labels:
      url: "{{ renderOnce(vars.github_url) }}"

  - id: if
    type: io.kestra.plugin.core.flow.If
    condition: "{{ renderOnce(vars.github_url) contains 'issue' }}"
    then:
      - id: issue
        type: io.kestra.plugin.scripts.shell.Commands
        containerImage: ghcr.io/kestra-io/ghcli:latest
        taskRunner:
          type: io.kestra.plugin.scripts.runner.docker.Docker
        commands:
          - gh project item-add 15 --owner kestra-io --url "{{ renderOnce(vars.github_url) }}"
        env:
          GITHUB_TOKEN: "{{ secret('GITHUB_TOKEN') }}"
    else:
      - id: pr
        type: io.kestra.plugin.scripts.shell.Commands
        containerImage: ghcr.io/kestra-io/ghcli:latest
        taskRunner:
          type: io.kestra.plugin.scripts.runner.docker.Docker
        commands:
          - gh project item-add 16 --owner kestra-io --url "{{ renderOnce(vars.github_url) }}"
        env:
          GITHUB_TOKEN: "{{ secret('GITHUB_TOKEN') }}"

triggers:
  - id: github
    type: io.kestra.plugin.core.trigger.Webhook
    key: xxx
```

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):
