### ISSUE TITLE
Unable to authenticate to private image repo if GetAuthToken is inside working dir

### ISSUE THREAD

**Issue by paulgrainger85** [kestra-io/kestra#4000]
### Describe the issue

If the GetAuthToken task is executed within a working directory, then the subsequent task that authenticates to a private image repo will fail. For example

**this fails**
```yaml
id: ecr_test
namespace: demo
description: check user creds

tasks:
  - id: wdir
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
    - id: auth
      type: io.kestra.plugin.aws.ecr.GetAuthToken
      accessKeyId: "{{secret('AWS_ACCESS_KEY_ID')}}"
      secretKeyId: "{{secret('AWS_SECRET_ACCESS_KEY')}}"
      region: "eu-west-3"
    - id: image_test
      type: io.kestra.plugin.scripts.shell.Commands
      runner: DOCKER
      docker:
        credentials:
          password: "{{outputs.auth.token.value)}}"
          username: AWS
        image: "account_id.dkr.ecr.eu-west-3.amazonaws.com/shell:latest"
  
        pullPolicy: ALWAYS
      commands:
        - echo abc
```

Fails with error message
```log
2024-06-11 16:12:10.306Status 404: {"message":"pull access denied for account_id.dkr.ecr.eu-west-3.amazonaws.com/shell, repository does not exist or may require 'docker login': denied: Your Authorization Token is invalid."}

```

**This works**
```yaml
id: ecr_test
namespace: demo
description: check user creds

tasks:
  - id: auth
    type: io.kestra.plugin.aws.ecr.GetAuthToken
    accessKeyId: "{{secret('AWS_ACCESS_KEY_ID')}}"
    secretKeyId: "{{secret('AWS_SECRET_ACCESS_KEY')}}"
    region: "eu-west-3"
  - id: wdir
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
    - id: image_test
      type: io.kestra.plugin.scripts.shell.Commands
      runner: DOCKER
      docker:
        credentials:
          password: "{{outputs.auth.token.value)}}"
          username: AWS
        image: "account_id.dkr.ecr.eu-west-3.amazonaws.com/shell:latest"
  
        pullPolicy: ALWAYS
      commands:
        - echo abc
```
```

### Environment

- Kestra Version: 0.17.2
- Operating System Docker
