### ISSUE TITLE
`exitCode` does not exist when task fails for `io.kestra.plugin.scripts.shell.Commands`

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#4020]
### Describe the issue

When using `io.kestra.plugin.scripts.shell.Script`, it seems to only give the output exitCode if it succeeds. The example below doesn't generate exitCode so the second task fails.

```yaml
id: exit-codes
namespace: example
tasks: 
  - id: task1 
    type: io.kestra.plugin.scripts.shell.Commands
    commands:  
      - exit 1
    allowFailure: true

  - id: task2 
    type: io.kestra.plugin.core.debug.Return 
    format: "{{ outputs.task1.exitCode }}"
```

`Unable to find exitCode used in the expression {{ outputs.task1.exitCode }} at line 1`

It should return an `exitCode` when it fails and `allowFailure` is set to `true`

Seems to also be an issue for the SSH plugin: https://github.com/kestra-io/kestra/issues/4016

### Environment

- Kestra Version: 0.18 Snapshot

**Comment by anna-geller** [comment]
@loicmathieu is this feasible? if so, how difficult would it be to persist outputs like this one in a failed task with allowFailure? I'm aware we discussed this in the past but I admit I no longer remember what was the decision here 

if not feasible, you can directly close and we can consider clarifying it in the Script docs

**Comment by anna-geller** [comment]
similar request https://github.com/kestra-io/plugin-dbt/issues/112

**Comment by loicmathieu** [comment]
Yes, it's a refactoring that needs to be done on all script and CLI task to: in case of script exception, return the output with the exit code instead of throwing the exception, then set the task to FAIL.

**Comment by johnkm516** [comment]
Scripts and CLI tasks should definitely handle this automatically, but as a temporary workaround for anyone dealing with this you can do something like this : 

```
id: batch-cm-log
namespace: erp.cm

tasks:
  - id: start_batch
    type: io.kestra.plugin.fs.ssh.Command
    commands:
      - cd /app/instances/cm-bat
      - output=$(./springBatch.sh batchStoreDailySales}})
      - exit_code=$?
      - echo $output
      - exit $exit_code
    host: "{{ secret('batch.host') }}"  
    password: "{{ secret('batch.password') }}"
    username: "{{ secret('batch.username') }}"
```

Works with script blocks as well, like this : 

```
     - { echo "Running command 1"; echo "Running command 2"; false; echo "Running command 3"; }
     - exit_code=$?
     - exit $exit_code
```
