### ISSUE TITLE
Unable to use {{ trigger.date }} inside a trigger parameter string 

### ISSUE THREAD

**Issue by LekhaR100** [kestra-io/kestra#4023]
### Describe the issue

I want to set a trigger to ingest a unique url every 15 minutes. I would like one portion of the url to change for each ingestion, depending on the time of the trigger. This portion is formatted as so: 'yyyyMMddHHmm' I cannot use now(), because occasionally it runs a minute late, causing the url portion to end with 16 instead of 15, which does not exist. The ideal solution is to replace {{ now() }} with {{ trigger.date }} so that the url format will always represent a 15 minute interval.

However, I get this error when I attempt to use {{ trigger.date }} instead of {{ now() }}:

"Evaluate Failed with error 'Missing variable: 'date' on '[http://...{{](http://data.gdeltproject.org/gdeltv2/%7B%7B) trigger.date | date('yyyyMMddHHmm') }}00.CSV.zip' at line 1'"

This is a screenshot of my example flow to show how I am using the trigger:
![image](https://github.com/kestra-io/kestra/assets/171082150/9a4114cf-118f-4294-bf29-e1492683e76c)

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by anna-geller** [comment]
hey, unfortunately, you cannot use `trigger.date` within the trigger input because inputs are evaluated first before execution is even created. This means that trigger.date variable doesn't exist at the time when the inputs are evaluated. This is a safety mechanism in kestra to ensure that only executions with valid inputs are created. 

To solve it, you can move the trigger expression into the task:

```yaml  
id: trigger_repro
namespace: company.team

inputs:
  - id: myurl
    type: STRING

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: my file {{ inputs.myurl ?? 'http://' ~ (trigger.date | date('yyyyMMddHHmm')) ~ '00.CSV.zip' }}

triggers:
  - id: pass_date
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "*/1 * * * *"
```
