### ISSUE TITLE
Add ENUM_ARRAY input type

### ISSUE THREAD

**Issue by japerry911** [kestra-io/kestra#4024]
### Feature description

I think a multi-select ENUM list input would be great.

syntax idea from Yann:

```yaml
  - id: new
    type: ENUM_ARRAY
    values:
      - "A"
      - "B"
      - "C"
    defaults:
      - "A"
      - "B"
```

Would it be possible to have it interact nicely with UI execution Input menu as well?

Thanks!

**Comment by Skraye** [comment]
After discussion with Anna, we may go for something like that :
```yml
id: myflow
namespace: company.myteam
description: mark ENUM as deprecated in favor of SELECT type but not remove yet
inputs:
  - id: hey
    type: SELECT
    options:
      - a
      - b
      - c
      - d
    defaults:
      - a

  - id: hey2
    type: MULTISELECT
    options:
      - a
      - b
      - c
      - d
    defaults:
      - a
      - b

```
