### ISSUE TITLE
Add a MinIO plugin replicating S3 plugin's functionality

### ISSUE THREAD

**Issue by aku** [kestra-io/kestra#4029]
### Feature description

Add s3 option for a io.kestra.plugin.fs plugin to be able to upload/download files from/to s3 storages.
Currently, you have AWS S3 plugin but it does not seem to support a custom s3 endpoint

**Comment by anna-geller** [comment]
Can you try the following?
- https://kestra.io/plugins/plugin-aws/tasks/s3/io.kestra.plugin.aws.s3.upload#endpointoverride
- https://kestra.io/plugins/plugin-aws/tasks/s3/io.kestra.plugin.aws.s3.downloads#endpointoverride

This should work, if not, this might be a bug.

**Comment by immutablesemaphore** [comment]
For anyone who comes across this, here is one way that worked with MinIO locally

```yml
- id: upload_to_minio
  type: "io.kestra.plugin.aws.s3.Upload"
  compatibilityMode: true
  bucket: my-bucket
  from: '{{ outputs.someStep.outputFiles["some-file.json"] }}'
  key: "some-file.json"
  accessKeyId: "xxx"
  secretKeyId: "xxx"
  endpointOverride: "http://172.22.0.3:9000"
  region: "eu-west-1"
```
