### ISSUE TITLE
Icon for alias class are not displayed anymore 

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#4030]
Example for a schedule, but all renamed task are affected 

```yaml
triggers:
  - id: schedule
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "* * * * *"
```

![image](https://github.com/kestra-io/kestra/assets/2064609/b77f86b4-9aff-4482-9de9-7f2925e865be)
