### ISSUE TITLE
JSON defaults are not show as json on create execution

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#4033]
```yaml
inputs:
  - id: jobs
    type: JSON
    required: true
    defaults: |
      [
        "fetch_accounts",
        "fetch_ads",
        "fetch_keywords"
      ]
    description: The list of fetch jobs to run.
```

![image](https://github.com/kestra-io/kestra/assets/2064609/4bc8d562-b962-4d2c-a0e9-572b4f1ad66a)
