### ISSUE TITLE
Make it easier to use data stored in ION format in DuckDB

### ISSUE THREAD

**Issue by lburja** [kestra-io/kestra#4038]
### Feature description

When working with Oracle, if I want to copy data from one table to another, I can use a combination of `io.kestra.plugin.jdbc.oracle.Query` and `io.kestra.plugin.jdbc.oracle.Batch`, as shown in the [documentation](https://kestra.io/plugins/plugin-jdbc-oracle/tasks/io.kestra.plugin.jdbc.oracle.batch).

I have a situation, where I would like to copy data from Oracle into DuckDB.

However, DuckDB does not have a task `io.kestra.plugin.jdbc.duckdb.Batch`.
DuckDB can also not import ION files, which Kestra produces.

The solution for now is to query Oracle and store the result as a ION file, then transform to a CSV file, then load the CSV file into DuckDB. With a task `io.kestra.plugin.jdbc.duckdb.Batch`, this could be solved simpler, faster, with less CPU and less storage involved.

In the image below, I have selected from Oracle (duration: 15s) and transformed to CSV (duration: 31s). The CSV transform would not be necessary if I could load the results of `io.kestra.plugin.jdbc.oracle.Query` directly into DuckDB.

<img width="1558" alt="image" src="https://github.com/kestra-io/kestra/assets/459215/a3e64355-9803-475b-8d20-3b52709a6d47">

**Comment by anna-geller** [comment]
Hey, we were planning to contribute an ION extension to DuckDB. It turned out to be more difficult than anticipated. We'll keep investigating and update here once we know more.

**Comment by Ben8t** [comment]
Closed by https://github.com/duckdb/community-extensions/pull/1085

**Comment by Pradumnasaraf** [comment]
Hey, can I get a sample flow to QA this? I tried this flow, but it didn't work

```yaml
id: duck
namespace: dev

tasks:
  - id: get
    type: io.kestra.plugin.fs.http.Download
    uri: https://huggingface.co/datasets/kestra/datasets/blob/main/ion/todos.ion

  - id: query
    type: io.kestra.plugin.jdbc.duckdb.Queries
    store: true
    inputFiles:
      todos.json: "{{ outputs.get.uri }}"
    sql: |
      INSTALL ion;
      LOAD ion;
      SELECT *
      FROM read_ion_auto('{{ workingDir }}/todos.ion');
```

**Comment by Pradumnasaraf** [comment]
Hey @Ben8t, in case you missed the above, comment!

**Comment by Ben8t** [comment]
This looks good:

```yaml
id: quack
namespace: lake

tasks:
  - id: create_and_store_data
    type: io.kestra.plugin.jdbc.duckdb.Queries
    sql: |
      CREATE TABLE my_table (id INTEGER, name VARCHAR);
      INSERT INTO my_table VALUES (1, 'Alice'), (2, 'Bob');
      SELECT * FROM my_table;
    fetchType: STORE
    outputDbFile: true

  - id: select_from_stored_uri
    type: io.kestra.plugin.jdbc.duckdb.Queries
    inputFiles:
      test.ion: "{{ outputs.create_and_store_data.outputs[0].uri }}"
    sql: |
      INSTALL ion FROM community;
      LOAD ion;
      SELECT * FROM read_ion('test.ion');
    fetchType: FETCH
```
