### ISSUE TITLE
feat: add yaml scalars to more properties

### ISSUE THREAD

**Issue by pythoninthegrass** [kestra-io/kestra#4043]
### Feature description

Per [Slack](https://kestra-io.slack.com/archives/C03FEC452NQ/p1718479388522579), a really nice addition would be more allowed [yaml scalars](https://quickref.me/yaml#yaml-reference) at the properties level. Especially for the `io.kestra.plugin.scripts.shell.Commands prop`.

Coming from ansible and taskfile (although the [latter discourages it](https://taskfile.dev/styleguide/#prefer-using-external-scripts-instead-of-multi-line-commands)), it’s a lot more convenient to write tiny shell scripts/code blocks inline vs. attaching a file/script explicitly.

The array workaround is fine for now, but less than ideal.

```yaml
# FAIL
- id: test_secrets
  type: io.kestra.plugin.scripts.shell.Commands
  commands: |
    echo "{{ secret('DOCKERHUB_USERNAME') }}"
    echo "{{ secret('DOCKERHUB_PASSWORD') }}"

# WORKS
- id: test_secrets_shell
  type: io.kestra.plugin.scripts.shell.Commands
  commands:
    - |
      echo "{{ secret('DOCKERHUB_USERNAME') }}"
      echo "{{ secret('DOCKERHUB_PASSWORD') }}"
```

**Comment by anna-geller** [comment]
hey, it's already possible using Shell Script https://kestra.io/plugins/plugin-script-shell/tasks/io.kestra.plugin.scripts.shell.script:

```yaml
id: "script"
type: "io.kestra.plugin.scripts.shell.Script"
script: |
  echo "The current execution is : {{ execution.id }}"
  echo "1" >> {{ outputDir }}/first.txt
  cat {{ outputs.previousTaskId.uri }}
```

if this doesn't address your request, please reopen the issue
