### ISSUE TITLE
Some task logs are not displayed in the UI even though they are captured by the JDBC backend

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4044]
### Describe the issue

When you download logs, you can validate that they are captured on the backend side.

However, the UI doesn't display some of them for tasks with many logs:
![image](https://github.com/kestra-io/kestra/assets/86264395/5974196a-f74e-428c-8232-12ec0ccede21)

### Environment

- Kestra Version: develop 0.18

**Comment by anna-geller** [comment]
reproducer:

```yaml
id: myflow
namespace: company.team

inputs: 
  - id: nr
    type: INT
    defaults: 500

tasks:
  - id: log
    type: io.kestra.plugin.scripts.python.Script
    script: |
      logs = int({{ inputs.nr }}) + 1
      for i in range(1, logs):
          print(f"Generating log messages: {i}")
```
