### ISSUE TITLE
Dynamic Input Defaults (Allow Pebble Templating Language in Inputs)

### ISSUE THREAD

**Issue by japerry911** [kestra-io/kestra#4046]
### Feature description

I think it'd be useful to have Pebble Template Language usable in `Inputs` defaults.

Example:
```yaml
  - id: end_date
    type: STRING
    required: false
    validator: ^\d{4}-\d{2}-\d{2}$
    defaults: "{{ now().format('yyyy-MM-dd') }}"
    description: The end date to fetch data from Google Ads.
```

Let me know your thoughts, thank you 🙏

**Comment by anna-geller** [comment]
mainly needed for setting default dates

Risks: 
1. not easy to create run context at the stage of evaluating inputs and creating an execution 
2. It might be complex for users to understand what is possible to use and what not within dynamically rendered inputs

Possible to use only variables not related to the execution context:
1. Flow variables
3. Namespace variables
4. KV Store (soon)
5. Global env variables `globals.myvar`

@japerry911 as a workaround, you can use a subflow to use execution context from another flow for dynamic rendering

**Comment by japerry911** [comment]
sounds good/will do, thank you @anna-geller !

**Comment by anna-geller** [comment]
sorry Jack, was sharing just raw notes in the meeting. we'll investigate

**Comment by anna-geller** [comment]
Hi @japerry911 , discussed with the team and the best solution for now is to use the approach with a string that you used but without a validator (becuase a validator would validate the expression string rather than a rendered date):

```yaml
id: end_date_demo
namespace: company.team

inputs:
  - id: end_date
    type: STRING
    defaults: "{{ now() | date('yyyy-MM-dd') }}"
    description: The end date to fetch data from Google Ads in the format yyyy-MM-dd e.g. 2024-12-24

tasks:
  - id: print_date
    type: io.kestra.plugin.core.log.Log
    message: hello on {{ render(inputs.end_date) }}
```

I believe once we fix the issue with `null` https://github.com/kestra-io/kestra/issues/4065, the use case shared here will become much easier as you will be able to do e.g.:

```yaml
id: end_date_demo_2
namespace: company.team

inputs:
  - id: end_date
    type: DATE
    defaults: null
    required: false
    description: The end date to fetch data from Google Ads in the format yyyy-MM-dd e.g. 2024-12-24

tasks:
  - id: print_date
    type: io.kestra.plugin.core.log.Log
    message: hello on {{ inputs.end_date ?? now() | date('yyyy-MM-dd') }}
```

for now, the above flow will not create any execution due to the error:

```
At end_date: Invalid input for `end_date`, java.lang.Exception: Expected `DATE` 
but received `Invalid date` with errors: 
``` Text 'Invalid date' could not be parsed at index 0 ```, 
but received `Invalid date`
```

big thanks for flagging this, it's a poor UX atm, we'll tackle this as a high-priority item
