### ISSUE TITLE
Replace ENUM with SELECT

### ISSUE THREAD

**Issue by Skraye** [kestra-io/kestra#4063]
### Feature description

```yaml
id: myflow
namespace: company.myteam
description: mark ENUM as deprecated in favor of SELECT type but not remove yet
inputs:
  - id: hey
    type: SELECT
    options:
      - a
      - b
      - c
      - d
    defaults:
      - a
```
