### ISSUE TITLE
Kafka trigger produces an error:  Worker Evaluate Failed with error 'Cannot invoke "java.util.Optional.map(java.util.function.Function)" because "evaluate" is null'

### ISSUE THREAD

**Issue by aku** [kestra-io/kestra#4067]
### Describe the issue

After I've recreated a flow (i.e. deleted and created a new one with different ID) following errors happen whenever the flow tries to run a kafka trigger:

` Worker Evaluate Failed with error 'Cannot invoke "java.util.Optional.map(java.util.function.Function)" because "evaluate" is null'`

followed by 

```
2024-06-17 22:14:49.532 read_orders_from_kafka null
```

Previously it was running without any troubles.

Here is a trigger:

```
triggers:
  - id: read_orders_from_kafka
    type: io.kestra.plugin.kafka.Trigger
    keyDeserializer: STRING
    valueDeserializer: JSON
    interval: PT5S
    topic:  [REDACTED]
    groupId:  [REDACTED]
    maxRecords: 7000
    properties:
      bootstrap.servers: [REDACTED]
      sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="{{ secret('[REDACTED]') }}" password="{{ secret('[REDACTED]' )}}";
      sasl.mechanism: SCRAM-SHA-256
      security.protocol: SASL_PLAINTEXT
      max.poll.records: 5000
```

### Environment

- Kestra Version: 0.17.2, 0.17.3
- Operating System (OS/Docker/Kubernetes): both
- Java Version (if you don't run kestra in Docker):
