### ISSUE TITLE
Setting namespacedFiles.enabled  to false in io.kestra.plugin.scripts.python.Script task  throws NullPointerException exception

### ISSUE THREAD

**Issue by aku** [kestra-io/kestra#4078]
### Describe the issue

flow:

```yaml
id: python_script_test
namespace: test

# s3://kestra//test/_files/test.py exists

tasks:
  - id: run_script
    type: io.kestra.plugin.scripts.python.Script
    namespaceFiles:
      enabled: false
    script: "{{ read('test.py') }}"
```

Execution error:

```
Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "io.kestra.core.models.tasks.NamespaceFiles.getEnabled()" is null
```

<img width="916" alt="image" src="https://github.com/kestra-io/kestra/assets/678596/ee4a8834-b007-41ac-9f17-bdd7905fb51c">

### Environment

- Kestra Version: 0.17.4
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):
