### ISSUE TITLE
Deprecated error doesn't explain what was replaced for `LocalFiles` and `docker`

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#4084]
### Describe the issue

```yaml
id: pip
namespace: dev
tasks:
  - id: wdir
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
    - id: pip
      type: io.kestra.plugin.core.storage.LocalFiles
      inputs:
        requirements.txt: |
          kestra>=0.6.0
          pandas>=1.3.5
          requests>=2.31.0
    - id: pythonScript
      type: io.kestra.plugin.scripts.python.Script
      docker:
        image: python:3.11-slim
      beforeCommands:
        - pip install -r requirements.txt > /dev/null
      warningOnStdErr: false
      script: |
        import requests
        import kestra
        import pandas as pd
        print(f"requests version: {requests.__version__}")
        print(f"pandas version: {pd.__version__}")
        methods = [i for i in dir(kestra.Kestra) if not i.startswith("_")]
        print(f"Kestra methods: {methods}")
```
Error:
`tasks[0] is deprecated. tasks[1].docker is deprecated.`

Some users have been confused by this and unclear what the solution was. Would be great if we could add `io.kestra.plugin.core.storage.LocalFiles is replaced by `inputFiles` property in `io.kestra.plugin.core.flow.WorkingDirectory`.

and docker error is something like:
`docker is replaced by containerImage`

Good example of an error that doesn't leave users hanging:
`io.kestra.plugin.fs.http.Request is replaced by io.kestra.plugin.core.http.Request`

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):
