### ISSUE TITLE
Issue with Escaping Curly Braces in YAML for Kestra

### ISSUE THREAD

**Issue by n0one42** [kestra-io/kestra#4087]
## Description
I am experiencing an issue where Kestra interprets the double curly braces `{{ }}` in my YAML configuration. I need the string `{{ item }}` to be written exactly as it is in the YAML file without interpretation by Kestra. This string is part of an Ansible playbook that runs inside a Docker container.

## Steps to Reproduce
1. Define a YAML file in Kestra with the following content:
   ```yaml
   inputFiles:
     myplaybook.yml: |
       ---
       - hosts: all
         become: true
         tasks:
           - name: Disable IPv6
             block:
               - name: Insert content into /etc/rc.local if file existed
                 ansible.builtin.lineinfile:
                   path: /etc/rc.local
                   line: '{{ item }}'
                 loop:
                   - 'sysctl -p /etc/sysctl.d/42-disable-ipv6.conf'
                 when: rc_local.stat.exists
   ```

2. Run the Kestra workflow that processes this YAML.

## Expected Behavior
The `{{ item }}` string should be passed as-is to the Ansible playbook.

## Actual Behavior
Kestra interprets the double curly braces and fails with an error:

`Failed preExecuteTasks on WorkingDirectory: Unable to find 'item' used in the expression`

## Additional Context
- I have tried various methods to escape the curly braces, including `{{ "{{ item }}" }}` and `{{"{{ item }}"}}`, but none have worked.
- This issue is critical for integrating Ansible playbooks within Kestra workflows.

## Environment
- Kestra version: 0.17.4

## Possible Solutions
- Provide a way to escape or pass through strings without interpretation in YAML files.
- Documentation update with a clear example of how to handle such cases.

**Comment by loicmathieu** [comment]
Hi,
You should escape your string with the `raw` tag, see https://kestra.io/docs/concepts/expression/tag#raw.
Double curly brace is used by our tempating engine to render expressions.

**Comment by n0one42** [comment]
As I said, I have tried various methods.
```yml
tasks:
  - id: server-init-essentials
    type: io.kestra.plugin.core.flow.WorkingDirectory
    inputFiles:
      inventory.ini: |
        {% for host in vars.hosts %}
        {{ host }} ansible_port=2242
        {% endfor %}
      myplaybook.yml: |
        ---
        - hosts: all
          become: true
          tasks:
            - name: Insert content into /etc/rc.local
              ansible.builtin.lineinfile:
                path: /etc/rc.local
                line: {% raw %}{{ item }}{% endraw %}
              loop:
                - '#!/bin/sh -e'
                - 'sysctl -p /etc/sysctl.d/42-disable-ipv6.conf'
                - 'exit 0'
```

```
2024-06-21 10:24:25.757
Failed preExecuteTasks on WorkingDirectory: Unable to find `item` used in the expression `---
- hosts: all
  become: true
  tasks:
    - name: Insert content into /etc/rc.local
      ansible.builtin.lineinfile:
        path: /etc/rc.local
        line: {{ item }}
      loop:
        - '#!/bin/sh -e'
        - 'sysctl -p /etc/sysctl.d/42-disable-ipv6.conf'
        - 'exit 0'
` at line 8
```

its nice to instantly close the ticket
