### ISSUE TITLE
Fail a flow validation if a Pebble expression contains a `-` in a variable name

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#4090]
### Feature description

When you have a task with a `-` in it, you cannot refer it via its variable name as Pebble use the `-` for substraction, if you do this you will ends up with an error at runtime:

`
io.pebbletemplates.pebble.error.PebbleException: Could not perform subtraction ({{ inputs.server-fqn }}:1)
`

In this case, the subsript notation `{{ inputs[server-fqn] }}` should be used instead.

We should fail the flow validation or at least display a warning in the editor as it is a very common issue.

See this tread in Slack for ex: https://kestra-io.slack.com/archives/C03FQKXRK3K/p1718964532123669

**Comment by hashimzs** [comment]
can you assign this to me @loicmathieu @anna-geller

**Comment by MilosPaunovic** [comment]
Hi @hashimzs,

This issue is already assigned, but if you're willing to contribute, may I suggest that you check our [curated list of good first issues](https://go.kestra.io/contributing) to see if there is something you find interesting enough and think you can tackle independently. It can be further filtered by desired labels to narrow down the results (suggesting to filter by either `area/backend` or `area/frontend` ones, based on your preferences).

**Comment by hashimzs** [comment]
Hi @MilosPaunovic, thanks for the suggestion!

I noticed that the issue has been assigned for over a month without activity—would you be open to reconsidering the assignment and allowing me to take it on? I'd be happy to start working on it right away.

Thanks for considering!

**Comment by MilosPaunovic** [comment]
Hi @hashimzs,

After an internal discussion, we agreed that you can take your shot at it first. I'll assign you and we'll wait for your PR. Thanks for the interest on it! 🚀

**Comment by hashimzs** [comment]
@MilosPaunovic @loicmathieu 
i have created a pr https://github.com/kestra-io/kestra/pull/8379

**Comment by loicmathieu** [comment]
Fixed by https://github.com/kestra-io/kestra/pull/8379

**Comment by ReLoutre** [comment]
Testing on the latest version [i don't see any difference of behavior](https://jam.dev/c/d06f2a64-4ea1-417f-81e4-0dd34aa23de4) as before the merge : 

No pop up nor warns in the UI and still able to save and run such flows (issued error at execution hasn't changed either).
The changes seems to be ignored...

**Comment by MilosPaunovic** [comment]
Hi @loicmathieu, could we get your input here, is everything merged and not working properly or is there something else that needs merging?

**Comment by loicmathieu** [comment]
Preview / Dev env may not be up-to-date at this time.
Checking now on preview I can see the warning and the flow didn't validate.

![Image](https://github.com/user-attachments/assets/2e61bf68-0d70-4299-842e-17eb90313876)

**Comment by ReLoutre** [comment]
While i confirm as well that your examples works well @loicmathieu , it seems that the validation isn't applied over all of the pebbles.

I.E. This flow do not trigger any warnings and may be launched, leading to the classic and expected error that the subtraction wasn't possible.
``` yaml
id: toad_158267
namespace: company.team

tasks:
  - id: previous-task
    type: io.kestra.plugin.core.debug.Return
    format: zoom

  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: "{{ outputs.previous-task }}"
```
Edit : the validation fail if we try to select a value contained in the object :

![Image](https://github.com/user-attachments/assets/f6d6e4f5-8e62-43b1-ac6f-943e070cbc54)

![Image](https://github.com/user-attachments/assets/aebdf51a-9ed8-479e-9724-5df8f8f5b42c)

**Comment by anna-geller** [comment]
that's okay, user should use brackets and quotes if they use the - notation, we recommend camelCase or under_score_notation to avoid such issues

```yaml
id: toad_158267
namespace: company.team

tasks:
  - id: previous-task
    type: io.kestra.plugin.core.debug.Return
    format: zoom

  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: "{{ outputs['previous-task'] }}"
```
