### ISSUE TITLE
io.kestra.plugin.core.flow.WaitFor: incorrect behaviour when using output of previous task

### ISSUE THREAD

**Issue by lburja** [kestra-io/kestra#4092]
### Describe the issue

Given the following flow:

```
id: waitFor-bug
namespace: playground

tasks:
  - id: loop
    type: io.kestra.plugin.core.flow.WaitFor
    condition: "{{ outputs.produce.value == '3' }}"
    tasks:
      - id: produce
        type: io.kestra.plugin.core.debug.Return
        format: "{{ outputs.loop.iterationCount  }}"
        
      - id: consume
        type: io.kestra.plugin.core.log.Log
        message: "{{ outputs.produce.value }}"
```

I would expect that the  'produce' task will produce 1, 2, 3 and the 'consume' task will log 1, 2 3.
In reality, the 'consume' task will log 1, 1, 2.

The practical example that I have is to invoke in a loop an API that supports pagination, and insert each page of results in the database. Due to the bug above, the first page is inserted twice and the last one is missing.

Here is a screenshot:
![image](https://github.com/kestra-io/kestra/assets/459215/e98b82a5-5ba0-45e1-993e-e08c69eb9ea2)

### Environment

- Kestra Version: 0.17.4
- Operating System (OS/Docker/Kubernetes): Kubernetes
- Java Version (if you don't run kestra in Docker): default
