### ISSUE TITLE
Preview PDF files in Outputs Tab

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#4116]
### Describe the issue

Example flow that generates a PDF file in the Outputs tab
```yaml
id: myflow2
namespace: company.myteam

tasks:

  - id: download
    type: io.kestra.plugin.core.http.Download
    uri: https://www.rs600.org/documents/p1h11hsft1125afa11n4m166r1iel3.pdf
```
Instead of previewing the PDF, it shows the raw content:
![Screenshot 2024-06-24 at 12 57 51](https://github.com/kestra-io/kestra/assets/34094921/573c055e-ab7e-43ce-9572-228005cf2e61)

### Environment

- Kestra Version: 0.18 Snapshot
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):
