### ISSUE TITLE
[UI] Add the Inputs/Outputs Preview functionality for PDF files — for now, kestra displays them as binary objects

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4125]
### Feature description

Try running this workflow and providing a PDF file as input:

```yaml
id: myflow
namespace: company.myteam

inputs:
  - id: myfile
    type: FILE
    
tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 
```

You will see the following in the preview:

![image](https://github.com/kestra-io/kestra/assets/86264395/1225cbe2-64cd-4915-aea6-b4759bcaae04)

We should provide a convenient PDF preview instead e.g. with one page and the ability to browse through pages directly in the preview
