### ISSUE TITLE
Add YAML input type

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4126]
We should support use cases like this one that accepts a YAML input (nicely formatted as YAML in the Execute modal):

```yaml
id: vars_this_should_work
namespace: company.myteam

inputs:
  - id: servers
    type: YAML
    defaults:
      - fqn: server01.mydomain
        user: root
      - fqn: server02.mydomain
        user: guest
      - fqn: server03.mydomain
        user: rick

tasks:
  - id: parallel
    type: io.kestra.plugin.core.flow.EachParallel
    value: "{{ inputs.servers }}"
    tasks:
      - id: debugLog
        type: io.kestra.plugin.core.log.Log
        message:
           - "{{ taskrun.value }}" 
           - "{{ json(taskrun.value).fqn }}"
           - "{{ json(taskrun.value).user }}" 
```
