### ISSUE TITLE
[Cooldown issue] Validate the possibility to optionally pass taskrun.value as object instead of JSON

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4127]
### Feature description

e.g. by adding a property `valueAsJson: false` (default: true)

## Example to illustrate this

This works already but requires adding a `json()` function:

```yaml
id: vars1
namespace: company.myteam

inputs:
  - id: servers
    type: JSON
    defaults: |
      [
        {
          "fqn": "docker01.hl443.de",
          "user": "niclas"
        },
        {
          "fqn": "docker02.hl443.de",
          "user": "root"
        },
        {
          "fqn": "docker03.hl443.de",
          "user": "root"
        }
      ]    

tasks:
  - id: parallel
    type: io.kestra.plugin.core.flow.EachParallel
    value: "{{ inputs.servers }}"
    convertToObject
    tasks:
      - id: debugLog
        type: io.kestra.plugin.core.log.Log
        message:
           - "{{ taskrun.value }}" # for each element of the servers list, this will print the full JSON object e.g. {“fqn”:“server01.mydomain.io”,“user”:“root”}
           - "{{ json(taskrun.value).fqn }}" # prints the value for that key e.g. server01.mydomain.io
           - "{{ json(taskrun.value).user }}" # prints the value for that key e.g. root
```

This would be friendlier:

```yaml
id: vars2
namespace: company.myteam

inputs:
  - id: servers
    type: JSON
    defaults: |
      [
        {
          "fqn": "docker01.hl443.de",
          "user": "niclas"
        },
        {
          "fqn": "docker02.hl443.de",
          "user": "root"
        },
        {
          "fqn": "docker03.hl443.de",
          "user": "root"
        }
      ]    

tasks:
  - id: parallel
    type: io.kestra.plugin.core.flow.EachParallel
    value: "{{ inputs.servers }}"
    valueAsJson: false # default set to true to avoid a BC
    tasks:
      - id: debugLog
        type: io.kestra.plugin.core.log.Log
        message:
           - "{{ taskrun.value }}" 
           - "{{ taskrun.value.fqn }}"
           - "{{ taskrun.value.user }}" 
```
