### ISSUE TITLE
[Blocker] Null coalescing operator doesn't work as expected when processing undefined inputs

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4134]
Unexpectedly, this flow doesn't work:

```yaml
id: end_date_demo
namespace: company.team

inputs:
  - id: end_date
    type: DATE
    required: false
    description: The end date to fetch data from Google Ads

tasks:
  - id: print_date
    type: io.kestra.plugin.core.log.Log
    message: hello on {{ inputs.end_date ?? now() | date('yyyy-MM-dd') }}
```

it returns nothing instead of the current date

## Minimal Repro
Already this simple example `{{ null ?? now() | date('yyyy-MM-dd') }}` doesn't return what it should. It returns "undefined"/nothing instead of the current date. 

## Next steps

Change `??` so that:
    `{{ inputs.end_date ?? now() | date('yyyy-MM-dd') }}`
behaves like:
    `{{ inputs.end_date == null ? (now() | date('yyyy-MM-dd')): inputs.end_date }}`

This means, for now we treat undefined and null as the same in the `??` operator, this will also solve https://github.com/kestra-io/kestra/issues/2396 

Additionally, we'll add `???` for use cases where handling undefined properties is required, e.g., when trying to access outputs of a task that wasn't chosen in conditional branching. This is the main use case for the ??? operator, as now in kestra >= 0.17, we treat `undefined` inputs the same way as `null`.

Suggested solution:

```yaml
id: end_date_demo2
namespace: company.team

description: |
    {{ inputs.end_date ?? now() | date('yyyy-MM-dd') }} returns current date, same as {{ inputs.end_date == null ? (now() | date('yyyy-MM-dd')): inputs.end_date }}
    {{ inputs.end_date ??? now() | date('yyyy-MM-dd') }} returns null if no input is provided at runtime
    {{ inputs.wurst ?? now() | date('yyyy-MM-dd') }} returns current date
    {{ inputs.wurst ??? now() | date('yyyy-MM-dd') }} returns current date

inputs:
  - id: end_date
    type: DATE
    required: false
    defaults: null
    description: The end date to fetch data from Google Ads

tasks:
  - id: print_date
    type: io.kestra.plugin.core.log.Log
    message: "hello on {{ inputs.end_date ?? now() | date('yyyy-MM-dd') }}
```
