### ISSUE TITLE
Code sample on https://kestra.io/docs/installation/docker page contains problems

### ISSUE THREAD

**Issue by aku** [kestra-io/kestra#4142]
### Describe the issue

https://kestra.io/docs/installation/docker

```
tasks:
    tmp-dir:
      path: /tmp/kestra-wd/tmp
          url: http://localhost:8080/"
```

double quotes missing from url value, formatting is off 

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):
