### ISSUE TITLE
Bash exemple does not work out of the box

### ISSUE THREAD

**Issue by eregnier** [kestra-io/kestra#417]
https://github.com/kestra-io/kestra/blob/a9ab424843ade3ab61b4165c0dc14d025401a1cc/core/src/main/java/io/kestra/core/tasks/scripts/Bash.java#L36

I guess kestra.io exemple is generated from here. it does not work "as it"

```yaml
id: "bash"
type: "io.kestra.core.tasks.scripts.Bash"
commands:
- echo "The current execution is : {{execution.id}}"
```
https://kestra.io/plugins/core/tasks/scripts/io.kestra.core.tasks.scripts.Bash.html#examples

but I don't remember / know what works today to do the appropriate PR

![image](https://user-images.githubusercontent.com/5399780/146079192-08e18e34-699b-447d-82bc-35cc1af8d65e.png)
