### ISSUE TITLE
Upgrading kestra from 17.5 to 17.8 breaks triggered flows executions

### ISSUE THREAD

**Issue by aku** [kestra-io/kestra#4195]
### Describe the issue

UPD: I've went back to 17.8 and the problem has disappeared.  

I guess it would be nice to introduce some sort of compatibility checks between Kestra and plugins versions.
Also, the system should report some compatibility issues during startup when upgrading/downgrading 

---

UPD: the same problem happens after I went back to 17.5 version. this time it is a cron-based trigger

I have a couple of flows with kafka triggers and clickhouse triggers

e.g.:
```
triggers:
  - id: read_orders_from_kafka
    type: io.kestra.plugin.kafka.Trigger
    keyDeserializer: STRING
    valueDeserializer: JSON
    interval: PT5S
    topic: [TOPIC]
    groupId: [GROUP]
    maxRecords: 7000
    properties:
      bootstrap.servers: [REDACTED]
      sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="{{ secret('[REDACTED]') }}" password="{{ secret('[REDACTED]' )}}";
      sasl.mechanism: SCRAM-SHA-256
      security.protocol: SASL_PLAINTEXT
      auto.offset.reset: latest
      max.poll.records: 5000

```

Flows were running smoothly with kestra 17.4 and 17.5
Once I've updated to 17.8 following problem has happened:

A flow creates a new execution that stucks in "CREATED" state.
If I click on the execution id in a global Executions tab or from the flow's Execution tab a message with "execution not found" pops up. However I can delete it by checking a box near to the execution id and clicking on DELETE button.

Also, I've checked that execution's data is available in S3 storage.

<img width="1139" alt="image" src="https://github.com/kestra-io/kestra/assets/678596/1be50a87-394e-48c3-b97a-6a3b2e2bb8c3">

<img width="796" alt="image" src="https://github.com/kestra-io/kestra/assets/678596/64d87014-513f-47c9-80cc-8342ee652eae">

<img width="651" alt="image" src="https://github.com/kestra-io/kestra/assets/678596/2e83e986-0857-4563-8e3d-207e328dbdbb">

I had to downgrade back to 17.5 to make the flows running again. In 17.8 triggered executions stuck in CREATED state 

### Environment

- Kestra Version: 0.17.8
- Operating System (OS/Docker/Kubernetes): standalone binarie
- Java Version (if you don't run kestra in Docker):
