### ISSUE TITLE
A flow with realtime kafka trigger throws an exception 

### ISSUE THREAD

**Issue by aku** [kestra-io/kestra#4196]
### Describe the issue

I've noticed that one of my flows has started producing weird issues:

Real time trigger throws an exception. Flow does not create new execution.s

<img width="1506" alt="image" src="https://github.com/kestra-io/kestra/assets/678596/a8a48839-494e-4806-9193-4f0d077da386">

The issue has started after I did some upgrades/downgrades of my Kestra installation (went from 17.4 to 17.8 then back to 17.5) Also, I'm using an unreleased minio plugin storage-minio-0.17.1 created by Brian to mitigate Ceph compatibility problem

Here is my flow:

```
tasks:
  - id: echo
    type: io.kestra.plugin.core.log.Log
    message: "{{ trigger.value }}"

  - id: if_large
    type: io.kestra.plugin.core.flow.If
    condition: "{{ trigger.value.total_nm | default(0) >= 15 }}"
    then:
      - id: notify_via_telegram
        type: io.kestra.plugin.notifications.telegram.TelegramSend
        channel: [REDACTED]
        token: "{{ secret('[REDACTED]') }}"
        payload: |
          [REDACTED] {{ trigger.value.total_nm }} [REDACTED]


triggers:
  - id: read_orders_from_kafka
    type: io.kestra.plugin.kafka.RealtimeTrigger
    keyDeserializer: STRING
    valueDeserializer: JSON
    topic: [REDACTED]
    groupId: [REDACTED]
    properties:
      bootstrap.servers:[REDACTED]
      sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="{{ secret('[REDACTED]') }}" password="{{ secret('[REDACTED]') }}";
      sasl.mechanism: SCRAM-SHA-256
      security.protocol: SASL_PLAINTEXT
```

Any ideas on how to debug this?

### Environment

- Kestra Version: 17.5
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):
