### ISSUE TITLE
containerImage don't have any impact without providing taskRunner

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#4200]
When `taskRunner` is configured by `pluginDefaults`: 
```yaml
      tasks:
        defaults:
        - type: io.kestra.plugin.scripts.
          forced: true
          values:
            runner: "DOCKER"
```

using this flow: 
```yaml
    - id: python
      type: io.kestra.plugin.scripts.python.Script
      allowFailure: true
      containerImage: python:latest
      beforeCommands:
        - "pip install requests"
      script: | 
        import requests
        import socket
        print(socket.gethostname())

        response = requests.get('https://api.github.com/')
        print(response)
```

changing the `containerImage` has no effect, and the default image will be taken all the time 

Adding the `taskRunner` will make the `containerImage` works
```yaml
    - id: python
      type: io.kestra.plugin.scripts.python.Script
      containerImage: python:latest
      taskRunner: 
        type: io.kestra.plugin.scripts.runner.docker.Docker
```
