### ISSUE TITLE
Suppressing logs via pluginDefaults does not prevent a task from being marked as Warning

### ISSUE THREAD

**Issue by aku** [kestra-io/kestra#4201]
### Describe the issue

Due to this issue https://github.com/kestra-io/kestra/issues/4197 I have modified log level using pluginDefaults:

```
pluginDefaults:
  - type: "io.kestra.plugin.scripts.python.Script"
    values:
      logLevel: ERROR
```      

However, the task itself is still marked as (Warning). Probably it works as intended, however such behaviour makes it hard to understand what is going on since there are no logs explaining why this task is marked with Warning.

Consider improving it by introducing an option to ignore warnings (i.e. do not mark task) on a task level or align/sync it with pluginDefaults / logLevel behaviour. I.e. if logLevel is ERROR then the task should be marker as (Warning)

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):
