### ISSUE TITLE
All executions need to be killed and dont terminate.

### ISSUE THREAD

**Issue by Jds5nz** [kestra-io/kestra#4202]
### Describe the issue

I am running Kestra 0.17.8 (and tested many 0.17.x versions before that) and some test flows I have created never terminate and always require to be killed.

I have created a powershell flow to output some text. The execution INFO log shows the output as expected, however the execution never terminates. The execution still appears to be running, but I am left with stopped ghcr.io/kestra-io/powershell containers afterwards. 
So it appears to be running the flow, but not terminating. 

Example:

```
id: powershell_hello_world
namespace: dev

variables:
  myvar: myname
  type: STRING

tasks:
  - id: powershell_script
    type: io.kestra.plugin.scripts.powershell.Commands
    inputFiles:
      main.ps1: |
        'Hello, World {{ vars.myvar }} !' | Write-Output
    commands:
      - ./main.ps1
```

INFO Log:
```
2024-07-02T05:56:09.747Z INFO Provided 1 input(s).
2024-07-02T05:56:11.019Z DEBUG Image pulled [ghcr.io/kestra-io/powershell:latest]
2024-07-02T05:56:11.503Z DEBUG Starting command with container id c2847eb288151bae8470e3e5c0449e89d4b196ad430ea12885f52318321c1863 [pwsh -NoProfile -NonInteractive -Command $ErrorActionPreference = "Stop"
./main.ps1]
2024-07-02T05:56:11.986Z INFO Hello, World myname !
```

However in the GUI the execution is still running, even 10mins after the log entries. 

I use the Synology NAS DSM built in Container Manager app, and I have created a /tmp/kestra-wd on the host.
That reports it has Docker version 20.10.23, build 876964a installed.

### Environment

- Kestra Version: 0.17.8 as Docker
- Operating System (OS/Docker/Kubernetes): Synology DSM 7.2.1-69057 Update 5, running Docker version 20.10.23, build 876964a
- Java Version (if you don't run kestra in Docker): Docker.

**Comment by smunteankestra** [comment]
not reproducing , kestra EE postgress 
<img width="1608" alt="image" src="https://github.com/kestra-io/kestra/assets/171780240/cc918e85-cf33-48e0-9382-596ce85d13c8">

**Comment by gregtap** [comment]
I am seeing a similar issue where the local containers are terminated and exited (exit 0) but the UI continues to show it as running for a few minutes. 

docker-compose, single node.

**Comment by Ben8t** [comment]
What's your Kestra version?

**Comment by gregtap** [comment]
> What's your Kestra version?

Latest 0.22

here is the docker compose part.


```
  kestra:
    image: kestra/kestra:v0.22.0
    user: "root"
    command: server standalone --worker-thread=128
    volumes:
      - kestra_data:/app/storage
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/foobar/kestra_working_directory:/tmp/kestra-wd
      - /home/foobar/docker-config:/root/.docker
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - private
      - public
    env_file:
      - kestra.env
    environment:
      KESTRA_DEMO_FLOWS_ENABLED: "false"
      KESTRA_CONFIGURATION: |-
        datasources:
          postgres:
            url: jdbc:postgresql://xxxxxxx:5432/kestra
            driverClassName: org.postgresql.Driver
            username: kestra
            password: ${KESTRA_DB_PASSWORD}
        kestra:
          repository:
            type: postgres
            execution:
              purge:
                enabled: true
                interval: PT1H
                delay: P7D
                maxAge: P30D
                status:
                  - SUCCESS
          queue:
            type: postgres
          storage:
            type: local
            local:
              basePath: /app/storage
          url: http://localhost:8080/
          demo:
            flows:
              enabled: false
          plugins:
            configurations:
              - type: io.kestra.plugin.scripts.runner.docker.Docker
                values:
                  volume-enabled: true
        micronaut:
          server:
            netty:
              max-initial-line-length: 16384
              max-header-size: 32768
    labels:
      - "group=system"
    deploy:
      resources:
        limits:
          cpus: '10.0'
          memory: 32G
```

Task example

```
...
concurrency:
  limit: 1
 
    # Run dbt deps and model
    - id: run_dbt_deps_and_model
      type: io.kestra.plugin.dbt.cli.DbtCLI # Assumes standard dbt plugin type
      taskRunner:
        type: io.kestra.plugin.scripts.runner.docker.Docker
        cpu:
          cpus: 60
        memory:
          memory: "32GB"
        volumes:
          - /tmp/kestra-wd:/tmp/kestra-wd
      containerImage: ghcr.io/kestra-io/dbt-duckdb:latest

      # Specifies the directory containing dbt_project.yml relative to the WorkingDirectory root
      projectDir: fiibar/data/dbt_jobs

      commands:
        # ....
 
```

Container terminated 3 min ago.

![Image](https://github.com/user-attachments/assets/e4474145-23e0-4ef4-bc26-59d7bbe436c3)


UI is still running.

![Image](https://github.com/user-attachments/assets/198cc862-3251-4638-9a42-33943dcb7529)
