### ISSUE TITLE
Add ability to clean executions automatically

### ISSUE THREAD

**Issue by aku** [kestra-io/kestra#4206]
### Feature description

I know there are Purge and PurgeExecution tasks available, however, it would be very useful to be able to specify TTL of executions somewhere in the workflow. I've faced with a problem running multiple kafka-based workflows that produce gigabytes of intermediate data. It would be so much easier for me to set something like this on a flow-level:

```
id: flowId
namespace: nsId

autoCleanup: 
  interval: PT48H # clean executions every 48 hrs or clean executions that are 48 hrs old
  states: # clean executions only in certain states
    - SUCCESS
```

In my experience, I rarely need to access data of old executions. If I need to persist some data I would rather put it in a separate storage. Currently, I have to create separate flows with Purge + Cron Trigger for each use-case. Also, I've faced with multiple problems using Purge task (logs and executions are not cleaned properly)
