### ISSUE TITLE
Add a task allowing to purge outputs from the current execution by IDs

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4207]
## Context 
There are many use cases in which user may want to pass output to downstream tasks without the need to keep it afterward due to:
- large files
- entire database backups
- sensitive outputs 

For example, imagine that you extract a large dataset from a given source, and then you load it to a destination such as BigQuery. Once data has been successfully stored in BigQuery, there's no need to keep it in internal storage. We currently support a Purge task, but it will delete all outputs — you can't cherry-pick only specific ones. However, sometimes you want to keep all outputs but only purge a single large/sensitive output.

It would be great to add a task that allows to delete only specific outputs by ID.

## Proposed syntax

```yaml
  - id: clean
    type: io.kestra.plugin.core.storage.PurgeOutputs
    outputs: 
      - "{{ outputs.extract.uri }}"
```

## Example usage in a flow

```yaml
id: purge_outputs
namespace: company.myteam
tasks:
  - id: extract
    type: io.kestra.plugin.core.http.Download
    description: imagine this is a huuuuuge file that doesn't need to be kept in internal storage after it has been loaded to BigQuery
    uri: https://huggingface.co/datasets/kestra/datasets/blob/main/csv/orders.csv

  - id: load
    type: io.kestra.plugin.gcp.bigquery.Load
    from: "{{ outputs.extract.uri }}"
    destinationTable: "my_project.my_dataset.my_table"
    format: CSV
    csvOptions:
      fieldDelimiter: ";"

  - id: clean
    type: io.kestra.plugin.core.storage.PurgeOutputs
    outputs: 
      - "{{ outputs.extract.uri }}"
```
