### ISSUE TITLE
Display the CRON schedule in a human-readable format (worst case using AI)

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4211]
### Feature description

When business users hover over a Schedule trigger, it would be great to display a human-readable explanation of the trigger, e.g. this trigger should show something like "Every first day of the month at 9:00 AM UTC":

```yaml
triggers:
  - id: monthly
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 9 1 * *"
```

If there is some native way to do that in Java, this would be preferable. 

If not, we can add it as an EE feature and use an LLM prompt to explain the Schedule trigger — when using AI, we can additionally explain complex schedules with complex conditions in a single sentence e.g.:  "Every workday at 9:00 AM and every weekend at 8:00 PM."

```yaml
triggers:
  - id: workday
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 9 * * *"
    scheduleConditions:
      - type: io.kestra.plugin.core.condition.NotCondition
        conditions:
          - type: io.kestra.plugin.core.condition.WeekendCondition
  - id: weekend
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 20 * * *"
    scheduleConditions:
      - type: io.kestra.plugin.core.condition.WeekendCondition
    inputs:
      beverage: beer
```
