### ISSUE TITLE
DbtCLI throws git error

### ISSUE THREAD

**Issue by paulgrainger85** [kestra-io/kestra#4213]
### Describe the issue

```
id: dbt
namespace: company.myteam
description: Save and Execute the flow

tasks:
  - id: dbt
    type: io.kestra.plugin.dbt.cli.DbtCLI
    commands:
      - dbt debug
 ```

This returns an error 
```
Error from git --help: Could not find command, ensure it is in the user's PATH: "git"
```

Is this expected? 

```

### Environment

- Kestra Version: 0.17.8
- Operating System Docker

**Comment by anna-geller** [comment]
We don't include Git in the default Docker image for security reasons.

To use `dbt debug`, you need to install git as a dependency e.g. using `beforeCommands`:

```yaml
      beforeCommands:
        - apt-get update && apt-get install -y git && apt-get clean
```

full flow:

```yaml
id: dwh_and_analytics
namespace: tutorial
description: Data Warehouse and Analytics

tasks:
  - id: dbt
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
    - id: clone_repository
      type: io.kestra.plugin.git.Clone
      url: https://github.com/kestra-io/dbt-demo
      branch: main

    - id: dbt_build
      type: io.kestra.plugin.dbt.cli.DbtCLI
      taskRunner:
        type: io.kestra.plugin.scripts.runner.docker.Docker
      containerImage: ghcr.io/kestra-io/dbt-duckdb:latest
      beforeCommands:
        - apt-get update && apt-get install -y git && apt-get clean
      commands:
        - dbt debug
      profiles: |
        jaffle_shop:
          outputs:
            dev:
              type: duckdb
              path: dbt.duckdb
              extensions: 
                - parquet
              fixed_retries: 1
              threads: 16
              timeout_seconds: 300
          target: dev      
```

you can also build a custom image and add git within the image before/after installing dbt:
```Dockerfile
FROM python:3.11-slim

RUN apt-get update && apt-get install -y git && apt-get clean
```
