### ISSUE TITLE
Unable to save flows with queue based triggers

### ISSUE THREAD

**Issue by shrutimantri** [kestra-io/kestra#4236]
### Describe the issue

I am trying to create flows with GCP Pubsub / AWS SQS trigger. I am getting `Invalid type` error when I try to save the flow.

![Screenshot 2024-07-05 at 9 59 12 AM](https://github.com/kestra-io/kestra/assets/6594483/4dbef2ea-c591-49dc-9c34-be66a1c2b7d3)

![Screenshot 2024-07-05 at 10 00 37 AM](https://github.com/kestra-io/kestra/assets/6594483/e2d94fc3-0f8e-4f59-8f53-20f86bb578cd)

Example flows:

```
id: myflow
namespace: company.myteam
tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: 
      - Hello World! 🚀
      - Kestra team wishes you a great day 👋

triggers:
  - id: "pubsub_trigger"
    type: io.kestra.plugin.gcp.pubsub.Trigger
    projectId: shruti-project-425403
    serviceAccount: "{{ secret('GCP_SERVICE_ACCOUNT_JSON') }}"
    subscription: smnatri-test-sub
    topic: smnatri-test
    maxRecords: 2
```

```
id: myflow
namespace: company.myteam
tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: 
      - Hello World! 🚀
      - Kestra team wishes you a great day 👋

triggers:
  - id: "trigger"
    type: "io.kestra.plugin.aws.sqs.Trigger"
    accessKeyId: "<access-key>"
    secretKeyId: "<secret-key>"
    region: "eu-central-1"
    queueUrl: "https://sqs.eu-central-1.amazonaws.com/000000000000/test-queue"
    maxRecords: 10
```

### Environment

- Kestra Version: 0.17.8
- Operating System (OS/Docker/Kubernetes): Docker
- Java Version (if you don't run kestra in Docker):
