### ISSUE TITLE
Create a GitHub plugin with a task to open an issue when a workflow fails

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4239]
### Feature description

Use case: when flow fails, create an issue (as part of `errors` task)

```yaml
id: myflow
namespace: company.myteam

tasks:
  - id: hello
    type: io.kestra.plugin.github.issues.Create
    token: your_github_token
    repository: kestra-io/kestra
    issueTitle: Workflow failed
    issueBody: "{{ execution.id }} has failed on {{ taskrun.startDate }}. See the link below for more details"
    issueLabels:
      - bug
      - workflow
```

Python equivalent:

```Python
import requests

GITHUB_TOKEN = 'your_github_token'
REPO_OWNER = 'repository_owner'
REPO_NAME = 'repository_name'
ISSUE_TITLE = 'Issue Title'
ISSUE_BODY = 'Description of the issue.'
ISSUE_LABELS = ['bug', 'enhancement']  

url = f'https://api.github.com/repos/{REPO_OWNER}/{REPO_NAME}/issues'

headers = {
    'Authorization': f'token {GITHUB_TOKEN}',
    'Accept': 'application/vnd.github.v3+json'
}

payload = {
    'title': ISSUE_TITLE,
    'body': ISSUE_BODY,
    'labels': ISSUE_LABELS
}

response = requests.post(url, headers=headers, json=payload)

if response.status_code == 201:
    print('Issue created successfully.')
    print('Issue URL:', response.json()['html_url'])
else:
    print('Failed to create issue.')
    print('Response:', response.json())
```
