### ISSUE TITLE
Create a Jira plugin with a task to open a ticket when a workflow fails

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4240]
### Feature description

Use case: when flow fails, create an issue (e.g. as part of the `errors` task)

```yaml
id: myflow
namespace: company.myteam

tasks:
  - id: hello
    type: io.kestra.plugin.jira.issues.Create
    jiraDomain: your-domain.atlassian.net
    jiraEmail: your_email@example.com
    projectKey: myproject
    issueTitle: Workflow failed
    issueSummary: "{{ execution.id }} has failed on {{ taskrun.startDate }}"
    issueDescription: "See the link below for more details"
    issueLabels:
      - bug
      - workflow
```

Python equivalent:

```Python
import requests
from requests.auth import HTTPBasicAuth
import json

JIRA_DOMAIN = 'your_jira_domain'  
JIRA_EMAIL = 'your_email@example.com'
JIRA_API_TOKEN = 'your_api_token'
PROJECT_KEY = 'PROJ'  
ISSUE_SUMMARY = 'Issue Summary'
ISSUE_DESCRIPTION = 'Description of the issue.'
ISSUE_LABELS = ['bug', 'enhancement'] 

url = f'https://{JIRA_DOMAIN}/rest/api/2/issue'

headers = {
    'Accept': 'application/json',
    'Content-Type': 'application/json'
}

payload = json.dumps({
    'fields': {
        'project': {
            'key': PROJECT_KEY
        },
        'summary': ISSUE_SUMMARY,
        'description': ISSUE_DESCRIPTION,
        'issuetype': {
            'name': 'Task'  # Or 'Bug', 'Story', etc.
        },
        'labels': ISSUE_LABELS
    }
})

auth = HTTPBasicAuth(JIRA_EMAIL, JIRA_API_TOKEN)

response = requests.post(url, headers=headers, data=payload, auth=auth)

if response.status_code == 201:
    print('Issue created successfully.')
    print('Issue URL:', f'https://{JIRA_DOMAIN}/browse/{response.json()["key"]}')
else:
    print('Failed to create issue.')
    print('Response:', response.json())
```
