### ISSUE TITLE
Create a Zendesk plugin with a task to open a ticket when a workflow fails

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4241]
### Feature description

```yaml
id: myflow
namespace: company.myteam

tasks:
  - id: hello
    type: io.kestra.plugin.zendesk.tickets.Create
    domain: yourcompany.zendesk.com
    email: your_email@example.com
    token: your_zendesk_api_token
    subject: Workflow failed
    description: |
      "{{ execution.id }} has failed on {{ taskrun.startDate }}. 
      See the link below for more details."
    priority: normal  # Options: 'urgent', 'high', 'normal', 'low'
    ticketType: incident # Options: 'question', 'incident', 'problem', 'task'
    tags:
      - bug
      - workflow
```

Python equivalent to see how the API works:

```Python
import requests
import json

# Replace these variables with your own values
ZENDESK_DOMAIN = 'your_zendesk_domain'  # e.g., yourcompany.zendesk.com
ZENDESK_EMAIL = 'your_email@example.com/token'
ZENDESK_API_TOKEN = 'your_api_token'
TICKET_SUBJECT = 'Subject of the ticket'
TICKET_DESCRIPTION = 'Description of the issue.'
TICKET_PRIORITY = 'normal'  # Options: 'urgent', 'high', 'normal', 'low'
TICKET_TYPE = 'problem'  # Options: 'question', 'incident', 'problem', 'task'
TICKET_TAGS = ['bug', 'api']  # List of tags to assign to the ticket

url = f'https://{ZENDESK_DOMAIN}/api/v2/tickets.json'

headers = {
    'Content-Type': 'application/json'
}

payload = {
    'ticket': {
        'subject': TICKET_SUBJECT,
        'description': TICKET_DESCRIPTION,
        'priority': TICKET_PRIORITY,
        'type': TICKET_TYPE,
        'tags': TICKET_TAGS
    }
}

response = requests.post(
    url,
    headers=headers,
    auth=(ZENDESK_EMAIL, ZENDESK_API_TOKEN),
    data=json.dumps(payload)
)

if response.status_code == 201:
    print('Ticket created successfully.')
    print('Ticket URL:', f"https://{ZENDESK_DOMAIN}/agent/tickets/{response.json()['ticket']['id']}")
else:
    print('Failed to create ticket.')
    print('Response:', response.json())
```
