### ISSUE TITLE
Create a Linear plugin with a task to open an issue when a workflow fails

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4243]
### Feature description

```yaml
id: myflow
namespace: company.myteam

tasks:
  - id: linear
    type: io.kestra.plugin.linear.issues.Create
    token: your_api_token
    teamId: the ID of the team where you want to create the issue
    issueTitle: Workflow failed
    issueDescription: "{{ execution.id }} has failed on {{ taskrun.startDate }}. See the link below for more details"
    issueLabels:
      - bug
      - workflow
```

Python equivalent to show how their GraphQL API works https://developers.linear.app/docs/graphql/working-with-the-graphql-api:

```Python
import requests
import json

# Replace these variables with your own values
LINEAR_API_TOKEN = 'your_api_token'
TEAM_ID = 'your_team_id'  # The ID of the team where you want to create the issue
ISSUE_TITLE = 'Title of the issue'
ISSUE_DESCRIPTION = 'Description of the issue'
ISSUE_LABELS = ['bug', 'api']  # List of labels to assign to the issue

url = 'https://api.linear.app/graphql'

headers = {
    'Authorization': f'Bearer {LINEAR_API_TOKEN}',
    'Content-Type': 'application/json'
}

# GraphQL mutation to create an issue
query = '''
mutation CreateIssue($teamId: String!, $title: String!, $description: String!, $labelIds: [String!]) {
    issueCreate(input: {
        teamId: $teamId,
        title: $title,
        description: $description,
        labelIds: $labelIds
    }) {
        success
        issue {
            id
            url
        }
    }
}
'''

# Fetching label IDs from Linear
label_query = '''
query {
    labels {
        nodes {
            id
            name
        }
    }
}
'''

response = requests.post(url, headers=headers, json={'query': label_query})
label_data = response.json()
if response.status_code == 200:
    label_dict = {label['name']: label['id'] for label in label_data['data']['labels']['nodes']}
    label_ids = [label_dict[label] for label in ISSUE_LABELS if label in label_dict]
else:
    print('Failed to fetch labels.')
    print('Response:', label_data)
    label_ids = []

variables = {
    'teamId': TEAM_ID,
    'title': ISSUE_TITLE,
    'description': ISSUE_DESCRIPTION,
    'labelIds': label_ids
}

payload = {
    'query': query,
    'variables': variables
}

response = requests.post(url, headers=headers, json=payload)

if response.status_code == 200 and response.json()['data']['issueCreate']['success']:
    issue = response.json()['data']['issueCreate']['issue']
    print('Issue created successfully.')
    print('Issue URL:', issue['url'])
else:
    print('Failed to create issue.')
    print('Response:', response.json())
```
