### ISSUE TITLE
Create a Hubspot plugin with a task to open a ticket when a workflow fails

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4244]
### Feature description

```yaml
id: myflow
namespace: company.myteam

tasks:
  - id: hubspot
    type: io.kestra.plugin.hubspot.tickets.Create
    apiKey: your_hubspot_api_key
    subject: Workflow failed
    content: "Execution {{ execution.id }} has failed on {{ taskrun.startDate }}. See the link below for more details."
    hsPipeline: 123 # optional
    hsPipelineStage: 1 # optional
```

Docs: https://developers.hubspot.com/docs/api/crm/tickets

Python example showing how the API works:

```Python
import requests

# Replace with your own values
api_key = 'your_hubspot_api_key'
ticket_data = {
    "properties": {
        "subject": "Test Ticket",
        "content": "This is a test ticket created via the API"
    }
}

url = f'https://api.hubapi.com/crm/v3/objects/tickets?hapikey={api_key}'

headers = {
    'Content-Type': 'application/json'
}

response = requests.post(url, headers=headers, json=ticket_data)

if response.status_code == 201:
    print('Ticket created successfully.')
else:
    print('Failed to create ticket:', response.json())
```
