### ISSUE TITLE
Introduce task templates to reduce code duplication in a flow

### ISSUE THREAD

**Issue by aku** [kestra-io/kestra#4248]
### Feature description

There is a lot of cases when I need to reuse some task with different input parameters or configs.
Currently, we have plugin/task defaults and subflows. They do not solve the problem completely, 'cause you need to specify custom data for each instance of a task. Subflows lead to code fragmentation and unnecessary flows\executions that clutter the system and make it harder to maintain/debug. Also, you might have a case when there are task instances that should not have the same default values. I.e. 3 tasks with similar type where 2 tasks share some config and the 3rd task has different inputs

Imagine a simple scenario where you have IF-ELSE branches and each branch should run the same task with different params. Currently, you have to either duplicate the whole task definition or opt for separate subflow 

What I propose is task templates. Something that can be defined on a flow level and reused across the flow:

```
templates:

  - id: task_template_id
    params:
        - id: someParam
          type: STRING
    spec:     
       type: ....SomePlugin.SomeTask
       someField: "{{ params.someParam }}"
       anotherField: "some predefined value"
    
tasks:

   - id: some_task
     type: ...core.TaskTemplate
     templateId: task_template_id
     params:
         - someParam: "some value"   
         
         
   - id: another_task
     type: ...core.TaskTemplate
     templateId: task_template_id
     anotherField: "..." # overrides property in template
     params:
         - someParam: "another value" 
         
         
```         

Related issue https://github.com/kestra-io/kestra/issues/4229

Thread on Slack: https://kestra-io.slack.com/archives/C03FQKXRK3K/p1720099330988929
