### ISSUE TITLE
The Executions endpoint should return a URL allowing to follow the Execution progress from the UI

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4256]
### Feature description

Currently, you can create a flow:

```yaml
id: myflow
namespace: company.myteam
tasks:
  - id: hello
    type: io.kestra.plugin.scripts.shell.Commands
    commands:
      - sleep 30
    taskRunner:
      type: io.kestra.plugin.core.runner.Process
```

Then, you can create an Execution of this flow from anywhere via an API call:

```bash
curl -X POST http://localhost:8080/api/v1/executions/company.myteam/myflow
```

This endpoint is even capable of waiting until the Execution finishes by adding `?wait=true`:

```bash
curl -X POST http://localhost:8080/api/v1/executions/company.myteam/myflow?wait=true
```

What's missing is a UI URL allowing users to click on the URL to follow the Execution progress.
