### ISSUE TITLE
Misconfigured Output Handling leads to failure in the task itself

### ISSUE THREAD

**Issue by aresfkonrad** [kestra-io/kestra#4274]
## Description

We are running an HTTP POST request via `io.kestra.plugin.core.http.Request` whose results we are trying to process first with `io.kestra.plugin.core.output.OutputValues` and then with the `outputs` parameter itself.

Unfortunately we could not find an example where the outputs parameter is used with variables. This lead us to searching for a solution via trial and error.

Our tasks look like this:

```yaml
tasks:
  - id: create_vm_request
    type: io.kestra.plugin.core.http.Request
    body: "{{inputs.payload}}"
    method: POST
    uri: "{{vars.endpoint}}/virtual-machines"

  - id: create_vm_request_outputs
    type: io.kestra.plugin.core.output.OutputValues
    values:
      success: "{{outputs.create_vm_request.code < 400}}"
      return_code: "{{ outputs.create_vm_request.code }}"
```

Our misconfigured outputs parameter looks like this:

```yaml
outputs:
  - id: success
    type: STRING
    value: outputs.create_vm_request_outputs.values.success
  - id: return_code
    type: STRING
    value: outputs.create_vm_request_outputs.values.return_code
```

The correct outputs parameter would look like this

```yaml
outputs:
  - id: success
    type: STRING
    value: "{{outputs.create_vm_request_outputs.values.success}}"
  
  - id: return_code
    type: STRING
    value: "{{outputs.create_vm_request_outputs.values.return_code}}"
```

We know that our outputs are misconfigured. That is not our issue here.

The following bug turns up in this case:

When we leave the misconfigured code as it is, the **create_vm_request** task fails after 12 seconds with a read error. When we comment out the whole output parameter, the **create_vm_request** task succeeds after 3 seconds.

## Expected behavior

The HTTP request should not fail, if its parameters are set correctly and if its payload is correct. This should not be impacted by a misconfigured `outputs` parameter.

Thank you very much for your support.

### Environment

- Kestra Version: 0.17.1 EE
- Operating System (OS/Docker/Kubernetes): Kubernetes 1.27
