### ISSUE TITLE
Logs opened from the Execution Topology view are missing (empty display)

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4300]
### Describe the issue

![image](https://github.com/kestra-io/kestra/assets/86264395/5c1f8a2f-0c7e-426c-ba9a-d3d8622af085)

https://share.descript.com/view/DCQXXxOGCaT

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by MilosPaunovic** [comment]
This should be amended with one of the previous commits, can you confirm @anna-geller?

**Comment by anna-geller** [comment]
yup, works 🥳 

![image](https://github.com/user-attachments/assets/66d160e2-a303-4c2c-8b11-8be3feee5fcf)

**Comment by anna-geller** [comment]
sorry I was too quick, need to reopen 😢  it seems that this occurs only when you have many tasks, see https://share.descript.com/view/vrMmpSDUwhD 

reproducer:

```yaml
id: dwh_and_analytics
namespace: tutorial
description: Data Warehouse and Analytics

tasks:
  - id: dbt
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
    - id: clone_repository
      type: io.kestra.plugin.git.Clone
      url: https://github.com/kestra-io/dbt-demo
      branch: main

    - id: dbt_build
      type: io.kestra.plugin.dbt.cli.DbtCLI
      taskRunner:
        type: io.kestra.plugin.scripts.runner.docker.Docker
      containerImage: ghcr.io/kestra-io/dbt-duckdb:latest
      commands:
        - dbt deps
        - dbt build
      profiles: |
        jaffle_shop:
          outputs:
            dev:
              type: duckdb
              path: dbt.duckdb
              extensions: 
                - parquet
              fixed_retries: 1
              threads: 16
              timeout_seconds: 300
          target: dev      

    - id: python
      type: io.kestra.plugin.scripts.python.Script
      outputFiles:
        - "*.csv"
      taskRunner:
        type: io.kestra.plugin.scripts.runner.docker.Docker
      containerImage: ghcr.io/kestra-io/duckdb:latest
      script: |
        import duckdb
        import pandas as pd

        conn = duckdb.connect(database='dbt.duckdb', read_only=False)

        tables_query = "SELECT table_name FROM information_schema.tables WHERE table_schema = 'main';"
        tables = conn.execute(tables_query).fetchall()

        # Export each table to CSV, excluding tables that start with 'raw' or 'stg'
        for table_name in tables:
            table_name = table_name[0]
            # Skip tables with names starting with 'raw' or 'stg'
            if not table_name.startswith('raw') and not table_name.startswith('stg'):
                query = f"SELECT * FROM {table_name}"
                df = conn.execute(query).fetchdf()
                df.to_csv(f"{table_name}.csv", index=False)

        conn.close()
```
