### ISSUE TITLE
Pebble filters applied to JSON inputs produce non-JSON strings

### ISSUE THREAD

**Issue by aku** [kestra-io/kestra#4340]
### Describe the issue

If you have a JSON field, e.g.

```
inputs:
  - id: payload
    type: JSON
    defaults: |-
      [{"name": "single quote in string '"}]
```

and want to apply pebble filters such as replace or escapeChar the resulting string will loose JSON formatting.

```"{{ inputs.payload | escapeChar('single') }}"``` -> ```[{name=single quote in string \'}]```

if you do the same against STRING field it will produce expected result ```[{"name":"single quote in string \'"}]```
      
I.e. when you use pebble filters with JSON it gets serialized to string which is non-json compliant 

Context and examples: https://kestra-io.slack.com/archives/C03FQKXRK3K/p1720800171410189

Example:

```yaml
id: json_vs_string_filtering
namespace: dev
inputs:
  - id: payload_json
    type: JSON
    defaults: |-
      [{"name": "single quote in string '"}]
  - id: payload_string
    type: STRING
    defaults: "[{\"name\":\"single quote\" in string '}]"
tasks:

  - id: debug
    type: io.kestra.plugin.core.debug.Echo
    format: "{{ inputs.payload_json | escapeChar('single') }} \n {{ inputs.payload_string | escapeChar('single') }}"

```

### Environment

- Kestra Version: 17.8
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):
