### ISSUE TITLE
Find a better way to for DockerTaskRunner to run containers without DinD on Windows

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4348]
### Feature description

For now, we can leverage the [host](https://kestra.io/plugins/plugin-terraform/task-runners/io.kestra.plugin.scripts.runner.docker.dockertaskrunner#host) property but it may not be sufficient as we also need volume sharing to make it work. We should investigate a similar solution to what we do with KubernetesTaskRunner that creates a volume for the taskrun. 

Example flow that currently doesn't work yet on Windows WSL2:

```yaml
id: "test_wsl2"
namespace: "myteam"
tasks:
  - id: bash
    type: io.kestra.plugin.scripts.python.Commands
    taskRunner: 
      type: io.kestra.plugin.scripts.runner.docker.DockerTaskRunner
      host: unix:///var/run/docker.sock
    inputFiles:
      main.py: |
        import requests
        from kestra import Kestra

        response = requests.get('https://google.com/')
        print(response.status_code)
        Kestra.outputs({'status': response.status_code, 'text': response.text})
    beforeCommands:
      - python -m venv venv
      - . venv/bin/activate
      - pip install requests kestra > /dev/null
    commands:
      - python main.py
```

from @loicmathieu: "Looking quickly at the Docker Java driver we should be able to copy files in the container after creating and downloading them after deleting as we do for k8s. This would avoid mounting any directory so would fix the issue for Windows and orchestrators like Swarm."
