### ISSUE TITLE
Documentation missing for production docker-compose deployment of Kestra without root

### ISSUE THREAD

**Issue by kryptonut** [kestra-io/kestra#4371]
### Describe the issue

In the documentation and example YAML file for docker-compose:
https://github.com/kestra-io/kestra/blob/releases/v0.17.x/docker-compose.yml
https://github.com/kestra-io/kestra/blob/develop/docker-compose.yml

There is a comment that says:
# Note that this is meant for development only. Refer to the documentation for production deployments of Kestra which runs without a root user.

I am unable to find documentation for production deployments of Kestra which runs without a root user in the website documentation.  All examples run as root.

### Environment

- Kestra Version:  N/A
- Operating System (OS/Docker/Kubernetes):  docker-compose
- Java Version (if you don't run kestra in Docker):  N/A

**Comment by anna-geller** [comment]
this one is rootless but more complex https://github.com/kestra-io/kestra/blob/develop/docker-compose-dind.yml 

feel free to contribute

**Comment by kryptonut** [comment]
@anna-geller that file contains the same comment and code


```
kestra:
    image: kestra/kestra:latest-full
    pull_policy: always
    # Note that this is meant for **development only. Refer to the documentation for production deployments** of Kestra which runs without a root user.
    **user: "root"**

```

**Comment by anna-geller** [comment]
sorry for misunderstanding but what was meant was this part that you can replicate in your kestra image https://github.com/kestra-io/kestra/blob/develop/docker-compose-dind.yml#L26-L37 

are you open to contribute a new docker compose? you can add it e.g. as https://github.com/kestra-io/kestra/blob/develop/docker-compose-rootless.yml

**Comment by kryptonut** [comment]
Thanks @anna-geller, I'll give it a go when I'm free.

**Comment by kryptonut** [comment]
Just an update....I've attempted to set this up, but I'm running into issues with dind.  Will have to sort that out before I can see if I can get the stack up and running without root.

**Comment by qp-st** [comment]
@anna-geller Could you please consider re-opening this issue?

This was closed with a link to https://kestra.io/docs/installation/podman-compose, but in https://github.com/kestra-io/docs/issues/2404 that page got updated by @loicmathieu to remove the mention of rootless instructions again. So right now it seems like there aren't any recommended instructions for non-root setup with docker or podman.

If I get the chance, I will try to achieve a rootless docker setup soon and document it.

Please kindly let me know if non-root docker/podman setup is considered out of scope.

**Comment by MilosPaunovic** [comment]
@aj-emerich Could you validate this and handle if needed?

**Comment by aj-emerich** [comment]
@qp-st, hey there, if you're able to get a setup working and provide consistent documentation, then we are happy to accept it and review the content. I know this was a pain to get working consistently in the past, so it got dropped.

**Comment by qp-st** [comment]
I have successfully deployed Kestra v1.1.14 in **rootless** Docker Compose using a minimally modified `compose.yaml` file. @aj-emerich 

For Working Directory Tasks, the tmp directory must be set to a user-writable location. And for Docker-related Tasks, the socket must be pointed at the correct host-side rootless Docker socket:

```diff
--- a/compose.yaml
+++ b/compose.yaml
@@ services:
     command: server standalone
     volumes:
       - kestra-data:/app/storage
-      - /var/run/docker.sock:/var/run/docker.sock
-      - /tmp/kestra-wd:/tmp/kestra-wd
+      - /run/user/1000/docker.sock:/var/run/docker.sock
+      - $PWD/tmp/kestra-wd:/tmp/kestra-wd
```
(compared to the [original](https://github.com/kestra-io/kestra/blob/v1.1.14/docker-compose.yml))

Notably, Kestra **must** run as root _inside the container_ with this `docker compose` setup to ensure correct file access permissions. Against what one might expect, **this is safe**, as root inside the container just gives it user-level permission in the host (container uid 0 ⇔ host uid 1000). It means the Kestra container can start other rootless containers, but cannot perform system actions on the host.

If Kestra is not run as "root", basic features like Flow execution work, but Docker and File-related Tasks stop working due to user-namespace uid mapping issues (container uid 1000 ⇔ host uid >100000). I choose to not investigate this further.

A minimal example Kestra Service definition for rootless Docker Compose:
```yaml
services:
  kestra:
    image: kestra/kestra:latest
    # IMPORTANT:
    # Run as root inside container, even when host is rootless Docker,
    # otherwise Docker socket and file access will fail due to userns mapping.
    user: "root"
    command: server standalone
    volumes:
      - kestra-data:/app/storage
      - /run/user/1000/docker.sock:/var/run/docker.sock
      - $PWD/tmp/kestra-wd:/tmp/kestra-wd
    environment:
      KESTRA_CONFIGURATION: *common_configuration
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_started
```

Naturally, the working directory could also be specified as an absolute path, without the `$PWD`.
