### ISSUE TITLE
[Regression] JSON inputs are displayed in the UI as strings instead of JSON

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4388]
Reproducer:

```yaml
id: myflow123
namespace: company.myteam
description: Save and Execute the flow

labels:
  env: dev
  project: myproject

inputs:
  - id: payload
    type: JSON
    defaults: |
      {
        "name": "John Doe",
        "age": 30,
        "email": "john.doe@example.com",
        "address": {
          "street": "123 Main St",
          "city": "Anytown",
          "state": "CA",
          "zip": "12345"
        },
        "phoneNumbers": [
          {
            "type": "home",
            "number": "555-1234"
          },
          {
            "type": "work",
            "number": "555-5678"
          }
        ]
      }

tasks:
  - id: send_data
    type: io.kestra.plugin.core.http.Request
    uri: https://reqres.in/api/products
    method: POST
    contentType: application/json
    body: "{{ inputs.payload }}"

  - id: print_status
    type: io.kestra.plugin.core.log.Log
    message: hello on {{ outputs.send_data.headers.date | first }}
```

![image](https://github.com/user-attachments/assets/8bdd1920-0caa-482a-a083-cde10ff2d9e0)
