### ISSUE TITLE
Revisit the fix that requires `--break-system-packages` to install pip packages in the Docker image

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4408]
### Feature description

Revisit the fix from https://github.com/kestra-io/kestra/pull/4406/files as ideally, we'd rather avoid having to use the option `--break-system-packages`.  

from @fhussonnois: "The build of docker image seems to be broken since yesterday (without any modification) with the pip error: `error: externally-managed-environment` when installing the kestra library (i.e. `pip install kestra`). Adding the option `--break-system-packages` seems to fix the issue. But, not being a Python developer, I don't know why we're getting this error now."

**Comment by anna-geller** [comment]
we may need to tackle it sooner as currently on develop you can't install any packages using process runner:

![image](https://github.com/user-attachments/assets/dca7aa50-53ed-491f-bdc7-3c7ae8eb7a33)

**Comment by anna-geller** [comment]
reproducer:
```yaml
id: beforecommands_repro
namespace: company.team

tasks:
  - id: transform
    type: io.kestra.plugin.scripts.python.Script
    taskRunner:
      type: io.kestra.plugin.core.runner.Process
    beforeCommands:
      - pip install requests
    script: |
      print("hello")
```
