### ISSUE TITLE
EachSequential task getting stuck when looping through json

### ISSUE THREAD

**Issue by nikolicdragoslav** [kestra-io/kestra#4419]
### Describe the issue

Hello, 

I have implemented a workflow in Kestra which is polling for status of other workflows and writing the results into a Kafka topic for more detailed monitoring. 

I am having an issue once in a while with EachSequential plugin. It seems that sometimes it get's stuck in the loop that is basically going through taskRunList from the response of the Kestra API.

it is triggered with some payload I use and also with an execution id of the flow that has subflows, that is why I am looping through taskList to fetch the statuses of each subflow

```yaml
id: statusChecker
namespace: utility
description: Flow that checks Kestra workflow status every x seconds and writes the status into a Kafka topic
labels:
  taskTitle: Workflow status checker
  showInUI: "false"
  isRootFlow: "false"

inputs:
- id: execution_id
  type: STRING
- id: payload
  type: JSON

tasks:
- id: log
  type: io.kestra.plugin.core.log.Log
  message: "Input: {{inputs}}"

- id: checkStatus
  type: io.kestra.plugin.core.flow.WaitFor
  condition: "{{ json(outputs.callAPI.body)['state']['current'] == 'SUCCESS' or json(outputs.callAPI.body)['state']['current'] == 'FAILED' }}"  
  checkFrequency: 
    maxIterations: 10
    maxDuration: 120
    interval: PT15S
  tasks:
    - id: callAPI
      type: io.kestra.plugin.core.http.Request
      uri: "[https://kestra/api/v1/executions/{{inputs.execution_id}}](https://kestra/api/v1/executions/%7B%7Binputs.execution_id%7D%7D)"
      method: GET
      contentType: application/json
      options:
        basicAuthUser: user
        basicAuthPassword: usr
    
    - id: logResponse
      type: io.kestra.plugin.core.log.Log
      message: "Status: {{outputs.callAPI}}"

    - id: fetchLogsFirst 
      type: io.kestra.plugin.core.http.Request  
      uri: "[https://kestra/api/v1/logs/{{inputs.execution_id}}/download](https://kestra/api/v1/logs/%7B%7Binputs.execution_id%7D%7D/download)"  
      method: GET  
      contentType: application/json  
      options:  
        basicAuthUser: user  
        basicAuthPassword: usr 

    - id: writeStatusParent
      type: io.kestra.plugin.kafka.Produce  
      topic: status-test
      keySerializer: STRING  
      valueSerializer: JSON  
      from:  
        value: {"event_id": "{{inputs.payload.event_id}}", "tenant_name": "{{inputs.payload.tenant_name}}", "sandbox_name": "{{inputs.payload.sandbox_name}}", "task_type_id": "curated", "status": "{{json(outputs.callAPI.body)}}", "execution_log": "{{ outputs.fetchLogsFirst.body }}"}
      properties:  
        bootstrap.servers: servers
        sasl.client.callback.handler.class: software.amazon.msk.auth.iam.IAMClientCallbackHandler  
        sasl.jaas.config: software.amazon.msk.auth.iam.IAMLoginModule required;  
        sasl.mechanism: AWS_MSK_IAM  
        security.protocol: SASL_SSL
    
    - id: each_sequential  
      type: io.kestra.plugin.core.flow.EachSequential  
      value: "{{ json(outputs.callAPI.body)['taskRunList'] }}"  
      tasks:  
        - id: logExecutionId  
          type: io.kestra.plugin.core.log.Log  
          message: "Execution id: {{ json(taskrun.value)['outputs']['executionId'] | default('default_value') }} for task: {{ json(taskrun.value)['taskId']}}"
    
        - id: if_subflow  
          type: io.kestra.plugin.core.flow.If  
          condition: "{{ json(taskrun.value)['outputs']['executionId'] is defined and json(taskrun.value)['taskId'] != 'startStatusChecker' }}"
          then:  
            - id: printTrue  
              type: io.kestra.plugin.core.log.Log  
              message: "Task is a subflow, checking status of execution: {{ json(parent.taskrun.value)['outputs']['executionId'] }}"  
        
            - id: callTaskExecutionId  
              type: io.kestra.plugin.core.http.Request  
              uri: "[https://kestra/api/v1/executions/{{](https://kestra/api/v1/executions/%7B%7B) json(parent.taskrun.value)['outputs']['executionId']}}"  
              method: GET  
              contentType: application/json  
              options:  
                basicAuthUser: user  
                basicAuthPassword: usr
            - id: fetchLogs  
              type: io.kestra.plugin.core.http.Request  
              uri: "[https://kestra/api/v1/logs/{{](https://kestra/api/v1/logs/%7B%7B) json(parent.taskrun.value)['outputs']['executionId']}}/download"  
              method: GET  
              contentType: application/json  
              options:  
                basicAuthUser: user  
                basicAuthPassword: usr  
        
            - id: logSubflowStatus  
              type: io.kestra.plugin.core.log.Log  
              message: "Status: {{ outputs.callTaskExecutionId[parent.taskrun.value].body }}"  

            - id: writeStatusSub  
              type: io.kestra.plugin.kafka.Produce  
              topic: status-test
              keySerializer: STRING  
              valueSerializer: JSON  
              from:  
                value: {"event_id": "{{inputs.payload.event_id}}", "tenant_name": "{{inputs.payload.tenant_name}}", "sandbox_name": "{{inputs.payload.sandbox_name}}", "task_type_id": "curated", "status": "{{ outputs.callTaskExecutionId[parent.taskrun.value].body }}", "execution_log": "{{ outputs.fetchLogs[parent.taskrun.value].body }}"}
              properties:  
                bootstrap.servers: servers
                sasl.client.callback.handler.class: software.amazon.msk.auth.iam.IAMClientCallbackHandler  
                sasl.jaas.config: software.amazon.msk.auth.iam.IAMLoginModule required;  
                sasl.mechanism: AWS_MSK_IAM  
                security.protocol: SASL_SSL 
          else:  
            - id: printFalse  
              type: io.kestra.plugin.core.log.Log  
              message: "Task is not a subflow. Not checking the status."  

- id: callAPIFinal
  type: io.kestra.plugin.core.http.Request
  uri: "[https://kestra/api/v1/executions/{{inputs.execution_id}}](https://kestra/api/v1/executions/%7B%7Binputs.execution_id%7D%7D)"
  method: GET
  contentType: application/json
  options:
    basicAuthUser: user
    basicAuthPassword: usr
- id: fetchLogsFinal  
  type: io.kestra.plugin.core.http.Request  
  uri: "[https://kestra/api/v1/logs/{{inputs.execution_id}}/download](https://kestra/api/v1/logs/%7B%7Binputs.execution_id%7D%7D/download)"  
  method: GET  
  contentType: application/json  
  options:  
    basicAuthUser: user  
    basicAuthPassword: usr  

- id: logResponseFinal
  type: io.kestra.plugin.core.log.Log
  message: "Status: {{outputs.callAPIFinal}}"

- id: each_sequentialFinal  
  type: io.kestra.plugin.core.flow.EachSequential  
  value: "{{ json(outputs.callAPIFinal.body)['taskRunList'] }}"  
  tasks:  
    - id: logExecutionIdFinal 
      type: io.kestra.plugin.core.log.Log  
      message: "Execution id: {{ json(taskrun.value)['outputs']['executionId'] | default('default_value') }} for task: {{ json(taskrun.value)['taskId']}}"

    - id: if_subflowFinal  
      type: io.kestra.plugin.core.flow.If  
      condition: "{{ json(taskrun.value)['outputs']['executionId'] is defined and json(taskrun.value)['taskId'] != 'startStatusChecker' }}"
      then:  
        - id: printTrueFinal  
          type: io.kestra.plugin.core.log.Log  
          message: "Task is a subflow, checking status of execution: {{ json(parent.taskrun.value)['outputs']['executionId'] }}"  
    
        - id: callTaskExecutionIdFinal  
          type: io.kestra.plugin.core.http.Request  
          uri: "[https://kestra/api/v1/executions/{{](https://kestra/api/v1/executions/%7B%7B) json(parent.taskrun.value)['outputs']['executionId']}}"  
          method: GET  
          contentType: application/json  
          options:  
            basicAuthUser: user  
            basicAuthPassword: usr
        - id: fetchLogsSubFinal 
          type: io.kestra.plugin.core.http.Request  
          uri: "[https://kestra/api/v1/logs/{{](https://kestra/api/v1/logs/%7B%7B) json(parent.taskrun.value)['outputs']['executionId']}}/download"  
          method: GET  
          contentType: application/json  
          options:  
            basicAuthUser: user  
            basicAuthPassword: usr   
    
        - id: logSubflowStatusFinal  
          type: io.kestra.plugin.core.log.Log  
          message: "Status: {{ outputs.callTaskExecutionIdFinal[parent.taskrun.value].body }}"  

        - id: writeStatusSubFinal  
          type: io.kestra.plugin.kafka.Produce  
          topic: status-test
          keySerializer: STRING  
          valueSerializer: JSON  
          from:  
            value: {"event_id": "{{inputs.payload.event_id}}", "tenant_name": "{{inputs.payload.tenant_name}}", "sandbox_name": "{{inputs.payload.sandbox_name}}", "task_type_id": "curated", "status": "{{ outputs.callTaskExecutionIdFinal[parent.taskrun.value].body }}", "execution_log": "{{ outputs.fetchLogsSubFinal[parent.taskrun.value].body }}"}
          properties:  
            bootstrap.servers: servers
            sasl.client.callback.handler.class: software.amazon.msk.auth.iam.IAMClientCallbackHandler  
            sasl.jaas.config: software.amazon.msk.auth.iam.IAMLoginModule required;  
            sasl.mechanism: AWS_MSK_IAM  
            security.protocol: SASL_SSL 
      else:  
        - id: printFalseFinal 
          type: io.kestra.plugin.core.log.Log  
          message: "Task is not a subflow. Not checking the status."

- id: writeStatusFinal
  type: io.kestra.plugin.kafka.Produce  
  topic: status-test
  keySerializer: STRING  
  valueSerializer: JSON  
  from:  
    value: {"event_id": "{{inputs.payload.event_id}}", "tenant_name": "{{inputs.payload.tenant_name}}", "sandbox_name": "{{inputs.payload.sandbox_name}}", "task_type_id": "curated", "status": "{{json(outputs.callAPIFinal.body)}}", "execution_log": "{{ outputs.fetchLogsFinal.body }}"}
  properties:  
    bootstrap.servers: servers
    sasl.client.callback.handler.class: software.amazon.msk.auth.iam.IAMClientCallbackHandler  
    sasl.jaas.config: software.amazon.msk.auth.iam.IAMLoginModule required;  
    sasl.mechanism: AWS_MSK_IAM  
    security.protocol: SASL_SSL
```
Snippets of tasks in RUNNING
![image](https://github.com/user-attachments/assets/235ecfcf-efb9-4bd8-b1ef-6d5787b36194)
![image](https://github.com/user-attachments/assets/1ff362c0-589b-4150-9e91-79fc9e75bf3d)

For example this is how I trigger the status checker flow -  it checks the status of the parent flow, its tasks identifying the subflows to check their task status, but it does not check the tasks of the subflow. That being said it goes only one level deeper than the parent API call:

```id: testinStatusCheck
namespace: test

triggers:
  - id: kafkaTrigger
    type: io.kestra.plugin.kafka.RealtimeTrigger
    keyDeserializer: JSON
    groupId: "kestraConsumer"
    properties:
      auto.offset.reset: earliest
      bootstrap.servers: brokers
      sasl.client.callback.handler.class: software.amazon.msk.auth.iam.IAMClientCallbackHandler
      sasl.jaas.config: software.amazon.msk.auth.iam.IAMLoginModule required;
      sasl.mechanism: AWS_MSK_IAM
      security.protocol: SASL_SSL
    topic: test-topic
    valueDeserializer: JSON

tasks:
  - id: printEvent
    type: io.kestra.plugin.core.log.Log
    message: "{{trigger.value}}"
  - id: parallel
    type: io.kestra.plugin.core.flow.Parallel
    tasks:
      - id: startStatusChecker
        type: io.kestra.plugin.core.flow.Subflow
        namespace: utility
        flowId: statusChecker
        inputs:
          execution_id: "{{execution.id}}"
          payload: "{{trigger.value}}"
        wait: false
        transmitFailed: true
      - id: startExampleFlow
        type: io.kestra.plugin.core.flow.Subflow
        namespace: test
        flowId: example_flow
        inputs:
          payload: "{{trigger.value}}"
        wait: true
        transmitFailed: true
```

To sum it up, when it get's to the end of the iteration, instead of stopping the task and returning to the WaitFor parent task, it gets stuck in RUNNING state, after looping through all tasks. To note, it gets stuck on the first iteration, usually first iteration doesn't have execution id ready for the subflows so it goes to the printFalse task. 

For example, looking at the below JSON that is what we are looping through, it sees for each task (printEvent, parallel, startStatusChecker, startCdmGenerator) that they currently don't have execution id and instead of jumping out of the loop it get's stuck after logging each one of them and logging the print of printFalse task. Since it doesn't reach printTrue I believe here maybe it is not a case of complexity of the flow, but some bug with the EachSequential plugin. 

Example of rendered expression for EachSequential flow ({{ json(outputs.callAPI.body)['taskRunList'] }}):
```
[
  {
    "id": "2ACBvWpctTIm8VD1y9ajyJ",
    "executionId": "7SLZtK3NZ2dK4Yc2msKjy4",
    "namespace": "test",
    "flowId": "flow1",
    "taskId": "printEvent",
    "attempts": [
      {
        "state": {
          "current": "SUCCESS",
          "histories": [
            {
              "state": "CREATED",
              "date": "2024-07-24T12:49:19.873Z"
            },
            {
              "state": "RUNNING",
              "date": "2024-07-24T12:49:19.873Z"
            },
            {
              "state": "SUCCESS",
              "date": "2024-07-24T12:49:19.887Z"
            }
          ],
          "startDate": "2024-07-24T12:49:19.873Z",
          "endDate": "2024-07-24T12:49:19.887Z",
          "duration": "PT0.014S"
        }
      }
    ],
    "outputs": {},
    "state": {
      "current": "SUCCESS",
      "histories": [
        {
          "state": "CREATED",
          "date": "2024-07-24T12:49:19.419Z"
        },
        {
          "state": "RUNNING",
          "date": "2024-07-24T12:49:19.863Z"
        },
        {
          "state": "SUCCESS",
          "date": "2024-07-24T12:49:19.888Z"
        }
      ],
      "startDate": "2024-07-24T12:49:19.419Z",
      "endDate": "2024-07-24T12:49:19.888Z",
      "duration": "PT0.469S"
    }
  },
  {
    "id": "6qlV6029qDTYXwIaVgmAwn",
    "executionId": "7SLZtK3NZ2dK4Yc2msKjy4",
    "namespace": "test",
    "flowId": "flow",
    "taskId": "parallel",
    "outputs": {},
    "state": {
      "current": "RUNNING",
      "histories": [
        {
          "state": "CREATED",
          "date": "2024-07-24T12:49:20.305Z"
        },
        {
          "state": "RUNNING",
          "date": "2024-07-24T12:49:20.318Z"
        }
      ],
      "startDate": "2024-07-24T12:49:20.305Z",
      "duration": "PT0.013S"
    }
  },
  {
    "id": "6OoZ2ytl3Uev23lDA8D9oS",
    "executionId": "7SLZtK3NZ2dK4Yc2msKjy4",
    "namespace": "test",
    "flowId": "flow1",
    "taskId": "startStatusChecker",
    "parentTaskRunId": "6qlV6029qDTYXwIaVgmAwn",
    "attempts": [
      {
        "state": {
          "current": "SUCCESS",
          "histories": [
            {
              "state": "CREATED",
              "date": "2024-07-24T12:49:20.380Z"
            },
            {
              "state": "SUCCESS",
              "date": "2024-07-24T12:49:20.380Z"
            }
          ],
          "startDate": "2024-07-24T12:49:20.380Z",
          "endDate": "2024-07-24T12:49:20.380Z",
          "duration": "PT0S"
        }
      }
    ],
    "outputs": {
      "state": "CREATED",
      "executionId": "73BymR3KiLDVGegvj5d8IL"
    },
    "state": {
      "current": "SUCCESS",
      "histories": [
        {
          "state": "CREATED",
          "date": "2024-07-24T12:49:20.368Z"
        },
        {
          "state": "RUNNING",
          "date": "2024-07-24T12:49:20.380Z"
        },
        {
          "state": "SUCCESS",
          "date": "2024-07-24T12:49:20.380Z"
        }
      ],
      "startDate": "2024-07-24T12:49:20.368Z",
      "endDate": "2024-07-24T12:49:20.380Z",
      "duration": "PT0.012S"
    }
  },
  {
    "id": "32s3F23tx5gi6v3YwBfH1I",
    "executionId": "7SLZtK3NZ2dK4Yc2msKjy4",
    "namespace": "test",
    "flowId": "flow1",
    "taskId": "startCdmGenerator",
    "parentTaskRunId": "6qlV6029qDTYXwIaVgmAwn",
    "state": {
      "current": "RUNNING",
      "histories": [
        {
          "state": "CREATED",
          "date": "2024-07-24T12:49:20.368Z"
        },
        {
          "state": "RUNNING",
          "date": "2024-07-24T12:49:20.380Z"
        }
      ],
      "startDate": "2024-07-24T12:49:20.368Z",
      "duration": "PT0.012S"
    }
  }
]
```

Please let me know if any information that is not provided is needed.

Thank you,
Dragoslav

### Environment

- Kestra Version: v0.17.0
- Operating System (OS/Docker/Kubernetes): Kubernetes

**Comment by nikolicdragoslav** [comment]
Hello @anna-geller, tagging you because I see you made some edit here, anyone had a chance to look at this yet?

**Comment by anna-geller** [comment]
hey, I only edited the format of a code block back then 😄 

There are many things you can optimize in your flow to avoid it getting stuck:
1. we generally recommend splitting a large flow into subflows if you have many tasks. You can consider splitting if_subflow task into actual real subflow https://kestra.io/docs/best-practices/flows 
2. I see you have a *status checker flow - it checks the status of the parent flow* -- we provide a native way to call another flow as a subflow and wait for its completion in a more efficient way than via WaitFor task:

```yaml
  - id: launch_subflow_and_wait_for_completion
    type: io.kestra.plugin.core.flow.Subflow
    namespace: yournamespace
    flowId: yourflow
    wait: true
    transmitFailed: true
```
