### ISSUE TITLE
Securely Transfer and Decrypt a File using Kestra's OpenPGP Plugin

### ISSUE THREAD

**Issue by vibzsg** [kestra-io/kestra#4424]
### Blueprint title

Encrypt, Transfer, and Decrypt a File using OpenPGP Plugin

### Source code

```
id: secure-file-transfer
namespace: blueprint
tasks:
  - id: encrypt-report
    type: "io.kestra.plugin.crypto.openpgp.Encrypt"
    from: `"/local/path/to/report.txt"`
    key: |
      -----BEGIN PGP PUBLIC KEY `BLOCK-----`
      ... (recipient's public key) ...
    recipients:
      - admin@remote-server.com
    outputs:
      - uri: "encrypted_report.pgp"

  - id: sftp-transfer
    type: "io.kestra.plugin.fs.sftp.Upload"
    from: "{{ task.encrypt-report.uri }}"
    to: "/remote/path/encrypted_report.pgp"
    host: "sftp.remote-server.com"
    username: "sftp-user"
    password: "{{ secret('sftp_password') }}"

  - id: decrypt-report
    type: "io.kestra.plugin.crypto.openpgp.Decrypt"
    from: "/remote/path/encrypted_report.pgp"
    privateKey: |
      -----BEGIN PGP PRIVATE KEY BLOCK-----
      ... (recipient's private key) ...
    privateKeyPassphrase: "{{ secret('pgp_passphrase') }}"
    outputs:
      - uri: "decrypted_report.txt"

```

### About this blueprint

Concise markdown documentation about the blueprint's configuration and usage:

This blueprint demonstrates how to securely transfer a confidential file using Kestra's OpenPGP plugin. It covers the following steps:

1. Encrypt the File: The encrypt-report task uses the OpenPGP plugin to encrypt a file with the recipient's public key.
2. Transfer the Encrypted File: The sftp-transfer task uploads the encrypted file to a remote server using SFTP.
3. Decrypt the File: The decrypt-report task decrypts the file on the remote server using the recipient's private key and passphrase.

Prerequisites:

1. Ensure you have the recipient's public key for encryption.
2. Ensure the recipient's private key and passphrase are available for decryption.
3. Configure your SFTP credentials as Kestra secrets (sftp_password, pgp_passphrase).

Usage:

1. Clone the repository and navigate to the blueprint directory.
2. Update the file paths, keys, and secrets in the YAML configuration.
3. Deploy the workflow in your Kestra instance to securely transfer and decrypt your files.``

### Tags (optional)

Security - Encryption - Decryption - SFTP - Kestra - OpenPGP
