### ISSUE TITLE
SEO summary

### ISSUE THREAD

**Issue by khabdrick** [kestra-io/kestra#4425]
### Blueprint title

Extract file and generate SEO summary for a document.

### Source code

```yaml
id: seo-summary
namespace: blueprint
description: Save and Execute the flow

tasks:
  - id: fetch_article
    type: io.kestra.plugin.scripts.python.Script
    taskRunner:
      type: io.kestra.plugin.core.runner.Process

    warningOnStdErr: false
    outputFiles:
      - article.txt
    description: "Fetch the article from a txt file on GitHub"
    script: |
      import requests

      github_url = "https://raw.githubusercontent.com/khabdrick/wordpress-directus/main/article.txt"
      response = requests.get(github_url)
      response.raise_for_status()
      with open("article.txt", "w") as file:
          file.write(response.text)
      print("Article fetched successfully.")

  - id: generate_seo_summary
    type: io.kestra.plugin.scripts.python.Script
    taskRunner:
      type: io.kestra.plugin.core.runner.Process
    warningOnStdErr: false

    beforeCommands:
      - pip install openai > /dev/null
    outputFiles:
      - seo_summary.txt
    description: "Generate an SEO-optimized summary using OpenAI"
    script: |
      from openai import OpenAI
      
      client = OpenAI(api_key="<Your-openai-key>")
      with open('{{ outputs.fetch_article.outputFiles['article.txt'] }}', "r") as file:
          article_content = file.read()
      response = client.completions.create(
        model="gpt-3.5-turbo-instruct",
        prompt=f"Write an SEO-optimized summary for the following article:\n\n{article_content}",
        max_tokens=150,
      )


      seo_summary = response.choices[0].text.strip()
      with open("seo_summary.txt", "w") as file:
          file.write(seo_summary)

      print("SEO summary generated successfully.")

  - id: log_seo_summary
    type: io.kestra.plugin.scripts.python.Script
    description: "Print the SEO summary in the log"
    script: |
      with open('{{ outputs.generate_seo_summary.outputFiles['seo_summary.txt'] }}', "r") as file:
          seo_summary = file.read()
      print("SEO Summary:\n", seo_summary)
```

### About this blueprint

Kestra workflow to automate writing SEO-optimized summaries using the Python plugin and OpenAI. The workflow will fetch an article from a `txt` file on GitHub and use OpenAI to generate an SEO summary, which will then be printed in the log.

### Tags (optional)

- OpenAI
- Python
