### ISSUE TITLE
Add PROCESS runner properties to the Process Task Runner

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#4442]
### Feature description

The previous `PROCESS` runner supported the additional `workerGroup` property too like this:

```yaml
id: gpu_task
namespace: company.team

tasks:
  - id: gpu
    type: io.kestra.plugin.scripts.python.Commands
    runner: PROCESS
    commands:
      - python ml_on_gpu.py
    workerGroup:
      key: gpu
```

It should be added to the process Task Runner like this:

```yaml
id: gpu_task
namespace: company.team

tasks:
  - id: gpu
    type: io.kestra.plugin.scripts.python.Commands
    taskRunner:
      type: io.kestra.plugin.core.runner.Process
      workerGroup:
        key: gpu
    commands:
      - python ml_on_gpu.py
```
Other `PROCESS` properties should also be added too but not sure there are any others
