### ISSUE TITLE
[Bugfix release needed] Task runner issue on 0.17.14

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4448]
### Describe the issue

Reproducer:

```yaml
id: drip-subscriber-new
namespace: prod

tasks:
  - id: parse_webhook_json
    type: io.kestra.plugin.scripts.python.Script
    description: Parse webhook body
    script: |
      from kestra import Kestra
      json_data = dict(mystr="hello", myint=42)
      Kestra.outputs(json_data)
```

Error:

```
"Cannot invoke "io.kestra.core.models.tasks.runners.TaskRunner.getType()" because the return value of "io.kestra.plugin.scripts.exec.AbstractExecScript.getTaskRunner()" is null"
```

![image](https://github.com/user-attachments/assets/e50f6d50-dede-454d-9222-6a0096064ac6)

### Environment

- Kestra Version: 0.17.14
