### ISSUE TITLE
Trigger logs view is automatically collapsing after a couple of seconds, making it impossible to read the logs

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4450]
### Describe the issue

To reproduce, add any event trigger (e.g. SQS = can be a regular polling or realtime trigger) and try to read the logs:
https://share.descript.com/view/cmdaa1Y1wh5

You can reproduce using:

```yaml
id: myflow
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World!

triggers:
  - id: sqs
    type: io.kestra.plugin.aws.sqs.Trigger
    accessKeyId: "<access-key>"
    secretKeyId: "<secret-key>"
    region: "eu-central-1"
    queueUrl: "https://sqs.eu-central-1.amazonaws.com/000000000000/test-queue"
    maxRecords: 10
```

after 3-4 seconds the trigger log view will auto-collapse — we should avoid auto-collapse

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):
