### ISSUE TITLE
Executing shell commands outside Kestra Docker

### ISSUE THREAD

**Issue by g33kroid** [kestra-io/kestra#4466]
### Issue description

Hi, I am building a workflow that executes a bash script outside the Docker Container from the host. 
However, I can quite get it to work as it keeps checking inside the docker, and the result is command not found 

Any Idea how to fix such issue.

**Comment by anna-geller** [comment]
Hi, yes -- you would need to use the process task runner https://develop.kestra.io/docs/concepts/task-runners/types/process-task-runner 

Example:

```yaml
id: process_script_runner
namespace: company.team

tasks:
  - id: shell
    type: io.kestra.plugin.scripts.shell.Commands
    taskRunner:
      type: io.kestra.plugin.core.runner.Process
    commands:
      - echo "Hello World!"
```
