### ISSUE TITLE
new ForEach topology show task in "parallel" while concurrency is set to 1

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#4474]
### Describe the issue

When using the new ForEach task with `concurency: 1` the topology still show tasks like if they were run in parallel. Not a big issue but could mislead users - especially those used to EachSequential + `concurrency: 1` is the default value

![image](https://github.com/user-attachments/assets/884b2098-22d7-47b0-ace4-0b50a6f8576a)

### Environment

- Kestra Version: 0.18-SNAPSHOT
- Operating System (OS/Docker/Kubernetes): Docker
- Java Version (if you don't run kestra in Docker):

**Comment by anna-geller** [comment]
I can confirm topology view is not correct 

![image](https://github.com/user-attachments/assets/d16d36ee-ea1b-4b9b-b81c-b41cc245bfc1)

even though backend-wise everything is fine (see execution is correctly running each task groups sequentially one after the other rather than in parallel as shown in the topology view):

![image](https://github.com/user-attachments/assets/241c3eb2-de48-43de-8ba2-01e7f1b1edd6)

```yaml
id: test_for_each
namespace: kestra.qa

tasks:
  - id: for_each
    type: io.kestra.plugin.core.flow.ForEach
    values: ['value1', 'value2', 'value3']
    concurrencyLimit: 1
    tasks:
      - id: log1
        type: io.kestra.plugin.core.log.Log
        message: "{{ taskrun.value }}"
      
      - id: log2
        type: io.kestra.plugin.core.log.Log
        message: "{{ taskrun.value }}"

      - id: log3
        type: io.kestra.plugin.core.log.Log
        message: "{{ taskrun.value }}"
```

@MilosPaunovic can you have a look? the tasks in the group should be shown as a sequential group within ForEach
