### ISSUE TITLE
New ForEach task gets stuck in a Running state when using `concurrencyLimit: 0`

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#4475]
### Describe the issue

The following flow get stuck to RUNNING state when `concurrency: 0` (EachParallel behavior)

![image](https://github.com/user-attachments/assets/a8c1845c-f7b9-4c53-b73b-3ee181b78958)

```yaml
id: test_for_each
namespace: kestra.qa

tasks:
  - id: for_each
    type: io.kestra.plugin.core.flow.ForEach
    values: ['value1', 'value2', 'value3']
    concurrencyLimit: 0
    tasks:
      - id: log1
        type: io.kestra.plugin.core.log.Log
        message: "log1"
      
      - id: log2
        type: io.kestra.plugin.core.log.Log
        message: "log2"

      - id: log3
        type: io.kestra.plugin.core.log.Log
        message: "log3"
```

### Environment

- Kestra Version: OSS develop-full
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):
