### ISSUE TITLE
Stderr isn't shown in Kestra logs tab

### ISSUE THREAD

**Issue by KrisF-Midnight** [kestra-io/kestra#4485]
### Describe the issue

As above.
Here's the task:

```
tasks:
  - id: aws_auth
    type: io.kestra.plugin.scripts.shell.Script
    taskRunner:
      type: io.kestra.plugin.core.runner.Process
    beforeCommands:
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - ./aws/install --bin-dir ~/bin --install-dir ~/aws-cli --update
    script: |
      /home/ubuntu/bin/aws sts get-caller-identity
```

line /home/ubuntu/bin/aws sts get-caller-identity logs to stderr, but Kestra doesn't show it. 
redirecting it to stdout resolves the issue:
`/home/ubuntu/bin/aws sts get-caller-identity **2>&1**`

### Environment

- Kestra Version: 0.17.15
- Operating System (OS/Docker/Kubernetes): K8s
- Java Version (if you don't run kestra in Docker):

**Comment by anna-geller** [comment]
Hi, please try the AwsCLI task as it's intended exactly for your use case! Docs: https://kestra.io/plugins/plugin-aws/tasks/cli/io.kestra.plugin.aws.cli.awscli 

this example shows how you can redirect the output to store it as kestra outpiut:

```yaml
id: myflow
namespace: company.team
tasks:
  - id: hello
    type: io.kestra.plugin.aws.cli.AwsCLI
    accessKeyId: "{{ secret('AWS_ACCESS_KEY_ID') }}"
    secretKeyId: "{{ secret('AWS_SECRET_ACCESS_KEY') }}"
    region: "eu-central-1"
    commands:
      - aws sts get-caller-identity | tr -d ' \n' | xargs -0 -I {} echo '::{"outputs":{}}::'
```

when you run this flow, you should get it nicely parsed: 

![image](https://github.com/user-attachments/assets/168d7b95-eccf-4724-9340-b4558d399c59)
