### ISSUE TITLE
Cannot select "true" in onResume boolean inputs within the Pause task (might be general UI issue for boolean inputs)

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4497]
### Describe the issue

not critical as it technically works when you first select False :D but frustrating, we should investigate: https://share.descript.com/view/fMA3ZP87528

reproducer:
```yaml
id: myform
namespace: company.team

inputs:
  - id: resource_type
    description: Resource Type
    type: SELECT
    required: true
    defaults: Access permissions
    values:
      - Access permissions
      - SaaS application
      - Development tools (e.g., IDEs)

  - id: deadline
    type: DATE
    required: false

tasks:
  - id: send_approval_request
    type: io.kestra.plugin.notifications.slack.SlackIncomingWebhook
    url: https://reqres.in/api/slack
    payload: |
      {
        "channel": "#vacation",
        "text": "To approve the request, click on the `Resume` button here http://localhost:28080/ui/{{flow.tenantId}}/executions/{{flow.namespace}}/{{flow.id}}/{{execution.id}}"
      }

  - id: wait_for_approval
    type: io.kestra.plugin.core.flow.Pause
    onResume:
      - id: approved
        description: Whether to approve the request
        type: BOOLEAN
        defaults: true
      - id: reason
        description: Reason for approval or rejection
        type: STRING
        defaults: Approved

  - id: automate_resource_provisioning_after_approval
    type: io.kestra.plugin.core.http.Request
    uri: https://reqres.in/api/products
    method: POST
    contentType: application/json
    body: "{{ inputs.request }}"

  - id: log
    type: io.kestra.plugin.core.log.Log
    message: Status is {{ outputs.wait_for_approval.onResume.reason }}. Process finished with {{ outputs.approve.body }}
```

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):
