### ISSUE TITLE
10-second limit on the HTTP task execution

### ISSUE THREAD

**Issue by nikita-stovpak** [kestra-io/kestra#4500]
### Describe the issue

Describe the issue:

Timeout for an HTTP task cannot be increased beyond the default value.

Here is an example using the default timeout for an HTTP task. I'm making a request to localhost inside a Docker container. The request has a timeout, and it handles everything as expected.
Here's a video example: https://monosnap.com/file/hxUQHz8An6ipUvwpJFwtX56HFxkY9T

After that, I change the parameter:
First setting it to less than the default value (5 seconds). As seen in the video, the request fails faster. 
Then I set it to a higher value (20 seconds), but the request still fails at 10 seconds (which is the default value).
Video: https://monosnap.com/file/giXdmsRXx6BWb3blzATkxb0kFWJzmA

Workflow with 20s timeout: 
````
id: myflow
namespace: company.myteam
description: Save and Execute the flow

labels:
  env: dev
  project: myproject

inputs:
  - id: payload
    type: JSON
    defaults: |-
      [{"name": "kestra", "rating": "best in class"}]

tasks:
  - id: timeout_check
    type: io.kestra.plugin.core.http.Request
    uri: http://api:3000/health
    method: GET
    contentType: application/json
    timeout: PT20S


triggers:
  - id: webhook
    type: io.kestra.plugin.core.trigger.Webhook
    key: 4wjtkzwVGBM9yKnjm3yv8r
```

### Environment

- [Kestra Version:](image: kestra/kestra:latest-full)
- [Operating System]: (docker-compose)

**Comment by smunteankestra** [comment]
would this flow also confirm the issue?

id: myflowdelay
namespace: company.myteam
description: Test HTTP request with extended timeout

labels:
  env: dev
  project: myproject

inputs:
  - id: payload
    type: JSON
    defaults: |-
      [{"name": "kestra", "rating": "best in class"}]

tasks:
  - id: timeout_check
    type: io.kestra.plugin.core.http.Request
    uri: https://httpbin.org/delay/25
    method: GET
    contentType: application/json
    timeout: PT35S

triggers:
  - id: webhook
    type: io.kestra.plugin.core.trigger.Webhook
    key: 4wjtkzwVGBM9yKnjm3yv8r

**Comment by nikita-stovpak** [comment]
Yes
https://monosnap.com/direct/cevy8t28daph2jGCmmjLapvCJPjY17

**Comment by smunteankestra** [comment]
Will be handled in next release, thanks for reporting

**Comment by loicmathieu** [comment]
The `timeout` is a property to timeout a task execution at the Worker level.
If you want to configure the HTTP client timeout you should use the `options` property.

The following flow works fine:
```yaml
id: myflowdelay
namespace: company.myteam
description: Test HTTP request with extended timeout

inputs:
  - id: payload
    type: JSON
    defaults: |-
      [{"name": "kestra", "rating": "best in class"}]

tasks:
- id: timeout_check
  type: io.kestra.plugin.core.http.Request
  uri: https://httpbin.org/delay/25
  method: GET
  contentType: application/json
  options:
    readTimeout: PT35S
```
