### ISSUE TITLE
String value length (20054016) exceeds the maximum allowed 2000000

### ISSUE THREAD

**Issue by nikita-stovpak** [kestra-io/kestra#4503]
### Describe the issue

When sending a large amount of text in the body to a webhook, the workflow fails with an error.
<img width="1162" alt="image" src="https://github.com/user-attachments/assets/71bb4d59-44bf-4226-b3fe-152f4aaececf">

Workflow code:
```
id: myflow
namespace: company.myteam
description: Save and Execute the flow

labels:
  env: dev
  project: myproject

inputs:
  - id: payload
    type: JSON
    defaults: |-
      [{"name": "kestra", "rating": "best in class"}]

tasks:
  - id: timeout_check
    type: io.kestra.plugin.core.http.Request
    uri: http://api:3000/health
    method: GET
    contentType: application/json
    timeout: PT20S

triggers:
  - id: webhook
    type: io.kestra.plugin.core.trigger.Webhook
    key: 4wjtkzwVGBM9yKnjm3yv8r
```

### Environment

- [Kestra Version:](image: kestra/kestra:latest-full)
- [Operating System]: (docker-compose)

**Comment by anna-geller** [comment]
hey, thanks for the issue. when it comes to webhooks, they are usually meant to carry payloads that are limited in size. if you need to pass a large amount of data to your workflow, we'd recommend adding a `FILE` type `input` and passing the file to the API call. Check this guide https://kestra.io/docs/workflow-components/execution#execute-a-flow-via-an-api-call 

Example flow:

```yaml
id: large_json_payload
namespace: company.team

inputs:
  - id: myCustomFileInput
    type: FILE

tasks:
  - id: hello
    type: io.kestra.plugin.scripts.shell.Commands
    inputFiles:
      myfile.json: "{{ inputs.myCustomFileInput }}"
    taskRunner:
      type: io.kestra.plugin.core.runner.Process
    commands:
      - cat myfile.json
```

assuming you have a file myfile.json in the current wdir, invoke the flow via:

```bash
curl -X POST -F "files=@./myfile.json;filename=myCustomFileInput" 'http://localhost:28080/api/v1/executions/company.team/large_json_payload'
```

While we technically _could_ consider extending the payload of the webhook, it would be generally not a good practice for 2 reasons:
- those large payloads would be stored directly in the DB backend, cluttering your valuable DB space
- privacy

If you pass it as a file instead, it will be stored in internal storage. We do have an issue to allow passing file inputs to a webhook, you can follow the progress here https://github.com/kestra-io/kestra/issues/1965 

Given it's intended behavior, I'll close the issue and you can add more use cases on #1965
