### ISSUE TITLE
Killing a loop execution kills Gantt and future flow executions

### ISSUE THREAD

**Issue by smunteankestra** [kestra-io/kestra#4510]
### Describe the issue

Step 1: Run the flow below for a couple of seconds
Step 2: Kill the Execution
Step 3: Start the execution with 1 loop instead of 800

Expected - to run execution successfully
Actual - Execution is stuck  

Flow:
```yaml
id: chucknorris
namespace: chucknorris.chucknorris.chucknorris.chucknorris.chucknorris
description: Save and Execute the flow

labels:
  env: dev
  project: myproject
tasks:
  - id: loop_jokes
    type: io.kestra.plugin.core.flow.EachParallel
    description: "Loop to request random jokes 200 times."
    value: |
      {{ range(1, 801) }}
    tasks:
      - id: timeout_check
        type: io.kestra.plugin.core.http.Request
        uri: https://api.chucknorris.io/jokes/random
        method: GET
        contentType: application/json
        timeout: PT20S
```

### Environment

- Kestra Version: 1.8
- Operating System (Docker):
- Java Version (Docker):
