### ISSUE TITLE
The Editor complains about filesMap property being in the wrong type (Incorrect type. Expected "array | string".)

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4516]
### Describe the issue

![image](https://github.com/user-attachments/assets/7186a89c-83c5-47f6-bdb9-5f16fb2f6454)

reproducer:

```yaml
id: aws_batch_runner
namespace: company.team

inputs:
  - id: python_script
    type: STRING
    defaults: |
      import platform
      import socket
      import sys
      import json
      from kestra import Kestra
      
      print("Hello from AWS Batch and kestra!")
      
      
      def print_environment_info():
          print(f"Host's network name: {platform.node()}")
          print(f"Python version: {platform.python_version()}")
          print(f"Platform information (instance type): {platform.platform()}")
          print(f"OS/Arch: {sys.platform}/{platform.machine()}")
      
          env_info = {
              "host": platform.node(),
              "platform": platform.platform(),
              "OS": sys.platform,
              "python_version": platform.python_version(),
          }
          Kestra.outputs(env_info)
      
          filename = "{{ workingDir }}/environment_info.json"
          with open(filename, "w") as json_file:
              json.dump(env_info, json_file, indent=4)
      
      
      if __name__ == "__main__":
          print_environment_info()
tasks:
  - id: py
    type: io.kestra.plugin.core.namespace.UploadFiles
    filesMap:
      script.py: "{{ inputs.python_script }}"
```

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by anna-geller** [comment]
since it should be a path to a file rather than a string, I guess the right reproducer would be:

```yaml
id: aws_batch_runner
namespace: company.team

inputs:
  - id: python_script
    type: FILE

tasks:
  - id: py
    type: io.kestra.plugin.core.namespace.UploadFiles
    namespace: company.team
    filesMap:
      main.py: "{{ inputs.python_script }}"
```

still the same UI warning:

![image](https://github.com/user-attachments/assets/b77ba442-5206-4e6e-81f3-b790e9fabbbf)
