### ISSUE TITLE
containerImage ignored in script task

### ISSUE THREAD

**Issue by paulgrainger85** [kestra-io/kestra#4525]
### Describe the issue

Execute tutorial flow `data_engineering_pipeline` 

Flow fails on transform task. It appears to be pulling `kestrapy` rather than using the supplied alpine image
```
  - id: transform
    type: io.kestra.plugin.scripts.python.Script
    containerImage: python:3.11-alpine
    inputFiles:
      data.json: "{{ outputs.extract.uri }}"
    outputFiles:
      - "*.json"
    env:
      COLUMNS_TO_KEEP: "{{ inputs.columns_to_keep }}"
    script: |
      ...
```
![image](https://github.com/user-attachments/assets/cf5a6884-c02b-4da4-860c-ae4050b64e2e)

### Environment

- Kestra Version: v0.18 (develop) 
- Operating System: Mac M2 (ARM), via docker
