### ISSUE TITLE
[KV STORE] Task Set only accepts value of type String if not using expression

### ISSUE THREAD

**Issue by fhussonnois** [kestra-io/kestra#4529]
### Describe the issue

The `io.kestra.plugin.core.kv.Set` task only accepts `value` of type String while a K/V can accepts multiple types.

It's not possible to use that flow: 

```
id: myflow
namespace: company.team
tasks:
  - id: hello
    type: io.kestra.plugin.core.kv.Set
    key: hello
    value: 
      foo: bar
      bar: foo
```

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):
