### ISSUE TITLE
WorkingDir with gitClone raise an error

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#4555]
### Describe the issue

![image](https://github.com/user-attachments/assets/cdd3807a-0b5a-41f2-9944-687e9d97e464)

```
id: transform
namespace: certification.fundamentals.project

labels:
  certification: fundamentals

tasks:
  - id: git
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      - id: clone_repository
        type: io.kestra.plugin.git.Clone
        url: https://github.com/Ben8t/dbt_weather.git
        branch: main

      ```

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):
