### ISSUE TITLE
Bash task with Docker runner can miss some log

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#456]
### Actual Behaviour

We have some situations that some logs are missing at the end of the bash executions.
Sometime we also have this error : 
![image](https://user-images.githubusercontent.com/2064609/152137756-298c6b0c-76ef-4c88-b4fd-d7f685dcb664.png)

### Environment Information

- Kestra Version: 0.3.2
- Operating System (OS / Docker / Kubernetes): k8s
- Java Version (If not docker): 11

**Comment by anna-geller** [comment]
community example to reproduce

```yaml
id: "test-node"
namespace: "com.acxiom.vivane"
tasks:
  - id: task-node-1
    type: io.kestra.core.tasks.scripts.Node
    inputFiles:
      main.js: |
        const Kestra = require("./kestra");
        const kestraNode = require('kestra-custom').KestraNode;
        const agent = kestraNode.sayHello();
        Kestra.outputs({agent});
      package.json: |
        {
          "dependencies": {
            "kestra-custom": "/app"
          }
        }
    runner: DOCKER
    dockerOptions: 
      # dockerHost: tcp://localhost:5000
      image: localhost:5000/kestra/custom:latest
      pullImage: false

  - id: task-log-1
    type: io.kestra.core.tasks.log.Log
    message: "{{outputs['task-node-1'].vars}}"

  - id: task-node-2
    type: io.kestra.core.tasks.scripts.Node
    inputFiles:
      main.js: |
        const kestraNode = require('kestra-custom').KestraNode;
        kestraNode.handshake({{outputs['task-node-1'].vars.agent}});
      package.json: |
        {
          "dependencies": {
            "kestra-custom": "/app"
          }
        }
    runner: DOCKER
    dockerOptions: 
      # dockerHost: tcp://localhost:5000
      image: localhost:5000/kestra/custom:latest
      pullImage: false

  - id: task-node-3
    type: io.kestra.core.tasks.scripts.Node
    inputFiles:
      main.js: |
        const kestraNode = require('kestra-custom').KestraNode;
        kestraNode.handshake({{outputs['task-node-1'].vars.agent}});
      package.json: |
        {
          "dependencies": {
            "kestra-custom": "/app"
          }
        }
    runner: DOCKER
    dockerOptions: 
      # dockerHost: tcp://localhost:5000
      image: localhost:5000/kestra/custom:latest
      pullImage: false

  - id: task-node-4
    type: io.kestra.core.tasks.scripts.Node
    inputFiles:
      main.js: |
        const kestraNode = require('kestra-custom').KestraNode;
        kestraNode.handshake({{outputs['task-node-1'].vars.agent}});
      package.json: |
        {
          "dependencies": {
            "kestra-custom": "/app"
          }
        }
    runner: DOCKER
    dockerOptions: 
      # dockerHost: tcp://localhost:5000
      image: localhost:5000/kestra/custom:latest
      pullImage: false
```

node code:

```js
const _ = require('lodash');
const Chance = require('chance');
const chance = new Chance();

class KestraNode {
    sayHello() {
        const id = chance.guid();
        console.log(`Hello from ${_.camelCase('Kestra Custom')} (${id}).`);

        return {
            id,
            name: 'KestraNode',
            date: new Date(),
        };
    }

    handshake(agent) {
        console.log(`Handshaking with [${agent.id}] ${agent.name} at ${agent.date}`);
    }
}

module.exports = {
    KestraNode: new KestraNode()
};
```
