### ISSUE TITLE
Problem with saving the flow after adjusting parameter values via low-code UI forms

### ISSUE THREAD

**Issue by nikita-stovpak** [kestra-io/kestra#4564]
### Describe the issue

If I want to save changes HTTP task timeout with other changes, I can do that. If I try to update ONLY the timeout, the save does not happen.

https://monosnap.com/file/NRObOzjzKXN2qFs07QletzXSSV8paV

code:

```
id: myflowdelay
namespace: company.myteam
description: Test HTTP request with extended timeout

labels:
  env: dev
  project: myproject

inputs:
  - id: payload
    type: JSON
    defaults:
    [{"name": "kestra", "rating": "best in class"}]
    tasks:

  - id: timeout_check
    type: io.kestra.plugin.core.http.Request
    uri: https://httpbin.org/delay/25
    method: GET
    contentType: application/json
    timeout: PT35S
triggers:

  - id: webhook
    type: io.kestra.plugin.core.trigger.Webhook
    key: 4wjtkzwVGBM9yKnjm3yv8r
```

### Environment

- [Kestra Version:](image: kestra/kestra:latest-full)
- [Operating System]: (docker-compose)
