### ISSUE TITLE
Low code editor shouldn't add empty placeholder values for optional properties like `else` in the `If` task

### ISSUE THREAD

**Issue by johnkm516** [kestra-io/kestra#4570]
### Describe the issue

1) Create any `io.kestra.plugin.core.flow.If` flow block.
2) The low code editor creates an empty "else" attribute by default if it's not otherwise input by the user. 
3) Run the flow.
4) If block is stuck in running state indefinitely if the If condition returns false. 

### Environment

- Kestra Version: 0.18 SNAPSHOT (8/6 last pulled)
- Operating System (OS/Docker/Kubernetes): Docker

**Comment by anna-geller** [comment]
can you share a flow in which we can reproduce the issue? 

overall, there seems to be no issue in the If block:

```yaml
id: myflow
namespace: company.team
tasks:
  - id: check
    type: io.kestra.plugin.core.flow.If
    condition: “{{ 1 == 2 }}“
    then:
      - id: iftrue
        type: io.kestra.plugin.core.log.Log
        message: it's true
    else:
      - id: iffalse
        type: io.kestra.plugin.core.log.Log
        message: it's false
```

perhaps some low-code editor issue? can you share a screen-share recording or some screenshots?

**Comment by johnkm516** [comment]
> can you share a flow in which we can reproduce the issue?
> 
> overall, there seems to be no issue in the If block:
> 
> ```yaml
> id: myflow
> namespace: company.team
> tasks:
>   - id: check
>     type: io.kestra.plugin.core.flow.If
>     condition: “{{ 1 == 2 }}“
>     then:
>       - id: iftrue
>         type: io.kestra.plugin.core.log.Log
>         message: it's true
>     else:
>       - id: iffalse
>         type: io.kestra.plugin.core.log.Log
>         message: it's false
> ```
> 
> perhaps some low-code editor issue? can you share a screen-share recording or some screenshots?

Hi @anna-geller 

The else block has to be empty like this : 

```
  - id: ifNotBlock
    type: io.kestra.plugin.core.flow.If
    errors: []
    condition: "{{1 == 2}}"
    else: []
    then:
      - id: asdf
        type: io.kestra.plugin.core.log.Log
        message: "1"
```

As a separate issue with a lot of the other low code tasks, in general I think if the attribute is non-mandatory it should not add the attribute to the flow YAML, unless the attribute is filled in by a default value. 

For example, ```io.kestra.plugin.core.execution.PurgeExecutions``` creates an empty ```states``` attribute in the YAML code by default if not otherwise set by the user in the low code editor. The empty ```states``` field makes it so that the task purges nothing, it would work fine if this field is deleted entirely in the YAML. I cannot list all of the tasks off the top of my head where non-mandatory values created in the YAML by the low code editor results in unexpected behavior, but there's quite a lot of these cases.

**Comment by anna-geller** [comment]
yeah, it seems we have two issues here:
1. Low code editor shouldn't add optional placeholder values 
2. If block actually has a bug — this flow should generate an error rather than being stuck in Running state -- I opened a separate issue for this one https://github.com/kestra-io/kestra/issues/4601

**Comment by MilosPaunovic** [comment]
@Ben8t Can you help me with reproducing this (or close if it's alright now) as everything I've tried so far ends up with it working properly?

**Comment by Ben8t** [comment]
@MilosPaunovic yes same here; not able to reproduce (I'm on 0.18.4). flows is created without any else block if not inputed by user:

```yaml
id: mytestflow
namespace: kestra.sandbox
tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀
  - id: if-state
    type: io.kestra.plugin.core.flow.If
    condition: 1 == 1
    then:
      - id: test1
        type: io.kestra.plugin.core.log.Log
        message: test
```

I'm closing the issue for now. @johnkm516 do not hesitate to reach out if you still see the error
