### ISSUE TITLE
SQS Trigger fails with error

### ISSUE THREAD

**Issue by paulgrainger85** [kestra-io/kestra#4598]
### Describe the issue

Reproducer flow along with error message:

flow:
```
id: sqs
namespace: demo

tasks:
  - id: log_trigger
    type: io.kestra.plugin.core.log.Log
    message: "{{trigger.data}}"

triggers:
  - id: "realtime_trigger"
    type: io.kestra.plugin.aws.sqs.RealtimeTrigger
    accessKeyId: "{{ secret('AWS_SQS_ACCESS_KEY') }}"
    secretKeyId: "{{ secret('AWS_SQS_SECRET_KEY') }}"
    region: "eu-west-3"
    queueUrl: "https://sqs.eu-west-3.amazonaws.com/707969873520/pg-kestra-test"
    serdeType: STRING
```

Error
```
kestra-1    | 2024-08-07 16:00:11,325 WARN  WorkerThread flow.sqs.realtime_trigger [tenant: default] [namespace: demo] [flow: sqs] [trigger: realtime_trigger] [date: 2024-08-07T16:00:09.898Z] Trigger evaluation failed in the worker with error: throttlingBackoffStrategy must not be null.
kestra-1    | java.lang.NullPointerException: throttlingBackoffStrategy must not be null.
kestra-1    | 	at software.amazon.awssdk.utils.Validate.paramNotNull(Validate.java:156)
kestra-1    | 	at software.amazon.awssdk.retries.internal.BaseRetryStrategy.<init>(BaseRetryStrategy.java:65)
kestra-1    | 	at software.amazon.awssdk.retries.internal.DefaultStandardRetryStrategy.<init>(DefaultStandardRetryStrategy.java:31)
kestra-1    | 	at software.amazon.awssdk.retries.internal.DefaultStandardRetryStrategy$Builder.build(DefaultStandardRetryStrategy.java:100)
kestra-1    | 	at io.kestra.plugin.aws.sqs.AbstractSqs.lambda$asyncClient$0(AbstractSqs.java:63)
kestra-1    | 	at software.amazon.awssdk.utils.builder.SdkBuilder.applyMutation(SdkBuilder.java:61)
kestra-1    | 	at software.amazon.awssdk.core.client.builder.SdkClientBuilder.overrideConfiguration(SdkClientBuilder.java:51)
kestra-1    | 	at io.kestra.plugin.aws.sqs.AbstractSqs.asyncClient(AbstractSqs.java:55)
kestra-1    | 	at io.kestra.plugin.aws.sqs.RealtimeTrigger.lambda$publisher$4(RealtimeTrigger.java:146)
kestra-1    | 	at reactor.core.publisher.FluxCreate.subscribe(FluxCreate.java:97)
kestra-1    | 	at reactor.core.publisher.Flux.subscribe(Flux.java:8840)
kestra-1    | 	at reactor.core.publisher.Flux.blockLast(Flux.java:2816)
kestra-1    | 	at io.kestra.core.runners.WorkerTriggerRealtimeThread.doRun(WorkerTriggerRealtimeThread.java:55)
kestra-1    | 	at io.kestra.core.runners.AbstractWorkerThread.run(AbstractWorkerThread.java:57)
```

### Environment

- Kestra Version: v0.18.0
- Operating System Docker (Mac M2)
