### ISSUE TITLE
Generate an error if `then` or `else` blocks are set to an empty array in the `If` task 

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4601]
### Describe the issue

repro:

```yaml
id: myflow
namespace: company.team
tasks:
  - id: check
    type: io.kestra.plugin.core.flow.If
    condition: 0
    else: []
    errors: []
    then:
      - id: iftrue
        type: io.kestra.plugin.core.log.Log
        message: it's true
```

This flow will be stuck in a running state — it should either:
1. fail to be saved directly from the UI (syntax validation error)
2. fail immediately at runtime as soon as the condition evaluates to false (and the `else` block is `[]`)

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):
