### ISSUE TITLE
Chat with your Elasticsearch data Blueprint.

### ISSUE THREAD

**Issue by Adematics** [kestra-io/kestra#4608]
### Blueprint title

Chat with your ElasticSearch data using the OpenAI plugin.

### Source code

```yaml
id: "chat_with_your_data"
namespace: "chat.demo"

inputs:
  - id: question
    type: STRING
    defaults: How do I join the course after it has started?

  - id: select_a_zoomcamp
    type: ENUM
    defaults: "data-engineering-zoomcamp"
    values:
      - data-engineering-zoomcamp
      - machine-learning-zoomcamp
      - data-science-zoomcamp


tasks:
  - id: "search"
    type: "io.kestra.plugin.elasticsearch.Search"
    connection:
      hosts: 
        # Enter the host of your Elasticsearch database here "http://localhost:9200/"
        - "http://172.17.0.1:9200/" 
    indexes:
      - "course_questions"
    request:
      size: 5
      query: 
        bool:
          must:
            multi_match:
              query: "{{inputs.question}}"
              fields: ["question^3", "text", "section"]
              type: "best_fields"
          filter:
            term:
              course: "{{inputs.select_a_zoomcamp}}"

  - id: context_template
    type: io.kestra.plugin.core.debug.Return
    format: >
      {% for row in outputs.search.rows %}
        Section: {{ row.section }}
        Question: {{ row.question }}
        Text: {{ row.text }}

      {% endfor %}


  - id: generate_response
    type: io.kestra.plugin.openai.ChatCompletion
    # Enter your OpenAI API key here
    apiKey: sk-proj-I0xuxxxxxxxxxxxx
    model: gpt-4o-mini
    maxTokens: 500
    prompt: |
      You're a course teaching assistant. Answer the user QUESTION based on CONTEXT - the documents retrieved from our FAQ database. 
      Only use the facts from the CONTEXT. If the CONTEXT doesn't contain the answer, return "NONE"
      
      QUESTION: {{ inputs.question }}

      CONTEXT:
      {{ outputs.context_template.value }}

    
  - id: log_output
    type: io.kestra.plugin.core.log.Log
    message: "{{ outputs.generate_response.choices | jq('.[].message.content') | first }}"
```

### About this blueprint

This flow will:
1. Ask for an input to search the Elasticsearch database.
2. Search the database based on the input given.
3. Return the output of the search as a context template.
4. Generate a response based on the input and context template using the OpenAI API plugin.

It uses the public dataset from the [Datatalks Zoomcamp Frequently Asked Questions (FAQ)](https://raw.githubusercontent.com/alexeygrigorev/llm-rag-workshop/main/notebooks/documents.json).

To set up the Elasticsearch database locally for development with Docker use the following command below:

```bash
docker run -it \
    --rm \
    --name elasticsearch \
    -m 2G \
    -p 9200:9200 \
    -p 9300:9300 \
    -e "discovery.type=single-node" \
    -e "xpack.security.enabled=false" \
    docker.elastic.co/elasticsearch/elasticsearch:8.14.3
```
> [!NOTE]
>
>  If you get a `"Elasticsearch has quit unexpectedly"` message, you can use the `-m` field to increase the memory limit of your container.
> 

The Elasticsearch database uses the `index`  to manage your data structure and search efficiency. To create a sample `course_questions` index with mapping properties for the FAQ dataset, use the following command:

```bash
curl -X PUT "http://localhost:9200/course_questions" -H "Content-Type: application/json" -d'
{
 "settings": {
   "number_of_shards": 1,
   "number_of_replicas": 0
 },
 "mappings": {
   "properties": {
     "text": { "type": "text" },
     "section": { "type": "text" },
     "question": { "type": "text" },
     "course": { "type": "keyword" }
   }
 }
}'

```

Once your sample index is created, load the Datatalks FAQ dataset into the Elasticsearch database.

```bash
curl -X POST "http://localhost:9200/course_questions/_bulk" \
-H "Content-Type: application/json" \
--data-binary @<(curl -s https://raw.githubusercontent.com/Adematics/llm-zoomcamp-workshop-module-1/main/processed_documents.json | jq -c '.[] | {"index":{}}, .')

```

To get access to the OpenAI API key:

- Sign up to [OpenAI if you don't have an account](https://platform.openai.com/) 
- Go to the [API key section](https://platform.openai.com/api-keys)
- Create a new key and copy it

### Tags (optional)

- AI 
- ElasticSearch 
- OpenAI
