### ISSUE TITLE
MQTT Realtime Trigger with an ExpressionCondition on trigger.message.payload can lead to a crash

### ISSUE THREAD

**Issue by 8perezm** [kestra-io/kestra#4629]
### Describe the issue

Whilst developing a flow using flow.energy-notifier.mqtt-trigger.  I placed in an expressioncondition that the system didn't like, which caused the container to crash.  Restarting the container just triggers the flow again which causes another crash.  So I'm not able to get the application running again.

[kestra-standalone.log](https://github.com/user-attachments/files/16576481/kestra-standalone.log)

### Environment

- Kestra Version: 0.18
- Operating System (Kubernetes):

**Comment by loicmathieu** [comment]
Hi,
Can you give us a flow reproducer in YAML?
You can redact any secrets or give a simplified version if needed.

**Comment by 8perezm** [comment]
The expression which caused the application to crash was {{ trigger.message.payload | json_decode | get('Energy.Power') > 35 }}
Admittedly I used AI to create the expression because there wasn't documentation on the website to instruct how to use it. https://kestra.io/plugins/core/conditions/io.kestra.plugin.core.condition.expressioncondition

I have managed to log into the postgres database and I removed the expression from the flow, then restarting the pod which allowed the kestra standalone to correctly start without exceptions.

I've attached the yaml. 
[energy.txt](https://github.com/user-attachments/files/16579879/energy.txt)

**Comment by loicmathieu** [comment]
I can reproduce it with this flow example

```yaml
id: trigger-crash
namespace: company.team

triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "* * * * *"
    conditions:
      - type: io.kestra.plugin.core.condition.ExpressionCondition
        expression: "{{ trigger.message.payload | json_decode | get('Energy.Power') > 35 }}"
tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀
```
