### ISSUE TITLE
Wrong evaluation of If condition

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4640]
### Describe the issue

```yaml
id: if
namespace: company.team
tasks:
  - id: check
    type: io.kestra.plugin.core.flow.If
    # Boolean coercion allows 0, -0, null and ‘’ to evaluate to false, all other values will evaluate to true.
    condition: “{{ 1 == 2 }}“
    then:
      - id: iftrue
        type: io.kestra.plugin.core.log.Log
        message: it's true
    else:
      - id: iffalse
        type: io.kestra.plugin.core.log.Log
        message: it's false
```

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by loicmathieu** [comment]
This is because your fow uses a non-standard double-quote so the result is a false String with a non-standard double-quote: `“false“`.

The following works:
```yaml
id: if
namespace: company.team
tasks:
  - id: check
    type: io.kestra.plugin.core.flow.If
    # Boolean coercion allows 0, -0, null and ‘’ to evaluate to false, all other values will evaluate to true.
    condition: "{{ 1 == 2 }}"
    then:
      - id: iftrue
        type: io.kestra.plugin.core.log.Log
        message: it's true
    else:
      - id: iffalse
        type: io.kestra.plugin.core.log.Log
        message: it's false
```
