### ISSUE TITLE
Triggers logs - flicker on page refresh 

### ISSUE THREAD

**Issue by smunteankestra** [kestra-io/kestra#4648]
### Describe the issue

Step 1 : Run the flow bellow (basically it logs a string every minute)
Step 2: Navigate to triggers (on the same flow)
Step 3 : Refresh the page/turn on Autorefresh 

Expected: See Logs: on start of the trigger, then the message 
Actual: logs flicker 

Flow: 

```yaml
id: APIFlow_b7795389-449a-43ed-bc3f-ade9ad2c4c0c
namespace: tutorial
description: A simple flow to test real-time triggers and tasks.
tasks:
- id: echo
  type: io.kestra.plugin.core.log.Log
  message: "This flow was triggered at {{ trigger.date }}"
- id: if_large
  type: io.kestra.plugin.core.flow.If
  condition: "{{ 1 == 1 }}"
  then:
  - id: log_notify
    type: io.kestra.plugin.core.log.Log
    message: "Condition met: 1 is greater than or equal to 1"
  else:
  - id: log_no_notify
    type: io.kestra.plugin.core.log.Log
    message: "Condition not met: 1 is less than 1"
triggers:
- id: schedule
  type: io.kestra.plugin.core.trigger.Schedule
  cron: '* * * * *'
```

### Environment

- Kestra Version: develop
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):
