### ISSUE TITLE
No results for the current selection - replace with "No logs emitted"

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4654]
### Describe the issue

to reproduce, add any schedule trigger that won't fire any executions immediately:

```yaml
id: daily_flow
namespace: company.team
tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀

triggers:
  - id: daily
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 9 * * *"
```

You'll see a confusing info-box:

![image](https://github.com/user-attachments/assets/e79162e4-81ea-44ea-a4c3-79818233a0d0)

Sth like: "No logs emitted so far" would be easier to understand

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):
