### ISSUE TITLE
Calling WaitFor task from If block returns a `TaskRun.getOutputs() is null` error

### ISSUE THREAD

**Issue by paulgrainger85** [kestra-io/kestra#4657]
If `WaitFor` is invoked inside an `If` block, it will fail with the following error:

```Java
Unable to resolve state from the Flowable task: 
Cannot invoke “java.util.Map.get(Object)” 
because the return value of 
“io.kestra.core.models.executions.TaskRun.getOutputs()” is null
```

We should fix it 🐛 

Reproducer:

```yaml
id: http_wait
namespace: demo

tasks:
  - id: if
    type: io.kestra.plugin.core.flow.If
    condition: "{{1 == 1}}"
    then:
    - id: wait
      type: io.kestra.plugin.core.flow.WaitFor
      checkFrequency:
        interval: PT3S
        maxDuration: PT90S
      condition: "{{ outputs.users.body | jq ('.[].username') | first == 'Bret' or outputs.users.body != null}}"
      tasks:
      - id: users
        type: io.kestra.plugin.core.http.Request
        uri: "https://jsonplaceholder.typicode.com/users"
        method: GET
```

**Comment by anna-geller** [comment]
A workaround with a subflow:

```yaml
id: http_wait
namespace: demo

tasks:
  - id: if
    type: io.kestra.plugin.core.flow.If
    condition: "{{1 == 1}}"
    then:
      - id: subflow
        type: io.kestra.plugin.core.flow.Subflow
        namespace: demo
        flowId: child
```
child:
```yaml
id: child
namespace: demo

tasks:
  - id: wait
    type: io.kestra.plugin.core.flow.WaitFor
    checkFrequency:
      interval: PT3S
      maxDuration: PT90S
    condition: "{{ outputs.users.body | jq ('.[].username') | first == 'Bret' or outputs.users.body != null}}"
    tasks:
    - id: users
      type: io.kestra.plugin.core.http.Request
      uri: "https://jsonplaceholder.typicode.com/users"
      method: GET
```
