### ISSUE TITLE
Input validation error regression

### ISSUE THREAD

**Issue by paulgrainger85** [kestra-io/kestra#4673]
### Describe the issue

Previously this was the error received when input validation failed 👍
![image](https://github.com/user-attachments/assets/b65f2564-86da-49c6-94e1-93c8113c1598)

As of v0.18 this is the error seen now 👎
![image](https://github.com/user-attachments/assets/b7e79706-191b-42ca-a762-cbb89a56d342)

Sample flow
```
id: regex-input
namespace: demo

inputs:
  - id: age
    type: INT
    defaults: 42
    required: false
    min: 18
    max: 64

  - id: user
    type: STRING
    defaults: student
    required: false
    validator: ^student(\d+)?$

tasks:
  - id: validator
    type: io.kestra.plugin.core.log.Log
    message: User {{ inputs.user }}, age {{ inputs.age }}
```

### Environment

- Kestra Version: v0.18.2
- Operating System: Docker
