### ISSUE TITLE
io.kestra.plugin.git.PushFlows ignores result of PushCommand.call()

### ISSUE THREAD

**Issue by lburja** [kestra-io/kestra#4680]
### Describe the issue

I have a situation where the `PushFlows` task finishes successfully, but I see no commits in the remote git repo (BitBucket).

Here is a screenshot from Kestra, where the log output claims that changes were pushed:
<img width="1027" alt="image" src="https://github.com/user-attachments/assets/fb4cef02-f46a-4a03-99eb-6b0e2480b351">

When I check the remote repository, no commits have been made in fact.

By looking in the source code, I see that the result of `PushCommand.call()` is ignored:
![image](https://github.com/user-attachments/assets/e492b7a4-d36f-4263-9ee2-db7d1c1da63e)

According to this StackOverflow question, not all push errors result in an exception being thrown, some of them are returned as push results : https://stackoverflow.com/questions/51140394/jgit-push-wont-fail-when-push-is-impossible
I believe that the push fails in some way, but there's non way to see the error in Kestra.

I would expect at the very least that any push result is logged. Even better, it would be returned as an output, and the task would throw an exception if any update was rejected.

### Environment

- Kestra Version: v0.18.2
- Operating System (OS/Docker/Kubernetes): Kubernetes
- Java Version (if you don't run kestra in Docker): n/a

**Comment by anna-geller** [comment]
Can you share the exact flow you were using? Also, can you say more about your setup? Is your Git VCS self-hosted and if so, can you confirm you can reach it from your kestra container? Do you see any server logs that can be helpful to reproduce this?

We should certainly fail the task if something fails to be pushed

**Comment by lburja** [comment]
@anna-geller Yes, I can share the flow, it's pretty simple:

```
id: git-push-flows
namespace: git

pluginDefaults:
  - type: io.kestra.plugin.git.PushFlows
    values:
      url: https://dpl.cis.consilium.europa.eu/bitbucket/scm/gscdp/data-platform.git
      branch: master
      password: "....redacted...."
      username: vasile-lucian.burja@consilium.europa.eu
      includeChildNamespaces: true 

tasks:
  - id: commit-and-push-git
    type: io.kestra.plugin.git.PushFlows
    gitDirectory: kestra/git-sync/flows/git
    sourceNamespace: git
    commitMessage: Latest flows in namespace git
```

We have indeed a self-hosted BitBucket. It's reachable from Kestra, since I can do `SyncFlows` successfully.

There are some rules for commits, for example unsigned commits are rejected. In this case, maybe the error is that the commit is unsigned. Or maybe something else.

The point of the bug report is that Kestra doesn't log any errors if the push is rejected. If I saw the reject message, I could fix it (e.g., disabling in BitBucket the requirement for signed commits for this particular repo).
