### ISSUE TITLE
Metrics are not rendered

### ISSUE THREAD

**Issue by corentinghigny** [kestra-io/kestra#47]
I get stuff like
```yaml
2020-01-29 17:11:24,162 TRACE mory-queue-0 .bq-load-stg Metrics
- name: output.rows
  tags:
    destination_table: '{{ globals.projects-stg }}.samples.{{ flow.id }}_v1_{{ execution.id
      }}'
    projectId: my-project-dev
    location: EU
```

Output in my Metrics. it would be nice if it was rendered
