### ISSUE TITLE
Add a Supabase plugin

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4711]
![image](https://github.com/user-attachments/assets/fb012bd2-e22d-45d3-b4ce-0599f1a54e95)

**Comment by Cansiano** [comment]
preferable supabase features:
create project
create table ( or have option to run sql with the create table commands)
change table 
get table info (scheme)
read data from table (sql query)
add rows into table (sql query)
delete rows
update rows
add files to storage
download files from storage
get file info from storage

**Comment by shrutimantri** [comment]
We can connect to Supabase using Postgres driver.
Hence, we can achieve all the table and trigger related operations with Postgres plugin.

When it comes to Supabase storage, it is s3-compatible.
Hence, we can use minio plugin for all storage related operations.

**Comment by aninditamitro** [comment]
@anna-geller I would like to contribute to this issue. Please assign it to me if no one else is looking into it.

**Comment by anna-geller** [comment]
Assigned, thanks @aninditamitro 🎉

**Comment by aninditamitro** [comment]
@anna-geller Thank you.

**Comment by MilosPaunovic** [comment]
Hi @aninditamitro,

Since there hasn't been any progress on the issue, I've unassigned you for now. If you decide to work on it and open a PR, let me know, and I'll be happy to reassign it to you.

In the meantime, the issue is open for anyone in the community who would like to take it on! 🚀

**Comment by yairyairyair** [comment]
Can we please add supabase as triggers as well? Maybe via supabase realtime but preffered via supabase db functions.

For example when a row is inserted in supabase update me via slack

**Comment by anna-geller** [comment]
Given that Supabase is to a large extent compatible with Postgres, we'd need **specific** use cases for which the regular Postgres plugin is not sufficient 

I believe this might work for your use case @yairyairyair, can you try? 

```yaml
id: send_slack_alert_when_new_row
namespace: company.team

tasks:
  - id: slack
    type: io.kestra.plugin.notifications.slack.SlackIncomingWebhook
    url: https://mywebhook/xxx/xxx
    payload: |
      {
        "text": "got a new row {{ trigger.data }}"
      }

triggers:
  - id: supabase_new_row
    type: io.kestra.plugin.debezium.postgres.RealtimeTrigger
```
