### ISSUE TITLE
Setting keystore value from Variables

### ISSUE THREAD

**Issue by passerini** [kestra-io/kestra#4722]
### Issue description

I don't know exactly if it's an error but I'll report the case. 
Setting a json key in key store getting value form vars:

```
id: testing_json_ks
namespace: dev

variables:
  key_name_1: "value1"

tasks:
  - id: set_json_key
    type: io.kestra.plugin.core.kv.Set
    key: new_namespace_key
    value: |
      {
        "key1": "{{ vars.key_name_1}}"
      }
    overwrite: true
```
    
return error: "Tried to add java.lang.String to java.lang.String"

**Comment by Ben8t** [comment]
These work

```yaml
id: testing_json_ks
namespace: kestra.sandbox

variables:
  key_name_1: '{"key1": "value1"}'

tasks:
  - id: set_json_key
    type: io.kestra.plugin.core.kv.Set
    key: new_namespace_key
    value: '{{ vars.key_name_1 }}'
    overwrite: true
```

```yaml
id: testing_json_ks
namespace: kestra.sandbox

variables:
  key_name_1: "value1"

tasks:
  - id: set_json_key
    type: io.kestra.plugin.core.kv.Set
    key: key1
    value: '{{ vars.key_name_1 }}'
    overwrite: true
```

and also from the documentation

```yaml
id: kv_json_flow
namespace: company.team

tasks:
  - id: set_json_kv
    type: io.kestra.plugin.core.kv.Set
    key: favorite_song
    value: |
      {
        "author": "Rick Astley",
        "song": "Never Gonna Give You Up",
        "album": {
          "name": "Whenever You Need Somebody",
          "release_date": "1987-11-16"
        }
      }

  - id: parse_json_kv
    type: io.kestra.plugin.core.log.Log
    message:
      - "Author: {{ json(kv('favorite_song')).author }}"
      - "Song: {{ json(kv('favorite_song')).song }}"
      - "Album name: {{ json(kv('favorite_song')).album.name }}"
      - "Album release date: {{ json(kv('favorite_song')).album.release_date }}"

  - id: get
    type: io.kestra.plugin.core.kv.Get
    key: favorite_song

  - id: parse_json_from_kv
    type: io.kestra.plugin.core.log.Log
    message: "Country: {{ json(outputs.get.value).album.name }}"
```

However using pebble inside JSON type KV value raise the issue noticed by @passerini

**Comment by Ben8t** [comment]
UPDATE: finally got a workaround

```yaml
id: testing_json_ks2
namespace: kestra.sandbox

variables:
  key_name_1: "value1"
  key_name_2: "value2"

tasks:

  - id: test
    type: io.kestra.plugin.core.output.OutputValues
    values:
      data: |
        {
        "key1": "{{ vars.key_name_1 }}",
        "key2": "{{ vars.key_name_2 }}",
        "client_id": "001"
        }

  - id: set_json_key
    type: io.kestra.plugin.core.kv.Set
    key: new_namespace_key
    value: '{{ outputs.test.values.data }}'
    overwrite: true

  - id: read
    type: io.kestra.plugin.core.log.Log
    message: "{{kv('new_namespace_key')}}"
```

Still make sense IMO to be able to do this directly in kv.Set task
