### ISSUE TITLE
Cannot save the flow edited from Topology due to empty array 

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4758]
### Describe the issue

To reproduce, try to edit any Script task from the topology view -- you should see that for interpreter, the UI sends an empty array making it impossible to save the flow because the interpreter is required.

![image](https://github.com/user-attachments/assets/84a3c3e7-1437-431e-a1fb-109ea398a335)

From the topology side in the UI, it looks like topology is filled even though it's not (it's only a default value displayed in the UI). 

```yaml
id: topo
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀
  - id: log
    type: io.kestra.plugin.core.log.Log
    message: hello world
  - id: shell
    type: io.kestra.plugin.scripts.shell.Commands
    beforeCommands: []
    commands:
      - echo hello world there
    interpreter:
      - /bin/bash
      - "-c"
    outputFiles: []
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
  - id: py
    type: io.kestra.plugin.jdbc.duckdb.Query
    outputFiles: []
    sql: SELECT 42;
    # optional arrays are autofilled with empty array
```

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):
