### ISSUE TITLE
outputFiles should be dynamic to allow passing files from inputs or other tasks

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#4759]
### Describe the issue

Reported by a customer willing to migrate from 0.15.17 to 0.18.X, the following flow is not working anymore (working on 0.15.17)

Whatever the input or the string filled in the `outputfiles` prop. (I tried with some glob pattern, `render()` function, etc.) - the issue is the same

```
id: subflow
namespace: kestra.sandbox

inputs:
  - id: out
    type: STRING

tasks:

  - id: echo
    type: io.kestra.plugin.core.log.Log
    message: "{{ inputs.out }}"

  - id: shell
    type: io.kestra.plugin.scripts.shell.Commands
    outputFiles:
      - "*.{{ inputs.out }}"
    commands:
      - touch test.txt
      - touch test2.txt
```

![image](https://github.com/user-attachments/assets/48347a77-a918-46d8-8fa2-1161451feeb4)

### Environment

- Kestra Version: 0.18.3
- Operating System (OS/Docker/Kubernetes): docker
- Java Version (if you don't run kestra in Docker):
