### ISSUE TITLE
The Running duration of each dbt node is no longer parsed in the Gantt view 

### ISSUE THREAD

**Issue by AlxGlx** [kestra-io/kestra#4767]
### Describe the issue

Gantt lines are not appearing correctly for DBT model builds. Run Duration in the hover over is also incorrect.
![image](https://github.com/user-attachments/assets/39dffd59-c653-44f5-bfd6-9c6645d3122b)

in previous builds the gantt chard displays like this:
![image](https://github.com/user-attachments/assets/ccd340e2-7dbf-43d2-be84-4e133dbae208)

### Environment

- Kestra Version: 0.18.3
- Operating System (OS/Docker/Kubernetes):  Debain 12 Bookworm/ Docker 27.1.2

**Comment by anna-geller** [comment]
do you have a reproducer? running duration of 0s seems suspicious indeed

**Comment by anna-geller** [comment]
ok, I was able to reproduce with the tutorial flow. Looks like the issue in parsing manifest.json. Thanks for reporting this!

```yaml
id: dwh_and_analytics
namespace: tutorial
description: Data Warehouse and Analytics

tasks:
  - id: dbt
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
    - id: clone_repository
      type: io.kestra.plugin.git.Clone
      url: https://github.com/kestra-io/dbt-demo
      branch: main

    - id: dbt_build
      type: io.kestra.plugin.dbt.cli.DbtCLI
      parseRunResults: true
      taskRunner:
        type: io.kestra.plugin.scripts.runner.docker.Docker
      containerImage: ghcr.io/kestra-io/dbt-duckdb:latest
      commands:
        - dbt deps
        - dbt build
      profiles: |
        jaffle_shop:
          outputs:
            dev:
              type: duckdb
              path: dbt.duckdb
              extensions: 
                - parquet
              fixed_retries: 1
              threads: 16
              timeout_seconds: 300
          target: dev      
```
