### ISSUE TITLE
Redpanda for local env

### ISSUE THREAD

**Issue by raphaelauv** [kestra-io/kestra#477]
### Issue description

Redpanda is faster and smaller for local env, it could be interesting to replace kafka and zookeeper in the develop docker-compose

https://github.com/kestra-io/kestra/blob/develop/docker-compose.yml

```yaml
version: '3.8'

services:
  kafka-broker:
    image: docker.vectorized.io/vectorized/redpanda:v21.11.4
    ports:
      - "9092:9092"
      - "9081:8081"
      - "9082:8082"
    expose:
      - 29092
      - 8081 # schema-registry
      - 8082 # restproxy
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - '0'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://kafka-broker:29092,OUTSIDE://localhost:9092


  akhq:
    image: tchiotludo/akhq:0.20.0
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka-broker:29092"
              schema-registry:
                url: "http://kafka-broker:8081"
    ports:
      - "9028:8080"
    depends_on:
      - kafka-broker
```

**Comment by tchiotludo** [comment]
I've been thinking that for months also. I've kafka & zookeeper running permanently on my machine. 

So I do some research and found that : https://redpanda.com/blog/fast-transactions/: support for transaction is partial for now, Kestra heavily use Kafka transactions. So I'm not really sure it will work properly with Redpanda. 

Maybe for local env and most of people, it could be sufficient. 

Do you have test on your side ?

**Comment by raphaelauv** [comment]
They will apparently soon work on it -> https://github.com/redpanda-data/redpanda/milestone/42

**Comment by tchiotludo** [comment]
I've made a quick test : 
```yaml 
version: "3.6"

volumes:
  redpanda-data:
    driver: local
  elasticsearch-data:
    driver: local
  kestra-data:
    driver: local

services:
  kafka:
    image: docker.vectorized.io/vectorized/redpanda
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - '0'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://kafka:9092

    volumes:
      - redpanda-data:/var/lib/redpanda/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    environment:
      discovery.type: single-node
      cluster.routing.allocation.disk.threshold_enabled: "false"
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  kestra:
    image: kestra/kestra:develop-full
    command: server standalone
    volumes:
      - kestra-data:/app/storage
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/kestra:/tmp/kestra
    environment:
      KESTRA_CONFIGURATION: |
        kestra:
          kafka:
            client:
              properties:
                bootstrap.servers: kafka:9092
          elasticsearch:
            client:
              http-hosts: http://elasticsearch:9200
          repository:
            type: elasticsearch
          storage:
            type: local
            local:
              base-path: "/app/storage"
          queue:
            type: kafka
          tasks:
            tmp-dir:
              path: /tmp/kestra/tmp
          url: http://localhost:8080/
    ports:
      - "28080:8080"
    links:
      - kafka
```

I've an error on the topic creation, don't know why :disappointed:
