### ISSUE TITLE
Enable logToFile also for subflows

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4773]
### Feature description

As a follow-up to https://github.com/kestra-io/kestra/pull/4757

We should also enable logging to file for subflows.

Currently this will not work yet:

```yaml
id: parent
namespace: company.team
tasks:
  - id: hello
    type: io.kestra.plugin.core.flow.Subflow
    namespace: company.team
    flowId: child_flow
    logToFile: true
```

with:

```yaml
id: child_flow
namespace: company.team
tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: 
      - Hello World! 
      - Kestra team wishes you a great day 
      - If you need some help, reach out via Slack      
  - id: log_more
    type: io.kestra.plugin.core.log.Log
    message: 
      - Hello World! 
      - Kestra team wishes you a great day 👋
      - If you need some help, reach out via Slack            
```

![image](https://github.com/user-attachments/assets/2a33988f-fc91-4c0f-b4ee-ce4a243b3a2a)
