### ISSUE TITLE
/bin/sh: 2: python: not found

### ISSUE THREAD

**Issue by owaismultani** [kestra-io/kestra#480]
### Actual Behaviour

![image](https://user-images.githubusercontent.com/47238206/154907933-53ab3dd7-88ec-4d90-848a-86faefcbaea5.png)

Possible issue: python used is python3 and no alias is set for python, hence the error.

### Steps To Reproduce

Getting Error Running given example. It says Python is not found.
1. Run docker container
2. Go to http://localhost:8080/
2. Go to Flows
3. Create a new flow with the following:

`id: pythonTest
namespace: io.kestra.cliff
revision: 2
tasks:
  - id: Test001
    type: io.kestra.core.tasks.scripts.Python
    args:
      - data.json
    inputFiles:
      data.json: |
        {"status": "OK"}
      main.py: |
        from kestra import Kestra
        import json
        import requests
        import sys
        result = json.loads(open(sys.argv[1]).read())
        print(f"python script {result['status']}")
        response = requests.get('http://google.com')
        print(response.status_code)
        Kestra.outputs({'status': response.status_code, 'text': response.text})
      pip.conf: |
        # some specific pip repository configuration
    requirements:
      - |-
        requests
        Copied!
`
reference: (https://kestra.io/plugins/core/tasks/scripts/io.kestra.core.tasks.scripts.Python.html)

### Environment Information

- Kestra Version: develop-full
- Operating System (OS / Docker / Kubernetes): Docker
- Java Version (If not docker):

### Example flow

id: pythonTest
namespace: io.kestra.test
revision: 1
tasks:
  - id: Test001
    type: io.kestra.core.tasks.scripts.Python
    args:
      - data.json
    inputFiles:
      data.json: |
        {"status": "OK"}
      main.py: |
        from kestra import Kestra
        import json
        import requests
        import sys
        result = json.loads(open(sys.argv[1]).read())
        print(f"python script {result['status']}")
        response = requests.get('http://google.com')
        print(response.status_code)
        Kestra.outputs({'status': response.status_code, 'text': response.text})
      pip.conf: |
        # some specific pip repository configuration
    requirements:
      - |-
        requests
        Copied!

**Comment by tchiotludo** [comment]
Hi,
it's in intended behaviour that we should document properly. 
The base docker image of Kestra don't include python since we don't want to have a large image for everyone. 
There is 2 solutions for you: 
- Build a custom image with python and use it on docker-compose: 
```Dockerfile
FROM docker pull kestra/kestra:develop-full

RUN apt-get update -y && \
  apt-get install -y --no-install-recommends python3-pip python3-wheel gcc python3-dev python3-setuptools python3-venv python3-virtualenv \
  apt-get clean && rm -rf /var/lib/apt/lists/* /var/tmp/* 

```
- Use the `dockerOptions` and `runner: DOCKER` to use a python image that work out of the box with `docker-compose.yml` provided: 
```yaml 
id: pythonTest
namespace: io.kestra.test
revision: 3
tasks:
  - id: Test001
    type: io.kestra.core.tasks.scripts.Python
    args:
      - data.json
    dockerOptions:
      image: python
    inputFiles:
      data.json: |
        {"status": "OK"}
      main.py: |
        from kestra import Kestra
        import json
        import requests
        import sys
        result = json.loads(open(sys.argv[1]).read())
        print(f"python script {result['status']}")
        response = requests.get('http://google.com')
        print(response.status_code)
        Kestra.outputs({'status': response.status_code, 'text': response.text})
      pip.conf: |
        # some specific pip repository configuration
    requirements:
      - requests
    runner: DOCKER
```

Keeping it for the documentation that is missing
