### ISSUE TITLE
support for deleting namespace folders

### ISSUE THREAD

**Issue by MarthaScheffler** [kestra-io/kestra#4807]
### Feature description

enhance the DeleteFiles plugin (https://kestra.io/plugins/core/tasks/namespace/io.kestra.plugin.core.namespace.deletefiles) to also remove folders.

example flow:
```
id: delete_namespace_files
namespace: kestra.sandbox

tasks:
  - id: working_directory # run following tasks in the same working directory
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      - id: write_into_directory
        type: io.kestra.core.tasks.scripts.Bash
        commands:
          - mkdir test
          - echo 'test test' >> test.txt
          - cp test.txt test

      - id: upload_directory_files_into_namespace
        type: io.kestra.plugin.core.namespace.UploadFiles
        files:
          - "glob:**"
        namespace: "{{ flow.namespace }}"

  - id: wait
    type: io.kestra.plugin.core.flow.Pause # check if the files are in the namespace

  - id: delete_namespace_files
    type: io.kestra.plugin.core.namespace.DeleteFiles
    namespace: "{{ flow.namespace }}"
    files:
      - "**"
```

**Comment by Ben8t** [comment]
Thanks Martha for opening issue !

Adding complement of the current behavior: the flow shared by Martha above will actually delete all files, but the underlying folder structure created stay in place (they are empty)
**Goal: also remove folders when no specific files are targeted.**

For example

```yaml
  - id: delete_namespace_files
    type: io.kestra.plugin.core.namespace.DeleteFiles
    namespace: "{{ flow.namespace }}"
    files:
      - "my_folder/**"
```
Should remove all files from `my_folder` and the folder itself.

Maybe we want to add a flag `deleteFolder: true | false` to keep things explicit and not mix with glob semantic
