### ISSUE TITLE
Parent flow with `retry` does not retry when Subflow fails and `transmitFailed` set to true 

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#4823]
### Describe the issue

This parent flow will call a Subflow which will fail. `transmitFailed` is set to true meaning that the parent flow fails too. However, the parent flow does not retry despite being defined.

Parent flow:
```yaml
id: retry_flow
namespace: kestra.sandbox

retry:
  maxAttempt: 2
  behavior: CREATE_NEW_EXECUTION
  type: constant
  interval: PT2S

tasks:
  - id: call_subflow
    type: io.kestra.plugin.core.flow.Subflow
    namespace: "{{ flow.namespace }}"
    flowId: fail_flow
    wait: true
    transmitFailed: true
```
Subflow:
```yaml
id: fail_flow
namespace: kestra.sandbox

tasks:
  - id: fail
    type: io.kestra.plugin.scripts.shell.Commands
    commands:
      - exit 1
```
What happened:
![Screenshot 2024-09-04 at 13 36 39](https://github.com/user-attachments/assets/32c50f77-7e68-463f-9905-0912f9d5cd5c)

What should happen (parent flow is forced to fail separately to subflow to generate expected result):
![Screenshot 2024-09-04 at 13 37 11](https://github.com/user-attachments/assets/46678c35-cda2-470e-8035-58858e8cf3a4)

### Environment

- Kestra Version: 0.19 Snapshot as well as 0.18.4
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):
