### ISSUE TITLE
Make namespaceFiles include/exclude properties dynamic

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4861]
### Feature description

Sample usage user would like to see:

```yaml
namespaceFiles:
  enabled: true
    include:
      - "{{ inputs.script_path }}"
```
