### ISSUE TITLE
`include` and `exclude` properties for `namespaceFiles` only work when `enabled` is set to true despite being default true

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#4867]
### Describe the issue

In the documentation for `namespaceFiles`, it says that for `enabled`:
> Note that this property is by default set to true so that you can specify only the include and exclude properties to filter the files to load without having to explicitly set enabled to true.

However this doesn't work. It fails unless you set `enabled` to true. The property is working once `enabled` is set to true as a simple `ls` shows that only the expected files are visible (there are other files in this namespace). The problem is that the default value is incorrect here.

![Screenshot 2024-09-09 at 12 29 44](https://github.com/user-attachments/assets/b2e82c4f-ff9f-4fc0-972a-99684550d13f)

This works:
```yaml
id: python_code
namespace: company.team

tasks:
  - id: py
    type: io.kestra.plugin.scripts.python.Commands
    namespaceFiles:
      enabled: true
      include:
        - main.py
    commands:
      - ls
      - python main.py
```
![Screenshot 2024-09-09 at 12 33 20](https://github.com/user-attachments/assets/f085bfeb-c0c6-4ee5-a7a5-d5c480bba008)

This does not work:
```yaml
id: python_code
namespace: company.team

tasks:
  - id: py
    type: io.kestra.plugin.scripts.python.Commands
    namespaceFiles:
      include:
        - main.py
    commands:
      - ls
      - python main.py
```
![Screenshot 2024-09-09 at 12 33 37](https://github.com/user-attachments/assets/8086bd56-ab32-4563-b25f-9680095b6573)

### Environment

- Kestra Version: 0.19 Snapshot `abf0662`
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):
