### ISSUE TITLE
Load Purge flow from Strapi to display System namespace in OSS at server start time

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4878]
### Feature description

```yaml
id: purge
namespace: system

tasks:
  - id: purge_executions
    type: io.kestra.plugin.core.execution.PurgeExecutions
    endDate: "{{ now() | dateAdd(-1, 'MONTHS') }}"
    purgeLog: false
    states:
      - SUCCESS

  - id: purge_logs
    type: io.kestra.plugin.core.log.PurgeLogs
    endDate: "{{ now() | dateAdd(-1, 'MONTHS') }}"

triggers:
  - id: daily
    type: io.kestra.plugin.core.trigger.Schedule
    disabled: true
    cron: "0 9 * * *" 
```

Blueprint: http://localhost:8080/ui/blueprints/234

https://kestra.io/blueprints/trigger/234-system-flow-purge-execution-data-including-logs-metrics-and-outputs-on-a-schedule 

Todo:
- [x] load at server start time
- [x] adjust the namespace (e.g. with RegEx) in case user has overwritten `system` to some other name in their configuration
