### ISSUE TITLE
Topology view for triggers is buggy with light theme

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#4882]
### Describe the issue

![image](https://github.com/user-attachments/assets/9aa68912-8031-4d15-9536-1b069ac5b291)

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by MilosPaunovic** [comment]
Hey @Ben8t, could you provide a flow which creates the graph in question, as of right now, I am not sure about which line you're talking, as there is no line on the dark theme neither, on the place I'm thinking of, to the top right corner icon.

![image](https://github.com/user-attachments/assets/82f937ee-5453-4405-8696-4e6f0e659e11)

**Comment by Ben8t** [comment]
Yes here is the flow

```
id: hello_world
namespace: kestra.sandbox
description: This flow logs a message to the console.

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello world!

triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "* 9 * * *"
```

![image](https://github.com/user-attachments/assets/79ea80ba-0032-4cc2-9422-317d70260554)
![image](https://github.com/user-attachments/assets/05e31c22-2349-47ba-80e3-e49800851fd8)
