### ISSUE TITLE
Topology execution for subflow boxes is buggy

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#4902]
### Describe the issue

The Topology view when a flow is running show some bugs regarding subflows:

1. When the flow is running, go to the Topology view and try to expand the subflow. The box doesn't expand well

![image](https://github.com/user-attachments/assets/0929e31a-3a8c-4ae6-bfdf-2853f3e07259)

2. When the flow has finished to run, it's not possible to expand the subflow

https://github.com/user-attachments/assets/a3bd5577-03f3-4269-a8f1-e7f793af7f86

3. The whole flow is still running, the subflow is completed, but Tasks inside the subflow are still not shown as completed (task execution information are not forwarded)

![image](https://github.com/user-attachments/assets/509f09a4-3f07-4633-947b-699914170486)

### Flow Reproducer 

```yaml
id: parent
namespace: kestra.qa
tasks:
  - id: sub
    type: io.kestra.plugin.core.flow.Subflow
    flowId: child
    namespace: kestra.qa
```

```yaml
id: child
namespace: kestra.qa
tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀

  - id: hello2
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀
```

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):
