### ISSUE TITLE
Allow adjusting the flow template based on configuration

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4956]
### Feature description

Ideally, via configuration on OSS + on a tenant or namespace-level in EE:

```yaml
id: myflow
namespace: company.team
tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀
```

**Comment by MilosPaunovic** [comment]
Related to https://github.com/kestra-io/kestra-ee/issues/606.

**Comment by Ben8t** [comment]
First thing to do: configuration backend (instance level)
then we can evaluate local storage (client side) for "user profiles"

**Comment by anna-geller** [comment]
@MilosPaunovic assuming we would add some configuration variable, e.g.:

```yaml
kestra:
  flowTemplate: |    
    tasks:
      - id: hello
        type: io.kestra.plugin.core.log.Log
        message: Hello World! 
```

Wouldn't this be a quick win then? We'd treat the id and namespace in the template as optional so that those can still be dynamically generated unless user explicitly sets some default namespace or flow ID - WDYT?
