### ISSUE TITLE
Unauthorized error access output created by subflow in root namespace

### ISSUE THREAD

**Issue by paulgrainger85** [kestra-io/kestra#4958]
### Describe the issue

Create the following flow and subflow 

```
id: subflow_exec
namespace: org.suborg
tasks:
  - id: sf1
    type: io.kestra.plugin.core.flow.Subflow
    flowId: create_file
    namespace: org
```

```
id: create_file
namespace: org
tasks:
  - id: output
    type: io.kestra.plugin.scripts.shell.Commands
    outputFiles:
      - out.txt
    commands:
      - echo org_namespace > out.txt

outputs:
  - id: final
    type: FILE
    value: "{{ outputs.output.outputFiles['out.txt'] }}"
```

Execute parent flow (level of permissions does not matter - error can be seen as admin)

Once flow completes, try to select the output from the UI, you will get an Unauthorized error
![image](https://github.com/user-attachments/assets/e5e6b185-ed0c-4e6d-91a0-40f80dc1afba)

Selecting "Preview" will show the contents of the file. 

Select "Download" will produce an error
```
{"message":"Unauthorized","logref":null,"path":null,"_links":{"self":{"href":"/api/v1/executions/7DKeUEVqoi8iSakMBROSCL/file?path=kestra:///org/create-file/executions/7DKeUEVqoi8iSakMBROSCL/tasks/output/7YSNuFD3biJKggOezeg3Bm/6annewgAUSmMKUNkFDBtcd-out.txt","templated":false,"profile":null,"deprecation":null,"title":null,"hreflang":null,"type":null,"name":null}},"_embedded":{}}
```

### Environment

- Kestra Version: 0.18.7
- Operating System: Docker
