### ISSUE TITLE
Change password of posgres in Docker

### ISSUE THREAD

**Issue by evertonaleixo** [kestra-io/kestra#4961]
### Describe the issue

Hello, I am trying to change the password of Postgres in Docker, but the Kestra container is not reading the password correctly.
So, the container of postgres uses the new password and the Kestra one uses the default password, and cannot start.

```
volumes:
  postgres-data:
    driver: local
  kestra-data:
    driver: local

services:
  postgres:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: kestra
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: new_pwd
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 10

  kestra:
    image: kestra/kestra:latest
    pull_policy: always
    user: "root"
    command: server standalone
    volumes:
      - ./bots:/app/bots
      - kestra-data:/app/storage
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/kestra-wd:/tmp/kestra-wd
    environment:
      KESTRA_CONFIGURATION: |
        datasources:
          postgres:
            url: jdbc:postgresql://postgres:5432/kestra
            driverClassName: org.postgresql.Driver
            username: kestra
            password: new_pwd
        kestra:
          server:
            basic-auth:
              enabled: true
              username: "email@email.com" # it must be a valid email address
              password: 123456
          repository:
            type: postgres
          storage:
            type: local
            local:
              base-path: "/app/storage"
          queue:
            type: postgres
          tasks:
            tmp-dir:
              path: /tmp/kestra-wd/tmp
          url: http://localhost:8080/
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_started

```

### Environment

- Kestra Version: latest
- Operating System (OS/Docker/Kubernetes): Docker
- Java Version (if you don't run kestra in Docker): Running in Docker
