### ISSUE TITLE
[Idea] Add design proposal to enable storing all inputs and outputs in internal storage 

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4962]
### Feature description

We increasingly hear user requests to allow storing all inputs and outputs in internal storage. With the successful implementation of the Key Value store this idea seems feasible and worth exploring in terms of added complexity and latency

**Comment by Ben8t** [comment]
Idea: could be an option in configuration too (either memory or internal storage)

**Comment by anna-geller** [comment]
## Extra notes
internally, we don't have any update of the execution when running e.g. `PurgeExecutionFiles`, we are only removing the file from internal storage, nothing more. Users can also use lifecycle policies at the bucket level to implement the purge operation, meaning that we will only be aware at runtime if the file exists or not. This means that the following flow where `"{{outputs.download.uri}}"` still points to the (no longer existing) file is expected. 

```yaml
id: purge_current_execution_files
namespace: qa

tasks:
  - id: download
    type: io.kestra.plugin.core.http.Download
    uri: https://huggingface.co/datasets/kestra/datasets/raw/main/csv/orders.csv

  - id: purge
    type: io.kestra.plugin.core.storage.PurgeCurrentExecutionFiles

  - id: assert
    type: io.kestra.plugin.core.flow.If
    condition: "{{outputs.download.uri}}"
    then:
      - id: fail
        type: io.kestra.plugin.core.execution.Fail
        errorMessage: File still exists 
    else:
      - id: pass
        type: io.kestra.plugin.core.log.Log
        message: File successfully purged
```

Most things in kestra is designed on the immutable pattern, so best practice here would be: 
`condition: "{{ fileExists(outputs.download.uri) }}"`
