### ISSUE TITLE
Downgrading Ion file that contains type annotation fail

### ISSUE THREAD

**Issue by ReLoutre** [kestra-io/kestra#4991]
### Describe the issue

Using IonToJson task on a file that contains a type annotated value produce infinite nested call of IonSystemLite['loader"] and IonStringLite["system"].

## Bug reproduction
Here's a flow to reproduce the error :
```yml
id: bug_reproduction
namespace: bloup

inputs:
  - id: test_ref_file
    type: FILE

tasks:
  - id: downgrade_Ion_to_Json
    type: io.kestra.plugin.serdes.json.IonToJson
    from: "{{inputs.test_ref_file}}"
```
Here's the content of the file to input in the flow :
```ion
{someKey:"someValue",attributes:{description:["Some not encoded text"]}}
{someKey:"someValue",attributes:{description:[base64::"TGlzmlhbGUgZGUgbCdJVVQ="]}}
{someKey:"someValue",attributes:{description:["Some not encoded text", "and some more"]}}
```

Removing the type annotation `base64::` works fine.

## Expecting behaviour :

While downgrading to JSON type annotation may be totally erased or concerned field may be translated as :
```json
{someKey:"someValue",attributes:{description:[base64::"TGlzmlhbGUgZGUgbCdJVVQ="]}}
->
{"someKey":"someValue","attributes":{"description":[{"annot":"base64","value":"TGlzmlhbGUgZGUgbCdJVVQ="}]}}
```
For example...

### Environment

- Kestra Version: 0.18.4
- Operating System (OS/Docker/Kubernetes): Docker
