### ISSUE TITLE
MULTISELECT input values requires an array and doesn't accept values from the kv() function

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5035]
### Describe the issue

![image](https://github.com/user-attachments/assets/fc914a44-8b7c-43fa-87d6-93798c389111)

error:

At flow: Cannot construct instance of `java.util.ArrayList` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('{{ kv('values') }}') at [Source: (StringReader); line: 7, column: 13] (through reference chain: io.kestra.core.models.flows.Flow["inputs"]->java.util.ArrayList[0]->io.kestra.core.models.flows.input.MultiselectInput["values"])

reproducer:

```yaml
id: multi
namespace: company.team

inputs:
  - id: values
    type: MULTISELECT
    values: "{{ kv('values') }}"

tasks:
  - id: foreach
    type: io.kestra.plugin.core.flow.ForEach
    values: "{{ inputs.values }}"
    tasks:
      - id: print
        type: io.kestra.plugin.core.log.Log
        message: Hello {{ taskrun.value }}
```

trying the same using expression:

```yaml
id: multi
namespace: company.team

inputs:
  - id: values
    type: MULTISELECT
    expression: "{{ kv('values') }}"

tasks:
  - id: foreach
    type: io.kestra.plugin.core.flow.ForEach
    values: "{{ inputs.values }}"
    tasks:
      - id: print
        type: io.kestra.plugin.core.log.Log
        message: Hello {{ taskrun.value }}
```

gives another error:

At values: Invalid input for `values`, missing required input, but received `null`

and then also throws:

```Java
Internal Server Error: Error encoding object [ApiValidateExecutionInputsResponse[id=multi, namespace=company.team, inputs=[ApiInputAndValue[input=io.kestra.core.models.flows.input.MultiselectInput@6a9fa625, value=null, enabled=true, errors=[ApiInputError[message=Invalid input for `values`, missing required input, but received `null`]]]]]] to JSON: class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap') (through reference chain: io.kestra.webserver.controllers.api.ExecutionController$ApiValidateExecutionInputsResponse["inputs"]->java.util.ImmutableCollections$ListN[0]->io.kestra.webserver.controllers.api.ExecutionController$ApiValidateExecutionInputsResponse$ApiInputAndValue["input"]->io.kestra.core.models.flows.input.MultiselectInput["values"]->java.util.ArrayList[0])
```

@fhussonnois let's prioritize this over Worker Group UI at first to have this feature fully finished 👍

**Comment by anna-geller** [comment]
EDIT: the issue seems to be in the values of the KV pair itself

the above flow with expression works when the KV value is: `["hello","world","my","key"]` but fails if it's an array of integers: `[1, 2, 3, 4, 5]`. Maybe we need to add ARRAY type KV type instead of relying on the JSON type?

**Comment by fhussonnois** [comment]
The first flow is not valid. The field `values` can only be used to pass static values. Values from K/V must be passed through the `expression` field.

```
id: multi
namespace: company.team

inputs:
  - id: values
    type: MULTISELECT
    # This is NOT valid
    # values: "{{ kv('values') }}"
    expression: "{{ kv('values') }}"
```

Otherwise, I fixed the issue with the array of integers.
