### ISSUE TITLE
KV pairs from parent namespace are not inherited to child namespaces

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5037]
### Describe the issue

reproducer - add parent key in `company` namespace and run:

```yaml
id: child
namespace: company.team
tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello {{ kv('parent') }}
```

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):
