### ISSUE TITLE
kvType doesn't work as expected for JSON

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5041]
### Describe the issue

```yaml
id: add_kv_pairs
namespace: company.myteam

tasks:
  - id: kv_set
    type: io.kestra.plugin.core.kv.Set
    key: access_permissions
    kvType: JSON
    value: |
      {{ ["Admin", "Developer", "Editor", "Launcher", "Viewer"] | toJson }}
```
also tried: 
```yaml
    value: |
      ["Admin", "Developer", "Editor", "Launcher", "Viewer"]
```

Regardless, the KV pair is stored as STRING, not JSON. I need this KV pair to be an array - @brian-mulier-p please help

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):
