### ISSUE TITLE
Input description text is not legible -- can we make the text white?

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5042]
### Describe the issue

Make the input description text white

![image](https://github.com/user-attachments/assets/69c2ca40-9c2a-4f97-91c6-ee0cf9fa8e00)

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by MilosPaunovic** [comment]
May I have a sample flow for reproduction? @anna-geller

**Comment by anna-geller** [comment]
any input description:
![image](https://github.com/user-attachments/assets/1ae32be7-2920-4a86-893f-413d766f7a5d)

```yaml
id: business_processes
namespace: tutorial
description: Business Processes

inputs:
  - id: request.name
    type: STRING
    defaults: Rick Astley
    description: Name of the person requesting vacation

  - id: request.start_date
    type: DATE
    defaults: 2024-07-01
    description: Start date of the vacation request

  - id: request.end_date
    type: DATE
    defaults: 2024-07-07
    description: End date of the vacation request

  - id: slack_webhook_uri
    type: URI
    defaults: https://reqres.in/api/slack
    description: URI for the Slack webhook used to send notifications

tasks:
  - id: send_approval_request
    type: io.kestra.plugin.notifications.slack.SlackIncomingWebhook
    url: "{{ inputs.slack_webhook_uri }}"
    payload: |
      {
        "channel": "#vacation",
        "text": "Validate holiday request for {{ inputs.request.name }}. To approve the request, click on the `Resume` button here http://localhost:8080/ui/executions/{{flow.namespace}}/{{flow.id}}/{{execution.id}}"
      }

  - id: wait_for_approval
    type: io.kestra.plugin.core.flow.Pause

  - id: process_request
    type: io.kestra.plugin.core.http.Request
    uri: https://reqres.in/api/products
    method: POST
    contentType: application/json
    body: "{{ inputs.request }}"
```
