### ISSUE TITLE
HTML links from the HTTP plugin don't render in the logs leading to confusing log messages

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5049]
### Describe the issue

![image](https://github.com/user-attachments/assets/2d44798c-86c6-4f42-a960-d2e62da59579)

reproducer: default DE tutorial flow with http task

```yaml
id: data_engineering_pipeline
namespace: tutorial

tasks:
  - id: extract
    type: io.kestra.plugin.core.http.Download
    uri: https://dummyjson.com/products
```

### Environment

- Kestra Version: develop
