### ISSUE TITLE
The defaults for the DURATION input is ignored by the UI

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5078]
### Describe the issue

Follow-up to https://github.com/kestra-io/kestra/issues/3710

The `defaults` is now ignored and you currently cannot trigger an execution without setting a duration even though the default is set via code:

![image](https://github.com/user-attachments/assets/47e07185-5d95-4fa4-b1a1-7ee355ba13a9)

reproducer:

```yaml
id: duration_repro
namespace: company.team

inputs:
  - id: duration
    type: DURATION
    defaults: PT1H

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: my {{ inputs.duration }}
```

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):
