### ISSUE TITLE
Log task ignores log level

### ISSUE THREAD

**Issue by sdroid74** [kestra-io/kestra#5090]
### Describe the issue

Using the `io.kestra.plugin.core.log.Log` task ignores the levels `WARN` and `ERROR`.
`DEBUG `and `TRACE `are printed, but both shown as `INFO `in the UI.

Tested with following flow:

```yaml
id: myflow
namespace: company.team
tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀
  - id: debug
    type: io.kestra.plugin.core.log.Log
    message: Hello Debug! 🚀
    logLevel: DEBUG
  - id: warn
    type: io.kestra.plugin.core.log.Log
    message: Hello WARN! 🚀
    logLevel: WARN
  - id: error
    type: io.kestra.plugin.core.log.Log
    message: Hello ERROR! 🚀
    logLevel: ERROR
  - id: trace
    type: io.kestra.plugin.core.log.Log
    message: Hello TRACE
    logLevel: TRACE
```

![kestra-logs](https://github.com/user-attachments/assets/30cfb664-41ac-4d3d-86ea-9dcc809ffe0f)

### Environment

- Kestra Version: v0.18.9
- Operating System (OS/Docker/Kubernetes): Tested on Windows (standalone) and Linux (podman)
- Java Version (if you don't run kestra in Docker): Temurin-21.0.4+7
