### ISSUE TITLE
ForEachItem - Stream input items to the subflow instead of splitting the input file into multiple files

### ISSUE THREAD

**Issue by johnkm516** [kestra-io/kestra#5161]
### Feature description

One of the biggest problems with the current ForEachItem for me is that by default, ForEachItem will split an input file into multiple files, one for each batch. 
Consider the following flow parameters : 

- Batch job that must handle ~100,000 rows, stored in an ION file from a database query. **Subflow must take in one row per execution.**
- ForEachItem with the 100,000 rows. ```{{ouptuts.query.uri}}``` would be values input into the ForEachItem
- Result : ForEachItem splits the 100,000 into 100,000 files in the internal storage, which takes ages to do because it's splitting one file into 100,000 files, and the disk IO becomes a major bottleneck

Instead of splitting the 100,000 row ION file into 100,000 separate files, I would like an option for the ForEachItem to simply stream the original ION file in memory in batches (the amount stored in memory will be dependent on the ```batch``` property's rows attribute), creating executions as it processes the file in a "sliding window" fashion. 

I believe this will make the ForEachItem task far more efficient way it passes inputs to subflows.

**Comment by anna-geller** [comment]
hey John, did you know that you can [decide about the batch size](https://kestra.io/docs/concepts/flowable-tasks#foreachitem)? it doesn't have to be 1 file per row e.g.: here 10k rows per batch:

```yaml
  - id: each
    type: io.kestra.plugin.core.flow.ForEachItem
    items: "{{ inputs.file }}" # could be also an output variable {{ outputs.extract.uri }}
    inputs:
      file: "{{ taskrun.items }}" # items of the batch
    batch:
      rows: 10000
    namespace: company.team
    flowId: subflow
    revision: 1 # optional (default: latest)
    wait: true # wait for the subflow execution
    transmitFailed: true # fail the task run if the subflow execution fails
    labels: # optional labels to pass to the subflow to be executed
      key: value
```

To be transparent, we can't do that splitting in memory 😢  in fact, this is why this task exists - to split data processing into chunks and avoid processing everything at once.
