### ISSUE TITLE
`Prefill` Execution button sometimes fails

### ISSUE THREAD

**Issue by japerry911** [kestra-io/kestra#5194]
### Describe the issue

1. Press Execute on a completed execution run
2. Press `Prefill`
3. Press `Execute`

```
Illegal state
Illegal state: Duplicate key type (attempted merging values dbt and dbt)
```

--

Request URL:
```
https://xxx/api/v1/xxx-dev/executions/xxx.subflows.dbt/executeDbtBuild?labels=type:dbt&labels=type:dbt

409 Conflict

{
    "message": "Illegal state: Duplicate key type (attempted merging values dbt and dbt)",
    "logref": null,
    "path": null,
    "_links": {
        "self": {
            "href": "/api/v1/xxx-dev/executions/xxx.subflows.dbt/executeDbtBuild?labels=type:dbt&labels=type:dbt",
            "templated": false,
            "profile": null,
            "deprecation": null,
            "title": null,
            "hreflang": null,
            "type": null,
            "name": null
        }
    },
    "_embedded": {}
}
```

https://www.loom.com/share/dd4b5eb7703745fcaca1e2778af8c095?sid=2af1097f-934c-4114-b5ea-1d2af248124e

### Environment

- Kestra Version: v0.18.9
- Operating System (OS/Docker/Kubernetes): Kestra Cloud
- Java Version (if you don't run kestra in Docker): n/a

**Comment by anna-geller** [comment]
Hi Jack, thanks for the issue. Can you perhaps share a flow so that we can reproduce? (you can DM me via Slack)

I suspect this happens only with nested inputs based on my short test: https://share.descript.com/view/H5LyegP8Pyh -- can you confirm this issue happens only for nested inputs? would be great to narrow it down to identify which input types are not prefilled as expected

I was using this flow:

```yaml
id: inputs
namespace: company.team

inputs:
  - id: string
    type: STRING
    defaults: "Hello World!"

  - id: optional
    type: STRING
    required: false

  - id: int
    type: INT
    defaults: 100

  - id: list_of_int
    type: ARRAY
    itemType: INT
    defaults: [1, 2, 3]

  - id: bool
    type: BOOLEAN
    defaults: true

  - id: float
    type: FLOAT
    defaults: 100.12

  - id: value_enum
    type: SELECT
    defaults: VALUE_1
    values:
      - VALUE_1
      - VALUE_2
      - VALUE_3

  - id: instant
    type: DATETIME
    defaults: "2013-08-09T14:19:00Z"

  - id: date
    type: DATE
    defaults: "2013-10-25"

  - id: json
    type: JSON
    defaults: |
      [{"name": "kestra", "rating": "best in class"}]

  - id: uri
    type: URI
    defaults: "https://huggingface.co/datasets/kestra/datasets/raw/main/csv/orders.csv"

  - id: nested.string
    type: STRING
    defaults: "Hello World!"

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello {{ inputs }}
```
