### ISSUE TITLE
Always load system blueprint for purging logs even if tutorial flows are disabled

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5219]
### Describe the issue

loading the purge flow should be independent of this configuration:

```yaml
kestra:
  tutorial-flows:
    enabled: false # true by default
```

even if this is set to false, this blueprint should be loaded: https://kestra.io/blueprints/trigger/234-purge-execution-data-including-logs-metrics-and-outputs-on-a-schedule
