### ISSUE TITLE
Flow description is not rendered correctly as markdown

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5233]
### Describe the issue

![image](https://github.com/user-attachments/assets/52dd6d28-bec4-4bec-9606-e95fc0ddc7c7)

https://preview-oss.kestra.io/ui/flows/edit/dev/api_python_sql2?startDate=2024-08-31T13:01:21.269%2B02:00&endDate=2024-09-30T13:01:21.269%2B02:00&scope=USER&flowId=api_python_sql2

repro - any flow with markdown description:

```yaml
id: api_python_sql2
namespace: dev
description: |
  This flow extracts data from multiple APIs in parallel, including products, users, and quotes. 
  
  1. The product data is transformed using a Python script into a CSV file, which is then further processed using an SQL query to calculate the average price per brand. 
  2. Finally, the user data is sent via a `POST` request to a specified API endpoint, and the flow is triggered daily at 9 AM.

labels:
  env: prod
  country: US

tasks:
  - id: extract_in_parallel
    type: io.kestra.core.tasks.flows.Parallel
    tasks:
      - id: products
        type: io.kestra.plugin.fs.http.Request
        uri: https://dummyjson.com/products
        method: GET
      - id: users
        type: io.kestra.plugin.fs.http.Request
        uri: https://dummyjson.com/products
      - id: quotes
        type: io.kestra.plugin.fs.http.Request
        uri: https://dummyjson.com/quotes

  - id: python_transform
    type: io.kestra.plugin.scripts.python.Script
    runner: PROCESS
    beforeCommands:
      - pip install polars
    warningOnStdErr: false
    script: |
      import polars as pl
      data = {{outputs.products.body | jq('.products') | first}}
      df = pl.from_dicts(data)
      df.glimpse()
      df.select(["brand", "price"]).write_csv("{{outputDir}}/products.csv")

  - id: sql_transform
    type: io.kestra.plugin.jdbc.duckdb.Query
    inputFiles:
      in.csv: "{{ outputs.python_transform.outputFiles['products.csv'] }}"
    sql: |
      SELECT brand, round(avg(price), 2) as avg_price
      FROM read_csv_auto('{{workingDir}}/in.csv', header=True)
      GROUP BY brand
      ORDER BY avg_price DESC;
    store: true

  - id: load
    type: io.kestra.plugin.fs.http.Request
    uri: https://reqres.in/api/products
    method: POST
    contentType: application/json
    body: "{{outputs.users.body}}"

triggers:
  - id: daily
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "0 9 * * *"
```

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):
