### ISSUE TITLE
Mask the value of SECRET-type input if accidentally exposed in the logs

### ISSUE THREAD

**Issue by janorga** [kestra-io/kestra#5259]
### Describe the issue

When a SECRET is asked by inputs it is leaked at logs when it is used as `{{inputs.password}}` (see the example below). 

In the example below, in Kestra task logs `export SUPER_PASSWORD=<the_plain_password_here>` the input (secret) is shown in plain. This should be masked.

```yaml
id: test_input_secret
namespace: test

inputs:
  - id: username
    type: STRING

  - id: password
    type: SECRET

tasks:
  - id: commands_task
    type: io.kestra.plugin.scripts.shell.Commands
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
      pullPolicy: ALWAYS
      entryPoint: []
    containerImage: "ubuntu:latest"
    namespaceFiles:
      enabled: true
    commands:
      - export SUPER_PASSWORD={{ inputs.password }}
```

### Environment

- Kestra Version: v0.18.9
- Operating System (OS/Docker/Kubernetes): Kubernetes RKE2

**Comment by anna-geller** [comment]
to clarify - @loicmathieu can we mask such input in the Shell command or is it outside of our control given it's a container?

![image](https://github.com/user-attachments/assets/86a7c1b4-e73f-4442-8fad-e67d36eb1e49)

FWIW @janorga you should never log or expose your secret as shown in the example with the `export` command, instead you should add `env` property as shown here - this way, nothing is logged:

```yaml
id: test_input_secret
namespace: test

inputs:
  - id: username
    type: STRING

  - id: password
    type: SECRET

tasks:
  - id: commands_task
    type: io.kestra.plugin.scripts.shell.Commands
    env:
      SUPER_PASSWORD: "{{ inputs.password }}"
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
      pullPolicy: ALWAYS
      entryPoint: []
    containerImage: "ubuntu:latest"
    namespaceFiles:
      enabled: true
    commands:
      - echo hello world
```
