### ISSUE TITLE
Dynamically generated tasks make it impossible to replay the next task

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5284]
### Feature description

![image](https://github.com/user-attachments/assets/1f2c4a9c-2357-448f-90ef-b376b3d3734b)

Reproducer:

```yaml
id: dwh_and_analytics
namespace: tutorial
description: Data Warehouse and Analytics

inputs:
  - id: fail
    type: BOOLEAN
    defaults: true

tasks:
  - id: dbt
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
    - id: clone_repository
      type: io.kestra.plugin.git.Clone
      url: https://github.com/kestra-io/dbt-demo
      branch: main

    - id: dbt_build
      type: io.kestra.plugin.dbt.cli.DbtCLI
      taskRunner:
        type: io.kestra.plugin.scripts.runner.docker.Docker
      containerImage: ghcr.io/kestra-io/dbt-duckdb:latest
      commands:
        - dbt deps
        - dbt build
      profiles: |
        jaffle_shop:
          outputs:
            dev:
              type: duckdb
              path: dbt.duckdb
              extensions: 
                - parquet
              fixed_retries: 1
              threads: 16
              timeout_seconds: 300
          target: dev      

  - id: if
    type: io.kestra.plugin.core.flow.If
    condition: "{{ inputs.fail }}"
    then:
      - id: fail
        type: io.kestra.plugin.core.execution.Fail
    else:
      - id: python
        type: io.kestra.plugin.scripts.python.Script
        outputFiles:
          - "*.csv"
        taskRunner:
          type: io.kestra.plugin.scripts.runner.docker.Docker
        containerImage: ghcr.io/kestra-io/duckdb:latest
        script: |
          import duckdb
          import pandas as pd

          conn = duckdb.connect(database='dbt.duckdb', read_only=False)

          tables_query = "SELECT table_name FROM information_schema.tables WHERE table_schema = 'main';"
          tables = conn.execute(tables_query).fetchall()

          # Export each table to CSV, excluding tables that start with 'raw' or 'stg'
          for table_name in tables:
              table_name = table_name[0]
              # Skip tables with names starting with 'raw' or 'stg'
              if not table_name.startswith('raw') and not table_name.startswith('stg'):
                  query = f"SELECT * FROM {table_name}"
                  df = conn.execute(query).fetchdf()
                  df.to_csv(f"{table_name}.csv", index=False)

          conn.close()
```

![image](https://github.com/user-attachments/assets/3a40c93c-5222-4d77-a9e3-fde3054894a5)
