### ISSUE TITLE
Fold content lines button does not work

### ISSUE THREAD

**Issue by fdelbrayelle** [kestra-io/kestra#531]
### Expected Behavior

When I create a new Flow and click on the "Fold content lines" button
Then The lines content folds

![image](https://user-images.githubusercontent.com/296836/161395403-4799859c-1aa3-4e36-a7ff-2db1fa387c6e.png)

### Actual Behaviour

When I create a new Flow and click on the "Fold content lines" button
Then The lines content does not fold

![image](https://user-images.githubusercontent.com/296836/161395328-ca87a4a8-5c89-4341-bc7b-ecea9f029fd0.png)

### Steps To Reproduce

1. Go to http://localhost:28080/ui/flows/new
2. Paste some YAML like the given below
3. Click the "Fold content lines" button

```
id: logs
namespace: io.kestra.tests

tasks:
- id: t1
  type: io.kestra.core.tasks.debugs.Echo
  format: first {{task.id}}
  level: TRACE
- id: t2
  type: io.kestra.core.tasks.debugs.Echo
  format: second {{task.type}}
  level: WARN
- id: t3
  type: io.kestra.core.tasks.debugs.Echo
  format: third {{flow.id}}
  level: ERROR
```

### Environment Information

- Kestra Version: latest
- Operating System (OS / Docker / Kubernetes): Ubuntu
- Java Version (If not docker): 11
