### ISSUE TITLE
Render HTML file outputs in the Outputs preview

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5332]
### Feature description

Adding this inside an iframe with good restrictions will allow us to add it without compromising security

```yaml
id: html
namespace: company.team
tasks:
  - id: get
    type: io.kestra.plugin.core.http.Download
    uri: https://huggingface.co/datasets/kestra/datasets/resolve/main/html/forecast.html
```
