### ISSUE TITLE
Too much space when input has a long description

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5336]
### Describe the issue

We should significantly reduce the space generated by a newline

![image](https://github.com/user-attachments/assets/fc9d7a86-1711-4a78-afde-3b23bbcab84c)

reproducer:

```yaml
id: myflow
namespace: company.team

inputs:
  - id: test_long_description
    type: STRING
    defaults: hello
    description: This is a very long `description` of an input that will be split into multiple lines with too much space between lines. We should fix this to make the inputs display clearer and more visually appealing.

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀
```

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):
