### ISSUE TITLE
Change the order of loading files allowing to inject `namespaceFiles` to a `taskRunner` before loading task-specific files + avoid `java.nio.file.FileAlreadyExistsException` 

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5337]
### Example: dbt

Instead of overwriting the `profile`, dbt profiles added via dbt task property gives java.nio.file.FileAlreadyExistsException

reproducer:
```yaml
id: dbt_build
namespace: company.team

tasks:
  - id: sync
    type: io.kestra.plugin.git.SyncNamespaceFiles
    url: https://github.com/kestra-io/dbt-example
    branch: master
    namespace: company.team
    gitDirectory: dbt
    dryRun: false

  - id: dbt_build
    type: io.kestra.plugin.dbt.cli.DbtCLI
    containerImage: ghcr.io/kestra-io/dbt-duckdb:latest
    namespaceFiles:
      enabled: true
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
    commands:
      - dbt build
    profiles: |
      my_dbt_project:
        outputs:
          dev:
            type: duckdb
            path: ":memory:"
        target: dev    
```

error:

```
java.nio.file.FileAlreadyExistsException: /tmp/3a36oa9laKOXOGbZhCdw4R/profiles.yml at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source) at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source) at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(Unknown Source) at java.base/java.nio.file.Files.newByteChannel(Unknown Source) at java.base/java.nio.file.Files.createFile(Unknown Source) at io.kestra.core.runners.LocalWorkingDir.createFile(LocalWorkingDir.java:163) at io.kestra.plugin.scripts.exec.scripts.runners.CommandsWrapper.lambda$run$0(CommandsWrapper.java:143) at io.kestra.core.utils.Rethrow.lambda$throwConsumer$0(Rethrow.java:50) at java.base/java.lang.Iterable.forEach(Unknown Source) at io.kestra.plugin.scripts.exec.scripts.runners.CommandsWrapper.run(CommandsWrapper.java:141) at io.kestra.plugin.dbt.cli.DbtCLI.run(DbtCLI.java:284) at io.kestra.plugin.dbt.cli.DbtCLI.run(DbtCLI.java:39) at io.kestra.core.runners.WorkerTaskCallable.doCall(WorkerTaskCallable.java:78) at io.kestra.core.runners.AbstractWorkerCallable.call(AbstractWorkerCallable.java:56) at io.kestra.core.runners.WorkerSecurityService.callInSecurityContext(WorkerSecurityService.java:10) at io.kestra.core.runners.Worker.callJob(Worker.java:783) at io.kestra.core.runners.Worker.runAttempt(Worker.java:742) at io.kestra.core.runners.Worker.run(Worker.java:599) at io.kestra.core.runners.Worker.handleTask(Worker.java:284) at io.kestra.core.runners.Worker.lambda$run$7(Worker.java:240) at io.micrometer.core.instrument.internal.TimedRunnable.run(TimedRunnable.java:49) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by brian-mulier-p** [comment]
This is painful to handle and is more global than specific to DBT, this is due to the fact that as of now we have no way to create files from a task that comes on top of namespace files as the namespace files are injected in the taskRunner setup that comes after the task itself started to setup.

So basically rn when a task run with a task runner:
- generate any file from the task itself
- inject namespace files on top
- throw everything in the task runner
- run

The issue here is that an error is thrown while in theory the namespace files should override any generated file. However this is not the wanted behaviour and the files generated by the task itself should come on top of namespace files.
To tackle it we should probably separate the taskRunner run into a separate setupFiles then run methods, this way we can:
setupFiles(), generateFilesFromTask(), run()

Unassigning myself for now as I have other things to handle but as said it's more global than DBT.

**Comment by anna-geller** [comment]
one painful aspect is that because of this issue, even though I already have a `profiles.yaml` file in my namespace files, I need to specify it again on the profiles.yaml because namespace files are loaded too late into the task's working directory:

to reproduce, first runt this:
```yaml
id: upload_dbt_project
namespace: company.datateam.dbt

tasks:
  - id: wdir
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      - id: git_clone
        type: io.kestra.plugin.git.Clone
        url: https://github.com/kestra-io/dbt-example
        branch: master

      - id: upload
        type: io.kestra.plugin.core.namespace.UploadFiles
        namespace: "{{ flow.namespace }}"
        files:
          - "glob:**/dbt/**"
```

then this:

```yaml
id: dbt_build
namespace: company.datateam.dbt

tasks:
  - id: dbt
    type: io.kestra.plugin.dbt.cli.DbtCLI
    namespaceFiles:
      enabled: true
    containerImage: ghcr.io/kestra-io/dbt-duckdb:latest
    projectDir: dbt
    commands:
      - dbt build --project-dir dbt
    loadManifest:
      key: manifest.json
      namespace: "{{ flow.namespace }}"
    storeManifest:
      key: manifest.json
      namespace: "{{ flow.namespace }}"
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
```

that flow will fail. the only way atm to make it work is to explicitly set profiles inline:

```yaml
id: dbt_build
namespace: company.datateam.dbt

tasks:
  - id: dbt
    type: io.kestra.plugin.dbt.cli.DbtCLI
    namespaceFiles:
      enabled: true
    containerImage: ghcr.io/kestra-io/dbt-duckdb:latest
    projectDir: dbt
    commands:
      - dbt build --project-dir dbt
    loadManifest:
      key: manifest.json
      namespace: "{{ flow.namespace }}"
    storeManifest:
      key: manifest.json
      namespace: "{{ flow.namespace }}"
    profiles: |
      my_dbt_project:
        outputs:
          dev:
            type: duckdb
            path: ":memory:"
        target: dev      
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
```

**Comment by loicmathieu** [comment]
@brian-mulier-p 

> However this is not the wanted behaviour and the files generated by the task itself should come on top of namespace files.

One easy solution is to avoid creating the namespace file if a file with the same name exists.
Or we may throw so it fails the task, in this case the user must add an exclusion, this is more declarative and deterministic, WDYT @anna-geller ?

**Comment by anna-geller** [comment]
> the user must add an exclusion, this is more declarative and deterministic

smart 🧠 I should have thought about this. it makes sense. I'll add a Plugin example to dbt and close the issue then

**Comment by loicmathieu** [comment]
@anna-geller so should I filter the file, throw an exception, or stay like that with override the file?

**Comment by anna-geller** [comment]
> Or we may throw so it fails the task, in this case the user must add an exclusion, this is more declarative and deterministic 

not sure I understand. This seems like the current behavior already -- namespace files loaded profiles.yml. Then on my dbt task, I was trying to define `profiles` property which would attempt to create this file but it already exists based on injected namespace files and Kestra then throws `java.nio.file.FileAlreadyExistsException`. 

Try:
```yaml
id: dbt_build
namespace: company.team

tasks:
  - id: sync
    type: io.kestra.plugin.git.SyncNamespaceFiles
    url: https://github.com/kestra-io/dbt-example
    branch: master
    namespace: company.team
    gitDirectory: dbt
    dryRun: false

  - id: dbt_build
    type: io.kestra.plugin.dbt.cli.DbtCLI
    containerImage: ghcr.io/kestra-io/dbt-duckdb:latest
    namespaceFiles:
      enabled: true
      # exclude:
      #   - profiles.yml
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
    commands:
      - dbt build
    profiles: |
      my_dbt_project:
        outputs:
          dev:
            type: duckdb
            path: ":memory:"
        target: dev    
```

**Comment by anna-geller** [comment]
so it seems: if we add the docs with example like this, we are good?

```yaml
id: dbt_build
namespace: company.team

tasks:
  - id: sync
    type: io.kestra.plugin.git.SyncNamespaceFiles
    url: https://github.com/kestra-io/dbt-example
    branch: master
    namespace: company.team
    gitDirectory: dbt
    dryRun: false

  - id: dbt_build
    type: io.kestra.plugin.dbt.cli.DbtCLI
    containerImage: ghcr.io/kestra-io/dbt-duckdb:latest
    namespaceFiles:
      enabled: true
      exclude:
        - profiles.yml
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
    commands:
      - dbt build
    profiles: |
      my_dbt_project:
        outputs:
          dev:
            type: duckdb
            path: ":memory:"
        target: dev    
```
