### ISSUE TITLE
Fetch the name of a system namespace from the /config endpoint in the UI

### ISSUE THREAD

**Issue by MilosPaunovic** [kestra-io/kestra#5396]
Right now, in the `UI` (both `OSS` and `EE`) we have `system` namespaces fixed to that particular word, which is not ideal, see https://github.com/kestra-io/kestra/issues/5226#issuecomment-2393602768.

We need to decide are we going to handle this on UI side, which would mean we need to send the name of custom system namespace, and to decide whether this will be the new value in all of the select fields, or, are we going to handle this on the BE side, meaning to send and show `system` on the UI, and handle the rest on the side of endpoint.

I need your opinions here @Ben8t, @brian-mulier-p.

**Comment by Ben8t** [comment]
@MilosPaunovic 

if I understand, currently we don't take into account this configuration property ?

```yaml
kestra:
  system-flows:
    namespace: system # here user can configure to whatever word they want
```

To me backend should send this to frontend and so filter and system namespace should update accordingly
