### ISSUE TITLE
[Kestra EE] SQL Triggers broken in 0.19

### ISSUE THREAD

**Issue by johnkm516** [kestra-io/kestra#5401]
### Describe the issue

None of the SQL Triggers like 

```
triggers:
  - id: trigger
    type: io.kestra.plugin.jdbc.sqlserver.Trigger
    logLevel: WARN
    interval: 5.0
    url: "{{ secret('db.plm.jdbc_uri') }}"
    username: "{{ secret('db.plm.username') }}"
    password: "{{ secret('db.plm.password') }}"
    sql: |
      SELECT TOP(1) 1 FROM tablename
    fetch: true
    fetchSize: 100
```

are working properly since 0.19. 
I have a default worker and a worker group with a worker group key deployed. The triggers are executed by the default worker (no worker group key specified in the flow YAML). 
Looking at the server logs for the default worker, the triggers are not being executed at all. However tasks with no worker specified (such as an SQL query task with no worker key specified) seem to work fine. Only triggers are affected.

### Environment

- Kestra Version: 0.19.2
- Operating System (OS/Docker/Kubernetes): Docker
