### ISSUE TITLE
Weird if branch behavior

### ISSUE THREAD

**Issue by Tschrock** [kestra-io/kestra#5437]
### Describe the issue

Not sure if this is intended, but I didn't find any mention of this behavior in the docs, and it confused me for a bit.

I set up a pretty simple flow that just toggles a KV between "foo" and "bar"

<details><summary>Click to expand</summary>

```yaml
id: myflow
namespace: company.team
tasks:
  - id: if
    type: io.kestra.plugin.core.flow.If
    condition: "{{ kv('myvalue') == 'foo' }}"
    then:
    - id: log-start-foo
      type: io.kestra.plugin.core.log.Log
      message: Starting foo branch
    - id: set-bar
      type: io.kestra.plugin.core.kv.Set
      key: myvalue
      value: bar
    - id: log-end-foo
      type: io.kestra.plugin.core.log.Log
      message: Ending foo branch
    else:
    - id: log-start-bar
      type: io.kestra.plugin.core.log.Log
      message: Starting bar branch
    - id: set-foo
      type: io.kestra.plugin.core.kv.Set
      key: myvalue
      value: foo
    - id: log-end-bar
      type: io.kestra.plugin.core.log.Log
      message: Ending bar branch
 ```

</details>

Here's the topology for it:
![](https://p.cp3.es/ss1728811377-ad4f1c.png) 

From this and the other docs I've read, I would expect this to run in series like a computer program, either running
- if -> log-start-foo -> set-bar -> log-end-foo
or
- if -> log-start-bar -> set-foo -> log-end-bar

However, when I execute this flow it does this:

- if -> log-start-bar -> set-foo -> log-start-foo -> set-bar -> log-end-bar

![](https://p.cp3.es/ss1728811947-7de727.png)

![](https://p.cp3.es/ss1728812405-e03ff9.png)

It seems the "If" task will re-evaluate the condition and switch back and forth between paths as it changes, rather than picking a path and sticking to it.

### Environment

- Kestra Version: 0.19.2 - 4338437 Tue, Oct 8, 2024 9:52 AM
- Operating System (OS/Docker/Kubernetes): Docker (kestra/kestra:latest)
- Java Version (if you don't run kestra in Docker):
