### ISSUE TITLE
Unexpected 404 with a basic demo flow

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5438]
To reproduce, try adding this flow on develop and save:

```yaml
id: demo
namespace: company

tasks:
  - id: nothing
    type: io.kestra.plugin.core.log.Log
    message: nothing
```

This will give a 404 page not found error.

See https://share.descript.com/view/eBYYggadvan
