### ISSUE TITLE
Follow-Up on Dynamic Properties -- batch size for ForEachItem cannot be passed from inputs

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5442]
### Describe the issue

```
At flow: Cannot deserialize value of type `java.lang.Integer` from String "{{ inputs.batch_size}}": not a valid `java.lang.Integer` value at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: io.kestra.core.models.flows.Flow["tasks"]->java.util.ArrayList[1]->io.kestra.plugin.core.flow.ForEachItem["batch"]->io.kestra.plugin.core.flow.ForEachItem$Batch["rows"])
```

Reproducer:

```yaml
id: file_output_parent_concat_foreach_batch_1
namespace: company.team
inputs:
  - id: batch_size
    type: INT
    defaults: 1

description: |
  id: file_output_child
  namespace: company.team

  inputs:
    - id: json_file
      type: FILE

  tasks:
    - id: debug
      type: io.kestra.plugin.core.log.Log
      message: "{{ json(read(inputs.json_file)) }}"

    - id: jsonata
      type: io.kestra.plugin.transform.jsonata.TransformItems
      from: "{{ inputs.json_file }}"
      expression: |
        {
          "id": id,
          "name": data.Color & ' ' & name
        }

  outputs:
    - id: myoutput
      type: FILE
      value: "{{ outputs.jsonata.uri }}"

tasks:
  - id: extract
    type: io.kestra.plugin.jdbc.duckdb.Query
    sql: |
      INSTALL httpfs;
      LOAD httpfs;
      SELECT *
      FROM read_csv_auto('https://huggingface.co/datasets/kestra/datasets/raw/main/csv/orders.csv', header=True);
    store: true

  - id: for_each_item
    type: io.kestra.plugin.core.flow.ForEachItem
    items: "{{ outputs.extract.uri }}"
    batch:
      rows: "{{ inputs.batch_size}}"
    namespace: company.team
    flowId: file_output_child
    wait: true
    transmitFailed: true
    inputs:
      order: "{{ taskrun.items }}"

  - id: ion_to_json
    type: io.kestra.plugin.serdes.json.IonToJson
    from: "{{ outputs.for_each_item_merge.subflowOutputs }}"
    newLine: false

  - id: merge
    type: io.kestra.plugin.core.storage.Concat
    files: "{{ read(outputs.ion_to_json.uri) | jq('map(.myoutput)') | flatten }}"
    separator: "\n"

  - id: for_each
    type: io.kestra.plugin.core.flow.ForEach
    values: "{{ read(outputs.ion_to_json.uri) }}"
    tasks:
      - id: log
        type: io.kestra.plugin.core.log.Log
        message: "{{ read(json(taskrun.value).myoutput) }}"
```

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):
