### ISSUE TITLE
Improve concatenating ForEachItem + ForEach outputs 

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5456]
## Main issue

Looping across the output files from subflow executions would lead to the error:

```yaml
Unable to read the file 'kestra:///company/team/orders/executions/vBBGnSRLntC6xhA1IjFYc/tasks/transform/541J75lWtI0WQUvxz4v0qH/8580806061061976640.ion' as it didn't belong to the current execution
```

## Design spec outdated

The pluggable design proposed below is outdated as we decided to go for a single Enum property for specifying output handling + expand file output by default.

- [ ]  expand FILE outputs by default instead of only providing file URI because those files are not accessible to other tasks as they come from another execution (subflow execution)
- [ ]  Enum property for `outputFormat` handling

```yaml
id: json_file_output_parent_batch_1
namespace: company.team 

tasks:
  - id: download
    type: io.kestra.plugin.core.http.Download
    uri: https://api.restful-api.dev/objects
    contentType: application/json
    method: GET
    failOnEmptyResponse: true
    timeout: PT15S

  - id: json_to_ion
    type: io.kestra.plugin.serdes.json.JsonToIon
    from: "{{ outputs.download.uri }}"
    newLine: false # regular json

  - id: ion_to_jsonl
    type: io.kestra.plugin.serdes.json.IonToJson
    from: "{{ outputs.json_to_ion.uri }}"
    newLine: true # JSON-L

  - id: for_each_item
    type: io.kestra.plugin.core.flow.ForEachItem
    items: "{{ outputs.ion_to_jsonl.uri }}"
    batch:
      rows: 1
    namespace: company.team
    flowId: json_file_output_child
    wait: true
    transmitFailed: true
    outputFormat: SINGLE # SEPARATE - TBD it's whether single or more files
    inputs:
      json_file: "{{ taskrun.items }}"
```

## Context
There are many ways users may want to combine subflow execution outputs, and multiple concat strategies are needed depending on the output ID and type. To facilitate this, we want to explore a pluggable system where each plugin can perform custom concatenation strategy.

When implemented, this closes https://github.com/kestra-io/kestra-ee/issues/1934 as the Zip concat strategy would make accessing subflow execution files no longer necessary.

Subflow with 3 types of outputs:

```yaml
id: json_file_output_child
namespace: company.team

inputs:
  - id: json_file
    type: FILE

tasks:
  - id: debug
    type: io.kestra.plugin.core.log.Log
    message: "{{ json(read(inputs.json_file)) }}"

  - id: jsonata
    type: io.kestra.plugin.transform.jsonata.TransformItems
    from: "{{ inputs.json_file }}"
    expression: |
      {
        "id": id,
        "name": data.Color & ' ' & name
      }

outputs:
  - id: myoutput
    type: FILE
    value: "{{ outputs.jsonata.uri }}"

  - id: mystring
    type: STRING
    value: hello 

  - id: myint
    type: INT
    value: 42
```

Proposed solution with `compressOutputs` property allowing multiple outputs to be concatenated in various ways based on the chosen plugin:

```yaml
id: json_file_output_parent_batch_1
namespace: company.team 

tasks:
  - id: download
    type: io.kestra.plugin.core.http.Download
    uri: https://api.restful-api.dev/objects
    contentType: application/json
    method: GET
    failOnEmptyResponse: true
    timeout: PT15S

  - id: json_to_ion
    type: io.kestra.plugin.serdes.json.JsonToIon
    from: "{{ outputs.download.uri }}"
    newLine: false # regular json

  - id: ion_to_jsonl
    type: io.kestra.plugin.serdes.json.IonToJson
    from: "{{ outputs.json_to_ion.uri }}"
    newLine: true # JSON-L

  - id: for_each_item
    type: io.kestra.plugin.core.flow.ForEachItem
    items: "{{ outputs.ion_to_jsonl.uri }}"
    batch:
      rows: 1
    namespace: company.team
    flowId: json_file_output_child
    wait: true
    transmitFailed: true
    inputs:
      json_file: "{{ taskrun.items }}"
    # outputFormat: SEPARATE # tbd
```

**Comment by anna-geller** [comment]
example use cases and flows that can be used during design https://github.com/kestra-io/examples/tree/main/ForEachItem

**Comment by Harsh4902** [comment]
@anna-geller Can I work on this issue?

**Comment by MilosPaunovic** [comment]
Absolutely, go for it @Harsh4902! 🚀

**Comment by Harsh4902** [comment]
How can I check the current behavior of the application?

**Comment by MilosPaunovic** [comment]
@Harsh4902 Not sure what do you mean?

**Comment by anna-geller** [comment]
@Harsh4902 this issue is very very difficult, I'd suspect it can take 1-2 weeks. Perhaps you can check issues labeled as a good first issue instead?

**Comment by Harsh4902** [comment]
@anna-geller sure. I am unassigning the issue, but will try to work on this.

**Comment by loicmathieu** [comment]
If we do this, we should also provide the same for ForEach as this task also need to be able to concatenate its results (its subtask outputs).
See for example: https://kestra-io.slack.com/archives/C03FQKXRK3K/p1730131704470679

**Comment by anna-geller** [comment]
![image](https://github.com/user-attachments/assets/82ed5001-6be7-46ca-80f9-640afc039be5)

**Comment by loicmathieu** [comment]
This should fix https://github.com/kestra-io/kestra/issues/4996

**Comment by anna-geller** [comment]
was already linked ;)

**Comment by loicmathieu** [comment]
In the new `Loop` design you have to manually split if you want to batch.
Then the Loop can work on ION files and defines outputs.
After the Loop, you can then use concat the files and use the transformation for redduction.

The idea is that nothing should be transparent when dealing with files or data transformation: you can use separate tasks, each with it's own purpose.

See this complete example:

```yaml
id: elt_csv_split_loop_aggregate
namespace: loop.flow
labels:
  tier: tier2
description: |
  Map-reduce batch processing pattern. Pulls the public Kestra orders CSV, converts it to Ion
  (so records become typed structs with column names), splits the Ion file into chunks, and
  runs a `Loop` over the chunk URIs (filter then per-chunk aggregate by customer).
  Per-iteration aggregate URIs are surfaced via the loop-level `outputs:` declaration, then
  extracted with JSONata, concatenated into a single Ion file, and re-aggregated to merge the
  same customers across chunks — producing one final result file.

tasks:
  - id: download
    type: io.kestra.plugin.core.http.Download
    uri: https://huggingface.co/datasets/kestra/datasets/raw/main/csv/orders.csv

  - id: to_ion
    type: io.kestra.plugin.serdes.csv.CsvToIon
    from: "{{ outputs.download.uri }}"
    header: true

  - id: split
    type: io.kestra.plugin.core.storage.Split
    from: "{{ outputs.to_ion.uri }}"
    rows: 25

  - id: per_chunk
    type: io.kestra.plugin.core.flow.Loop
    values: "{{ outputs.split.uris }}"
    concurrencyLimit: 4
    fetchType: FETCH
    outputs:
      - id: data
        type: STRING
        value: "{{ outputs.aggregate.uri }}" 
    tasks:
      - id: filter
        type: io.kestra.plugin.transform.Filter
        from: "{{ item.value }}"
        where: todecimal(total) > 10

      - id: aggregate
        type: io.kestra.plugin.transform.Aggregate
        from: "{{ outputs.filter.uri }}"
        outputType: STORE
        groupBy: [customer_email]
        aggregates:
          orders:
            expr: count()
            type: INT
          revenue:
            expr: sum(todecimal(total))
            type: DECIMAL

  - id: concat
    type: io.kestra.plugin.core.storage.Concat
    files: "{{ loopOutputs(outputs.per_chunk.outputs, 'data') }}"
    extension: .ion

  - id: reduce
    type: io.kestra.plugin.transform.Aggregate
    from: "{{ outputs.concat.uri }}"
    outputType: STORE
    groupBy: [data.customer_email]
    aggregates:
      orders:
        expr: sum(orders)
        type: INT
      revenue:
        expr: sum(revenue)
        type: DECIMAL

  - id: log_summary
    type: io.kestra.plugin.core.log.Log
    message: "Map-reduce final aggregate file: {{ outputs.reduce.uri }}"
```

The `loopOutputs` can extract a list of values from the output of a loop sub-task for easier post-processing.

I'm closing this issue now, if you think the new mechanism can be improved, please open an issue with your thoughts on it.
