### ISSUE TITLE
Secret not work as password in io.kestra.plugin.fs.ssh.Command

### ISSUE THREAD

**Issue by pomazanbohdan** [kestra-io/kestra#5458]
### Describe the issue

If you write the password without a secret, the flow works, if you write it with a secret, it doesn't.
```
id: com.fprofitable-erp.chocolate-pull
namespace: evo.lab
description: ""

tasks:
  - id: command
    type: io.kestra.plugin.fs.ssh.Command
    authMethod: PASSWORD
    commands:
      - cd odoo/odoo_com_profitable-erp_chocolate/odoo_addons_17_nonfree/
      - git pull
    host: 204.12.YYY.XXX
    password: "{{ secret('SERVER_A') }}"
    username: administrator
disabled: false
```
.env_encoded^
`SECRET_SERVER_A=eHUqU2Qh#$hTOHpoDQ==`

0.19.2

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):
