### ISSUE TITLE
Add displayName to flow level outputs 

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5476]
### Feature description

In the same way as users can define `displayName` for `inputs`:

```yaml
id: request_resources
namespace: company.team

inputs:
  - id: resource_type
    displayName: Select the resource type
    type: SELECT
    required: true
    values:
      - Access permissions
      - SaaS application
      - Development tool
      - Cloud VM

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: requested {{ inputs.resource_type }}
```

We want to support `displayName` on flow `outputs`, e.g.:

```yaml
id: request_resources
namespace: company.team

inputs:
  - id: resource_type
    displayName: Select the resource type
    type: SELECT
    required: true
    values:
      - Access permissions
      - SaaS application
      - Development tool
      - Cloud VM

tasks:
  - id: getdata
    type: io.kestra.plugin.core.debug.Return
    format: requested {{ inputs.resource_type }}

outputs:
  - id: myoutput
    type: STRING
    value: "{{ outputs.getdata.value }}"
    displayName: Final returned value
```

![image](https://github.com/user-attachments/assets/a1a2791b-b812-40c9-aac6-33db12e6ee89)

The columns we want to display for both inputs are outputs are:
- Id
- Name
- Value
