### ISSUE TITLE
Add support of input type EMAIL 

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5477]
### Feature description

Sometimes the input is not just plain string but email. Implementing email validation regex every time can be tedious — we can add a new EMAIL input type to help with that use case. 

```yaml
id: myflow
namespace: company.team
inputs:
  - id: myemail
    type: EMAIL
    defaults: hello@kestra.io
tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello {{ inputs.myemail }}
```

trying to enter sth like "Arbitrary string" would not be allowed as this input must be a valid email.
