### ISSUE TITLE
Resuming an execution throws errors on develop

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5494]
### Describe the issue

Demo: https://share.descript.com/view/u1L1aa0eXRU

To reproduce, run this flow and then try to Resume:
```yaml
id: approval
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 

  - id: wait_for_approval
    type: io.kestra.plugin.core.flow.Pause
    onResume:
      - id: approved
        description: Whether to approve the request
        type: BOOLEAN
        defaults: true

      - id: comment
        description: Extra comments about the provisioned resources
        type: STRING
        defaults: All requested resources are approved    

  - id: bye
    type: io.kestra.plugin.core.log.Log
    message: bye
```

@fhussonnois maybe you see what's the issue?

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):
