### ISSUE TITLE
Replace the Resume button with two buttons: Resume + Cancel

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5499]
### Describe the issue

![image](https://github.com/user-attachments/assets/8d1527fc-6594-46e4-89c0-37f2273f69d0)

(the buttons will stay on the right side)

Reason: users need 2 options when validating whether execution should be resumed:
1. `Resume` = will Resume the execution (`Resumed` state)
2. `Cancel` = will Cancel the execution (`Cancelled` state)

Reproducer:

```yaml
id: approval
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 

  - id: wait_for_approval
    type: io.kestra.plugin.core.flow.Pause
    onResume:
      - id: approved
        description: Whether to approve the request
        type: BOOLEAN
        defaults: true

      - id: comment
        description: Extra comments about the provisioned resources
        type: STRING
        defaults: All requested resources are approved    

  - id: bye
    type: io.kestra.plugin.core.log.Log
    message: bye
```
