### ISSUE TITLE
[UI] Gantt view not updated anymore after a Pause task

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#5503]
### Describe the issue

Using the following flow:

```yaml
id: sandbox
namespace: company.team

tasks:
  - id: pause
    type: io.kestra.plugin.core.flow.Pause
    delay: PT5S
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: "Hello World"
```

After triggering the flow, the UI goes to the Gantt view.
After the pause task is executed, the Gantt is not updated with the new Log task, but refreshing the page shows the task.

See the screen share: 
[screen-capture (4).webm](https://github.com/user-attachments/assets/79c6a784-024f-492c-9f9f-e7142bef7a2b)

### Environment

- Kestra Version: 0.20.0-SNAPSHOT
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):
