### ISSUE TITLE
trigger input does not show after you navigate away from "Overview"

### ISSUE THREAD

**Issue by paulgrainger85** [kestra-io/kestra#5517]
Create a flow triggered by a webhook:

```yaml
id: webhook
namespace: demo

triggers:
  - id: hook
    type: io.kestra.plugin.core.trigger.Webhook
    key: qwertyuiopasdfghjkl

tasks:
  - id: triggered
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀
```

Trigger the flow:
```bash
curl http://localhost:8080/api/v1/executions/webhook/demo/webhook/qwertyuiopasdfghjkl
```

Navigate to Executions -> latest execution for this flow -> Overview. You will see 3 trigger inputs
![image](https://github.com/user-attachments/assets/b95f1b34-2e99-41a7-a0fc-e6dbd9db516f)

In the execution navigate to another tab, e.g. Logs then back to Overview. Note now that the trigger values do not show
![image](https://github.com/user-attachments/assets/dc8db2a8-2aec-44c7-bdc8-e3fe93ce00a8)

Page must be refreshed to see the values

### Environment

- Kestra Version: 0.19.2
- Operating System: Docker (macOS)
