### ISSUE TITLE
Expand the first output of the first task by default

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5523]
### Feature description

Video Explanation: https://share.descript.com/view/XZfNQXgUj5A

When you run the workflow below and navigate to Outputs, you currently see only tasks and you need to expand to see any task outputs:

![image](https://github.com/user-attachments/assets/b710c412-46c6-40ce-8986-0e0b6d28ea48)

We had a customer request to expand the first output of the first task by default — this will also make the Outputs functionality more visible and will highlight the important `Debug Outputs` button:

![image](https://github.com/user-attachments/assets/4491f74f-7ecb-4b0b-b34e-d63285f5aacf)

![image](https://github.com/user-attachments/assets/49624428-5ada-4e67-b1f9-444eb18da351)

Reproducer workflow:

```yaml
id: data_engineering_pipeline
namespace: tutorial
description: Data Engineering Pipelines

inputs:
  - id: columns_to_keep
    type: ARRAY
    itemType: STRING
    defaults: 
      - brand
      - price

tasks:
  - id: extract
    type: io.kestra.plugin.core.http.Download
    uri: https://dummyjson.com/products

  - id: transform
    type: io.kestra.plugin.scripts.python.Script
    containerImage: python:3.11-alpine
    inputFiles:
      data.json: "{{ outputs.extract.uri }}"
    outputFiles:
      - "*.json"
    env:
      COLUMNS_TO_KEEP: "{{ inputs.columns_to_keep }}"
    script: |
      import json
      import os

      columns_to_keep_str = os.getenv("COLUMNS_TO_KEEP")
      columns_to_keep = json.loads(columns_to_keep_str)

      with open("data.json", "r") as file:
          data = json.load(file)

      filtered_data = [
          {column: product.get(column, "N/A") for column in columns_to_keep}
          for product in data["products"]
      ]

      with open("products.json", "w") as file:
          json.dump(filtered_data, file, indent=4)

  - id: query
    type: io.kestra.plugin.jdbc.duckdb.Query
    inputFiles:
      products.json: "{{ outputs.transform.outputFiles['products.json'] }}"
    sql: |
      INSTALL json;
      LOAD json;
      SELECT brand, round(avg(price), 2) as avg_price
      FROM read_json_auto('{{ workingDir }}/products.json')
      GROUP BY brand
      ORDER BY avg_price DESC;
    store: true
```
