### ISSUE TITLE
Cannot use FLOAT type as input in SubFlow

### ISSUE THREAD

**Issue by paulgrainger85** [kestra-io/kestra#5535]
### Describe the issue

Define these 2 flows
```
id: parent_flow
namespace: sales

tasks:
  - id: exec_subflow
    type: io.kestra.plugin.core.flow.Subflow
    namespace: sales
    flowId: subflow_test
    inputs:
      myfloat: 0.5

-----

id: subflow_test
namespace: sales

inputs:
  - id: myfloat
    type: FLOAT

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello values is {{inputs.myfloat}}
```

Execute parent flow. Subflow execution fails with this error
```
2024-10-17 20:54:06.052myfloat: Invalid input for `myfloat`, java.lang.Exception: Expected `FLOAT` but received `0.5` with errors: ``` class java.lang.Double cannot be cast to class java.lang.String (java.lang.Double and java.lang.String are in module java.base of loader 'bootstrap') ```, but received `0.5`
```

### Environment

- Kestra Version: 0.19.2
- Docker
