### ISSUE TITLE
Pre-render Pebble in URL (currently gives a bug)

### ISSUE THREAD

**Issue by janorga** [kestra-io/kestra#5581]
### Feature description

This a mix about a Feature request and a Bug. Consider a flow where you have a task calling a subflow in a "templated" way like

```yaml
      - id: call_invoke_migration
        type: io.kestra.plugin.core.flow.Subflow
        namespace: "{{ flow.namespace }}"
        flowId: invoke_migration
```

Now, if one goes to Topology in an Execution and expands the Subflow, a 404 error is given because the formed URL would be: `/ui/flows/edit/{{ flow.namespace }}/invoke_migration/overview`

In this way, it would be super nice that when a request is done, first a Pebble rendering is also triggered.

Note that you can even have more complex templating in a subflow call, like: `namespace: "{{ (flow.namespace | split('\\.'))[0] }}"`. Why so complex templating? Because this could be a workaround for working in develop namespace and you want the subflow calls to be relative to the rendered workspace, because you probably want a Sync (push) to Git with a sourceNamespace "develop" but a targetNamespace "production" (so subflow calls (called namespace) are not modified when GitPush flow is executed).

Note that having that 404 error is also currently a bug because we are allowing that templating in namespace but breaking the Topology (and maybe other things that I haven't tested).

**Comment by janorga** [comment]
@anna-geller please check this and triage it as it is needed. Currently, it behaves like a bug, but maybe what I am requesting is a major in terms of a feature request.

**Comment by Ben8t** [comment]
Thanks @janorga for raising this one. The 404 is definitely a bug 👍 Especially at Execution time (Pebble is rendered so we got the info)

However, outside execution, I can understand that technically speaking it can be hard to render the pebble value. Let one of our engineer look through it.
cc @Skraye @loicmathieu

**Comment by loicmathieu** [comment]
Yes, we need investiguation as we may not have the correct execution context.

As a side note, we can relax the requirement to specify the namespace of the subflow and use the parent flow namespace itself, it would makes your example easier to writte.

**Comment by janorga** [comment]
@loicmathieu I don't know if I have got your point correctly (😅). If I got you well, how would you achieve a flow in "develop.nested_namespace" to call a subflow in "develop" namespace? Note: the goal is to achieve that it is going to work when Git Push to `targetNamespace: production` as an example.

Just maybe I am hitting a corner (maybe nonsense?) use case, but it is about covering all the scenarios for a possible bug.

**Comment by anna-geller** [comment]
This is now handled ✅ 


```yaml
id: child
namespace: company.team

tasks:
  - id: hello_from_child
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 
```

and:

```yaml
id: parent
namespace: company.team

tasks:
  - id: call_subflow
    type: io.kestra.plugin.core.flow.Subflow
    namespace: "{{ flow.namespace }}"
    flowId: child
```

Expanding subflow task is now handled quite well https://jam.dev/c/5b4a1941-095b-4cd8-8df2-4026207d10b5

Steps:

1. Navigate to Edit flow page (00:01)
2. Edit the flow (00:02)
3. Attempt to expand the subflow task 'hello_from_parent' (00:05)
4. See the error message: "Can't expand subflow task 'hello_from_parent' because namespace and/or flowId contains dynamic values. This can only be viewed on an execution." (00:06)
5. Execute the flow (00:10)
6. Go to the Execution Topology page (00:12)
7. Attempt to expand 'hello_from_parent' task again (00:14) and validate it works as expected 
![image](https://github.com/user-attachments/assets/e4fad89e-9f61-4c8a-9087-80f74932e4ba)

![image](https://github.com/user-attachments/assets/1f8d0686-3799-4345-be4c-d91e8e2b4c83)

## Best practice

As a best practice, we recommend EXPLICITLY declaring the namespace and flowId when using parent-child workflows with both subflows and flow triggers for 2 reasons:
1. Kestra is declarative and pebble should only be used when really needed for some dynamic conditions e.g. in `runIf` or If-like conditions
2. The UI and some triggers may not work correctly without it as we see here when subflow topology cannot be expanded until runtime
