### ISSUE TITLE
Execution chart shows Invalid date

### ISSUE THREAD

**Issue by paulgrainger85** [kestra-io/kestra#5582]
### Describe the issue

Add the following flow and wait a few minutes for data. Then view Executions for past 5 minutes (e.g. http://localhost:8080/ui/executions?scope=USER&timeRange=PT5M). All x-axis values show "Invalid Date"

This should show the correct time bucket 

```
id: tasks
namespace: demo
tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀
  - id: hello_again
    type: io.kestra.plugin.core.log.Log
    message: Running some tasks
  - id: loop
    type: io.kestra.plugin.core.flow.ForEach
    values: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    concurrencyLimit: 2
    tasks:
      - id: parallel
        type: io.kestra.plugin.scripts.shell.Commands
        commands:
          - echo "this is value {{taskrun.value}}"

triggers:
  - id: every_second
    type: io.kestra.plugin.core.trigger.Schedule
    withSeconds: true
    cron: "*/1 * * * * *"
```

![image](https://github.com/user-attachments/assets/0f20771d-9004-4b46-ad73-b4e99bfda73a)

### Environment

- Kestra Version: 0.19.4
- Operating System: Kubernetes
