### ISSUE TITLE
Storing into Kestra Internal Storage does not take into account illegal characters

### ISSUE THREAD

**Issue by johnkm516** [kestra-io/kestra#5589]
### Describe the issue

I'm trying to download a file into Kestra's internal storage using the ```io.kestra.plugin.core.http.Download``` task, but this task fails because the filename of the downloaded file has illegal characters for the URI. Here's the error log for the download task : 

```Illegal character in path at index 122: kestra:///plm/complm-cm-dd-005-worker/executions/1QE1b2wn7AS3yoJTtqKKmm/tasks/centric-downloadfile/1E8tP0Znk8oTzN33AEVRYv/[TEST용]-Adobe-Artboard-for-APP_Sarah-23.png```

I have no control over the endpoint and the endpoint itself does not support renaming the file in the request. Kestra fails to add the file to the internal storage because ```[```,```]``` are illegal characters for URI. 

I suspect this issue will occur for any download of files or any time a file is stored in internal storage with the filename set by external factors, not just exclusive to HTTP Download. 

My proposed solution would be to automatically url encode the filename any time Kestra stores something in internal storage, and automatically decode it during retrieval. 

### Environment

- Kestra Version: 0.19.4
- Operating System (OS/Docker/Kubernetes): Docker

**Comment by Malaydewangan09** [comment]
Hey @MilosPaunovic @johnkm516 
Can I pick this up?
Thanks!

**Comment by MilosPaunovic** [comment]
It's fine by me, but let's first close https://github.com/kestra-io/kestra/issues/5590, as you're already assigned there. After, you can switch to this issue.

**Comment by Malaydewangan09** [comment]
Sure, Thanks!

**Comment by johnkm516** [comment]
@Skraye 
The commit didn't fix the issue. Now the task itself succeeds but the file doesn't exist in the Kestra internal storage. 

<img width="758" alt="image" src="https://github.com/user-attachments/assets/7e9b2b8b-15b8-49e7-9313-fa50ada19098">

Clicking on "Download" goes to : 

<img width="956" alt="image" src="https://github.com/user-attachments/assets/922e96a0-964f-4008-92f7-4a5bcc092bff">

**Comment by johnkm516** [comment]
@Skraye 

Sorry to bump this again, your commits in the latest release worked, but now the problem is in purge. I'm getting the following error when purging successful task executions : 

![image](https://github.com/user-attachments/assets/03b79e6b-991f-40b7-99f9-088612032074)

**Comment by Skraye** [comment]
Misread the issue, can you send the path so I can see which character is the wrong one, as your path seems already encoded

**Comment by johnkm516** [comment]
@Skraye The log is all I have. It seems to me the problem is the encoding? The log error is this : 

`Illegal character in path at index 122: kestra:///plm/complm-cm-dd-005-worker/executions/6j0m2Oeyt025Bxwiuwkylv/tasks/centric-downloadfile/1CAiNO1phjV3DAeDokDKBi/"%5BTEST%EC%9A%A9%5D-Adobe-Artboard-for-APP_Sarah-28.png"`

I think the issue is the double quotation in the filename, I don't know what that's there :

`"%5BTEST%EC%9A%A9%5D-Adobe-Artboard-for-APP_Sarah-28.png"`

**Comment by Skraye** [comment]
Seems due to the double quote, we have an issue for that, its unrelated to the encoding

**Comment by yuri1969** [comment]
FYI this issue (the Internal Storage not handling files containing `@`) seems to be present in v0.16.16.

**Comment by Skraye** [comment]
@yuri1969 Does it concerns also the Download Task or another use case ?

**Comment by yuri1969** [comment]
@Skraye I am able to download and preview the generated output on the Outputs view. AFAIK we do not use the Download task.

```yaml
id: uri-chars
namespace: test

inputs:
  - id: fileName
    type: STRING
    #defaults: "foo@bar" # FIXME
    defaults: "foo.bar"

tasks:
  - id: prepare-data
    type: io.kestra.plugin.scripts.shell.Commands
    commands:
      - "echo 'TEST' > {{ outputDir }}/{{ inputs['fileName'] }}"

  - id: read-data
    type: io.kestra.plugin.scripts.shell.Commands
    commands:
      - "cat {{ outputs['prepare-data']['outputFiles'][inputs['fileName']] }}"
```
