### ISSUE TITLE
Extend the SELECT input with a radio-button option

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5591]
### Feature description

Using this flow:

```yaml
id: choose_your_cloud
namespace: company.team

inputs:
  - id: cloud
    type: SELECT
    allowCustomValue: true
    values:
      - AWS
      - GCP
      - Azure
      - Oracle

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello {{ inputs.cloud }}
```

You can see the SELECT will be by default shown as a dropdown:

![image](https://github.com/user-attachments/assets/91ac03e6-d064-49e3-a3e6-6e1f78fa9eed)

For some use cases, a radio button might be more desirable. We can add an ENUM option `displayType: RADIO_BUTTON`:

```yaml
id: choose_your_cloud
namespace: company.team

inputs:
  - id: cloud
    type: SELECT
    allowCustomValue: true
    displayType: RADIO_BUTTON # default is DROPDOWN
    values:
      - AWS
      - GCP
      - Azure
      - Oracle

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello {{ inputs.cloud }}
```

`DROPDOWN` should stay as the default option as it's more compact.

---

Note: Adding the ENUM property has a small backend part.
