### ISSUE TITLE
Add Exit task to immediately end the execution in a Success/Warning/Killed state without processing any downstream tasks

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5599]
```yaml
id: myflow
namespace: company.team
tasks:
  - id: terminate_successfully
    type: io.kestra.plugin.core.execution.Exit
    state: SUCCESS # Enum by default set to SUCCESS with options also for WARNING, KILLED and FAILED
```

The main goal of this task would be to introduce a behavior similar to Python's `sys.exit(0)` or linux `exit 0`.

**Comment by Smiloutcha** [comment]
Hi @anna-geller, could you clarify the purpose of adding this feature? Will it provide a specific functionality, or is it intended just for demonstration purposes?

**Comment by anna-geller** [comment]
One user asked about it for a more elaborate conditional logic so we opened the issue 

In case you consider contributing, keep in mind this will need to touch some code on the Executor side to be aware of this new task that can set Execution state to a Success

**Comment by Smiloutcha** [comment]
Hello @anna-geller,
I’d love to contribute! However, I’m still unclear on the specifics behind the Success type. When the workflow reaches a task of type Success, what exactly should I be checking? Additionally, could you provide the steps for debugging Kestra from the Docker image? I’ve tried but haven’t been successful so far.

**Comment by MilosPaunovic** [comment]
Hi @Smiloutcha,

It might be better if you'd look through other issues from the [curated list](https://github.com/orgs/kestra-io/projects/15/views/1?filterQuery=no%3Aassignee+label%3A%22good+first+issue%22) of good first ones and check if there is any which you can solve independently. That way, your help would be most aprreciated. 🚀

**Comment by Smiloutcha** [comment]
Hello @MilosPaunovic,
Thank you for your response. Could you help me understand the reason behind your suggestion? I’d appreciate any clarification.

**Comment by anna-geller** [comment]
@Smiloutcha I refined the issue body and I'm adding an example below that shows the use case for this new plugin: task3 and task4 should never run if the input is set to false

```yaml
id: conditional
namespace: company.team

inputs:
  - id: run_if_true
    type: BOOLEAN
    defaults: true

tasks:
  - id: conditional
    type: io.kestra.plugin.core.flow.If
    condition: "{{ inputs.run_if_true }}"
    then:
      - id: task1
        type: io.kestra.plugin.core.log.Log
        message: Hello 
      - id: task2
        type: io.kestra.plugin.core.log.Log
        message: Hello     
    else:
      - id: exit_0
        type: io.kestra.plugin.core.execution.Exit

  - id: task3
    type: io.kestra.plugin.core.log.Log
    message: This should not run if  "{{ inputs.run_if_true }}" is false
    
  - id: task4
    type: io.kestra.plugin.core.log.Log
    message: This should not run if  "{{ inputs.run_if_true }}" is false   
```
