### ISSUE TITLE
Add revision history for Namespace Files

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5617]
In the same way we offer revision history for flows, users should be able to view and restore previous versions of Namespace Files.

Each Namespace File uploaded with the same path creates a new revision, while the **base file always represents the latest version**:

* First upload: `queries/my_query.sql` → treated as version 0 (for backward compatibility)
* Second upload: `queries/my_query.sql.v1`
* Third upload: `queries/my_query.sql.v2`
* The latest version is always stored as `queries/my_query.sql`, with older versions kept under suffixed names.

Users can view and restore revisions through a **“Revision History”** option visible next to the Save icon on each Namespace File opened in the Editor, or via right-click in the File Explorer window.

<img width="1189" height="764" alt="Image" src="https://github.com/user-attachments/assets/ec3066e4-e488-4988-8175-90fee4c3eb43" />

Clicking on this icon can open a closable Revision History window from where user can inspec past revisions side-by-side and restore the chosen version without disrupting any existing editor panels:

<img width="2161" height="820" alt="Image" src="https://github.com/user-attachments/assets/6ab4f892-f360-486d-972d-3a1e6f77a445" />

### Follow-up

- [x] Add audit logs to record who edited each revision and when
- [x] When renaming a file, it should increase the version
- [x] Extend the `read('queries/my_query.sql', version=2)` function to allow pointing to a specific revision. 
- [x] Add a visual indicator when viewing a non-latest version of a given namespace file
- [ ] Add `PurgeFiles` task allowing to purge Namespace Files with optional behavior allowing to only purge old revisions 
```yaml
id: purge_ns_files
namespace: company.team

tasks:
  - id: purge_ns_files
    type: io.kestra.plugin.core.files.PurgeFiles 
    # similar to io.kestra.plugin.core.kv.PurgeKV
    namespaces:
      - company
    includeChildNamespaces: true
    namespacePattern: Glob pattern for the namespaces to delete files from. If not set (e.g., company_*), all namespaces will be considered. Can't be used with namespaces - use one or the other.
    filePattern: string for a glob file pattern, e.g. "*.sql" to purge only files matching the glob pattern.
    behavior: 
      oldRevisionsOnly: true
```
- [ ] (optional, might be difficult) allow referencing an older revision of a file explicitly in commands
```yaml
tasks:
  - id: hello
    type: io.kestra.plugin.scripts.python.Commands
    namespaceFiles:
      enabled: true
    commands:
      - python scripts/main.py.v2
```
