### ISSUE TITLE
Inputs validation UI throws "Form error Invalid field: XYZ" for any input

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5639]
Any parametrized flow currently gives UI validation errors on develop (the execution can be created just fine though):

reproducer:

```yaml
id: hello_world
namespace: tutorial
description: Hello World
inputs:
  - id: user
    type: STRING
    defaults: Rick Astley
tasks:
  - id: first_task
    type: io.kestra.plugin.core.debug.Return
    format: thrilled
  - id: second_task
    type: io.kestra.plugin.scripts.shell.Commands
    commands:
      - sleep 0.42
      - echo '::{"outputs":{"returned_data":"mydata"}}::'
  - id: hello_world
    type: io.kestra.plugin.core.log.Log
    message: |
      Welcome to Kestra, {{ inputs.user }}! 
      We are {{ outputs.first_task.value}} to have You here!
```

![image](https://github.com/user-attachments/assets/93a88509-c91b-483c-ae1e-e185e45edccc)

![image](https://github.com/user-attachments/assets/281d3b0c-80fc-48af-8416-855d85b4824e)

### Environment

- Kestra Version: develop
