### ISSUE TITLE
Autocompletion for the "error" property is aware of taskId but not aware of message and stackTrace properties

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5641]
### Describe the issue

![image](https://github.com/user-attachments/assets/d04a1377-32b0-4b71-8c51-78301a9c7c6a)

We should extend the autocompletion if possible so that users don't have to look up those `error` properties

To reproduce:

```yaml
id: errors
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Starting the workflow
  - id: fail
    type: io.kestra.plugin.core.execution.Fail

errors:
  - id: error-log
    type: io.kestra.plugin.core.log.Log
    message:
      - "It's the fault of '{{ error.taskId }}'"
      - "See the message: {{ error.message }}"
      - "{{ error.stackTrace }}"
```

### Environment

- Kestra Version: develop
