### ISSUE TITLE
Plugin icons are not rendered correctly in the Outputs tab for errors tasks 

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5643]
### Describe the issue

![image](https://github.com/user-attachments/assets/e024181f-9301-488c-a60e-9b89df54679c)

## Reproducer flow

```yaml
id: errors
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Starting the workflow
  - id: fail
    type: io.kestra.plugin.core.execution.Fail

errors:
  - id: return
    type: io.kestra.plugin.core.output.OutputValues
    values:
      message: "{{ error.message }}"
      taskId: "{{ error.taskId }}"
      stacktrace: "{{ error.stackTrace }}"

  - id: error_log
    type: io.kestra.plugin.core.log.Log
    message:
      - "It's the fault of '{{ error.taskId }}'"
      - "See the message: {{ error.message }}"
      - "{{ error.stackTrace }}"
```

### Environment

- Kestra Version: develop
