### ISSUE TITLE
Propagate correlationId label also to the initial flow that triggered the subflow

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5644]
### Feature description

Let's say we have 3 flows, parent called flow1 and two subflows flow2 and flow3 triggered in a chain:

flow1 --> flow2 --> flow3

Currently, the `executionId` of flow1 will be propagated as `system_correlationId` label to flow2 and flow3 but I believe flow1 should also get the same label to clearly indicate all flows in the chain incl. the initial one

![image](https://github.com/user-attachments/assets/a69657e9-aede-435e-98ed-bcd6d5d6cb7f)

To reproduce:

```yaml
id: flow1
namespace: company.team
tasks:
  - id: subflow
    type: io.kestra.plugin.core.flow.Subflow
    namespace: company.team
    flowId: flow2
``` 

```yaml
id: flow2
namespace: company.team
tasks:
  - id: subflow
    type: io.kestra.plugin.core.flow.Subflow
    namespace: company.team
    flowId: flow3
``` 

```yaml
id: flow3
namespace: company.team
tasks:
  - id: log
    type: io.kestra.plugin.core.log.Log
    message: hello from the last flow
```

**Comment by loicmathieu** [comment]
This is not that easy as when we propagate the correlationId to the first subflow, we cannot update the parent execution.
We can add the correlationId to all execution but it would just be a duplicate of the executionId.

This needs investigation on how to do this the best.

**Comment by anna-geller** [comment]
interesting, I thought we could add this label (as below but automatically) to all executions that have at least 1 subflow task and don't have any upstream parent execution ID?

```yaml
id: flow1
namespace: company.team

labels:
  system_correlationId: "{{ flow.executionId }}"

tasks:
  - id: subflow
    type: io.kestra.plugin.core.flow.Subflow
    namespace: company.team
    flowId: flow2
```

> We can add the correlationId to all execution but it would just be a duplicate of the executionId.

This would run the risk that the subflow execution would get its own correlationId (equal to is own executionId) overriding the one it got from parent right?
