### ISSUE TITLE
Add pebble function to access taskrun value for which the task failed in ForEach 

### ISSUE THREAD

**Issue by paulgrainger85** [kestra-io/kestra#5653]
### Feature description

Take the example flow here. If this flow breaks during an iteration of ForEach, we should be able to access the value at the current `{{taskrun.value}}` . However currently this is not passed through as we are no longer in the flowable context

```
id: errors
namespace: demo

variables:
  current_iteration: ""

tasks:
- id: iterateObjects
  type: io.kestra.plugin.core.flow.ForEach
  concurrencyLimit: 1
  values: '["/tmp/kestra-wd/data/good.csv", "/tmp/kestra-wd/data/error.csv"]'
  tasks:
    - id: debugCurrentIteration
      type: io.kestra.plugin.core.debug.Return
      format: "{{ taskrun.value }}"

    - id: printFileName
      type: io.kestra.plugin.core.log.Log
      message: Let's read CSV {{ taskrun.value }}

    - id: downloadFile
      type: io.kestra.plugin.core.http.Download
      uri: '{{ taskrun.value }}'
  errors:
    - id: printErrorMsg
      type: io.kestra.plugin.core.log.Log
      message: Error reading {{ taskrun.value }}
```

**Comment by anna-geller** [comment]
`error.value` will be extra information printed for Flowable that do some sort of iteration

- taskrun.items for ForEachItem
- taskrun.value for ForEach
- loop.iterationCount for WaitFor
- case for Switch task

**Comment by anna-geller** [comment]
a short info that the errorLogs() pebble function doesn't solve the issue of providing info about the loop iteration value for which the ForEach task has failed

here is an example that shows why:

```yaml
id: fail
namespace: company.team
tasks:
  - id: for_each
    type: io.kestra.plugin.core.flow.ForEach
    values: "{{ range(1, 5) }}"
    tasks:
      - id: fail_for_4
        type: io.kestra.plugin.core.execution.Fail
        runIf: "{{ taskrun.value == '4' }}"
        errorMessage: Bad value returned!
    errors:
      - id: debug_msg
        type: io.kestra.plugin.core.log.Log
        message: Error reading {{ errorLogs() }}
```

The errorLogs() will return:

```json
[{"namespace":"company.team","flowId":"fail","taskId":"fail_for_4",
"executionId":"5Tm6g3inZS28tmYSfsFEY6",
"taskRunId":"2QP4rRmgUG3k3TSFSdEIkJ",
"attemptNumber":0,"timestamp":"2024-12-09T21:36:50.672Z","level":"ERROR","thread":"worker_4",
"message":"Bad value returned!","deleted":false}]
```

this doesn't provide info that the loop failed for the taskrun.value == 4.

**Comment by paulgrainger85** [comment]
Hi, has there been any further discussion on adding this? Agree with Anna that errorLogs() does not provide the required information. thanks!

**Comment by anna-geller** [comment]
@tchiotludo, since you blocked the `error.value` implementation, do you have some suggestions on how this should be addressed technically? this is needed by customers

**Comment by tchiotludo** [comment]
for the visibility, @Skraye should restart a new implementation, but no more blocker

**Comment by tchiotludo** [comment]
Another [customer request](https://kestra-io.slack.com/archives/C080UCPG7M1/p1742925157414839) to have `{{ error.taskId }}` to have this use case: 
```yaml 
errors:
- id: switch
  type: io.kestra.plugin.core.flows.Switch
  value: "{{error.taskId}}"
  cases:
    task_one:
    - id: handle_task_one_error
      type: io.kestra.plugin.core.log.Log
      message: "task one failed!!!!"
    task_two:
    - id: handle_task_two_error
      type: io.kestra.plugin.core.log.Log
      message: "task two failed!!!!"
```
