### ISSUE TITLE
Error with Inputs Implementation in Kestra Flows

### ISSUE THREAD

**Issue by userS4B0** [kestra-io/kestra#5663]
## Issue Overview
When attempting to implement inputs in Kestra flows, an error message appears indicating a problem with the input. However, the input is correctly passed to the task, and the flow executes successfully.

## Steps to reproduce
1. Configure a Kestra flow with an input in YAML.
2. Set up a simple flow to execute a "hello world" command on remote servers via Ansible.
3. Run the flow manually in the Kestra environment.

##### Example Kestra Workflow
```yaml
id: ansible_test_01
namespace: mycompany.examples.ansible
  
inputs:
  - id: hosts
    type: STRING
    required: true
    defaults: "test_server" # In this example refers to localhost
    displayName: "Destination Server"


tasks:
  - id: ansible_task
    type: io.kestra.plugin.ansible.cli.AnsibleCLI
    inputFiles:
      inventory.yml: "{{ read('inventory/test_inventory.yml') }}"
      playbook.yml: "{{ read('playbooks/test_plb.yml') }}"

    containerImage: cytopia/ansible:latest-tools
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
      cpu:
        cpus: 1
      memory:
        memory: 512Mb
      pullPolicy: IF_NOT_PRESENT

    commands:
      - ansible-playbook -i inventory.yml playbook.yml --limit {{ inputs.hosts }}
    
    env:
      ANSIBLE_HOST_KEY_CHECKING: "False"
```

##### Example inventory/test_inventory.yml
```yaml
all:
  hosts:
    test_server: 
      ansible_connection: local
    test_server_2:
      ansble_host: 172.31.174.5
      ansible_port: 1473
```

##### Example playbooks/test_plb.yml
```yaml
- hosts: all
  tasks:
  - name: Send Hello World Message
    debug:
      msg: "Hello From Ansible"
```

## Expected Behaviour
The flow should run without displaying any errors regarding the inputs when they are configured correctly.

## Actual Behaviour
Even though the input is passed correctly and the flow executes successfully, an error message consistently appears regarding problems with the input.

##### Error Message Screenshot
![KestrInputError](https://github.com/user-attachments/assets/a67509f4-c78e-46c5-884f-4e2e5324a061)

##### Successful Execution Screenshot
![KestraFlowSuccess](https://github.com/user-attachments/assets/c5193963-c5f9-436d-b2a4-3a3917d36695)

### Additional Context
This error message appears in every Kestra flow that includes inputs, regardless of whether it’s with the Ansible plugin or other plugins.

### Environment

- Kestra Version: kestra-0.19.5
- Operating System: Ubuntu (noble) 24.04.1 LTS
- Java Version: OpenJDK Runtime Environment Temurin-21.0.5+11 (build 21.0.5+11-LTS)

**Comment by mithindev** [comment]
Hello @userS4B0, could this error be due to:

<img width="804" alt="image" src="https://github.com/user-attachments/assets/7042ccb3-2045-443e-bd5d-21f1680fef8d">

**Comment by userS4B0** [comment]
Hi @mithindev, as I've said in the issue description this error looks unrelated to plugins, Here you have an example with a simple log flow.

```yaml
id: error_poc_02
namespace: byteguardshield.dev.test

inputs:
  - id: name
    type: STRING
    defaults: "Ryan"
    
tasks:
  - id: error_poc
    type: io.kestra.plugin.core.log.Log
    message: Hello {{ inputs.name }}
```

When I run the task I get the same error:
![KestrInputError2](https://github.com/user-attachments/assets/cc431c80-2a6a-4450-8fd0-ddf2191cb707)

And as you can see, the execution is successfull and the input string is passed correctly to the task:
![KestraFlowSuccess2](https://github.com/user-attachments/assets/9e91b773-7d84-457d-bee7-e3cf95253898)
