### ISSUE TITLE
Documentation: Port should be a string `io.kestra.plugin.fs.smb.Upload`

### ISSUE THREAD

**Issue by johnsturgeon** [kestra-io/kestra#5666]
### Describe the issue

Small tweak to fix the documentation for `io.kestra.plugin.fs.smb.Upload`

change:
```yaml
id: fs_smb_upload
namespace: company.team

inputs:
  - id: file
    type: FILE

tasks:
  - id: upload
    type: io.kestra.plugin.fs.smb.Upload
    host: localhost
    port: 445
    username: foo
    password: pass
    from: "{{ inputs.file }}"
    to: "/my_share/dir2/file.txt"
```

port should be:
`port: "445"`

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):
