### ISSUE TITLE
Executions not working 

### ISSUE THREAD

**Issue by Nannymeta** [kestra-io/kestra#570]
### Expected Behavior

Executions works

### Actual Behaviour

When i clic on Execution i get this error: 
Internal server error: Failed to inject value for field [storageInterface] of class: io.kestra.core.runners.RunnerUtils Message: No bean of type [io.kestra.core.storages.StorageInterface] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor). Path Taken: new $ExecutionController$Definition$Intercepted(BeanResolutionContext $beanResolutionContext,BeanContext $beanContext,Qualifier $qualifier,List $interceptors) --> $ExecutionController$Definition$Intercepted.runnerUtils --> RunnerUtils.storageInterface

![image](https://user-images.githubusercontent.com/103997330/164465768-f567479f-b6d9-4d62-94fa-05149832a92d.png)

### Steps To Reproduce

1. Deployment with helm on minikube
2. log in and clic on Executions

### Environment Information

- Kestra Version: 0.4.3
- Operating System (OS / Docker / Kubernetes): minikube
- Java Version (If not docker):

I've customized the values.yaml : 
````
### Image
image:
  image: kestra/kestra
  tag: latest-full
  pullPolicy: IfNotPresent

imagePullSecrets: []


### Configurations for deployments
configuration: {}


### Secrets for deployments
secrets: {}


### configuration files
configurationPath:


### Kestra executable
executable: /app/kestra


### Deployments
deployments:
  webserver:
    enabled: false
    kind: Deployment
    replicaCount: 1
    command: "server webserver"
    resources: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}
    strategy: {}
    podSecurityContext: {}
    securityContext: {}
    terminationGracePeriodSeconds: 30
    autoscaler:
      enabled: false
      minReplicas: 1
      maxReplicas: 3
      extra: {}
      metrics: []
      #  - type: Resource
      #    resource:
      #      name: cpu
      #      target:
      #        type: Utilization
      #        averageUtilization: 50
      #  - type: Resource
      #    resource:
      #      name: memory
      #      target:
      #        type: AverageValue
      #        averageValue: 100Mi

  executor:
    enabled: false
    kind: Deployment
    command: "server executor"

  indexer:
    enabled: false
    kind: Deployment
    command: "server indexer"

  scheduler:
    enabled: false
    kind: Deployment
    command: "server scheduler"

  worker:
    enabled: false
    kind: Deployment
    command: "server worker --thread=128"
    terminationGracePeriodSeconds: 60

  standalone:
    enabled: true
    kind: Deployment
    command: "server standalone"
    terminationGracePeriodSeconds: 60


# for io.kestra.core.tasks.scripts.Bash task, attach a docker dind container in order to isolate in a container
# every command launch
dind:
  enabled: true
  image:
    image: docker
    tag: dind
    pullPolicy: IfNotPresent
  socketPath: /dind/
  tmpPath: /tmp/
  resources: {}
  args:
    - --log-level=fatal
  securityContext: {}


### Kafka
kafka:
  enabled: true 

### ElasticSearch
elasticsearch:
  enabled: true
  clusterName: "es-kestra"

  esConfig:
    elasticsearch.yml: |
      xpack:
        security:
          enabled: false

  antiAffinity: "soft"

  roles:
    ml: "false"


### Minio
minio:
  enabled: true
  rootUser: root
  rootPassword: 3vqQqHSdUp4lAqLCaXkJ
  mode: standalone
  persistence:
    size: 8Gi
  resources:
    requests:
      memory: 512Mi
  buckets:
    - name: kestra
      policy: none
      purge: false

### Services
service:
  type: ClusterIP
  port: 8080
  annotations: {}


### Ingress
ingress:
  enabled: false
  className: ""
  annotations: {}
  kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local


### Global Deployement
nameOverride: ""
serviceAccountName: ""


### Annotations for deployments
annotations: {}
podAnnotations: {}
initContainers: []

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  #limits:
    #cpu: 100m
    #memory: 128Mi
  #requests:
    #cpu: 100m
    #memory: 128Mi

terminationGracePeriodSeconds: 30

nodeSelector: {}

tolerations: []

affinity: {}

extraVolumeMounts: []

extraVolumes: []

extraEnv: []

podSecurityContext: {}
# fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
# runAsUser: 1000


### Readiness / Liveness probe config.
### ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/
readinessProbe:
  enabled: true
  path: /health
  port: management
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3
  httpGetExtra: {}

livenessProbe:
  enabled: true
  path: /health
  port: management
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3
  httpGetExtra: {}

micronaut:
  server:
    port: 8086
  ssl:
    enabled: true
    keyStore:
      path: classpath:server.p12
      password: mypassword
      type: PKCS12
  logger:
  levels:
    io.kestra.runner: TRACE
    org.elasticsearch.client: TRACE
    org.elasticsearch.client.sniffer: TRACE
    org.apache.kafka: DEBUG
    io.netty.handler.logging: TRACE
````

### Example flow

Can't execute a flow.
