### ISSUE TITLE
Jumping to Definitions in a plugin documentation will lead to page reload risking unsaved work

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5702]
### Describe the issue

We should ensure that navigating to any definition doesn't cause a page reload. Otherwise, there's rsk of unsaved work for the user or they would need to save unnecessarily often. 

Demo: https://share.descript.com/view/A33LTwKq1C6

To reproduce, navigate to the definition linked on the `storeManifest` property in the dbt plugin:

```yaml
id: dbt_build
namespace: company.datateam.dbt

tasks:
  - id: dbt
    type: io.kestra.plugin.dbt.cli.DbtCLI
    namespaceFiles:
      enabled: true
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
    containerImage: ghcr.io/kestra-io/dbt-duckdb:latest
    commands:
      - dbt build --project-dir dbt
```

### Environment

- Kestra Version: develop
