### ISSUE TITLE
Allow flow label values to be of data types different than strings (int, boolean, float)

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5707]
### Feature description

Currently, trying to define booleans or integers as label values will not allow to save such a flow:

```yaml
labels:
  mynr: 42
  system.readOnly: true
```

You would need to wrap it in quotes:

```yaml
labels:
  mynr: "42"
  system.readOnly: "true"
```

This flow should ideally work:
```yaml
id: read_only
namespace: company.team

labels:
  mynr: 42
  system.readOnly: true

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 
```

We want that everything that can be serialized as a string is allowed: int, float, str, bool.

Complex objects like lists or maps will still not be allowed as label values.
