### ISSUE TITLE
Change system labels pattern to use dot instead of underscore as a separator to match existing naming conventions

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5708]
### Feature description

We realized that the current pattern using underscore as a system flow separator: `system_readOnly` or `system_correlationId` can be confusing to some users given that we mix `camelCase` with `snake_case` notation.

Let's change system labels to use dot:

```yaml
id: read_only
namespace: company.team

labels:
  mynr: 42
  system.readOnly: true
  system.correlationId: i174t8

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello {{ labels.system }}
```

Once we use the dot notation, some users will likely expect that this pattern `{{ labels.system }}` can be used to retrieve all system labels, so we should enable that pebble if feasible.

**Comment by loicmathieu** [comment]
@anna-geller we also had that for hidden labels:
```yaml
  hidden-labels:
    prefixes:
      - system.
      - internal.
```

Should I changed bot to use a dot?
