### ISSUE TITLE
Inputs don't behave as expected -- form errors and boolean not passed correctly in conditional inputs

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5731]
## Form errors when no defaults are set

Examples:

```yaml
id: myflow123
namespace: company.team
inputs:
  - id: input1
    type: STRING

  - id: input2
    type: STRING

  - id: input3
    type: STRING

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello {{inputs}}
```

![image](https://github.com/user-attachments/assets/b6312c9d-68e2-4575-8e38-8218d3f05d17)

## Boolean inputs set to true 

https://share.descript.com/view/hA5709B740U

```yaml
id: helloWorld
namespace: demo
description: |
  This flow logs a message to the console, and used for demoing and testing purposes.

inputs:
  - id: execute_fetch
    type: BOOLEAN
    required: true
    defaults: false
    description: |
      If True, this process will execute a Fetch. Otherwise the Fetch will not be executed.

  - id: container_paths
    type: STRING
    required: true
    defaults: "null"
    description: |
      The Container Paths that user wants to have specifically fetched. In the format of
      `accounts/<account-id>/containers/{container-id}`, comma separated list with no
      spaces.
    dependsOn:
      inputs:
        - execute_fetch
      condition: "{{ inputs.execute_fetch }}"

  - id: execute_dbt
    type: BOOLEAN
    required: true
    defaults: false
    description: |
      If true, execute dbt, otherwise skip dbt.

  - id: dbt_select_pattern
    type: STRING
    required: true
    defaults: "+marts.core.gtm.*+"
    description: The dbt select pattern(s) to run dbt build on.
    dependsOn:
      inputs:
        - execute_dbt
      condition: "{{ inputs.execute_dbt }}"

  - id: dbt_full_refresh
    type: BOOLEAN
    required: true
    defaults: false
    description: If true, run dbt build with full refresh.
    dependsOn:
      inputs:
        - execute_dbt
      condition: "{{ inputs.execute_dbt }}"


tasks:
  - id: log_test_party
    type: io.kestra.plugin.core.log.Log
    message: "{{ inputs.execute_dbt }}"
```

### Environment

- Kestra Version: both 0.19.7 and develop
