### ISSUE TITLE
JSON Schema validation refuse time without timezone — "String is not a RFC3339 time" warning

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#5734]
### Describe the issue

Our JSON Schema refuse time without timezone but they are correctly accepted by our serialization framework (using the default timezone).

Using one will show the following warning: 
![image](https://github.com/user-attachments/assets/0084c04b-5dc4-47a8-8a19-6aa48f032cc6)

But the RFC in question allows 'partial time' without timezone so we should change the  JSON shema (or the editor side) to allow such time.

### Environment

- Kestra Version: 0.20.0-SNAPSHOT
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by mithindev** [comment]
Hello @loicmathieu, can i take work on this issue?

**Comment by loicmathieu** [comment]
Yes you can, but I'm not sure where the issue is so I cannot help you on this one.

**Comment by mithindev** [comment]
It's okay, @loicmathieu . Thank you for trusting me with this one.

**Comment by mithindev** [comment]
Hello @MilosPaunovic,

I’ve been working on this issue for a while, initially suspecting it was a backend problem. This led me to review several components, including serializers and validators. However, it now appears to be related to frontend validation. 

The warning doesn’t seem to originate from any backend response (specifically, it’s not in any response received from the backend validation API call). I traced the warning to the script `json.worker-CJ89eVXr.js`. Could you please help confirm if this is indeed a frontend issue and provide some guidance on resolving it?

For your reference, here’s the relevant flow:

```yaml
id: inputs
namespace: company.team
inputs:
  - id: time
    type: TIME
    displayName: "A time input"
    defaults: "14:19:00"
tasks:
  - id: log_time
    type: io.kestra.plugin.core.log.Log
    message: "The input time is: {{ inputs.time }}"
```
<hr>

![image](https://github.com/user-attachments/assets/f7b90c85-45bb-45da-9e64-f7e69ba5b93e)

**Comment by MilosPaunovic** [comment]
Hey @mithindev,

I took a quick look at this and from the first glance, I'm not really sure how it works. It should be part of schema fetched from an endpoint, but apart from that, have to details. Also not sure when I'll have some more time to dive deeper into this, but maybe @brian-mulier-p can give us some pointers in the meantime?

**Comment by mithindev** [comment]
Thank you @MilosPaunovic. I’ll wait to hear back from @brian-mulier-p

**Comment by anna-geller** [comment]
@brian-mulier-p you seem to be a blocker here 😄 maybe you can recommend next steps

**Comment by loicmathieu** [comment]
I'll take it over

**Comment by brian-mulier-p** [comment]
https://kestra-io.slack.com/archives/C05S0242T4G/p1732089109235839?thread_ts=1732075316.496799&cid=C05S0242T4G

I replied here as @mithindev reached me via slack a few week ago

**Comment by mithindev** [comment]
Hello team, I've been constantly trying to figure it out, but couldn't fix it. 😔

**Comment by anna-geller** [comment]
repro:
```yaml
id: myflow
namespace: company.team
inputs:
  - id: time
    type: TIME
    defaults: 09:00:00
tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 
```
