### ISSUE TITLE
FILE-type input lacks download and preview buttons in the new columnar design

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5741]
### Describe the issue

After the switch to the columnar design, it looks like the file handling was forgotten: the download + preview buttons are missing:

![image](https://github.com/user-attachments/assets/c1f2ad9e-4054-47ed-bfda-532dba755940)

It should have the preview + download buttons as here:

![image](https://github.com/user-attachments/assets/abdf7712-6c2e-4963-8d81-426c16eb9542)

To reproduce, use any flow with FILE type input:

```yaml
id: repro
namespace: demo
inputs:
  - id: file
    type: FILE

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello 
```

### Environment

- Kestra Version: develop

**Comment by 5AIPAVAN** [comment]
i want to try this , can you please assign this to me :-)

**Comment by 5AIPAVAN** [comment]
@MilosPaunovic i unassigned my self ( i am unable to it -> some problem to run locally )
will try any other issue when locally setup is working fine
Thank you :-)

**Comment by ManojTauro** [comment]
Hi @MilosPaunovic I want to work on this issue. Could you please assign this to me?

**Comment by ManojTauro** [comment]
Hi @anna-geller I am able to display a table with download + preview button when the input is a file.

I was wondering what is the expectation when there are different types of inputs in a flow?

For example, please consider the below input:

```
inputs:
  - id: columns_to_keep
    type: ARRAY
    itemType: STRING
    defaults: 
      - brand
      - price
  - id: file
    type: FILE
```
