### ISSUE TITLE
Show raw data in clear text in the Output Preview if ION data is not in a tabular format (unstructured data)

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#5743]
When you have different columns on multiple rows inside the dataset, we are guessing them based only on the first rows, leading to not displaying any data for rows that don't match the first one

![image](https://github.com/user-attachments/assets/9e9e58e8-988c-48d3-9474-f5163010461f)

Example data: 
```
{index:{_index:"my-index"}}
{order_id:"1",customer_name:"Kelly Olsen",customer_email:"jenniferschneider@example.com",product_id:"20",price:"166.89",quantity:"1",total:"166.89"}
{index:{_index:"my-index"}}
{order_id:"2",customer_name:"Miguel Moore",customer_email:"mccarthylee@example.net",product_id:"14",price:"171.63",quantity:"8",total:"1373.04"}
```

Example flow: 
```yaml
id: es
namespace: demo
tasks:
  - id: get_csv
    type: io.kestra.plugin.core.http.Download
    uri: https://huggingface.co/datasets/kestra/datasets/raw/main/csv/orders.csv
  - id: to_ion
    type: io.kestra.plugin.serdes.csv.CsvToIon
    from: "{{outputs.get_csv.uri}}"
  - id: add_index
    type: io.kestra.plugin.scripts.jython.FileTransform
    from: "{{outputs.to_ion.uri}}"
    script: |
      rows = [
        {"index": {"_index": "my-index"}},
        row
      ]
```

## Solution

We should detect if ION data is not structured. If data doesn't fit a tabular format with the same columns in each row within the ION file, we should show raw data in clear text, in the same way as we do that for CSV files.
