### ISSUE TITLE
UI Execution Overview doesn't correctly handle errors caused by wrong output types

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5744]
### Describe the issue

Demo: https://share.descript.com/view/VtM2aaZFpNU

![image](https://github.com/user-attachments/assets/02947863-92f5-4af9-bd60-d1ffe443874d)

Reproducer:

```yaml
id: invalid_output
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.core.debug.Return
    format: this is a string, not a number

outputs:
  - id: invalid
    type: INT
    value: "{{ outputs.hello.value }}"
```

### Environment

- Kestra Version: develop
