### ISSUE TITLE
Add support for reading from a file as the value for the "values" property  of forEach

### ISSUE THREAD

**Issue by andrewlauau** [kestra-io/kestra#5766]
### Feature description

I've read the official documentation of  io.kestra.plugin.core.flow.ForEach, and I don't find a clue that I can read from a file(specifically a multi-line .txt file) as the value for the "values" property.

For example, the flow definition is like, 
```yaml
tasks:
  - id: for_each
    type: io.kestra.plugin.core.flow.ForEach
    values: "/path/to/the/file" # read from a file
    tasks:
      - id: return
        type: io.kestra.plugin.core.debug.Return
        format: "{{ task.id }} with value {{ taskrun.value }}"
```

and the content of /path/to/the/file is like,
```text
Apple
Banana
Pineapple
```

Not sure if there's a workaround. 

Thanks!
