### ISSUE TITLE
Include all upstream executions in the `{{ trigger }}` object for a multi-condition flow trigger

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5789]
### Feature description

Upstream flows:

```yaml
id: myflow1
namespace: company.team
tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello from {{ flow.id }}
```

```yaml
id: myflow2
namespace: company.team
tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello from {{ flow.id }}
```

Downstream flow that required both of the above to run successfully:

```yaml
id: myflow3
namespace: company.team

triggers:
  - id: wait_for_upstream
    type: io.kestra.plugin.core.trigger.Flow
    conditions:
      - id: poll_for_flows
        type: io.kestra.plugin.core.condition.FlowFilters
        upstreamFlows:
          - namespace: company.team
            flowId: myflow1
            states: [SUCCESS, WARNING]
          - namespace: company.team
            flowId: myflow2
            states: [SUCCESS, WARNING]

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: I'm triggered by two flows! Trigger data {{ trigger }}
```

Now run `myflow1` and then `myflow2`. This will trigger an execution of `myflow3` but the trigger object will only include the execution of `myflow2` because that’s the last execution that satisfied conditions for `myflow3`:

```json
{"executionId":"Rd9IOzt1nKX2hmhgXQe29","state":"SUCCESS","namespace":"company.team","flowId":"myflow2","flowRevision":1}
```

@loicmathieu Is it technically feasible to capture both executions in the trigger object as an array?

```json
[{"executionId":"Rd9IOzt1nKX2hmhgXQe29","state":"SUCCESS","namespace":"company.team","flowId":"myflow2","flowRevision":1},
{"executionId":"xyz123456789jhcrugggge","state":"SUCCESS","namespace":"company.team","flowId":"myflow1","flowRevision":1}]
```
