### ISSUE TITLE
Expression in onResume not working for pause flow

### ISSUE THREAD

**Issue by stumpf84** [kestra-io/kestra#5805]
### Describe the issue

Using an expression for a SELECT input in onResume in a Pause flow does not show items.

Here is a sample 

```
id: inputIssue
namespace: test

inputs:

  - id: hosts
    type: ARRAY
    itemType: STRING
    required: true
    defaults: [ "host1", "host2", "host3" ]

tasks:

  - id: dbg
    type: io.kestra.plugin.core.log.Log
    message: "{{ inputs.hosts }}"

  - id: select_host
    type: io.kestra.plugin.core.flow.Pause
    onResume:
      - id: selected_host
        type: SELECT
        expression: "{{ inputs.hosts }}"
        required: true

```
### Expected
Resuming shows SELECT input containing host1-3

### Actual
Resuming shows SELECT input  'No data'

### Environment

- Kestra Version: 0.19.9

**Comment by Ben8t** [comment]
hello @stumpf84 

This is seems to work on my side (on kestra:develop, might double check on 0.19.9). Can you share a screenshot of this "no data" please ?

<img width="1120" alt="Screenshot 2024-11-08 at 10 31 55" src="https://github.com/user-attachments/assets/5ed92beb-44f2-4a7c-8505-1b8a77cd3228">

**Comment by stumpf84** [comment]
Hello @Ben8t,
here is the screenshot. 

![image](https://github.com/user-attachments/assets/c14ab320-0165-4058-bb1e-c36dde03883b)

Running as docker-compose.

**Comment by Ben8t** [comment]
Indeed, I'm able to reproduce on `0.19.9` , however seems to be fixed on `develop` already. If you have the opportunity you can pull this version or wait for next release.

**Comment by stumpf84** [comment]
Hello @Ben8t,
the problem still exists in 0.19.11

**Comment by anna-geller** [comment]
I can reproduce the issue on develop https://share.descript.com/view/AaSBIBPFZat

**Comment by anna-geller** [comment]
hey @stumpf84, thanks again for the issue, this is not fixed on develop. Keep in mind that the only dynamic expression valid to render SELECT dropdown values from is KV Store, so you may need to adjust some of your flows to match that pattern e.g. using dedicated tasks adding or updating KV pairs for a given namespace

here is an example that works now (thx Bart for fixing it in https://github.com/kestra-io/kestra/pull/6188):

```yaml
id: inputIssue
namespace: test

inputs:
  - id: hosts
    type: SELECT
    expression: "{{ kv('hosts') }}"
    
tasks:
  - id: first
    type: io.kestra.plugin.core.log.Log
    message: "{{ inputs.hosts }}"

  - id: pause
    type: io.kestra.plugin.core.flow.Pause
    onResume:
      - id: selected_host
        type: SELECT
        expression: "{{ kv('hosts') }}"

  - id: last
    type: io.kestra.plugin.core.log.Log
    message: "{{ outputs.pause.onResume.selected_host }}"
```
