### ISSUE TITLE
If statement condition evaluation fail

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#5812]
### Describe the issue

Example flow:
```yaml
id: for_loop_example
namespace: company.team

tasks:
  - id: for_each
    type: io.kestra.plugin.core.flow.ForEach
    values: ["value 1", "value 2", "value 3"]
    tasks:
      - id: before_if
        type: io.kestra.plugin.core.debug.Return
        format: "Before if: {{ taskrun.value }}"
      - id: if
        type: io.kestra.plugin.core.flow.If
        condition: "{{ taskrun.value equals 'value 2' }}"
        then:
          - id: after_if
            type: io.kestra.plugin.core.debug.Return
            format: "After if: {{ parent.taskrun.value }}"
```
This works on `latest` 19.8. But on `develop`, it throws the following error when it gets to the `if` task.

```
Unable to resolve state from the Flowable task: Unable to find the 'evaluationResult' output, this may indicate that the condition evaluation fail, check your execution logs for more information.
```

 I tried replacing the condition with just true to remove any issues with the taskrun expression but the same error. I was able to get an if statement working without ForEach. Example used below:

<details>
<summary>Example that worked with an if statement</summary>

```yaml
id: if
namespace: company.team

inputs:
  - id: string
    type: STRING
    required: true

tasks:
  - id: if
    type: io.kestra.plugin.core.flow.If
    condition: "{{ inputs.string == 'Condition' }}"
    then:
      - id: when_true
        type: io.kestra.plugin.core.log.Log
        message: "Condition was true"
    else:
      - id: when_false
        type: io.kestra.plugin.core.log.Log
        message: "Condition was false"
```

</details>

### Environment

- Kestra Version: develop
- Commit Hash: 4259466
- Edition: OSS

**Comment by wrussell1999** [comment]
Reports on Slack of this happening on 19.9 with the same error message:

```yaml
    - id: if_stripe_cus_found
      type: io.kestra.plugin.core.flow.If
      condition: "{{ outputs.stripe_search_customer_latest.vars.id is defined }}"

      then:
        - id: add-label-stripe-cus-id
          type: io.kestra.plugin.core.execution.Labels
```

It is defined and works as expected: 
![image](https://github.com/user-attachments/assets/316c4a28-2db7-4680-af78-27ad009ff64c)
