### ISSUE TITLE
Provide a `fileURI()` Pebble function to get the URI of a namespace file or internal storage file

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#5817]
### Feature description

You can read a namespace file via a Pebble function, but if you want to use a namespace file in a task that support Kestra's internal storage URI but didn't allow using directly namespace files, you can't easily do this.

Some clever user may find that a namespace file has a stable URI, for ex: `kestra://~/company/team/_files/fileA.ion` and use it. But it's not guaranteed to work in the future and shows implementation detail.

So we need a Pebble function to get the URI of a namespace file from its name, let's call it `nsFile()` but maybe a better name can be found (getFile or fileURI for ex).

Example usage:

```yaml
id: myflow
namespace: company.team


tasks:
    - id: test
      type: io.kestra.plugin.joinExpr.Join
      expr: "{{ a.id | split('-') contains b.name }}"
      fileA: "{{ fileURI(fileA.ion) }}"
      fileB: "{{ fileURI(fileB.ion) }}"
      getJoined: true
      getRejectA: true
      getRejectB: true
```
