### ISSUE TITLE
Find a way to extend the width of text displayed in the Monaco Editor autocompletion

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5823]
### Feature description

Some long plugin names are truncated, making it difficult to read. To reproduce, try to autocomplete the following:

```yaml
id: myflow
namespace: company.team
tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 

triggers:
  - id: flow
    type: io.kestra.plugin.core.trigger.Flow
    conditions:
      - id: flow
        type: ... # try autocomplete here
```
![image](https://github.com/user-attachments/assets/5f9eb9d2-a6ff-46bf-86c2-8d8efa43e49c)

This is a difficult issue as the width is hardcoded in Monaco editor code, so changing this would require us to manage a custom build:

![image](https://github.com/user-attachments/assets/b9e6b92b-80e1-47a6-90f2-1ecc67dab364)

**Note: this is not a good task for an external contributor.**
