### ISSUE TITLE
Cannot execute a flow named `pause`

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#5832]
### Describe the issue

You cannot execute a flow named `pause`.

Try for example to create the following flow and execute it:

``` yaml
id: pause
namespace: company.team
tasks:
  - id: pause
    type: io.kestra.plugin.core.flow.Pause
    delay: PT30S
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀
```

This is because Micronaut redirect to the pause endpoint of the ExecutionController instead of the create endpoint:

```java
    @Post(uri = "/{namespace}/{id}", consumes = MediaType.MULTIPART_FORM_DATA)
    public Publisher<ExecutionResponse> create()
    }

    @Post(uri = "/{executionId}/pause")
    public void pause()
    }
```

The same issue occurs for all endpoints taken an executionId and using a POST method: pause, resume, kill, unqueue, ...

To fix that we can either:
- use a regex (to be validated): `{executionId:[^/]*}`
- rename those endpoints to use something that cannot be used as a flow identifier, like `_pause` so there are no possible mismatches.

### Environment

- Kestra Version: develop
