### ISSUE TITLE
Add labels map to the new Executions condition

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5836]
```yaml
  - id: flow3
    type: io.kestra.plugin.core.trigger.Flow
    conditions:
      - id: flow_filters
        type: io.kestra.plugin.core.condition.ExecutionsCondition
        timeSLA:
          type: DURATION_WINDOW
          window: PT1D
        preconditions:
          - namespace: company.team
            flowId: myflow1
            states: [SUCCESS, WARNING]
            labels: 
              mykey: mylabelvalue
          - namespace: company.team
            flowId: myflow2
            states: [SUCCESS]
```
