### ISSUE TITLE
Explore whether we should move the new Flow trigger conditions to `preconditions` as currently they behave differently than the regular conditions (they require `id`) 

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5837]
### Feature description

Only those three conditions are currently possible for Flow trigger, this might be a bug

![image](https://github.com/user-attachments/assets/5c89a743-7e9b-4b40-a16a-486bb341b35b)

if you remove the ID, all conditions appear:
![image](https://github.com/user-attachments/assets/12be9324-f3ac-4b28-8cdd-2e1c02829319)

**Comment by Ben8t** [comment]
What would be the differences between `precondition` and `condition` then 🤔 Isn't just a matter of fixing this `id` behavior ?

Is that `condition` will be evaluate when execution is actually triggered upstream, working like a if/else condition ? While precondition is the actual trigger definition ?

**Comment by anna-geller** [comment]
don't worry about the naming - can be `executionsCondition`, it's a matter of finding a technical solution to ensure that conditions related to flow trigger show up there + find a way to have the ExecutionsWindow or FilteredExecutionsWindow as a map (single condition) instead as a list (multiple conditions)

we keep iterating on this https://github.com/kestra-io/kestra/issues/5856

next meeting to discuss it is on Tuesday 
![image](https://github.com/user-attachments/assets/d8524444-9282-4c36-95dd-248d50e3c855)

**Comment by anna-geller** [comment]
will be solved by preconditions with this syntax:

```yaml
id: myflow123
namespace: company.team
triggers:
  - id: wait_for_upstream
    type: io.kestra.plugin.core.trigger.Flow
    conditions:
      - type: io.kestra.plugin.core.condition.HasRetryAttemptCondition
    preconditions:
      timeWindow:
        type: DURATION_WINDOW
        window: PT1D
      flows: # AND by default for all list elements
        - namespace: company.team
          flowId: myflow1
          states: [SUCCESS, WARNING]
        - namespace: company.team
          flowId: myflow2
          states: [SUCCESS]
          labels:
            mykey: myvalue
            another: labelvalue
          inputs: # TODO
            myuser: Loic
# executionFilters, query filters
      where:
        - id: custom_filters # operand: AND # default, needs to be specified only if OR
          filters:
            - field: NAMESPACE
              type: STARTS_WITH
              value: company
            - field: FLOW_ID
              type: IN
              values: 
                - flow1
                - flow2
            - field: STATE
              type: IN
              values: [SUCCESS, WARNING, CANCELLED]
tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: I'm triggered after two flows!
```
