### ISSUE TITLE
Deprecation icon might be failing to be rendered

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5840]
### Describe the issue

Not sure exactly what the icon here should look like but this icon looks like a small bug:

![image](https://github.com/user-attachments/assets/495b85e2-ac41-4651-a65c-4f7e11394a31)

To reproduce, add a flow with outdated plugin syntax:

```yaml
id: myflow
namespace: company.team
tasks:
  - id: hello
    type: io.kestra.core.tasks.flows.ForEachItem
```

### Environment

- Kestra Version: develop
