### ISSUE TITLE
[Regression] Outputs tab now displays incorrect Pebble expressions and Pebble is rendered in the wrong place

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5842]
### Describe the issue

![image](https://github.com/user-attachments/assets/106e8bd5-cd55-4077-9a8f-710f237d4524)

Demo: https://share.descript.com/view/O9XWH3nGBHZ

To reproduce, run this flow and navigate to Outputs:

```yaml
id: hello-world
namespace: repro

inputs:
  - id: user
    type: STRING
    defaults: Rick Astley
tasks:
  - id: first_task
    type: io.kestra.plugin.core.debug.Return
    format: thrilled
  - id: second_task
    type: io.kestra.plugin.scripts.shell.Commands
    commands:
      - sleep 0.42
      - echo '::{"outputs":{"returned_data":"mydata"}}::'
  - id: hello_world
    type: io.kestra.plugin.core.log.Log
    message: |
      Welcome to Kestra, {{ inputs.user }}! 
      We are {{ outputs.first_task.value}} to have You here!
```

### Environment

- Kestra Version: develop
