### ISSUE TITLE
Change the Debug Outputs section to be resizable 

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5843]
### Feature description

Some expressions or outputs are large. It would be great to make this Debug Outputs section as a resizable component:

![image](https://github.com/user-attachments/assets/837cfd15-f035-4a0d-b0e6-11db200e0dca)

### Extra info for first-time contributors

You can reproduce it by adding this flow, running it and navigating to Outputs:

```yaml
id: hello-world
namespace: dev
description: Hello World
inputs:
  - id: user
    type: STRING
    defaults: Rick Astley
tasks:
  - id: first_task
    type: io.kestra.plugin.core.debug.Return
    format: thrilled
  - id: second_task
    type: io.kestra.plugin.scripts.shell.Commands
    commands:
      - sleep 0.42
      - echo '::{"outputs":{"returned_data":"mydata"}}::'
  - id: hello_world
    type: io.kestra.plugin.core.log.Log
    message: |
      Welcome to Kestra, {{ inputs.user }}! 
      We are {{ outputs.first_task.value}} to have You here!
```
