### ISSUE TITLE
Support Encrypting Task Outputs with Special Syntax

### ISSUE THREAD

**Issue by GideonStowell** [kestra-io/kestra#5849]
### Feature description

I would like to be able to encrypt task outputs when using the special syntax like this:
```
::{"outputs":{"test":"value"}}::
```
If the value of the output `test` is sensitive I have no way of protecting it. 

There is a way to encrypt flow outputs as described in the docs in [this section](https://kestra.io/docs/configuration#encryption) but not task level outputs.

I have the following example flow and I need to encrypt the outputs from the onepass task to be used in subsequent tasks. 

```
tasks:
  - id: "onepass"
    type: io.kestra.plugin.scripts.ruby.Commands
    taskRunner:
      type: io.kestra.plugin.core.runner.Process
    logLevel: ERROR
    inputFiles:
      env.yml: |
        GITHUB_USER: 'op://kestra-github/username'
        GITHUB_TOKEN: 'op://kestra-github/credential'
        GCP_TOKEN: 'op://provisioner/gcp_token'
        ANOTHER_TOKEN: 'op://key_json'
      outputs.rb: |
          require 'yaml'
          require 'json'
          inputs = YAML.load(STDIN)
            outputs = inputs.transform_values do |value|
            { "type" => "io.kestra.datatype:aes_encrypted", "value" => value }
          end
          json = JSON.dump( { outputs: outputs } ) 
          STDOUT.puts "::#{json}::"
    commands:
      - cat env.yml | op inject | ruby outputs.rb 
    ### The outputs from this shows up under the execution output tab unecrypted. See screenshot
    
outputs:
  - id: return
    type: SECRET
    value: "mysecretvalue" 
    ### This shows up properly encrypted in the execution overview tab
```

![Screenshot of variables](https://github.com/user-attachments/assets/226e4e01-5d18-49d5-9634-bad07b4db07c)

**Comment by danlsgiga** [comment]
Would love to see this feature being added, which will support a multitude of use cases on our side. 🙏🏻

**Comment by danlsgiga** [comment]
Interesting enough, I just found out that https://kestra.io/plugins/plugin-aws/ecr/io.kestra.plugin.aws.ecr.getauthtoken already does that. Would be awesome to get this across the board!

**Comment by anna-geller** [comment]
@fhussonnois I'll ping you via huddle to discuss more

**Comment by anna-geller** [comment]
Since this would compete with the Secrets feature in the Enterprise Edition, we added it in EE https://github.com/kestra-io/kestra-ee/issues/3441

**Comment by danlsgiga** [comment]
Thanks for working on this feature!

I'd argue this should not be behind EE.

1. The EE Secrets feature exists for secret consumption and storage. This feature fits mostly on the category of sensitive information being generated by a task and needing to be hidden on log outputs to potentially be passed on to further tasks or flows.
2. [Flow outputs](https://kestra.io/docs/workflow-components/outputs#flow-outputs) already supports encryption in the Open Source edition for the same kind of use cases
3. https://kestra.io/plugins/plugin-aws/ecr/io.kestra.plugin.aws.ecr.getauthtoken also automatically encrypts its outputs and is available in the Open Source edition.

I know this is a business decision but can this decision be potentially revisited? 🙏🏻

**Comment by anna-geller** [comment]
I'm sorry @danlsgiga, this is out of my control. 

Below is the info from the private PR - sharing for transparency on how the feature works.

I can understand if you don't feel ready for EE -- we started the Early Adopter Program for Kestra Cloud - not open to everyone just yet, but as a consolation, we'd be happy to include you in the program with a special early adopter price & benefits: https://kestra.io/cloud

---


**Implementation**
```
::{"encryptedOutputs":{"test":"value"}}::
```

**Testing**

Using the following flow:

```
id: gh_3441
namespace: io.kestra

tasks:
  - id: hello
    type: io.kestra.plugin.scripts.shell.Script
    script: |
      echo '::{"outputs":{"plaintext":"plaintext_value"}}::'
      echo '::{"encryptedOutputs":{"encrypted":"my secret value"}}::'

  - id: print
    type: io.kestra.plugin.core.log.Log
    message: "{{ outputs.hello['vars']['encrypted'] }}"
```

* `encrypted` output should not be accessible in plaintext via the UI Outputs tab
