### ISSUE TITLE
UI - Executions In Progress does not update duration for running execution it appears

### ISSUE THREAD

**Issue by japerry911** [kestra-io/kestra#5867]
### Describe the issue

<img width="581" alt="Screenshot 2024-11-09 at 11 24 43 AM" src="https://github.com/user-attachments/assets/1649f45f-6ae7-4a67-b8d6-b185c1ddb1b2">

Current view ^

<img width="517" alt="Screenshot 2024-11-09 at 11 24 56 AM" src="https://github.com/user-attachments/assets/3bef8566-0e7d-4de5-bcee-9bbb4f53152a">

Duration in execution ^

### Environment

- Kestra Version: v0.19.8
- Kestra Cloud

**Comment by prajyot004** [comment]
Hi @japerry911 can you give that task to me if you are comfortable to share it.

**Comment by prajyot004** [comment]
I would like to work on this.

**Comment by MilosPaunovic** [comment]
Hi, @prajyot004, you can take the issue, but I'm not really sure on how we should approach it, as the current endpoint which is showing the list of executions in progress is static.

Maybe @Ben8t could give us a bit of ideas on how we want to approach this from the product standpoint first?

**Comment by Ben8t** [comment]
@japerry911 can you give us more details on where you're looking at for the two different views you mentioned please?

I'm looking to reproduce on my side but have a doubt - especially on the first view you share

**Comment by japerry911** [comment]
Sure! is this helpful - https://www.loom.com/share/cb7b2156472543db88dfcf84eced27ea?sid=43c78669-b04b-416c-b87c-858e1495847c

**Comment by japerry911** [comment]
@Ben8t meant to tag you sorry ^

**Comment by Ben8t** [comment]
Thanks a lot @japerry911 ! Indeed, when coming back or refresh the dashboard page the execution duration should be updated.

Here is a basic flow reproducer:
```
id: sleep
namespace: kestra.test

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀

  - id: sleep
    type: io.kestra.plugin.scripts.shell.Commands
    commands:
      - sleep 30
```

@MilosPaunovic do you think it's technically feasible (thinking about your comment _"as the current endpoint which is showing the list of executions in progress is static.")_

**Comment by prajyot004** [comment]
I have almost fixed it.

**Comment by Ben8t** [comment]
@prajyot004 thanks ! Can you link your PR please?

**Comment by prajyot004** [comment]
I did one changes in executions page but found another issue. State is aslo not changing from running to Success.

https://github.com/user-attachments/assets/f8404642-0b8e-4db0-8ac3-6f246c9acf35

I did this but not able to figure out how the state will update for that row only. Can anyone please help me to understand it better ?
@MilosPaunovic @Ben8t

**Comment by MilosPaunovic** [comment]
We can either change the backend endpoint to have those kinds of information `live` or we can trigger refresh periodically. Neither solution is ideal, but I think any approach needs an internal discussion first @Ben8t.

**Comment by prajyot004** [comment]
Hi @MilosPaunovic should i do refresh periodically or is there anything other solution you know to be implemented ?

**Comment by MilosPaunovic** [comment]
@prajyot004  Let's leave this one open for now, and, if you're up for contributing, may I suggest that you check our [curated list of good first issues](https://go.kestra.io/contributing) to see if there is something you find interesting enough and think you can tackle independently. It can be further filtered by desired labels to narrow down the results (suggesting to filter by either `area/backend` or `area/frontend` ones, based on your preferences).

**Comment by Ben8t** [comment]
It's a bug, the auto-refresh button or "classic" refresh button doesn't update the duration nor the state on the Execution In Progress list (it doesn't refresh at all)

**Comment by MilosPaunovic** [comment]
Tested this with a paused flow. 

```yaml
id: human_in_the_loop
namespace: github.milos

tasks:
  - id: before_approval
    type: io.kestra.plugin.core.debug.Return
    format: Output data that needs to be validated by a human

  - id: pause
    type: io.kestra.plugin.core.flow.Pause

  - id: run_post_approval
    type: io.kestra.plugin.scripts.shell.Commands
    runner: PROCESS
    commands:
      - echo "Manual approval received! Continuing the execution..."

  - id: post_resume
    type: io.kestra.plugin.core.debug.Return
    format: "{{ task.id }} started on {{ taskrun.startDate }} after the Pause"
```

On every refresh, data in the `Executions In Progress` table is fetched with `executions/search` endpoint, with these parameters:

```js
size: 5
page: 1
state: RUNNING
state: PAUSED
state: RESTARTED
state: KILLING
state: QUEUED
state: RETRYING
```

And the resulting set always returns the same duration, so I'd think this is backend related.
