### ISSUE TITLE
Labels in execution page are not shown

### ISSUE THREAD

**Issue by smunteankestra** [kestra-io/kestra#5879]
### Describe the issue

Having this Flow::

```
id: autotest_14163083-2e98-4660-8f7a-58f9fe6433fd
namespace: autotest_14163083-2e98-4660-8f7a-58f9fe6433fd

labels:
  song: never_gonna_give_you_up
  artist: rick_astley

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: "Hello, {{ missing_variable }}!"
```

no labels are returned in execution page

![image](https://github.com/user-attachments/assets/4fff6987-c4eb-4b2a-bd2c-d6022f996b1b)

### Environment

- Kestra Version: develop
