### ISSUE TITLE
Autorefresh button disabled 

### ISSUE THREAD

**Issue by smunteankestra** [kestra-io/kestra#5881]
### Describe the issue

sample flow just in case:
```

id: autotest_0902d119-55b3-4939-a7bd-7ff0b12324be
namespace: autotest_0902d119-55b3-4939-a7bd-7ff0b12324be

tasks:
  - id: external_system_export
    type: io.kestra.plugin.scripts.shell.Commands
    taskRunner:
      type: io.kestra.plugin.core.runner.Process
    commands:
      - echo "processing data for {{ execution.startDate ?? trigger.date }}"
      - sleep $((RANDOM % 5 + 1))

triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "*/30 * * * *"

```

![image](https://github.com/user-attachments/assets/cd355478-6da8-421e-a959-5631f08b2d9e)

### Environment

- Kestra Version: develop
