### ISSUE TITLE
Log lines are out of order when viewing live logs

### ISSUE THREAD

**Issue by Zibbp** [kestra-io/kestra#5915]
### Describe the issue

When viewing logs of a running flow (clicking "Execute" then "Logs") the lines are out of order, both by timestamp and expected order (see the flow below).
![image](https://github.com/user-attachments/assets/ddd004e2-224a-46f4-8844-c64b835e5cc9)

When the job is complete and I refresh the page the log lines are in the correct order, as expected.
![image](https://github.com/user-attachments/assets/ce7fe46e-6b71-4ee3-94f9-70a9a93184b1)

The flow I'm using:
```yaml
id: run_playbook_DEBUG
namespace: company.team
inputs:
  - id: playbook
    type: STRING
    required: true
    description: Playbook name
    defaults: server-kestra-demo.yml
  - id: server
    type: MULTISELECT
    expression: "{{ kv('servers_debug') }}"
    required: true
tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀
  - id: ansible
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      - id: clone_repository
        type: io.kestra.plugin.git.Clone
        url: <redacted>
        branch: master
      - id: test
        type: io.kestra.plugin.scripts.shell.Script
        taskRunner:
          type: io.kestra.plugin.scripts.runner.docker.Docker
        containerImage: <redacted>
        script: |
          echo "hi"
          touch foo.txt
          echo "running playbook: {{ inputs.playbook }}"
          echo "on: {{ inputs.server | join(", ") }}"
          echo "bye"
```

### Environment

- Kestra Version: v0.19.10 using the provided docker compose file
