### ISSUE TITLE
Outputs tab shows only `outputs.` instead of full expression like `outputs.mytask.outputName` for the first output

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5920]
### Describe the issue

The first output is expanded by default — that's expected. What's unexpected is that the expression is showing only `outputs.` instead of full outputs expression `outputs.mytask.outputName`
![image](https://github.com/user-attachments/assets/f5aa2342-f60c-489e-b8c2-94086d0ee465)

Seems like regression introduced in PR to https://github.com/kestra-io/kestra/issues/5523

Reproducer flow:

```yaml
id: get_data
namespace: company.team

inputs:
  - id: data
    displayName: Select Data to Download
    type: SELECT
    values:
      - customers
      - employees
      - products
      - stores
      - suppliers
    defaults: customers

tasks:
  - id: extract
    type: io.kestra.plugin.core.http.Download
    uri: https://huggingface.co/datasets/kestra/datasets/resolve/main/ion/{{ inputs.data }}.ion  

outputs:
  - id: data
    type: FILE
    value: "{{ outputs.extract.uri }}"
```

### Environment

- Kestra Version: develop
