### ISSUE TITLE
FILE-type Flow output cannot be expanded

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5921]
### Describe the issue

Issue: https://share.descript.com/view/6BpYzpiGApV

![image](https://github.com/user-attachments/assets/6bf3e1e0-314a-4e75-a260-d5541b5637c0)

Reproducer:
```yaml
id: get_data
namespace: company.team

inputs:
  - id: data
    displayName: Select Data to Download
    type: SELECT
    values:
      - customers
      - employees
      - products
      - stores
      - suppliers
    defaults: customers

tasks:
  - id: extract
    type: io.kestra.plugin.core.http.Download
    uri: https://huggingface.co/datasets/kestra/datasets/resolve/main/ion/{{ inputs.data }}.ion  

outputs:
  - id: data
    type: FILE
    value: "{{ outputs.extract.uri }}"
```

### Environment

- Kestra Version: develop
