### ISSUE TITLE
Add "Debug Expression" next to columnar Trigger Variables on each Execution Overview page

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5940]
## Problem

Navigating JSON data has become too complex:

![image](https://github.com/user-attachments/assets/596843cb-12af-4ac6-b037-0a4e52dd4fc9)

Viewing it as a single JSON code block is often much easier:

![image](https://github.com/user-attachments/assets/7fb51a16-4e34-43be-a0de-450fe7921bab)

## Solution

Let's add Render Expression to Triggers the same way as we do that on Outputs, allowing to view that as JSON by clicking on Render expression:

![Image](https://github.com/user-attachments/assets/712de3d7-4c86-4de6-beba-7ad4e1728df4)

https://www.figma.com/design/ew0uXk0NRXJ2NBBJTNe2n1/01_UI?node-id=1446-8508&t=qDTKKT4P60ul9cqi-4

**Comment by anna-geller** [comment]
for posterity: we discussed today with Nico that we'll add Debug Expression to Triggers to match how it's done on Outputs. This will allow both columnar design as is today + will allow to get a JSON of specific trigger variables

**Comment by anna-geller** [comment]
@Piyush-r-bhaskar this might be a fairly quick one to add a similar "Debug expression" field on triggers

to reproduce, you can use:

```yaml
id: repro
namespace: company.team

tasks:
  - id: log
    type: io.kestra.plugin.core.log.Log
    message: "{{ trigger.body }}"

triggers:
  - id: webhook
    type: io.kestra.plugin.core.trigger.Webhook
    key: test1234
```

then copy the URL to trigger an execution:

![Image](https://github.com/user-attachments/assets/5cfd7ce7-66a9-44e6-b05e-2f54d36590a7)

run:

```bash
curl -X POST http://localhost:8080/api/v1/executions/webhook/company.team/repro/test1234 \
  -H "Content-Type: application/json" \
  -d '{"key1":"value1","key2":"value2"}'
```

and you should see the trigger variables on the Execution page. The goal is to add "Debug expression" section as we have on Outputs. 

![Image](https://github.com/user-attachments/assets/745dd59e-b66e-4099-8418-3ff89064bd5c)
