### ISSUE TITLE
Killing workflow executions does not work if workflow is in Retry

### ISSUE THREAD

**Issue by johnkm516** [kestra-io/kestra#5983]
### Describe the issue

I have not tested this _without_ subflows, therefore I do not know if this issue is exclusive to a parent workflow executing child workflows that are in retry, or if this issue exists regardless. 

1) Create a parent workflow that executes a child workflow.
2) Have the child workflow cause an error with a retry, for example 5 times with an interval of 10s. 
3) While the child workflow is in retry, kill the parent execution (Kill parents and subflows, or kill the parent, either or it doesn't work).
4) The parent and child workflow executions are not killed. The retry logic overrides the kill command and keeps executing.

### Environment

- Kestra Version: 0.19.10

**Comment by Ben8t** [comment]
Hello John, I'm not able to reproduce on kestra:develop. See the following flow and screenshot

```
id: parent
namespace: kestra.test

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀

  - id: subflow
    type: io.kestra.plugin.core.flow.Subflow
    flowId: child
    namespace: kestra.test
```

```
id: child
namespace: kestra.test

tasks:
  - id: retry
    type: io.kestra.plugin.scripts.shell.Commands
    commands:
      - sleep 5
      - exit 1
    retry:
      type: constant
      interval: PT10M
      maxAttempt: 5
    taskRunner:
      type: io.kestra.plugin.core.runner.Process
```

![image](https://github.com/user-attachments/assets/c57535cb-6f79-436a-b165-3ad7427adc54)

![image](https://github.com/user-attachments/assets/5a6b053b-884c-40f5-9976-7050d9e77778)


Can you provide flows to reproduce (if mines aren't complete) and screenshot please ?

**Comment by johnkm516** [comment]
I'll post my flow as a support ticket. I tried creating a reproducer but it's working fine for me as well, I can't figure out what part of my reproducer that's causing this issue.

Edit : Posted a support ticket with my flow and a GIF showing it not working.

**Comment by anna-geller** [comment]
@johnkm516 I can't find which ticket matches this one

if you prefer to tackle it as a GitHub issue, can you please share the reproducer flow here?

**Comment by anna-geller** [comment]
Hi John, thanks for reporting this and providing example flows in your ticket. There are definitely some issues here, already that blinking in the UI makes it impossible to kill some executions https://share.descript.com/view/tolEva3F7kY

For anyone working on it, here are reproducers:

Child flow:
```yaml
id: child
namespace: company.team

inputs:
  - id: masterDataRow
    type: JSON
    required: true
    defaults: |
      {
        "order_id": 2,
        "customer_name": "Miguel Moore",
        "customer_email": "mccarthylee@example.net",
        "product_id": 14,
        "price": 171.63,
        "quantity": 8,
        "total": 1373.04
      }

tasks:
  - id: log_data
    type: io.kestra.plugin.core.log.Log
    message: Hello "{{ inputs.masterDataRow }}"

  - id: python
    type: io.kestra.plugin.scripts.python.Script
    taskRunner:
      type: io.kestra.plugin.core.runner.Process
    script: |
      from kestra import Kestra
      import random

      random_value = random.randint(0, 1)
      outputs = {
          'random_value': random_value
      }
      Kestra.outputs(outputs)


  - id: fail
    type: io.kestra.plugin.core.execution.Fail
    runIf: "{{ outputs.python.vars.random_value == 1 }}"
    errorMessage: Bad value returned!
```

Parent flow:
```yaml
id: parent
namespace: company.team

tasks:
  - id: extract
    type: io.kestra.plugin.core.http.Download
    uri: https://huggingface.co/datasets/kestra/datasets/raw/main/csv/orders.csv

  - id: query
    type: io.kestra.plugin.jdbc.duckdb.Query
    fetchType: FETCH
    inputFiles:
      data.csv: "{{ outputs.extract.uri }}"
    sql: >
      SELECT * FROM read_csv_auto('{{ workingDir }}/data.csv');
  
  - id: parallel
    type: io.kestra.plugin.core.flow.ForEach
    values: "{{outputs.query.rows}}"
    concurrencyLimit: 0
    tasks:
      - id: child
        type: io.kestra.plugin.core.flow.Subflow
        namespace: company.team
        flowId: child
        inputs:
          masterDataRow: "{{ taskrun.value }}"
        retry:
          type: constant
          behavior: CREATE_NEW_EXECUTION
          interval: PT3S
          maxAttempt: 5
          warningOnRetry: false
```
