### ISSUE TITLE
Rename the printContext() pebble function to fetchContext() or just context()

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#5993]
### Feature description

Best if we can rename it with a "softly-deprecated" alias :)

Given that this function fetches and returns data that can be used in downstream tasks, it would be better to call it "fetch" or "get" rather than "print" — "print" would be suitable if it would log sth to the console but here it returns context that can be used to fetch specific info e.g. `{{ printContext().taskrun }}`

Full example:

```yaml
id: myflow
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.core.debug.Return
    format: "{{ printContext() }}"

  - id: print
    type: io.kestra.plugin.core.log.Log
    message: 
      - "{{ json(outputs.hello.value).execution }}"
      - "{{ json(outputs.hello.value).labels }}"
      - "{{ json(outputs.hello.value).tasks }}"
```
