### ISSUE TITLE
Double autocompletion for flow-level retry type

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#6017]
### Describe the issue

![image](https://github.com/user-attachments/assets/f2e68a27-d0b1-4a3f-bc10-59133d0d6d42)

to reproduce, add a flow with retry:

```yaml
id: myflow_repro
namespace: company
retry:
  behavior: RETRY_FAILED_TASK
  type: constant # TRY AUTOCOMPLETE HERE 
  maxAttempt: 3
```

### Environment

- Kestra Version: develop
