### ISSUE TITLE
Large amount of triggers and executions lead to performance issues

### ISSUE THREAD

**Issue by LegendJerry-Goguette** [kestra-io/kestra#6024]
### Describe the issue

When a large amount of triggers/executions occur the application starts to slow down immensely.
Executions are created, but no tasks actually start even when it's in the `Running` state.
And If tasks start they take a very long time to actually execute.

If tried setting up concurrency. With that I just get a huge backlog of executions to process.

This is a screenshot showing the current situation:
<img width="1284" alt="Screenshot 2024-11-20 at 10 42 15 AM" src="https://github.com/user-attachments/assets/36ac9882-281a-4bb9-bbab-24f41096e2b2">

Examples showing execution created hours ago and it currently in the `Running` state yet no tasks are created:
<img width="1296" alt="Screenshot 2024-11-20 at 11 14 13 AM" src="https://github.com/user-attachments/assets/1fa49f9d-954f-4cdb-b98c-65338f817d03">
<img width="1300" alt="Screenshot 2024-11-20 at 11 14 25 AM" src="https://github.com/user-attachments/assets/7236a520-9178-47e9-8ab3-89ba57d678cc">

My current Setup for the triggers include:
- 3 Real time debezium mysql triggers
-- 1 constant load (200+ per minute)
-- 1 hourly bulk load (30K+ per hour)
-- 1 minimal load (50+ per hour)
- 1 Webhook
-- Constant load (Roughly 1500+ per minute)

Using `pg_stat_statements` postgresql extension with the following query:
```sql
SELECT
    query,
    calls,
    total_exec_time,
    mean_exec_time,
    max_exec_time
FROM
    pg_stat_statements
ORDER BY
    total_exec_time DESC
LIMIT 10;

```

I was able to identify the top slowest queries which you can find in this google sheet linked [HERE](https://docs.google.com/spreadsheets/d/15kiHtopCYWCjWgGpZYfQZRJ1VhjLgocJXteRs7b-zw8/edit?usp=sharing)

Screenshot for quick glance:
<img width="1501" alt="Screenshot 2024-11-20 at 1 42 06 PM" src="https://github.com/user-attachments/assets/e5ff2a9b-33b9-4e45-9549-3ed31c3c39f2">

Just in case this is needed, I've included the database details:

```
kestra=> SELECT
    n.nspname || '.' || c.relname AS full_table_name,
    pg_size_pretty(pg_total_relation_size(c.oid)) AS total_size,
    pg_size_pretty(pg_relation_size(c.oid)) AS table_size,
    pg_size_pretty(pg_total_relation_size(c.oid) - pg_relation_size(c.oid)) AS indexes_size
FROM
    pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE
    c.relkind = 'r'  -- Only base tables
    AND n.nspname NOT IN ('pg_catalog', 'information_schema')
ORDER BY
    pg_total_relation_size(c.oid) DESC
LIMIT 10;
      full_table_name      | total_size | table_size | indexes_size
---------------------------+------------+------------+--------------
 public.queues             | 28 GB      | 7288 MB    | 21 GB
 public.executions         | 4191 MB    | 1050 MB    | 3141 MB
 public.execution_queued   | 1460 MB    | 702 MB     | 758 MB
 public.logs               | 570 MB     | 412 MB     | 158 MB
 public.metrics            | 294 MB     | 233 MB     | 60 MB
 public.executorstate      | 265 MB     | 214 MB     | 51 MB
 public.service_instance   | 1032 kB    | 976 kB     | 56 kB
 public.worker_job_running | 432 kB     | 8192 bytes | 424 kB
 public.flows              | 336 kB     | 48 kB      | 288 kB
 public.triggers           | 160 kB     | 80 kB      | 80 kB
(10 rows)
```

### Environment

- Kestra Version: latest

I'm using AWS:

- EC2: m6i.4xlarge
- RDS: db.r6g.4xlarge
- Docker Swarm:
```yaml
volumes:
  kestra-data:
    driver: local

services:
  kestra-webserver:
    image: kestra/kestra:v0.19.9
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 30
    env_file: &env
      - .env_encoded
    user: "root"
    command: server webserver
    volumes: &volumes
      - kestra-data:/app/storage
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/kestra-wd:/tmp/kestra-wd
    environment: &configuration
      KESTRA_CONFIGURATION: |
        datasources:
          postgres:
            url: jdbc:postgresql://endpoint:5432/kestra
            driverClassName: org.postgresql.Driver
            username: username
            password: password
        kestra:
          jdbc:
            cleaner:
              initialDelay: 1h
              fixedDelay: 1h
              retention: 3d
          tutorialFlows:
            enabled: false
          server:
            basic-auth:
              enabled: false
              username: "admin@kestra.io" # it must be a valid email address
              password: kestra
          repository:
            type: postgres
          storage:
            type: s3
            s3:
              accessKey: "accessKey"
              secretKey: "secretKey"
              region: "region"
              bucket: "bucket"
          queue:
            type: postgres
          tasks:
            tmp-dir:
              path: /tmp/kestra-wd/tmp
          url: https://url.com
          variables:
            globals:
              env: staging
          environment:
            name: Staging
            color: "#FCB37C"
    ports:
      - "80:8080"
      - "8081:8081"
    networks:
      - shared-overlay-network

  kestra-worker-1:
    image: kestra/kestra:v0.19.9
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        max_attempts: 30
    env_file: *env
    user: "root"
    command: server worker --thread=256
    volumes: *volumes
    environment: *configuration
    depends_on:
    - kestra-webserver
    networks:
      - shared-overlay-network

  kestra-executor-1:
    image: kestra/kestra:v0.19.9
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        max_attempts: 30
    env_file: *env
    user: "root"
    command: server executor
    volumes: *volumes
    environment: *configuration
    depends_on:
    - kestra-webserver
    networks:
      - shared-overlay-network

  kestra-worker-2:
    image: kestra/kestra:v0.19.9
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        max_attempts: 30
    env_file: *env
    user: "root"
    command: server worker --thread=256
    volumes: *volumes
    environment: *configuration
    depends_on:
    - kestra-webserver
    networks:
      - shared-overlay-network

  kestra-executor-2:
    image: kestra/kestra:v0.19.9
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        max_attempts: 30
    env_file: *env
    user: "root"
    command: server executor
    volumes: *volumes
    environment: *configuration
    depends_on:
    - kestra-webserver
    networks:
      - shared-overlay-network

  kestra-worker-3:
    image: kestra/kestra:v0.19.9
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        max_attempts: 30
    env_file: *env
    user: "root"
    command: server worker --thread=256
    volumes: *volumes
    environment: *configuration
    depends_on:
    - kestra-webserver
    networks:
      - shared-overlay-network

  kestra-executor-3:
    image: kestra/kestra:v0.19.9
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        max_attempts: 30
    env_file: *env
    user: "root"
    command: server executor
    volumes: *volumes
    environment: *configuration
    depends_on:
    - kestra-webserver
    networks:
      - shared-overlay-network

  kestra-scheduler-1:
    image: kestra/kestra:v0.19.9
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        max_attempts: 30
    env_file: *env
    user: "root"
    command: server scheduler
    volumes: *volumes
    environment: *configuration
    depends_on:
    - kestra-webserver
    networks:
      - shared-overlay-network

networks:
  shared-overlay-network:
    external: true
    name: shared-overlay-network

```
