### ISSUE TITLE
[UI] Improve execution error display in the execution overview page

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#6029]
### Feature description

PR https://github.com/kestra-io/kestra/pull/5989 brings a new error widget in the execution overview for failed executions.
This displays a list of taskId / taskRunId / message.
However, the design can be improved.

This can be tested with the following flow YAML:
```yaml
id: fail
namespace: company.team

tasks:
  - id: fail
    type: io.kestra.plugin.core.execution.Fail
```
