### ISSUE TITLE
Disable the Execute button if inputs don't pass validation - e.g. email input type

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#6039]
### Describe the issue

```yaml
id: kestra_cloud_form
namespace: company.team

inputs:
  - id: email
    type: EMAIL
    displayName: Your e-mail address

  - id: reason
    type: STRING
    displayName: What do you plan to orchestrate?

  - id: accept_tos
    type: BOOLEAN
    defaults: true
    displayName: I agree to receive other communications from Kestra.
    description: By clicking Submit, you agree to Kestra storing and processing the personal information provided above to deliver the requested content.

tasks:
  - id: save_in_db
    type: io.kestra.plugin.core.log.Log
    message: Signup received
```
![image](https://github.com/user-attachments/assets/51f2acfb-eff8-47cd-b9b0-c5a03f2ac499)

![image](https://github.com/user-attachments/assets/dfe6c74a-d158-4a7f-a792-fb1a12ad83b1)

### Environment

- Kestra Version: develop
