### ISSUE TITLE
Input field is not displayed in Execute Flow dialog immediately after adding it to a flow

### ISSUE THREAD

**Issue by peterskim12** [kestra-io/kestra#6070]
### Describe the issue

Input field is not provided in Execute Flow dialog if you click the Execute button immediately after adding an input and saving it to an existing flow.

Steps to reproduce:
1) Create new flow which doesn't contain an input:
```
id: getting_started
namespace: company.team

tasks:
  - id: hello_world
    type: io.kestra.plugin.core.log.Log
    message: Hello World!
```
2) Add an input to the flow:
```
id: getting_started
namespace: company.team

inputs:
  - id: api_url
    type: STRING

tasks:
  - id: hello_world
    type: io.kestra.plugin.core.log.Log
    message: Hello World!
```

3) Click Save, then click Execute immediately (in less than 1 second between both clicks). 

The Execute dialog should contain an input field but it doesn't. 

If you wait at least 1-2 seconds after clicking Save, then clicking Execute, the input field appears as expected. 

VIdeo reproducing issue: https://youtu.be/oneb5DZqI2o

### Environment

- Kestra Version: develop
