### ISSUE TITLE
Ensure that the errorLogs() function captures error logs from a script

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#6083]
### Feature description

```yaml
id: error_logs_demo
namespace: company.team

tasks:    
  - id: fail
    type: io.kestra.plugin.scripts.python.Script
    taskRunner:
      type: io.kestra.plugin.core.runner.Process
    script: |
      raise ValueError("An error occurred: This is a manually raised exception.")
errors:
  - id: alert
    type: io.kestra.plugin.core.log.Log
    message: list of error logs — {{ errorLogs() }}
```

Another example:

```yaml
id: error_logs_demo
namespace: company.team

tasks:    
  - id: fail
    type: io.kestra.plugin.scripts.python.Script
    taskRunner:
      type: io.kestra.plugin.core.runner.Process
    script: |
      def divide_numbers(a, b):
          return a / b

      result = divide_numbers(5, 0)
      print(result)

errors:
  - id: alert
    type: io.kestra.plugin.core.log.Log
    message: list of error logs — {{ errorLogs() }}
```

The only error log it captures is `Command failed with exit code 1`  - the actual log with a reason why the task failed is not captured.

```bash
list of error logs — [{"namespace":"company.team","flowId":"error_logs_demo2","taskId":"fail","executionId":"41ClpgK5tLqp2WqKsM1U3c","taskRunId":"tfBn6QL2y51KtWxUDbWf7","attemptNumber":0,"timestamp":"2024-11-25T15:40:22.226Z","level":"ERROR","thread":"worker_4","message":"Command failed with exit code 1","deleted":false},{"namespace":"company.team","flowId":"error_logs_demo2","taskId":"fail","executionId":"41ClpgK5tLqp2WqKsM1U3c","taskRunId":"tfBn6QL2y51KtWxUDbWf7","attemptNumber":0,"timestamp":"2024-11-25T15:40:22.226Z","level":"ERROR","thread":"worker_4","message":"io.kestra.core.models.tasks.runners.TaskException: Command failed with exit code 1","deleted":false}]
```

**Comment by wrussell1999** [comment]
This is an example with S3 Copy that fails.

```yaml
id: error_logs_demo
namespace: company.team

tasks:    
  - id: copy
    type: io.kestra.plugin.aws.s3.Copy
    accessKeyId: "<access-key>"
    secretKeyId: "<secret-key>"
    region: "eu-central-1"
    from:
      bucket: "my-bucket"
      key: "path/to/file"
    to:
      bucket: "my-bucket2"
      key: "path/to/file2"

errors:
  - id: alert
    type: io.kestra.plugin.core.log.Log
    message: list of error logs — {{ errorLogs() }}
```

Result:
![Screenshot 2024-11-25 at 15 43 30](https://github.com/user-attachments/assets/27a4afb7-5a44-43af-a7d5-addb0db0ec37)

`develop` EE
