### ISSUE TITLE
Skip error message display on Cancelled executions e.g. due to EXECUTION_CONDITION SLA with CANCEL behavior

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#6098]
### Feature description

![image](https://github.com/user-attachments/assets/d90199f4-1e33-44af-9796-0bbdfb67678c)

Repro - run with CANCEL input:

```yaml
id: sla_demo
namespace: company.team

inputs:
  - id: behavior
    type: SELECT
    values:
      - FAIL
      - CANCEL
      - NONE
    defaults: NONE

sla:
  - id: maxDuration
    type: MAX_DURATION
    behavior: FAIL
    duration: PT2S
    labels:
      sla: missed

  - id: cancel
    type: EXECUTION_CONDITION
    behavior: CANCEL # Execution killed due to missed SLA
    condition: "{{ inputs.behavior == 'CANCEL' }}"
    labels:
      sla: missed
      
  - id: pass_and_log
    type: EXECUTION_CONDITION
    behavior: NONE # SLA passed with a log message
    condition: "{{ inputs.behavior == 'NONE' }}"
    labels:
      sla: passed

tasks:
  - id: hi
    type: io.kestra.plugin.core.log.Log
    message: Welcome!

  - id: sleep
    type: io.kestra.plugin.core.flow.Sleep
    duration: PT3S

  - id: bye
    type: io.kestra.plugin.core.log.Log
    message: Goodbye!
```
