### ISSUE TITLE
Flow trigger plugin is not displayed correctly — the columnar display truncates long text

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#6099]
### Describe the issue

![image](https://github.com/user-attachments/assets/af022e07-524d-46a0-b126-341ba549f180)

To reproduce, add 2 flows, one depending on another:

```yaml
id: myflow
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World!

triggers:
  - id: flow_trigger
    type: io.kestra.plugin.core.trigger.Flow
    preconditions:
      id: child_flow
      flows:
        - namespace: company.team
          flowId: child
          states: [SUCCESS]
```

and child flow:

```yaml
id: child
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello from {{ flow.id }}
```

then run the child flow to reproduce the bug

### Environment

- Kestra Version: develop
