### ISSUE TITLE
UI Flow Dependencies display is not adjusted to match Flow trigger preconditions — since no conditions are defined, UI shows all flows in the instance as dependencies

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#6100]
### Describe the issue

To reproduce, add 2 flows, `myflow` depending on `child` flow:

```yaml
id: myflow
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World!

triggers:
  - id: flow_trigger
    type: io.kestra.plugin.core.trigger.Flow
    preconditions:
      id: child_flow
      flows:
        - namespace: company.team
          flowId: child
          states: [SUCCESS]
```

and child flow:

```yaml
id: child
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello from {{ flow.id }}
```

Then refresh the page of the `myflow` and go to `Dependencies` tab: you will see that all flows in the instance are listed as dependencies. We need to fix it to first check for `preconditions`, only then check for `conditions`.

![image](https://github.com/user-attachments/assets/26bac472-abef-427f-b949-e5df8ffc874d)

**Note that backend behavior is OK — running any `tutorial` flow will not trigger an execution of `myflow`. Only the UI needs adjustment.**

@loicmathieu if you have any suggestions for the front end folks on how to tackle this, please share

### Environment

- Kestra Version: develop
