### ISSUE TITLE
[Flow trigger]  UI warning when using the time string "HH:MM:SS" — `String is not a RFC3339 time`

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#6102]
### Feature description

repro:

```yaml
id: myflow
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World!

triggers:
  - id: flow_trigger
    type: io.kestra.plugin.core.trigger.Flow
    preconditions:
      id: myflow
      timeWindow:
        type: DAILY_TIME_DEADLINE
        deadline: "09:00:00"
      flows:
        - namespace: company.team
          flowId: child
          states: [SUCCESS]
```

![image](https://github.com/user-attachments/assets/5d969cf0-9895-46a7-b45b-b69f4261045f)
