### ISSUE TITLE
UI Execution logs tab shows a task run as Failed when its state is Success due to `allowWarning: true`

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#6103]
### Describe the issue

Follow up to https://github.com/kestra-io/kestra/pull/5472

Reproducer:

```yaml
id: fail
namespace: company.team
tasks:
  - id: warn
    type: io.kestra.plugin.core.execution.Fail
    allowFailure: true
    allowWarning: true
```

This should be a green `Success` state here:

![image](https://github.com/user-attachments/assets/0472d190-ebae-41a2-975b-6653d9dec623)

The same is true for:

```yaml
id: fail
namespace: company.team
tasks:
  - id: warn
    type: io.kestra.plugin.core.execution.Fail
    allowFailure: true
```

![image](https://github.com/user-attachments/assets/0fb1d974-914e-4e64-9ae0-e7bf171ee776)

### Environment

- Kestra Version: develop
