### ISSUE TITLE
Empty Proxy have different behaviors in HTTP.Request

### ISSUE THREAD

**Issue by ThierryLehoux** [kestra-io/kestra#6107]
### Describe the issue

In the plugin `io.kestra.plugin.core.http.Request`, 
In http options, the proxy is
 - **skip** if we set it literally with an empty string.
 - **set to localhost** if we set it with a evaluated syntax that give an empty string.

Here a sample to reproduce the issue.
If should be great for us to be able to conditionnaly set the proxy based on other variables

Here a sample to reproduce the issue.
```
id: test-proxy-vide
namespace: seiitra.tlehoux

description: |
  Test condition of proxy with syntax interpretation

tasks:
  - id: log_condition_that_create_empty_string
    type: io.kestra.plugin.core.log.Log
    message: "why '{{ 1 == 1 ? '' : '' }}' is not equivalent to '' in proxy address"  

  - id: test_google_no_proxy
    type: io.kestra.plugin.core.http.Request
    uri: "https://www.google.com/"
    method: GET
    options: 
      proxyAddress: ""
      proxyPort: 3128
      proxyType: HTTP
  - id: Failt_test_google_proxy_set_to_localhost
    type: io.kestra.plugin.core.http.Request
    uri: "https://www.google.com/"
    method: GET
    options: 
      proxyAddress: "{{ 1 == 1 ? '' : '' }}"
      proxyPort: 3128
      proxyType: HTTP
```

### Environment

- Kestra Version: 0.18.3
