### ISSUE TITLE
Local Flow Synchronization file format and Export Flows format do not match 

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#6116]
### Describe the issue

When I export a flow from the UI in Kestra, it produces a file for a flow of flow id `myflow` and namespace `company.team` as:
```
company.team.myflow.yml
```

However, when configuring Kestra to look for [local files](https://github.com/kestra-io/docs/pull/1842/files#diff-d5ee1ebfb16758267a6ee7031eb3490e55d7a20d17c922987cd95340ed514527), the error says file not found with the file in this format:
```
company.team_myflow.yml
```

This causes a bit of confusion because I tried to export my flows, put them in a local directory and point my Kestra Configuration at that directory but was hit by an error due to inconsistent naming.

`company.team.myflow.yml`:
```yaml
id: myflow
namespace: company.team
tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: "{{ secret('AWS_ACCESS_KEY_ID') }}"
```

### Environment

- Kestra Version: `develop` OSS
