### ISSUE TITLE
Local File Sync doesn't work

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#6120]
### Describe the issue

When setting up [Local File Sync](https://github.com/kestra-io/docs/pull/1842/files#diff-d5ee1ebfb16758267a6ee7031eb3490e55d7a20d17c922987cd95340ed514527) on an empty instance of Kestra, I am hit with the following error:

```
kestra-1    | 2024-11-26 14:20:45,689 ERROR standalone   i.k.c.s.FileChangedEventListener /Users/wrussell/Documents/Repositories/kestra-server/example/example_flows
kestra-1    | java.lang.NullPointerException
kestra-1    |   at java.base/sun.nio.fs.UnixPath.register(Unknown Source)
kestra-1    |   at java.base/java.nio.file.Path.register(Unknown Source)
kestra-1    |   at io.kestra.cli.services.FileChangedEventListener.startListening(FileChangedEventListener.java:115)
kestra-1    |   at io.kestra.cli.services.FileChangedEventListener.startListeningFromConfig(FileChangedEventListener.java:106)
kestra-1    |   at io.kestra.cli.commands.servers.StandAloneCommand.call(StandAloneCommand.java:124)
kestra-1    |   at io.kestra.cli.commands.servers.StandAloneCommand.call(StandAloneCommand.java:24)
kestra-1    |   at picocli.CommandLine.executeUserObject(CommandLine.java:2045)
kestra-1    |   at picocli.CommandLine.access$1500(CommandLine.java:148)
kestra-1    |   at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
kestra-1    |   at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
kestra-1    |   at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
kestra-1    |   at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
kestra-1    |   at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
kestra-1    |   at picocli.CommandLine.execute(CommandLine.java:2174)
kestra-1    |   at io.kestra.cli.App.execute(App.java:67)
kestra-1    |   at io.kestra.cli.App.main(App.java:50)
```

My Kestra configuration is the default with this addition at the bottom: 

```yaml
micronaut:
  io:
    watch:
      enabled: true
      paths:
        - /Users/wrussell/Documents/Repositories/kestra-server/example/example_flows
```

Directory on my system:
![Screenshot 2024-11-26 at 14 43 16](https://github.com/user-attachments/assets/f43dc346-0f55-44c6-98bb-a46286a06228)

Full flow:
```yaml
KESTRA_CONFIGURATION: |
  datasources:
    postgres:
      url: jdbc:postgresql://postgres:5432/kestra
      driverClassName: org.postgresql.Driver
      username: kestra
      password: k3str4
  kestra:
    server:
      basic-auth:
        enabled: false
        username: "admin@kestra.io" # it must be a valid email address
        password: kestra
    repository:
      type: postgres
    storage:
      type: local
      local:
        base-path: "/app/storage"
    queue:
      type: postgres
    tutorial-flows:
      enabled: false 
    tasks:
      tmp-dir:
        path: /tmp/kestra-wd/tmp
    url: http://localhost:8080/
  micronaut:
    io:
      watch:
        enabled: true
        paths:
          - /Users/wrussell/Documents/Repositories/kestra-server/example/example_flows
```

### Environment

- Kestra Version: `develop` OSS Docker (using the Docker Compose file)

**Comment by wrussell1999** [comment]
Somewhat related: https://github.com/kestra-io/kestra/issues/6116 as couldn't identify files which were correctly named in the folder. This example has `myflow` in Kestra and in the sync flows directory:

```java
kestra-1    | 2024-11-26 14:48:08,264 ERROR standalone   i.k.c.s.FileChangedEventListener /Users/wrussell/Documents/Repositories/kestra-server/example/example_flows
kestra-1    | 2024-11-26 14:48:08,292 ERROR standalone   i.k.c.s.FileChangedEventListener Error writing file: /Users/wrussell/Documents/Repositories/kestra-server/example/example_flows/company.team_myflow.yml
kestra-1    | java.nio.file.NoSuchFileException: /Users/wrussell/Documents/Repositories/kestra-server/example/example_flows/company.team_myflow.yml
kestra-1    |   at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
kestra-1    |   at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
kestra-1    |   at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
kestra-1    |   at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(Unknown Source)
kestra-1    |   at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(Unknown Source)
kestra-1    |   at java.base/java.nio.file.Files.newOutputStream(Unknown Source)
kestra-1    |   at java.base/java.nio.file.Files.write(Unknown Source)
kestra-1    |   at java.base/java.nio.file.Files.writeString(Unknown Source)
kestra-1    |   at java.base/java.nio.file.Files.writeString(Unknown Source)
kestra-1    |   at io.kestra.cli.services.FileChangedEventListener.flowToFile(FileChangedEventListener.java:223)
kestra-1    |   at io.kestra.cli.services.FileChangedEventListener.lambda$startListeningFromConfig$1(FileChangedEventListener.java:77)
kestra-1    |   at io.kestra.core.runners.FlowListeners.listen(FlowListeners.java:143)
kestra-1    |   at io.kestra.cli.services.FileChangedEventListener.startListeningFromConfig(FileChangedEventListener.java:73)
kestra-1    |   at io.kestra.cli.commands.servers.StandAloneCommand.call(StandAloneCommand.java:124)
kestra-1    |   at io.kestra.cli.commands.servers.StandAloneCommand.call(StandAloneCommand.java:24)
kestra-1    |   at picocli.CommandLine.executeUserObject(CommandLine.java:2045)
kestra-1    |   at picocli.CommandLine.access$1500(CommandLine.java:148)
kestra-1    |   at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
kestra-1    |   at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
kestra-1    |   at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
kestra-1    |   at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
kestra-1    |   at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
kestra-1    |   at picocli.CommandLine.execute(CommandLine.java:2174)
kestra-1    |   at io.kestra.cli.App.execute(App.java:67)
kestra-1    |   at io.kestra.cli.App.main(App.java:50)
kestra-1    | java.lang.NullPointerException
kestra-1    |   at java.base/sun.nio.fs.UnixPath.register(Unknown Source)
kestra-1    |   at java.base/java.nio.file.Path.register(Unknown Source)
kestra-1    |   at io.kestra.cli.services.FileChangedEventListener.startListening(FileChangedEventListener.java:115)
kestra-1    |   at io.kestra.cli.services.FileChangedEventListener.startListeningFromConfig(FileChangedEventListener.java:106)
kestra-1    |   at io.kestra.cli.commands.servers.StandAloneCommand.call(StandAloneCommand.java:124)
kestra-1    |   at io.kestra.cli.commands.servers.StandAloneCommand.call(StandAloneCommand.java:24)
kestra-1    |   at picocli.CommandLine.executeUserObject(CommandLine.java:2045)
kestra-1    |   at picocli.CommandLine.access$1500(CommandLine.java:148)
kestra-1    |   at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
kestra-1    |   at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
kestra-1    |   at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
kestra-1    |   at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
kestra-1    |   at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
kestra-1    |   at picocli.CommandLine.execute(CommandLine.java:2174)
kestra-1    |   at io.kestra.cli.App.execute(App.java:67)
kestra-1    |   at io.kestra.cli.App.main(App.java:50)
```

**Comment by wrussell1999** [comment]
For Docker, you need to set up a bind mount so it can see the local directory on your machine. Example:

```yaml
kestra:
    image: kestra/kestra:develop
    pull_policy: always
    # Note that this setup with a root user is intended for development purpose.
    # Our base image runs without root, but the Docker Compose implementation needs root to access the Docker socket
    # To run Kestra in a rootless mode in production, see: https://kestra.io/docs/installation/podman-compose
    user: "root"
    command: server standalone
    volumes:
      - kestra-data:/app/storage
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/kestra-wd:/tmp/kestra-wd
      - /Users/wrussell/Documents/Repositories/kestra-server/example/example_flows:/local_flows
    env_file:
      - .env_encoded
    environment:
      KESTRA_CONFIGURATION: |
        datasources:
          postgres:
            url: jdbc:postgresql://postgres:5432/kestra
            driverClassName: org.postgresql.Driver
            username: kestra
            password: k3str4
        kestra:
          server:
            basic-auth:
              enabled: false
              username: "admin@kestra.io" # it must be a valid email address
              password: kestra
          repository:
            type: postgres
          storage:
            type: local
            local:
              base-path: "/app/storage"
          queue:
            type: postgres
          tutorial-flows:
            enabled: false 
          tasks:
            tmp-dir:
              path: /tmp/kestra-wd/tmp
          url: http://localhost:8080/
        micronaut:
          io:
            watch:
              enabled: true
              paths:
                - /local_flows
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_started
```
