### ISSUE TITLE
Flows with boolean inputs can't be executed

### ISSUE THREAD

**Issue by smunteankestra** [kestra-io/kestra#6121]
### Describe the issue

Flow to reproduce:

```yaml
id: autotest_9062d0bc-97df-4313-ad6c-9d0841bcef37
namespace: autotest_9062d0bc-97df-4313-ad6c-9d0841bcef37

inputs:
  - id: bool
    type: BOOLEAN

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: "Hello World! {{ inputs.test }}"
```

### Environment

- Kestra Version: develop
