### ISSUE TITLE
Invesitgate the best way to provide metadata context for why some Execution has failed

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#6123]
We were investigating adding a function `errorInfo()` that would emit the following as a JSON object: 

```json
{
  "namespace": "namespace",
  "flowId": "flowId",
  "id": "id",
  "startTime": "...",
  "endTime": "...",
  "tasks": [{
    "id": "id",
    "type": "task class like Python, SQL Server Query etc"
  }],
  "state": "FAILED"
}
```

If the function were called from a non-`FAILED` execution, the `tasks` array would be `null`.

However, there were some **challenges** with this approach:
- The execution is not terminated when you are in an `error` branch, so it is reported as `RUNNING`. This means we cannot limit the function to `FAILED` execution as we have no way to know if an execution is `FAILED` before it is terminated.
- We can fetch an execution that is not up-to-date, so the function can return no failed task even if some failed task run exists

So the `errorInfo()` as a function doesn't work. 

This will solve the problem raised here https://github.com/kestra-io/kestra-ee/issues/2264#issuecomment-2500397364

**Comment by Ben8t** [comment]
@anna-geller isn't the same as `errorLogs` introduced in 0.21? lmk if I miss something, or if can close

**Comment by anna-geller** [comment]
Logs are logs, this one fetches metadata about a failed execution. Seems like a useful pebble function and easy enough for a new joiner like Malay soon 

So it's different, both are useful

**Comment by anna-geller** [comment]
In fact, the log itself in `errorLogs()` already provides the info on which task failed (at least if only one failed): `The execution ended in FAILED with error [{"namespace":"company.team","flowId":"stingray_943886","taskId":"hello","executionId":"1QHYxlz2E4bnP4rbio0Lf0","taskRunId":"6uzoQWfq05thRB9F2vWjjc","attemptNumber":0,"timestamp":"2025-03-30T11:46:02.247338Z","level":"ERROR","thread":"worker_22","message":"something went wrong here","deleted":false}]`



```yaml
id: stingray_943886
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.core.execution.Fail
    errorMessage: something went wrong here

afterExecution:
  - id: onError
    type: io.kestra.plugin.core.log.Log
    runIf: "{{execution.state == 'FAILED'}}"
    message: "The execution ended in {{execution.state}} with error {{errorLogs()}}"
```

so we can close for now
