### ISSUE TITLE
Possible memory leak leading to Java Heap Space error

### ISSUE THREAD

**Issue by LegendJerry-Goguette** [kestra-io/kestra#6129]
### Describe the issue

I'm running into issues: `Java heap space`

<img width="1285" alt="Screenshot 2024-11-26 at 11 57 25 AM" src="https://github.com/user-attachments/assets/d2aaefb1-2ec1-42c8-bbdd-e43605648fed">

I believe there is a memory leak somewhere. Because the memory kept increasing bit by bit until eventual crash/restart or triggers die with that error.

My current Setup for the triggers include:

3 Real time debezium mysql triggers
-- 1 constant load (200+ per minute)
-- 1 hourly bulk load (30K+ per hour)
-- 1 minimal load (50+ per hour)
1 Webhook
-- Constant load (Roughly 1500+ per minute)

Each of the triggers have a simple kafka produce task. No variables/inputs used.

Sample task:
```yaml
id: boot-mysql-connector-realtime-2-prod
namespace: wisepublishing.engineering

labels:
  env: dev
  project: snowflake-data-ingest

tasks:
  - id: send-to-snowflake
    type: io.kestra.plugin.kafka.Produce
    from:
      value: "{{ trigger.data }}"
      timestamp: "{{ execution.startDate }}"
    topic: "{{ trigger.data.metadata.source.db | replace({'_staging': ''}) | replace({'.': '_'}) }}_{{ trigger.data.metadata.source.table | replace({'_staging': ''}) | replace({'.': '_'}) }}"
    transactional: true
    properties:
      bootstrap.servers: "{{ secret('KAFKA_BOOTSTRAP_SERVERS') }}"
      sasl.mechanism: SCRAM-SHA-512
      sasl.jaas.config: "{{ secret('KAFKA_JASS_CONFIG') }}"
      security.protocol: SASL_SSL

```

### Environment

Kestra Version: latest
I'm using AWS:

EC2: m6i.4xlarge
RDS: db.r6g.4xlarge
Docker Swarm:
```
volumes:
  kestra-data:
    driver: local

services:
  kestra-webserver:
    image: kestra/kestra:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 30
    env_file: &env
      - .env_encoded
    user: "root"
    command: server webserver
    volumes: &volumes
      - kestra-data:/app/storage
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/kestra-wd:/tmp/kestra-wd
    environment: &configuration
      KESTRA_CONFIGURATION: |
        datasources:
          postgres:
            url: jdbc:postgresql://endpoint:5432/kestra
            driverClassName: org.postgresql.Driver
            username: username
            password: password
        kestra:
          jdbc:
            cleaner:
              initialDelay: 1h
              fixedDelay: 1h
              retention: 3d
          tutorialFlows:
            enabled: false
          server:
            basic-auth:
              enabled: false
              username: "admin@kestra.io" # it must be a valid email address
              password: kestra
          repository:
            type: postgres
          storage:
            type: s3
            s3:
              accessKey: "accessKey"
              secretKey: "secretKey"
              region: "region"
              bucket: "bucket"
          queue:
            type: postgres
          tasks:
            tmp-dir:
              path: /tmp/kestra-wd/tmp
          url: https://url.com
          variables:
            globals:
              env: staging
          environment:
            name: Staging
            color: "#FCB37C"
    ports:
      - "80:8080"
      - "8081:8081"
    networks:
      - shared-overlay-network

  kestra-worker-1:
    image: kestra/kestra:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        max_attempts: 30
    env_file: *env
    user: "root"
    command: server worker --thread=256
    volumes: *volumes
    environment: *configuration
    depends_on:
    - kestra-webserver
    networks:
      - shared-overlay-network

  kestra-executor-1:
    image: kestra/kestra:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        max_attempts: 30
    env_file: *env
    user: "root"
    command: server executor
    volumes: *volumes
    environment: *configuration
    depends_on:
    - kestra-webserver
    networks:
      - shared-overlay-network

  kestra-worker-2:
    image: kestra/kestra:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        max_attempts: 30
    env_file: *env
    user: "root"
    command: server worker --thread=256
    volumes: *volumes
    environment: *configuration
    depends_on:
    - kestra-webserver
    networks:
      - shared-overlay-network

  kestra-executor-2:
    image: kestra/kestra:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        max_attempts: 30
    env_file: *env
    user: "root"
    command: server executor
    volumes: *volumes
    environment: *configuration
    depends_on:
    - kestra-webserver
    networks:
      - shared-overlay-network

  kestra-worker-3:
    image: kestra/kestra:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        max_attempts: 30
    env_file: *env
    user: "root"
    command: server worker --thread=256
    volumes: *volumes
    environment: *configuration
    depends_on:
    - kestra-webserver
    networks:
      - shared-overlay-network

  kestra-executor-3:
    image: kestra/kestra:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        max_attempts: 30
    env_file: *env
    user: "root"
    command: server executor
    volumes: *volumes
    environment: *configuration
    depends_on:
    - kestra-webserver
    networks:
      - shared-overlay-network

  kestra-scheduler-1:
    image: kestra/kestra:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        max_attempts: 30
    env_file: *env
    user: "root"
    command: server scheduler
    volumes: *volumes
    environment: *configuration
    depends_on:
    - kestra-webserver
    networks:
      - shared-overlay-network

networks:
  shared-overlay-network:
    external: true
    name: shared-overlay-network
```
