### ISSUE TITLE
Support @hourly, @daily, @weekly, @monthly, etc. cron shortcuts

### ISSUE THREAD

**Issue by nsteinmetz** [kestra-io/kestra#614]
### Feature description

Hi,

Instead of:

```yaml
triggers:
  - id: schedule
    type: io.kestra.core.models.triggers.types.Schedule
    backfill:
      start: "2022-04-30T22:00:00Z"
    cron: 0 0 * * *
```

It would be nice to use:

```yaml
triggers:
  - id: schedule
    type: io.kestra.core.models.triggers.types.Schedule
    backfill:
      start: "2022-04-30T22:00:00Z"
    cron: "@daily"
```

Thanks !
