### ISSUE TITLE
String is not RFC3339 in new trigger precondition

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#6156]
### Describe the issue

While setting precondition with `DAILY_TIME_DEADLINE` sla

```yaml
triggers:
  - id: upstream_dep
    type: io.kestra.plugin.core.trigger.Flow
    inputs:
      value_from_a: "{{ trigger.outputs.return_value }}"
    preconditions:
      id: test
      flows:
        - namespace: kestra.sandbox
          flowId: flow_a
          states: [SUCCESS]
      timeWindow: 
        type: DAILY_TIME_DEADLINE
        deadline: "09:00:00"
```

![Screenshot 2024-11-28 at 09 57 09](https://github.com/user-attachments/assets/96d050ae-88ff-4c28-b61c-647f80f69e60)

👉 Can we have other ISO specification? we use ISO 8601 time in other part of the application

### Environment

- Kestra Version: develop
