### ISSUE TITLE
Flow Trigger precondition to check upstream outputs values

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#6160]
### Feature description

The flow below never triggered with
```yaml
      where:
        - id: outputs
          filters:
            - type: IS_NOT_NULL
              field: EXPRESSION
              value: "{{ trigger.outputs.return_value }}"
```

(it works without it)

I would expect to be able to be able to user upstream flow outputs in the EXPRESSION type in filters:

```yaml
id: flow_b
namespace: kestra.sandbox

inputs:
  - id: value_from_a
    type: STRING

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: "{{ inputs.value_from_a }}"

triggers:
  - id: upstream_dep
    type: io.kestra.plugin.core.trigger.Flow
    inputs:
      value_from_a: "{{ trigger.outputs.return_value }}"
    preconditions:
      id: test
      flows:
        - namespace: kestra.sandbox
          flowId: flow_a
          states: [SUCCESS]
      where:
        - id: outputs
          filters:
            - type: IS_NOT_NULL
              field: EXPRESSION
              value: "{{ trigger.outputs.return_value }}"
```
