### ISSUE TITLE
JSON Flow outputs causes parent flow to fail

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#6212]
### Describe the issue

If you have a JSON flow output in a subflow, the parent flow will fail.

Subflow:
```yaml
id: debugJsonResult
namespace: debug

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Kestra Test with output

outputs:
  - id: myResult
    type: JSON
    value: |
      {
        "id": "myResult",
        "details": "just a simple json output"
      }
```

Parent flow:
```yaml
id: parentFlow
namespace: debug

tasks:
  - id: callSubflow
    type: io.kestra.plugin.core.flow.Subflow
    flowId: debugJsonResult
    namespace: debug
```

### Environment

- Kestra Version: develop
