### ISSUE TITLE
Use pebble expression in inputs - example: to provide Select input list

### ISSUE THREAD

**Issue by schmanat** [kestra-io/kestra#6232]
### Feature description

I would like to suggest an extension of the expression properties (for inputs). Would it be possible to extend them so that not only an array (or list) can be used as a source but also an array of objects. I currently have the following scenario.

Via the API of Gitlab I get all users and load them into a JSON object (id, username, email) now I want to display the username in the input of the “user”. In the subsequent flow, however, the ID must be used instead of the username. If everything is OK, I would like to send an email to the selected user.

I think the code is worth 1000 words

My KV Store

```JSON
[
  {
    "user":"schman",
    "id":"2",
    "email": "hello@schman.dev"
  },
  {
    "user":"jdoe",
    "id":"3",
    "email": "jane@schman.dev"
  }
]
```

and my flow looks like this:

```yaml
id: create-gitlab-project
namespace: schman.software

inputs:
  - id: project_name
    type: STRING
    required: true
    displayName: "Projektname"
    description: "Projektname für das Gitlab Projekt"

  - id: project_description
    type: STRING
    required: false
    displayName: "Projektbeschreibung"
    description: "Beschreibung des neuen Projektes."

  - id: namespace
    type: SELECT    
    displayName: "Namespace"
    description: "Namespace unter dem das Projekt angelegt wird."
    expression: "{{ json(kv('gitlab_namespace')).username }}"

variables:
  terraform_gitlab_project_url: "https://git.dornbirn.at/adsd-infrastruktur/terraform.git"
  terraform_gitlab_branch: "main"
  gitlab_root_access_token: "{{secret('GITLAB_ROOT_ACCESS_TOKEN')}}"

tasks:
  - id: wdir
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      - id: clone-terraform-git-project
        type: io.kestra.plugin.git.Clone
        url: "{{vars.terraform_gitlab_project_url}}"
        branch: "{{vars.terraform_gitlab_branch}}"
        username: root
        password: "{{ secret('GITLAB_ROOT_ACCESS_TOKEN')}}"

      - id: terraform
        type: io.kestra.plugin.terraform.cli.TerraformCLI
        beforeCommands:
          - terraform -chdir=gitlab init
        inputFiles:
          gitlab/terraform.auto.tfvars: |
            GITLAB_TOKEN = "{{secret('GITLAB_ROOT_ACCESS_TOKEN')}}"
            project_name = "{{inputs.project_name}}"
            project_description = "{{inputs.project_description}}"
            namespace = "{{inputs.namespace}}"
        outputFiles:
          - "*.txt"
        commands:
          - terraform -chdir=gitlab plan -no-color 2>&1 | tee plan_output.txt
          - terraform -chdir=gitlab apply -auto-approve -no-color 2>&1 | tee apply_output.txt      

triggers:
  - id: git_webhook
    type: io.kestra.plugin.core.trigger.Webhook
    key: "{{ inputs.project_name }}"

```

It would be cool to iterate it like:

```yaml
    expression: "{{ json(kv('gitlab_namespace')).username }}"
```
And then in the flow it should be possible to select the id instead of the selected username.
