### ISSUE TITLE
PAUSED tasks for killed execution should be marked as KILLED

### ISSUE THREAD

**Issue by fhussonnois** [kestra-io/kestra#6243]
### Describe the issue

If an execution is PAUSED then killed, the paused TaskRun remains in PAUSED state instead of being KILLED

Use this flow to reproduce: 
```yaml
id: paused_flow
namespace: io.kestra
tasks:
  - id: start
    type: io.kestra.plugin.core.debug.Return
    format: "Started"

  - id: pause
    type: io.kestra.plugin.core.flow.Pause

  - id: resume
    type: io.kestra.plugin.core.log.Log
    message: "Resumed"
```

### Environment

- Kestra Version: develop
