### ISSUE TITLE
Exception on "a lot of files download" from FTP

### ISSUE THREAD

**Issue by MarcoGriep88** [kestra-io/kestra#6248]
### Describe the issue

Hi, when i download alot of files (Recursive) from FTP i'm getting an "2024-12-02T14:55:07.524Z TRACE java.lang.StackOverflowError"

My Flow

```
id: backup_netcup_webspace_to_s3
namespace: company.backups
tasks:
  - id: download_webhosting_files
    type: io.kestra.plugin.fs.ftp.Downloads
    action: NONE
    from: /
    host: 188.0.0.0
    logLevel: INFO
    password: ULTRA-SAFE-PASSWORD
    recursive: true
    username: super_dupa_mega_root

  - id: create_tar_archive
    type: io.kestra.plugin.scripts.shell.Commands
    description: Erstellt ein Tar-Archiv der heruntergeladenen Dateien mit aktuellem Datum und Uhrzeit.
    commands:
      - export TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
      - tar -czf /tmp/backup_$TIMESTAMP.tar.gz -C "{{ outputs.download_webhosting_files.to }}" .
      - echo "/tmp/backup_$TIMESTAMP.tar.gz"
    logLevel: INFO
    outputFiles:
      - "/tmp/*.tar.gz"

errors:
  - id: send_failed_pushover_notification
    type: io.kestra.plugin.core.http.Request
    body: "{ \"token\": \"{{ secret('PUSHOVER_TOKEN') }}\", \"user\": \"{{ secret('PUSHOVER_USER') }}\", \"message\": \"Fehler in der Datensicherung von Webhosting\" }"
    contentType: application/json
    method: POST
    uri: https://api.pushover.net/1/messages.json

triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "@daily"
    disabled: true
```

This only happens when i download many files (About 40 Minutes download from FTP)

Full Log:
[kestra-execution-20241202161814-1wESh07VC5QVXAhjVYsqpL-6nCKK73whjSDqikT2jIDru.log](https://github.com/user-attachments/files/17980032/kestra-execution-20241202161814-1wESh07VC5QVXAhjVYsqpL-6nCKK73whjSDqikT2jIDru.log)

### Environment

- Kestra Version: 0.19.1
- Virtualized in Proxmox VM: Ubuntu 24.04 Host. Docker
