### ISSUE TITLE
PushNamespaceFiles seems to ignore recursive folders.

### ISSUE THREAD

**Issue by camsellem** [kestra-io/kestra#6255]
### Describe the issue

The flow below  doesnt push any changes to the git repository - Tried multiple Glob patterns but still ignore files. The files are organised as follow

![image](https://github.com/user-attachments/assets/68ff2663-95d0-4a6c-a2a7-6f50469362fc)
 
```
id: demo_github
namespace: io.kestra.examples

tasks:
  - id: commit_and_push
    type: io.kestra.plugin.git.PushNamespaceFiles
    namespace: io.kestra.examples
    files:
      - "**/*.sql"
      # - "**/*"
      # - "**/*.*"
    gitDirectory: _kestra
    url: https://github.com/camsellem/kinesis-to-segment
    username: camsellem
    password: "{{ secret('github_token') }}"
    branch: kestra
    commitMessage: "New queries files"
    dryRun: false

    workerGroup:
      key: kestra-dev-cluster
```

### Environment

- Kestra Version: 0.19.11

**Comment by Ben8t** [comment]
@camsellem I'm not able to fully reproduce 🤔 

```
id: push_ns
namespace: company

tasks:
  - id: push
    type: io.kestra.plugin.git.PushNamespaceFiles
    url: https://github.com/Ben8t/git-demo-kestra
    branch: test
    username: Ben8t
    password: '{{ secret("GH_TOKEN") }}'
    files:
      - "*"
```

works as intended (I've a test.txt and a queries/test.sql and both are pushed correctly).
