### ISSUE TITLE
[io.kestra.plugin.core.http.Download] Filename and file extension are not preserved

### ISSUE THREAD

**Issue by camsellem** [kestra-io/kestra#6270]
### Describe the issue

Reproduced on 19.8

Related to the issue [3788](https://github.com/kestra-io/kestra/issues/3788)

The file extension and name are not captured properly. Might be specific to the type of endpoint. Fila shared access to the endpoint - will share the postman collection to generate the session token in our private slack channel

```
tasks:
  - id: dl-img-fila
    type: io.kestra.plugin.core.http.Download
    uri: <<REDACTED>>
    headers:
      Cookie: SecurityTokenURL=centric://<<REDACTED>>
      Accept-Encoding: gzip, deflate, br
      Host: <<REDACTED>>
```

![image](https://github.com/user-attachments/assets/802ab48b-521d-46ca-8f2b-1453b0b5ddc8)

![image](https://github.com/user-attachments/assets/927c37d4-da47-462a-9d9f-37b0575ed8d8)

### Environment

- Kestra Version: develop
