### ISSUE TITLE
When typing an inline Python script, mention Namespace Files in a popup

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#6301]
## Problem

We hear feedback that despite our best efforts highlighting the existence of Namespace Files, some new users are not aware of it. 

## Idea 

When typing a script inline in YAML, prompt the user with a popup window:

> Did you know that you can manage your scripts as Namespace Files? Give it a try by expanding the left sidebar (Click on the `Files` icon) and adding a `main.py` file. Then reference it in your script as follows: small example flow with `namespaceFiles.enabled` set to `true`

- [ ] Add a nice visual pointing the user to the Namespace Files left sidebar 
- [ ] The user could click on "Don't show again" — similar to what we do asking to enable basic auth

**Comment by Nico-Kestra** [comment]
A popup with a small animation on the Files button could be nice. What do you think?

https://www.figma.com/proto/ew0uXk0NRXJ2NBBJTNe2n1/01_UI?page-id=0%3A1&node-id=4854-43774&node-type=frame&viewport=-1260%2C-3102%2C1.28&t=SjRraiv4rrwskSUI-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=681%3A5355

**Comment by anna-geller** [comment]
nice, thx Nico

btw I didn't mean it literally

the text would need to have a code block:

Did you know that you can manage your scripts as Namespace Files? Click on the `Files` icon and add your script e.g. `main.py` file. Then reference it in your script as follows: 
```yaml
id: python
namespace: company.team
tasks:
  - id: example
    type: io.kestra.plugin.scripts.python.Commands
    namespaceFiles:
      enabled: true
    commands:
      - python main.py
```
![image](https://github.com/user-attachments/assets/6581ff72-5b9f-42af-96bf-a3d570cec5b0)
