### ISSUE TITLE
UploadFiles to Namespace Files does not work correctly

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#6304]
### Describe the issue

I have a namespace file called `myfile.txt`. I was unable to write to it / overwrite it using the `UploadFiles` task. This was a common occurrence at the HackFrost hackathon that took place last week too.

```yaml
id: files
namespace: company.team

tasks:
  - id: python_output
    type: io.kestra.plugin.scripts.python.Script
    namespaceFiles:
      enabled: true
    taskRunner:
      type: io.kestra.plugin.core.runner.Process
    outputFiles:
      - "*.txt"
    script: |
      with open("myfile.txt", "a") as f:
        f.write("Hi, this is output from a script 👋")

  - id: save_file
    type: io.kestra.plugin.core.namespace.UploadFiles
    files:
      - "{{ outputs.python_output.outputFiles['myfile.txt'] }}"
    namespace: "{{ flow.namespace }}"

  - id: read_output
    type: io.kestra.plugin.core.log.Log
    message: "{{ read(outputs.python_output.outputFiles['myfile.txt']) }}"
```

This also didn't work if `myfile.txt` didn't exist in the first place.

### Environment

- Kestra Version: develop

**Comment by Skraye** [comment]
The reason is that you are using the task incorrectly, here is the good task :
 ```yaml
  - id: save_file
    type: io.kestra.plugin.core.namespace.UploadFiles
    filesMap: #change this property 
      myfile.txt: "{{ outputs.python_output.outputFiles['myfile.txt'] }}" #provide it as a map
    namespace: "{{ flow.namespace }}"
```

`files` is used for finding file in current directory through a regex, `fileMaps` using output files from other task where you have the direct access with the URI
