### ISSUE TITLE
Task run showing as RUNNING and duration still counting even though Execution was killed hours ago

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#6331]
### Describe the issue

Demo: https://share.descript.com/view/LOP42SX5vup

![image](https://github.com/user-attachments/assets/5d5ece75-c788-47ca-b893-b7d036108617)

It crashed the worker on cloud: https://github.com/kestra-io/kestra-ee/issues/2416

Execution: https://us.kestra.cloud/ui/kestra-tech/executions/company.team/api-python-sql/3dO37csVSlm7SjBzkeHTie

```yaml
id: api-python-sql
namespace: company.team
# disabled when it crashed the worker 
disabled: true

tasks:
  - id: api
    type: io.kestra.plugin.core.http.Request
    uri: https://dummyjson.com/products

  - id: python
    type: io.kestra.plugin.scripts.python.Script
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
    containerImage: python:slim
    beforeCommands:
      - pip install polars
    outputFiles:
      - products.csv
    warningOnStdErr: false
    script: |
      import polars as pl
      data = {{ outputs.api.body | jq('.products') | first }}
      df = pl.from_dicts(data)
      df.glimpse()
      df.select(["brand", "price"]).write_csv("products.csv")

  - id: sql_query
    type: io.kestra.plugin.jdbc.duckdb.Query
    inputFiles:
      in.csv: "{{ outputs.python.outputFiles['products.csv'] }}"
    sql: |
      SELECT brand, round(avg(price), 2) as avg_price
      FROM read_csv_auto('{{ workingDir }}/in.csv', header=True)
      GROUP BY brand
      ORDER BY avg_price DESC;
    fetchType: STORE
```

### Environment

- Kestra Version: develop
