### ISSUE TITLE
New Plugin - Hugging Face

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#6352]
### Feature description

Currently the http plugins makes possible to call Hugging Face models hosted behind [Inference API](https://huggingface.co/docs/api-inference/index).

Here is an example:
```yaml
  - id: llm_categorization
    type: io.kestra.plugin.core.http.Request
    uri: https://api-inference.huggingface.co/models/facebook/bart-large-mnli
    method: POST
    contentType: application/json
    headers:
      Authorization: "Bearer {{ secret('HF_API_TOKEN') }}"
    formData:
      inputs: "I want a refund"
      parameters:
        candidate_labels:
          - "legal"
          - "new feature"
          - "refund"
 ```

Most of the text models available under these API follow the same type of parameters. Here are the two main ones we can cover at first:

**Simple `inputs`**
```
curl https://api-inference.huggingface.co/models/meta-llama/Llama-3.2-1B \
	-X POST \
	-d '{"inputs": "Can you please let us know more details about your "}' \
	-H 'Content-Type: application/json' \
	-H 'Authorization: Bearer hf_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
```

**`inputs` and `parameters`**:

```
curl https://api-inference.huggingface.co/models/facebook/bart-large-mnli \
	-X POST \
	-d '{"inputs": "Hi, I recently bought a device from your company but it is not working as advertised and I would like to get reimbursed!", "parameters": {"candidate_labels": ["refund", "legal", "faq"]}}' \
	-H 'Content-Type: application/json' \
	-H 'Authorization: Bearer hf_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
```

## Task Design

**Task Type**: `io.kestra.plugin.huggingface.Inference`

**Properties**:

- `apiKey` - STRING - required
- `model` - STRING - required - <Organization>/<ModelName>, it's what follows the main api endpoint https://api-inference.huggingface.co/models ie. `meta-llama/Llama-3.2-1B`
- inputs - STRING - optional most of the time it's the prompt
- parameters - MAP/ARRAY - optional
- endpoint - STRING - optional, default to `https://api-inference.huggingface.co/models`

## Example

So instead of using http like this:
```yaml
  - id: llm_categorization
    type: io.kestra.plugin.core.http.Request
    uri: https://api-inference.huggingface.co/models/facebook/bart-large-mnli
    method: POST
    contentType: application/json
    headers:
      Authorization: "Bearer {{ secret('HF_API_TOKEN') }}"
    formData:
      inputs: "I want a refund"
      parameters:
        candidate_labels:
          - "legal"
          - "new feature"
          - "refund"
 ```

we simplify with Kestra DSL to:

```yaml
  - id: llm_categorization
    type: io.kestra.plugin.huggingface.Inference
    model: facebook/bart-large-mnli
    apiKey: XXXX
    inputs: "I want a refund"
    parameters:
      candidate_labels:
         - "legal"
         - "new feature"
         - "refund"
 ```
