### ISSUE TITLE
Bug - 90% of executions that have PARALLEL or SEQUENTIAL stuck in CREATED

### ISSUE THREAD

**Issue by japerry911** [kestra-io/kestra#6357]
### Describe the issue

- Bug - 90% of executions that have PARALLEL or SEQUENTIAL core flow tasks get stuck in CREATED

Hey team,

Reported in slack, but added here for transparency.

I think there are issues again with the executor, this execution is stuck for example - id - 28YS1LKkhHPIFuaKQLpF8q
I made a reproducible example, causes some Tasks to be locked in CREATED. It does sometimes succeed.
example -> https://www.loom.com/share/7481ee78f44b46d18aad93d45c4c7b81?sid=d1584d1e-1409-40f0-81af-c2c3b15373f0

```yaml
id: helloWorld
namespace: demo
description: |
  This flow logs a message to the console, and used for demoing and testing purposes.

inputs:
  - id: if1
    type: BOOLEAN

  - id: if2
    type: BOOLEAN

  - id: if3
    type: BOOLEAN

tasks:
  - id: parallel
    type: io.kestra.plugin.core.flow.Parallel
    concurrent: 0
    tasks:
      - id: if1
        type: io.kestra.plugin.core.flow.If
        condition: "{{ inputs.if1 }}"
        then:
        - id: hello1
          type: io.kestra.plugin.core.log.Log
          message: "Hello World!"
      - id: if2
        type: io.kestra.plugin.core.flow.If
        condition: "{{ inputs.if2 }}"
        then:
          - id: hello2
            type: io.kestra.plugin.core.log.Log
            message: "Hello World!"
      - id: if3
        type: io.kestra.plugin.core.flow.If
        condition: "{{ inputs.if3 }}"
        then:
          - id: hello3
            type: io.kestra.plugin.core.log.Log
            message: "Hello World!"
      - id: hello4
        type: io.kestra.plugin.core.log.Log
        message: "Hello World!"
      - id: hello5
        type: io.kestra.plugin.core.log.Log
        message: "Hello World!"
      - id: hello6
        type: io.kestra.plugin.core.log.Log
        message: "Hello World!"
      - id: hello7
        type: io.kestra.plugin.core.log.Log
        message: "Hello World!"
      - id: hello8
        type: io.kestra.plugin.core.log.Log
        message: "Hello World!"
      - id: hello9
        type: io.kestra.plugin.core.log.Log
        message: "Hello World!" 
```
This issue is causing a major outage for us and the only solution is to wake up really early and manually retrigger everything until it executes.. which may be 2-5+ retries. Force Rerun does not react to this either, have to kill and re-execute.

### Environment

- Kestra Version: 0.20.2 - Cloud
