### ISSUE TITLE
Trigger workflow based on the last day of the month

### ISSUE THREAD

**Issue by nikolicdragoslav** [kestra-io/kestra#6388]
### Feature description

Hello, 

Is it possible to support setting dayInMonth as LAST, for example, without setting dayOfWeek, because I don't want to aim for a specific day of the week, I would like to have a possibility of just choosing FIRST or LAST day in the month?

example:
```
- id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 11 * * 1"
    conditions:
      - type: io.kestra.plugin.core.condition.DayWeekInMonthCondition
        date: "{{ trigger.date }}"
        # dayOfWeek: "MONDAY"
        dayInMonth: "LAST"
```

Thank you,
Dragoslav
