### ISSUE TITLE
Magic Rewrite feature in the editor

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#6405]
The user will need to hit `Save` after the change to confirm the changes are OK. Even later, the user can roll back to a previous revision if needed.

![image](https://github.com/user-attachments/assets/d90fb178-ac15-43c9-9444-8267081d6d17)

Reproducer to see deprecated features:

```yaml
id: failure_alert
namespace: company.team

tasks:
  - id: send_alert
    type: io.kestra.plugin.notifications.slack.SlackExecution
    url: "{{ secret('SLACK_WEBHOOK') }}" # format: https://hooks.slack.com/services/xzy/xyz/xyz
    channel: "#general"
    executionId: "{{trigger.executionId}}"

triggers:
  - id: failed_prod_workflows
    type: io.kestra.plugin.core.trigger.Flow
    conditions:
      - type: io.kestra.plugin.core.condition.ExecutionStatusCondition
        in:
          - FAILED
          - WARNING
      - type: io.kestra.plugin.core.condition.ExecutionNamespaceCondition
        namespace: prod
        prefix: true
```
