### ISSUE TITLE
SyncFlow fails to deserialize the password field: Cannot deserialize value of type `java.lang.String` from Array value

### ISSUE THREAD

**Issue by ChristianLempa** [kestra-io/kestra#6410]
### Describe the issue

After updating Kestra 0.19.x to 0.20.6 I get the following error in the SyncFlow task, which fails with 
```
Illegal flow yaml: Cannot deserialize value of type `java.lang.String` from Array value (token `JsonToken.START_ARRAY`)
 at [Source: (StringReader); line: 14, column: 7] (through reference chain: io.kestra.core.models.flows.Flow["inputs"]->java.util.ArrayList[0]->io.kestra.core.models.flows.input.StringInput["defaults"])
```

This is my SyncFlow
```yaml
[...]
  - id: git
    type: io.kestra.plugin.git.SyncFlows
    gitDirectory: flows
    targetNamespace: production
    includeChildNamespaces: true
    delete: true
    url: https://git.home.clcreative.de/homelab/kestra
    branch: main
    username: xcad
    password: "{{ secret('GITLAB_TOKEN') }}"
    dryRun: false
[...]
```

### Environment

- Kestra Version: 0.20.6
