### ISSUE TITLE
The first scheduling interval is executed twice in backfills from the UI

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#6413]
### Describe the issue

reproducer:
```yaml
id: backfill_test
namespace: company.team

variables:
  file: yellow_tripdata_{{trigger.date ?? execution.startDate | date("yyyy-MM")}}.parquet

tasks:
  - id: label
    type: io.kestra.plugin.core.execution.Labels
    labels:
      file: "{{render(vars.file)}}"
      
  - id: log
    type: io.kestra.plugin.core.log.Log
    message: file https://d37ci6vzurychx.cloudfront.net/trip-data/{{render(vars.file)}}

triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: 0 8 1 * *
    description: at 8:00 AM on the 1st day of every month
```

![image](https://github.com/user-attachments/assets/82441fd4-589f-484e-b5ee-409ab67bb968)

![image](https://github.com/user-attachments/assets/38683433-d2d8-48a2-87b3-7cc39c2fe3b6)

### Environment

- Kestra Version: latest 0.20.6
