### ISSUE TITLE
Non required boolean is not showing up in the Execute modal

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#6444]
### Describe the issue

```yaml
id: repro_bool
namespace: company.team

inputs:
  - id: mybool
    type: BOOLEAN
    required: false
    defaults: false
    description: This will not show up in the UI at all unless you mark it as required

tasks:
  - id: return_null
    type: io.kestra.plugin.core.debug.Return
    format: "{{inputs}}"
```

![image](https://github.com/user-attachments/assets/d35d2549-0023-45c8-98cd-c1be9c371c1b)

### Environment

- Kestra Version: latest 0.20.6
