### ISSUE TITLE
Improve Execution Notifications plugins to allow passing custom payload

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#6457]
### Feature description

Add the ability to be able to get the `{{ errorLogs() }}` function inside of a Flow Trigger that runs when flows fail. This allows for instance wide error handling with useful errors inside of them.

From a user in Slack:
> I'm using a triggered Slack alert flow for all failed flows in my workspace as described in best practices [here](https://kestra.io/docs/administrator-guide/monitoring). Is there any way to get the new `{{ errorLogs() }}` pebble function from the v0.20 release into the trigger attributtes, so that my Slack alert flow can display them?  (without having to push it into outputs for every single flow)

**Comment by loicmathieu** [comment]
Better to use the `io.kestra.plugin.core.log.Fetch` task for that, the `errorLog()` function has been defined to load logs for the current execution only. There are RBAC considerations when loading logs from a different flow.

**Comment by Ben8t** [comment]
Agree with Loic, this one sounds like we need more info too. @wrussell1999 do you have the user name raising this need? I would like to have more details on the flow and corresponding trigger involved - reading the issue title "Improve Execution Notifications plugins to allow passing custom payload" it sounds like a broader subject around notification isn't?

**Comment by MarthaScheffler** [comment]
@Ben8t it's me :) 
here is the Slack link: https://kestra-io.slack.com/archives/C03FQKXRK3K/p1734105888969879
wanna take the discussion here or via Slack?

**Comment by Ben8t** [comment]
Ah great :)

Let's keep the discussion here as we have the proper issue!
Can you send me a sample flow definition where you have your Slack alert/trigger please? Just want to be sure to have understood the point here first

**Comment by MarthaScheffler** [comment]
My setup: I get a Slack alert for all flows that end up with either FAILED or WARNED in the respective namespace. prod alerts go to the prod alert channel, dev alerts go to the dev alert channel. However, the error message is a bit crude at the moment, I only managed to include in the Slack message which flow, execution_id, and where the link is to access the logs.

I would love to additionally display part of the error logs in the Slack message. I haven't yet managed to look more into the log.Fetch task, and if it would help me here. I thought that the new {{ errorLogs() }} pebble function could cover my needs, but it's not available via trigger.

my slack alert task:

````

id: slack_alert
namespace: dev.slack
description: Send an alert to a Slack channel

variables:
  env: "{{ envs.env == 'prod' ? '' : '(dev)' }}"

tasks:
      - id: send_alert
        type: io.kestra.plugin.notifications.slack.SlackIncomingWebhook
        url: "{{ secret('SLACK_WEBHOOK') }}" # https://hooks.slack.com/services/xzy/xyz/xyz
        # https://app.slack.com/block-kit-builder
        payload: |
          {
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": ":warning: {{ trigger.namespace ?? 'manual' }}.{{ trigger.flowId ?? 'triggered' }} - {{ trigger.state ?? 'MANUAL' }} {{ vars.env }} :warning:",
                  "emoji": true
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "The _{{ trigger.flowId ?? flow.id }}_ flow has ended with {{ trigger.state ?? 'MANUAL' }} on execution_id <http://localhost:8080/ui/executions/{{ trigger.namespace ?? flow.namespace }}/{{ trigger.flowId ?? flow.id }}/{{ trigger.executionId ?? execution.id }}/logs|*{{ trigger.executionId ?? execution.id }}*>"
                }
              },
              {
                "type": "divider"
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "plain_text",
                    "text": "Kestra {{ envs.env }} pod needs to be forwarded to localhost to be able to access the logs.",
                    "emoji": true
                  }
                ]
              }
            ]
          }

triggers:
  - id: failed_workflows
    type: io.kestra.plugin.core.trigger.Flow
    conditions:
      - type: io.kestra.plugin.core.condition.ExecutionStatus
        in:
          - FAILED
          - WARNING
      - type: io.kestra.plugin.core.condition.Or
        conditions:
          - type: io.kestra.plugin.core.condition.ExecutionNamespace
            # namespace will be substituted with prod by git flows
            namespace: dev
            prefix: true
          - type: io.kestra.plugin.core.condition.ExecutionNamespace
            namespace: system
            prefix: true

````

**Comment by Ben8t** [comment]
Thanks for the details, very clear now :)

The good thing with the [fetch.log task](https://kestra.io/plugins/core/tasks/log/io.kestra.plugin.core.log.fetch) is that you can provide the `trigger.executionId` to fetch corresponding logs (the task outputs to file uri in internal storage). Then you can probably use a `{{ read(outputs.fetch_log_task.uri) }}` inside you Slack payload. Let us know if that works for you

**Comment by MarthaScheffler** [comment]
It kind of works.
I had to add a transformation from ion to json, and then I could read the first error message. not the others though, as my conversion onto something readable only catches the first error. I will add my outputs as well, hoping for a hint, how I can do a better conversion :)

adjusted workflow:

````

id: slack_alert
namespace: dev.slack
description: Send an alert to a Slack channel

variables:
  env: "{{ envs.env == 'prod' ? '' : '(dev)' }}"

tasks:
      - id: get_error_logs
        type: io.kestra.plugin.core.log.Fetch
        level: WARN
        executionId: "{{ trigger.executionId ?? execution.id }}"
        namespace: "{{ trigger.namespace ?? 'manual' }}"
        flowId: "{{ trigger.flowId ?? 'triggered' }}"

      - id: read_error_logs
        type: io.kestra.plugin.serdes.json.IonToJson
        from: "{{ outputs.get_error_logs.uri }}"

      - id: send_alert
        type: io.kestra.plugin.notifications.slack.SlackIncomingWebhook
        url: "{{ secret('SLACK_WEBHOOK') }}" # https://hooks.slack.com/services/xzy/xyz/xyz
        # https://app.slack.com/block-kit-builder
        payload: |
          {
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": ":warning: {{ trigger.namespace ?? 'manual' }}.{{ trigger.flowId ?? 'triggered' }} - {{ trigger.state ?? 'MANUAL' }} {{ vars.env }} :warning:",
                  "emoji": true
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "The _{{ trigger.flowId ?? flow.id }}_ flow has ended with {{ trigger.state ?? 'MANUAL' }} on execution_id <http://localhost:8080/ui/executions/{{ trigger.namespace ?? flow.namespace }}/{{ trigger.flowId ?? flow.id }}/{{ trigger.executionId ?? execution.id }}/logs|*{{ trigger.executionId ?? execution.id }}*>"
                }
              },
              {
                "type": "divider"
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "plain_text",
                    "text": "Kestra {{ envs.env }} pod needs to be forwarded to localhost to be able to access the logs.",
                    "emoji": true
                  }
                ]
              },
              {
                "type": "divider"
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "plain_text",
                    # this only gets the first error
                    "text": "{{ outputs.get_error_logs.size == 0 ? 'details see logs' : json(read(outputs.read_error_logs.uri)).message }}",
                    "emoji": true
                  }
                ]
              }
            ]
          }

triggers:
  - id: failed_workflows
    type: io.kestra.plugin.core.trigger.Flow
    conditions:
      - type: io.kestra.plugin.core.condition.ExecutionStatus
        in:
          - FAILED
          - WARNING
      - type: io.kestra.plugin.core.condition.Or
        conditions:
          - type: io.kestra.plugin.core.condition.ExecutionNamespace
            # namespace will be substituted with prod by git flows
            namespace: dev
            prefix: true
          - type: io.kestra.plugin.core.condition.ExecutionNamespace
            namespace: system
            prefix: true

````

output of the get_error_logs task:

![image](https://github.com/user-attachments/assets/ef7d4487-c2e6-4422-ac0c-4c28f5efb8ee)

**Comment by MarthaScheffler** [comment]
@Ben8t is there any way to pull the logs in a usable format, no trouble with special signs and formatting?

I have been struggling for some time now, using the log.Fetch task, and adding things like `| replace({'"': '', '{': '', '}': ''})` to get the logs displayed, but have to give up on colorful logs. how do I get these into Slack?? I don't mind if the color gets removed from the ERROR, I just want to get a Slack alert in the first place!

![image](https://github.com/user-attachments/assets/4ec2cb29-8699-4192-8dcf-5ac608067e3c)

**Comment by arthur-t-w-mills** [comment]
My colleague (Michael Abounabhan - will link his GitHub account when I find it :) ) recently worked on this exact issue. For anyone looking to get around this problem, this was the solution that Michael put in place. The key code here that got us over the line versus what's above is:
```
    from: "{{ outputs.get_error_logs.uri }}"
    newLine: false
```
and
```
 {% set errorLogs = fromJson(read(outputs.read_error_logs.uri)) %}
````

---

Full Flow config:

```yaml
id: dbt_failure_notification
namespace: alerts

concurrency:
    limit: 5
    behavior: QUEUE

triggers:
  - id: dbt_job_failure
    type: io.kestra.plugin.core.trigger.Flow
    states: 
      - FAILED    
    preconditions:
      id: dbt_flows
      where:
        - id: flow_ids_containing_dbt
          filters:
            - field: FLOW_ID
              type: CONTAINS
              value: "dbt"

tasks:
  - id: get_error_logs
    type: io.kestra.plugin.core.log.Fetch
    level: ERROR
    executionId: "{{ trigger.executionId ?? execution.id }}"
    namespace: "{{ trigger.namespace ?? 'manual' }}"
    flowId: "{{ trigger.flowId ?? 'triggered' }}"

  - id: read_error_logs
    type: io.kestra.plugin.serdes.json.IonToJson
    from: "{{ outputs.get_error_logs.uri }}"
    newLine: false

  - id: slack_failure_alert
    type: io.kestra.plugin.notifications.slack.SlackIncomingWebhook
    url: https://hooks.slack.com/services/your_slack_app_hook_id_here
    payload: |
            {% set errorLogs = fromJson(read(outputs.read_error_logs.uri)) %}
            {
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": ":warning: dbt Job Failed on Flow \"{{ errorLogs[0].flowId }}\"",
                    "emoji": true
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": ">:open_file_folder: *Namespace:*\n>{{ errorLogs[0].namespace }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": ">:gear: *Flow:*\n>{{ errorLogs[0].flowId }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": ">:label: *Execution ID:*\n>{{ errorLogs[0].executionId }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": ">:warning: *State:*\n>{{ errorLogs[0].level }}"
                    }
                  ]
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {           
                      "type": "mrkdwn",
                      "text": ">:x: *Error Logs:*\n"
                    }
                },
                {% for messages in errorLogs %}
                {% set msg = messages.message | replace({'\u001B[31m': '', '\u001B[0m': '', '[31m': '', '[0m': ''}) | toJson %}
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "```{{ msg | slice(1, msg.length - 1) }}```"
                    }
                },
                {% endfor %}
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":point_right: *See full run details in Kestra:*"
                  },
                  "accessory": {
                    "type": "button",
                    "text": {
                      "type": "plain_text",
                      "text": "Open run in Kestra",
                      "emoji": true
                    },
                    "url": "http://your_url_or_ip_here/ui/executions/{{ errorLogs[0].namespace }}/{{ errorLogs[0].flowId }}/{{ errorLogs[0].executionId }}",
                    "style": "danger"
                  }
                }
              ]
            }
```
