### ISSUE TITLE
Explore how to fill the default input value in Backfills by the input value set within a schedule

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#6458]
### Feature description

Repro:
```yaml
id: backfill_test
namespace: company.team

inputs:
  - id: taxi
    type: SELECT
    displayName: Select taxi type
    values: [yellow, green]
    defaults: green

variables:
  file: yellow_tripdata_{{trigger.date ?? execution.startDate | date("yyyy-MM")}}.parquet

tasks:
  - id: label
    type: io.kestra.plugin.core.execution.Labels
    labels:
      file: "{{render(vars.file)}}"
      
  - id: log
    type: io.kestra.plugin.core.log.Log
    message: file https://d37ci6vzurychx.cloudfront.net/trip-data/{{render(vars.file)}}

triggers:
  - id: green_schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 9 1 * *"
    inputs:
      taxi: green

  - id: yellow_schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 17 1 * *"
    inputs:
      taxi: yellow
```

For now, backfill for the yellow_schedule will have the default value to be green - would be cool to make it "yellow" as defined by the trigger input.

![image](https://github.com/user-attachments/assets/b91dc2ac-4123-4d97-85b0-6a2b99405ce9)
