### ISSUE TITLE
Add markdown formatting to inputs values/display name + increase allowed displayName to be more than 64 characters 

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#6470]
### Describe the issue

- [x] BACKEND: Display name is restricted to 64 characters which seems limiting - we should remove this limit, there are no technical reasons to have that limit

<details>
<summary>Screenshots</summary>

![image](https://github.com/user-attachments/assets/c7d6c8f6-9c5a-4c2b-a8b2-48ea63f06715)

</details>

---

- [x] FRONTEND: Display name doesn't have markdown rendering yet - it would be great to add it, the same way as GitHub is able to render markdown in issue titles etc.

<details>
<summary>Screenshots</summary>

![image](https://github.com/user-attachments/assets/6c55f095-f870-4072-9afd-25e8577bc133)

</details>

---

- [x] FRONTEND: Input values also lack markdown formatting — this might be a bit more tricky as we use element+ for the element. If not feasible, we'll skip this part.

<details>
<summary>Screenshots</summary>

![image](https://github.com/user-attachments/assets/e07b27ce-f707-43be-b17e-2cc6fb567334)

</details>

## Context

We were planning to leverage Apps to let students submit homework assignments, and this shows some unexpected limitations of display names. 

## Reproducer

```yaml
id: homework
namespace: zoomcamp

inputs:
  - id: first
    type: SELECT
    displayName: 1) Uncompressed file size of `yellow_tripdata_2020-12.csv`
    description: |
      1) Within the execution for `Yellow` Taxi data for the year `2020` and month `12`: what is the uncompressed file size (i.e. the output file `yellow_tripdata_2020-12.csv` of the `extract` task)?
    required: true
    values:
      - 128.3 MB
      - 134.5 MB
      - 364.7 MB
      - 692.6 MB

  - id: second
    type: SELECT
    displayName: 2) Task run state of bq_green_tripdata for yellow taxi input
    description: |
      2) What is the task run state of tasks bq_green_tripdata, bq_green_tmp_table and bq_merge_green when you run the flow with the `taxi` input set to value `yellow`?
    required: true
    values:
      - SUCCESS
      - FAILED
      - SKIPPED
      - CANCELED

  - id: third
    type: SELECT
    displayName: |
      3) How to deal with table schema in the GCP ingestion pipeline?
    required: true
    values:
      - We don't define the schema at all because this is a data lake after all
      - We let BigQuery autodetect the schema
      - Kestra automatically infers the schema from the extracted data
      - We explicitly define the schema in the tasks that create external source tables and final target tables

  - id: fourth
    type: SELECT
    displayName: |
      4) How does Kestra handles backfills in the scheduled flow?
    required: true
    values:
      - You need to define backfill properties in the flow configuration
      - You have to run CLI commands to backfill the data
      - You can run backfills directly from the UI from the Flow Triggers tab by selecting the time period
      - Kestra doesn't support backfills
  
  - id: fifth
    type: SELECT
    displayName: 5) CRON to run flow at 09:00 UTC on the first day of every month
    description: |
      5) Which of the following CRON expressions schedules a flow to run at 09:00 UTC on the first day of every month?
    required: true
    values:
      - 0 9 1 * *
      - 0 1 9 * *
      - 0 9 * * *
      - 1 9 * * *
        
  - id: sixth
    type: SELECT
    displayName: |
      6) How to set timezone to New York in a Schedule trigger?
    required: true
    values:
      - Add a `timezone` property set to `EST` in the `Schedule` trigger configuration  
      - Add a `timezone` property set to `America/New_York` in the `Schedule` trigger configuration
      - Add a `timezone` property set to `UTC-5` in the `Schedule` trigger configuration
      - Add a `location` property set to `New_York` in the `Schedule` trigger configuration

  - id: email
    type: EMAIL
    displayName: Your email
    required: true

tasks:
  - id: submission_to_gsheets
    type: io.kestra.plugin.core.log.Log
    message: homework submission {{ inputs }}
```

### Environment

- Kestra Version: develop
