### ISSUE TITLE
fetchType: "FETCH_ONE" in postgresql.Trigger creates flow execution eventhough sql statement does not return a result

### ISSUE THREAD

**Issue by gvanderweerd** [kestra-io/kestra#6482]
### Describe the issue

I recently upgraded my kestra version from 17 to 20. Previously I had a flow trigger like this. Now fetch & fetchOne are depricated so I want to switch to fetchType: "FETCH_ONE". However now the flow creates an execution regardless if there is a result. Now the script crashes every 30 seconds on "{{ trigger.row }}" because row is not defined. How can I ensure that the flow is only triggered if there is actually a result in "table" like it was on the previous version?

```yaml
tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: "{{ trigger.row }}"
triggers:
  - id: watchNewConnections
    type: io.kestra.plugin.jdbc.postgresql.Trigger
    interval: "PT30S"
    url: "{{ globals['encast-db-url'] }}"
    username: "{{ globals['db-user'] }}"
    password: "{{ globals['db-pass'] }}"
    sql: "SELECT * FROM table
      WHERE data_provider IS NOT NULL;"
    fetchType: "FETCH_ONE"
```
The behaviour now outputs this eventhough the query inside the trigger does not return a result. Then the flow crashes because trigger.row is not defined.
```json
{
  "size": 1
}
```
![](https://files.slack.com/files-pri/T01JX6XH5KN-F0852RH92T0/screenshot_2024-12-16_at_12.41.20.png)

### Environment

- Kestra Version: develop
