### ISSUE TITLE
`waitFor` doesn't work in Flowable

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#6494]
### Describe the issue

Here is a reproducer with `Switch`: the `outputs.loop` is not accessible (I also tested with `If` task, got the same behavior):

```
id: my_loop
namespace: io.kestra.examples

inputs:
  - id: string
    type: STRING
    required: true
    defaults: 'FIRST'

tasks:

  - id: case
    type: io.kestra.plugin.core.flow.Switch
    value: "{{ inputs.string }}"
    cases:
      FIRST:
      - id: loop
        type: io.kestra.plugin.core.flow.WaitFor
        condition: "{{ outputs.loop }}"
        tasks:
          - id: logLoop
            type: io.kestra.plugin.core.log.Log
            message: "Loop = {{ outputs.loop }}"
          - id: dodo
            type: io.kestra.plugin.core.flow.Sleep
            duration: 5
```

![image](https://github.com/user-attachments/assets/9b87a622-e154-4c0b-b7cf-24e26ecb71c9)

Yet, at the end of the flow execution the outputs is here

![image](https://github.com/user-attachments/assets/f7ce20a4-48bd-4eec-990b-bc8923bd7c8a)

### Environment

- Kestra Version: 0.20
