### ISSUE TITLE
Find a better way to handle Outputs download/preview buttons when Execution outputs have been purged

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#6514]
Small demo: https://share.descript.com/view/BRjUMUZfZOy

The easiest reproducer:

```yaml
id: download
namespace: company.team

tasks:
  - id: extract
    type: io.kestra.plugin.core.http.Download
    uri: https://huggingface.co/datasets/kestra/datasets/raw/main/csv/orders.csv
  
  - id: purge
    type: io.kestra.plugin.core.storage.PurgeCurrentExecutionFiles
```

Purging old execution data is quite common so it would be cool if we would handle this use case better: **perhaps we don't show the download/preview buttons** at all if the file is 0 B (when it doesn't exist)? 

![image](https://github.com/user-attachments/assets/f6449ed6-1780-4bf8-8d37-cab8e6d22201)
