### ISSUE TITLE
Add a flowable TaskGroup allowing to include subflow's tasks within the same parent execution without copy

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#6518]
## Templates and their deprecation
Initially, Kestra had a concept of Templates that provided largely equivalent functionality as subflows but could not be parametrized with inputs as subflows could. Due to the huge amount of functionality overlap between Templates and Subflows, we had users asking virtually every week in Slack: _"What is the difference between those two concepts? They seem to do the same? When to use one vs the other?"_.

Templates also suffered from multiple issues:
- **Security**: if the task within a template returns an OAuth token, each flow calling that template would be able to fetch that auth token 
- **Privacy**: all outputs generated within a template would be accessible to the consumer — this is not always desirable. Subflows solve that by explicitly returning outputs when needed/desirable. 
- **No versioning**: templates didn't have revision history the same way as flows/subflows do
- **Skewed topology view**: tasks from the templates would be copied over to the parent instead of being linked between the parent-child. As a result, by looking at the topology alone, you could not tell which tasks came from a template and which were defined directly in the flow.
- **Task ID conflicts**: for the same reason as above with the topology, since the tasks would be directly copied over, if your main flow would have some tasks with the same IDs, this would break the flow due to task ID conflicts.
- **No dependency tracking**: you could not track which flows used a given template. This was mainly Code-Copy-Pasta rather than a true API-first concept as subflows are. 

For the above reasons, Templates were [deprecated in kestra v0.11](https://kestra.io/docs/migration-guide/0.11.0/templates) in August 2023. Since then, we have recommended subflows for all use cases requiring reusable workflow logic.

## New use cases

Subflows have solved many Template problems but there are some use cases left unaddressed:
1. **Extra executions** — since subflow tasks are not just copied but executed from another flow, the number of executions can easily multiply, making them a bit more complex to manage for some users
2. **Restarts** — restarting a parent flow with some task that failed in a subflow execution will create an entirely new execution for the subflow. Some users have a reasonable expectation that restarting the parent with some tasks coming from a subflow would only restart the failed task runs from that subflow. 
3. **Billing/tracking** — some users track plugin metrics (e.g. BigQuery Bytes processed etc.) on a namespace level. Since each subflow can be used in flows from various namespaces, this can make tracking more difficult.
4. **RBAC** — some RBAC can get quite complex when e.g. task t1 from flow f1 uses a secret from namespace n1, and that subflow is called from parent flow f2 in namespace n2. Should this secret be retrieved from n1 or from n2? Subflow would use n1, but the new Task Group implementation shown below would use 

## Proposal: new TaskGroup task

Let's say we have this flow `f1`:
```yaml
id: f1
namespace: n1

tasks:
  - id: t1
    type: io.kestra.plugin.core.debug.Return
    format: using vars from n1 {{ namespace.myvar }}

  - id: t2
    type: io.kestra.plugin.core.debug.Return
    format: using secrets from n1 {{ secret('GCP_CREDS') }}

  - id: t3
    type: io.kestra.plugin.core.debug.Return
    format: value3

outputs:
  - id: myoutput
    type: STRING
    value: "{{ outputs.t3.value }}"
```

We call it in flow `f2` as a task group:

```yaml
id: f2
namespace: n2

tasks:
  - id: first_task
    type: io.kestra.plugin.core.log.Log
    message: value1

  - id: group
    type: io.kestra.plugin.core.flow.TaskGroup
    namespace: n1
    flowId: f1

  - id: log
    type: io.kestra.plugin.core.log.Log
    message: "{{ outputs.group.myoutput }}"
```

Calling `f1` subflow as a task group effectively has the same effect as we would copy the tasks from the subflow but render them so that they use secrets/KV from the parent flow's namespace n2 + the topology view will show them as a subflow directly expanded and visible in the main flow `f2` with a clear tracking that their underlying task definition comes from flow `f1`:

```yaml
id: f2
namespace: n2

tasks:
  - id: first_task
    type: io.kestra.plugin.core.log.Log
    message: value1

  - id: t1
    type: io.kestra.plugin.core.debug.Return
    format: using vars from n2 {{ namespace.myvar }}

  - id: t2
    type: io.kestra.plugin.core.debug.Return
    format: using secrets from n2 {{ secret('GCP_CREDS') }}

  - id: t3
    type: io.kestra.plugin.core.debug.Return
    format: value3

  - id: log
    type: io.kestra.plugin.core.log.Log
    message: "{{ outputs.t3.value }}"
```

### Handling task IDs

Within the parent flow, we will prefix all subflow's tasks with the TaskGroup's task ID.  (implementation detail where @tchiotludo can share more info)

### Removal of Templates

Given how closely TaskGroup functionality resembles Templates (but without Template's limitations), we will remove Templates entirely from the code base. Under the hood, we will be able to reuse a lot of that code.

Users who still rely on Templates today, 1.5 years after their deprecation, will need to migrate to subflows — with TaskGroup, that migration will be straightforward. 

### Documentation of best practices

Users will need to be aware that outputs must be explicitly exposed within the subflow in order to access them within a parent, even with TaskGroup — the pattern is `{{ outputs.task_group_id.output_id }}`.

### Large execution context with too deep nesting 

For now, this design assumes we will infinitely render all tasks, i.e. if you have this chain: 

1. flow1 with 10 tasks and the last is a TaskGroup based on flow2 
2. flow2 also has 10 tasks with the last task being a TaskGroup for flow3
3. flow3 also has 10 tasks with the last task being a TaskGroup for flow4
4. ...

In the first iteration, we won't limit how far the user can go with a task group being able to be expanded to see another task group and another, but we need to highlight in the plugin docs of this task + in the Best Practices docs that user should be mindful of not using TaskGroup with too deep nesting as in contrast to Subflows creating new executions, TaskGroup tasks are executed in the same execution which can break your instance if you try to run hundreds of tasks within a single flow.
