### ISSUE TITLE
Templated flow with eachSequential will end if a child taks fails

### ISSUE THREAD

**Issue by nsteinmetz** [kestra-io/kestra#654]
### Expected Behavior

With a flow and a template as below, and assuming the `getDevicesList` will provide 3+ results, if loop fails on 2nd value, the 3rd and latter value are never run. Child tasks stops and flow is marked as failed.

### Actual Behaviour

Flow is marked as failed and child task for 3rd and latter value is never executed

### Steps To Reproduce

Use a flow with child tasks and using a template as described below.

### Environment Information

- Kestra Version: 0.5.0-beta+ (last develop version on 08/07/2022), using lite version
- Operating System (OS / Docker / Kubernetes): Docker
- Java Version (If not docker):

### Example flow

Template:

```yml
id: periodic-aggregations
namespace: corp.iot.ts
tasks:
  - id: getDevicesList
    type: io.kestra.plugin.fs.http.Request
    uri: "https://{{ parent.outputs.args.api_url }}/v1/operations/list_flowboxes?token={{ parent.outputs.args.operation_token }}"
  - id: each_sequential
    type: io.kestra.core.tasks.flows.EachSequential
    tasks:
      - id: request
        type: io.kestra.plugin.fs.http.Request
        body: |
          [ '{{ parent.outputs.args.read_token }}' '{{ parent.outputs.args.write_token }}' {  'company_customer' '{{ json(taskrun.value).compay_customer_id }}' 'customer' '{{ json(taskrun.value).customer_id }}' 'building' '{{ json(taskrun.value).building_id }}' 'zone' '{{ json(taskrun.value).zone_id }}' } '{{ parent.outputs.args.execution_date }}' ] @company/iot/{{ parent.outputs.args.aggregation_period }}_aggregation
        method: POST
        uri: "{{ parent.outputs.args.url }}"
      - id: use-output
        type: io.kestra.core.tasks.debugs.Return
        format: Code {{ outputs.request[taskrun.value].code }} with message {{ outputs.request[taskrun.value].body }}
    value: "{{ json(outputs.getDevicesList.body).devices }}"
```

Flow:

```yml
id: flowbox-staging-daily-aggregation
namespace: flovea.flowbox.warp10
description: daily aggregation on staging
revision: 3
variables:
  aggregation_period: daily
  api_url: XXX
  execution_date: "{{ schedule.date ?? execution.startDate }}"
  operation_token: XXX
  read_token: XXX
  url: XXX
  write_token: XXX
tasks:
  - id: task1
    type: io.kestra.core.tasks.flows.Template
    namespace: corp.iot.ts
    args:
      aggregation_period: "{{ vars.aggregation_period }}"
      api_url: "{{ vars.api_url }}"
      execution_date: "{{ vars.execution_date }}"
      operation_token: "{{ vars.operation_token }}"
      read_token: "{{ vars.warp10_read_token }}"
      url: "{{ vars.url }}"
      write_token: "{{ vars.write_token }}"
    templateId: periodic-aggregations
```

**Comment by nsteinmetz** [comment]
It also fails without templates:


```yml
id: loop-api-without-templates
namespace: nst.test
revision: 2
variables:
  aggregation_period: daily
  api_url: XXX
  execution_date: "{{ schedule.date ?? execution.startDate }}"
  operation_token: XXX
  read_token: XXX
  url: XXX
  write_token: XXX
tasks:
  - id: getDevicesList
    type: io.kestra.plugin.fs.http.Request
    uri: https://{{ vars.api_url }}/v1/operations/list_flowboxes?token={{ vars.operation_token }}
  - id: each_sequential
    type: io.kestra.core.tasks.flows.EachSequential
    tasks:
      - id: request
        type: io.kestra.plugin.fs.http.Request
        body: |
          [ '{{ vars.read_token }}' '{{ vars.write_token }}' {  'company_customer' '{{ json(taskrun.value).company_customer_id }}' 'customer' '{{ json(taskrun.value).customer_id }}' 'building' '{{ json(taskrun.value).building_id }}' 'zone' '{{ json(taskrun.value).zone_id }}' } '{{ vars.execution_date }}' ] @company/iot/{{ vars.aggregation_period }}_aggregation
        method: POST
        uri: "{{ vars.url }}"
      - id: use-output
        type: io.kestra.core.tasks.debugs.Return
        format: Code {{ outputs.request[taskrun.value].code }} with message {{ outputs.request[taskrun.value].body }}
    value: "{{ json(outputs.getDevicesList.body).flowboxes }}"
```

**Comment by nsteinmetz** [comment]
Solution is to insert a `AllowFailure` in between and access to the output of `value` of the `eachSequential` flow via `parent.taskrun.value`

```yml
id: loop-api-without-templates
namespace: nst.test
revision: 2
variables:
  aggregation_period: daily
  api_url: XXX
  execution_date: "{{ schedule.date ?? execution.startDate }}"
  operation_token: XXX
  read_token: XXX
  url: XXX
  write_token: XXX
tasks:
  - id: getDevicesList
    type: io.kestra.plugin.fs.http.Request
    uri: https://{{ vars.api_url }}/v1/operations/list_flowboxes?token={{ vars.operation_token }}
  - id: each_sequential
    type: io.kestra.core.tasks.flows.EachSequential
    tasks:
      - id: allowFailure
        type: io.kestra.core.tasks.flows.AllowFailure
        tasks:
          - id: request
            type: io.kestra.plugin.fs.http.Request
            body: |
              [ '{{ vars.read_token }}' '{{ vars.write_token }}' {  'company_customer' '{{ json(parent.taskrun.value).company_customer_id }}' 'customer' '{{ json(parent.taskrun.value).customer_id }}' 'building' '{{ json(parent.taskrun.value).building_id }}' 'zone' '{{ json(parent.taskrun.value).zone_id }}' } '{{ vars.execution_date }}' ] @company/iot/{{ vars.aggregation_period }}_aggregation
            method: POST
            uri: "{{ vars.url }}"
          - id: use-output
            type: io.kestra.core.tasks.debugs.Return
            format: Code {{ outputs.request[parent.taskrun.value].code }} with message {{ outputs.request[parent.taskrun.value].body }}
    value: "{{ json(outputs.getDevicesList.body).devices  #}}"
```
