### ISSUE TITLE
Hugging Face not working + no icon

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#6559]
### Describe the issue

1. Basic flow doesn't work:
```yaml
id: test
namespace: test

tasks:
  - id: hf
    type: io.kestra.plugin.huggingface.Inference
    model: cardiffnlp/twitter-roberta-base-sentiment-latest
    apiKey: XXXX
    inputs: "I'm doing well today!"
```
![image](https://github.com/user-attachments/assets/5622057a-1789-44be-bbc6-f5efc08874b5)

2. The icon is not showed in topology
![image](https://github.com/user-attachments/assets/4b514c19-e726-4287-a448-e4392b05f3cf)

### Environment

- Kestra Version: develop
