### ISSUE TITLE
Add an Export To Excel / CSV Feature

### ISSUE THREAD

**Issue by johnkm516** [kestra-io/kestra#6592]
### Feature description

There are many use cases in which I would like to export Kestra data, for record keeping / audits, or to simply export the data and create a spreadsheet from it for a ToDo list. It's useful for reporting as well, where I can export the data to excel which is accessible by everyone, even if they're not a Kestra user. 

Therefore, it would be great if there was an export to csv / excel feature in the three main tabs : 
Flows, Executions, Administration - Triggers. 

The export feature would simply export the entire dataset (not paginated, Executions could be hundreds of thousands of rows) into a single CSV.

**Comment by ManojTauro** [comment]
Hi @MilosPaunovic I would like work on this issue.

**Comment by MilosPaunovic** [comment]
Sure, you can go ahead and open a PR, just be aware that this will also have to include some work on the BE side, also. Is that alright with you?

**Comment by Ben8t** [comment]
At first sight, that sounds like a Kestra App (introduced in 0.20) and a system flow; something like this:

```yaml
id: export_meta_to_excel
namespace: system

inputs:
  - id: table
    type: ENUM
    values:
      - flows
      - executions
      - audit_logs
      - triggers

tasks:
  - id: query
    type: io.kestra.plugin.jdbc.postgresql.Query
    sql: SELECT * FROM kestra.{{ inputs.table}}
    fetchType: STORE

  - id: export
    type: io.kestra.plugin.serdes.excel.IonToExcel
    from: "{{ outputs.query.uri }}"
```

Exposed through an Apps so user can export whatever table wanted (flow above is draft/idea). @johnkm516 is it something you're up to use this way?
