### ISSUE TITLE
Add always (or finally) tasks that run at the end regardless of the final state — useful for cleanup tasks

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#6649]
### Feature description

Internal use case: shut down Docker containers after QA tasks are finished

Possible syntax:

```yaml
id: always_example
namespace: company.team

tasks:
  - id: fail
    type: io.kestra.plugin.core.execution.Fail
    errorMessage: Test downstream tasks

errors:
  - id: send_alert
    type: io.kestra.plugin.core.log.Log
    message: alert on failure

always:
  - id: cleanup_task
    type: io.kestra.plugin.core.log.Log
    message: cleaning up resources
```

Later on, we can add the same concept within flowable tasks that currently support `errors`
