### ISSUE TITLE
A flow with an "if" where the only task in the "then" path is disabled seems to run forever

### ISSUE THREAD

**Issue by bertusk** [kestra-io/kestra#6658]
### Describe the issue

Probably a bit of a edge case but, this flow seems to run forever or at least for a very long time. 
When the `disabled: true` is removed the flow runs normally.
 
```
id: myflow
namespace: company.team

variables:
  numeric_variable: 42

tasks:
  - id: if
    type: io.kestra.plugin.core.flow.If
    condition: "{{ vars.numeric_variable > 0 }}"
    then:
      - id: log1
        disabled: true
        type: io.kestra.plugin.core.log.Log
        message: Log 1
```

### Environment

- Kestra Version: 0.20.10
