### ISSUE TITLE
RunIf Condition Not Working in Filesystem Tasks

### ISSUE THREAD

**Issue by fabioglopes** [kestra-io/kestra#6689]
### Describe the issue

While attempting to use the runIf condition in tasks under the filesystem category, it appears the condition is not being evaluated as expected. The tasks run regardless of the specified condition, or the condition is ignored entirely.

Steps to Reproduce:

Configure a task under the filesystem with a runIf condition.
Set up a scenario where the condition evaluates to false.
Execute the task.
Expected Behavior:
The task should only run if the runIf condition evaluates to true.

Actual Behavior:
The task runs regardless of the condition.

```
id: fabio_test_runif_file_system
namespace: gierd.test
description: "Simple flow to log output based on runIf condition"

inputs:
  - id: scripts_to_run
    type: MULTISELECT
    required: true
    values:
      - "orders"
      - "carriers"
      - "transactions"
    defaults: ["orders"]

tasks:
  - id: fileSystem
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      - id: log_orders
        type: io.kestra.plugin.scripts.ruby.Commands
        commands:
          - "ruby -e \"puts 'Logging for orders task'\""
        runIf: "{{ inputs.scripts_to_run contains 'orders' }}"

      - id: log_carriers
        type: io.kestra.plugin.scripts.ruby.Commands
        commands:
          - "ruby -e \"puts 'Logging for carriers task'\""
        runIf: "{{ inputs.scripts_to_run contains 'carriers' }}"

      - id: log_transactions
        type: io.kestra.plugin.scripts.ruby.Commands
        commands:
          - "ruby -e \"puts 'Logging for transactions task'\""
        runIf: "{{ inputs.scripts_to_run contains 'transactions' }}"
```

### Environment

- Kestra Version: 0.20.7
