### ISSUE TITLE
Fix JSON display in Topology view

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#6696]
### Describe the issue

Original user flow:

```yaml
id: mta
namespace: io.connect
tasks:
  - id: mta-s-1
    type: io.kestra.plugin.ioconnect.Invoke
    description: MTA Step 1
    method: getNextLayout
    nextLayoutDef: '{"groupdef":[{"type": "group", "children": [{"type":"window", "appName": "Motor Edit Client"}]},{"type": "group", "children": [{"type":"window", "appName": "Home Edit Client"} ]}]}'
    previousStep: 1
```

The same JSON string is displayed in the topology with extra escaping slashes:
```yaml
 "{\"groupdef\":[{\"type\": \"group\", \"children\": [{\"type\":\"window\", \"appName\": \"Motor Edit Client\"}]},{\"type\": \"group\", \"children\": [{\"type\":\"window\", \"appName\": \"Home Edit Client\"} ]}]}"
```

We should find a way to display the original string the same way in topology property box as in the code editor, this may need to change the property box to code editor box which could be hard unless the property is JSON instead of string

### Environment

- Kestra Version: develop
