### ISSUE TITLE
`outputFiles` adds a random prefix to file names

### ISSUE THREAD

**Issue by guslipkin** [kestra-io/kestra#6703]
### Describe the issue

When using `outputFiles` in a task, it prefixes my file names with a random string. My later tasks may depend on specific file names such as `YYYY_MM_DD.csv` and thus adding a prefix to the file name is difficult to work with.

For example, here we save a file to `tmp/cyl={{taskrun.value}}/part-0.parquet`. However, in Kestra, that path becomes `kestra:///path/random_folder_names/random-prefix-part0.parquet`.

```
id: myflow-copy
namespace: company.team

tasks:
  - id: query_parallel
    type: io.kestra.plugin.core.flow.ForEach
    values: "[4,6,8]"
    concurrencyLimit: 0
    tasks:
      - id: query
        type: io.kestra.plugin.scripts.shell.Commands
        taskRunner:
          type: io.kestra.plugin.scripts.runner.docker.Docker
        namespaceFiles:
          enabled: true
        commands:
          - mkdir -p tmp/cyl={{taskrun.value}}
          - touch tmp/cyl={{taskrun.value}}/part-0.parquet
        outputFiles:
          - "tmp/**/*.parquet"

  - id: log_combine_results
    type: io.kestra.plugin.core.log.Log
    message: "{{ outputs.query }}"
```

### Environment

- Kestra Version: open source
