### ISSUE TITLE
`outputFiles` drops folder structure

### ISSUE THREAD

**Issue by guslipkin** [kestra-io/kestra#6704]
### Describe the issue

If I have a task that creates a file with a specific folder structure, such as an Arrow dataset, then the intermediate folder structure is dropped and only the file itself is made available in later tasks. Sometimes that folder structure is very important and it should be kept.

A discussion about this in the Kestra Slack can be found here: https://kestra-io.slack.com/archives/C03FQKXRK3K/p1736048596068889

For example, here we save a file to `tmp/cyl={{taskrun.value}}/part-0.parquet`. However, in Kestra, that path becomes `kestra:///path/random_folder_names/random-prefix-part0.parquet`.

```
id: myflow-copy
namespace: company.team

tasks:
  - id: query_parallel
    type: io.kestra.plugin.core.flow.ForEach
    values: "[4,6,8]"
    concurrencyLimit: 0
    tasks:
      - id: query
        type: io.kestra.plugin.scripts.shell.Commands
        taskRunner:
          type: io.kestra.plugin.scripts.runner.docker.Docker
        namespaceFiles:
          enabled: true
        commands:
          - mkdir -p tmp/cyl={{taskrun.value}}
          - touch tmp/cyl={{taskrun.value}}/part-0.parquet
        outputFiles:
          - "tmp/**/*.parquet"

  - id: log_combine_results
    type: io.kestra.plugin.core.log.Log
    message: "{{ outputs.query }}"
```

### Environment

- Kestra Version: open source

**Comment by anna-geller** [comment]
similar to https://github.com/kestra-io/kestra/issues/6703#issuecomment-2658046989, I'd tend to close the issue as this is the way kestra works — each task is fully independent + isolated (tasks share nothing other than declaratively/explicitly passing files) and there is no shared disk shared between files, unless you would use worker groups that provides stateful workers but this is an EE feature. 

if you need to e.g. do something with that path like writing to S3, best to do that directly from that script task 

if you need an explicit path, you can also return that path explicitly:

```yaml
outputFiles:
  - mydir/subdir/myfile.parquet
``` 

then, in another task, access it: "{{ outputs.query.outputFiles['mydir/subdir/myfile.parquet'] }}"

it seems that what you are trying to do is a stateful pattern of dumping an entire directory of files and persisting them to a worker. this works if you add a worker group key:

```yaml
id: myflow-copy
namespace: company.team

tasks:
  - id: query_parallel
    type: io.kestra.plugin.core.flow.ForEach
    values: "[4,6,8]"
    concurrencyLimit: 0
    tasks:
      - id: query
        type: io.kestra.plugin.scripts.shell.Commands
        workerGroup:
          key: yourWorker
        taskRunner:
          type: io.kestra.plugin.scripts.runner.docker.Docker
        namespaceFiles:
          enabled: true
        commands:
          - mkdir -p tmp/cyl={{taskrun.value}}
          - touch yourDir/cyl={{taskrun.value}}/part-0.parquet
```

then, all files from `yourDir` will be available on `yourWorker` and accessible to other tasks — if you want to try it out, you can reach out https://kestra.io/demo as worker groups is EE feature
