### ISSUE TITLE
Add ability to skip tasks on restart/replay

### ISSUE THREAD

**Issue by paulgrainger85** [kestra-io/kestra#6711]
### Feature description

A use-case I have encountered is the following
- A user has a long-running flow which requires a lot of pre-processing data
- A non-critical task in the flow causes it to fail - say a data quality check which fails due to a false positive. 
- User is now unable to complete the flow because it is not possible to get past this failed check

There are of course ways to prevent this in the first place (e.g. using human in the loop). 

However, another option for users would be the ability to mark certain tasks as skippable then replaying. E.g. 
- The above flow runs and fails due to a bad data quality check
- The user marks the data quality task as "SKIP" and replays the flow from this task
- The flow proceeds as if the data quality task had succeeded. 

Certain tasks and flows will not be compatible with this, such as tasks which produce outputs that are used elsewhere in the flow, but there need not be guards placed around that as a user should understand the risk of skipping a task.

**Comment by anna-geller** [comment]
Loic added the feature called "Change task run state" which allows you to mark that flaky/unimportant/skippable task to SUCCESS and Kestra will then automatically launch all downstream tasks without having to rerun anything -- see https://jam.dev/c/b23e7b36-744b-44c6-936b-061a2b32c683 based on this reproducer:

```yaml
id: failure
namespace: dev
tasks:
  - id: start
    type: io.kestra.plugin.core.log.Log
    message: Hello World!
  - id: fail
    type: io.kestra.plugin.core.execution.Fail
  - id: run_after_restart
    type: io.kestra.plugin.core.log.Log
    message: Hello after restart!
```
