### ISSUE TITLE
Tasks aren't able to save files to local storage on `develop`

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#6712]
### Describe the issue

Students from the DTC DE Zoomcamp course are reporting issues where their execution fails because expected files were not generated as output files.

Error from student (because file didn't exist):
![image](https://github.com/user-attachments/assets/828e5216-ce65-4e2d-beb3-f7e6af972c57)

![Screenshot 2025-01-10 at 16 23 26](https://github.com/user-attachments/assets/7b9ab831-baf5-4115-bf99-2d5b4481ac89)

No Output Files are generated:

![Screenshot 2025-01-10 at 16 33 35](https://github.com/user-attachments/assets/493a6741-2ffb-4e4e-a6fa-79cd1842765f)

Specifically from the `extract` task of type `io.kestra.plugin.scripts.shell.Commands`

```yaml
id: postgres_taxi
namespace: zoomcamp
description: |
  The CSV Data used in the course: https://github.com/DataTalksClub/nyc-tlc-data/releases

inputs:
  - id: taxi
    type: SELECT
    displayName: Select taxi type
    values: [yellow, green]
    defaults: yellow
  - id: year
    type: SELECT
    displayName: Select year
    values: ["2019", "2020"]
    defaults: "2019"
  - id: month
    type: SELECT
    displayName: Select month
    values: ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"]
    defaults: "01"

variables:
  file: "{{inputs.taxi}}_tripdata_{{inputs.year}}-{{inputs.month}}.csv"
  staging_table: "public.{{inputs.taxi}}_tripdata_staging"
  table: "public.{{inputs.taxi}}_tripdata"
  # data: green_tripdata_2019-01.csv
  data: "{{outputs.extract.outputFiles[inputs.taxi ~ '_tripdata_' ~ inputs.year ~ '-' ~ inputs.month ~ '.csv']}}"

tasks:
  - id: set_label
    type: io.kestra.plugin.core.execution.Labels
    labels:
      file: "{{render(vars.file)}}"
      taxi: "{{inputs.taxi}}"
  - id: extract
    warningOnStdErr: false
    type: io.kestra.plugin.scripts.shell.Commands
    outputFiles:
      - "*.csv"
    taskRunner:
      type: io.kestra.plugin.core.runner.Process
    commands:
      - wget -qO- https://github.com/DataTalksClub/nyc-tlc-data/releases/download/{{inputs.taxi}}/{{render(vars.file)}}.gz | gunzip > {{render(vars.file)}}
  - id: log
    type: io.kestra.plugin.core.log.Log
    message: "{{ render(vars.data) }}"  
```

### Environment

- Kestra Version: develop
