### ISSUE TITLE
Change the "Change status" behavior to allow option to rerun downstream tasks

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#6722]
### Feature description

![image](https://github.com/user-attachments/assets/2397efa6-3106-4a02-b8bc-391dd1eb8dc6)

Instead of just "OK", we can change it for 2 buttons:
1. Change status
2. Change status and restart downstream

Option 2 is Change status manually + restart the Execution from one task below

## Repro

```yaml
id: mark_success
namespace: company.team

tasks:
  - id: fail
    type: io.kestra.plugin.core.execution.Fail

  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 
```
