### ISSUE TITLE
The SSE connection is not released from the Logs tab when there are no log

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#6725]
### Describe the issue

Create a flow that didn't emit any logs

```yaml
id: no-logs
namespace: company.team

tasks:
  - id: forEach
    type: io.kestra.plugin.core.flow.ForEach
    values: ["1", 2", "3"]
    tasks:
    - id: hello
      type: io.kestra.plugin.core.output.OutputValues
      values:
        some: value
```

For debugging the issue, adds a log here so you know when the code enter this block: https://github.com/kestra-io/kestra/blob/develop/core/src/main/java/io/kestra/core/services/ExecutionLogService.java#L65

From the UI, create an execution and go to the logs tab, you could notice that the log you added to the ExecutionLogServicee is never shown, so the connection is still alive in the server and the queue has never been properly closed. From the browser dev tools you can see the request marked as cancelled.

If you have log in your flow, or if you close your browser tab, you would be able to see that the connection is correctly dispose.

### Environment

- Kestra Version: develop
