### ISSUE TITLE
Error logs are not showed at the task level

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#6737]
### Describe the issue

```yaml
id: mymy_reproducer
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀

  - id: return
    type: io.kestra.plugin.core.debug.Return
    format: "{{inputs.test }}"
```
The error is not showed at the task level, there's no indication for the user
![image](https://github.com/user-attachments/assets/f940f5aa-8d9b-4448-b3e1-f10cc28f7941)

Though, it's displayed at the flow execution level:
![image](https://github.com/user-attachments/assets/372a1252-4db9-4b91-979c-f83565ed211b)

### Environment

- Kestra Version: develop
