### ISSUE TITLE
Ensure that the timeout property works on all tasks, both Flowable and Runnable

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#6739]
### Feature description

Below is an example user flow where they used timeout in a task that doesn't support it. This is confusing — the user shouldn't care whether a task is flowable or runnable; `timeout` is a core task property and should be supported on all tasks. 

```yaml
id: account_qualification_job
namespace: growth_production.outbound_engine
description: |-
  This Kestra flow automates the retrieval of new companies from the database and executes a subflow (`account_qualification`) for each company in parallel. The flow is designed for efficient processing, leveraging concurrency limits to optimize performance while avoiding overloading.

tasks:
  - id: get_new_companies
    type: io.kestra.plugin.jdbc.postgresql.Query
    fetchSize: 150
    fetchType: STORE
    sql: |-
      SELECT 
        companies.domain, 
        companies.company_description,
        companies.keywords  
      FROM automation.companies
      WHERE companies.last_qualified_at is null
      ORDER BY companies.last_processed_at ASC NULLS FIRST
      LIMIT 150
    sslMode: REQUIRE
    store: true
    url: "{{ secret('PRODUCTION_POSTGRES_URL') }}"

  # Convert ION to JSON-Lines format
  - id: convert_to_jsonl
    type: io.kestra.plugin.serdes.json.IonToJson
    from: "{{ outputs.get_new_companies.uri }}"
    newLine: true
    
  - id: parallelization
    type: io.kestra.plugin.core.flow.ForEachItem
    namespace: growth_production.outbound_engine
    inputs:
      input_format_company: "{{ read(taskrun.items) }}"
    tasks:
      - id: parallelization_split
        type: io.kestra.plugin.core.flow.ForEachItem$ForEachItemSplit
        batch:
          rows: "1"
          separator: "\n"
        items: "{{ outputs.convert_to_jsonl.uri }}"
      - id: parallelization_items
        type: io.kestra.plugin.core.flow.ForEachItem$ForEachItemExecutable
        inputs:
          input_format_company: "{{ read(taskrun.items) }}"
        inheritLabels: false
        subflowId:
          namespace: growth_production.outbound_engine
          revision: null
          flowId: account_qualification
        transmitFailed: true
        wait: true
      - id: parallelization_merge
        type: io.kestra.plugin.core.flow.ForEachItem$ForEachItemMergeOutputs
    allowFailure: true
    flowId: account_qualification
    items: "{{ outputs.convert_to_jsonl.uri }}"
    logLevel: INFO
    timeout: PT0H20M
triggers:
  - id: 1h_scheduler
    type: io.kestra.plugin.core.trigger.Schedule
    cron: 0 */1 * * *
    disabled: false
```
