### ISSUE TITLE
`runIf` doesn't work on tasks inside of WorkingDirectory

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#6742]
### Describe the issue

When executing this flow with the `discount_amount` input set to 0, it succeeds until it gets to the task `s3_upload_discounts` where it fails because the expected file doesn't exist. This file only exists if the discount_amount is anything other than 0. The `runIf` property stops this task from running if the discount wasn't set, and works fine if you remove the WorkingDirectory nesting.

The problem here is that `runIf` is not working as expected.

```yaml
id: python_example
namespace: company.team

inputs:
  - id: dataset_uri
    type: STRING
    displayName: Dataset URI
    defaults: https://huggingface.co/datasets/kestra/datasets/raw/main/csv/orders.csv

  - id: discount_amount
    type: FLOAT
    displayName: Discount Amount
    description: By default, it's set to 0 (no discount).
    min: 0
    max: 1
    defaults: 0

variables:
  github_repo_url: https://github.com/wrussell1999/kestra-examples
  filename: processed_orders.csv

tasks:
  - id: wdir
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      - id: clone
        type: io.kestra.plugin.git.Clone
        url: "{{ vars.github_repo_url }}"

      - id: code
        type: io.kestra.plugin.scripts.python.Commands
        containerImage: ghcr.io/kestra-io/pydata:latest
        namespaceFiles:
          enabled: true
        beforeCommands:
          - pip install kestra
        outputFiles:
          - "{{ vars.filename }}"
        env:
          DATASET_URL: "{{ inputs.dataset_uri }}"
          DISCOUNTED_AMOUNT: "{{ inputs.discount_amount ?? 0 }}"
          FILENAME: "{{ vars.filename }}"
        commands:
          - python demos/py-etl-demo/files/etl.py

      - id: slack_message
        type: io.kestra.plugin.notifications.slack.SlackIncomingWebhook
        url: "{{ secret('SLACK_WEBHOOK') }}"
        payload: |
          {
            "text": "Total: ${{ outputs.code.vars.total }}"
          }

      - id: s3_upload_discounts
        type: io.kestra.plugin.aws.s3.Upload
        runIf: "{{ inputs.discount_amount > 0 }}"
        region: eu-west-2
        bucket: oss-example
        key: "{{ vars.filename }}"
        from: "{{ outputs.code.outputFiles['processed_orders.csv'] }}"
        accessKeyId: "{{ secret('AWS_ACCESS_KEY_ID') }}"
        secretKeyId: "{{ secret('AWS_SECRET_KEY_ID') }}"
```

![Screenshot 2025-01-14 at 13 16 33](https://github.com/user-attachments/assets/8218d25f-d192-49ab-ab5b-a4c04e81fe4a)

See these examples where `runIf` works without WorkingDirectory:
- [Example 1](https://github.com/wrussell1999/kestra-examples/blob/main/demos/py-etl-demo/python_inline.yml)
- [Example 2](https://github.com/wrussell1999/kestra-examples/blob/main/demos/py-etl-demo/python_sync_file.py)

### Environment

- Kestra Version: latest EE

**Comment by wrussell1999** [comment]
I also wonder how many other tasks that nest tasks inside of them don't work with `runIf`, e.g. ForEach

**Comment by wrussell1999** [comment]
It works for ForEach:

```yaml
id: foreach
namespace: company.team

tasks:
  - id: for_each
    type: io.kestra.plugin.core.flow.ForEach
    values:
      - value 1
      - value 2
      - value 3
      - value 4
    concurrencyLimit: 2
    tasks:
      - id: return
        type: io.kestra.plugin.core.debug.Return
        format: "{{ task.id }} with value {{ taskrun.value }}"
        runIf: "{{ false }}"
```
![Screenshot 2025-01-14 at 13 24 57](https://github.com/user-attachments/assets/2c5938bf-cdb2-4543-b2cd-c9e3d9265ffa)
