### ISSUE TITLE
Plugin property v2 with default are invalid in editor and not displayed on the documentation 

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#6744]
validation failed on monaco editor: 
![image](https://github.com/user-attachments/assets/6bd251e2-eda4-4c9d-8990-3511d9f3a6eb)

no default value displayed on the documentation: 
![image](https://github.com/user-attachments/assets/33535bce-b489-4658-ae37-ccf3e95e7167)

even if the property are defined with a default: 
```java
    @Schema(title = "Does a kill or a stop command will be used.")
    @Builder.Default
    @NotNull
    private Property<Boolean> kill = Property.of(false);

    @Schema(title = "Does we will remove the container.")
    @Builder.Default
    @NotNull
    private Property<Boolean> delete = Property.of(true);
```

example flow: 
```yaml
id: docker
namespace: company.team

tasks:
  - id: dockerStart
    type: io.kestra.plugin.docker.Run
    containerImage: redis
    portBindings:
      - "6379:6379"
    wait: false

finally: 
  - id: dockerStop
    type: io.kestra.plugin.docker.Stop
    containerId: "{{ outputs.dockerStart.containerId }}"
```
