### ISSUE TITLE
`where` property in custom dashboard PieChart is not at the same level as others

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#6746]
### Describe the issue

In this chart definition:

```yaml
  - id: executions_pie
    type: io.kestra.plugin.core.dashboard.chart.Pie
    chartOptions:
      graphStyle: DONUT
      displayName: Total Executions
      description: Total executions per state
      legend:
        enabled: true
      colorByColumn: state
    data:
      type: io.kestra.plugin.core.dashboard.data.Executions
      columns:
        state:
          field: STATE
        total:
          agg: COUNT
      where:
        - field: NAMESPACE
          type: STARTS_WITH
          value: dev.ben
```

The `where` property is nested within the `data`property. On the `io.kestra.plugin.core.dashboard.chart.TimeSeries` below, the `where` is at the root level. 

```yaml
  - id: executions_timeseries
    type: io.kestra.plugin.core.dashboard.chart.TimeSeries
    chartOptions:
      displayName: Executions
      description: Executions duration and count per date
      legend:
        enabled: true
      column: date
      colorByColumn: state
    data:
      type: io.kestra.plugin.core.dashboard.data.Executions
      columns:
        date:
          field: START_DATE
          displayName: Date
        state:
          field: STATE
        total:
          displayName: Executions
          agg: COUNT
          graphStyle: BARS
        duration:
          displayName: Duration
          field: DURATION
          agg: SUM
          graphStyle: LINES
      where:
        - field: NAMESPACE
          type: STARTS_WITH
          value: dev.ben
```

👉 align the two DSL in favor of the `where` at the root level

### Environment

- Kestra Version: develop
