### ISSUE TITLE
[Optional] Setting `disabled: true` on a flowable task could mark all child task also as disabled in the Topology

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#6754]
When you are using `disabled: true` on any flowable, in fact the whole flowable (with its child) will be disabled, but the topology will only display the first child as disabled. 
We should display all nested child as disable, we also need to disabled visually the whole cluster. 

![image](https://github.com/user-attachments/assets/a85ebb85-2e7f-4df5-88f7-ea583e00d5a4)

example flow: 

```yaml 
  - id: parallel
    type: io.kestra.plugin.core.flow.Parallel
    tasks:
      - id: string
        disabled: true
        type: io.kestra.plugin.core.flow.Sequential
        tasks:
          - id: stringSet
            type: io.kestra.plugin.redis.string.Set
            url: "{{ vars.dockerUrl }}"
            key: "string_{{ execution.id }}"
            value: "{{ flow.id }}"
            serdeType: STRING

          - id: stringGet
            type: io.kestra.plugin.redis.string.Get
            url: "{{ vars.dockerUrl }}"
            key: "string_{{ execution.id }}"
            serdeType: STRING

```
