### ISSUE TITLE
Plugin deprecation should have new line to make it readable 

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#6771]
![image](https://github.com/user-attachments/assets/185311f0-f569-4bbe-8486-7d71df967b60)
best layout will be to use list and inline code block like this:

- `tasks[0]` is deprecated.
- `io.kestra.plugin.fs.http.Download` is replaced by `io.kestra.plugin.core.http.Download` 
- `io.kestra.core.models.triggers.types.Schedule` is replaced by `io.kestra.plugin.core.trigger.Schedule`

**Comment by rajatsingh23** [comment]
I would like to work on it. Can I know how can I reproduce it?

**Comment by MilosPaunovic** [comment]
@Ben8t Could you provide a sample flow with a few deprecated plugin names?

**Comment by Ben8t** [comment]
Yes, here is one:

```yaml
id: test
namespace: test
tasks:
  - id: download
    type: io.kestra.plugin.fs.http.Download
    uri: https://huggingface.co/datasets/kestra/datasets/raw/main/csv/orders.csv
```
