### ISSUE TITLE
Execution timer does't stop after failure

### ISSUE THREAD

**Issue by NovytskyiD** [kestra-io/kestra#6780]
### Describe the issue

When one task branch in Dag is failed - some tasks in another branch still processing (or just the timer doesn't stop).
For example, the timer for dependentOne didn't stop.
![image](https://github.com/user-attachments/assets/0c9e4d33-f111-46db-b352-8db9a202f2e8)

Code to reproduce
```

id: testTimer
namespace: company.team


inputs:
  - id: user
    type: STRING
    defaults: Rick Astley


tasks:
  - id: dag
    type: io.kestra.plugin.core.flow.Dag
    tasks:
      - task:
          id: first_task
          type: io.kestra.plugin.core.debug.Return
          format: thrilled
      
      - task:
          id: dependentOne
          type: io.kestra.plugin.core.flow.If
          condition: "{{ inputs.user == 'Rick Astley'}}"
          then:
          - id: second_task
            type: io.kestra.plugin.scripts.shell.Commands
            commands:
              - sleep 10
              - echo '::{"outputs":{"returned_data":"mydata"}}::'
        dependsOn:
          - first_task
      
      - task:
          id: dependentTwo
          type: io.kestra.plugin.core.flow.If
          condition: "{{ inputs.user == 'Rick Astley'}}"
          then:
          - id: fail_missing_variable
            type: io.kestra.plugin.core.log.Log
            message: "{{ vars.nonexistent_variable }}"
        dependsOn:
          - first_task
      
```

### Environment

- Kestra Version: 0.20.11

**Comment by loicmathieu** [comment]
`Dag` process tasks in parallel, there is an inherent race when doing that.

You would have the same issue with the `Parallel` task.

```yaml
id: parallel
namespace: company.team


inputs:
  - id: user
    type: STRING
    defaults: Rick Astley


tasks:
  - id: dag
    type: io.kestra.plugin.core.flow.Parallel
    tasks:
      - id: dependentOne
        type: io.kestra.plugin.core.flow.If
        condition: "{{ inputs.user == 'Rick Astley'}}"
        then:
        - id: second_task
          type: io.kestra.plugin.scripts.shell.Commands
          commands:
            - sleep 10
            - echo '::{"outputs":{"returned_data":"mydata"}}::'
      
      - id: dependentTwo
        type: io.kestra.plugin.core.flow.If
        condition: "{{ inputs.user == 'Rick Astley'}}"
        then:
        - id: fail_missing_variable
          type: io.kestra.plugin.core.log.Log
          message: "{{ vars.nonexistent_variable }}"
      
```
