### ISSUE TITLE
Irrelevant warning on deprecated field

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#6791]
### Describe the issue

```yaml
id: ion_to_excel
namespace: qa

tasks:
  - id: create_csv
    type: io.kestra.plugin.core.http.Download
    uri: https://huggingface.co/datasets/kestra/datasets/raw/main/csv/orders.csv
```

![Screenshot 2025-01-16 at 09 42 44](https://github.com/user-attachments/assets/c65e3177-9138-45f2-a1d2-715ea8ab9c76)

Got this warning but didn't explicitly use the allowFailed prop 🤔 

### Environment

- Kestra Version: develop

**Comment by Ben8t** [comment]
Could be related too:
- Script tasks seem to have a lot of issues - the plugin is marked as not known to monako editor (Value must be "io.kestra.core.tasks.scripts.Python" -- not true)
- Task runner types lack autocompletion

**Comment by Ben8t** [comment]
For example it's not happening on log

```yaml
id: ion_to_excel
namespace: qa

tasks:
  - id: create_csv
    type: io.kestra.plugin.core.log.Log
    message: rgaerg
```
