### ISSUE TITLE
Restarting an execution from "Change state" of a task duplicate the logs

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#6793]
### Describe the issue

1. Start a flow that fails on a task

```yaml
id: chage-staus
namespace: company.team

tasks:
  - id: fail
    type: io.kestra.plugin.core.execution.Fail
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀
```

2. From the Gantt view, goes to the failing task menu -> Change state -> SUCCESS

The logs will be duplicated.

### Environment

- Kestra Version: develop
