### ISSUE TITLE
ForEachItem doesn't work inside an If flow

### ISSUE THREAD

**Issue by MarthaScheffler** [kestra-io/kestra#6801]
### Describe the issue

https://kestra-io.slack.com/archives/C03FQKXRK3K/p1737016097792479

When forEachItem is used inside of an If flow, it doesn't manage to start the subflows. The item split seems to work, but there is always an error `Cannot invoke "java.util.Map.get(Object)" because the return value of "java.util.Map.get(Object)" is null` before any subflow gets started.
The same flow works without the If clause.

Interesting: when both, forEach and forEachItem are set in the same flow, then the link to the subflows in forEachItem will lead to subflows for both subtasks.

flow example:

````
id: for_each_item_with_if
namespace: kestra.sandbox

tasks:
#  - id: if
#    type: io.kestra.plugin.core.flow.If
#    condition: "true"
#    then:
      - id: for_each
        disabled: true
        type: io.kestra.plugin.core.flow.ForEach
        values: ["1","2"]
        tasks:
          - id: subflow
            type: io.kestra.plugin.core.flow.Subflow
            flowId: subflow
            namespace: "{{ flow.namespace }}"
            inputs:
              number: "{{ taskrun.value }}"
      
      - id: read_items
        type: io.kestra.plugin.jdbc.duckdb.Query
        url: 'jdbc:duckdb:'
        timeZoneId: Europe/Paris
        sql: |-
          SELECT 1 AS item
          UNION ALL
          SELECT 2 AS item;
        fetchType: STORE

      - id: ion_to_jsonl
        type: io.kestra.plugin.serdes.json.IonToJson
        from: "{{ outputs.read_items.uri }}"
        newLine: true

      - id: for_each_item
        type: io.kestra.plugin.core.flow.ForEachItem
        #runIf: "false"
        items: "{{ outputs.ion_to_jsonl.uri }}"
        batch:
          rows: 1
        flowId: subflow
        namespace: "{{ flow.namespace }}"
        inputs:
          number: "{{ json(read(taskrun.items)).item }}"

````

````
id: subflow
namespace: kestra.sandbox

inputs:
  - id: number
    type: STRING

tasks:
  - id: log
    type: io.kestra.plugin.core.log.Log
    message: "Subflow {{ inputs.number}} is started"

````

### Environment

- Kestra Version: OSS 0.20.12
