### ISSUE TITLE
Timeout property doesn't have good typing

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#6821]
### Describe the issue

In no code the task level `timeout`property have weird type "one of" and also display "String" two times 🤔 

![Image](https://github.com/user-attachments/assets/cc4faf89-0adf-47cb-9ffc-a1ed89d5bcf2)

![Image](https://github.com/user-attachments/assets/983db780-eb80-4be7-b9de-ef93ed0c07ba)

Simple reproducer:

```yaml
id: myflow_test2
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀
    timeout: PT2S
```

### Environment

- Kestra Version: develop
