### ISSUE TITLE
io.kestra.plugin.kafka.Produce always pointing to 127.0.0.1 regardless of the properties

### ISSUE THREAD

**Issue by ab-smith** [kestra-io/kestra#6824]
### Describe the issue

Hello,

I'm trying to assess all my plugins before I start linking everything and I'm struggling witg `io.kestra.plugin.kafka.Produce` that doesn't seem to take the properties into consideration. To avoid any mis-interpretation, I've used exactly the sample from the doc and changed the targeted host to docker internal (I'm on Mac OS).

```
id: send_message_to_kafka
namespace: company.team

inputs:
  - id: file
    type: FILE
    description: "A CSV file with columns: id, username, tweet, and timestamp."

tasks:
  - id: csv_to_ion
    type: io.kestra.plugin.serdes.csv.CsvToIon
    from: "{{ inputs.file }}"

  - id: ion_to_avro_schema
    type: io.kestra.plugin.scripts.nashorn.FileTransform
    from: "{{ outputs.csv_to_ion.uri }}"
    script: |
      var result = {
        "key": row.id,
        "value": {
          "username": row.username,
          "tweet": row.tweet
        },
        "timestamp": row.timestamp,
        "headers": {
          "key": "value"
        }
      };
      row = result

  - id: avro_to_kafka
    type: io.kestra.plugin.kafka.Produce
    from: "{{ outputs.ion_to_avro_schema.uri }}"
    keySerializer: STRING
    properties:
      bootstrap.servers: host.docker.internal:9092
    serdeProperties:
      schema.registry.url: http://host.docker.internal:8085
    topic: test_kestra
    valueAvroSchema: |
      {"type":"record","name":"twitter_schema","namespace":"io.kestra.examples","fields":[{"name":"username","type":"string"},{"name":"tweet","type":"string"}]}
    valueSerializer: AVRO
```

Kestra get stucked on the task sending to kafka. I can see on the docker logs that it's trying to send to 127.0.0.1 regardless of what I put as settings : 

```
Id=producer-44XnO1rYXvd9XNAB1464yh, transactionalId=44XnO1rYXvd9XNAB1464yh] Connection to node 0 (/127.0.0.1:9092) could not be established. Node may not be available.
2025-01-20 08:37:45,009 WARN  ad | producer-6lyLYr3riZzOSWaGzoPctw o.apache.kafka.clients.NetworkClient [Producer clientId=producer-6lyLYr3riZzOSWaGzoPctw, transactionalId=6lyLYr3riZzOSWaGzoPctw] Connection to node 0 (/127.0.0.1:9092) could not be established. Node may not be available.
2025-01-20 08:37:45,218 WARN  ad | producer-4WA70Hbs8H4PCT58Bvf9SC o.apache.kafka.clients.NetworkClient [Producer clientId=producer-4WA70Hbs8H4PCT58Bvf9SC, transactionalId=4WA70Hbs8H4PCT58Bvf9SC] Connection to node 0 (/127.0.0.1:9092) could not be established. Node may not be available.
2025-01-20 08:37:45,255 WARN  ad | producer-6gXdY8IYU3b4crinSp2Am3 o.apache.kafka.clients.NetworkClient [Producer clientId=producer-6gXdY8IYU3b4crinSp2Am3, transactionalId=6gXdY8IYU3b4crinSp2Am3] Connection to node 0 (/127.0.0.1:9092) could not be established. Node may not be available.
```

I know that the host is reachable from the Kestra instance as I tried other basic http requests successfully to `host.docker.internal` 

Did I miss something?

Thank you

### Environment

- Kestra Version: 0.20 using standard docker on Mac OS

**Comment by Ben8t** [comment]
I'm able to reproduce on 0.21.5 with the flow provided, this[test.csv](https://github.com/user-attachments/files/19127788/test.csv), and the following kafka docker-compose setup:

```yaml
version: "2.5"
volumes:
  volume1:
services:
  kafka1:
    image: 'bitnami/kafka:3.3.1'
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9092
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka1:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_KRAFT_CLUSTER_ID=r4zt_wrqTRuT7W2NJsB_GA
    volumes:
      - volume1:/bitnami/kafka
  kafka-ui:
    container_name: kafka-ui
    image: 'provectuslabs/kafka-ui:latest'
    ports:
      - "8085:8080"
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka1:9092
      - KAFKA_CLUSTERS_0_NAME=r4zt_wrqTRuT7W2NJsB_GA

networks:
  default:
    external:
      name: kestra-net # my kestra is also sharing that network
```

FYI, this other flow succeed to produce a message

```yaml
id: create_message
namespace: company.team

tasks:
  - id: api
    type: io.kestra.plugin.core.http.Request
    uri: https://dummyjson.com/products

  - id: produce
    type: io.kestra.plugin.kafka.Produce
    from:
      key: mykey
      value: "{{ outputs.api.body }}"
      timestamp: "{{ execution.startDate }}"
      headers:
        x-header: some value
    keySerializer: STRING
    valueSerializer: JSON
    topic: topic_test
    properties:
      bootstrap.servers: host.docker.internal:9092
```

**Comment by Malaydewangan09** [comment]
I am not able to reproduce as of Kestra latest docker image
- Kestra: latest (Docker)
- Kafka: bitnami/kafka:3.3.1 (Docker Compose)
- Network: Shared Docker network (kestra-net)

Docker compose:
```yaml
version: "2.5"
services:
  kafka:
    image: bitnami/kafka:3.3.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_KRAFT_CLUSTER_ID=r4zt_wrqTRuT7W2NJsB_GA

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8085:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS=kafka:9092

networks:
  default:
    name: kestra-net
    external: true
```
Test flow 1:
```yaml
id: kafka-produces-failure
namespace: company.team

inputs:
  - id: file
    type: FILE
    description: "A CSV file with columns: id, username, tweet, and timestamp."

tasks:
  - id: csv_to_ion
    type: io.kestra.plugin.serdes.csv.CsvToIon
    from: "{{ inputs.file }}"

  - id: ion_to_avro_schema
    type: io.kestra.plugin.scripts.nashorn.FileTransform
    from: "{{ outputs.csv_to_ion.uri }}"
    script: |
      var result = {
        "key": row.id,
        "value": {
          "username": row.username,
          "tweet": row.tweet
        },
        "timestamp": row.timestamp,
        "headers": {
          "key": "value"
        }
      };
      row = result

  - id: avro_to_kafka
    type: io.kestra.plugin.kafka.Produce
    from: "{{ outputs.ion_to_avro_schema.uri }}"
    keySerializer: STRING
    valueSerializer: JSON
    topic: topic_test
    properties:
      bootstrap.servers: host.docker.internal:9092

```

Test flow 2:
```yaml
id: kafka-produce-success
namespace: company.team

tasks:
  - id: produce
    type: io.kestra.plugin.kafka.Produce
    from:
      key: mykey
      value: "{\"message\": \"hello again\"}"
      timestamp: "{{ execution.startDate }}"
      headers:
        x-header: some value
    keySerializer: STRING
    valueSerializer: JSON
    topic: topic_test
    properties:
      bootstrap.servers: kafka:9092
```

Closing this for now; feel free to reopen if you still face issues after upgrading.
Thanks!
