### ISSUE TITLE
Flow outputs are not passed correctly to downstream flows using `{{ trigger.outputs }}` expression in Flow trigger

### ISSUE THREAD

**Issue by shrutimantri** [kestra-io/kestra#6848]
### Describe the issue

As mentioned in the [ExecutionOutputs flow condition](https://develop.kestra.io/plugins/core/conditions/io.kestra.plugin.core.condition.executionoutputs), we can use the trigger outputs in the expression of this condition like:
```
- conditions:
    - type: io.kestra.plugin.core.condition.ExecutionOutputs
      expression: {{ trigger.outputs.status_code == '200' }}
```  

But, when I execute the flow, and try to print the `{{ trigger }}`, `outputs` are not present as part of trigger. We get only the following data in the `{{ trigger }}`:

```
{"executionId":"1BWq0Z9NvQLZfs7xxSEPU6","state":"SUCCESS","namespace":"company.team","flowId":"python_flow","flowRevision":7}
``` 

Hence, it is not possible to use the ExecutionOutputs condition. We should start including the outputs in the `trigger`.

### Environment

- Kestra Version: develop

**Comment by anna-geller** [comment]
I can confirm that while technically, flow trigger dependencies are evaluated correctly, the outputs from the upstream flows are not accessible by the downstream flow even when they are explicitly exposed/defined. Reproducer:


```yaml
id: flowA
namespace: company.team

inputs:
  - id: userValue
    type: STRING
    defaults: hello

tasks:
  - id: hello
    type: io.kestra.plugin.core.debug.Return
    format: "{{ inputs.userValue }}"

outputs:
  - id: flowAoutput
    type: STRING
    value: "{{ outputs.hello.value }}"
```

and the main flow:
```yaml
id: flowB
namespace: company.team

tasks:
  - id: upstreamOutputs
    type: io.kestra.plugin.core.log.Log
    message: got "{{ trigger.outputs }}"

triggers:
  - id: flowA
    type: io.kestra.plugin.core.trigger.Flow
    states:
      - SUCCESS
    conditions:
      - type: io.kestra.plugin.core.condition.ExecutionOutputs
        expression: "{{ trigger.outputs.flowAoutput == 'hello' }}"
```

Changing the line `message: got "{{ trigger.outputs }}"` with `message: hello` shows that dependencies work by themselves, it's just that outputs are not passed between flows

**Comment by anna-geller** [comment]
fix to docs for now https://github.com/kestra-io/kestra/pull/7394/files

**Comment by Ben8t** [comment]
Alternatively, one can use `inputs` to pass data coming from upstream flow outputs:

```yaml
id: flow_b
namespace: kestra.sandbox
inputs:
  - id: value_from_a
    type: STRING
tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: "{{ inputs.value_from_a }}"
triggers:
  - id: upstream_dep
    type: io.kestra.plugin.core.trigger.Flow
    inputs:
      value_from_a: "{{ trigger.outputs.return_value }}"
...
...
```
