### ISSUE TITLE
Vertex AI Custom Job Training Plugin does not finish when job finishes training

### ISSUE THREAD

**Issue by japerry911** [kestra-io/kestra#6849]
### Describe the issue

I am using the Kestra Vertex AI Custom Job Training plugin, and it does not mark the finished/completed job as complete and keeps task running forever in Kestra.

```
2025-01-21T06:25:20.050Z INFO Job projects/xxx/locations/us-central1/customJobs/3000721679224668160 ended in PT13M9.553791S with status JOB_STATE_SUCCEEDED
2025-01-21T06:28:41.734Z INFO {"severity":"INFO","time":"2025-01-21T06:28:38.483205565Z","logging.googleapis.com/insertId":"x2pt2gdq999","logging.googleapis.com/labels":{"ml.googleapis.com/endpoint":"","ml.googleapis.com/job_state":"SUCCEEDED"},"logging.googleapis.com/trace_sampled":false,"message":"Job completed successfully."}
```
sample logs ^

### Environment

- Kestra Version: 0.20.12

**Comment by japerry911** [comment]
![Image](https://github.com/user-attachments/assets/416eaf2e-fbda-4ab9-b037-7ac25d4556ff)

still running image (10 minutes after finished, killing now)

**Comment by japerry911** [comment]
sample flow 

```
id: ${flow_id}
namespace: ${namespace}
description: |
  This flow is used to train a custom job on Vertex AI.

inputs:
    - id: imageUri
      type: STRING
      required: true
    
    - id: machineType
      type: STRING
      required: true
      defaults: n1-standard-16

tasks:
  - id: custom_job
    type: io.kestra.plugin.gcp.vertexai.CustomJob
    projectId: "{{ secret('GCP_PROJECT_ID') }}"
    region: us-central1
    displayName: Custom Job via Kestra
    spec:
      workerPoolSpecs:
      - containerSpec:
          imageUri: "{{ inputs.imageUri }}"
        machineSpec:
          machineType: "{{ inputs.machineType }}"
        replicaCount: 1
    serviceAccount: "{{ secret('GCP_SERVICE_ACCOUNT_JSON') }}"

```
