### ISSUE TITLE
`io.kestra.plugin.gcp.bigquery.DeleteTable` doesn't use `projectId` attribute

### ISSUE THREAD

**Issue by obzva** [kestra-io/kestra#6852]
### Describe the issue

:wave: Hello, team!
I tried to delete gcp bigquery table with kestra.

```yml
# kestra flow
...
      - id: bq_del_green_table_tmp
        type: io.kestra.plugin.gcp.bigquery.DeleteTable
        projectId: "{{kv('GCP_PROJECT_ID')}}"
        dataset: "{{kv('GCP_DATASET')}}"
        table: "{{render(vars.table)}}" # this evaluates to 'green_tripdata_2019_03'
...
pluginDefaults:
  - type: io.kestra.plugin.gcp
    values:
      serviceAccount: "{{kv('GCP_CREDS')}}"
      projectId: "{{kv('GCP_PROJECT_ID')}}"
      location: "{{kv('GCP_LOCATION')}}"
      bucket: "{{kv('GCP_BUCKET_NAME')}}"
```

I set kv pairs like this.

```yml
# kestra kv setting
...
  - id: gcp_project_id
    type: io.kestra.plugin.core.kv.Set
    key: GCP_PROJECT_ID
    kvType: STRING
    value: kestra-sandbox-448507 
  - id: gcp_dataset
    type: io.kestra.plugin.core.kv.Set
    key: GCP_DATASET
    kvType: STRING
    value: kestra_sandbox_zoomcamp_dataset
...
```

When I execute the kestra flow, the following error occurs.

```
Invalid table ID "kestra_sandbox_zoomcamp_dataset.green_tripdata_2019_03".
```

I think the task `io.kestra.plugin.gcp.bigquery.DeleteTable`  is not using `projectId` to evaluate the target table ID.
How can I handle this?
Thanks.

### Environment

- Kestra Version: 0.20.12
