### ISSUE TITLE
Python commands can't be filled

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#6854]
### Describe the issue

```yaml
id: test
namespace: kestra.test

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    description: This is a description
    message: Hello World!

  - id: write
    type: io.kestra.plugin.core.storage.Write
    content: |
      print("Hello World!")
    extension: .py

  - id: python
    type: io.kestra.plugin.scripts.python.Commands
    commands:
      - python {{ outputs.write.uri}}
```
In develop this raise the following error during flow validation:
<img width="270" alt="Image" src="https://github.com/user-attachments/assets/b5902d3a-8e7c-4d3c-af82-a3cef76ebfbf" />

### Environment

- Kestra Version: develop
