### ISSUE TITLE
Output Files Preview button causes error when using PurgeCurrentExecutionFiles

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#6887]
### Describe the issue

When using this workflow, it will purge execution files. However, when you view them in the Outputs tab, the preview button is still present. When you press it, an error pops up in the UI and leaves the user on a generic error page unrelated to their flow. Is there a way to disable the preview button on files of 0B? 

```yaml
id: purge_current_execution_files
namespace: qa

tasks:
  - id: download
    type: io.kestra.plugin.core.http.Download
    uri: https://huggingface.co/datasets/kestra/datasets/raw/main/csv/orders.csv

  - id: purge
    type: io.kestra.plugin.core.storage.PurgeCurrentExecutionFiles
```

![Image](https://github.com/user-attachments/assets/70fe17dd-254f-4664-98d7-619bec804c6a)

### Environment

- Kestra Version: `latest` - v0.20.11
