### ISSUE TITLE
Add Pebble functions to help troubleshoot if file exists, is empty and inspecting its file size

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#6888]
### Feature description

Proposed pebble functions:
```yaml
{{ fileSize(output.download.uri)  }}
{{ fileExists(output.download.uri)  }}
{{ isEmpty(output.download.uri)  }} # true or false
```

**Comment by deepPublicGit** [comment]
Hi @anna-geller  few questions:

1. Is the proposed filesize function different from the existing one:

https://github.com/kestra-io/kestra/blob/develop/core/src/main/java/io/kestra/core/runners/pebble/functions/FileSizeFunction.java

2. What should the return type of fileExists function ? (true/false ?)

3. Can we reuse fileSize function for isEmpty function, if fileSize==0 return true or should it check the file content? 

4. Would it better to rename isEmpty to isFileEmpty to avoid potential confusion with any future function that would check if the content of a variable/string is empty?

**Comment by anna-geller** [comment]
1. You are right, I wasn't aware this function already exists (see flow below), so it seems that no action is needed then ✅  
2. Yup, exactly, a boolean with true if file exists is great!
3. I believe checking the file content seems like a more reliable way to check if the file is empty
4. We can name it `fileEmpty()` for consistency with `fileExists()` 👍 
 
```yaml
id: etl
namespace: company.team

tasks:
  - id: download
    type: io.kestra.plugin.core.http.Download
    uri: https://huggingface.co/datasets/kestra/datasets/raw/main/csv/orders.csv
  
  - id: log
    type: io.kestra.plugin.core.log.Log
    message: "{{ fileSize(outputs.download.uri) }}"
```
