### ISSUE TITLE
Trigger is not cleaned when the concurrency limit is reached

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#6889]
You have a trigger every hour, with concurrency set with cancelled 
```yaml 
concurrency:
  behavior: CANCEL
  limit: 1
```

If a flow is manually triggered and end after the schedule, the triggered execution will be `CANCELLED`, fine. 
But the trigger will not cleaned the execution id, leading to locking the schedule, with this logs: 

```
Execution '6hjH3zCN4e6yDczobgnSgh' is not found, schedule is blocked since '2025-01-22T14:00:02.350299Z'
```

A user on the EE kafka version: 
![Image](https://github.com/user-attachments/assets/4741e367-cf3d-427a-8490-a2e6432fae3e)

It's theory here, that need to be validated

**Comment by loicmathieu** [comment]
Using the following flow:

```yaml
id: trigger-cancelled
namespace: company.team

concurrency:
  behavior: CANCEL
  limit: 1

triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "* * * * *"

tasks:
  - id: sleep
    type: io.kestra.plugin.core.flow.Sleep
    duration: PT30S

  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀
```

When I execute it and an execution triggered by the schedule is already running => the execution is cancelled ✅ 
When I execute it and then an execution is triggered by the schedule => the execution triggered by the schedule is cancelled ✅ 

In both cases, subsequent executions are created by the trigger and it is never locked.
Tested in both Postgres OSS and Kafka EE.

So I don't think concurrency limit is the issue here and we would need more information from the user to be able to understand what's going on.
