### ISSUE TITLE
Delete Executions per Namespace charts on the Namespace page.

### ISSUE THREAD

**Issue by Nico-Kestra** [kestra-io/kestra#6901]
### Describe the issue

<img width="1761" alt="Image" src="https://github.com/user-attachments/assets/f3bba8ae-89d0-4350-8a88-62ca4f8107d8" />

The "Executions per Namespace" chart has no relevance to appear on the Namespace page.

### Environment

- Kestra Version: develop

**Comment by rajatsingh23** [comment]
Can it be assigned to me?

**Comment by MilosPaunovic** [comment]
Hi @Nico-Kestra,

I believe we should not do this. See the reasoning below:

- I have nested namespaces like on the image below (ignore the incoherent names, it's for local testing):

![Image](https://github.com/user-attachments/assets/e3a8d4f1-6c2e-4024-9338-57425518a9fa)

- Click on the top level, in this case, `Company` namespace and get this view, as there were executions in two of the child namespaces:

![Image](https://github.com/user-attachments/assets/c1ecf0d0-b1c4-471e-b279-933bffd3e585)

Do you think it's a good idea to keep it as is now, or are you still up for removal?

**Comment by Nico-Kestra** [comment]
Ah, I understand. But if a namespace doesn't have sub-namespaces, then it shouldn't be displayed. However, if a namespace does have sub-namespaces, then the idea of displaying it is a good one.
it is possible?

**Comment by MilosPaunovic** [comment]
Yup, should be doable. @rajatsingh23 As I see you've closed the PR, are you still open to handle this one with those new requirements?

**Comment by rajatsingh23** [comment]
Hey @MilosPaunovic,  
Sure, I’ll work on it, but I’ll need an example flow to reproduce the issue.

**Comment by MilosPaunovic** [comment]
So, what you could do is have two flows:

```yaml
id: first
namespace: rajatsingh23.first

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀
```

and

```yaml
id: first
namespace: rajatsingh23.second

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀
```

Execute both at least once, then go to `Namespace` page from the left menu, and open details of namespace named `rajatsingh23`. In this case, it's a parent namespace of `first` and `second`, and if you've executed those flows, you'll have two different stacks in the chart in question.

What we need to do is to filter out which namespace is opened, and if it has no child namespaces, then show no card for that.

Is it a bit clearer now @rajatsingh23?
