### ISSUE TITLE
SSE for execution stop too soon before the end of the execution

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#6913]
The execution follow endpoint will stop too soon even if the tasks in not ended.

We see that as ending point: 
![Image](https://github.com/user-attachments/assets/26c242ef-d83d-41bf-8017-11019ad03c9e)
But when we refresh: 
![Image](https://github.com/user-attachments/assets/41b4e10f-5a7b-4339-9005-1bdf6ab2efbe)

We see others end of the first tasks, and the second one: 

```yaml
id: fail
namespace: company.team
tasks:
  - id: failed
    type: io.kestra.plugin.core.log.Log
    message: "{{ taskrun.attemptsCount == 3 ? 'ok' : ko}}"
    retry:
      type: constant
      interval: PT0.250S
      maxAttempt: 4
      maxDuration: PT15S
      warningOnRetry: true

  - id: warn
    type: io.kestra.plugin.core.execution.Fail
    allowFailure: true
    allowWarning: true
```
