### ISSUE TITLE
Improve the display of ARRAY inputs

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#6947]
Let's improve the design of arrays, currently we show it as a code block:

![Image](https://github.com/user-attachments/assets/671b065b-f20f-415d-8931-f62a38a21647)

This is how we display INT values:

![Image](https://github.com/user-attachments/assets/b593b15f-45e7-43ae-ba57-4a666b733a4b)

```yaml
id: lists
namespace: company.team

inputs:
  - id: table
    type: ARRAY
    itemType: STRING
    defaults:
      - dev
      - prod

  - id: years
    type: ARRAY
    itemType: INT
    defaults:
      - 2026
      - 2025

  - id: nr
    type: INT
    defaults: 42

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: "{{ inputs }}"
```

## New design

https://www.figma.com/design/ew0uXk0NRXJ2NBBJTNe2n1/01_UI?node-id=5947-55698&t=ZIJRZZrW3MQrTBTy-4 

![image](https://github.com/user-attachments/assets/af833a4c-74a7-41ad-8484-2dba0c182319)
