### ISSUE TITLE
io.kestra.plugin.git.SyncFlows doesn't work with sublows

### ISSUE THREAD

**Issue by NovytskyiD** [kestra-io/kestra#6969]
### Describe the issue

When I try to sync flow that contains sublows - it fails with an error

```
Long.then[0].namespace: must not be empty
 Short._else[0].namespace: must not be empty

```

If I change in the repo namespace here and then run sync - it works well
```
type: io.kestra.plugin.core.flow.Subflow
      namespace: null
```

Code to reproduce

subflow
```
id: testSubFlow
namespace: pl.base

tasks:
  - id: hello
    type: io.kestra.plugin.scripts.python.Commands
    namespaceFiles:
      enabled: true
    commands:
      - python scripts/hello.py

```

parent flow
```
id: testFlow
namespace: null

inputs:
  - id: shortPeriod
    displayName: shortPeriod
    type: SELECT
    values:
      - Yes
      - No
    defaults: No

  - id: customPeriod
    displayName: customPeriod
    type: SELECT
    values:
      - Yes
      - No
    defaults: No

  - id: dateFrom
    type: DATETIME
    dependsOn:
      inputs:
        - customPeriod
      condition: "{{ inputs.customPeriod == 'Yes' }}"

  - id: dateTo
    type: DATETIME
    dependsOn:
      inputs:
        - customPeriod
      condition: "{{ inputs.customPeriod == 'Yes' }}"
  

tasks:
  - id: longOrShort
    type: io.kestra.plugin.core.flow.If
    condition: "{{inputs.shortPeriod == 'Yes'}}"
    then:
    - id: Long
      type: io.kestra.plugin.core.flow.Subflow
      namespace: null
      flowId: testSubFlow
      inputs:
        shardId: "1"
        customPeriod: "{{ inputs.customPeriod}}"
        dateFrom: "{{ inputs.dateFrom ?? NULL}}"
        dateTo: "{{ inputs.dateTo ?? NULL}}"
    else:
    - id: Short
      type: io.kestra.plugin.core.flow.Subflow
      namespace: null
      flowId: testSubFlow
      inputs:
        shardId: "1"
        customPeriod: "{{ inputs.customPeriod}}"
        dateFrom: "{{ inputs.dateFrom ?? NULL}}"
        dateTo: "{{ inputs.dateTo ?? NULL}}"
```

### Environment

- Kestra Version: 0.20.11
