### ISSUE TITLE
Execute Backfill button is greyed out when float input value is set to 0 or 0.000 (it must be some decimal to make it work atm)

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#7008]
### Describe the issue

When trying to run backfills on this flow, the Backfill button is greyed out unless I set the input `discount_amount` to anything that isn't 0. It can be executed with 0 manually.

Execute Backfill greyed out when Discount Amount is set to 0
![Image](https://github.com/user-attachments/assets/d0904b52-47d7-4366-8c31-193b11e92d6e)

Execute Backfill works when anything other than 0 is used.
![Image](https://github.com/user-attachments/assets/cc347b65-fa63-40e4-8ec5-fdf1458a820e)

```yaml
id: input_test
namespace: data

inputs:
  - id: dataset_uri
    type: STRING
    displayName: Dataset URI
    defaults: https://huggingface.co/datasets/kestra/datasets/raw/main/csv/orders.csv

  - id: discount_amount
    type: FLOAT
    displayName: Discount Amount
    description: By default, it's set to 0 (no discount).

tasks:
  - id: code
    type: io.kestra.plugin.scripts.python.Script
    containerImage: ghcr.io/kestra-io/pydata:latest
    beforeCommands:
      - pip install kestra
    outputFiles:
      - processed_orders.csv
    script: |
      import pandas as pd
      from kestra import Kestra

      df = pd.read_csv('{{ inputs.dataset_uri }}')
      total_revenue = df['total'].sum()
      Kestra.outputs({"total": total_revenue})
      if {{ inputs.discount_amount }} > 0:
        df['discounted_total'] = df['total'] * (1 - {{ inputs.discount_amount }})
        df.to_csv('processed_orders.csv')

triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "@daily"
```

### Environment

- Kestra Version: OSS `develop` and `latest`

**Comment by anna-geller** [comment]
Very strange indeed, as changing the default value below from 0.0000 to 0.0001 will make it work

```yaml

  - id: discount_amount
    type: FLOAT
    displayName: Discount Amount
    defaults: 0.0000 # won't work but changing to 0.0001 would work
    description: By default, it's set to 0 (no discount).
```
