### ISSUE TITLE
Incorrect Plugin Docs displayed when saving with an error

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#7009]
### Describe the issue

Sometimes when I am editing a flow, I will press CTRL + S to save my flow but there's an error. When I do this, the Plugin Docs seems to stick to the last clicked plugin. Here's examples where it happened with `Log` and `Schedule`.

![Image](https://github.com/user-attachments/assets/6f362d36-5271-4912-abae-9b877cf16dfc)

![Image](https://github.com/user-attachments/assets/42f1cd36-a1fc-4d01-a4e7-ad94156ab579)

![Image](https://github.com/user-attachments/assets/22e4312c-0527-4232-af17-bfc5610483c1)

Refreshing the page fixes it until it happens again. It doesn't go away if you fix the syntax and save again, a refresh is required.

A flow to recreate with a typo. Try saving it.
```yaml
id: fail_sometimes
namespace: data

inputs:
  - id: fail
    type: BOOLEAN
    defaults: false

tasks:
  - id: log
    type: io.kestra.plugin.core.log.Log
    message: "{{ trigger.date ?? execution.startDate }}"

  - id: fail_execution
    type: io.kestra.plugin.core.execution.Fail
    runIf: "{{ inputs.fail }}"

triggers:
  - id: schedule_60_mins
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "5 * * * *"
    inputs:
      fail: false

  - id: fail_every_3_hours
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "20 */3 * * *"
    inputs:
      fail: true
    labels:
      debug: true
      ebug : 
```

### Environment

- Kestra Version: `develop` OSS
