### ISSUE TITLE
Topology - Finally lines not all the same colors

### ISSUE THREAD

**Issue by Skraye** [kestra-io/kestra#7044]
### Describe the issue

All line within the finally block should be yellow
![Image](https://github.com/user-attachments/assets/00645636-11b2-4ad8-b0d5-2ad7dad817d4)

Reproducer :
```yaml
id: finally
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: hello

finally:
  - id: for_each
    type: io.kestra.plugin.core.flow.ForEach
    values: ["value 1", "value 2", "value 3"]
    errors:
      - id: test
        type: io.kestra.plugin.core.log.Log
        message: ok
    tasks:
      - id: before_if
        type: io.kestra.plugin.core.debug.Return
        format: "Before if {{ taskrun.value }}"
      - id: if
        type: io.kestra.plugin.core.flow.If
        condition: '{{ taskrun.value == "value 2" }}'
        then:
          - id: after_if
            type: io.kestra.plugin.core.execution.Fail
```

### Environment

- Kestra Version: develop
