### ISSUE TITLE
[Regression] Remove the empty code block that shows up for each task description

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#7052]
### Describe the issue

To reproduce the issue, navigate to the **topology** view and try to view the task's **description**:

https://capture.dropbox.com/dVO4hNhsz5QEsn1o

Reproducer flow:

```yaml
id: orderProcessing
namespace: ecommerce
description: E-commerce Order Processing Workflow

inputs:
  - id: orderId
    type: STRING
    defaults: myorder

tasks:
  - id: checkInventory
    type: io.kestra.plugin.core.http.Request
    description: Check inventory for the order items
    uri: https://reqres.in/api/inventory-service/check

  - id: processPayment
    type: io.kestra.plugin.core.http.Request
    runIf: "{{ outputs.checkInventory.body.inventoryAvailable == true }}"
    description: Process payment for the order
    uri: https://reqres.in/api/payment-service/process
    
  - id: orderConfirmation
    type: io.kestra.plugin.core.http.Request
    runIf: "{{ outputs.processPayment.body.paymentResult == true }}"
    description: Confirm the order and notify the customer
    uri: https://reqres.in/api/order-service/confirm

  - id: arrangeShipping
    type: io.kestra.plugin.core.http.Request
    runIf: "{{ outputs.orderConfirmation.body.status == 'SUCCESS' }}"
    description: Arrange shipping for the order
    uri: https://reqres.in/api/shipping-service/arrange

  - id: updateDeliveryStatus
    type: io.kestra.plugin.core.http.Request
    description: Update the delivery status of the order
    uri: https://reqres.in/api/delivery-service/updateStatus
    runIf: "{{ outputs.arrangeShipping.body.status == 'SUCCESS' }}"

pluginDefaults:
  - type: io.kestra.plugin.core.http.Request
    values:
      contentType: multipart/form-data
      method: POST 
      formData:
        orderId: "{{inputs.orderId}}"
```

### Environment

- Kestra Version: develop (works fine on the latest 0.20.13)
