### ISSUE TITLE
The pluginDefaults should be a section, like tasks, triggers, and errors.

### ISSUE THREAD

**Issue by MilosPaunovic** [kestra-io/kestra#7064]
@Ben8t Do we have an idea on how it should look, as on the old Metadata editor it was just an Editor field, like it is now?

**Comment by anna-geller** [comment]
@Nico-Kestra we need a design for this, maybe we can reuse the same design as we wanted to add on a namespace level? do you remember Nico? this is the one we drew on a whiteboard during the last onsite https://www.figma.com/design/ew0uXk0NRXJ2NBBJTNe2n1/01_UI?node-id=4976-42281&t=8s5zIDux7S0N4NUu-4 

@MilosPaunovic if Nico doesn't get back to you on this, ping him :)

**Comment by Nico-Kestra** [comment]
Is it to include the default plugin in the no-code form?

**Comment by anna-geller** [comment]
@Nico-Kestra it's to replace this code block field for `pluginDefaults` with real no-code:

![image](https://github.com/user-attachments/assets/5dc57f13-2394-433e-9e5f-2046def4946e)

so instead of e.g.:

```yaml
pluginDefaults:
  - type: io.kestra.plugin.scripts.python
    forced: true
    values:
      containerImage: ghcr.io/kestra-io/kestrapy:latest
      taskRunner:
        type: io.kestra.plugin.core.runner.Process
      namespaceFiles:
        enabled: true
        exclude:
          - "sql/**"    
  - type: io.kestra.plugin.core.log.Log
    values:
      level: TRACE
```

we would need to have this as an array with sub-properties, e.g. an array where for each element you select the `type`, whether it's `forced` (boolean so it can be a toggle), and the `values`, which is another nested field with as many properties that can be configured as in the task itself
