### ISSUE TITLE
[UI] Dashboard refresh didn't work

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#7083]
### Describe the issue

This can be reproducible in our RC environment.

Create a flow with a pause in it:
```yaml
id: pause
namespace: company.team

tasks:
  - id: pause
    type: io.kestra.plugin.core.flow.Pause
    delay: PT30S
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀
```

Maunch it 5 times.
Goes to the Dashboards page, you should see something like that, notice the 5 executions in progress that you just launched

![Image](https://github.com/user-attachments/assets/119f28a6-d71c-45f2-802c-9e2c9e002e99)

Wait 30s.
Hit refresh, the 5 executions are still reported as running.
Refresh the page, the dashboard is refreshed and the 5 executions are no more reported as running.

### Environment

- Kestra Version: develop
