### ISSUE TITLE
Feature request. Output variables value assignment strategy

### ISSUE THREAD

**Issue by s0rr0w** [kestra-io/kestra#7105]
### Feature description

Hi team,
It will be useful to have different strategies for output variables when task assigns the values to them, especially for repeating/loop tasks. I consider the following strategies as most needed:

- Owerride. Default behavior. New values will override the previous ones
- Array. New values will be stored as new array item
- Set once. Value can be set only once.
- Merge. Merge two objects.

It can be global parameter for tasks which doesn't have `values` option, and strategy can be set separately for every single key of `values` declaration.

Examples:
```
id: loop_append
namespace: demo

tasks:
  - id: loop
    type: io.kestra.plugin.core.flow.WaitFor
    condition: "{{ outputs.return.value == '4' }}"
    tasks:
      - id: kv_set_loop
        type: io.kestra.plugin.core.kv.Set
        key: test
        value: "some_value"
        kvType: STRING
        setAs: ARRAY
      - id: out
        type: io.kestra.plugin.core.output.OutputValues
        values:
          iterations: "{{ outputs.loop.iterationCount }}" as ARRAY
```
