### ISSUE TITLE
Outputs tab => clicking on Debug outputs with a non existing variable sometimes makes thing disappear

### ISSUE THREAD

**Issue by brian-mulier-p** [kestra-io/kestra#7115]
### Describe the issue

Reproducer:
```
id: failing
namespace: io.kestra.bmu

tasks:
  - id: hello2
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀
  - id: failing
    type: io.kestra.plugin.core.execution.Fail
    runIf: "{{ taskRun.attempts.length == 1 }}"
  - id: hi2
    type: io.kestra.plugin.core.log.Log
    message: hi
```

Go to outputs tab, click on "failing" task and try to put "{{ ou }}", and click the Debug outputs button, everything disappear for some reasons, seems not to happen on the hello2 task so idk

### Environment

- Kestra Version: develop
