### ISSUE TITLE
Subflow expands within foreach in Topology view looks weird

### ISSUE THREAD

**Issue by brian-mulier-p** [kestra-io/kestra#7118]
### Describe the issue

```
id: for-each
namespace: io.kestra.bmu

tasks:
  - id: hey
    type: io.kestra.plugin.core.log.Log
    message: "Hello before"
  - id: hello
    type: io.kestra.plugin.core.flow.ForEach
    values: ["a", "b", "c"]
    tasks:
      - id: log
        type: io.kestra.plugin.core.log.Log
        message: "Hello {{taskrun.value}}"
      - id: subflow
        type: io.kestra.plugin.core.flow.Subflow
        namespace: io.kestra.bmu
        flowId: hello-world
      - id: log2
        type: io.kestra.plugin.core.log.Log
        message: "Hi again {{taskrun.value}}"
  - id: hi
    type: io.kestra.plugin.core.log.Log
    message: "Hello after"
```

![Image](https://github.com/user-attachments/assets/5345c4c8-8152-4663-bffe-45abcaaf2387)

### Environment

- Kestra Version: develop
