### ISSUE TITLE
Bring back pebble expressions highlighting in no-code Editor fields

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#7128]
### Feature description

Some no-code editor fields that users to have Monaco editor now lost their syntax highlighting - let's bring them back

![image](https://github.com/user-attachments/assets/5bee881c-8feb-4872-ad41-b8ed54269289)

Repro

```yaml
id: myflow
namespace: company.team

inputs:
  - id: user
    type: STRING
    defaults: anna

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello "{{ inputs.user }}"
```
