### ISSUE TITLE
The expected value is not registered in the key-value pair by http.request.

### ISSUE THREAD

**Issue by sasano8** [kestra-io/kestra#7135]
### Describe the issue

When I executed the workflow below, the expected value was not registered.

actual: "us"
expected: "us-east-1"

You can register from the WebUI without any problems, but it will not be registered correctly if you use the io.kestra.plugin.core.http.Request.

```
id: setup_default_kv
namespace: tutorial.builtin

tasks:
  - id: PUT_AWS_REGION
    type: io.kestra.plugin.core.http.Request
    uri: http://localhost:8080/api/v1/namespaces/tutorial.builtin/kv/AWS_REGION
    method: PUT
    contentType: application/json
    body: "us-east-1"

  - id: echo
    type: io.kestra.plugin.core.log.Log
    message: "{{ kv('AWS_REGION') }}"
```

![Image](https://github.com/user-attachments/assets/d23f32f3-5133-4314-8970-ddbd366703b5)

### Environment

- Kestra Version: develop

I'm using the latest version of docker image.
Maybe v0.20.

**Comment by sasano8** [comment]
I had made a beginner's mistake.
I solved it by surrounding it with single quotes.

```
id: setup_default_kv
namespace: tutorial.builtin

tasks:
  - id: PUT_AWS_REGION
    type: io.kestra.plugin.core.http.Request
    uri: http://localhost:8080/api/v1/namespaces/tutorial.builtin/kv/AWS_REGION
    method: PUT
    contentType: application/json
    body: '"us-east-1"'

  - id: echo
    type: io.kestra.plugin.core.log.Log
    message: "{{ kv('AWS_REGION') }}"
```
