### ISSUE TITLE
LABELS and PREFILL Error - Duplicate key type (attempted merging values)

### ISSUE THREAD

**Issue by ReLoutre** [kestra-io/kestra#7147]
### Describe the issue

Reproducer :
``` yaml
id: prefill_labelling_error_reproducer
namespace: test

inputs:
  - id: some_dummy_input
    type: SELECT
    values:
      - some
      - value

labels:
  some_key: SOME_VALUE

tasks:
  - id: label_exec
    type: io.kestra.plugin.core.execution.Labels
    labels:
      SELECTED_VALUE: "{{ inputs.some_dummy_input }}"
```
Steps to reproduce :
- execute the flow
- execute it a second time using the prefill tool

Expected fail on the second run :
`java.lang.IllegalStateException: Duplicate key some_key (attempted merging values SOME_VALUE and SOME_VALUE)`

Error display :
![Image](https://github.com/user-attachments/assets/cdb3b69a-01ec-49a5-abec-b33f3021510e)

### Environment

- Kestra Version: 0.21.0
- Env : Debian, Docker compose project, web access through Firefox
