### ISSUE TITLE
Execution Ouputs multiple enhancement  

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#7158]
When playing on outputs, you need to send the taskrun on this endpoint `${apiUrl(store)}/executions/${taskRun?.executionId}/eval/${taskRun.id}` to have a proper debugging for the current task (since the execution context change between task).

The actual debug is failing because: 
- each click on Debug Outputs button will unselected the value 
- if I have a flow with multiple tasks, the `${taskRun.id}` is always the first one 

For nested outputs, the value on the debug editor is also not displayed: 
![image](https://github.com/user-attachments/assets/0d6014b0-7e93-40c4-a9be-bf227ed5b9e0)

Some internal storage url is not displayed as preview / Download / Internal links: 
![image](https://github.com/user-attachments/assets/f7bd0815-e466-479c-bc5f-488fee132d13)

Right panel is not refresh: 
1. click on first tasks `sharepoint_data_extract`, the value is displayed 
  ![image](https://github.com/user-attachments/assets/ef222ca3-8370-4f42-bc7e-5618415b5fb0)
2. click on second tasks `debug-sharepoint`, the value of `sharepoint_data_extract` is still displayed that make this confusing 
  ![image](https://github.com/user-attachments/assets/3ec681d4-384f-4e14-892b-7a9b6f542c08)

<details><summary>Flow Example</summary>

```yaml
id: test
namespace: test
description: |
  testing

variables:
  resource_data_file: "{{ currentEachOutput(outputs.sharepoint_data_extract)['outputFiles']['resource_data.json'] }}"
  input_json: [ {"value":1}, {"value":2} ]


tasks:
 
  - id: run_sharepoint_resources_parallel
    type: io.kestra.plugin.core.flow.EachParallel
    concurrent: 1
    timeout: PT90M
    value:  "{{ render(vars.input_json)| jq('.[]') }}"
    tasks:
          - id: sharepoint_resource
            type: io.kestra.plugin.core.flow.EachSequential
            value: ["{{taskrun.value}}"]
            tasks:
                - id: sharepoint_data_extract
                  type: io.kestra.plugin.scripts.python.Script
                  #containerImage: ghcr.io/kestra-io/kestrapy:latest
                  script: |
                      import json

                      # Example data to write into the JSON file
                      resource_data = {
                          "resources": [
                              {"id": "ONE", "name": "Resource A", "type": "Type 1"},
                              {"id": "TWO", "name": "Resource B", "type": "Type 2"}
                          ]
                      }

                      # Write the JSON data to the output file
                      with open("resource_data.json", "w") as json_file:
                          json.dump(resource_data, json_file, indent=4)
                  outputFiles:
                    - "resource_data.json"

                - id: debug-sharepoint
                  type: io.kestra.plugin.core.debug.Return
                  format: |
                    {{ render(vars.resource_data_file) | json(true) }}

                - id: log-parsed-json
                  type: io.kestra.plugin.core.log.Log
                  message: >
                    {{ json(read(currentEachOutput(outputs.sharepoint_data_extract).outputFiles['resource_data.json']))['resources'][0]['id'] }}

                - id: if_no_files_to_process
                  #type: io.kestra.plugin.core.flow.If
                  type: io.kestra.plugin.core.flow.Switch
                  #condition: "{{ json(read(currentEachOutput(outputs.sharepoint_data_extract).outputFiles['resource_data.json']))['resources'][0]['id'] == true  }}"
                  #then:
                  value: "{{ json(read(render(vars.resource_data_file)))['resources'][0]['id'] }}" 
                  cases:
                    ONE:
                      - id: if-pass-output
                        type: io.kestra.plugin.core.debug.Return
                        format: |
                          {{ render(vars.resource_data_file) | json(true) }} 
                    defaults:
                      - id: default-output
                        type: io.kestra.plugin.core.debug.Return
                        format: |
                          {{ render(vars.resource_data_file) | json(true) }}
```

</details>
