### ISSUE TITLE
Concurrency not reflected

### ISSUE THREAD

**Issue by smunteankestra** [kestra-io/kestra#7159]
### Describe the issue

Flow
```yaml
id: autotest
namespace: autotest

concurrency:
  limit: 2

tasks:
  - id: wait
    type: io.kestra.plugin.scripts.shell.Commands
    commands:
      - sleep 10
```
### Environment

- Kestra Version: `develop`
