### ISSUE TITLE
Selection of nr of rows per page in custom dashboard tables has no effect

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#7164]
### Describe the issue

![image](https://github.com/user-attachments/assets/19ed8e55-8b35-4a7a-85a4-4b5375760060)

Changing to 10 rows still shows a table of the same size

### Environment

- Kestra Version: develop

**Comment by MilosPaunovic** [comment]
This a a bit deeper problem. I've stared investigating it, and, as part of it, closed https://github.com/kestra-io/kestra/issues/6919, and now the only issue that seems to remain is the problem where the endpoint is not returning the proper amount for `total`, but just the sum of results in that request.

To elaborate further:

- By using this code create a custom dashboard:
```yaml
title: All Success Executions
description: Table with all SUCCESS state executions

timeWindow:
  default: P30D
  max: P365D

charts:
  - id: executions_all
    type: io.kestra.plugin.core.dashboard.chart.Table
    chartOptions:
      displayName: All Executions
      description: List all executions with SUCCESS state
    data:
      type: io.kestra.plugin.core.dashboard.data.Executions
      columns:
        id:
          field: ID
        namespace:
          field: NAMESPACE
        flowId:
          field: FLOW_ID
        duration:
          field: DURATION
        state:
          field: STATE
      where:
        - field: STATE
          type: IN
          values:
            - SUCCESS
```

- Make sure to have a 10+ successful executions.
- First endpoint is sending `{page: 1, size: 10}` as parameters, and returns the `data` array of 10 items and `total` field with the value 10, even if there are hundreds of executions in the desired state.

#### How to confirm it:

- In `kestra/ui/src/components/dashboard/components/tables/custom/Table.vue` component, change the line `18` which is now `:total="data.total"` to a fixed number, e.g. `:total="120"`, and you'll see pagination pages rendering properly now and proper parameters being passed to the endpoint.

So, in conclusion, I've done the UI part in the PR mentioned above, and this is now left with a purely BE fix to be made. Will assign @Skraye as he worked on Custom Dashboards recently, if in the wrong, please re-assign.
