### ISSUE TITLE
[Post-Release] Add Breaking Changes for 0.22 to GitHub Release Notes

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#7169]
### EE: Default tenant deprecation

Multi-tenancy was introduced in Kestra 0.13. For backward compatibility with older versions (≤0.12), you could use the concept of a default tenant, which imitated the multitenancy feature with the so-called “null”-tenant. One and a half years later, in Kestra 0.22, we are deprecating the default tenant functionality and plan to remove it in the future. We will provide a detailed migration guide for all customers who still use the default tenant. Until then, you can continue using `defaultTenant` by setting the corresponding configuration flag to `true`:

```yaml
kestra:
  tenants:
    enabled: true
    defaultTenant: true
```

Note that in Kestra 0.22 and higher, `defaultTenant` is NOT enabled by default, so you must explicitly set that configuration option to `true` to keep using the default tenant.

Also, keep in mind that prior to Kestra 0.22, `tenants.enabled` was by default set to `false` and now they are enabled.

### EE: Azure log exporter

The log exporter plugin for Azure `io.kestra.plugin.ee.azure.LogExporter`, introduced in Kestra 0.21, got split into two `io.kestra.plugin.ee.azure.monitor.LogExporter` and `io.kestra.plugin.ee.azure.storage.LogExporter` to reflect that you can now export your log to Azure either using Azure Monitor or using Azure Blob Storage.

### EE: Enterprise Edition API changes

Before Kestra 0.22, the Service Account name had to be globally unique within the instance. As a result, attempting to create a Service Account `cicd` in a `dev` tenant would raise an error `"Username already exists"` if your `prod` tenant also has a Service Account with the name `cicd`. 

To support multiple service accounts with the same name, we’ve renamed the `username` property to `name` in the JSON payload for the following REST API endpoint: `POST /api/v1{/tenant}/users/service-accounts{/id}`.

### EE: Too many failed login attempts now lock the account

To improve the security of your Enterprise Edition instance, we now automatically lock user accounts after a `threshold` number of failed login attempts made within `monitoring-window`. Both, the number of failed attempts, the monitoring window to track consecutive number of failed attempts and (soon) the duration of how long the user remains locked are configurable.

```yaml
security:
  login:
    failed-attempts:
      threshold: 10
      monitoring-window: PT15M    # period to count failed attempts
      # lockout-duration: PT24H      # period the account remains locked — will be added in the next release
```

Note that this change is only relevant for users who leverage LDAP or basic authentication (not relevant for SSO-users). Superadmin can unlock the user manually by resetting their password from the user's detail page.

### Change to `readinessProbe` and `livenessProbe`

Before [this PR](https://github.com/kestra-io/helm-charts/pull/62/files), both probes pointed to `/health`. This caused Kubernetes to restart the pod when an external component was unavailable. To resolve this, we updated the value file to configure the liveness and readiness probes to use the health paths recommended by Micronaut:

- Liveness probe now points to `/health/liveness`
- Readiness probe now points to `/health/readiness`.

### Plugins using the `version` property

With the introduction of plugin versioning, we reserve the `version` keyword for internal use, allowing us to specify the Kestra plugin version. As a result, we’ve renamed the `version` property for a few plugins that already used it, incl. the following:

- `io.kestra.plugin.elasticsearch.Get` → renamed as `docVersion`
- `io.kestra.plugin.opensearch.Get` → renamed as `docVersion`
- `io.kestra.plugin.mqtt.RealtimeTrigger` → renamed as `mqttVersion`
- `io.kestra.plugin.mqtt.Trigger` → renamed as `mqttVersion`
- `io.kestra.plugin.serdes.parquet.IonToParquet` → renamed as `parquetVersion`

Note that your **custom plugins** will need an equivalent approach of renaming any plugin that uses the `version` property, as this is now a core property reserved for plugin management. If any of your custom plugins rely on a `version` property, they won't compile anymore unless you rename that property to a different name.

### Change in the default value for the `kv()` function

Before Kestra 0.22, the `kv()` function had the property `errorOnMissing` set to `false` by default. We changed it to be `true` by default. If you want to keep the previous behavior of returning `null` without an error when attempting to fetch non-existing KV-pairs, use the syntax `"{{ kv('NON_EXISTING_KV_PAIR', errorOnMissing=false) }}"`.

**Comment by loicmathieu** [comment]
3 missing BC (from the PR label):
https://github.com/kestra-io/kestra/issues/971
https://github.com/kestra-io/kestra-ee/pull/3162
https://github.com/kestra-io/kestra-ee/pull/3068

**Comment by Ben8t** [comment]
Also now KV store values are mandatory:
> It has been decided that missing KV now throws an exception.

For example this was not breaking before 0.22 if the KV values were not set:

```yaml
id: infrastructure-automation
namespace: sanitychecks.flows.blueprints
description: Infrastructure Automation
inputs:
  - id: docker_image
    type: STRING
    defaults: kestra/myimage:latest
tasks:
  - id: build_image
    type: io.kestra.plugin.docker.Build
    dockerfile: |
      FROM python:3.11-alpine
      RUN pip install --no-cache-dir kestra
    tags:
      - "{{ inputs.docker_image }}"
    push: false # you can change this to true after adding credentials
    credentials:
      registry: https://index.docker.io/v1/
      username: "{{ kv('DOCKERHUB_USERNAME') }}"
      password: "{{ kv('DOCKERHUB_PASSWORD') }}"
```

Now it fails

PR for doc update https://github.com/kestra-io/docs/pull/2382

**Comment by anna-geller** [comment]
most important: default tenant deprecation https://github.com/kestra-io/kestra-ee/issues/3237

**Comment by nkwiatkowski** [comment]
Breaking changes on the log shipper: the property batchSize has been remove:
```yml
tasks:
  - type: io.kestra.plugin.ee.core.log.AuditLogShipper
    id: synchronize_logs
    resources:
      - FLOW
      - EXECUTION
    ~~batchSize: 2~~
```
