### ISSUE TITLE
reverse order for forEachItem

### ISSUE THREAD

**Issue by MarthaScheffler** [kestra-io/kestra#7170]
### Feature description

I would like to be able to manipulate (reverse) the order that subflows are started with when using forEachItem.

use case/example:
I'm doing a database query and get a couple of IDs as result. Then I start a subflow for each of these IDs with forEachItem. I want to start a second set of subflows with forEachItem from the same result set, but with the inverse order (starting with the last ID). I can't run the query again with changed ORDER BY, as I might get a different result then first time.

````
id: for_each_item_order
namespace: kestra.sandbox

tasks:     
      - id: read_items
        type: io.kestra.plugin.jdbc.duckdb.Query
        url: 'jdbc:duckdb:'
        timeZoneId: Europe/Paris
        sql: |-
          SELECT 1 AS item
          UNION ALL
          SELECT 2 AS item;
        fetchType: STORE

      - id: ion_to_jsonl
        type: io.kestra.plugin.serdes.json.IonToJson
        from: "{{ outputs.read_items.uri }}"
        newLine: true

      - id: for_each_item
        type: io.kestra.plugin.core.flow.ForEachItem
        items: "{{ outputs.ion_to_jsonl.uri }}"
        batch:
          rows: 1
        flowId: subflow_1
        namespace: "{{ flow.namespace }}"
        inputs:
          number: "{{ json(read(taskrun.items)).item }}"

      - id: for_each_item_reversed
        type: io.kestra.plugin.core.flow.ForEachItem
        #here I would like the items in reversed order
        items: "{{ outputs.ion_to_jsonl.uri - reverse this somehow}}"
        batch:
          rows: 1
        flowId: subflow_2
        namespace: "{{ flow.namespace }}"
        inputs:
          number: "{{ json(read(taskrun.items)).item }}"
````

If my subflows both have a concurrency limit of 1, then I want that subflow_1 first starts with item 1 and then afterwards runs item 2.
While subflow_2 is doing it reversed: it will first run with item 2, and afterwards item 1.

if I use a list as input for forEach, I can use the pebble for reversed list. But I want to use forEachItem, and not use an additional script e.g. Python.
