### ISSUE TITLE
Docker container fails due to DNS resolution

### ISSUE THREAD

**Issue by nikolicdragoslav** [kestra-io/kestra#7224]
### Describe the issue

When flow Kestra runs Docker container which is supposed to interact with Redshift through Python / psycopg2 library, it fails due to DNS resolution:
```
Failed to write dbt log to main_meta.dbt_run_logs, could not translate host name "[merklecdp-redshift-cluster-dev.eu-central-1.redshift.amazonaws.com](http://merklecdp-redshift-cluster-dev.eu-central-1.redshift.amazonaws.com/)" to address: Name does not resolve. 
```

The goal is to investigate why it happens.

This is the workflow:
```
id: runDbt
namespace: example 
description: Generated flow that executes curated DBT model
labels:
  taskTitle: Run curated DBT model
  showInUI: "true"
  isRootFlow: "false"

variables:
  dbt_repo_url: 'url'
  dbt_repo_branch: 'dev'
  docker_image: 'image'
tasks:
  - id: dbt
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      - id: cloneRepository
        type: io.kestra.plugin.git.Clone
        url: "{{vars.dbt_repo_url}}"
        branch: "{{vars.dbt_repo_branch}}"
        username: "{{ secret('GIT_USERNAME') }}"
        password: "{{ secret('GIT_PASSWORD') }}"

      - id: dbtCommands
        type: io.kestra.plugin.dbt.cli.DbtCLI
        retry:
          maxAttempt: 1
          type: constant
          interval: PT5M
          warningOnRetry: true
        namespaceFiles:
          enabled: true
        # containerImage: "{{vars.docker_image}}:main"
        outputFiles:
          - output/executed_tables.txt
        taskRunner:
          type: io.kestra.plugin.scripts.runner.docker.Docker
          image: "{{vars.docker_image}}:main"
          networkMode: "host"
          credentials:
            auth: "{{ secret('DOCKER_CREDENTIALS') }}"
        env:
          DWH_TYPE: "{{envs.dwh_type}}"
          DWH_ACCOUNT: "{{envs.dwh_account}}"
          DWH_DATABASE: "{{envs.dwh_database}}"
          DWH_HOST: "{{envs.dwh_host}}"
          DWH_PORT: "{{envs.dwh_port}}"
          DWH_CLUSTER: "{{envs.dwh_cluster}}"
          DWH_APP_USER_NAME: "{{envs.dwh_app_user_name}}"
          DWH_APP_USER_PASSWORD: "{{ secret('DWH_APP_USER_PASSWORD') }}"
        beforeCommands:
          - chmod 777 scripts/dbt-run.sh
        commands: 
          - scripts/dbt-run.sh --project-dir dbt/main --profiles-dir dbt --models +curated__apavel_bo_006 --target dev-main

      - id: print-result
        type: io.kestra.plugin.core.log.Log
        message: "Results:  {{ read(outputs.dbtCommands.outputFiles['output/executed_tables.txt'])}}"          

  - id: graphQlPutTableTrigger
    type: io.kestra.plugin.core.flow.Subflow
    namespace: utility
    flowId: graphQlPutTable
    inputs:
      schema_name: "main_curated"
      table_name: "apavel_bo_006"
    wait: true
    transmitFailed: true
```

By adding this line 
```- echo "nameserver <ip_address>" > /etc/resolv.conf```
we were able to force correct cluster DNS.

I am attaching a log print exported from Kestra, keep in mind I removed a part of the redshift cluster  address in order to not share the exact url with the world.

[kestra-execution-20250206155256-7PG3Y3ahwI84mtLpSh4jSL-6OIs3XsIv2nluPdJk1kDgW.log](https://github.com/user-attachments/files/18691862/kestra-execution-20250206155256-7PG3Y3ahwI84mtLpSh4jSL-6OIs3XsIv2nluPdJk1kDgW.log)

### Environment

- Kestra Version: 0.20.7
- OS: Kubernetes
