### ISSUE TITLE
Backfills don't work if trigger has a timezone set

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#7227]
### Describe the issue

If you have a trigger set up using the `timezone` property like the example below:
```yaml
triggers:
  - id: green_schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 9 1 * *"
    timezone: Europe/Berlin
    inputs:
      taxi: green
```
It displays correctly inside of the **Triggers tab** for the next Scheduled execution
![Image](https://github.com/user-attachments/assets/6bc3d24f-9185-4cf9-9bb6-8618f0b75069)

However, if you run a Backfill with a valid range, it will let you start it and claims it finished, but no executions were created.

In this video, I set up a Backfill between 1st January 2019 and the 31st March 2019. It should have 3 separate executions created, yet when we refresh the Triggers page, it shows the backfill as complete and the Executions page remains empty.

https://github.com/user-attachments/assets/2c7236a5-e303-409f-b5ac-a0b0f872cbb4

Full flow can be found here, but you will need to add the `timezone` property like above: https://github.com/DataTalksClub/data-engineering-zoomcamp/blob/main/02-workflow-orchestration/flows/02_postgres_taxi_scheduled.yaml

### Environment

- Kestra Version: `latest` 0.21 OSS pulled today

**Comment by wrussell1999** [comment]
Someone else was having this issue (From the DTC DE Zoomcamp) and I was able to reproduce it.

![Image](https://github.com/user-attachments/assets/bd58197b-a1da-481a-861e-9cc318c9b3bb)

**Comment by wrussell1999** [comment]
This bug seems to only happen sometimes. Here are some clear steps to reproduce it:

1. Use a completely new [Docker Compose file](https://github.com/kestra-io/kestra/blob/develop/docker-compose.yml)
2. Create a new Flow and paste in the following flow below as an example
3. Save it and go to Triggers and press Backfill executions
4. Select a large date range. I set it to `2020-02-01 00:00:00` to now (`2025-02-07 13:58:51`
5. Add a label such as `backfill: true` to make it easier to spot which ones are backfills
6. Press execute

```yaml
id: purge_bug
namespace: company.team

tasks:
  - id: test_request
    type: io.kestra.plugin.core.http.Request
    uri: https://www.google.com
    method: GET
    options:
      connectionPoolIdleTimeout: PT1M
    retry:
      maxAttempt: 1
      type: constant
      interval: PT1S

triggers:
  - id: green_schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 9 1 * *"
    timezone: Europe/Berlin
```

![Image](https://github.com/user-attachments/assets/92bc8d4b-b718-411a-bd1d-dfcac82ae482)

When I did this, it was taking its time to complete the backfill, but no executions were visible in the Executions page for the flow or under the main Executions page in the side menu.

If you remove the `timezone` property, it will work and generate executions. My example used 1st January 2024 to now:

![Image](https://github.com/user-attachments/assets/c2137078-cb70-40bc-80f9-46c088023b3b)
