### ISSUE TITLE
The order of log entries in the Kestra interface is broken

### ISSUE THREAD

**Issue by apavel07** [kestra-io/kestra#7243]
### Describe the issue

I run python scripts in a docker container and print log. 
In Kestra inferface log lines are mixed up, the order is broken. 
I tryed diifferent ways to print logs, but it doesn't matter, which loger I use

```
# Example 1
for i in range(100):
    print(f"a_{i}")

# Example 2
from kestra import Kestra
logger = Kestra.logger()
for i in range(100):
    logger.info(f"c_{i}")
```

---------------------------------

```
id: sqlCreateSandbox
namespace: example
tasks:
- id: create
  type: "io.kestra.plugin.docker.Run"
  namespaceFiles:
    enabled: true
  containerImage: ghcr.io/merkle-dach/merklecdp-kestra-core-sql:dev
  credentials:
    auth: "{{ secret('DOCKER_CREDENTIALS') }}"
  commands:
    - /home/default/app/scripts/v1/app_test_kestra_logs.py    
```

---------------------------------

![Image](https://github.com/user-attachments/assets/58c8c98f-7366-4615-bc41-de881fa218af)

### Environment

Kestra Version: 0.20.7
OS: Kubernetes
