### ISSUE TITLE
AutoScroll on log during execution are not following log anymore

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#7252]
In the past, the scrolling of the logs are in realtime and auto scroll to follow last emitted logs. 

There is a regression and now it's not working anymore, I need to manually scroll to follow the execution. 

[Screencast_20250207_201450.webm](https://github.com/user-attachments/assets/ad930d1e-762a-4966-a4b6-a0bd00423a41)

**Comment by rajatsingh23** [comment]
Can I give it a try? Also, I’ll need an example flow to reproduce it.

**Comment by MilosPaunovic** [comment]
@Ben8t Maybe you could help us here with the reproduction flow?

**Comment by tchiotludo** [comment]
```yaml 
id: longRunning
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.scripts.shell.Script
    script: | 

      for i in $(seq 0 100;); do
        echo $i
        sleep 0.1
      done
```
