### ISSUE TITLE
Sublfow task validator render bug

### ISSUE THREAD

**Issue by ReLoutre** [kestra-io/kestra#7271]
### Describe the issue

![Image](https://github.com/user-attachments/assets/64f34ef8-0aec-40aa-96d4-260476311893)

Flow validator do not render the dynamic output and so is unable validate successfully the yaml.
Yet on my instance it does execute successfully anyway and the error doesn't prevent me to save using CTRL-S.

Here's a really simple reproducer :
```yaml
id: subflow_dynamic_property_bug_reproducer
namespace: iut.cri.bug_reproducers

tasks:
  - id: call_subflow_with_pebble_namespace
    type: io.kestra.plugin.core.flow.Subflow
    flowId: some_subflow
    namespace: "{{ flow.namespace }}"
```

With its called dummy sublfow :
``` yaml
id: some_subflow
namespace: iut.cri.bug_reproducers

tasks:
  - id: log
    type: io.kestra.plugin.core.log.Log
    message: hello world
```
Executing this reproducer does indeed render and execute successfully the sub flow :

![Image](https://github.com/user-attachments/assets/9c2d7a53-4a00-4d4f-bcd0-d830889fe195)

### Environment

- Kestra Version: 0.21.1
