### ISSUE TITLE
Unable to trigger flow from transient state

### ISSUE THREAD

**Issue by paulgrainger85** [kestra-io/kestra#7281]
### Describe the issue

From [this](https://github.com/kestra-io/kestra/pull/4975) recent addition we should be able to trigger flows from transient states such as `RUNNING` 

This does not appear to work as expected. Take the below flows. "triggered_flow" will never start

```
id: triggered_flow
namespace: paul_dev.support

triggers:
  - id: flow
    type: io.kestra.plugin.core.trigger.Flow
    preconditions:
      id: myid
      flows:
       - flowId: long_flow
         namespace: paul_dev.support
         states:
           - RUNNING

tasks:
  - id: trigger_sucess
    type: io.kestra.plugin.core.log.Log
    message: triggered! {{ trigger.state }}
```

```
id: long_flow
namespace: paul_dev.support

tasks:
  - id: sleep
    type: io.kestra.plugin.core.flow.Sleep
    duration: PT30S
  - id: log
    type: io.kestra.plugin.core.log.Log
    message: we're done
```

### Environment

- Kestra Version: 0.21.1

**Comment by paulgrainger85** [comment]
Nothing required here, flow should be 

```
triggers:
  - id: flow
    type: io.kestra.plugin.core.trigger.Flow
    states:
      - RUNNING
      - KILLED
    preconditions:
      id: myid
      flows:
       - flowId: long_flow
         namespace: paul_dev.support
         states:
           - RUNNING
           - KILLED
```
