### ISSUE TITLE
Add additional param to merge() function for deep merge

### ISSUE THREAD

**Issue by s0rr0w** [kestra-io/kestra#7302]
### Current state
Currently merge() function doesn't really merge objects. If you have the declaration
```
- id: vars
  type: io.kestra.plugin.core.output.OutputValues
  values:
    obj:
      a:
        x: "will be removed"
        b:
          c: {}
          d: 2
```
And you merge it using standard `merge()` function
```
{{ outputs.vars.obj | merge( { "a": { "b": { "c": { "new": "data" } } } } ) }}
```
The resulting object will be the same as passed to merge function. 

### New functionality
Accept `deep` param for `merge( obj [,deep] )` function that will allow non-destructive deep merge.
