### ISSUE TITLE
Support !!map type cast

### ISSUE THREAD

**Issue by s0rr0w** [kestra-io/kestra#7303]
### Current state
Current implementation doesn't allow to merge 2 objects (JSONs)
The following declaration assigns string instead of object
```
obj:
  test: "{{ inputs.json }}"
```

### New functionality
Support standard YAML !!map type cast declaration.
```
  test: !!map "{{ inputs.json }}"
```
The assigned value should be HashMap, not a String.

**Comment by s0rr0w** [comment]
I would extend the support to the `!!int` type cast as well.

**Comment by s0rr0w** [comment]
Test case:
```
id: json_test
namespace: test.test

tasks:

  - id: vars
    type: io.kestra.plugin.core.output.OutputValues
    values:
      data:
        timestamp: "{{ now() | timestamp(timeZone='UTC') }}"

  - id: log
    type: io.kestra.plugin.core.log.Log
    message: "{{ outputs.vars.values.data }}"
```
Output result:
```
{"timestamp":"1739281345"}
```
Timestamp is a string instead of number.
