### ISSUE TITLE
Git.sync doesn't work at the HTTP layer

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#7364]
```
id: git_sync
namespace: sanitychecks

tasks:
  - id: git_sync
    type: io.kestra.plugin.git.SyncFlows
    url: https://github.com/kestra-io/blueprints
    gitDirectory: sanitychecks
    targetNamespace: sanitychecks
    includeChildNamespaces: true
```

![image](https://github.com/user-attachments/assets/bb3e63a6-5ce2-47c2-84ea-9a7486676fd9)

Probably related to recent changes in underlying HTTP client

### Environment

- Kestra Version: develop
