### ISSUE TITLE
Possible to save bad flow which runs idefinitely

### ISSUE THREAD

**Issue by paulgrainger85** [kestra-io/kestra#7387]
### Describe the issue

Consider the parent and subflow below. Notice that the type is incorrect, it should be Subflow, not subflow. Kestra UI allows us to save this flow. 
```
id: parent
namespace: abc

tasks:
  - id: hello
    type: io.kestra.plugin.core.flow.subflow
    flowId: child
    namespace: abc
-------
id: child
namespace: abc

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀
```

The subflow is executed correctly, but the parent flow remains running indefinitely (until manually killed). 

What should be the correct behavior here? (stop flow from being saved in the first place, or allow case-insensitive type definition) 

![Image](https://github.com/user-attachments/assets/ccbd1134-ce0f-4804-92f1-e685c7aed436)

### Environment

- Kestra Version: 0.21.2
