### ISSUE TITLE
No Code - Condition should be a proper form

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#7388]
### Feature description

![image](https://github.com/user-attachments/assets/0c55bfa4-840f-470e-a61f-089c076d9aef)

**Comment by anna-geller** [comment]
@MilosPaunovic to provide more details, what Ben meant was likely trigger conditions, you can reproduce using:

```yaml
id: conditions
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 

triggers:
  - id: flow
    type: io.kestra.plugin.core.trigger.Flow
    conditions:
      - type: io.kestra.plugin.core.condition.ExecutionNamespace
        namespace: company.team
        comparison: PREFIX
```
