### ISSUE TITLE
Navigating to Definitions from property description within plugin docs sometimes doesn't work (example: DbtCLI task)

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#7390]
See demo https://capture.dropbox.com/FFvJlqyLWmgDuF1y

@MilosPaunovic if you don't know how to tackle this, @brian-mulier-p might be able to help as he worked quite a lot on plugin docs

![image](https://github.com/user-attachments/assets/94d8d4aa-178e-4a92-b4fd-68a1e681dedf)

Example repro:

```yaml
id: dbt_build
namespace: company.datateam.dbt

tasks:
  - id: dbt
    type: io.kestra.plugin.dbt.cli.DbtCLI
    namespaceFiles:
      enabled: true
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
    containerImage: ghcr.io/kestra-io/dbt-duckdb:latest
    commands:
      - dbt build --project-dir dbt
```

### Environment

- Kestra Version: develop
