### ISSUE TITLE
Auto-expand the first input on the Execution overview page

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#7392]
### Describe the issue

repro:

```yaml
id: file
namespace: company.team

inputs:
  - id: file
    type: FILE

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: flow with file
```

![image](https://github.com/user-attachments/assets/818c8160-4a6c-4662-83d9-adb93bd53e8b)

in the past, before we added the expand/collapse columnar layout, you could immediately see the preview/download button here and as a result, it had a friendlier UX — we should bring that experience back by auto-expanding this:

![image](https://github.com/user-attachments/assets/0d73b521-0b3e-4c77-8e8d-d554b3f97473)

### Environment

- Kestra Version: develop
