### ISSUE TITLE
Alert blocks like ::alert are not rendered in the recently changed plugin docs on latest

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#7393]
### Describe the issue

![image](https://github.com/user-attachments/assets/167cb7da-bab3-49f2-99b2-d4633c47c90f)

repro - create the flow and go to Flow trigger, state property:

```yaml
id: flowB
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 

triggers:
  - id: flowA
    type: io.kestra.plugin.core.trigger.Flow
    states:
      - SUCCESS
    conditions:
      - type: io.kestra.plugin.core.condition.ExecutionOutputs
        expression: "{{ trigger.outputs.flowAoutput == 'hello' }}"
```

### Environment

- Kestra Version: latest
