### ISSUE TITLE
[Windows] python startup bug: The system cannot find the path specified.

### ISSUE THREAD

**Issue by karimazz** [kestra-io/kestra#740]
### Expected Behavior

within in linux OS the python script works perfectly fine. im currently running kestra on windows OS with the following command: "kestra-0.5.0.bat server local" 

the kestra flow source code looks like this:
```yaml
  - id: python
    type: io.kestra.core.tasks.scripts.Python
    args:
      - data.json
    exitOnFailed: false
    inputFiles:
      data.json: |
        {"status": "OK"}
      main.py: |
        print(f"python script {result['status']}")
        from kestra import Kestra
        import json
        import requests
        import sys
        result = json.loads(open(sys.argv[1]).read())
        print(f"python script {result['status']}")
        response = requests.get('http://google.com')
        print(response.status_code)
        Kestra.outputs({'status': response.status_code, 'text': response.text})
      pip.conf: |
        # some specific pip repository configuration
    interpreter: cmd
    interpreterArgs:
      - /c
    requirements:
      - requests
```

### Actual Behaviour

I get the following error:
![image](https://user-images.githubusercontent.com/83555835/190622179-e331dafa-082a-4dc3-88b6-e9d6a443c8dd.png)

it seems like the starting command is linux based and i would like to change it to windows based.

### Steps To Reproduce

1. Windows 10 OS
2. kestra-0.5.0.bat server local
3. Run the kestra source code

### Environment Information

- Kestra Version: 0.5.0
- Windows 10
- Java Version 11

### Example flow

```yaml
id: TESATAST
namespace: tesstt
revision: 10
tasks:
  - id: bash
    type: io.kestra.core.tasks.scripts.Bash
    commands:
      - "echo \"The current execution is : {{execution.id}}\""
    exitOnFailed: false
    interpreter: cmd
    interpreterArgs:
      - /c
  - id: python
    type: io.kestra.core.tasks.scripts.Python
    args:
      - data.json
    exitOnFailed: false
    inputFiles:
      data.json: |
        {"status": "OK"}
      main.py: |
        print(f"python script {result['status']}")
        from kestra import Kestra
        import json
        import requests
        import sys
        result = json.loads(open(sys.argv[1]).read())
        print(f"python script {result['status']}")
        response = requests.get('http://google.com')
        print(response.status_code)
        Kestra.outputs({'status': response.status_code, 'text': response.text})
      pip.conf: |
        # some specific pip repository configuration
    interpreter: cmd
    interpreterArgs:
      - /c
    requirements:
      - requests
```
