### ISSUE TITLE
@NotNull properties with a default throw a warning in the editor

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#7406]
### Describe the issue

![image](https://github.com/user-attachments/assets/a235a21e-41f8-4008-90a0-6c323fa5641a)
![image](https://github.com/user-attachments/assets/4156d36c-61da-4a24-8a19-ddd33552b1f0)

example repro:
```yaml
id: data-engineering-pipeline
namespace: tutorial
description: Data Engineering Pipelines

inputs:
  - id: columns_to_keep
    type: ARRAY
    itemType: STRING
    defaults:
      - brand
      - price

tasks:
  - id: extract
    type: io.kestra.plugin.core.http.Download
    uri: https://dummyjson.com/products

  - id: transform
    type: io.kestra.plugin.scripts.python.Script
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
    containerImage: python:3.11-alpine
    inputFiles:
      data.json: "{{ outputs.extract.uri }}"
    outputFiles:
      - "*.json"
    script: |
      import json
      import os

      with open("data.json", "r") as file:
          data = json.load(file)

      filtered_data = [
          {column: product.get(column, "N/A") for column in {{ inputs.columns_to_keep }}}
          for product in data["products"]
      ]

      with open("products.json", "w") as file:
          json.dump(filtered_data, file, indent=4)
```

### Environment

- Kestra Version: develop
