### ISSUE TITLE
Working Directory Pebble Template Variable Missing (Throws an Error) — Unable to find `workingDir` used in the expression `["export WORKING_DIRECTORY={{ workingDir }}"]`

### ISSUE THREAD

**Issue by sceptri** [kestra-io/kestra#7437]
### Describe the issue

With the new release 0.21.0 (and onward) the `WorkingDirectory` task in conjunction with the `{{ workingDir }}` pebble variable now throws the following error:
```
Unable to find `workingDir` used in the expression `{{ workingDir }}` at line 1
```

Minimal working example:
```
id: working_dir
namespace: tests

tasks:
  - id: working-dir
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      - id: debug
        type: io.kestra.plugin.core.log.Log
        message: "{{ workingDir }}"
```

### Environment

- Kestra Version: 0.21.*
- Operating System and Java Version (if not using Kestra Docker image): NixOS, jdk 17

**Comment by anna-geller** [comment]
Reproducer:

```yaml
id: lapwing_324848
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.scripts.python.Commands
    beforeCommands:
      - export WORKING_DIRECTORY={{ workingDir }}
    commands:
      - echo $WORKING_DIRECTORY
```

The same works fine on Script tasks:

```yaml
id: lapwing_324848
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.scripts.python.Script
    script: |
      print("{{ workingDir }}")
```
