### ISSUE TITLE
Request proxy config DIRECT

### ISSUE THREAD

**Issue by nkwiatkowski** [kestra-io/kestra#7449]
### Describe the issue

When using http proxy with a Request, the proxy type is forced to DIRECT, resulting in this error:
DataRequest
type DIRECT is not compatible with address admin-proxy.ksgdom.ksg.intern/10.100.5.11:8080

example:
```yaml
id: request
namespace: company.team

tasks:
  - id: DataRequest
    type: io.kestra.plugin.core.http.Request
    uri: https://www.google.com
    options:
      #proxyType: HTTP
      #proxyAddress: admin-proxy.ksgdom.ksg.intern
      #proxyPort: 8080
      proxy:
        address: admin-proxy.ksgdom.ksg.intern
        port: 8080
        type: HTTP
```

### Environment

- Kestra Version: `develop`
