### ISSUE TITLE
UI - Topology - Node broken when opening a subflow

### ISSUE THREAD

**Issue by Skraye** [kestra-io/kestra#7488]
### Describe the issue

When you open a subflow (the broken hello node is the parent class):

![Image](https://github.com/user-attachments/assets/0bca65c3-135d-4df6-928b-130cbb7ab852)

### Environment

- Kestra Version: develop

**Comment by anna-geller** [comment]
reproducer:

```yaml
id: child
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 
````

and:

```yaml
id: parent
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.core.flow.Subflow
    namespace: company.team
    flowId: child
```
