### ISSUE TITLE
Flow Validation - with Service Now

### ISSUE THREAD

**Issue by marora** [kestra-io/kestra#7497]
### Describe the issue

Using [plugin-servicenow](https://kestra.io/plugins/plugin-servicenow), I get this error: 

`Unable to validate the flow: HV000030: No validator could be found for constraint 'jakarta.validation.constraints.NotEmpty' validating type 'io.kestra.core.models.property.Property<java.util.Map<java.lang.String

java.lang.Object>>'. Check configuration for 'errors[1].data'`

This is the configuration used: 
```yaml
  - id: create_servicenow_ticket
    type: io.kestra.plugin.servicenow.Post
    domain: "snow_domain"
    username: "snow_username"
    password: "snow_password"
    clientId: "snow_client_id"
    clientSecret: "snow_client_secret"
    table: incident
    data:
      short_description: "API Create Incident..."
      requester_id: f8266e2adb16fb00fa638a3a489619d2
      requester_for_id: a7ec77cbdefac300d322d182689619dc
      product_id: 01a2e3c1db15f340d329d18c689ed922  
```

### Environment

- Kestra Version: 0.21.3
