### ISSUE TITLE
Updating the script via API does not show update in the Kestra UI

### ISSUE THREAD

**Issue by aucubin** [kestra-io/kestra#7499]
### Describe the issue

Repro:

- Change something on a namespace file in the Kestra UI and save it. After refreshing the page the change should still be there.
- Upload an older version of the namespace file via the `api/v1/namespaces/$namespace/files` route using curl or some other tool.
- Refresh the UI tab from before and you will see that the change from the API request is not there.
- The only way to see that the API change was applied is by exporting the namespace files via the API or by disabling the cache in the network tools and then refreshing the tab.

### Environment

- Kestra Version: 0.21.3

**Comment by surya9teja** [comment]
I have experienced the similar kind of issue with version 0.22.0 but with git sync when I make local changes -> push the script changes to remote git -> execute git sync flow in kestra -> the script should be updated but it didn't

```
id: git_sync
namespace: system

tasks:
  - id: sync_internal_flows
    type: io.kestra.plugin.git.SyncFlows
    targetNamespace: microform.internal
    gitDirectory: flows/internal
    includeChildNamespaces: true

  - id: sync_internal_scripts
    type: io.kestra.plugin.git.SyncNamespaceFiles
    namespace: microform.internal
    gitDirectory: scripts/internal 

  - id: sync_microform_scripts
    type: io.kestra.plugin.git.SyncNamespaceFiles
    namespace: microform
    gitDirectory: scripts/microform

  - id: sync_boa_scripts
    type: io.kestra.plugin.git.SyncNamespaceFiles
    namespace: microform.boa
    gitDirectory: scripts/boa

pluginDefaults:
  - type: io.kestra.plugin.git
    values:
      username: secret
      url: secret
      password: "secret"
      branch: main
      dryRun: false
```
