### ISSUE TITLE
FileLogExporter plugin should allow to export logs into multiple files instead of one potentially large file

### ISSUE THREAD

**Issue by Skraye** [kestra-io/kestra#7501]
### Feature description

Exporting log can create very big files, we should allow to create smaller multiple files

**Comment by anna-geller** [comment]
example with `maxLinesPerFile`:

```yaml
id: logShipper
namespace: logs
tasks:
  - id: shipLogs
    type: io.kestra.plugin.ee.core.log.LogShipper
    logLevelFilter: INFO
    batchSize: 1000
    lookbackPeriod: P1D
    offsetKey: logShipperOffset
    logExporters:
      - id: file
        type: io.kestra.plugin.ee.core.log.FileLogExporter
        format: JSON # default ION
        maxLinesPerFile: 100
```
