### ISSUE TITLE
Subflow with wait is neverending 

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#7506]
All subflow with `wait:true` are neverending: 
- Execution `master-flow`
- Subflow start 
- Subflow end 
- The `master-flow` is stucked 

 
```yaml 
id: master-flow
namespace: company.team

tasks:
  - id: delete
    type: io.kestra.core.tasks.flows.Subflow
    namespace: company.team
    flowId: child-flow
    transmitFailed: true
    wait: true
    inputs:
      message: "delete"
```

```yaml 
id: child-flow
namespace: company.team

tasks:
  - id: delete
    type: io.kestra.core.tasks.flows.Subflow
    namespace: fr.leroymerlin.datacomponent.dataplatform.keys-rotation
    flowId: subflow
    transmitFailed: true
    wait: true
    inputs:
      message: "delete"
```

**Comment by anna-geller** [comment]
not reproducible on 0.21.3 + develop using:

```yaml
id: grandchild
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 
```

and

```yaml
id: child
namespace: company.team

inputs:
  - id: message
    type: STRING
    defaults: hello

tasks:
  - id: sleep
    type: io.kestra.plugin.core.flow.Sleep
    duration: PT2S
  
  - id: subflow
    type: io.kestra.plugin.core.flow.Subflow
    namespace: company.team
    flowId: grandchild
    wait: true
    transmitFailed: true
```

from parent:

```yaml
id: parent
namespace: company.team

tasks:
  - id: call
    type: io.kestra.plugin.core.flow.Subflow
    namespace: company.team
    flowId: child
    wait: true
    transmitFailed: true
    inputs:
      message: delete
```
