### ISSUE TITLE
Invalid pebble after migration

### ISSUE THREAD

**Issue by brian-mulier-p** [kestra-io/kestra#7511]
### Describe the issue

```
- id: load_bq_from_gcs_csv
  type: io.kestra.plugin.gcp.bigquery.LoadFromGcs
  from:
    - 'gs://{{ secret("GCS_LANDING_BUCKET") }}/{{ json(parent.taskrun.value)["gcs_path_prefix"] }}/{{ inputs.uuid_str }}_*.csv.gz'
  destinationTable: "{{ json(parent.taskrun.value)['destination_table'] }}"
  writeDisposition: WRITE_APPEND
  createDisposition: CREATE_NEVER
  autodetect: false
  format: CSV
  csvOptions:
    encoding: UTF-8
    fieldDelimiter: ","
    skipLeadingRows: 1
    allowQuotedNewLines: true
  allowFailure: true
```
used to work but migration from 0.20.11 to 0.21.3 made it throw this error:
```
2025-02-19 10:28:47.062io.pebbletemplates.pebble.error.ParserException: Unexpected character [\] (["gs://{{ secret(\"GCS_LANDING_BUCKET\") }}/{{ json(parent.taskrun.value)[\"gcs_path_prefix\"] }}/{{ inputs.uuid_str }}_*.csv.gz"]:1)
```

### Environment

- Kestra Version: 0.20.11 to 0.21.3

**Comment by brian-mulier-p** [comment]
Please have a look to see if it's plugin related otherwise maybe it's due to serialization (cc @loicmathieu)

**Comment by mgabelle** [comment]
So yes I  think it's related to some serialization issue.

**Actual** 
`'gs://{{ secret("GCS_LANDING_BUCKET") }}/{{ json(parent.taskrun.value)["gcs_path_prefix"] }}/{{ inputs.uuid_str }}_*.csv.gz'`
It is causing the issue quoted above 

**Workaround**
It is working when putting the command in double quote and putting the secret variable into single quote like this : 
`"gs://{{ secret('GCS_LANDING_BUCKET') }}/{{ json(parent.taskrun.value)['gcs_path_prefix'] }}/{{ inputs.uuid_str }}_*.csv.gz"`

also works when removing the double quote but still replacing all the single quote inside by double quote : 
`gs://{{ secret('GCS_LANDING_BUCKET') }}/{{ json(parent.taskrun.value)['gcs_path_prefix'] }}/{{ inputs.uuid_str }}_*.csv.gz`

**Comment by anna-geller** [comment]
related https://github.com/kestra-io/kestra/issues/7437

**Comment by mgabelle** [comment]
Do you know how could we manage this @loicmathieu ?

**Comment by loicmathieu** [comment]
@brian-mulier-p @mgabelle can I have a reproducer please?

**Comment by Ben8t** [comment]
The one shared in the initial comment is a reproducer (the error happens before checking GCP credentials)

**Comment by loicmathieu** [comment]
A reproducer is a running flow, not just a task with secrets and dependencies on other complex tasks not present in the code snippet.

**Comment by Ben8t** [comment]
Here is a full flow without secret or upstream dependencies:

```yaml
id: dogfish_718364
namespace: company.team

variables:
  table: table
  file: out
  bucket: test
tasks:

- id: setKv
  type: io.kestra.plugin.core.kv.Set
  key: bucket
  value: "{{ vars.bucket}}"

- id: load_bq_from_gcs_csv
  type: io.kestra.plugin.gcp.bigquery.LoadFromGcs
  from:
    - 'gs://{{ kv("bucket") }}/{{ vars.table }}/{{ vars.file }}_*.csv.gz'
  destinationTable: "{{ vars.table }}"
  writeDisposition: WRITE_APPEND
  createDisposition: CREATE_NEVER
  autodetect: false
  format: CSV
  csvOptions:
    encoding: UTF-8
    fieldDelimiter: ","
    skipLeadingRows: 1
    allowQuotedNewLines: true
  allowFailure: true
```
