### ISSUE TITLE
Allow for hierarchical inputs

### ISSUE THREAD

**Issue by Melkaz** [kestra-io/kestra#753]
### Feature description

Use-case: the user want to group inputs

Candidate syntax:

```yaml
inputs:
    - name: sample.id
      type: INT 
    - name: sample.sex
       type: STRING
    - name: genome.sequence
       type: STRING
    - name: genome.sequenceIndex
       type: STRING
```

Thanks 🌈
