### ISSUE TITLE
configure storage by ENV seems not to work as expected

### ISSUE THREAD

**Issue by jalberto** [kestra-io/kestra#7543]
### Describe the issue

- use latest helm chart
- use `extraEnv` to add storage configuration

```
extraEnv:
  - name: "KESTRA_STORAGE_TYPE"
    value: "s3"
  - name: "KESTRA_STORAGE_S3_ENDPOINT"
    value: "https://s3.custom.endpoint"
  - name: "KESTRA_STORAGE_S3_REGION"
    value: "region"
  - name: "KESTRA_STORAGE_S3_BUCKET"
    value: "kestra"
  - name: KESTRA_STORAGE_S3_ACCESSKEY
    valueFrom:
      secretKeyRef:
        name: kestraext
        key: storage_secret_access_key
  - name: KESTRA_STORAGE_S3_SECRETKEY
    valueFrom:
      secretKeyRef:
        name: kestraext
        key: storage_access_key_id
```

- deploy/upgrade get error

```
Caused by: io.kestra.core.exceptions.KestraRuntimeException: Failed to create storage 's3'. Error: Unrecognized field "accesskey" (class io.kestra.storage.s3.S3Storage$S3StorageBuilder), not marked as ignorable (13 known properties: "forcePathStyle", "stsRoleSessionDuration", "s3AsyncClient", "bucket", "s3Client", "stsRoleExternalId", "secretKey", "stsEndpointOverride", "region", "endpoint", "stsRoleSessionName", "accessKey", "stsRoleArn"])
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: io.kestra.storage.s3.S3Storage$S3StorageBuilder["accesskey"])
```

So it seems to be expecting `accessKey` but get lowercase `k`

Things I tried and related issues:

- if you mix yaml and ENV config it doesn't work, all the keys must be in one format or another
- if I use `KESTRA_STORAGE_S3_ACCESS_KEY` it doesn't work with a similar error but complaining about `access`
- If I use `SECRET_KESTRA_STORAGE_S3_ACCESSKEY` with base64 value, it doesn't work either

### Environment

- Kestra Version: 0.21.3

**Comment by MarcoSaba** [comment]
@anna-geller May we add one dev to the loop? The issue here is how the micronaut env is translated into the configuration that Kestra reads. The env is translated in lowercase when it should be translated in camelcase.

Try to populate the configuration with the coordinates of the bucket you need without using env variables for now. 

Example:
```
kestra:
  storage:
    s3:
      accessKey: xxx
      secretKey: yyy

```
Regarding:

> if you mix yaml and ENV config it doesn't work, all the keys must be in one format or another

Can you post the error you get? I would try to leave accessKey and secretKey in the configuration yaml and leave
```
extraEnv:
  - name: "KESTRA_STORAGE_TYPE"
    value: "s3"
  - name: "KESTRA_STORAGE_S3_ENDPOINT"
    value: "https://s3.custom.endpoint"
  - name: "KESTRA_STORAGE_S3_REGION"
    value: "region"
  - name: "KESTRA_STORAGE_S3_BUCKET"
    value: "kestra"
```
as env variables. 
Be aware that as stated [here](https://kestra.io/docs/configuration) the environment variables take precedence over configuration files.
