### ISSUE TITLE
Postgres Tasks can't connect to DB `Cannot invoke "java.sql.Connection.rollback()" because "connection" is null`

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#7546]
### Describe the issue

When trying to connect to a Postgres DB, it always comes back with this:

```bash
Cannot invoke "java.sql.Connection.rollback()" because "connection" is null
```

We've seen this come up with Zoomcamp students recently too but I was able to reproduce on `develop`. Works fine on 0.20.X

Example flow: https://github.com/DataTalksClub/data-engineering-zoomcamp/blob/main/02-workflow-orchestration/flows/02_postgres_taxi.yaml

Use this Docker Compose to get PG db but change Kestra image tag to `develop`: https://github.com/DataTalksClub/data-engineering-zoomcamp/blob/main/02-workflow-orchestration/docker/combined/docker-compose.yml

### Environment

- Kestra Version: `develop`

**Comment by Ben8t** [comment]
What about port conflict? I see that zoocamp.postgres is on 5432 which is the default for Postgres.
Can you try using another port for zoocamp database?

**Comment by wrussell1999** [comment]
@Ben8t I should clarify that I had this issue right now and was able to get it working by rolling back to 0.20.7 (the version I used for the videos).

Example I used:
```yaml
id: python_etl_pg
namespace: company.team

inputs:
  - id: dataset_uri
    type: STRING
    displayName: Dataset URI
    defaults: https://huggingface.co/datasets/kestra/datasets/raw/main/csv/orders.csv

  - id: discount_amount
    type: FLOAT
    displayName: Discount Amount
    description: By default, it's set to 0 (no discount).
    min: 0.01
    max: 1
    defaults: 0.1

variables:
  github_url: https://github.com/wrussell1999/kestra-examples
  filename: processed_orders.csv
  table: orders

tasks:
  - id: extract
    type: io.kestra.plugin.core.http.Download
    uri: https://huggingface.co/datasets/kestra/datasets/raw/main/csv/orders.csv
  
  - id: wdir
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      - id: clone
        type: io.kestra.plugin.git.Clone
        url: "{{ vars.github_url }}"

      - id: transform
        type: io.kestra.plugin.scripts.python.Commands
        containerImage: ghcr.io/kestra-io/pydata:latest
        namespaceFiles:
          enabled: true
        beforeCommands:
          - pip install kestra
        inputFiles:
          data.csv: "{{ outputs.extract.uri }}"
        outputFiles:
          - "{{ vars.filename }}"
        env:
          DATASET_URL: "data.csv"
          DISCOUNTED_AMOUNT: "{{ inputs.discount_amount ?? 0 }}"
          FILENAME: "{{ vars.filename }}"
        commands:
          - python demos/py-etl-demo/files/etl.py

  - id: create_table
    type: io.kestra.plugin.jdbc.postgresql.Queries
    sql: |
      CREATE TABLE IF NOT EXISTS {{ vars.table }} (
          order_id               integer,
          customer_name          text,
          customer_email         text,
          product_id             integer,
          price                  double precision,
          quantity               integer,
          total                  double precision,
          discounted_total       double precision
        );
  
  - id: load
    type: io.kestra.plugin.jdbc.postgresql.CopyIn
    format: CSV
    from: "{{ render(outputs.transform.outputFiles[vars.filename]) }}"
    table: "{{ vars.table }}"
    header: true
    columns: [order_id,customer_name,customer_email,product_id,price,quantity,total,discounted_total]

triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: 0 10 * * *
    disabled: true

pluginDefaults:
  - forced: false
    type: io.kestra.plugin.jdbc.postgresql
    values:
      url: jdbc:postgresql://host.docker.internal:5432/etl_demo
      username: kestra
      password: k3str4 
```

PG DB Docker Compose:
```yaml
version: "3.8"
services:
  postgres:
    image: postgres
    container_name: postgres_db
    environment:
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: k3str4
      POSTGRES_DB: etl_demo
    ports:
      - "5432:5432"
    volumes:
      - etl-postgres-data:/var/lib/postgresql/data
volumes:
  etl-postgres-data:
```
