### ISSUE TITLE
Validate that plugin default are applied on schedule

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#7549]
```yaml 
          plugins:
            configuration:
              - type: io.kestra.plugin.core.trigger.Schedule
                values:
                   recoverMissedSchedules: NONE
```

seems to be not be applied on the schedule properly, leading to a backfill in case of long running execution

**Comment by tchiotludo** [comment]
https://kestra-io.zendesk.com/agent/tickets/309
relate to: https://github.com/kestra-io/kestra/issues/6681

**Comment by Ben8t** [comment]
I'm able to reproduce

```yaml
id: boar_881826
namespace: company.team

tasks:

  - id: slee
    type: io.kestra.plugin.core.flow.Sleep
    duration: PT5M
    
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀

triggers:
  - id: sche
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "*/2 * * * *"
```

See [here](https://postgres-ee.preview.dev.kestra.io/ui/flows/edit/company.team/boar_881826/executions) I [set pluginDefaults for](https://postgres-ee.preview.dev.kestra.io/ui/namespaces/edit/company.team/plugin-defaults) `recoverMissedSchedules: NONE`  in corresponding namespace, but the flow triggers missed schedule (due to the wait task duration > 2min) and it seems to trails behind new schedule

![image](https://github.com/user-attachments/assets/c0b9339b-9f77-4aaa-a42f-f45c61c1b9a5)
![image](https://github.com/user-attachments/assets/58c0f675-2b0c-4cc9-a016-fde5f8b20ed8)
