### ISSUE TITLE
[UI] Flow -> Metrics page is broken

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#7593]
### Describe the issue

The Flow -> Metrics page didn't work anymore.

For example, use this flow and launch 3 executions, each executions will generate metrics
```yaml
id: lemur_434144
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀
  - id: return
    type: io.kestra.plugin.core.debug.Return
    format: toto
```

Then goes to the flow Metrics page, it didn't show any metrics so there is no way to graph them as before.

![Image](https://github.com/user-attachments/assets/7b6f6c0f-8487-4926-9fb3-284e47e83d57)

### Environment

- Kestra Version: develop
