### ISSUE TITLE
Not passing docker volumes

### ISSUE THREAD

**Issue by PintjesB** [kestra-io/kestra#7600]
Hi all,

a year ago I setup my Kestra Ansible in docker automation, but it seems that is is broken now. I see that some configuration I am using is deprecated since and at the moment of setting it all up there was some confusion. If anyone can help me take a look, would be appreciated!
The error I'm getting is that it cannot find the Ansible playbook, however it is visible in the Kestra docker itself. So I feel like the problem lies within the 'passing volumes configuration'...

This is my docker compose:
  
```
kestra:
    container_name: kestra-server
    restart: unless-stopped
    image: kestra/kestra:latest-full
    pull_policy: always
    command: server standalone --worker-thread=128
    user: root
    volumes:
      - ansible_nfs:/ansible:ro
      - data_nfs:/app/storage
      - ~/.ssh:/ssh
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/kestra/:/tmp/kestra-wd
    environment:
      KESTRA_CONFIGURATION: |
        datasources:
          postgres:
            url: jdbc:postgresql://kestra-postgres:5432/kestra
            driverClassName: org.postgresql.Driver
            username: ${POSTGRES_USER}
            password: ${POSTGRES_PASSWORD}
        kestra:
          server:
            basic-auth:
              enabled: false
              username: ${KESTRA_USER}
              password: ${KESTRA_PASSWORD}
          repository:
            type: postgres
          storage:
            type: local
            local:
              base-path: "/app/storage"
          queue:
            type: postgres
          tasks:
            tmp-dir:
              path: /tmp/kestra-wd/tmp
          plugins:
            configurations:
              - type: io.kestra.plugin.scripts.runner.docker.Docker
                values:
                  volumeEnabled: true
          tutorial-flows:
            enabled: false
    env_file:
      - ./.env
    ports:
      - 8081:8080
      - 8082:8081
    depends_on:
      kestra-postgres:
        condition: service_healthy
    networks:
      - dockernet.docker.pve.home
```

And this is my Kestra flow:

id: ansible_update_pihole
namespace: ansible

```
tasks:
  - id: ansible_update_pihole
    type: io.kestra.plugin.ansible.cli.AnsibleCLI
    docker:
      image: cytopia/ansible:latest-tools
      pullPolicy: IF_NOT_PRESENT
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /ansible:/ansible
        - /ssh:/root/.ssh
    commands:
      - ansible-playbook /ansible/homelab/playbooks/pihole_update.yml -i /ansible/homelab/inventory
    env:
      ANSIBLE_HOST_KEY_CHECKING: "false"
      ANSIBLE_CONFIG: "/ansible/ansible.cfg"
    logLevel: DEBUG
triggers:
  - id: weekly_trigger
    type: io.kestra.plugin.core.trigger.Schedule
    cron: 0 5 * * 0
    logLevel: DEBUG
```

The execution logs:

```
2025-02-18 10:32:25.670Starting command with container id 5cd53a659b0538ddc51bfe4603e0318c62dafa966507a65f37f3769fd6da44df [/bin/bash -c ansible-playbook /ansible/homelab/playbooks/pihole_update.yml -i /ansible/homelab/inventory]
2025-02-18 10:32:26.530ERROR! the playbook: /ansible/homelab/playbooks/pihole_update.yml could not be found
2025-02-18 10:32:27.323io.kestra.core.models.tasks.runners.TaskException: Command failed with exit code 1
2025-02-18 10:32:27.323Command failed with exit code 1
2025-02-18 10:32:27.323io.kestra.core.models.tasks.RunnableTaskException: io.kestra.core.models.tasks.runners.TaskException: Command failed with exit code 1
 at io.kestra.plugin.scripts.exec.scripts.runners.CommandsWrapper.run(CommandsWrapper.java:173)
 at io.kestra.plugin.ansible.cli.AnsibleCLI.run(AnsibleCLI.java:156)
 at io.kestra.plugin.ansible.cli.AnsibleCLI.run(AnsibleCLI.java:29)
 at io.kestra.core.runners.WorkerTaskCallable.doCall(WorkerTaskCallable.java:78)
 at io.kestra.core.runners.AbstractWorkerCallable.call(AbstractWorkerCallable.java:56)
 at io.kestra.core.runners.WorkerSecurityService.callInSecurityContext(WorkerSecurityService.java:10)
 at io.kestra.core.runners.Worker.callJob(Worker.java:782)
 at io.kestra.core.runners.Worker.runAttempt(Worker.java:741)
 at io.kestra.core.runners.Worker.run(Worker.java:589)
 at io.kestra.core.runners.Worker.handleTask(Worker.java:294)
 at io.kestra.core.runners.Worker.lambda$run$8(Worker.java:250)
 at io.micrometer.core.instrument.internal.TimedRunnable.run(TimedRunnable.java:49)
 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
 at java.base/java.lang.Thread.run(Unknown Source)
 Caused by: io.kestra.core.models.tasks.runners.TaskException: Command failed with exit code 1
 at io.kestra.plugin.scripts.runner.docker.Docker.run(Docker.java:490)
 at io.kestra.plugin.scripts.exec.scripts.runners.CommandsWrapper.run(CommandsWrapper.java:159)
 ... 14 more
```

Thank you in advance!

**Comment by Ben8t** [comment]
Can you try doing a `ls` before the ansible commands in the flow, trying to explore what is mounted here please?

**Comment by PintjesB** [comment]
> Can you try doing a `ls` before the ansible commands in the flow, trying to explore what is mounted here please?

Forgot to mention that, I can see the files using the `ls` command from the container.

```
╭─🎯 ubuntu on docker in ~
╰─✗  sudo docker exec -it kestra-server ls /ansible
ansible.cfg  homelab
```

**Comment by Ben8t** [comment]
I'm able to reproduce with a simple flow:

```yaml
id: test
namespace: test

tasks:
  - id: ansible_update_pihole
    type: io.kestra.plugin.scripts.shell.Commands
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
      volumes:
        - /data/test_folder:/app
    commands:
      - ls /app
      - cat /app/new.txt
```

Here is my volume configuration:

```yaml
    volumes:
      - kestra-data:/app/storage
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/kestra-wd:/tmp/kestra-wd
      - ./test_folder:/data/test_folder # I have a ./test_folder/new.txt file locally
```

and my kestra plugin configuration:

```yaml
          plugins:
            configurations:
              - type: io.kestra.plugin.scripts.runner.docker.Docker
                values:
                  volumeEnabled: true
```


When using `taskRunner.type: io.kestra.plugin.core.runner.Process` everything works fine, but with `io.kestra.plugin.scripts.runner.docker.Docker` volumes aren't mounted. Tested on Kestra 0.21.4 on macOS docker-compose setup

`ls` in container shows the corresponding folder mounted well
![Screenshot 2025-02-27 at 11 56 00](https://github.com/user-attachments/assets/095381ed-1f6d-444d-abc1-008d985703dd)

**Comment by Ben8t** [comment]
Found the solution: since `0.17` you don't need an intermediate volume in your docker-compose.

You need the following configuration (under the `kestra` key), [as explained in this part of the documentation](https://kestra.io/docs/workflow-components/tasks/scripts/bind-mount):
```yaml
          plugins:
            configurations:
              - type: io.kestra.plugin.scripts.runner.docker.Docker
                values:
                  volume-enabled: true # 👈 this is the relevant setting, see the "-"
```

Once in the container you can directly use the host path:

```yaml
id: test
namespace: test

tasks:
  - id: ansible_update_pihole
    type: io.kestra.plugin.scripts.shell.Commands
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
      volumes:
        - /Users/benoit/dev/kestra/kestra_ee_prod/test_folder:/app
    commands:
      - ls /app
```
(for reference I updated [this](https://github.com/kestra-io/docs/pull/2284) migration guide)

I'm closing the issue for now. Let us know if you still face an issue on your side

**Comment by PintjesB** [comment]
Hi @Ben8t ,

I'm still not sure how to get this working properly...

In the bind-mounts guide (https://kestra.io/docs/workflow-components/tasks/scripts/bind-mount) it says to use the following kestra task for reference:

```yaml
id: pythonVolume
namespace: company.team
tasks:
  - id: anyPythonScript
    type: io.kestra.plugin.scripts.python.Commands
    runner: DOCKER
    containerImage: ghcr.io/kestra-io/pydata:latest
      volumes:
        - /Users/anna/gh/KESTRA_REPOS/scripts:/app
    commands:
      - python /app/etl/parametrized.py
```

However, in the AnsibleCLI docs, it says to use this:

```yaml
id: ansible
namespace: company.team

tasks:
  - id: ansible_task
    type: io.kestra.plugin.ansible.cli.AnsibleCLI
    inputFiles:
      inventory.ini: "{{ read('inventory.ini') }}"
      myplaybook.yml: "{{ read('myplaybook.yml') }}"
    docker:
      image: cytopia/ansible:latest-tools
    commands:
      - ansible-playbook -i inventory.ini myplaybook.yml
```

Could it be that the AnsibleCLI docs are outdated? Currently I'm unsure how to proceed to fix my kestra flow..

**Comment by Ben8t** [comment]
In the AnsibleCLI documentation, the example you highlight here use NamespaceFiles to store the playbook and inventory:

> Execute a list of Ansible CLI commands to orchestrate an Ansible playbook stored in the Editor using [Namespace Files](https://kestra.io/docs/developer-guide/namespace-files). ([source](https://kestra.io/plugins/plugin-ansible/io.kestra.plugin.ansible.cli.ansiblecli))


In Kestra you have several possibilities to attach scripts to your task: [NamespaceFiles](https://kestra.io/docs/concepts/namespace-files), [Volume Mount](https://kestra.io/docs/workflow-components/tasks/scripts/bind-mount), [GitClone](https://kestra.io/docs/workflow-components/tasks/scripts/git-clone), and inline scripting. You can find all the documentation regarding scripting in Kestra [here](https://kestra.io/docs/workflow-components/tasks/scripts).


In your case you could remove the unnessary volumes `- ansible_nfs:/ansible:ro` and use directly something like

```yaml
id: your_flow_id
namespace: your_namespace

tasks:
  - id: ansible_update_pihole
    type: io.kestra.plugin.ansible.cli.AnsibleCLI
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
      volumes:
        - /<path_to_your_ansible_nfs_folder:/ansible
      pullPolicy: IF_NOT_PRESENT
    commands:
      - ansible-playbook /ansible/homelab/playbooks/pihole_update.yml -i /ansible/homelab/inventory
    env:
      ANSIBLE_HOST_KEY_CHECKING: "false"
      ANSIBLE_CONFIG: "/ansible/ansible.cfg"
    logLevel: DEBUG
```

Please join our Slack if you still have some trouble. I tested volume-mount, namespacesfiles, inline script and git clone on the latest version of Kestra without issue on my side.

(I also update [this script example](https://github.com/kestra-io/docs/pull/2286) to use the latest taskRunner syntax)

**Comment by PintjesB** [comment]
I suppose I still need to pass the volume as the Kestra-server sees it, correct?
So that would be: 
```
╭─🎯 ubuntu on docker in ~
╰─❯ sudo docker exec -it kestra-server ls /ansible
ansible.cfg  homelab
```

So I would pass that as follows:
```yaml
id: ansible_backup_teleporter_pihole
namespace: ansible

tasks:
  - id: ansible_backup_teleporter_pihole
    type: io.kestra.plugin.scripts.shell.Commands
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
      image: cytopia/ansible:latest-tools
      pullPolicy: IF_NOT_PRESENT
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /ansible:/ansible
        - /ssh:/root/.ssh
    commands:
      - ls /ansible
      - ls /ssh
      - ansible-playbook /ansible/homelab/playbooks/pihole-teleporter_backup.yml -i /ansible/config/homelab/inventory
    env:
      ANSIBLE_HOST_KEY_CHECKING: "false"
      ANSIBLE_CONFIG: "/ansible/config/ansible.cfg"
    logLevel: DEBUG
```

Yet it still can't find the files.... Or am I missing something?
Sidenote: Also, do we still need to pass the docker socket?
