### ISSUE TITLE
schedule.date has not the same format as execution.startDate (or parser issue)

### ISSUE THREAD

**Issue by nsteinmetz** [kestra-io/kestra#761]
### Expected Behavior

Flow should output:

```
end: 2022-10-03T12:00:00Z
```

### Actual Behaviour

Current output:

```
Text '2022-10-03T12:10:00Z' could not be parsed at index 19
```

It works well when we run manual execution but it fails with schedule

### Environment Information

- Kestra Version: 0.5.1/Lite
- Operating System (OS / Docker / Kubernetes): Debian 11.x + Docker
- Java Version (If not docker):

### Example flow

```yaml
id: debug-date
namespace: nst.test
description: debug date issue
variables:
  end_date: "{{ schedule.date ?? execution.startDate | date(\"yyyy-MM-dd'T'HH:00:00'Z'\", existingFormat=\"yyyy-MM-dd'T'HH:mm:ss.SSS'Z'\") }}"
  start_date: "{{ execution.startDate ?? schedule.date | date(\"yyyy-MM-dd'T'HH:00:00'Z'\", existingFormat=\"yyyy-MM-dd'T'HH:mm:ss.SSS'Z'\") }}"
tasks:
  - id: start
    type: io.kestra.core.tasks.debugs.Echo
    format: "start: {{ vars.start_date }}"
  - id: end
    type: io.kestra.core.tasks.debugs.Echo
    format: "end: {{vars.end_date}}"
  - id: date
    type: io.kestra.core.tasks.debugs.Echo
    format: "date: {{execution.startDate}}"
triggers:
  - id: schedule
    type: io.kestra.core.models.triggers.types.Schedule
    backfill: {}
    cron: 10 * * * *
```

**Comment by nsteinmetz** [comment]
I thought first that the  `|date()` filter would apply only to the second element and not the first. That's why I changed the order between `execution.startDate` and  `schedule.date` in the variables.

**Comment by nsteinmetz** [comment]
So seems more that:
* `schedule.date` is formatted `yyyy-MM-dd'T'HH:mm:ss'Z'`
* `execution.startDate` is formatted `yyyy-MM-dd'T'HH:mm:ss.SSS'Z'`

**Comment by tchiotludo** [comment]
In fact, it's a more complicated. 
- First of all, `execution.startDate` or `schedule.date` will drop the millisecond if `.000` by default. This will be very uncertain on manually execution but for schedule it will be always the case. 
- The `existingFormat=\"yyyy-MM-dd'T'HH:mm:ss.SSS'Z'\")` expect explicitly millisecond `.SSS`, to make this optional, you can use `existingFormat=\"yyyy-MM-dd'T'HH:mm:ss[.SSS]'Z'\")`
- But In fact the `existingFormat` is intended to parse a string, but both date are already as date, so you don't need to parse it and just use the raw `"{{ schedule.date ?? execution.startDate | date(\"yyyy-MM-dd'T'HH:00:00'Z'\") }}"` that will only format output.

Resulting working flow 
```yaml 
id: debug-date
namespace: nst.test
description: debug date issue
revision: 4
variables:
  end_date: "{{ schedule.date ?? execution.startDate | date(\"yyyy-MM-dd'T'HH:00:00'Z'\") }}"
  start_date: "{{ execution.startDate ?? schedule.date | date(\"yyyy-MM-dd'T'HH:00:00'Z'\") }}"
tasks:
  - id: start
    type: io.kestra.core.tasks.debugs.Echo
    format: "start: {{ vars.start_date }}"
  - id: end
    type: io.kestra.core.tasks.debugs.Echo
    format: "end: {{vars.end_date}}"
  - id: date
    type: io.kestra.core.tasks.debugs.Echo
    format: "date: {{execution.startDate}}"
triggers:
  - id: schedule
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "* * * * *"
```

Tell me if it make sense for you!
