### ISSUE TITLE
QA the cache property on WorkingDirectory across all task runners as we keep seeing users reporting issues with it

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#7621]
User: "I've trying to track down a weird error we pretty much once or twice a day.
It seems to be related to caching, but that could be a red herring.
I've included an example flow, but I don't think this is consistently reproducible error. This flow is on a trigger than runs every 10 minutes and usually between midnight and 4am mountain time the error in the screenshot will occur and that error is thrown on the fileSystem create working directory task.  Subsequent executions run fine. but it consistently has this error ever 24-28 hrs."

```yaml
inputs:
  - id: account_id
    type: STRING
    defaults: 1
    required: false
tasks:
  - id: add_labels
    type: io.kestra.plugin.core.execution.Labels
    labels:
      account: "{{ inputs.account_id }}"

  - id: fileSystem
    type: io.kestra.plugin.core.flow.WorkingDirectory
    cache:
      patterns:
        - cache/pip/**
      ttl: PT24H

    tasks:
      - id: cloneRepository
        type: "io.kestra.plugin.git.Clone"
        url: https://github.com/kestra-io/kestra
        directory: kestra

      - id: python_script
        disabled: false
        type: io.kestra.plugin.scripts.python.Commands
        containerImage: public.ecr.aws/b3t6c4b5/data-science:latest
        taskRunner:
          type: io.kestra.plugin.scripts.runner.docker.Docker
        inputFiles:
          requirements.txt: ""
        beforeCommands:
          - pip install --cache-dir cache/pip -r requirements.txt
        commands:
          - python -c "print('hello')"

triggers:
  - id: 1
    disabled: false
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "*/10 * * * *"
    recoverMissedSchedules: "NONE"
    conditions:
      - type: io.kestra.plugin.core.condition.ExpressionCondition
        expression: "{{ envs.stage == 'prd' }}" # only in production
    inputs:
      account_id: 1
```

![image](https://github.com/user-attachments/assets/6e41b607-619c-483d-b610-a8484bb4d067)

[Slack Message](https://kestra-io.slack.com/archives/C03FQKXRK3K/p1740670531510559?thread_ts=1740670531.510559&cid=C03FQKXRK3K)
