### ISSUE TITLE
[UI error] Something went wrong while loading the execution

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#7623]
it popped out of nowhere:
![image](https://github.com/user-attachments/assets/f879f7f8-ad80-45af-a2ae-6b150ebfbc08)

worth investigating, I was able to reproduce by spinning up a fresh instance and trying to execute a flow using Cmd + Enter keyboard shortcut: https://jam.dev/c/68d92db0-565b-464a-9a86-d0317edf6fd6

### Environment

- Kestra Version: develop

**Comment by MilosPaunovic** [comment]
Could not reproduce in two separate tries. Is there anything else specific that could help me with reproduction @anna-geller?

**Comment by anna-geller** [comment]
it keeps happening every now and then, will assign @ReLoutre to validate 👍

**Comment by anna-geller** [comment]
happened again today for me when running this flow on develop:

```yaml
id: myflow
namespace: company.team

tasks:
  - id: fail
    type: io.kestra.plugin.core.execution.Fail
    errorMessage: This task sometimes fails, but that's OK

finally:
  - id: markSuccess
    type: io.kestra.plugin.core.execution.Exit
    state: SUCCESS
```
![image](https://github.com/user-attachments/assets/9a68dcad-8a50-4660-8bc5-7b2f01caf84e)
![image](https://github.com/user-attachments/assets/cf2030e9-d966-4696-b8f3-9f18e75b0ea9)

**Comment by ReLoutre** [comment]
Personally I'm unable to reproduce the error, don't matter how hard i try.
Tried both personal flows and the ones you provided.

Fresh instance as well ... could it be OS/Hardware dependent ?
What's your setup to run this kestra instance ? @anna-geller

**Comment by anna-geller** [comment]
the same as in the getting started guide - single docker container but using develop 

running on MacOS 15.3.1

**Comment by MilosPaunovic** [comment]
This smell awfully a lot like a race condition - the UI being too fast and doing the redirection before the execution itself if being populated to the proper DB fields.

Could you try to create a test which could simulate that somehow @ReLoutre?

**Comment by anna-geller** [comment]
another one today:

![image](https://github.com/user-attachments/assets/50d0c9e9-5cf0-41d3-940d-0531bc222594)

using this flow

```yaml
id: testFiles
namespace: company.team

tasks:
  - id: download
    type: io.kestra.plugin.core.http.Download
    uri: https://huggingface.co/datasets/kestra/datasets/raw/main/csv/orders.csv

  - id: fileExists
    allowFailure: true
    type: io.kestra.plugin.core.log.Log
    message: "{{ fileExists(outputs.download.uri) }}"
```
