### ISSUE TITLE
IllegalVariableEvaluationException: Unable to find `vars` used in the expression `debug: {{ outputs['task-id'].vars.output_id }}`

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#7625]
### Describe the issue

Strange issue retrieving outputs from script tasks here:

```yaml
id: test
namespace: test

tasks:
  - id: each
    type: io.kestra.plugin.core.flow.ForEach
    concurrencyLimit: 4
    values: ["one", "two", "three", "four"]
    tasks:
      - id: script
        type: io.kestra.plugin.scripts.python.Script
        script: |
          from kestra import Kestra
          Kestra.outputs({'ing': ['{{taskrun.value}}']})

      - id: debug 
        type: io.kestra.plugin.core.log.Log
        message: "debug: {{ outputs.script.vars.ing }}"
        # {{ outputs.script.["one"].vars.ing }} works in debug expressions
```

It looks like some pebble rendering problem.

![image](https://github.com/user-attachments/assets/193c5f91-971f-4ac1-a854-c868fa4d6b35)

![image](https://github.com/user-attachments/assets/96393ef7-f3af-473f-932f-300aab49cf48)

the same happens on latest 0.21.4:

![image](https://github.com/user-attachments/assets/c81be64c-298f-4ba3-861f-1bc55b65e7e1)

### Environment

- Kestra Version: develop

**Comment by anna-geller** [comment]
seems to only affect nested tasks below other Flowable like ForEach, as this works fine:

```yaml
id: outputs-from-shell-commands
namespace: company.team

tasks:
  - id: process
    type: io.kestra.plugin.scripts.shell.Commands
    commands:
      - echo '::{"outputs":{"test":"value","int":2,"bool":true,"float":3.65}}::'

  - id: return
    type: io.kestra.plugin.core.debug.Return
    format: "{{ outputs.process.vars.test }}"
```

**Comment by tchiotludo** [comment]
```yaml 
id: test
namespace: test

tasks:
  - id: each
    type: io.kestra.plugin.core.flow.ForEach
    concurrencyLimit: 4
    values: ["one", "two", "three", "four"]
    tasks:
      - id: script
        type: io.kestra.plugin.scripts.python.Script
        script: |
          from kestra import Kestra
          Kestra.outputs({'ing': ['{{taskrun.value}}']})

      - id: debug 
        type: io.kestra.plugin.core.log.Log
        message: "debug: {{ outputs.script.vars[taskrun.value].ing }}"
        # or 
        # message: "debug: {{ currentEachOutput(outputs.script).ing }}"
```

will be working since you are in a loop, you have multiple values, so you need to fetch by key of the iteration
