### ISSUE TITLE
The `ForEach` task should run tasks within each concurrent group sequentially, but it doesn't

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#7628]
### Describe the issue

The `ForEach` doesn't treat the group of tasks as a **group**

Repro:

```yaml
id: repro
namespace: test

tasks:
  - id: each
    type: io.kestra.plugin.core.flow.ForEach
    concurrencyLimit: 4
    values: ["one", "two", "three", "four"]
    tasks:
      - id: script
        type: io.kestra.plugin.scripts.python.Script
        script: |
          from kestra import Kestra
          Kestra.outputs({"key": "{{taskrun.value}}"})

      - id: debug 
        type: io.kestra.plugin.core.log.Log
        message: got {{ outputs.script }}
```

![image](https://github.com/user-attachments/assets/5daaf659-2bb8-477c-8862-b79dc15ae38b)

The random taskrun value passed from Python to debug tasks proves that the tasks are not executed as concurrent group but within each group tasks should run sequentially i.e. debug task should run after the script task within each group - this doesn't seem to be true. Run it 10 times and you'll see a random value from the `values` array: 

![image](https://github.com/user-attachments/assets/852fb20d-51a1-40b4-bcaa-1471f7c7fac9)

### Environment

- Kestra Version: latest + develop

**Comment by loicmathieu** [comment]
It does correctly run tasks within each groups sequentially.

![Image](https://github.com/user-attachments/assets/bcbc7777-d342-4a1e-9b71-6b9259a3ea2e)

`outputs.group` is an aggregate of the "current view of the outputs of all values", it cannot be reliably used, you should use `outputs[taskrun.value].group` to see the output of the current executing group of tasks, accessing directly the aggregate of all tasks is racy.

According to me, it works as desired.

**Comment by anna-geller** [comment]
if this is racy, then we have an issue, it shouldn't be racy; in the example from the issue, we clearly have 4 task groups, each with 2 sequential tasks that should run one after the other. In task-group "one", the taskrun-value  must be fixed to "one" and `{{ outputs.script }}` needs to return the value return by the script task for the iteration of this task that runs within task-group "one", not "three". it shouldn't be racy, it's unexpected, we need to find a better solution

I understand this might be more complex, so let me move this to the next cycle + schedule a meet to discuss possible solutions

**Comment by loicmathieu** [comment]
It's not the ForEachItem task that is racy, but the `outputs.group` output that is racy because of parallelization of task groups, this output is merged on each end of each task of each group so you cannot guarantee that it didn't contains outputs of group4 when you are processing group1.

That's why you should never use `outputs.group` as it's a mix of all outputs of all tasks of all groups, you should use `outputs.group[taskrun.value]` to access the output of the current group of tasks. 

> the taskrun-value must be fixed to "one" and {{ outputs.script }} needs to return the value return by the script task for the iteration

This has never worked like that, to access the output of the current group, you must use `outputs.group[taskrun.value]`, its like that since day 1 and clearly documented.

> I understand this might be more complex

This is not possible with our current implementation of all flowable tasks that executes multiple time the same task, nor with our current expression mechanism.

**Comment by anna-geller** [comment]
working example:

```yaml
id: repro
namespace: test

tasks:
  - id: each
    type: io.kestra.plugin.core.flow.ForEach
    concurrencyLimit: 4
    values: ["one", "two", "three", "four"]
    tasks:
      - id: script
        type: io.kestra.plugin.scripts.python.Script
        script: |
          from kestra import Kestra
          Kestra.outputs({"key": "{{taskrun.value}}"})

      - id: debug 
        type: io.kestra.plugin.core.log.Log
        message: got {{ outputs.script[taskrun.value].vars.key }}

      - id: debug2
        type: io.kestra.plugin.core.log.Log
        message: got {{ currentEachOutput(outputs.script).vars.key }}
```
