### ISSUE TITLE
[UI] The Outputs tab for ForEach task needs refactor to show child tasks split by loop iterations

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#7629]
### Describe the issue

```yaml
id: repro
namespace: test

tasks:
  - id: each
    type: io.kestra.plugin.core.flow.ForEach
    concurrencyLimit: 4
    values: ["one", "two", "three", "four"]
    tasks:
      - id: script
        type: io.kestra.plugin.scripts.python.Script
        script: |
          from kestra import Kestra
          Kestra.outputs({"key": "{{taskrun.value}}"})

      - id: debug 
        type: io.kestra.plugin.core.log.Log
        message: got {{ outputs.script }}
```

- [ ] make 1 task per each task within the loop and add column for loop iterations + show outputs per loop iteration in 4th column
![image](https://github.com/user-attachments/assets/01abeeda-27f0-47ef-8bca-e5b91d6d9e87)

- [ ] currently blank, we should fix that expression (using 4-columns layout as shown above):
![image](https://github.com/user-attachments/assets/7db26a02-c5f3-4b15-97a0-94364d3f400e)

### Environment

- Kestra Version: latest + develop
