### ISSUE TITLE
Issue sending a JSON network request (io.kestra.plugin.core.http.Request) with special characters

### ISSUE THREAD

**Issue by RemiBauzac** [kestra-io/kestra#7636]
### Describe the issue

I'm facing an issue to send json data through `io.kestra.plugin.core.http.Request` plugin with the following task: 

```yml
  - id: set_issue_as_filtering
    type: "io.kestra.plugin.core.http.Request"
    uri: "http://api.toto.com"
    method: POST
    contentType: "application/json"
    body:  "{{ {'status': 'new', 'rank': 3, 'comment': 'héhé' } | json  }}"
```
I've deliberately simplified the task and the parameters.
With this task, the sent payload is:

```json
{"status":"new", "rank":3,"comment":"h\xe9h\xe9"}
```
But the `é` character encoding is wrong here. To have a valid `json`, we need to have:
```
{"status":"new", "rank":3,"comment":"h\\u00e9h\\u00e9"}
```

The behavior breaks server json validator.
I tried with the following task, but the behavior remain the same : 
```yml
  - id: set_issue_as_filtering
    type: "io.kestra.plugin.core.http.Request"
    uri: "http://api.toto.com"
    method: POST
    contentType: "application/json"
    body:  '{"status": "new", "rank": 3, "comment": "héhé" }'
```

Has anyone ever had this problem ?
Thanks a lot for your help !

### Environment

- Kestra Version: 0.21.4

**Comment by RemiBauzac** [comment]
Thanks to @nkwiatkowski, the following task is working fine : 
```yml
  - id: set_issue_as_filtering
    type: "io.kestra.plugin.core.http.Request"
    uri: "http://api.toto.com"
    method: POST
    contentType: "application/json"
    body:  "{{ {'status': 'new', 'rank': 3, 'comment': 'héhé' } | json  }}"
   options:
      defaultCharset: UTF-8
        
```
