### ISSUE TITLE
Validate that outputs.task_id.output_id from another execution is not accessible directly to other flows in Subflows + Flow triggers

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#7653]
### Describe the issue

issue to QA and validate

### Environment

- Kestra Version: develop

**Comment by Ben8t** [comment]
@ReLoutre can you provide a reproducer and validate this one please? Creating a flow with outputs and try to access ones not exposed via another flow (subflow and flow trigger)

**Comment by ReLoutre** [comment]
Proposing a check for this case, any comments ?

# My Own Thoughts:

- As previously discussed with Benoit, it may be difficult to make requests to the local Kestra API where the sanity checks are running. I can propose alternatives, but so far, it would require not creating the subflow used for the test within the test itself. This means the test would have file dependencies.
- I'm not sure we can consider this flow a demo one since it doesn’t cover any real use case for customers. Therefore, I’m not sure it should be a public blueprint.

# What Does It Do?

The flow generates an output, which the subflow attempts to retrieve. It then asserts that the value was not accessible by the subflow and, finally, cleans up the test artifacts.

``` yaml
id: sanity_check_7653
namespace: sanitychecks
description: Validate that outputs.task_id.output_id from another execution is not accessible directly to other flows in Subflows + Flow triggers 

labels:
  dependencies: "core.flow.Subflow, core.http.Request, core.debug.Return"

tasks:
  - id: make_output
    type: io.kestra.plugin.core.debug.Return
    format: Some value that shouldn't be accesible to other exec.

  - id: create_subflow_yaml
    type: io.kestra.plugin.core.http.Request
    uri: http://localhost:8080/api/v1/flows
    contentType: application/x-yaml
    method: POST
    body: |
      id: sanity_check_tool
      namespace: reproducers
      tasks:
        - id: try_access_ouptut
          type: io.kestra.plugin.core.debug.Return
          format: |
            {% raw %}{{ outputs.make_output.value }}{% endraw %}
      outputs:
        - id: value
          type: STRING
          value: |
            {% raw %}{{ outputs.try_access_ouptut.value ?? 'empty' }}{% endraw %}

  - id: call_sublfow
    type: io.kestra.plugin.core.flow.Subflow
    flowId: sanity_check_tool
    namespace: reproducers
    inheritLabels: true
    transmitFailed: false

  - id: assert_fail
    type: io.kestra.plugin.core.execution.Assert
    conditions:
      - |
        {{ outputs.call_sublfow.outputs.value == 'empty' }}
        
finally:
  - id: remove_subflow_artifact
    type: io.kestra.plugin.core.http.Request
    uri: http://localhost:8080/api/v1/flows/reproducers/sanity_check_tool
    method: DELETE
```

**Comment by anna-geller** [comment]
this issue was intended just to validate if it's the case that you cannot access outputs from another execution unless those outputs were explicitly exposed within a flow

e.g. when you call the flow below in another flow as subflow or via flow trigger, you should be able to access the global output, but not the local output:

```yaml
id: toad_864134
namespace: company.team

tasks:
  - id: local_task_output
    type: io.kestra.plugin.core.debug.Return
    format: task output available only to this execution

  - id: global_task_output
    type: io.kestra.plugin.core.debug.Return
    format: task output exposed as flow output

outputs:
  - id: my_flow_output
    type: STRING
    value: "{{ outputs.global_task_output.value }}"
```

you can add the sanity check you created to https://github.com/kestra-io/blueprints/tree/main/sanitychecks/flows, don't worry, it will not be exposed as a blueprint unless you add it here https://github.com/kestra-io/blueprints/tree/main/flows

**Comment by ReLoutre** [comment]
closed by https://github.com/kestra-io/blueprints/commit/6d0547f410a778d62f1abe83d46db5823856e0a2

**Comment by anna-geller** [comment]
did you validate the behavior though @ReLoutre?

**Comment by Ben8t** [comment]
also @ReLoutre [this sanitycheck](https://github.com/kestra-io/blueprints/commit/6d0547f410a778d62f1abe83d46db5823856e0a2) won't work on preview environment as you're calling localhost. Please test first on one of the preview environment before merging a sanitycheck

**Comment by ReLoutre** [comment]
got it @Ben8t,
also, indeed the behaviour is validated @anna-geller, should we store the result of such issues somewhere ? Listing the state of such on the notion perhaps ?

**Comment by anna-geller** [comment]
I expected you to validate the behavior by running flows and adding screenshots (or screenshare e.g. with Jam.dev) documenting/proving the behavior works as expected directly here as issue comment

well spotted with localhost @Ben8t, perhaps Izaac can you dynamically retrieve the host? alternatively let's add that flow outside of the sanity-checks that get deployed (as it's still useful). perhaps a new private repo "qa-scripts"?

**Comment by Ben8t** [comment]
Yes, I think dynamically retrieve the host should be the way, but quite tricky as OSS and EE differ in the way you authenticate to the API. Hence the mention to https://github.com/kestra-io/kestra-ee/issues/2064 which will probably help on this.

@ReLoutre for your information I put a [basic subflow on sanitycheck repo](https://github.com/kestra-io/blueprints/blob/main/sanitychecks/flows/subflow.yaml) for some cases

**Comment by ReLoutre** [comment]
> validate the behavior by running flows and adding screenshots (or screenshare e.g. with Jam.dev) documenting/proving the 
behavior works as expected

Got it.

> directly here as issue comment

Yet regarding the fact to post it here solely seems weird to me. Aren't the results of the tests lost (among the flood) when closing the issue ?

> [basic subflow on sanitycheck repo](https://github.com/kestra-io/blueprints/blob/main/sanitychecks/flows/subflow.yaml) for some cases

👍

**Comment by ReLoutre** [comment]
# Documenting, Explaining, and Demonstrating That Outputs Produced Outside the Scope of Another Task Are Inaccessible  

## Explanation of Tests  

- Create a simple output.  
- Call a subflow that will:  
  - Try to access the output of the parent flow task.  
  - Generate a simple task output.  
  - Produce a flow output based on its attempt to access the parent flow task output.  
- Assess that accessing from the main flow the subflow's simple task output fails.  
- Assess that the subflow is unable to retrieve its parent flow task output.  
- Assess that the parent flow can access the subflow provided output.  

## Results  

- The subflow is unable to access its parent task outputs.  
- The parent flow is unable to access child outputs unless they are explicitly provided as outputs of the subflow.  

Here’s a GIF showcasing the execution of the flow below:  


![Image](https://github.com/user-attachments/assets/e65d35ab-9a7c-4e4b-bd73-5dfed76d21dc)

``` yaml
id: validate_exec_outputs_isolation 
namespace: dev.zac
description: |
  Validate that outputs.task_id.output_id from another execution is not accessible directly to other flows in Subflows + Flow triggers
  Originates from : https://github.com/kestra-io/kestra/issues/7653

labels:
  dependencies: "core.flow.Subflow, core.http.Request, core.debug.Return"

tasks:
  - id: make_output
    type: io.kestra.plugin.core.debug.Return
    format: Some value that shouldn't be accesible to other exec.

  - id: create_subflow_yaml
    type: io.kestra.plugin.core.http.Request
    uri: http://localhost:8080/api/v1/flows
    contentType: application/x-yaml
    method: POST
    body: |
      id: validate_exec_outputs_isolation_tool
      namespace: dev.zac
      tasks:
        - id: make_sub_output
          type: io.kestra.plugin.core.debug.Return
          format: Some SUB value that shouldn't be accesible to other exec.
        - id: try_access_output
          type: io.kestra.plugin.core.debug.Return
          format: |
            {% raw %}{{ outputs.make_output.value }}{% endraw %}
      outputs:
        - id: value
          type: STRING
          value: |
            {% raw %}{{ outputs.try_access_output.value ?? 'empty' }}{% endraw %}

  - id: call_sublfow
    type: io.kestra.plugin.core.flow.Subflow
    flowId: validate_exec_outputs_isolation_tool
    namespace: dev.zac
    inheritLabels: true
    transmitFailed: false

  - id: assert_fail_and_unreachable_sub_output
    type: io.kestra.plugin.core.execution.Assert
    conditions:
      - |
        {{ outputs.call_sublfow.outputs.value == 'empty' }}
      - |
        {{ outputs.make_sub_ouput.value ?? 'empty' == 'empty' }}
        
finally:
  - id: remove_subflow_artifact
    type: io.kestra.plugin.core.http.Request
    uri: http://localhost:8080/api/v1/flows/dev.zac/validate_exec_outputs_isolation_tool
    method: DELETE
```
# Side note
- I'm not sure it answers your demand @anna-geller 
- The blueprint has been removed from the sanity_checks due to its incompatibility on some Kestra instances
