### ISSUE TITLE
Documentation display drift when using sub-type properties

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#7708]
### Describe the issue

For example moving between simple Commands task and sub props taskRunner doesn't switch the documentation correctly
https://jam.dev/c/b18dbee4-f240-40c5-bd4f-46f50cd565ae

```yaml
id: lapwing_395976
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀

  - id: python
    type: io.kestra.plugin.scripts.python.Script
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
      
    script: |
      print('Hello')
```

### Environment

- Kestra Version: develop
