### ISSUE TITLE
Allow list (array) type for inputs

### ISSUE THREAD

**Issue by Melkaz** [kestra-io/kestra#771]
### Feature description

Allow for FLOAT[], INT[], STRING[], BOOLEAN[], URI[], etc... type as inputs.

For example, as part of testing a software, I'd like to iterate through a list of float values for a parameter (e.g. [0.1, 0.2, 0.3, ..., 1])
It would be nice to let the user specify a different list of values as inputs (e.g. [0.15, 0.50]).

Thanks !

**Comment by loicmathieu** [comment]
It can already be done using the JSON input type:

```yaml
id: array-input
namespace: myteam

inputs:
  - id: payload
    type: JSON

tasks:
  - id: each
    type: io.kestra.core.tasks.flows.EachSequential
    value: "{{inputs.payload}}"
    tasks:
      - id: log
        type: io.kestra.core.tasks.log.Log
        message: "{{taskrun.value}}"
```

![image](https://github.com/kestra-io/kestra/assets/1819009/79a69024-98df-4217-9b55-88e87178d19b)

For a better type safety we can create an ARRAY input file that will read the input as an array not a JSON but providing new input types for arrays of all supported types would double the supported types or array for not a lot of added value so I'm reluctant to do it.

another solution would be to allow to specify type: ARRAY and a subtype to also validate the subtype.

**Comment by anna-geller** [comment]
@loicmathieu love the suggestion with type and subtype — simple and easy to understand. 

If you say it's a quick win, let's go 🚀 

Example syntax to validate whether we have the same understanding:

```yaml
inputs:
  - id: my_numbers
    type: ARRAY
    subtype: INT
    defaults: [1, 2, 3, 4, 5]

  - id: my_strings
    type: ARRAY
    subtype: STRING
    defaults: ["my", "pretty", "inputs"]

  - id: my_booleans
    type: ARRAY
    subtype: BOOLEAN
    defaults: [true, true, false]

  - id: my_datetimes
    type: ARRAY
    subtype: DATETIME
    defaults: ["2024-08-09T14:19:00Z", "2024-08-09T15:19:00Z"]
```

**Comment by anna-geller** [comment]
and given this would be a list in YAML, I think we should also support this syntax then?

```yaml
inputs:
  - id: my_numbers
    type: ARRAY
    subtype: INT
    defaults: 
      - 1
      - 2
      - 3
      - 4
      - 5

  - id: my_strings
    type: ARRAY
    subtype: STRING
    defaults: 
      - my
      - pretty
      - inputs

  - id: my_booleans
    type: ARRAY
    subtype: BOOLEAN
    defaults: 
      - true
      - true
      - false

  - id: my_datetimes
    type: ARRAY
    subtype: DATETIME
    defaults: 
      - "2024-08-09T14:19:00Z"
      - "2024-08-09T15:19:00Z"
```
