### ISSUE TITLE
Refresh trigger throws flow not found error

### ISSUE THREAD

**Issue by paulgrainger85** [kestra-io/kestra#7712]
### Describe the issue

In the Triggers page with this one trigger

![Image](https://github.com/user-attachments/assets/0f68e44a-9076-43db-b563-192cbecaca5b)

If I select "Refresh Trigger" the screen changes to the following

![Image](https://github.com/user-attachments/assets/1e1f2549-db6f-40db-a2a0-75516dc714bc)

Example Flow:
```
id: spawn
namespace: demo

concurrency:
  behavior: QUEUE
  limit: 100

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀
  - id: sleep
    type: io.kestra.plugin.core.flow.Sleep
    duration: "PT10S"

triggers:
  - id: freq
    type: io.kestra.plugin.core.trigger.Schedule
    withSeconds: true
    cron: "* */1 * * * *"
```

### Environment

- Kestra Version: 0.21.5
