### ISSUE TITLE
File functions throw error `io.pebbletemplates.pebble.error.PebbleException: Unable to create the URI from the path`

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#7721]
### Describe the issue

Repro:

```yaml
id: testFiles
namespace: company.team

tasks:
  - id: fileExists
    allowFailure: true
    type: io.kestra.plugin.core.log.Log
    message: "{{ fileExists('main.py') }}"

  - id: fileSize
    allowFailure: true
    type: io.kestra.plugin.core.log.Log
    message: "{{ fileSize('main.py') }}"   

  - id: isFileEmpty
    allowFailure: true
    type: io.kestra.plugin.core.log.Log
    message: "{{ isFileEmpty('main.py') }}"  
```

![image](https://github.com/user-attachments/assets/85407559-e3b7-4eeb-b658-1f11397662d7)

Ideally, when a user provides a file `path` as a string, it would be helpful to support `namespace` as a second argument, like so:

```yaml
id: testFiles
namespace: company.team

tasks:
  - id: fileExists
    allowFailure: true
    type: io.kestra.plugin.core.log.Log
    message: "{{ fileExists('main.py', namespace='company.team') }}"
```

at the same time, we need to continue supporting accessing outputs from previous tasks:

```yaml
id: testFiles
namespace: company.team

tasks:
  - id: download
    type: io.kestra.plugin.core.http.Download
    uri: https://huggingface.co/datasets/kestra/datasets/raw/main/csv/orders.csv

  - id: fileExists
    allowFailure: true
    type: io.kestra.plugin.core.log.Log
    message: "{{ fileExists(outputs.download.uri) }}"
```

## TODOs

- [ ] fix the pebble error when trying to access namespace files within those 3 file functions
- [ ] add namespace as a second property to those functions if the file path is provided as a string of a namespace files path 
- [ ] make sure the syntax passing `outputs.task.uri` to those functions still works

### Environment

- Kestra Version: develop
