### ISSUE TITLE
Add autocompletion for Pebble filters when we type "|" inside Pebble

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#7734]
we can show all available filters after you type the pipe symbol | within a pebble expression

**Comment by hemantmm** [comment]
@tchiotludo, can I work on this issue?

**Comment by Pradumnasaraf** [comment]
It's not working

Jam: https://jam.dev/c/056c40c9-1416-411b-aea4-6e374a0526d3

```yaml
id: test-pebble-filters
namespace: company.team

inputs:
  - id: user_name
    type: STRING
    defaults: john doe

tasks:
  - id: generate_data
    type: io.kestra.plugin.core.log.Log
    message: "Hello {{ inputs.user_name }}"

  - id: transform_with_filters
    type: io.kestra.plugin.core.log.Log
    message: |
      Original: {{ inputs.user_name }}
      Uppercase: {{ inputs.user_name | upper }}
      Capitalized: {{ inputs.user_name | capitalize }}
      JSON: {{ outputs.generate_data | toJson }}
```

Reopening the issue
