### ISSUE TITLE
Kestra HTTP client BEARER auth use BASIC

### ISSUE THREAD

**Issue by nkwiatkowski** [kestra-io/kestra#7740]
### Describe the issue

When using Kestra HTTP client with BEARER auth, the client use BASIC auth.

Example to reproduce:

```yaml
id: lion_584021
namespace: company.team
tasks:
  - id: callProspayOnboardingApi
    type: io.kestra.plugin.core.http.Request
    description: "Call Prospay onboarding API"
    uri: "https://httpbin.org/headers"
    method: GET
    options:
      auth:
        type: BEARER
        token: "test-123"
    headers:
      Content-Type: application/json; charset=UTF-8
      Authorization: 'Bearer test-123'
    body: |
      {
        "key":"value"
      }
    allowFailed: true
  - id: apiResponse
    type: io.kestra.plugin.core.debug.Return
    format: "{{ outputs.callProspayOnboardingApi }}"
```

### Environment

- Kestra Version: develop
