### ISSUE TITLE
Array labels can't be filtered

### ISSUE THREAD

**Issue by brian-mulier-p** [kestra-io/kestra#7743]
### Describe the issue

```yaml
id: woodpecker_679858
namespace: company.team
inputs:
  - id: to_index
    type: MULTISELECT
    values:
      - blueprints
      - docs
      - plugins
  - id: array
    type: ARRAY
    itemType: STRING
    defaults:
      - a
      - b
tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀
  - id: add_labels
    type: io.kestra.plugin.core.execution.Labels
    labels:
      - key: array
        value: "{{inputs.array}}"
      - key: to_index
        value: "{{inputs.to_index}}"
```
Labels which are array can't be filtered, moreover are we expected to supply one of the value the label array contains, the whole array ?
Note: clicking on an existing one currently adds the whole array to the filter

https://jam.dev/c/fb5d92ac-a52f-4a7d-af4e-8b23be432d5f

### Environment

- Kestra Version: develop
