### ISSUE TITLE
flow.If handling of task outputs in condition statement

### ISSUE THREAD

**Issue by greglenane** [kestra-io/kestra#7760]
### Describe the issue

Issue with kestra interpretation of conditional statement in "io.kestra.plugin.core.flow.If". User attempting to use outputs from previous tasks in conditional statement and always evaluates to true. 

[fetch-f1-results.txt](https://github.com/user-attachments/files/19152586/fetch-f1-results.txt)

### Environment

[docker-compose.txt](https://github.com/user-attachments/files/19152619/docker-compose.txt)

using kestra latest (v0.21.5)

**Comment by anna-geller** [comment]
well spotted by Loic, the correct expression would be:
```yaml
  - id: return
    type: io.kestra.plugin.core.debug.Return
    format: "{{ outputs.getApiRound.vars.round_number > outputs.getDBrounds.row.round_number }}"
```

**Comment by anna-geller** [comment]
@greglenane can you check and close the issue if this fixes it for you?

**Comment by greglenane** [comment]
Thank you for the suggestion, this looks like a step in the right direction but the flow.If still seems buggy. Here are the key tasks flow (full flow attached) [fetch-f1-results.txt](https://github.com/user-attachments/files/19167278/fetch-f1-results.txt):
```
- id: show_output
    type: io.kestra.plugin.core.log.Log
    message:
      - "{{ outputs.getApiRound.vars.round_number }}"
      - "{{ outputs.getDBrounds.row.round_number }}"

  - id: return
    type: io.kestra.plugin.core.debug.Return
    format: "{{ outputs.getApiRound.vars.round_number > outputs.getDBrounds.row.round_number }}"

  - id: new_race_check
    type: io.kestra.plugin.core.flow.If
    condition: |
      "{{ outputs.getApiRound.vars.round_number > outputs.getDBrounds.row.round_number }}"
```
My outputs for these three steps respectively:
show_output (log): 7, 7
return (output value): false
new_race_check (output evaluationResult): true
It seems that the return task and the if.flow task are interpreting this conditional statement differently.

**Comment by ReLoutre** [comment]
It seems that the evaluation of the Pebble result is not the same in both plugins. Here's a simple reproducer on 0.21.5:

``` yaml
id: reprod_7760
namespace: reproducers

variables:
  a: 1
  b: 1

tasks:
  - id: return
    type: io.kestra.plugin.core.debug.Return
    format: "{{ vars.a > vars.b }}"

  - id: new_race_check
    type: io.kestra.plugin.core.flow.If
    condition: |
      "{{ vars.a > vars.b }}
    then:
      - id: shouldnt_be_true
        type: io.kestra.plugin.core.execution.Fail
        errorMessage: "{{ vars.a }} as been evaluated as striclty superior to {{ vars.b }}"
```
On my side, the first test returns false, while the second one executes the then block of the if statement.

However, changing the condition from:

``` yaml
    condition: |
      "{{ vars.a > vars.b }}
```
to :
``` yaml
    condition: "{{ vars.a > vars.b }}"
```
produces the expected behavior, returning false for both tests.

Notably, the single leading double quote (likely introduced by a typo) does not seem to have any impact on the condition.
