### ISSUE TITLE
Unable to access Supabase Bucket with AWS S3 Plugin

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#7787]
### Describe the issue

When using the S3 plugin with a Supabase Bucket (which is compatible with the S3 protocol), it fails however using the same endpoint, region, access key ID and secret access key in the AWS CLI, it works fine and is able to list files inside of the bucket.

I can't figure out if this is a bug with our plugin or if it's configured incorrectly.

Error message when running flow below locally with Docker Compose on `latest` or on `kafka-ee.preview.dev.kestra.io`:

```
Received an UnknownHostException when attempting to interact with a service. See cause for the exact endpoint that is failing to resolve. If this is happening on an endpoint that previously worked, there may be a network connectivity issue or your DNS cache could be storing endpoints for too long.
```

One thing that's a bit odd is that Supabase's endpoint contains a path which may be part of the problem?

```yaml
id: supabase_bucket
namespace: supabase

tasks:
  - id: list
    type: io.kestra.plugin.aws.s3.List
    accessKeyId: "{{ secret('SUPABASE_ACCESS_KEY_ID') }}"
    secretKeyId: "{{ secret('SUPABASE_SECRET_ACCESS_KEY') }}"
    region: eu-west-2
    endpointOverride: https://nqxaafovehwkjapsqqlk.supabase.co/storage/v1/s3
    bucket: kestra-example
    compatibilityMode: true
```

Available to run with secrets in preview: https://kafka-ee.preview.dev.kestra.io/ui/flows/edit/supabase/supabase_bucket

### Environment

- Kestra Version: `develop` and `latest`

**Comment by Malaydewangan09** [comment]
@wrussell1999 @loicmathieu 
Could it be that the AWS SDK is still attempting to use virtual-hosted style addressing instead of path-style addressing ?

<img width="1040" alt="Image" src="https://github.com/user-attachments/assets/ea2ce382-a348-4bac-994b-e7f957056c23" />

**Comment by loicmathieu** [comment]
All S3 compatible storage must use the plugin-minio instead of the plugin-s3 as for performance reason it is by default using virtual-host style addressing.

There is however a compatibility mode, it should be documented somewhere.

@wrussell1999 can you try with plugin-minio instead, or try using the compatibility mode wich would switch to path-style addressing?

**Comment by Malaydewangan09** [comment]
@loicmathieu, but Isn't the reproducer already using compatibility mode?

**Comment by wrussell1999** [comment]
@loicmathieu I tried using the MinIO plugin but was faced with path issues.

```yaml
id: supabase_bucket
namespace: supabase

tasks:
  - id: list_buckets
    type: io.kestra.plugin.minio.List
    accessKeyId: "{{ secret('SUPABASE_ACCESS_KEY_ID') }}"
    secretKeyId: "{{ secret('SUPABASE_SECRET_ACCESS_KEY') }}"
    region: eu-west-2
    endpoint: https://nqxaafovehwkjapsqqlk.supabase.co/storage/v1/s3
    bucket: kestra-example
```

Error:
```
no path allowed in endpoint https://nqxaafovehwkjapsqqlk.supabase.co/storage/v1/s3
```

Unclear what I can do to get around the path being in the endpoint based on current documentation.

I used `compatibilityMode` in the previous example combined with `endpointOverride` but that's what caused the original error.
