### ISSUE TITLE
Python package manager UV info log level are marked as error incorrectly

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#7798]
### Describe the issue

Any logs produced using UV to install dependencies for Python come back as error level meaning the workflow finishes with a warning state.

![Image](https://github.com/user-attachments/assets/58fe17b8-638c-41f7-86a1-945ad6a5d9fa)

```yaml
id: python_example
namespace: company.team

tasks:
  - id: code
    type: io.kestra.plugin.scripts.python.Script
    beforeCommands:
      - uv init data
      - cd data
      - uv add pandas
    env:
      UV_PROJECT_ENVIRONMENT: "/usr/local/"
    script: |
      import pandas as pd
      from kestra import Kestra

      df = pd.read_csv('https://huggingface.co/datasets/kestra/datasets/raw/main/csv/orders.csv')
      total_revenue = df['total'].sum()
      Kestra.outputs({"total": total_revenue})

```

### Environment

- Kestra Version: `latest` 0.21.5

**Comment by wrussell1999** [comment]
You can get around this issue by piping the errors to `/dev/null` like this:

```yaml
id: python_example
namespace: company.team

tasks:
  - id: code
    type: io.kestra.plugin.scripts.python.Script
    beforeCommands:
      - uv init data 2> /dev/null
      - cd data
      - uv add pandas 2> /dev/null
    warningOnStdErr: false
    env:
      UV_PROJECT_ENVIRONMENT: "/usr/local/"
    script: |
      import pandas as pd
      from kestra import Kestra

      df = pd.read_csv('https://huggingface.co/datasets/kestra/datasets/raw/main/csv/orders.csv')
      total_revenue = df['total'].sum()
      Kestra.outputs({"total": total_revenue})
```

This isn't a great solution as the logs shouldn't flag as errors in the first place, and allow the task to succeed

**Comment by anna-geller** [comment]
Sorry Will, but we validated in more depth and Kestra doesn't do anything wrong. The issue stems from the Unix convention that redirects not only ERROR but also DEBUG output into `stderr`, see: https://github.com/astral-sh/uv/issues/10714#issuecomment-2599006723

The right way to handle it for uv running in Docker (no need for venv) is to use --system and --quiet flags:

```yaml
id: python_example
namespace: company.team

tasks:
  - id: code
    type: io.kestra.plugin.scripts.python.Script
    beforeCommands:
      - uv pip install pandas --system --quiet
    script: |
      import pandas as pd
      from kestra import Kestra

      df = pd.read_csv('https://huggingface.co/datasets/kestra/datasets/raw/main/csv/orders.csv')
      total_revenue = df['total'].sum()
      Kestra.outputs({"total": total_revenue})
```
