### ISSUE TITLE
Logs are not displayed if there is too much of them

### ISSUE THREAD

**Issue by Skraye** [kestra-io/kestra#7843]
### Describe the issue

When opening an execution, for task with a lot of logs, none are displayed : 

![Image](https://github.com/user-attachments/assets/82c7f4e3-4fbc-42ec-865d-aa9092596655)

![Image](https://github.com/user-attachments/assets/445e9974-63ef-4a63-8ee2-5e13ac03b43f)

```yaml
id: reproducer
namespace: company.team
tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀
  - id: test
    type: io.kestra.plugin.scripts.python.Script
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
    script: |
      from kestra import Kestra
      logger = Kestra.logger()
      logger.info("test")
      for i in range(1000):
          logger.info(f"c_{i}")
```

### Environment

- Kestra Version: develop
