### ISSUE TITLE
Invalid date in tooltip for waiting tasks

### ISSUE THREAD

**Issue by NovytskyiD** [kestra-io/kestra#7865]
### Describe the issue

For waiting tasks in tooltip we get Invalid date
![Image](https://github.com/user-attachments/assets/e9b36cc9-d036-43f4-a11d-6ba7cf8195c3)

### Environment

- Kestra Version: 0.21.5

**Comment by MilosPaunovic** [comment]
Could you please share the flow reproduction also @NovytskyiD?

**Comment by Ben8t** [comment]
this tutorial flow reproduce:

```yaml
id: business-processes
namespace: sanitychecks
description: Business Processes
inputs:
  - id: request.name
    type: STRING
    defaults: Rick Astley
  - id: request.start_date
    type: DATE
    defaults: 2024-07-01
  - id: request.end_date
    type: DATE
    defaults: 2024-07-07
  - id: slack_webhook_uri
    type: URI
    defaults: https://reqres.in/api/slack
tasks:
  - id: send_approval_request
    type: io.kestra.plugin.notifications.slack.SlackIncomingWebhook
    url: "{{ inputs.slack_webhook_uri }}"
    payload: |
      {
        "channel": "#vacation",
        "text": "Validate holiday request for {{ inputs.request.name }}. To approve the request, click on the `Resume` button here http://localhost:8080/ui/executions/{{flow.namespace}}/{{flow.id}}/{{execution.id}}"
      }
  - id: wait_for_approval
    type: io.kestra.plugin.core.flow.Pause
  - id: process_request
    type: io.kestra.plugin.core.http.Request
    uri: https://reqres.in/api/products
    method: POST
    contentType: application/json
    body: "{{ inputs.request }}"
```

(with the task wait_for_approval)
