### ISSUE TITLE
Maintain execution input modal/pop-up window height

### ISSUE THREAD

**Issue by razuro** [kestra-io/kestra#7892]
### Feature description

Execution inputs modal exceeds window viewport height if input content is big/long. Suggest to add fixed height size for the modal, and `overflow: scroll` to input field would prevent this from happening especially for big content input like JSON.

<img width="772" alt="Image" src="https://github.com/user-attachments/assets/bd51114c-a078-40ad-9473-d10b9b73eaad" />

**Comment by satvik2131** [comment]
Hi @razuro could you help me with a sample video or full screenshot for this , where do you getting this issue exactly ?

**Comment by Piyush-r-bhaskar** [comment]
> Hi [@razuro](https://github.com/razuro) could you help me with a sample video or full screenshot for this , where do you getting this issue exactly ?

@satvik2131  This could be from `InputsForm.vue` for `JSON`, To reproduce may use below one and click on `Execute`

```
id: hello-world
namespace: tutorial
description: Hello World

inputs:
  - id: json
    type: JSON
    displayName: "A JSON input"
    defaults: |
     [{"name": "kestra", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class", "rating": "best in class"v}]

tasks:
  - id: first_task
    type: io.kestra.plugin.core.debug.Return
    format: thrilled
```
