### ISSUE TITLE
Allow defaults for onResume on pause task to be dynamic

### ISSUE THREAD

**Issue by swarooppradhan** [kestra-io/kestra#7926]
### Feature description

At present the defaults for onResume have to be hard coded/fixed but if those are made dynamic then we can have default values populated based on earlier task or input thus letting user review and override if needed.

**Comment by anna-geller** [comment]
We will try to make both `defaults` and the `description` dynamic but it might be difficult, so TBD

```yaml
  - id: wait_for_approval
    type: io.kestra.plugin.core.flow.Pause
    onResume:
      - id: myinput
        type: STRING
        defaults: "{{ outputs.task1.output1}}"
        description: "{{ outputs.task1.output2}}"
```

thanks for the issue!

@loicmathieu can provide more info as we discussed this during a meeting

**Comment by loicmathieu** [comment]
Complete reproducer: 

```yaml
id: pigeon_123548
namespace: company.team

tasks:
  - id: task1
    type: io.kestra.plugin.core.output.OutputValues
    values:
      output1: output1
      output2: output2
  - id: wait_for_approval
    type: io.kestra.plugin.core.flow.Pause
    onResume:
      - id: myinput
        type: STRING
        defaults: "{{ outputs.task1.output1}}"
        description: "{{ outputs.task1.output2}}"
```

This may be both a frontend and a backend issue as the form didn't appear to display the default.
