### ISSUE TITLE
ForEachItem doesn't pass labels properly

### ISSUE THREAD

**Issue by johnkm516** [kestra-io/kestra#7930]
### Describe the issue

I am running a ForEachItem with batchsize = 1, and want to attach dynamic labels like this : 

```
  - id: foreachitem
    type: io.kestra.plugin.core.flow.ForEachItem
    namespace: erp.scm.batch
    inputs:
      inputRow: "{{ read(taskrun.items) }}"
    tasks:
      - id: foreachitem_split
        type: io.kestra.plugin.core.flow.ForEachItem$ForEachItemSplit
        batch:
          rows: 1
          separator: "\n"
        items: "{{outputs.ion_to_json.uri}}"
      - id: foreachitem_items
        type: io.kestra.plugin.core.flow.ForEachItem$ForEachItemExecutable
        inputs:
          batch_uri: "{{ taskrun.items }}"
        inheritLabels: false
        subflowId:
          namespace: erp.scm.batch
          revision: null
          flowId: BAT_SCM_REPUCRTE_Worker
        transmitFailed: true
        wait: true
        labels:
        - key: SHOP_CD
          value: "{{ read(taskrun.items).SHOP_CD }}"
        - key: BRND_CD
          value: "{{ read(taskrun.items).BRND_CD }}"
        - key: REPU_DT
          value: "{{ read(taskrun.items).REPU_DT }}"
        - key: COMP_CD
          value: "{{ read(taskrun.items).COMP_CD }}"
      - id: foreachitem_merge
        type: io.kestra.plugin.core.flow.ForEachItem$ForEachItemMergeOutputs
    errors: []
    batch:
      rows: 1
    flowId: BAT_SCM_REPUCRTE_Batch
    items: "{{outputs.ion_to_json.uri}}"
```

However the above code does not work, despite there being no syntax errors.. If there is multiple rows per batch I could just use taskrun.items[0], to attach labels using data from the first label in the batch. Regardless of the usefulness of doing that if there is more than one rows in a batch, I would like for the labels to be passed to the subflow.

### Environment

- Kestra Version: 0.20.6
