### ISSUE TITLE
ForEachItem wrongly display RUNNING subflow executions normally KILLED 

### ISSUE THREAD

**Issue by johnkm516** [kestra-io/kestra#7933]
### Describe the issue

If I have a ForEachItem which invokes 1000 subflows, and the subflow has a concurrency limit set to 5 with queue behavior set to QUEUE, the subflow indeed runs max 5 executions at a time and the ForEachItem slowly processes all 1000 subflows with max 5 concurrently. 

However, if I KILL the master flow, the concurrency limit of the child subflow is suddenly not enforced and the concurrency tab will keep stacking above 5 concurrent executions until all executions are running at once, and the queued executions are not killed properly. 

### Environment

- Kestra Version: 0.20.6

**Comment by Ben8t** [comment]
I think I'm able to reproduce: see in this video, at the end all subflows are running without any concurrency applied https://jam.dev/c/fac74ce4-46f0-4af0-a072-31a9469eebe3

```yaml
id: orders
namespace: company.team
concurrency:
  behavior: QUEUE
  limit: 2

inputs: 
  - id: order
    type: STRING

tasks: 
  - id: read_file
    type: io.kestra.plugin.scripts.shell.Commands
    taskRunner: 
      type: io.kestra.plugin.core.runner.Process
    commands: 
      - cat "{{ inputs.order }}"

  - id: read_file_content
    type: io.kestra.plugin.core.log.Log
    message: "{{ read(inputs.order) }}"
```

```yaml
id: test_main
namespace: company.team

tasks:
  - id: extract
    type: io.kestra.plugin.jdbc.duckdb.Query
    sql: |
      INSTALL httpfs;
      LOAD httpfs;
      SELECT *
      FROM read_csv_auto('https://huggingface.co/datasets/kestra/datasets/raw/main/csv/orders.csv', header=True);
    store: true
  - id: each
    type: io.kestra.plugin.core.flow.ForEachItem
    items: "{{ outputs.extract.uri }}"
    batch:
      rows: 1
    namespace: company.team
    flowId: orders
    wait: true # wait for the subflow execution
    transmitFailed: true # fail the task run if the subflow execution fails
    inputs:
      order: "{{ taskrun.items }}" # special variable that contains the items of the batch
```


@johnkm516 can you send us a screencast to be sure it's the case
