### ISSUE TITLE
Logs are limited to 1000 lines

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#7955]
We are using VueVirtualScroller, that have a hard limit of 1000 based on the configuration, that we can increase: 
```js
    // default 
    app.use(VueVirtualScroller, {itemsLimit: 1000})
```

For now, there is no configuration, leading a max of 1000 lines of logs for each task.

I try to increase to 10000 using the flow below, and the interface become really laggy. 

Maybe a good time to replace [vue-virtual-scroller](https://github.com/Akryum/vue-virtual-scroller) that seems unsupported ? 

```yaml 
id: bear_590461
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.scripts.shell.Script
    interpreter: ["/bin/bash","-c"]
    script: | 
      for i in $(seq 0 6000); do echo $i; done;
```
