### ISSUE TITLE
Empty address of proxy is not interpreted as NoProxy

### ISSUE THREAD

**Issue by ThierryLehoux** [kestra-io/kestra#7961]
### Describe the issue

Related to the issue https://github.com/kestra-io/kestra/issues/6107
Now in the latest version an empty string in not interpreted as NoProxy any more. So it become very complex to set or unset proxy depending of environnement variable

```
id: test-proxy-vide
namespace: seiitra.tlehoux

description: |
  Test condition of enable proxy with syntax interpretation

tasks: 

  - id: test_google_no_proxy
    type: io.kestra.plugin.core.http.Request
    uri: "https://www.google.com/"
    method: GET
  - id: Failes_test_google_proxy_set_to_localhost
    type: io.kestra.plugin.core.http.Request
    uri: "https://www.google.com/"
    method: GET
    options: 
      proxy:
        address: ""
        port: 3128
        type: HTTP
```

### Environment

- Kestra Version: 0.21.1

**Comment by Ben8t** [comment]
> So it become very complex to set or unset proxy depending of environnement variable

Can you detail a bit more the issue here please?

What about something like `adress: {{ vars.dev ?? vars.prod }}` 

If you want to run the task without proxy you can use a `If` task without the proxy options

**Comment by ThierryLehoux** [comment]
Hi. we are in the second case. We want all `http.Request` tasks with or without proxy depending of the environment.

We know that we could add in front of each `http.Request`, an `if` task then duplicate the `http.request` without proxy.  But a flow with multiple `http.request` become a nightmare to read. we have to duplicate all our `http.Request` tasks with  a specific proxy configuration.  A maintenable code avoid duplication to be able to fix a issue in one place. Just because we cannot enable or disable proxy dynamically by setting an empty string.

If it is fixed, we could simply set a line in our pluginDefaults part and we could disable or set the address in one place to all `http.Request` tasks of the flow and all our flows become smoother to read and maintenable.

Thanks in advance

**Comment by Ben8t** [comment]
Thanks for the details.

@loicmathieu do you have any view on this? Would it be better to let empty `options.proxy.address` not setting the proxy or add a `enableProxy` boolean option to be more explicit here?

**Comment by loicmathieu** [comment]
You should be able to use `null` instead of empty:

```
id: test-proxy-vide
namespace: seiitra.tlehoux

description: |
  Test condition of enable proxy with syntax interpretation

tasks: 

  - id: test_google_no_proxy
    type: io.kestra.plugin.core.http.Request
    uri: "https://www.google.com/"
    method: GET
  - id: Failes_test_google_proxy_set_to_localhost
    type: io.kestra.plugin.core.http.Request
    uri: "https://www.google.com/"
    method: GET
    options: 
      proxy:
        address:
        port: 3128
        type: HTTP
`̀`

Or even with `proxy: null`, there are multiple ways to specify null in YAML...

**Comment by ThierryLehoux** [comment]
I test with null instead of empty string for the proxy.
But **null in the address of the proxy is not interpreted as no proxy**

```
id: test-proxy-vide
namespace: seiitra.tlehoux

description: |
  Test condition of enable proxy with syntax interpretation

tasks: 

  - id: Failes_test_google_proxy_set_to_localhost
    type: io.kestra.plugin.core.http.Request
    uri: "https://www.google.com/"
    method: GET
    options: 
      proxy:
        address:
        port: 3128
        type: HTTP
```

2025-03-21 10:41:48.798Connect to http://localhost:3128/ [localhost/127.0.0.1] failed: Connection refused

**Comment by loicmathieu** [comment]
Oh yes, you should set to null the whole proxy attribute.
```
  - id: Failes_test_google_proxy_set_to_localhost
    type: io.kestra.plugin.core.http.Request
    uri: "https://www.google.com/"
    method: GET
    options: 
      proxy:
```

**Comment by ThierryLehoux** [comment]
But in that case, how do set it to null dynamically? the proxy property is flag as "Non Dynamic"

![Image](https://github.com/user-attachments/assets/d7313098-bc4a-483f-b64a-120f82f62fa0)

I see how to set it to null the address properties dynamically like that
```
proxy:
  address: "{{envs.environment == 'dev' ? 'xxx.xxx.xxx.xxx': null }}" 
  port: 3128
  type: HTTP
```

Thanks in advance for your feedback
