### ISSUE TITLE
Nested inputs of type SECRET are not decrypted at runtime

### ISSUE THREAD

**Issue by danlsgiga** [kestra-io/kestra#7964]
### Describe the issue

When using inputs of type `SECRET` and defining them as `nested`, their values are not decrypted at runtime.

These inputs are decrypted at runtime:

```
- id: aws_access_key_id
  type: SECRET
  description: The AWS Access Key Id of the Assumed Role to authenticate to Vault
  displayName: AWS Access Key ID
- id: aws_secret_access_key
  type: SECRET
  description: The AWS Secret Access Key of the Assumed Role to authenticate to Vault
  displayName: AWS Secret Access Key
- id: aws_session_token
  type: SECRET
  description: The AWS Session Token of the Assumed Role to authenticate to Vault
  displayName: AWS Session Token
```

These inputs are not decrypted at runtime:

```
- id: aws.access.key.id
  type: SECRET
  description: The AWS Access Key Id of the Assumed Role to authenticate to Vault
  displayName: AWS Access Key ID
- id: aws.secret.access.key
  type: SECRET
  description: The AWS Secret Access Key of the Assumed Role to authenticate to Vault
  displayName: AWS Secret Access Key
- id: aws.session.token
  type: SECRET
  description: The AWS Session Token of the Assumed Role to authenticate to Vault
  displayName: AWS Session Token
```

### Environment

- Kestra Version: v0.21.7

**Comment by loicmathieu** [comment]
I'm not sure I understand what you mean by nested.
Can you provide a flow reproducer and the error you have when using these inputs?

**Comment by Ben8t** [comment]
```yaml
id: alpaca_626166
namespace: company.team


inputs:
  - id: test.sub
    type: SECRET

  - id: my_in
    type: SECRET
tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: "{{ inputs.test.sub }} - {{ inputs.my_in }}"
```

![image](https://github.com/user-attachments/assets/70ba6309-0f46-4283-ba61-4ac0d3803fb6)


The first secret - "nested" meaning using dot in the definition - is not decrypted nor masked
