### ISSUE TITLE
[Dashboard] Custom Dashboards with WHERE condition filtering by Labels in the dashboard code is not working on JDBC backend

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#7966]
### Feature description

Following https://github.com/kestra-io/kestra/issues/6655#issuecomment-2742478400, we need to improve how labels are processed by the JDBC backend when using WHERE conditions in the dashboard code.  are fetch/indexed. 

## Example

We will need to add label index on JDBC JSON column -- might be possible in Postgres but not on MySQL. 

TODO
- [ ] let Sales Eng inform Sophia Genetics, Quadis and Xiaomi in case they try to use this feature as this won't work on their MySQL backend
- [ ] Document this limitation on MySQL

```yaml
  - id: total_executions_timeseries
    type: io.kestra.plugin.core.dashboard.chart.TimeSeries
    chartOptions:
      displayName: Total Executions
      description: Executions duration and count per date
      legend:
        enabled: true
      column: date
      colorByColumn: state
      width: 9
    data:
      type: io.kestra.plugin.core.dashboard.data.Executions
      where:
        - labelKey: area # 🔥 this is the issue
          value: frontend
          type: EQUAL_TO
      columns:
        date:
          field: START_DATE
          displayName: Date
        state:
          field: STATE
        total:
          displayName: Executions
          agg: COUNT
          graphStyle: BARS
        duration:
          displayName: Duration
          field: DURATION
          agg: SUM
          graphStyle: LINES
```
