### ISSUE TITLE
read function doesn't take into account NamespaceFiles ordering

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#7967]
Follow up during QA of https://github.com/kestra-io/kestra/issues/5467

```yaml
id: hyena_375528
namespace: dev.ben

tasks:

  - id: ns
    type: io.kestra.plugin.scripts.python.Commands
    namespaceFiles:
      enabled: true
      namespaces:
        - "dev.ben"
        - "company"
    commands:
      - python test.py


  - id: ns2
    type: io.kestra.plugin.scripts.python.Script
    namespaceFiles:
      enabled: true
      namespaces:
        - "dev.ben"
        - "company"
    script: "{{ read('test.py') }}"
```

Setup for NamespaceFiles:
- Create a NS files in company namespace called `test.py`
- Create a NS files in `dev.ben` namespace called `test.py`

The first task run the good file (the one from company namespace), the second task run the one from dev.ben namespace. It should run the one from company namespace.

See sample execution [here](https://postgres-oss.preview.dev.kestra.io/ui/executions/dev.ben/hyena_375528/27MW2Unnjnw2l7XiMxoD9d/gantt).
### Environment

- Kestra Version: develop (preview)
