### ISSUE TITLE
Render defaults for STRING/all types inputs

### ISSUE THREAD

**Issue by NovytskyiD** [kestra-io/kestra#7972]
### Feature description

Now defaults for STRING inputs will not render and we should add a render function in every place where it was used or pass the name of kv/secret instead of the actual value.
For SELECT we have an expression param where we can render value before execution. It will be nice to have the same param for STRING/all inputs or render defaults before flow execution.

slack discussion - https://app.slack.com/client/T01JX6XH5KN/C03FQKXRK3K

**Comment by anna-geller** [comment]
done in 1.0

example flow:

```yaml
id: infrastructure_workflow
namespace: company.sales

inputs:
  - id: release_env
    displayName: Release Environment
    type: SELECT
    autoSelectFirst: true
    values:
      - DEV
      - TEST
      - QA
      - PROD

  - id: backup_enabled
    type: BOOL
    defaults: "{{ inputs.release_env == 'PROD' ? true : false }}"
    dependsOn:
      inputs:
        - release_env

tasks:
  - id: log
    type: io.kestra.plugin.core.log.Log
    message: dynamic default {{ inputs.backup_enabled }}
```
