### ISSUE TITLE
SyncNamespaceFiles doesn't pull latest files if deleted in same workflow

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#7973]
### Describe the issue

When using the `io.kestra.plugin.core.namespace.DeleteFiles` task to delete all NamespaceFiles and then using the `io.kestra.plugin.git.SyncNamespaceFiles` task to pull the latest files, it doesn't pull the latest files. It also doesn't work if you use just the `io.kestra.plugin.git.SyncNamespaceFiles` task with the `delete: true` property.

The [file from GitHub](https://github.com/wrussell1999/kestra-examples/blob/main/demos/py-etl-demo/files/etl.py) looks like this:
```python
import os
import pandas as pd
from kestra import Kestra

df = pd.read_csv(os.environ['DATASET_URL'])
total_revenue = df['total'].sum()
Kestra.outputs({"total": total_revenue})

discount_amount = float(os.environ['DISCOUNTED_AMOUNT'])
if discount_amount > 0:
  df['discounted_total'] = df['total'] * (1 - discount_amount)
  df.to_csv(os.environ['FILENAME'], index=False)
```

I've added an extra line to it in Kestra:

```python
import os
import pandas as pd
from kestra import Kestra

df = pd.read_csv(os.environ['DATASET_URL'])
total_revenue = df['total'].sum()
Kestra.outputs({"total": total_revenue})

discount_amount = float(os.environ['DISCOUNTED_AMOUNT'])
if discount_amount > 0:
  df['discounted_total'] = df['total'] * (1 - discount_amount)
  df.to_csv(os.environ['FILENAME'], index=False)

print("Hello, World")
```

What should happen is the `etl.py` file is replaced with the original one above (the one on GitHub) and remove the `print("Hello, World")` line from the bottom of the file, however this does not happen and the file remains the same.

Both examples below do not work:

```yaml
id: sync_example
namespace: company.team

tasks:
  - id: delete
    type: io.kestra.plugin.core.namespace.DeleteFiles
    namespace: company.team
    files:
      - "**"

  - id: sync
    type: io.kestra.plugin.git.SyncNamespaceFiles
    url: https://github.com/wrussell1999/kestra-examples
    gitDirectory: "demos/etl-demo/files"
```

https://github.com/user-attachments/assets/6a71e392-d031-4d0c-90b9-ad63ddeff921

This doesn't work either (replace delete task with `delete: true` property):
```yaml
id: sync_example
namespace: company.team

tasks:
  - id: sync
    type: io.kestra.plugin.git.SyncNamespaceFiles
    url: https://github.com/wrussell1999/kestra-examples
    gitDirectory: "demos/etl-demo/files"
    delete: true
```

https://github.com/user-attachments/assets/3dff99a3-341b-401b-b1f8-b90c3960e573

### Environment

- Kestra Version: `latest` 0.21.7 and 0.21.6
