### ISSUE TITLE
Triggers page toggles don't match up to flow definition

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#8011]
### Describe the issue

This page says 3 of the 4 triggers are enabled, but all of them have the triggers disabled using the `disabled` property in the flow definition.

![Image](https://github.com/user-attachments/assets/215c10ae-7215-4527-a0af-92a3da505b56)

https://github.com/user-attachments/assets/b676d1cb-0da3-48b0-a3dd-e58f6867a7c9

One of the flows for example (with the trigger disabled):
```yaml
id: oss_spotlight
namespace: company.team

inputs:
  - id: dataset_uri
    type: STRING
    displayName: Dataset URI
    defaults: https://huggingface.co/datasets/kestra/datasets/raw/main/csv/orders.csv

  - id: discount_amount
    type: FLOAT
    displayName: Discount Amount
    description: By default, it's set to 0 (no discount).
    min: 0
    max: 1
    defaults: 0

tasks:
  - id: download_data
    type: io.kestra.plugin.core.http.Download
    uri: "{{ inputs.dataset_uri }}"

  - id: code
    type: io.kestra.plugin.scripts.python.Script
    containerImage: ghcr.io/kestra-io/pydata:latest
    beforeCommands:
      - pip install kestra
    inputFiles:
      data.csv: "{{ outputs.download_data.uri }}"
    outputFiles:
      - processed_orders.csv
    env:
      MYVAR: "{{ inputs.dataset_uri }}"
    script: |
      import pandas as pd
      from kestra import Kestra
      import os

      print(os.environ["MYVAR"])
      df = pd.read_csv('data.csv')
      total_revenue = df['total'].sum()
      Kestra.outputs({"total": total_revenue})
      if {{ inputs.discount_amount }} > 0:
        df['discounted_total'] = df['total'] * (1 - {{ inputs.discount_amount }})
        df.to_csv('processed_orders.csv')

  - id: slack_message
    type: io.kestra.plugin.notifications.slack.SlackIncomingWebhook
    url: "{{ kv('SLACK_WEBHOOK') }}"
    payload: |
      {
        "text": "Total: ${{ outputs.code.vars.total }}"
      }



  - id: if_file
    type: io.kestra.plugin.core.flow.If
    condition: "{{ inputs.discount_amount > 0 }}"
    then:
      - id: s3_upload_discounts
        type: io.kestra.plugin.aws.s3.Upload
        region: eu-west-2
        bucket: oss-example
        key: "processed_orders.csv"
        from: "{{ outputs.code.outputFiles['processed_orders.csv']}}"
        accessKeyId: "{{ kv('AWS_ACCESS_KEY_ID') }}"
        secretKeyId: "{{ kv('AWS_SECRET_KEY_ID') }}"

errors:
  - id: slack_notification
    type: io.kestra.plugin.notifications.slack.SlackExecution
    url: "{{ kv('SLACK_WEBHOOK') }}"
    executionId: "{{ execution.id }}"

triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "@daily"
    disabled: true
```

### Environment

- Kestra Version: `develop` OSS using hash b6a3d0c
