### ISSUE TITLE
`http.Request` task outputs uri to the logs unmasked even if it's a secret

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#8092]
### Describe the issue

`orders_url` is https://huggingface.co/datasets/kestra/datasets/raw/main/csv/orders.csv

```yaml
id: example
namespace: example

tasks:
  - id: request
    type: io.kestra.plugin.core.http.Request
    uri: "{{ secret('orders_url') }}"
```
It's visible in the logs despite being a secret field:
![Image](https://github.com/user-attachments/assets/0d9aaaf1-58e7-43f0-a527-1f9710728cd1)

This may not be a typical use case for a secret (aka a URL), but some users might have a publicly accessible URL they want hidden in the workflow for example.

### Environment

- Kestra Version: `develop` EE

Discovered by me and @aj-emerich testing read only secrets
