### ISSUE TITLE
Align daily and hourly flow on the Schedule trigger (using Cache task)

### ISSUE THREAD

**Issue by sboisgontier-lmfr** [kestra-io/kestra#810]
### Feature description

Hello Kestra Team
I have a usecase where I wanted to condition the run of a schedule flow with the state of an other flow.
I have a daily and an hourly flow. The daily flow can take a few hour and during this time the hourly flow should not run.
I could "guesstimate" how much time the daily flow could take but I wanted to be safe, handle every case by using events to reduce the maintenance.
I would like to have that kind of stuff in the triggers part but according to the documentation and my testing it is not possible.
```yaml
triggers:
  - id: hourly
    type: org.kestra.core.models.triggers.types.Schedule
    conditions:
      - id: multiple
        type: io.kestra.core.models.conditions.types.MultipleCondition
        window: P1D
        windowAdvance: P0D
        conditions:
          success:
            type: io.kestra.core.models.conditions.types.ExecutionStatusCondition
            in:
              - SUCCESS
              - FAILED
              - WARNING
            notIn:
              - RUNNING
          daily-flow-condition:
            type: io.kestra.core.models.conditions.types.ExecutionFlowCondition
            namespace: my.flows.namespace
            flowId: daily-flow-id
    cron: 0 9-22 * * *
    timezone: Europe/Paris
```
Do you think it is possible to add this feature to kestra?
To workaround this limitation I am using a [State Bag](https://kestra.io/plugins/core/tasks/states/io.kestra.core.tasks.states.Set.html), but this is not a good solution since it is not concurrency safe

Thanks

**Comment by tchiotludo** [comment]
Possible solution: 
- StateCondition : You set a lock with state on the daily on the daily and you will add a condition on the hourly to prevent them for running, it will be concurrency safe because the scheduler prevent 2 concurrent evaluation of the schedule 
- MultipleCondition that is not working seems to be possible I think, we will dig for that

Possible workaround:  
- Schedule a flow
- [Count](https://kestra.io/plugins/core/tasks/executions/io.kestra.core.tasks.executions.counts) executions 
- if 0, start a subflow

**Comment by sboisgontier-lmfr** [comment]
Oh I did not think about checking in my flow if the other flow is running!
I was too focus on the trigger and condition part

That is a good idea!

**Comment by anna-geller** [comment]
the new `timeWindow` property added in Kestra v0.20 should solve it, if not, let us know and we'll reopen it 👍 

more details https://kestra.io/blogs/release-0-20#flow-trigger-enhancements

example flow:

```yaml
id: silver_layer
namespace: company.team

tasks:
  - id: transform_data
    type: io.kestra.plugin.core.log.Log
    message: deduplication, cleaning, and minor aggregations

triggers:
  - id: flow_trigger
    type: io.kestra.plugin.core.trigger.Flow
    preconditions:
      id: bronze_layer
      timeWindow:
        type: DAILY_TIME_DEADLINE
        deadline: "09:00:00"
      flows:
        - namespace: company.team
          flowId: bronze_layer
          states: [SUCCESS]
```
