### ISSUE TITLE
Handle optionnal flow condition in triggers

### ISSUE THREAD

**Issue by sboisgontier-lmfr** [kestra-io/kestra#811]
### Feature description

Hello Kestra Team

I have use case where a flow A should run on a time window if
- flow B & C have run successfully
- flow B has run successfully & flow C **never started**

The flow A should not start if flow A and/or flow B failed in any other way.

Example:
```yaml
triggers:
  - id: flows_trigger
    type: org.kestra.core.models.triggers.types.Flow
    conditions:
      - id: optionnal_flow
        type: io.kestra.core.models.conditions.types.MultipleCondition
        window: P1D
        windowAdvance: P0D
        conditions:
          success:
            type: io.kestra.core.models.conditions.types.ExecutionStatusCondition
            in:
              - SUCCESS
              - NONE
          optionnal-flow-condition:
            type: io.kestra.core.models.conditions.types.ExecutionFlowCondition
            namespace: my.flows.namespace
            flowId: flow_C
      - id: mandatory_flow
        type: io.kestra.core.models.conditions.types.MultipleCondition
        window: P1D
        windowAdvance: P0D
        conditions:
          success:
            type: io.kestra.core.models.conditions.types.ExecutionStatusCondition
            in:
              - SUCCESS
          optionnal-flow-condition:
            type: io.kestra.core.models.conditions.types.ExecutionFlowCondition
            namespace: my.flows.namespace
            flowId: flow_B
```

Thanks

**Comment by anna-geller** [comment]
This will be possible in 0.20 (naming can change as we still iterate on it):

```yaml
id: myflow
namespace: company.team

triggers:
  - id: wait_for_upstream
    type: io.kestra.plugin.core.trigger.Flow
    conditions:
      - id: poll_for_flows
        type: io.kestra.plugin.core.condition.ExecutionsCondition
        preconditions:
          - namespace: company.team
            flowId: myflow1
            states: [SUCCESS, WARNING]
          - namespace: company.team
            flowId: myflow2
            states: [SUCCESS]
            labels:
              mykey: myvalue

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: I'm triggered after two flows!
```

I believe this seems to address the main use case
