### ISSUE TITLE
Dashboard log level filter causes internal SQL error

### ISSUE THREAD

**Issue by zhjch05** [kestra-io/kestra#8128]
### Describe the issue

To reproduce, try this yml to create a dashboard using docker standalone version of Kestra:
```yaml
title: Overview
description: Default overview dashboard
timeWindow:
  default: P30D # P30DT30H
  max: P365D

charts:
  - id: logs_timeseries
    type: io.kestra.plugin.core.dashboard.chart.TimeSeries
    chartOptions:
      displayName: Error Logs
      description: Count of ERROR logs per date
      legend:
        enabled: true
      column: date
      colorByColumn: level
    data:
      type: io.kestra.plugin.core.dashboard.data.Logs
      columns:
        date:
          field: DATE
          displayName: Execution Date
        level:
          field: LEVEL
        total:
          displayName: Total Error Logs
          agg: COUNT
          graphStyle: BARS
      where:
        - field: LEVEL
          type: IN
          values:
            - ERROR
 ```
Then it will raise an internal error:
```
Internal server error: SQL [select count(*) as "total", "level" as "level", DATE(timestamp) as "date" from logs where ("tenant_id" is null and "deleted" = ? and level in (?)) group by "level", "date"]; ERROR: operator does not exist: log_level = character varying
Hint: No operator matches the given name and argument types. You might need to add explicit type casts.
Position: 141
```

I have asked for help in slack and then someone asks me to raise an issue for this, because it looks like a bug.

### Environment

- Kestra Version: develop
