### ISSUE TITLE
inputFiles of PodCreate hangs and fails for large files

### ISSUE THREAD

**Issue by leighton-juno-bio** [kestra-io/kestra#8142]
### Describe the issue

When piping large file (>5Gb) files into the `inputFiles` field of `ProdCreate` the pod fails to initialise and hangs until time out.

The following configuration should reproduce the issue:

```
id: parse_large_files_to_pod
namespace: test

inputs:
  - id: file
    type: STRING
    defaults: "gs://genomics-public-data/references/hg38/v0/1000G_phase3_v4_20130502.sites.hg38.vcf"
    # defaults: "gs://genomics-public-data/references/hg38/v0/1000G_omni2.5.hg38.vcf.gz.tbi" -- small file that works for comparison

tasks:
  - id: download_file
    type: io.kestra.plugin.gcp.gcs.Download
    from: "{{ inputs.file }}"
  - id: print_file_size
    type: io.kestra.plugin.kubernetes.PodCreate
    namespace: default
    resume: false
    inputFiles: "{{ {'file.dat' : outputs.download_file.uri} }}"
    spec:
      containers:
      - name: print-file-size
        image: ubuntu:latest
        command: ["/bin/sh"]
        args:
          - -c
          - >-
            ls -l --block-size=M {{workingDir}}/file.dat
```

`kubectrl describe <pod>` gives

```
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  18m   default-scheduler  Successfully assigned default/test-parse-large-files-to-pod-print-file-size-zlbg8 to gke-kestra-cluster-kestra-cluster-pre-de49e65e-c956
  Normal  Pulling    18m   kubelet            Pulling image "busybox"
  Normal  Pulled     18m   kubelet            Successfully pulled image "busybox" in 127ms (127ms including waiting). Image size: 2156519 bytes.
  Normal  Created    18m   kubelet            Created container: init-files
  Normal  Started    18m   kubelet            Started container init-files
```

The `init-files` side car hangs and the pod never initializes.

Can someone else reproduce this issue?

### Environment

- Kestra Version: develop
- Deployed on kubernetes
