### ISSUE TITLE
Parent flow status is not reflecting status of the Subflow with retries

### ISSUE THREAD

**Issue by rthesman** [kestra-io/kestra#8143]
### Describe the issue

Parent flow calls a Subflow, with retries, which will success on certain condition.

Parent flow status shows as:
-  FAILED - when both 'Inbox' and 'Sent' were selected
- SUCCESS - when either 'Inbox' or 'Sent' was selected

Main flow
```
id: mainflow
namespace: kestra
description: Main flow
inputs:
  - id: box
    type: MULTISELECT
    values:
      - Inbox
      - Sent
tasks:
  - id: foreach
    type: io.kestra.plugin.core.flow.Parallel
    tasks:
      - id: inbox
        type: io.kestra.plugin.core.flow.If
        condition: "{{ inputs.box contains 'Inbox' }}"
        then:
          - id: subflow_inbox
            type: io.kestra.plugin.core.flow.Subflow
            namespace: "{{ flow.namespace }}"
            flowId: subflow
            inputs:
              counter: "{{ taskrun.attemptsCount }}"
      - id: sent
        type: io.kestra.plugin.core.flow.If
        condition: "{{ inputs.box contains 'Sent' }}"
        then:
          - id: subflow_sent
            type: io.kestra.plugin.core.flow.Subflow
            namespace: "{{ flow.namespace }}"
            flowId: subflow
            inputs:
              counter: "{{ taskrun.attemptsCount }}"

pluginDefaults:
  - type: io.kestra.plugin.core.flow.Subflow
    values:
      retry:
        type: constant
        maxAttempt: 5
        interval: PT3S
```

Subflow
```
id: subflow
namespace: kestra
description: Subflow
inputs:
  - id: counter
    type: INT
tasks:
- id: log
  type: io.kestra.plugin.core.log.Log
  message: "Counter - {{ inputs.counter }}"
- id: check_counter
  type: io.kestra.plugin.core.flow.If
  condition: "{{ inputs.counter == 3 }}"
  then:
    - id: pass
      type: io.kestra.plugin.core.log.Log
      message: "Done"
  else:
    - id: fail
      type: io.kestra.plugin.core.execution.Fail
```

### Environment

- Kestra Version: 0.20.14
