### ISSUE TITLE
Zero-byte `FILE` input treatment

### ISSUE THREAD

**Issue by yuri1969** [kestra-io/kestra#8218]
### Describe the issue

A change of behavior happened between v0.16 and v0.17+ regarding both optional and required `FILE` inputs.

When such input gets passed a zero-byte (empty) file the API rejects such parameter value.

---

Versions prior v0.17 accept the empty file input and present it as a regular 0B file input. Is this behavior intended?

# Example

Flow:

```yaml
id: mule_167053
namespace: company.team

inputs:
  - id: empty_file
    type: FILE
    description: Do we accept zero-byte files or not?
    required: false

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀
```

Reproduction commands:

```console
touch /tmp/empty && \
curl -v -X POST -H 'Content-Type: multipart/form-data' -F 'files=@/tmp/empty;filename=empty_file' 'http://localhost:8080/api/v1/executions/company.team/mule_167053'
```

Error response body:

> {"message":"Invalid entity: empty_file: Invalid input for `empty_file`, missing required input, but received `null`","logref":null,"path":null,"_links":{"self":{"href":"/api/v1/executions/company.team/mule_167053","templated":false,"profile":null,"deprecation":null,"title":null,"hreflang":null,"type":null,"name":null}},"_embedded":{"errors":[{"message":"Invalid input for `empty_file`, missing required input, but received `null`","logref":null,"path":"empty_file","_links":{},"_embedded":{}}]}}

### Environment

- Kestra Version: develop
