### ISSUE TITLE
ui: concat don't respect string type

### ISSUE THREAD

**Issue by mengzhuo** [kestra-io/kestra#822]
### Expected Behavior

Trying this example in Kestra UI editor.
```
tasks:
  - id: echo
    type: io.kestra.core.tasks.scripts.Bash
    commands:
      - echo "Hello John" > {{ outputDirs.output }}/1.txt
      - echo "Hello Jane" > {{ outputDirs.output }}/2.txt
      - echo "Hello Doe" > {{ outputDirs.output }}/3.txt
    outputDirs:
      - output
  - id: concat
    type: io.kestra.core.tasks.storages.Concat
    files: "{{ outputs.echo.files | jq('.[]') }}"
```

I'm expecting use files as string.

### Actual Behaviour

But UI always change files into list

### Environment Information

- Kestra Version:
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):
