### ISSUE TITLE
Allow displaying the BOOLEAN-type inputs as a toggle

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#8225]
### Feature description

We got multiple reports clearly highlighting that the 3 options in the BOOLEAN selection are confusing (and it's totally understandable):

![image](https://github.com/user-attachments/assets/aa913b91-88c3-4bd1-9bf5-001e9a7a0965)

How about adding a property `isToggle` so that, if true, we show the BOOLEAN-type input as a toggle (especially relevant for Apps)?

```yaml
id: bool_test
namespace: company.team

inputs:
  - id: test
    type: BOOLEAN
    defaults: true
    isToggle: true

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello {{ inputs.test }}
```

![image](https://github.com/user-attachments/assets/5fbce292-abd9-42b0-8ce6-3d7b9f3fce75)

cc @Nico-Kestra for the design of the toggle

**Comment by anna-geller** [comment]
We'll add a new input type called BOOL to avoid an immediate BC and BOOL-type input will be implemented as a toggle which is `false` by default unless explicitly toggled on:

```yaml
id: bool_test
namespace: company.team

inputs:
  - id: test
    type: BOOL # new input shown as toggle
    defaults: true

  - id: test2
    type: BOOLEAN # deprecated, to be removed later - show a warning in the UI
    defaults: true

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello {{ inputs }}
```
