### ISSUE TITLE
Nested subtasks are not displayed in the no-code editor

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#8269]
### Describe the issue

Query task is not showing up. To reproduce, use the flow:

```yaml
id: business-automation
namespace: tutorial
description: Business Automation

tasks:
  - id: working_directory
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      - id: query
        type: io.kestra.plugin.jdbc.sqlite.Queries
        url: jdbc:sqlite:kestra.db
        fetchType: STORE
        sql: |
          CREATE TABLE IF NOT EXISTS features (
              id INTEGER PRIMARY KEY,
              name TEXT NOT NULL,
              description TEXT NOT NULL,
              release_version TEXT NOT NULL,
              edition TEXT NOT NULL
          );

          DELETE FROM features;

          INSERT INTO features (name, description, release_version, edition)
          VALUES 
              ('Worker Groups', 'Allows targeting specific tasks or triggers to run on specific remote workers for better scalability and resource management.', '0.10', 'Enterprise'),
              ('Realtime Triggers', 'Supports triggering event-driven workflows in real-time.', '0.17', 'Open-Source'),
              ('Task Runners', 'Provides on-demand remote execution environments for running tasks.', '0.16', 'Open-Source'),
              ('KV Store', 'Adds key-value storage for persisting data across workflow executions.', '0.18', 'Open-Source'),
              ('SCIM Directory Sync', 'Allows synchronization of users and groups from Identity Providers.', '0.18', 'Enterprise');  
              
          SELECT * FROM features
          ORDER BY release_version;

      - id: to_csv
        type: io.kestra.plugin.serdes.csv.IonToCsv
        from: "{{ outputs.query.outputs[0].uri }}"

      - id: to_excel
        type: io.kestra.plugin.serdes.excel.IonToExcel
        from: "{{ outputs.query.outputs[0].uri }}"
```
![image](https://github.com/user-attachments/assets/9ab0016c-c74b-400e-a402-d8816c602a27)

### Environment

- Kestra Version: develop
