### ISSUE TITLE
Schedule flow are not started with Inputs variable

### ISSUE THREAD

**Issue by Skraye** [kestra-io/kestra#828]
### Expected Behavior

When I write a flow with Inputs that have a default value,
If I schedule my flow, when it is triggered, I want the inputs variable available in the flow.

### Actual Behaviour

When I write a flow with Inputs that have a default value,
If I schedule my flow, when it is triggered, the inputs variable is not available in the flow, making it fail.

### Steps To Reproduce

- Create a flow with a input that have a default value
- Set up a schedule
- Wait the schedule to trigger the flow

### Environment Information

- Kestra Version: 0.5.2

**Comment by Skraye** [comment]
Issue seems not fixed

Version: Kestra 0.11.0-SNAPSHOT 

```
id: "flow-a"
namespace: "dev"
inputs:
  - name: myinput
    type: STRING
    defaults: "mycontent"
tasks:
  - id: log
    type: io.kestra.core.tasks.log.Log
    message: "{{ inputs.myinput }}"
triggers:
  - type: io.kestra.core.models.triggers.types.Schedule
    cron: "*/1 * * * *"
    id: trigger
```
