### ISSUE TITLE
Postgres restart causes executions to get stuck

### ISSUE THREAD

**Issue by NovytskyiD** [kestra-io/kestra#8356]
### Describe the issue

In the scenario, when we restart the Postgres DB without stopping the Kestra instance, some tasks get stuck in the Created or Running state, and I should kill them manually.
Some tasks get stuck in Running even though all steps were Success, some - with task in Running (but it doesn't execute more)

Need to run several copies of this flow and reboot Postgres maybe several times.

```
id: skanDataRecalculationShard4Copy4
namespace: customerflows

concurrency:
  limit: 1
  behavior: CANCEL

variables:
  shardId: 
  customerName: 
  envName:

tasks:
  - id: checkAndRecalculateDataOnSQL
    type: io.kestra.plugin.core.flow.Subflow
    namespace: base
    flowId: skanDataRecalculation
    inputs:
      shardId: "{{vars.shardId}}"
      customerName: "{{vars.customerName}}" #if we use secret, we will not need to add customerName and envName here
      envName: "{{vars.envName}}"

  - id: isNeedToStartRegActionLayerJob
    type: io.kestra.plugin.core.flow.If
    condition: "{{outputs.checkAndRecalculateDataOnSQL.outputs.resultCheck contains 'DateFrom' }}"
    then:
    - id: regActionLayerShort
      type: io.kestra.plugin.core.flow.Subflow
      namespace: customerflows
      flowId: skanDataRecalculation


triggers:
  - id: every5Second
    type: io.kestra.plugin.core.trigger.Schedule
    disabled: false
    withSeconds: true
    cron: "/5 * * * * *"
    recoverMissedSchedules: NONE
```
subflow
```
id: skanDataRecalculation
namespace: base

sla:
  - id: maxDuration
    type: MAX_DURATION
    duration: PT30M
    behavior: FAIL
    labels:
      sla: miss
      reason: durationExceeded

inputs:
  - id: customerName
    type: STRING
    defaults: PP #maybe we should use here secret ('Customer')

  - id: envName
    type: STRING
    defaults: Dev #maybe we should use here secret ('Environment')

  - id: shardId
    type: STRING
    defaults: "4"

tasks:
  - id: getCredentials
    type: io.kestra.plugin.core.flow.Subflow
    namespace: service
    flowId: getCredentialsFromVault
    inputs:
      customerName: "{{inputs.customerName}}"
      envName: "{{inputs.envName}}"
      secretName: "{{inputs.customerName ~ '_' ~ inputs.envName ~ '_SQLServer_Shard' ~ inputs.shardId}}" 

  - id: checkAndRecalculateDataOnSQL
    type: "io.kestra.plugin.jdbc.sqlserver.Query"
    url: jdbc:sqlserver://{{ outputs.getCredentials.outputs.resultCredentials.data.Address }};trustServerCertificate=true
    username: "{{ outputs.getCredentials.outputs.resultCredentials.data.User }}"
    password: "{{ outputs.getCredentials.outputs.resultCredentials.data.Password }}"
    sql: 
    fetchType: FETCH_ONE

outputs:
  - id: resultCheck
    type: JSON
    value: "{{ outputs.checkAndRecalculateDataOnSQL.row | default({}) }}"
```

I have tried to add SLA to the parent flow, and it works, but kills only the parent job, subflows are still in Running, and new copies of the parent flow can't start. After the SLA Fail, I had to restart the execution, and after this new execution was started by the trigger, so using SLA is not a decision for this problem

```
sla:
  - id: maxDuration
    type: MAX_DURATION
    duration: PT5M
    behavior: FAIL
    labels:
      sla: miss
      reason: durationExceeded
```

### Environment

- Kestra Version: 0.22.2
