### ISSUE TITLE
[Multi-Panel editor] Cannot save the flow after making changes

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#8368]
### Describe the issue

To reproduce, create a first revision of some flow e.g.:

```yaml
id: hello
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀
```

Then try to change the message and Save again e.g.:
```yaml
id: hello
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello kestra
```

You should see the error: `Invalid entity. At flow.id: Flow id already exists`

![Image](https://github.com/user-attachments/assets/d5851e83-c40f-4c26-829c-93a3d178b444)

### Environment

- Kestra Version: develop
