### ISSUE TITLE
UI: When editing the flow, the warning box shows up empty.

### ISSUE THREAD

**Issue by starlightknown** [kestra-io/kestra#8389]
### Describe the issue

<img width="681" alt="Image" src="https://github.com/user-attachments/assets/9d8223e7-b398-4568-b467-243d4888c5a6" />

Steps to reproduce:

Change the description to something short maybe like "Hello Wo" and see the warning come up

### Environment

- Kestra Version: develop

**Comment by Ben8t** [comment]
Hello, I'm not able to reproduce with a flow like this:
```yaml
id: elephant_969046
namespace: dev.ben
description: "Hello Wo"
tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀
```

Can you provide a screencast or proper resources and details to reproduce please?
