### ISSUE TITLE
Notification plugins like SlackExecution cannot react to a PAUSED state

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#8393]
### Describe the issue

Polling for status forever:

![Image](https://github.com/user-attachments/assets/d9e1c7e9-ca36-4ac8-9af0-26766ef66696)

To reproduce, add a flow with Pause task:

```yaml
id: pause
namespace: company.team

tasks:
  - id: log_before
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 
    
  - id: pause
    type: io.kestra.plugin.core.flow.Pause

  - id: log_after
    type: io.kestra.plugin.core.log.Log
    message: Resumed!
```

Then, add a flow reacting to the PAUSED state for that flow:

```yaml
id: react
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World!
  
  - id: send_slack_alert
    type: io.kestra.plugin.notifications.slack.SlackExecution
    url: https://reqres.in/api/slack
    executionId: "{{trigger.executionId}}"
  
triggers:
  - id: paused
    type: io.kestra.plugin.core.trigger.Flow
    preconditions:
      id: paused_flow
      flows:
        - namespace: company.team
          flowId: pause
    states:
      - PAUSED
```

What's also worrisome is that when adding the list of states to the preconditions.flows as shown below makes the Executor not react to the Paused state at all:

```yaml
id: react_to_paused
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World!
  
  - id: send_slack_alert
    type: io.kestra.plugin.notifications.slack.SlackExecution
    url: https://reqres.in/api/slack
    executionId: "{{trigger.executionId}}"
  
triggers:
  - id: paused
    type: io.kestra.plugin.core.trigger.Flow
    preconditions:
      id: paused_flow
      flows:
        - namespace: company.team
          flowId: pause
          states:
            - PAUSED
```

Adding the top level states as follows fixes it in the sense that at least flow trigger starts to fire some executions in response to the Paused state but even then, it keeps polling the EventListener instead of triggering the SlackExecution task for the `trigger.executionId`:

```yaml
id: react_to_paused
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World!
  
  - id: send_slack_alert
    type: io.kestra.plugin.notifications.slack.SlackExecution
    url: https://reqres.in/api/slack
    executionId: "{{trigger.executionId}}"
  
triggers:
  - id: paused
    type: io.kestra.plugin.core.trigger.Flow
    preconditions:
      id: paused_flow
      flows:
        - namespace: company.team
          flowId: pause
          states:
            - PAUSED
    states:
      - PAUSED            
```

### Environment

- Kestra Version: develop

**Comment by anna-geller** [comment]
@AcevedoR or @loicmathieu could one of you investigate?

**Comment by loicmathieu** [comment]
`PAUSED` is not in the list of states that are listened to by the Flow trigger by default, so it must be added via the `states` property, as you did in your last example.

I'm not sure what you mean by

> even then, it keeps polling the EventListener instead of triggering the SlackExecution task for the trigger.executionId:

This seems to be an issue with the the SlackExecution task, nothing specific to reacting to the PAUSED state, here it correctly reacts to the PAUSED state. Closing it as everything work as expected.

**Comment by anna-geller** [comment]
If user already defined PAUSED state in the preconditions, this must be enough. We should no longer require to add it in the states:

```yaml
triggers:
  - id: paused
    type: io.kestra.plugin.core.trigger.Flow
    preconditions:
      id: paused_flow
      flows:
        - namespace: company.team
          flowId: pause
          states:
            - PAUSED
    states:
      - PAUSED  
```

That syntax forcing user to double the `states` definition is not acceptable from the UX perspective.

Also, `SlackExecution` works as expected with the FAILED state:

```yaml
id: react
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World!
  
  - id: send_slack_alert
    type: io.kestra.plugin.notifications.slack.SlackExecution
    url: https://reqres.in/api/slack
    executionId: "{{trigger.executionId}}"
  
triggers:
  - id: paused
    type: io.kestra.plugin.core.trigger.Flow
    states:
      - FAILED            
```      

![Image](https://github.com/user-attachments/assets/aa1ec3e9-788d-42a5-9f00-c4a926b0ab9f)

but trying the same with PAUSED leads to a completely different behavior:

```yaml
id: react_to_paused
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World!
  
  - id: send_slack_alert
    type: io.kestra.plugin.notifications.slack.SlackExecution
    url: https://reqres.in/api/slack
    executionId: "{{trigger.executionId}}"
  
triggers:
  - id: paused
    type: io.kestra.plugin.core.trigger.Flow
    states:
      - PAUSED            
```    

![Image](https://github.com/user-attachments/assets/fc750a9d-3d5c-460c-92c3-0611767c4abc)

I guess this is because the paused upstream execution ID is not finished and the SlackExecution seems to only work with finished executions? this seems unexpected and is clearly also a bug
