### ISSUE TITLE
Flow Trigger stops working when Local Flow Synchronisation is on

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#8420]
### Describe the issue

User from YouTube on the [Local Flow Synchronization video](https://kestra.io/docs/how-to-guides/local-flow-sync):

> I have started using this feature yesterday, so I can have a simple way for backing up my flows without having to backup the Postrgres DB from Kestra.
> 
> However, since I activated this feature, the FlowTriggers in those flows are no longer working - meaning, Kestra won't start a flow based on a FlowTrigger.
> 
> Coincidence? Did anyone else encounter this behavior?

Will try and reproduce, but reporting now to keep track of it.

### Environment

- Kestra Version: develop

**Comment by wrussell1999** [comment]
Using `0.22.3`, the Local Flow Sync would only create the files in the local folder, I was unable to add flows into the folder and have them appear in Kestra. Also if I removed flows from the folder, it didn't remove them from Kestra.

Using `develop`:
- I could copy a new flow into the local folder and it would appear in Kestra ✅ 
- I could create a new blank file and turn it into a flow, and it would appear in Kestra ✅ 
- I could not drag and drop a file from a different folder to the local folder in the VSCode file explorer ❌ 
- I could not delete a file from the VSCode file explorer and empty trash and it remove it from Kestra ❌ 
- I could not delete a file from the terminal with `rm` and it remove it from Kestra ❌ 
- If the flow was removed from the local folder and then the flow was deleted inside of Kestra, it causes a 400 in the Kestra logs, and the flow remains inside of Kestra as viewable and executable.
  - `kestra-1    | 11:09:12.356 INFO  default-nioEventLoopGroup-1-6 io.kestra.webserver.access 2025-04-16T11:09:12.101Z | DELETE /api/v1/flows/delete/by-ids HTTP/1.1 | status: 400 | ip: 172.31.0.1 | length: 269 | duration: 4`
  - If I add the flow back to the folder, it still doesn't work.

Examples I am using:
`company.team_extract.yml`:
```yaml
id: extract
namespace: company.team

tasks: 
  - id: final_date
    type: io.kestra.plugin.core.debug.Return
    format: "{{ execution.startDate | dateAdd(-2, 'DAYS') | date('yyyy-MM-dd') }}"

outputs: 
  - id: date
    type: STRING
    value: "{{ outputs.final_date.value }}"
```

`company.team_transform.yml`:
```yaml
id: transform
namespace: company.team

inputs:
  - id: date
    type: STRING
    defaults: "2025-01-01"

variables:
  result: |
    Ingestion done in {{ trigger.executionId }}.
    Now transforming data up to {{ inputs.date }}

tasks:
  - id: run_transform
    type: io.kestra.plugin.core.debug.Return
    format: "{{ render(vars.result) }}"

  - id: log
    type: io.kestra.plugin.core.log.Log
    message: "{{ render(vars.result) }}"

triggers:
  - id: run_after_extract
    type: io.kestra.plugin.core.trigger.Flow
    inputs:
      date: "{{ trigger.outputs.date }}"
    preconditions:
      id: flows
      flows:
        - namespace: company.team
          flowId: extract
          states: [SUCCESS]
```

<details>

<summary>Docker Compose File</summary>
You will need to change the volume mount to a local directory on your machine.

```yaml
volumes:
  postgres-data:
    driver: local
  kestra-data:
    driver: local

services:
  postgres:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: kestra
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: k3str4
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 10

  kestra:
    image: kestra/kestra:develop
    pull_policy: always
    # Note that this setup with a root user is intended for development purpose.
    # Our base image runs without root, but the Docker Compose implementation needs root to access the Docker socket
    # To run Kestra in a rootless mode in production, see: https://kestra.io/docs/installation/podman-compose
    user: "root"
    command: server standalone
    volumes:
      - kestra-data:/app/storage
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/kestra-wd:/tmp/kestra-wd
      - /Users/wrussell/Documents/Repositories/kestra-server/example/example_flows:/local_flows
    env_file:
      - .env_encoded
    environment:
      KESTRA_CONFIGURATION: |
        datasources:
          postgres:
            url: jdbc:postgresql://postgres:5432/kestra
            driverClassName: org.postgresql.Driver
            username: kestra
            password: k3str4
        kestra:
          server:
            basic-auth:
              enabled: false
              username: "admin@kestra.io" # it must be a valid email address
              password: kestra
          repository:
            type: postgres
          storage:
            type: local
            local:
              base-path: "/app/storage"
          queue:
            type: postgres
          tutorial-flows:
            enabled: false 
          tasks:
            tmp-dir:
              path: /tmp/kestra-wd/tmp
          url: http://localhost:8080/
        micronaut:
          io:
            watch:
              enabled: true
              paths:
                - /local_flows

    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_started
```

</details>
