### ISSUE TITLE
Test unit / integration of flows

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#844]
Find a proper way to unit test flow and to validate there is no regression during development. 

- Mostly a design thinking, **WIP**. 
- For now, we are mostly thinking about integration test that will use effective resource behind (docker, cloud, ...) 
- We create a unit test definition (mostly in yaml, concept below) 
  - In the definition, we add the flow definition and how to start a flow 
  - We have easy assert on the final result of the execution 
  - We must be able to have some custom tasks to validate the data on the destination 
- we start it with the kestra cli: `./kestra unit <dir>` 

```yaml
# list of flow to inject 
flows: 
 - path: path/to/flow.yml
   variables: 
     my-var: "override a vars"
 - path: path/to/subflow.yml
​
# list of template to inject 
templates: 
 - path: path/to/templates.yml 
​
# variables to overwrite 
variables: 
  globals: 
    my-env: "variable"

​
# variables to overwrite 
taskDefaults: 
  - type: io.kestra.core.tasks.debugs.Return
    values:  
      format: "here is {}"
​
# the flow to start with the inputs 
run: 
  namespace: io.kestra
  id: flow-a
  inputs: 
    first-input: bla 
    first-file: path/to/a/file.yml
​
# test to do 
tests: 
  # validate execution status 
  - type: EXPR 
    expr: "{{ execution.state.current == 'SUCCESS' }}"
  # validate task executed 
  - type: EXPR 
    expr: "{{ execution.taskRunList | length == 12 }}"
  # validate outputs on a task 
  - type: EXPR 
    expr: "{{ outputs.my-task.id > 0 }}"
  # use a kestra task to fetch data from external services and validate the data on external service 
  - type: TASK
    expr: "{{ outputs.query.row.count > 0 }}"
    task:
      id: "query"
      type: "io.kestra.plugin.gcp.bigquery.Query"
      fetch: true
      sql: |
        SELECT COUNT(*) as count FROM `my-dataset.table`
```
