### ISSUE TITLE
Schedule not resuming after SLA cancellation

### ISSUE THREAD

**Issue by DanielGuelfi** [kestra-io/kestra#8459]
### Describe the issue

When defining an SLA on a flow (as below):

```yaml
sla:
  - id: maxDuration
    type: MAX_DURATION
    duration: PT4H
    behavior: CANCEL
    labels:
      sla: miss
      reason: durationExceeded
```

When the SLA is breached (and the flow is subsequently cancelled) the flow will no longer execute as per the schedule. This then requires a change to be made to the schedule definition (even a simple trigger ID change) which then rectifies the issue, and the schedule resumes.

To add to the above, when viewing the trigger record in the `triggers` database table, I noticed that the `execution_id` field was populated which corresponded to the `CANCELLED` flow execution ID. When I manually modified the `value` field to remove the `execution_id` reference, the schedule then resumed.

It appears that when the SLA is breached, the trigger record is not amended to remove the `execution_id` value so the scheduler thinks there is still a running instance of the flow and so does not trigger another execution?

### Environment

- Kestra Version: 0.22.2
