### ISSUE TITLE
The `kestra` Pebble object used in the expression `hello from {{kestra}}` doesn't work on EE (works in OSS)

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#8487]
### Describe the issue

in my configuration, I explicitly added:
```yaml
        kestra:
          url: http://localhost:8080/
          environment: 
            name: dev
```

still, it doesn't work:

![Image](https://github.com/user-attachments/assets/1fe6c8e0-d8e7-4030-b68f-d1664ab095ce)

```yaml
id: repro
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: hello from {{ kestra.environment.name }} 
    allowFailure: true

  - id: hello2
    type: io.kestra.plugin.core.log.Log
    message: hello from {{ kestra.url }}
    allowFailure: true
```

as per https://kestra.io/docs/configuration#kestra-url and https://kestra.io/blogs/release-0-22#new-pebble-functions, this should work?

### Environment

- Kestra Version: develop

**Comment by anna-geller** [comment]
@loicmathieu you added it here https://github.com/kestra-io/kestra/commit/1ba54cd08, am I doing sth wrong or is it a bug?

**Comment by wrussell1999** [comment]
I was able to reproduce this partially. I'm using `develop` on OSS.

Configuration same as Anna's:

```yaml
kestra:
  url: http://localhost:8084/
  environment:
    name: dev
```

Example flow where the first 2 succeed, final one fails:
```yaml
id: example_flow
namespace: company.team

tasks:
  - id: url
    type: io.kestra.plugin.core.log.Log
    message: "My URL: {{ kestra.url }}"

  - id: env
    type: io.kestra.plugin.core.log.Log
    message: "hello from {{ kestra.environment }}"

  - id: env_name
    type: io.kestra.plugin.core.log.Log
    message: "hello from {{ kestra.environment.name }}"
```

Logs showing 2 successful tasks, and 1 failure:
![Image](https://github.com/user-attachments/assets/d9c7331e-b2b8-47fb-b986-5d5875f3d424)

Debug Outputs for `{{ kestra }}` show that `kestra.environment.name` from the config is remapped to `kestra.environment` in Kestra:
![Image](https://github.com/user-attachments/assets/951972cc-e52c-4010-b340-410cd3be1fe0)

**Comment by wrussell1999** [comment]
Doing some more digging, it seems that `kestra` isn't coming up on EE, but it is on OSS. There's 2 problems here:

- [ ] `kestra.environment.name` becomes `{{ kestra.environment }}`
- [ ] `{{ kestra }}` doesn't work on EE

**Comment by loicmathieu** [comment]
I confirm this is only an EE issue.

For the record, the correct flow should be:

```yaml
id: repro
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: hello from {{ kestra.environment.name }} 
    allowFailure: true

  - id: hello2
    type: io.kestra.plugin.core.log.Log
    message: hello from {{ kestra.url }}
    allowFailure: true
```
