### ISSUE TITLE
[Execution filter] can't filter using the `is not` operator

### ISSUE THREAD

**Issue by yuri1969** [kestra-io/kestra#8494]
### Describe the issue

Using the current v0.23-SNAPSHOT version the `is not` operator doesn't really work. For example, the `labels is not foo:bar` returns no results even when there are executions featuring no `foo:bar` label. Or the `relative date is not PT1H` filter returns also executions executed last hour.

# Reproduction

1. Save the flow from below
2. Execute the flow
3. Apply the following negative execution filter: `labels is not a:b`
4. There are no executions but the previously created execution should be visible - it does not feature the label `a:b`

## Test flow

```yaml
id: turkey_547219
namespace: company.team

labels:
  foo: bar

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀
```

### Environment

- Kestra Version: develop
