### ISSUE TITLE
[Execution filter] amend Namespace `contains` filter

### ISSUE THREAD

**Issue by yuri1969** [kestra-io/kestra#8498]
### Describe the issue

Given the _Namespace_ filter contains both `starts with` and `contains`  operators the latter should behave differently from the former.

1. A manually entered value of the `contains` operator doesn't bring executions of a namespace containing such filter value.
2. The `contains` operator lists values namespaces which suits `starts with` more since the `contains` filter should operate on namespace "inner" parts (e.g. `team` -> `company.team.foo`).

---

# Example

## Flow

Define namespace `company.team.foo`:

```yaml
id: tapir_611734
namespace: company.team.foo

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀
```

## Filter

Running the develop via `./gradlew runLocal`.

Filter executions including the `company.team.foo` namespace using the `namespace contains team` filter:

http://localhost:8080/ui/executions?filters[namespace][CONTAINS]=team

### Environment

- Kestra Version: develop
