### ISSUE TITLE
docker Plugin - Improper cast of the CPU property

### ISSUE THREAD

**Issue by ReLoutre** [kestra-io/kestra#8510]
### Describe the issue

Should be possible to use a floating number for the "CPU: CPUS" property of the docker Plugin but the cpu property is cast to a long which prevents us to do so.

``` yaml
type: io.kestra.plugin.docker.Run
  cpu:
    cpus: "1.5" #should be possible but is not
```

![Image](https://github.com/user-attachments/assets/9c7b6edc-169c-49ef-9c9d-f1aa033a6690)

### Environment

- Kestra Version: 0.22.4
