### ISSUE TITLE
Task not keeping included files with same name in Python command execution plugin

### ISSUE THREAD

**Issue by notfounnd** [kestra-io/kestra#8521]
### Describe the issue

Executing Python files using Commands plugin, if it get two files with same name that exist in included path of namespaceFiles, task will keep only the last file loaded from the folder structure.

![Image](https://github.com/user-attachments/assets/84c569ed-7f3c-4593-b228-b6a0b0b07363)

![Image](https://github.com/user-attachments/assets/e1b52ef8-7811-4610-a036-6866002a0633)

I've checked this behaviour after update my Kestra instance (v0.21.5 --> v0.22.4). Before the update, in previous installed version, this behaviour not occur.

---

### Files structure

```
📦 kestra files
└── 📂 xyz
    ├── 📂 script_a
    |   └── 📜 hello_world.py
    └── 📂 script_b
        └── 📜 hello_world.py
```

> Python scripts just have a print() command for help examplify this issue.

### Flow

```yaml
id: check_load_script_file
namespace: xyz

tasks:
  - id: hello_world
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀
  
  - id: execute_script
    type: io.kestra.plugin.core.flow.Parallel
    tasks:

      - id: execute_script_a
        type: io.kestra.plugin.scripts.python.Commands
        warningOnStdErr: false
        commands:
          - python xyz/scritp_a/hello_world.py
        namespaceFiles:
          enabled: true
          include:
            - xyz/**
        taskRunner:
          type: io.kestra.plugin.core.runner.Process

      - id: execute_script_b
        type: io.kestra.plugin.scripts.python.Commands
        warningOnStdErr: false
        commands:
          - python xyz/scritp_b/hello_world.py
        namespaceFiles:
          enabled: true
          include:
            - xyz/**
        taskRunner:
          type: io.kestra.plugin.core.runner.Process

```

### Environment

- Kestra Version: 0.22.4

**Comment by notfounnd** [comment]
Fixed in [v0.22.5](https://github.com/kestra-io/kestra/releases/tag/v0.22.5).

- https://github.com/kestra-io/kestra/pull/8562
- https://github.com/kestra-io/kestra/commit/0de1caac2a67ae1744cbb5b44fc8dfee72d10659
- https://github.com/kestra-io/kestra/commit/be968cb20b463a3ba81671c768bb855d7f777ff4

### Files
```
📦 kestra files
└── 📂 xyz
    ├── 📜 requirements.txt
    ├── 📂 script_a
    |   └── 📜 hello_world.py
    ├── 📂 script_b
    |   └── 📜 hello_world.py
    └── 📂 script_c
        └── 📜 hello_world.py
```
> Python scripts just have a print() command for help examplify this issue.

### Flow
```yaml
id: check_load_script_file
namespace: xyz

tasks:
  - id: hello_world
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀
  
  - id: execute_script
    type: io.kestra.plugin.core.flow.Parallel
    tasks:

      - id: execute_script_a
        type: io.kestra.plugin.scripts.python.Commands
        warningOnStdErr: false
        commands:
          - python xyz/script_a/hello_world.py
        namespaceFiles:
          enabled: true
          include:
            - xyz/**
        taskRunner:
          type: io.kestra.plugin.core.runner.Process

      - id: execute_script_b
        type: io.kestra.plugin.scripts.python.Commands
        warningOnStdErr: false
        commands:
          - python xyz/script_b/hello_world.py
        namespaceFiles:
          enabled: true
          include:
            - xyz/**
        taskRunner:
          type: io.kestra.plugin.core.runner.Process

      - id: execute_script_c
        type: io.kestra.plugin.scripts.python.Commands
        warningOnStdErr: false
        beforeCommands:
          - pip install -r xyz/requirements.txt > /dev/null
        commands:
          - python xyz/script_c/hello_world.py
        namespaceFiles:
          enabled: true
          include:
            - xyz/**
        taskRunner:
          type: io.kestra.plugin.core.runner.Process
```
### Logs
![Image](https://github.com/user-attachments/assets/812774e3-1af2-4dff-bffa-2380f65cb3f5)

### Environment
- Kestra Version: 0.22.5
