### ISSUE TITLE
Caching example from the documentation fails in the latest version

### ISSUE THREAD

**Issue by elcapo** [kestra-io/kestra#8540]
### Describe the issue

The **Python example** from the **Caching** section:

~~~python
id: python_cached_dependencies
namespace: company.team

tasks:
  - id: working_dir
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      - id: python_script
        type: io.kestra.plugin.scripts.python.Script
        taskRunner:
          type: io.kestra.plugin.core.runner.Process
        warningOnStdErr: false
        beforeCommands:
          - python -m venv venv
          - source venv/bin/activate
          - pip install pandas
        script: |
          import pandas as pd
          print(pd.__version__)
    cache:
      patterns:
        - venv/**
      ttl: PT24H
~~~

... fails in the latest Kestra version.

The first error is due to the **source** binary not being available.

- [kestra-execution-1.log](https://github.com/user-attachments/files/19931670/kestra-execution-1.log)

> ERROR /bin/sh: 3: source: not found

Replacing **source** with a dot doesn't seem to work, as the log starts showing a warning recommending to use a virtual environment.

> ERROR WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
> 
> ERROR ModuleNotFoundError: No module named 'pandas'

- [kestra-execution-2.log](https://github.com/user-attachments/files/19931672/kestra-execution-2.log)

### Environment

- Kestra Version: 0.22.4 (Docker)

**Comment by Ben8t** [comment]
In more [recent version we added a proper dependancy propery for Python task](https://kestra.io/docs/how-to-guides/python-dependencies#cache-dependencies-beta), worth checking out for your issue.
Issue is still valid though (checked on 0.24 and the flow still fails)

**Comment by Saravana-PS** [comment]
@elcapo @tchiotludo  Is this an active issue. Can I work on this?

**Comment by MilosPaunovic** [comment]
Absolutely, go for it @Saravana-PS, thanks! 🚀

**Comment by MilosPaunovic** [comment]
Hey @Saravana-PS, are there any updates on this?

**Comment by MilosPaunovic** [comment]
Hi @Saravana-PS,

As there hasn't been any progress or updates on this, I'll unassign you for now. However, if you do open a PR, it will be reviewed, and you'll be reassigned if no one else handles it in the meantime.

Thanks for all the efforts so far! 🍀

**Comment by Saravana-PS** [comment]
Hi @MilosPaunovic , Apologies for the delay. I will raise the PR and let you know.

**Comment by Pradumnasaraf** [comment]
Hi, both the above and the updated example in the docs aren't working for me. Is the issue still not fixed?

> Issue Example

```yaml
id: python_cached_dependencies
namespace: company.team

tasks:
  - id: working_dir
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      - id: python_script
        type: io.kestra.plugin.scripts.python.Script
        taskRunner:
          type: io.kestra.plugin.core.runner.Process
        warningOnStdErr: false
        beforeCommands:
          - python -m venv venv
          - source venv/bin/activate
          - pip install pandas
        script: |
          import pandas as pd
          print(pd.__version__)
    cache:
      patterns:
        - venv/**
      ttl: PT24H
```

> Docs Example

```yaml
id: python_cached_dependencies
namespace: company.team

tasks:
  - id: working_dir
    type: io.kestra.plugin.core.flow.WorkingDirectory
    cache:
      patterns:
        - venv/**
      ttl: PT24H
    tasks:
      - id: python_script
        type: io.kestra.plugin.scripts.python.Commands
        taskRunner:
          type: io.kestra.plugin.core.runner.Process
        warningOnStdErr: false
        beforeCommands:
          - python -m venv venv
          - ./venv/bin/pip install pandas
        commands:
          - ./venv/bin/python -c "import pandas as pd; print(pd.__version__)"
```

**Comment by Pradumnasaraf** [comment]
Anyone?

**Comment by elcapo** [comment]
> Anyone?

The PR was pushed to **develop** two weeks ago.
So, I'd suggest trying the latest version, v1.3.7.

What version are you using?

**Comment by Pradumnasaraf** [comment]
I am using the latest `develop` image. @fhussonnois, can you have a look? cc @Ben8t

**Comment by Pradumnasaraf** [comment]
Reopening this issue, the issue is still reproducible. Asked for clarity previously, still waiting for that!!

**Comment by jaybamroliya** [comment]
Hi! I've submitted a PR to fix this issue in the docs repo.

The problem is that `source` command is not available in Kestra's `/bin/sh` shell environment.

Fix: use `./venv/bin/pip install pandas` directly instead of activating the venv.

PR: https://github.com/kestra-io/docs/pull/4858

**Comment by Pradumnasaraf** [comment]
`python -m venv venv` fails because the Kestra Docker images don't ship `python3-venv`. The virtual environment was not created successfully because ensurepip is not available. The rest of `beforeCommands` and the script never run.

```yaml
id: python_cached_dependencies
namespace: company.team

tasks:
  - id: working_dir
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      - id: python_script
        type: io.kestra.plugin.scripts.python.Script
        taskRunner:
          type: io.kestra.plugin.core.runner.Process
        beforeCommands:
          - python -m venv venv
          - ./venv/bin/pip install pandas
        script: |
          import pandas as pd
          print(pd.__version__)
    cache:
      patterns:
        - venv/**
      ttl: PT24H
```

<img width="1278" height="1080" alt="Image" src="https://github.com/user-attachments/assets/c53282ac-3f9d-4424-8b5c-652b328b703d" />
