### ISSUE TITLE
Add a Notion plugin + Notion blueprints

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#8557]
### Feature description

Now that Notion (finally!!!) supports webhooks (new feature https://developers.notion.com/reference/webhooks), we should add a Notion plugin.

No need for any Notion trigger plugin, as kestra's native Webhook-type trigger will allow us to start some automation whenever some Notion database has new/modified/deleted entries, but we can add tasks allowing to modify Notion databases.

Common use cases:
- Whenever there is a new row (potentially matching some criteria) in my Notion database, send a message to notify stakeholders about it (new incident, new customer)
- Whenever there is a new form submission, send that Notion form submission (database row) to some database 
- ...many use cases

@aj-emerich no urgency, but you can already plan some blueprints before we have a Notion plugin, as the new webhook integration in Notion is the main enabler for automation with Kestra

**Comment by Ben8t** [comment]
For Notion plugin start with:
- add CRUD for Notion database entries
- add CRUD for Notion pages

**Comment by Ben8t** [comment]
A first version of Notion plugin has been release in 0.23 - https://github.com/kestra-io/plugin-notion

Next steps:
- Add blueprints
- Add tasks to manage row and database (for now the plugin only have tasks about pages)

**Comment by aj-emerich** [comment]
It could be cool to make a blueprint that combines fetching some information, summarizing with an AI plugin, and then populating the AI summary in a Notion page.

**Comment by anna-geller** [comment]
AJ is trying to kill Notion AI 😂 jk, I think if you mean to fetch data from other sources that live outside of Notion, then summarizing and loading to Notion, seems like a fair use case 👍 I can see how this can be used to fetch e.g. competitive market insights with Perplexity plugin and inserting as sort of ecosystem news entry for a given day to a Notion database

**Comment by aj-emerich** [comment]
Yes I meant sources outside of Notion 😆

**Comment by aj-emerich** [comment]
I made something straightforward. Structuring AI output is kind of a pain atm 😄 I'll play around with the database tasks too.

```
id: perplexity_notion
namespace: aj-test

tasks:
  - id: chat-completion
    type: io.kestra.plugin.perplexity.ChatCompletion
    apiKey: "{{ secret('PERPLEXITY_API_KEY') }}"
    model: sonar
    messages:
      - type: USER
        content: "Can you compile a list of the most important news for today for a person living in Berlin, Germany? Please respond with a bulleted list of headline and a hyperlink to the text all as markdown."
    temperature: 0.7
  - id: create-notion-page
    type: io.kestra.plugin.notion.page.Create
    apiToken: "{{ secret('NOTION_API_KEY') }}"
    parentPageId: "25329f90080180348917e77663706a92"
    title: "Daily News Summary from AI"
    content: "{{ outputs['chat-completion'].outputText }}"
    
  - id: send-slack-notification
    type: io.kestra.plugin.notifications.slack.SlackIncomingWebhook
    url: "{{ secret('SLACK_WEBHOOK_URL') }}"
    messageText: "New Notion page created: {{ outputs['create-notion-page'].url }}"

triggers:
  - id: daily_run
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 0 * * *"
```

**Comment by aj-emerich** [comment]
https://github.com/kestra-io/blueprints/pull/100

**Comment by anna-geller** [comment]
@aj-emerich, can you add another blueprint/how to guide using the new Notion webhook system, pasting Kestra's webhook trigger there? after that you could close the issue as it will give us 2 blueprints, one using webhook and another using the Notion plugin task 

the use case is up to you, to give you some idea: you could hook it up to our Product Team Notion board e.g. to get notified whenever via Slack there is a new task assigned to you in that Notion DB - might be even quite practical for us :)

FWIW I think the Notion webhook use case is better suited for a how to guide than a blueprint to include some screenshots and step by step guidance

<img width="1214" height="1288" alt="Image" src="https://github.com/user-attachments/assets/409038f0-da95-472b-93da-338bd2f7ad52" />

**Comment by aj-emerich** [comment]
Unfortunately, I can't make integrations in our Notion Workspace, but I can play with it in a personal one to recreate it.

**Comment by anna-geller** [comment]
would be a matter of talking to Ludo, but no problem with a personal notion for sure 👍

**Comment by aj-emerich** [comment]
Here is a workflow that tracks for a change in a Notion database ( e.g., a new task page added to the board) and sends a Slack message with the task's title, assignee, and URL to a channel. I can clean it up and turn it into a how-to guide tomorrow.

```yaml
id: notion-webhook
namespace: aj-test

tasks:
  - id: get_notion_page_details
    type: io.kestra.plugin.core.http.Request
    uri: "https://api.notion.com/v1/pages/{{ trigger.body.entity.id }}"
    method: GET
    headers:
      Authorization: "Bearer {{ secret('NOTION_API_KEY_2') }}"
      Notion-Version: "2022-06-28"

  - id: send_slack_alert
    type: io.kestra.plugin.notifications.slack.SlackIncomingWebhook
    url: "{{ secret('SLACK_WEBHOOK_URL') }}"
    messageText: "New task titled {{ outputs.get_notion_page_details.body | jq('.properties.Button.title[0].text.content') | first }} assigned to {{ outputs.test_api_request.body | jq('.properties.Assignee.multi_select[0].name') | first }} on the Product team Notion board! Link: {{ outputs.get_notion_page_details.body | jq('.url') | first }}"

triggers:
  - id: notion_new_task_webhook
    type: io.kestra.plugin.core.trigger.Webhook
    key: my-notion-product-alert-key # Replace with a secure key
```
