### ISSUE TITLE
Plugin Defaults + docker plugin make the completion hints weird

### ISSUE THREAD

**Issue by ReLoutre** [kestra-io/kestra#8564]
### Describe the issue

Reproducer :
```
id: gaur_714762
namespace: company.team

pluginDefaults:
  - forced: false
    type: io.kestra.plugin.docker.Run
    values:
      containerImage: alpine:latest
      entryPoint: ["/bin/sh", "-c"]
      pullPolicy: IF_NOT_PRESENT

tasks:
  - id: test-wait
    type: io.kestra.plugin.docker.Run
    wait: false
    commands:
      - sleep 5 && echo 'wait test' > wait.txt
    outputFiles:
      - wait.txt
    # GO THERE AND PRESS CTRL-SPACE
```
![Image](https://github.com/user-attachments/assets/897c50fe-6037-4c09-bf42-d1a7c9df6c8e)

![Image](https://github.com/user-attachments/assets/98f27022-699b-448b-a476-50aef7c54290)

### Environment

- Kestra Version: develop

![Image](https://github.com/user-attachments/assets/59759c4e-d7d0-4bd8-86ac-3e0e47a46e13)
