### ISSUE TITLE
dockerOptions set max container memory limit

### ISSUE THREAD

**Issue by Proxx** [kestra-io/kestra#857]
Feature request for max-memory (and cpu limit) in the dockerOptions block

### Discussed in https://github.com/kestra-io/kestra/discussions/856

<div type='discussions-op-text'>

<sup>Originally posted by **Proxx** December 27, 2022</sup>
When running an openai container with a large dataset the job gets killed 137 OOM exception
so i need to limit the containers memory usage like the `--memory=<value>` flag on the docker run command

e.g. `docker run -it alpine --memory=4gb` 

but i cannot find a way to do this. i tried the dockerOptions:
``` yaml
dockerOptions:
  dockerConfig: | 
    { 
      "HostConfig": {
        "Memory": 1073741824
      }
    }
```

``` yaml
dockerOptions:
  dockerConfig: | 
    {
      "Memory": 1073741824
    }
```

clearly i'm missing something here.

Regards
</div>
