### ISSUE TITLE
[Regression] Relative pluginDefaults don't work on develop (when specifying parent plugin path)

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#8600]
### Describe the issue

Reproducer:

```yaml
id: repro
namespace: company.team

tasks:
  - id: core_task
    type: io.kestra.plugin.core.http.Download

  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World!

pluginDefaults:
  - type: io.kestra.plugin.core
    values:
      level: WARN
      uri: https://huggingface.co/datasets/kestra/datasets/raw/main/csv/orders.csv
```

works fine on latest (0.22.4)

![Image](https://github.com/user-attachments/assets/18310704-f8ea-4dc0-a786-981856a7672c)

on develop though:

![Image](https://github.com/user-attachments/assets/d5d9bff0-8ccb-40fc-95f5-665bea54a2a2)

### Environment

- Kestra Version: develop
