### ISSUE TITLE
ForEachItem task delayed/stuck RUNNING after all child subflows complete including afterExecution

### ISSUE THREAD

**Issue by luka-jukic** [kestra-io/kestra#8609]
## Description:

When using the **io.kestra.plugin.core.flow.ForEachItem** task  to execute a large number of child subflows, the ForEachItem task itself remains in a RUNNING state for an extended period after all spawned child subflow executions, **including their afterExecution blocks**, have successfully completed and reached a final status in the Kestra UI. 
 
 
 
## Steps to Reproduce:

- Define two flows: a parent flow and a subflow, as provided below.
- The parent flow uses ForEachItem to iterate a number of items
- The ForEachItem task is configured with wait: true, batch.rows: 1, and calls the defined subflow.
- The subflow contains simple tasks (e.g., Log) and importantly, includes an afterExecution block.
- The parent flow has a task defined after the ForEachItem task.
 
 
 
## Expected behavior:

The ForEachItem task should transition from RUNNING to a final state shortly after the last child execution it was waiting for ts afterExecution phase completes. 

## Observed behavior:

The ForEachItem task in the parent flow remains in the RUNNING state for a considerable amount of time after all 1000 child subflow executions are confirmed as SUCCESS in the UI. This includes confirmation that the afterExecution task ran and completed for all child subflows. 

### Parent Flow:

```yaml
id: flow
namespace: test.flow

tasks:
  - id: extract
    type: io.kestra.plugin.jdbc.duckdb.Query
    sql: |
      INSTALL httpfs;
      LOAD httpfs;
      SELECT *
      FROM read_csv_auto('https://huggingface.co/datasets/kestra/datasets/raw/main/csv/orders.csv', header=True);
    store: true
  - id: each
    type: io.kestra.plugin.core.flow.ForEachItem
    items: "{{ outputs.extract.uri }}"
    batch:
      rows: 1
    namespace: test.flow
    flowId: subflow
    wait: true # wait for the subflow execution (including its afterExecution)
    transmitFailed: true # fail the task run if the subflow execution fails
    inputs:
      order: "{{ taskrun.items }}"
  - id: hello 
    type: io.kestra.plugin.core.log.Log
    message: Hello World!
```

### Sub Flow:

```yaml
id: subflow
namespace: test.flow

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀

afterExecution:
  - id: hello21
    type: io.kestra.plugin.core.log.Log
    message: Hello from afterExecution!
```

### Environment

Kestra Version: 0.22.4
OS: Linux
