### ISSUE TITLE
Unable to use conditional operators inside of Script Task `commands` property

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#8615]
### Describe the issue

In this workflow, I want to be able to check if an input is true or false. If it's true, then I want the expression to return the new value. In the specific example, it's returning a `-f` flag for a command line prompt if the user has selected `true` for the input, otherwise it leaves it blank.

However using the expression `{{ inputs.export ? '-f' : '' }}` doesn't work in the `commands` property and returns the error: 

```
Unexpected flow-map-end token in YAML stream: "}"YAML(0)
Unexpected flow-map-end token in YAML stream: "}"YAML(0)
Unexpected double-quoted-scalar token in YAML stream: "\"\n\n\n"YAML(0)
```

You can get around it by using a different task (in my examp,e, the `debug.Return` task) to render the expression and then using that pre-rendered value as you can see from the first command in the example below. The second line doesn't work though.

Full flow:
```yaml
id: test_expression
namespace: company.team

inputs:
  - id: export
    type: BOOL
    displayName: Export the response as a file?
    defaults: false

tasks:
  - id: output_file
    type: io.kestra.plugin.core.debug.Return
    format: "{{ inputs.export ? '-f' : '' }}"

  - id: code
    type: io.kestra.plugin.scripts.python.Commands
    taskRunner:
       type: io.kestra.plugin.core.runner.Process
    commands:
      - echo {{ outputs.output_file.value }}
      - echo "{{ inputs.export ? '-f' : '' }}"

```

Same happens on other types of `Commands` tasks like `shell`.

### Environment

- Kestra Version: `develop`

**Comment by loicmathieu** [comment]
Testing it on develop it do works:

```yaml
id: test_expression
namespace: company.team

inputs:
  - id: export
    type: BOOL
    displayName: Export the response as a file?
    defaults: false

tasks:
  - id: output_file
    type: io.kestra.plugin.core.debug.Return
    format: "{{ inputs.export ? '-f' : '' }}"

  - id: code
    type: io.kestra.plugin.scripts.python.Commands
    taskRunner:
       type: io.kestra.plugin.core.runner.Process
    commands:
      - "echo {{ outputs.output_file.value }}"
      - "echo {{ inputs.export ? '-f' : '' }}"
```

Note the double-quotes, there was not correctly set on the given example.

![Image](https://github.com/user-attachments/assets/46bd391b-166b-4508-a8cf-e0e3e458d6d0)
