### ISSUE TITLE
Python code syntax highlighted as task property

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#8621]
### Describe the issue

`else` syntax is green when the `if` is brown like the rest of the script. On OSS `develop`

![Image](https://github.com/user-attachments/assets/dde7e667-36b6-4818-b44d-1f77d6e947d7)

Full flow:
```yaml
id: transform_python
namespace: company.team

tasks:
  - id: download
    type: io.kestra.plugin.core.http.Download
    uri: https://dummyjson.com/carts/1

  - id: json_to_ion
    type: io.kestra.plugin.serdes.json.JsonToIon
    from: "{{outputs.download.uri}}"

  - id: transform
    type: io.kestra.plugin.graalvm.python.FileTransform
    from: "{{ outputs.json_to_ion.uri }}"
    script: |
      if row['id'] == 666:
        # remove un-needed row
        row = None
      else:
        # remove the 'products' column
        row['products'] = None
        # add a 'totalItems' column
        row['totalItems'] = row['totalProducts'] * row['totalQuantity']
```

### Environment

- Kestra Version: `develop`

**Comment by wrussell1999** [comment]
Hmm seems to happen on the normal Python script task too. Maybe a wider issue? Moving to the main repo as may be more generic.
![Image](https://github.com/user-attachments/assets/d447ddb8-240d-445c-a0f7-61a539102fc0)

**Comment by wrussell1999** [comment]
Another example:
https://kestra.io/blueprints/data-engineering-pipeline

`column` and the first `{` are highlighting incorrectly.

![Image](https://github.com/user-attachments/assets/56786e45-e0f2-46b2-bb56-7c67e9c89f90)

**Comment by Ben8t** [comment]
Not reproducible anymore here https://kestra.io/blueprints/data-engineering-pipeline.

but this one's still valid on preview:
```yaml
id: transform_python
namespace: company.team

tasks:
  - id: download
    type: io.kestra.plugin.core.http.Download
    uri: https://dummyjson.com/carts/1

  - id: json_to_ion
    type: io.kestra.plugin.serdes.json.JsonToIon
    from: "{{outputs.download.uri}}"

  - id: transform
    type: io.kestra.plugin.graalvm.python.FileTransform
    from: "{{ outputs.json_to_ion.uri }}"
    script: |
      if row['id'] == 666:
        # remove un-needed row
        row = None
      else:
        # remove the 'products' column
        row['products'] = None
        # add a 'totalItems' column
        row['totalItems'] = row['totalProducts'] * row['totalQuantity']
```
