### ISSUE TITLE
Task Retry Interval Behavior in Kestra: Inconsistency Between CREATE_NEW_EXECUTION and RETRY_FAILED_TASK

### ISSUE THREAD

**Issue by FourFriends** [kestra-io/kestra#8664]
https://github.com/kestra-io/kestra/blob/0c93bc627551ddb65667389c20e9208ddeb9f262/core/src/main/java/io/kestra/core/runners/ExecutorService.java#L504

When configuring retries for a task in Kestra, it was observed that the ​​retry interval​​ only takes effect when the behavior is set to CREATE_NEW_EXECUTION. However, the interval is ​​ignored​​ when behavior is RETRY_FAILED_TASK. This inconsistency may lead to confusion in workflow design.

​​Recommendation​​:
The retry interval should function ​​independently​​ of the behavior parameter. This ensures consistent retry behavior across all execution modes and simplifies user expectations.

If this is a bug, please assign to me, thank you

**Comment by Ben8t** [comment]
Hello, can you provide a flow reproducer please?

**Comment by FourFriends** [comment]
Yes，I would like to provide a example, in Kestra Docs (https://kestra.io/docs/workflow-components/retries), here is a example, 

<img width="733" alt="Image" src="https://github.com/user-attachments/assets/76796566-9b94-425a-ae06-cf1f286f5945" />,

In practice, when the task fails, it doesn't wait for the PT0.25S interval before retrying, it retries immediately. 

<img width="1462" alt="Image" src="https://github.com/user-attachments/assets/e3fbae87-7b72-4b3f-83b9-14ebc7bd2927" />


So, recommendation​​:The retry interval should function ​​independently​​ of the behavior parameter. This ensures consistent retry behavior across all execution modes and simplifies user expectations.

**Comment by FourFriends** [comment]
@Ben8t hello, please check again, thanks.

**Comment by Ben8t** [comment]
Your example and screenshot seems legit! Up for a developer to work on a fix here now

**Comment by FourFriends** [comment]
okay, I will resolve it.

**Comment by loicmathieu** [comment]
I tried it with the following flow using a 1s delay so it's more observable:

```yaml
id: retry
namespace: company.team
description:
  This flow will be retry 4 times and will success at the 5th attempts

tasks:
- id: failed
  type: io.kestra.plugin.scripts.shell.Commands
  taskRunner:
    type: io.kestra.plugin.core.runner.Process
  commands:
  - 'if [ "{{taskrun.attemptsCount}}" -eq 4 ]; then exit 0; else exit 1; fi'
  retry:
    type: constant
    interval: PT1S
    maxAttempts: 5
    maxDuration: PT1M
    warningOnRetry: true

errors:
  - id: never_happen
    type: io.kestra.plugin.core.debug.Return
    format: Never happened {{task.id}}
```

You can clearly see that the retry happen more than 1s after the failure, for that you need to look at when it's running as the flow will be set in the `RETRYING` state as soon as it's retry, then wait for the delay.

<img width="1111" height="182" alt="Image" src="https://github.com/user-attachments/assets/e9d98b83-5b5d-4a5e-baea-62697d2ad823" />

So I think this is more a misconception, the retry delay is seen between the RETRYING and RUNNING step: it stays in RETRYING during the delay.

There didn't seems to be any bug on it. @Ben8t can you confirm my explainations?
