### ISSUE TITLE
Flow task can be search by labels

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#867]
on [Flow](https://kestra.io/plugins/core/tasks/flows/io.kestra.core.tasks.flows.Flow.html) it can be nice to search by labels, people fill the labels with a git commit or a version, and we search for flow based on all revision: 
```yaml 
id: "flow"
type: "io.kestra.core.tasks.flows.Flow"
namespace: io.kestra.tests
flowId: my-sub-flows
labels: 
  version: 0.1.1
inputs:
  file: "{{ outputs.my-task.files.resolver }}"
  store: 12
wait: false
```
If multiple flow matching the label, use latest one
