### ISSUE TITLE
Validate array display in No-Code

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#8694]
### Describe the issue

![Image](https://github.com/user-attachments/assets/cfedf8e6-508f-434f-b43a-b344d7a7e4b4)

```yaml
id: cat_291185
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀
  - id: log
    type: io.kestra.plugin.core.log.Log
    message:
      - first
      - second
      - third
```

The indended display is to have a dedicated tab for String and Array on tasks like message property on a Log task:

![Image](https://github.com/user-attachments/assets/78fd4ffc-2023-498a-9955-46bc1be6452d)

https://www.figma.com/design/ew0uXk0NRXJ2NBBJTNe2n1/01_UI?node-id=5985-62372&t=xaOt5d7SzECs0ZT1-4
