### ISSUE TITLE
ForEach is not consistent with concurrencyLimit

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#8697]
### Describe the issue

```
id: for_each
namespace: sanitychecks.plugins.core

tasks:
  - id: for_each
    type: io.kestra.plugin.core.flow.ForEach
    concurrencyLimit: 2
    values:
      - 1
      - 2
      - 3
    tasks:
      - id: return
        type: io.kestra.plugin.core.debug.Return
        format: "{{taskrun.value}}"

      - id: if
        type: io.kestra.plugin.core.flow.If
        condition: '{{ taskrun.value == "2" }}'
        then:
          - id: after_if
            type: io.kestra.plugin.core.debug.Return
            format: "After if {{ parent.taskrun.value }}"

  - id: assert
    type: io.kestra.plugin.core.execution.Assert
    conditions:
      - "{{ outputs.return['1'].value == '1' }}"
      - "{{ outputs.return['3'].value == '3' }}"
      - "{{ outputs.after_if['2'].value == 'After if 2' }}"
 ```

This flows doesn't work (sometimes it does, but it's very hard to reproduce. It's part of the sanitycheck and it was working in the past. I'm thinking of a regression...)

If you set `concurrencyLimit: 1` everything's good.
As described in the task documentation:

> If you set the concurrencyLimit property to 0, Kestra will execute all task groups concurrently for all values (zero limits!).

The `after_if` should be evaluated regardless of the concurrencyLimit property.

### Environment

- Kestra Version: develop

**Comment by ReLoutre** [comment]
Reminds me of this recent change : https://github.com/kestra-io/kestra/issues/8614, could be not related but the timing is weird.

**Comment by loicmathieu** [comment]
So, the issue is not on any consistency/concurrency issue, it's about the ìf` then branch never taken.
See

![Image](https://github.com/user-attachments/assets/6e14a807-5f41-466d-9be7-a839be4c0826)

I'm not sure taskrun.value is correctly handled in an If branch.

**Comment by Ben8t** [comment]
When setting `concurrencyLimit: 1` the if branch is handled that's why I mentioned the concurrency

**Comment by Ben8t** [comment]
```yaml
id: for_each_concurrency
namespace: sanitychecks.plugins.core

tasks:
  - id: for_each
    type: io.kestra.plugin.core.flow.ForEach
    concurrencyLimit: 1
    values:
      - 1
      - 2
      - 3
    tasks:
      - id: return
        type: io.kestra.plugin.core.debug.Return
        format: "{{taskrun.value}}"

      - id: if
        type: io.kestra.plugin.core.flow.If
        condition: '{{ taskrun.value == "2" }}'
        then:
          - id: after_if
            type: io.kestra.plugin.core.debug.Return
            format: "After if {{ parent.taskrun.value }}"

  - id: assert
    type: io.kestra.plugin.core.execution.Assert
    conditions:
      - "{{ outputs.return['1'].value == '1' }}"
      - "{{ outputs.return['3'].value == '3' }}"
      - "{{ outputs.after_if['2'].value == 'After if 2' }}"
```

![Image](https://github.com/user-attachments/assets/eb48064f-96f7-42f5-b356-4c6828bb816f)
