### ISSUE TITLE
Env variables does not replace basic auth password

### ISSUE THREAD

**Issue by gyl89** [kestra-io/kestra#8711]
### Describe the issue

Even when setting up the environment variable "KESTRA_SERVER_BASIC-AUTH_PASSWORD", the password defined in the config file does not seem to be overwritten by this env variable.

Relevant code(docker-compose):
```
kestra:
    image: kestra/kestra:latest
    pull_policy: always
    restart: always
    container_name: kestra
    profiles: [kestra]
    # Note that this setup with a root user is intended for development purpose.
    # Our base image runs without root, but the Docker Compose implementation needs root to access the Docker socket
    user: "root"
    command: server standalone --config /kestra/config/application.yml
    volumes:
      - kestra-data:/app/storage
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/kestra-wd:/tmp/kestra-wd
      - ./kestra/config/application.yml:/kestra/config/application.yml
      - ./kestra/workflows/cross_env:/kestra/workflows/cross_env
      - ${KESTRA_WORKFLOWS:-./kestra/workflows/local}:/kestra/workflows/instance
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - KESTRA_API_URL=http://api:4040
      - KESTRA_REDSHIFT_HOST=$KESTRA_REDSHIFT_HOST
      - KESTRA_REDSHIFT_DB=$KESTRA_REDSHIFT_DB
      - KESTRA_REDSHIFT_USER=$KESTRA_REDSHIFT_USER
      - KESTRA_REDSHIFT_PORT=$KESTRA_REDSHIFT_PORT
      - KESTRA_ENVIRONMENT=$KESTRA_ENVIRONMENT
      - KESTRA_SLACK_WEBHOOK_URL=$KESTRA_SLACK_WEBHOOK_URL
      - SECRET_KESTRA_USER_PASSWORD=$SECRET_KESTRA_USER_PASSWORD
      - SECRET_REDSHIFT_PASSWORD2=$SECRET_REDSHIFT_PASSWORD2
      - SECRET_KESTRA_PASSWORD=$SECRET_KESTRA_PASSWORD
      - SECRET_GITHUB_PAT=$SECRET_GITHUB_PAT
      - KESTRA_SERVER_BASIC-AUTH_PASSWORD=$KESTRA_PASSWORD
```

And the config file (obviously removed the true value of the password):
```
datasources:
  postgres:
    url: jdbc:postgresql://postgres:5432/kestra
    driverClassName: org.postgresql.Driver
    username: kestra
    password: ******
kestra:
  server:
    basicAuth:
      enabled: true
      username: "email@domain.com" 
      password: "*****"
...
```

### Environment

- Kestra Version: develop

**Comment by Ben8t** [comment]
Can you point me out where do you get that `KESTRA_SERVER_BASIC-AUTH_PASSWORD` env variables maps to the Kestra configuration?

**Comment by gyl89** [comment]
Not sure that I understand the question. I followed the doc about configuration to determine what's the right naming for the environment variable:
https://kestra.io/docs/configuration#environment

**Comment by Ben8t** [comment]
To set basic auth, the Kestra configuration should be:
```
  server:
    basicAuth:
      enabled: true
      username: "email@domain.com" 
      password: "*****"
```

This is not related to the environment variabled passed into the container under the `environment` key of the docker-compose. AFAIK, these two don't map.

I'm closing the issue as it's two concept not related. Do not hesitate to add comments if I miss understand your issue.
