### ISSUE TITLE
plugin defaults on runnable tasks environment variables are rendered in the executor instead of worker

### ISSUE THREAD

**Issue by danlsgiga** [kestra-io/kestra#8719]
### Describe the issue

Hey folks, I've been running the kestra `standalone` setup on ECS for some time already successfully.

This week we decided to step up our game due to increased adoption of the platform and deploy Kestra in the `microservice` deployment mode.

For that we split `executor`, `webserver`, `scheduler` and `worker` to run on their own ECS task and service.

Once we did that, our tasks that authenticate to AWS using provided environment variables on each ECS task started to fail to authenticate.

Upon some investigation we discovered the issue is that we have the following plugin defaults block in our configuration being rendered and captured by the `executor` and sent to the `worker` for execution.

The problem is these environment variables vary for each ECS Task, and the `executor` values will never work on the `worker` runtime environment.

I was able to validate this by exporting the output of the `env` bash command and check where it is coming from compared to the output of the flow execution

![Image](https://github.com/user-attachments/assets/20ab3cac-f90e-4968-907d-459caf1f1e1c)

![Image](https://github.com/user-attachments/assets/d911067d-8eb6-4625-8c69-9249b79ea340)

This is my configuration block that injects these environment variables:

```
  plugins:
    defaults:
      - type: io.kestra.plugin.scripts
        forced: true
        values:
          env:
            AWS_CONTAINER_CREDENTIALS_RELATIVE_URI: [[ envOrDefault "AWS_CONTAINER_CREDENTIALS_RELATIVE_URI" "" ]]
            ECS_CONTAINER_METADATA_URI: [[ envOrDefault "ECS_CONTAINER_METADATA_URI" "" ]]
            ECS_CONTAINER_METADATA_URI_V4: [[ envOrDefault "ECS_CONTAINER_METADATA_URI_V4" "" ]]
            AWS_EXECUTION_ENV: [[ envOrDefault "AWS_EXECUTION_ENV" "" ]]
            AWS_DEFAULT_REGION: [[ envOrDefault "AWS_DEFAULT_REGION" "" ]]
          taskRunner:
            type: io.kestra.plugin.scripts.runner.docker.Docker
            extraHosts:
              - "host.docker.internal:host-gateway"
      - type: io.kestra.plugin.aws
        forced: true
        values:
          env:
            AWS_CONTAINER_CREDENTIALS_RELATIVE_URI: [[ envOrDefault "AWS_CONTAINER_CREDENTIALS_RELATIVE_URI" "" ]]
            ECS_CONTAINER_METADATA_URI: [[ envOrDefault "ECS_CONTAINER_METADATA_URI" "" ]]
            ECS_CONTAINER_METADATA_URI_V4: [[ envOrDefault "ECS_CONTAINER_METADATA_URI_V4" "" ]]
            AWS_EXECUTION_ENV: [[ envOrDefault "AWS_EXECUTION_ENV" "" ]]
            AWS_DEFAULT_REGION: [[ envOrDefault "AWS_DEFAULT_REGION" "" ]]
          taskRunner:
            type: io.kestra.plugin.scripts.runner.docker.Docker
            extraHosts:
              - "host.docker.internal:host-gateway"
```

>[!NOTE]
> These environment variables are rendered by a Vault template running as an init script and generating the kestra.yaml file. These environment variables are injected to each task by ECS

This is the flow we are using to validate things:

```
id: aws_sts_test
namespace: test

variables:
  ecr_registry: <redacted>.dkr.ecr.us-east-1.amazonaws.com

tasks:
  - id: ecr_auth
    type: io.kestra.plugin.aws.ecr.GetAuthToken
    region: "us-east-1"

  - id: wdir
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      - id: cli
        type: io.kestra.plugin.aws.cli.AwsCLI
        containerImage: "{{ vars.ecr_registry }}/ecr-public/aws-cli/aws-cli:latest"
        stsCredentialSource: ECS_CONTAINER
        region: us-east-1
        taskRunner:
          type: io.kestra.plugin.scripts.runner.docker.Docker
          credentials:
            username: AWS
            password: "{{ outputs.ecr_auth.token }}"
        commands:
          - env
          - >
            aws sts
            get-caller-identity
```

FWIW, this is the error we get from the `aws sts get-caller-identity`:

> Error when retrieving credentials from container-role: Error retrieving metadata: Received non 200 response 400 from container metadata: {"code":"InvalidIdInRequest","message":"CredentialsV2Request: Credentials not found","HTTPErrorCode":400}

By any chance, can we have runnable tasks to inject these environment variables from the `worker` node?

### Environment

- Kestra Version: v0.22.6 on ECS
