### ISSUE TITLE
Add tasks for Dagger

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#8735]
Introduce support for a Dagger Commands and Script, allowing to run a Dagger pipeline - https://docs.dagger.io/quickstart

Likely similar to [plugin-script](https://github.com/kestra-io/plugin-scripts) with:

- `io.kestra.plugin.scripts.dagger.Commands` allowing to run inline execution (see [here](https://docs.dagger.io/features/shell))

```yaml
- id: io.kestra.plugin.scripts.dagger.Commands
  commands:
    - container | from alpine | with-exec echo "Hello" | stdout # should log 'Hello' in Kestra logs
````

- `io.kestra.plugin.scripts.dagger.Script` allowing to run scripts (see [here](https://docs.dagger.io/features/shell))

```yaml
- id: io.kestra.plugin.scripts.dagger.Script
  script: |
    container |
    from alpine |
    with-exec cat /etc/os-release |
    stdout
```

There's no official Java SDK, but a [community one](https://github.com/dagger/dagger/tree/main/sdk/java) is developed. A CLI is availble https://docs.dagger.io/api/cli
