### ISSUE TITLE
Go Plugin Bugs

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#8737]
### Describe the issue

The new go plugin (https://github.com/kestra-io/kestra/issues/7373) is looking great! There's a few things missing to make the experience match up to the other script tasks:

- [x] Process Task Runner doesn't seem to work. Seems to rely on a Docker container with a go image in order to run go. Process returns `/bin/sh: 2: go: not found`. I am running Kestra inside of Docker.
- [x] Autocomplete only shows the Process Task Runner as an option. No sign of Docker? Manually typing it does work.
  - ![Image](https://github.com/user-attachments/assets/9bf639f9-61a4-4697-9aa2-2e857350699d)

Pebble Expressions with Go:

Separately, I've been playing with expressions with the `Script` task but I am struggling to get it to work for all input types. This example works: 

This works:
```yaml
id: golang
namespace: company.team

inputs:
  - id: text
    type: STRING
    defaults: hello world

  - id: a_number
    type: INT
    defaults: 8

tasks:
  - id: go
    type: io.kestra.plugin.scripts.go.Script
    script: |
      package main

      import (
          "fmt"
          "strconv"
      )

      func main() {
          text := "{{ inputs.text }}"
          fmt.Println(text)
          number := {{ inputs.a_number }} + 8
          fmt.Printf(strconv.Itoa(number))
      }
```

However I haven't figured out how to get it to work with `ARRAY` type like the python example does. Even if I try to wrap it as a string, it still doesn't work. I am not a pro at Go so might be doing something wrong. Suspect it's because the array contains quotes.

```yaml
id: golang
namespace: company.team

inputs:
  - id: columns_to_keep
    type: ARRAY
    itemType: STRING
    defaults:
      - brand
      - price

tasks:
  - id: python
    type: io.kestra.plugin.scripts.python.Script
    script: |

      array = {{ inputs.columns_to_keep }}
      print(array)
      print(type(array)) # <class 'list'>

  - id: go
    type: io.kestra.plugin.scripts.go.Script
    script: |
      package main

      import (
          "fmt"
          "strings"
      )

      func main() {
          text := "{{ inputs.columns_to_keep }}" // syntax error: unexpected name brand at end of statement
          array := {{ inputs.columns_to_keep }} // syntax error: unexpected comma; expected ]
          fmt.Printf(text)
      }
```

### Environment

- Kestra Version: develop

**Comment by wrussell1999** [comment]
Following up on the Process Task Runner:

- It also doesn't work on Powershell as it's not installed on the default docker image
- Python and Node are installed by default so do work on Process
- We may need to improve docs/education around ensuring it's installed in the docker image so process works if you want to go down that route.
- If running with the `.jar`, then it relies on what's installed on your machine.

**Comment by fdelbrayelle** [comment]
Let's maybe create distinct issues for Powershell, Python and Node! What do you think?

**Comment by fdelbrayelle** [comment]
Hi @wrussell1999 👋 

I'm having a look at all your feedback!
Regarding the autocomplete, it seems to work here locally running Kestra through Docker:

![Image](https://github.com/user-attachments/assets/3c872781-f6cf-4cc8-b739-534eba54c9f7) 

Can you retry please?

**Comment by fdelbrayelle** [comment]
Since the Process task runner is running (as root) in a Ubuntu 22.04 docker image, the `go` command is not installed unlike `pip`, this is why it works for Python but not for Go.

An option would be to add a before command like in the following flow to install the `go` command:

```yaml
id: antelope_355074
namespace: company.team

tasks:
  - id: script
    type: io.kestra.plugin.scripts.go.Script
    taskRunner:
      type: io.kestra.plugin.core.runner.Process
    allowWarning: true # cause golang redirect ALL to stderr even false positives
    script: |
        package main
        import (
            "os"
            "github.com/go-gota/gota/dataframe"
            "github.com/go-gota/gota/series"
        )
        func main() {
            names := series.New([]string{"Alice", "Bob", "Charlie"}, series.String, "Name")
            ages := series.New([]int{25, 30, 35}, series.Int, "Age")
            df := dataframe.New(names, ages)
            file, _ := os.Create("output.csv")
            df.WriteCSV(file)
            defer file.Close()
        }
    outputFiles:
      - output.csv
    beforeCommands:
      - wget -qO- https://go.dev/dl/go1.24.3.linux-amd64.tar.gz | tar -C /usr/local -xzf - && echo 'export PATH=$PATH:/usr/local/go/bin' > /etc/profile.d/golang.sh && export PATH=$PATH:/usr/local/go/bin
      - go mod init go_script
      - go get github.com/go-gota/gota/dataframe
      - go mod tidy
```
