### ISSUE TITLE
Allow referencing multiple `pluginDefaults` blocks in a single flow by the ID of that pluginDefaults block

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#8740]
### Feature description

In a workflow with many tasks of the same type (e.g. 20+), user wants to use different `pluginDefaults` configs depending on the task type—some are I/O-intensive, others are CPU-intensive.

Currently, there's no way to define multiple `pluginDefaults` blocks and reference it in a task by ID. User would like to do something like this:

```yaml
pluginDefaults:
  - ref: io-config
    type: io.kestra.plugin.scripts.python.Script
    values:
      taskRunner:
        type: io.kestra.plugin.scripts.runner.docker.Docker
        cpu:
          cpus: 1
        memory:
          memory: "512Mi"
      containerImage: io-image:latest

  - ref: cpu-config
    type: io.kestra.plugin.scripts.python.Script
    values:
      taskRunner:
        type: io.kestra.plugin.scripts.runner.docker.Docker
        cpu:
          cpus: 10
        memory:
          memory: "1024Mi"
      containerImage: cpu-image:latest
```

And then in tasks:

```yaml
pluginDefaultsRef: io-config
```

This would help avoid redefining settings per task. For those stored on a namespace level in EE this would become even more useful -- user could define many plugin defaults and reference the one they need to keep their workflows DRY.

## Next steps

- add core task property called `pluginDefaultsRef`
- add autocomplete (dropdown) on a namespace level if possible, if not then on a tenant level in EE
- it should work with both OSS (when `pluginDefaults` set in a flow or configuration has `ref`) and EE namespace-level `pluginDefaults` — `ref` being an optional property

**Comment by anna-geller** [comment]
Use cases:
- switching between environments
- applying slightly different config for one set of tasks etc

ETA of complexity: 1 week of work

**Comment by anna-geller** [comment]
@AcevedoR A quick note that we will need to make this work not only for tasks but also for triggers and task runners -- wherever we rely on plugins.

**Comment by Ben8t** [comment]
Moving this back to triage and Core squad - it isn't pluginDefaults as defined and more something to define in the core of flow/tasks.

pluginDefaults supply **fallback values for a plugin *type*** when none is provided (closest scope wins). This request is the opposite shape: an explicit, per-task selection of a named config bundle. That's a reusable **`taskBlock`** defined at Namespace/Tenant level and referenced from a flow — a different primitive worth its own design.

Worth noting it's already achievable today, so this isn't blocking — using `variables` + [`TemplatedTask`](https://kestra.io/plugins/core/templating/io.kestra.plugin.core.templating.templatedtask#examples-body):

```yaml
id: variable_profiles_dynamic_demo
namespace: company.team

inputs:
  - id: profile
    type: ENUM
    values: [io, cpu]
    defaults: io

variables:
  io:  { image: "io-image:latest",  cpus: 1, memory: "512Mb" }
  cpu: { image: "cpu-image:latest", cpus: 2, memory: "1024Mb" }

tasks:
  - id: run_with_profile
    type: io.kestra.plugin.core.templating.TemplatedTask
    spec: |
      type: io.kestra.plugin.core.log.Log
      message: "profile={{ inputs.profile }} → image={{ vars[inputs.profile].image }} cpus={{ vars[inputs.profile].cpus }} memory={{ vars[inputs.profile].memory }}"
```

Or the per-task fan-out from the issue (each task picks its profile by name):

```yaml
id: variable_profiles_python_demo
namespace: company.team

variables:
  io:  { image: "python:slim", cpus: 1, memory: "512Mb" }
  cpu: { image: "python:slim", cpus: 2, memory: "1024Mb" }
  # each task declares which profile it wants — this is the per-task "ref"
  assignments:
    - { name: extract,   profile: io }
    - { name: transform, profile: cpu }
    - { name: load,      profile: io }

tasks:
  - id: each
    type: io.kestra.plugin.core.flow.ForEach
    values: "{{ vars.assignments }}"
    tasks:
      - id: run
        type: io.kestra.plugin.core.templating.TemplatedTask
        spec: |
          type: io.kestra.plugin.scripts.python.Script
          containerImage: "{{ vars[json(taskrun.value).profile].image }}"
          taskRunner:
            type: io.kestra.plugin.scripts.runner.docker.Docker
            cpu:
              cpus: {{ vars[json(taskrun.value).profile].cpus }}
            memory:
              memory: "{{ vars[json(taskrun.value).profile].memory }}"
          script: |
            print("task={{ json(taskrun.value).name }} profile={{ json(taskrun.value).profile }} cpus={{ vars[json(taskrun.value).profile].cpus }}")
```

For Namespace/Tenant-level reuse, lift the profiles into **namespace variables**; no flow edits needed to update them.

The one thing the workaround doesn't give is editor autocomplete/validation on the templated spec - which is to me exactly the argument for a first-class `taskBlock`, and a reason to design that rather than stretch pluginDefaults to fit

_Also FYI we a(Platform Squad) are working on having FlowDefaults (https://github.com/kestra-io/kestra-ee/issues/7739) that will merge with Plugin Defaults. Also currently designing a "Policies" feature to address the BlockedPlugin subject (and going further as it can be extended to other properties, https://github.com/kestra-io/kestra-ee/issues/7110)_

**Comment by anna-geller** [comment]
Not delivered on time, @brian-mulier-p is friendly enough to help, so he will work on it and he'll ask the Platform squad for review once done

**Comment by brian-mulier-p** [comment]
Closing as it has been done in https://github.com/kestra-io/kestra/pull/16995 and pluginDefaults are getting removed after 2.0.

**Comment by Pradumnasaraf** [comment]
Working as expected on 1.3.x. QA done ✅

```yaml
id: multiple_plugin_defaults_by_ref
namespace: qa.plugindefaults
pluginDefaults:
  - ref: quiet-logs
    type: io.kestra.plugin.core.log.Log
    values:
      level: ERROR
  - ref: loud-logs
    type: io.kestra.plugin.core.log.Log
    values:
      level: TRACE
tasks:
  - id: uses_quiet
    type: io.kestra.plugin.core.log.Log
    pluginDefaultsRef: quiet-logs
    message: this one should be ERROR level
  - id: uses_loud
    type: io.kestra.plugin.core.log.Log
    pluginDefaultsRef: loud-logs
    message: this one should be TRACE level
  - id: uses_none
    type: io.kestra.plugin.core.log.Log
    message: this one has no ref
```

<img width="1463" height="1080" alt="Image" src="https://github.com/user-attachments/assets/853a7b46-f9ca-4b01-836d-6b7b3be61ee7" />
