### ISSUE TITLE
Special Characters Encoding Issue - SlackIncomingWebhook

### ISSUE THREAD

**Issue by LRaverdy** [kestra-io/kestra#8749]
The SlackIncomingWebhook plugin doesn't properly handle special characters (emojis, Unicode) in the payload. Characters like é, è, or → are not displayed correctly in Slack messages.

```yaml
id: slack_message
namespace: dev

tasks:
  - id: send_slack_message
    type: io.kestra.plugin.notifications.slack.SlackIncomingWebhook
    url: "{{ secret('SLACK_WEBHOOK_BATCH_ALERT') }}"
    payload: |
      {
        "text": "My name is Andrè but with a é and this is a → symbol."
      }
          
```

Actual behavior:
Special characters are displayed as "?" or other incorrect characters

<img width="608" alt="Image" src="https://github.com/user-attachments/assets/c78315bd-1e16-4d08-b0ee-c4863c31aa2d" />

### Environment

- Kestra Version: 0.22.5
- Plugin: io.kestra.plugin.notifications.slack.SlackIncomingWebhook
