### ISSUE TITLE
[Regression on latest] Cannot deserialize value of type `java.time.Duration` from String

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#8754]
### Describe the issue

This flow works well on develop but on 0.22.6 fails to be saved with this validation error `Illegal flow yaml: Cannot deserialize value of type `java.time.Duration` from String "{{ inputs.check_frequency_interval }}": Failed to deserialize java.time.Duration: (java.time.format.DateTimeParseException) Text cannot be parsed to a Duration at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: io.kestra.core.models.flows.Flow["tasks"]->java.util.ArrayList[0]->io.kestra.plugin.core.flow.LoopUntil["checkFrequency"]->io.kestra.plugin.core.flow.LoopUntil$CheckFrequency["interval"])`: 

```yaml
id: wait_job_status
namespace: test

inputs:
  - id: check_frequency_interval
    type: DURATION
    defaults: "PT30S"
  - id: check_frequency_max_duration
    type: DURATION
    defaults: "PT1H"
    
tasks:
  - id: wait_for_job_status
    type: io.kestra.plugin.core.flow.LoopUntil
    condition: "{{randomInt(lower=0, upper=2) == 1}}"
    checkFrequency:
      interval: "{{ inputs.check_frequency_interval }}"
      maxDuration: "{{ inputs.check_frequency_max_duration }}"
    tasks:
      - id: log
        type: io.kestra.plugin.core.log.Log
        message: Looped
```

### Environment

- Kestra Version: 0.22.6
