### ISSUE TITLE
Remove node & python from docker

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#8783]
Actually, we have [python and node](https://github.com/kestra-io/kestra/blob/fe944ccc5b3400e77299261442b4b88b70f47cb9/.github/workflows/docker.yml#L54) installed. 

This bring a lot of [security issues](https://artifacthub.io/packages/helm/kestra/kestra?modal=security-report), that can be not so relevant since all scripting by default is using docker.

We can remove this package + the python kestra libs now to reduce the risk

**Comment by anna-geller** [comment]
There is a larger topic of which languages we want or don't want to support by default with the process task runner: 
- https://github.com/kestra-io/kestra/issues/8737 
- the same happens if you e.g. use PowerShell task without having PowerShell installed by default:

```yaml
id: caribou_403748
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.scripts.powershell.Script
    taskRunner: 
      type: io.kestra.plugin.core.runner.Process
    script: |
      'Hello, World!' | Write-Output
```

I think that removing Python will be too big of a BC and we should proceed carefully here, but maybe have a default response/doc on how we handle other less commonly used languages (e.g. some recipe on how to include it in the Kestra installation) - https://kestra.io/docs/best-practices/managing-pip-dependencies#using-a-custom-docker-image
