### ISSUE TITLE
Improve user flow of Execution Overview Inputs table

### ISSUE THREAD

**Issue by yuri1969** [kestra-io/kestra#8785]
### Feature description

This issue is very similar to #8784.

Daily users report that the redesigned nested design Execution-Overview-Inputs (introduced in v0.18) has made their day-to-day tasks less efficient compared to the previous plain design.

This feedback comes after a usage period lasting more than month.

---

The main complaint is the increased number of interactions required, compared to the previous design.

---

Using the new design even scalar inputs, like `STRING` or `INT`, must be clicked to show their value. This style also makes use cases like "searching an execution by input value" inefficient.

**Comment by yuri1969** [comment]
A related issue is the width/display style of the input value area. The current style forces user to copy any longer input to a text editor to read them effectively.

# Example

## Flow 

```yaml
id: tiger_404680
namespace: company.team

inputs:
  - id: lorem
    type: STRING
    defaults: >
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀
```

## Input Display

![Image](https://github.com/user-attachments/assets/d9d42dc5-ad2b-41c5-abae-b8e8c2644189)
