### ISSUE TITLE
TemplatedTask inside WorkingDirectory does not support {{ workingDir }}

### ISSUE THREAD

**Issue by danlsgiga** [kestra-io/kestra#8793]
### Describe the issue

This flow fails because the `{{ workingDir }}` pebble variable is not available within the TemplatedTask plugin.

> Unable to find `workingDir` used in the expression `type: io.kestra.plugin.scripts.python.Commands`

```
id: test
namespace: test

inputs:  
  - id: environment_variables
    type: YAML
    description: Environment variables to pass to the Python script to execute
    defaults: {}

tasks:
  - id: wdir
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      - id: python
        type: io.kestra.plugin.core.templating.TemplatedTask
        spec: |
          type: io.kestra.plugin.scripts.python.Commands
          taskRunner:
            type: io.kestra.plugin.scripts.runner.docker.Docker            
          containerImage: "python:latest"
          env:            
            {%- for env in inputs.environment_variables %}
            {{ env.key }}: "{{ env.value }}"
            {% endfor -%}
          beforeCommands:
            - . /opt/.venv/bin/activate
            - export ODBCINI="{{ workingDir }}/docker/odbc.ini"
          commands:
            - >
              python -v
```

In fact, it seems that any task level generated value like `{{ outputs.previousTask.value }}` fail to render if multiple tasks are in the TemplatedTask spec body.

### Environment

- Kestra Version: v0.22.6

**Comment by loicmathieu** [comment]
A `TemplatedTask` will render expression variables for the whole spec, but `{{workingDir}}` is a special expression variable set by the `Commands` task so it's not available at the time the `TemplatedTask` is rendering the spec.

To workaround that you can try to:
- escape the `{{` and `}}` of the workingDir expression
- defines the `{{ workingDir }}` expression as a variable and render this variable instead. As we didn't do recursive rendering, the `TemplatedTask` will render the variable to `{{workingDir}}` then the `Commands` task will render it.

**Comment by danlsgiga** [comment]
Ok, that makes sense! Thanks for the quick response!

Are you able to provide a working example on how to escape that?

I think the TemplatedTask documentation could also have something related to this to prevent people from having the same experience in the future!

**Comment by danlsgiga** [comment]
I found the `raw` pebble tag and it works now... but now I just realized another thing.

When using TemplatedTask, none of the PluginsDefault settings are applied, so this should be taken into consideration too

For example, I have this in my kestra config file:

```
plugins:
    defaults:
      - type: io.kestra.plugin.scripts.runner.docker.Docker
        host: "tcp://127.0.0.1:2375"
```

However, when rendering the TemplatedTask, it fails because Kestra tried to connect to the `unix:///var/run/docker.sock` default socket.

If I define the `host: "tcp://127.0.0.1:2375` again inside the TemplatedTask it works fine, however, it defeats the purpose of the Plugins Defaults and I'd also argue it totally bypasses any `force: true` plugin Defaults I define at the kestra config level, which can be used to evade security measures
