### ISSUE TITLE
Fix validation of String plugin properties

### ISSUE THREAD

**Issue by yuri1969** [kestra-io/kestra#8801]
### Describe the issue

Plugin property validation doesn't seem to work well with the `String` inner type.

The static flow validation prevents saving such flow with error:

> example.format: must not be blank 

# Reproducer Plugin

Checkout & build the forked/branch based on [github.com/kestra.io/plugin-template](https://github.com/yuri1969/plugin-template/tree/string-prop-validation).

The example provides a required `String` property using the `@NotBlank` Jakarta validatior.

# Reproducer Flow

```yaml
id: mosquito_795255
namespace: company.team

tasks:
  - id: "example"
    type: "io.kestra.plugin.templates.Example"
    format: "Text to be reverted" # static value is provided
```

### Environment

- Kestra Version: develop
