### ISSUE TITLE
TemplatedTask does not apply Plugin Default settings

### ISSUE THREAD

**Issue by danlsgiga** [kestra-io/kestra#8807]
### Describe the issue

When using `TemplatedTask`, none of the PluginsDefault settings defined in Kestra's config are applied

For example, I have this in my kestra config file:

```
plugins:
    defaults:
      - type: io.kestra.plugin.scripts.runner.docker.Docker
        host: "tcp://127.0.0.1:2375"
```

However, when rendering the `TemplatedTask`, it fails because Kestra tried to connect to the unix:///var/run/docker.sock default socket.

If I define the host: "tcp://127.0.0.1:2375 again inside the TemplatedTask it works fine, however, it defeats the purpose of the Plugins Defaults and I'd also argue it totally bypasses any `force: true` I define at the kestra config level, which can be used to evade security measures.

Can we have `TemplatedTask` inherit whatever is defined in Plugin Defaults?

Related to https://github.com/kestra-io/kestra/issues/8793

### Environment

- Kestra Version: v0.22.6

**Comment by Ben8t** [comment]
The [templated task is deprecated since v0.11.0](https://kestra.io/docs/migration-guide/0.11.0/templates) and we likely don't support the feature anymore. Subflow is the go to now, though we have some idea to bring some related specificities of Template Task on the back burner (ref. of [private internal issue](https://github.com/kestra-io/kestra-ee/issues/3501))

I'm closing the issue for now, please let us know if you can't work with Subflow in your specific use case (afaik, pluginDefaults will work nicely with Subflow)

**Comment by loicmathieu** [comment]
`TemplatedTask` is not deprecated, templates are deprecated.

**Comment by caxefaizan** [comment]
Confirming this is still open, with a root-cause trace and a note that it survives into 2.0.

### Root cause

Plugin defaults are injected at **flow-parse time** as a map transform, not at task-instantiation time. `PluginDefaultService.innerInjectDefault()` walks the flow as a `Map<String, Object>` and matches nested plugin maps by their `type` key.

`TemplatedTask.spec` is a **plain string** in that map, so the recursion never descends into the templated task definition. That is why global, namespace-level and flow-level defaults all fail identically here: they are three sources feeding the same single injection path.

At runtime, `TemplatedTask.run()` then builds the task itself and bypasses `PluginDefaultService` completely:

```java
Task task = OBJECT_MAPPER.readValue(taskSpec, Task.class);
...
return runnableTask.run(runContext);
```

So the inner task is constructed from the rendered YAML alone, with no defaults layer applied. This also confirms the original report's security concern: `forced: true` defaults are silently skipped for anything inside `spec`, since forced defaults are applied by that same parse-time pass.

### Still present in 2.0

`TemplatedTask.run()` at `v2.0.0-rc10` is unchanged from the version originally reported, so this is not fixed by the 2.0 upgrade. Reproduced on 2.0.0-rc10:

```yaml
variables:
  message: abc

tasks:
  - id: test1
    type: io.kestra.plugin.core.log.Log        # picks up the default, logs "abc xyz"
  - id: test2
    type: io.kestra.plugin.core.templating.TemplatedTask
    spec: |
      type: io.kestra.plugin.core.log.Log      # no default applied, NPEs
```

with a namespace-level default of:

```yaml
- type: io.kestra.plugin.core.log.Log
  forced: false
  values:
    message: "{{ vars.message }} xyz"
```

### Secondary issue: the failure mode is an NPE

`Log.message` is a bare `Object` with no `@NotNull`, so a missing value falls through to the `else` branch and dereferences null:

```
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "this.message" is null
	at io.kestra.plugin.core.log.Log.run(Log.java:106)
	at io.kestra.plugin.core.templating.TemplatedTask.run(TemplatedTask.java:76)
```

A required property missing on a templated task surfaces as a raw NPE rather than a validation error naming the property, which makes this considerably harder to diagnose than it needs to be. Worth fixing independently of the defaults behaviour, since it affects any required property omitted from a `spec`.

### `pluginDefaultsRef` is not a workaround

Worth recording, as it looks like one. `pluginDefaultsRef` (added on `Task` in 1.3.x) is resolved by the same parse-time map walk, so it cannot reach inside `spec` either. It is also absent from `Task` in `v2.0.0-rc10`, where `policyRefs` appears instead, so it is not something to build on.

### Current workaround

Set the property explicitly inside `spec`, which does work but forfeits the point of the defaults:

```yaml
  - id: test2
    type: io.kestra.plugin.core.templating.TemplatedTask
    spec: |
      type: io.kestra.plugin.core.log.Log
      message: "{{ vars.message }} xyz"
```

One caveat found while testing: hoisting the expression into a flow variable to avoid repeating it does **not** behave consistently. `variables.log_message: "{{ vars.message }} xyz"` referenced from a normal task renders to the literal `{{ vars.message }} xyz`, because variables are not recursively rendered. It only resolves correctly inside `TemplatedTask` because `spec` receives a second render pass. So that pattern silently produces different output depending on whether the task is templated.

---

Second customer report of this (EE, 1.3.34), so flagging for triage priority. @loicmathieu given the Core squad ownership and your earlier note on the thread.
