### ISSUE TITLE
All plugin docs with """ quotes in a new line are misindented in the plugin docs

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#8813]
### Describe the issue

Example that is broken:

```yaml
        @Example(
            full = true,
            title = "Simple text input and output.",
            code = """
                id: responses_text
                namespace: company.team

                inputs:
                  - id: prompt
                    type: STRING
                    defaults: Explain what is Kestra in 3 sentences

                tasks:
                  - id: explain
                    type: io.kestra.plugin.openai.Responses
                    apiKey: "{{ secret('OPENAI_API_KEY') }}"
                    model: gpt-4.1
                    input: "{{ inputs.prompt }}"

                  - id: log
                    type: io.kestra.plugin.core.log.Log
                    message: "{{ outputs.explain.outputText }}"
            """
        ),
```

![Image](https://github.com/user-attachments/assets/03ba0b29-bd26-4513-b710-818f410a20e7)

acc. to @brian-mulier-p the JSON schema seems to send the right data, so it must be a UI rendering issue

### Environment

- Kestra Version: develop
