### ISSUE TITLE
[Execution filter][Regression] clicking on labels doesn't edit the filter bar

### ISSUE THREAD

**Issue by yuri1969** [kestra-io/kestra#8843]
### Describe the issue

Selecting/deselecting labels manually by clicking at a flow/execution table row is not reflected by the filter bar.

# Reproduction

1. Checkout develop
2. Save flow

```yaml
id: shrew_473339
namespace: company.team

labels:
  foo: bar

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀
```

3. Execute the flow
4. Navigate to the Executions view
5. Click on the `foo` label located at the execution row

---

Note the URL parameters reflect changes correctly.

### Environment

- Kestra Version: develop
