### ISSUE TITLE
ForEach with unlimited concurrency executes the tasks in reverse order

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#8904]
### Describe the issue

Use the following flow:

```yaml
id: hummingbird_941521
namespace: company.team

tasks:

  - id: foreach
    type: io.kestra.plugin.core.flow.ForEach
    values: "{{ range(1, 16) }}"
    concurrencyLimit: 0
    tasks:
      - id: sleep
        type: io.kestra.plugin.core.flow.Sleep
        duration: PT1S
```

You can see that tasks are executed in reverse order (set worker threads to 2 to see it more easily)

![Image](https://github.com/user-attachments/assets/07894447-be8a-4079-861f-f14aa8121cb0)

### Environment

- Kestra Version: develop
