### ISSUE TITLE
Cannot pass var or input to dateAdd

### ISSUE THREAD

**Issue by paulgrainger85** [kestra-io/kestra#8953]
Repro:

```yaml
id: vars
namespace: demo

variables:
  timezone: "Australia/Perth"
  day: 1

tasks:
  - id: log
    type: io.kestra.plugin.core.log.Log
    message: '{{ now() | dateAdd(vars.day, "DAYS") | date("yyyy-MM-dd HH:mm:ss z", timeZone=render(vars.timezone)) }}'
```

error:
`14.503class java.lang.Integer cannot be cast to class java.lang.Long (java.lang.Integer and java.lang.Long are in module java.base of loader 'bootstrap')`

### Environment

- Kestra Version: 0.22.10, 0.23 develop
