### ISSUE TITLE
Http task, add new allowedResponseCodes

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#8973]
if you expect a response code 404, and want to failed on all response code except 200 & 404, you need actually to wrap your logic: 
```yaml 
- id: getTopic
  type: io.kestra.plugin.core.http.Request
  contentType: application/json
  method: GET
  options:
    allowFailed: true
  uri: "https://..."

- id: checkIfOk
  type: io.kestra.plugin.core.flow.If
  condition: "{{ outputs.getTopic.code == 200 }}"
  then:
    - id: topicAsOutput
      type: io.kestra.plugin.core.output.OutputValues
      values:
        topic: "{{ fromJson(outputs.getTopic.body) }}"
  else:
    - id: checkIfError
      type: io.kestra.plugin.core.flow.If
      condition: "{{ outputs.getTopic.code >= 300 and outputs.getTopic.code != 404 }}"
      then: 
        - id: fail
          type: io.kestra.plugin.core.execution.Fail
          errorMessage: "{{ outputs.getTopic.message }} (Status-Code: {{ outputs.getTopic.code }})"
```

The logic could be simply using `allowedResponseCodes`

```yaml 
- id: getTopic
  type: io.kestra.plugin.core.http.Request
  contentType: application/json
  method: GET
  options:
    allowedResponseCodes: [200, 404]
  uri: "https://..."
```
