### ISSUE TITLE
Implement inline documentation for additional plugins

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#9006]
### Feature description

Additional plugins (type of plugin provided by a plugin not inside the Kestra core) didn't work with inline documentation, when you are editing an additional plugins, the documentation keep displaying the documentation of the enclosing type.

You can use this flow that uses the Langchain4J plugin for ex, the following flow uses an additional plugin (Provider)

```yaml
id: llm-completion
namespace: company.team

inputs:
  - id: prompt
    type: STRING

tasks:
  - id: text_completion
    type: io.kestra.plugin.langchain4j.ChatCompletion
    messages:
      - type: USER
        content: "{{inputs.prompt}}"
    provider:
      type: io.kestra.plugin.langchain4j.provider.GoogleGemini
      apiKey: my_api_key
      modelName: gemini-2.0-flash
```
