### ISSUE TITLE
In progress ratio doesn't work

### ISSUE THREAD

**Issue by Ben8t** [kestra-io/kestra#9037]
### Describe the issue

https://jam.dev/c/d14bb2d6-d2cb-4caf-9031-2f67d60f50d1

flow reproducer if needed:
```yaml
id: dugong_190192
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀

  - id: sleep
    type: io.kestra.plugin.core.flow.Sleep
    duration: PT30S
```

### Environment

- Kestra Version: develop
