### ISSUE TITLE
Kestra should not remove attribute with empty string as a value

### ISSUE THREAD

**Issue by sboisgontier-lmfr** [kestra-io/kestra#909]
### Expected Behavior

When an empty string is associated to an attribute, the attribute should not be remove by Kestra.

``` 
  - id: load_data
    type: io.kestra.plugin.gcp.bigquery.LoadFromGcs
    createDisposition: CREATE_NEVER
    csvOptions:
      fieldDelimiter: "|"
      quote: ''
      skipLeadingRows: 0
    destinationTable: my_table
    format: CSV
    from:
      - "{{inputs.uri}}"
    ignoreUnknownValues: true
    writeDisposition: WRITE_TRUNCATE
```

### Actual Behaviour

When an empty string is associated to an attribute, the attribute **is removed** by Kestra.

``` 
  - id: load_data
    type: io.kestra.plugin.gcp.bigquery.LoadFromGcs
    createDisposition: CREATE_NEVER
    csvOptions:
      fieldDelimiter: "|"
      skipLeadingRows: 0
    destinationTable: my_table
    format: CSV
    from:
      - "{{inputs.uri}}"
    ignoreUnknownValues: true
    writeDisposition: WRITE_TRUNCATE
```

### Steps To Reproduce

Use the gcp step type `io.kestra.plugin.gcp.bigquery.LoadFromGcs` to load a CSV with an empty string quote option 
``` 
  - id: load_data
    type: io.kestra.plugin.gcp.bigquery.LoadFromGcs
    createDisposition: CREATE_NEVER
    csvOptions:
      fieldDelimiter: "|"
      quote: ''
      skipLeadingRows: 0
    destinationTable: my_table
    format: CSV
    from:
      - "{{inputs.uri}}"
    ignoreUnknownValues: true
    writeDisposition: WRITE_TRUNCATE
```

### Environment Information

- Kestra Version: 0.5.2
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

### Example flow

``` 
  - id: load_data
    type: io.kestra.plugin.gcp.bigquery.LoadFromGcs
    createDisposition: CREATE_NEVER
    csvOptions:
      fieldDelimiter: "|"
      quote: ''
      skipLeadingRows: 0
    destinationTable: my_table
    format: CSV
    from:
      - "{{inputs.uri}}"
    ignoreUnknownValues: true
    writeDisposition: WRITE_TRUNCATE
```
