### ISSUE TITLE
[nocode] FILE input has a Defaults optional property but FILE type do not support it

### ISSUE THREAD

**Issue by ReLoutre** [kestra-io/kestra#9222]
TBD if we can support local files soon:

```yaml
inputs:
  - id: myfile
    type: FILE
    defaults: file:///mydir/myfile.csv
```

Until then, we should hide the `defaults` property as it raises a validation error if set: **"myfile: no `defaults` can be set for inputs of type 'FILE'"**

![Image](https://github.com/user-attachments/assets/f0077745-ff1e-4c8b-8e14-96df60393289)

**Comment by anna-geller** [comment]
we now support defaults via local files and soon also nsfile so no longer an issue as defaults is now a valid field

```yaml
inputs:
  - id: myfile
    type: FILE
    defaults: file:///mydir/myfile.csv
```
