### ISSUE TITLE
Misclassified properties - io.kestra.plugin.core.debug.Return

### ISSUE THREAD

**Issue by ReLoutre** [kestra-io/kestra#9225]
### Describe the issue

![Image](https://github.com/user-attachments/assets/a9d8cd93-2d4a-40af-af84-61518f0b0ca2)
`Format` should be required and not hidden behind the optional properties.

### Environment

- Kestra Version: 

![Image](https://github.com/user-attachments/assets/15b3d15d-bade-4daa-a926-505de9dbf842)

**Comment by loicmathieu** [comment]
This property is not mandatory in code.
If we set it as mandatory, this will be a breaking change.

**Comment by Ben8t** [comment]
> This property is not mandatory in code.

What do you mean by "in code"?
Indeed we can save a flow like this:
```yaml
id: lyrebird_681293
namespace: dev.ben

tasks:
  - id: return
    type: io.kestra.plugin.core.debug.Return
```
The execution is an empty return (what's the point).

Making the `format` required seems best to make sense of such task no?
