### ISSUE TITLE
In App Plugin Docs keep showing task runner docs when main task property underneath is selected

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#9229]
### Describe the issue

As you can see, the Docker Task Runner docs come up when you select any of the python properties below the `taskRunner` section. If the `taskRunner` section is moved to the bottom or removed, this goes away and instead displays `python` docs as expected.

```yaml
id: python_dependencies
namespace: company.team

tasks:
  - id: python
    type: io.kestra.plugin.scripts.python.Script
    containerImage: python:3.13-slim
    dependencies:
      - pandas
      - kestra
    script: |
      from kestra import Kestra
      import pandas as pd
      data = {
        'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25, 30, 35]
      }
      df = pd.DataFrame(data)
      print(df)
      print("Average age:", df['Age'].mean())
      Kestra.outputs({"average_age": df['Age'].mean()})
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
```

https://github.com/user-attachments/assets/d8970059-17ed-4ff9-b15c-2b5543d0bb8d

### Environment

- Kestra Version: `develop` EE

**Comment by anna-geller** [comment]
to reproduce, put taskRunner early on:

```yaml
id: python_dependencies
namespace: company.team

tasks:
  - id: python
    type: io.kestra.plugin.scripts.python.Script
    containerImage: python:3.13-slim
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker    
    dependencies:
      - pandas
      - kestra
    script: |
      from kestra import Kestra
      import pandas as pd
      data = {
        'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25, 30, 35]
      }
      df = pd.DataFrame(data)
      print(df)
      print("Average age:", df['Age'].mean())
      Kestra.outputs({"average_age": df['Age'].mean()})
```
