### ISSUE TITLE
[UI] Trigger detail show an **Open** link instead of the database URL

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#9231]
### Describe the issue

Go to the **Administration -> Triggers** page
Hover on the icon of a Postgres trigger to see it's detail.

![Image](https://github.com/user-attachments/assets/4dc3adab-4c6f-412a-8084-8e4f4b13bf66)

It display an **Open** link instead of the database URL, there is no point of clicking this link as it's not HTTP...

Example flow to see it in action:
```yaml
id: jdbc-trigger
namespace: company.team
disabled: true

triggers:
  - id: jdbc
    type: io.kestra.plugin.jdbc.postgresql.Trigger
    url: jdbc:postgresql://localhost:5432/kestra_unit
    username: kestra
    password: k3str4
    sql: "SELECT * FROM logs LIMIT 1"
    fetchType: FETCH

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀
``` 

### Environment

- Kestra Version: develop
