### ISSUE TITLE
[UI][Fiters] Fow triggers list show a red unusable filter

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#9234]
### Describe the issue

Example with the flow YAML:
```yaml
id: jdbc-trigger
namespace: company.team
disabled: true

triggers:
  - id: jdbc
    type: io.kestra.plugin.jdbc.postgresql.Trigger
    url: jdbc:postgresql://localhost:5432/kestra_unit
    username: kestra
    password: k3str4
    sql: "SELECT * FROM logs LIMIT 1"
    fetchType: FETCH

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀
```

Go to the Flow page.
Click on the **Triggers page**

You will see a filter in red that didn't work for triggers:

![Image](https://github.com/user-attachments/assets/6ae50b34-3833-490e-a34a-8b349650a497)

### Environment

- Kestra Version: develop
