### ISSUE TITLE
Pause Task - Timeout fail the flow even after sucessfully resuming/terminating it before

### ISSUE THREAD

**Issue by ReLoutre** [kestra-io/kestra#9319]
### Describe the issue

https://jam.dev/c/c1e7dcca-840d-4a28-aba7-e9e8443f8d37
``` yaml
id: cheetah_821109
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.core.flow.Pause
    timeout: PT1M
```
Steps :
- Exec the flow
- Resume it before one min
- See its state changing to SUCCESS
- Wait until 1 min is reached
- Refresh and see that the duration of the exec has reached the timout limit and is now stated as FAILED

### Environment

- Kestra Version: 0.22.3
