### ISSUE TITLE
[Autocomplete] Some Pebble expressions (flow inputs and outputFiles on Script tasks) are not correctly autocompleted in No Code 

### ISSUE THREAD

**Issue by ReLoutre** [kestra-io/kestra#9321]
### Describe the issue

https://jam.dev/c/25cb79f5-a5be-411b-89b2-14662125a8ef

### Environment

- Kestra Version: 

![Image](https://github.com/user-attachments/assets/fc67cb78-3fbc-4bf3-8b12-8a74dc949121)

**Comment by anna-geller** [comment]
@elevatebart are you able to address it yourself or should our autocomplete expert @brian-mulier-p take it? 

I can confirm that it's still an issue

![Image](https://github.com/user-attachments/assets/f8de0536-99c3-45e1-a47b-563146d99f43)

**Comment by anna-geller** [comment]
from Will reporting the same in a separate issue:

> My input expression didn't autocomplete for my input. It did work in the flow editor. Would be good to have it work in no code too. Blocker for video: https://www.notion.so/kestra-io/Can-I-build-a-workflow-with-no-code-20136907f7b580eea527cf4541abc485?source=copy_link

![Image](https://github.com/user-attachments/assets/00c9a8ff-b940-4413-8d08-05d4bc3132f5)

Another example - `inputFiles` for Script tasks:

![Image](https://github.com/user-attachments/assets/0239582d-2c25-4bfd-ae3f-92032d135915)

**Comment by wrussell1999** [comment]
This doesn't seem to work fully for `outputs`. It will autocomplete the word `outputs` but none of the task IDs in the next bit.

```yaml
id: hello-world
namespace: tutorial
description: Hello World

inputs:
  - id: user
    type: STRING
    defaults: Rick Astley

tasks:
  - id: first_task
    type: io.kestra.plugin.core.debug.Return
    format: thrilled

  - id: second_task
    type: io.kestra.plugin.scripts.shell.Commands
    commands:
      - sleep 0.42
      - echo '::{"outputs":{"returned_data":"mydata"}}::'
  - id: hello_world
    type: io.kestra.plugin.core.log.Log
    message: |
      Welcome to Kestra, {{ inputs.user }} 
      We are to have ADD OUTPUT EXPRESSION HERE You here!

triggers:
  - id: daily
    type: io.kestra.plugin.core.trigger.Schedule
    disabled: true
    cron: 0 9 * * *

```

https://github.com/user-attachments/assets/e8bff7e7-7811-4dd7-8b9b-7a315a5df5c9
