### ISSUE TITLE
stdout error levels

### ISSUE THREAD

**Issue by tmountjr** [kestra-io/kestra#9382]
### Describe the issue

I noticed today that when a containerized python app uses the `logging` module and emits a `WARNING` level log (or really any log level that actually displays; I haven't figured out yet how to get stdout to show `INFO` and `DEBUG`) they're all interpreted as `ERROR` in the Kestra console. I was curious if it was a docker thing and so I created a second task that's just a bare python script, and saw the same results. Here's my flow:

```yaml
id: loglevel_test
namespace: tmountjr.debug

tasks:
  - id: run_loglevel
    type: io.kestra.plugin.docker.Run
    containerImage: tmountjr/loglevel:latest
    pullPolicy: ALWAYS
  - id: python_direct
    type: io.kestra.plugin.scripts.python.Script
    script: |
      import logging
      logger = logging.Logger("main")
      logger.critical("critical")
      logger.error("error")
      logger.warn("warning (old style)")
      logger.warning("warning (new style)")
      logger.info("info")
      logger.debug("debug")
```

I've attached the results of both of these tasks:

![Image](https://github.com/user-attachments/assets/fe551771-8500-4036-a408-b78f49ddfcf9)

Is this intentional, displaying everything as an `ERROR`? If so I guess it's more a QoL issue than a bug. 😄 It is a little frustrating that my script - which did exit normally, both as a container and as a script - would still show as a warning rather than a successful ending.

### Environment

- Kestra Version: develop

**Comment by yuri1969** [comment]
AFAIK [since v0.21](https://kestra.io/docs/migration-guide/0.21.0/stderr-log-level) printing to `stderr` has resulted in log lines marked as ERROR.

As for the bare script, the [custom Kestra logger implementation](https://pypi.org/project/kestra/) provides ability to emit different log levels - e.g. as shown by the [plugin's example](https://kestra.io/plugins/tasks/io.kestra.plugin.scripts.python.script#examples-body).

**Comment by Ben8t** [comment]
```yaml
id: loglevel_test
namespace: tmountjr.debug

tasks:
  - id: run_loglevel
    type: io.kestra.plugin.docker.Run
    containerImage: tmountjr/loglevel:latest
    pullPolicy: ALWAYS
  - id: python_direct
    type: io.kestra.plugin.scripts.python.Script
    script: |
      import logging
      logger = logging.Logger("main")
      logger.critical("critical")
      logger.error("error")
      logger.warn("warning (old style)")
      logger.warning("warning (new style)")
      logger.info("info")
      logger.debug("debug")
````

I'm not able to run first tak in your reproducer: got `exec /usr/local/bin/python3: exec format error`

However, in 0.23 (or develop now) the task is SUCCESS as expected

![Image](https://github.com/user-attachments/assets/1fcf8a1b-be47-4902-a0b9-c65b522c8b5a)
