### ISSUE TITLE
ForEachItem Namespace/FlowId properties as variable

### ISSUE THREAD

**Issue by thomas-depierre** [kestra-io/kestra#9405]
### Feature description

It would be interesting if for the ForEach Item task the "namespace" and "flowId" properties could depend on the current item in the same way as the inputs (with the particularity that the batch rows are at 1). In this way, the flow to be executed can directly depend on the input data, not on a single type of flow

```
- id: loop
  type: io.kestra.plugin.core.flow.ForEachItem
  items: "{{ outputs.ion_to_json.uri }}"
  batch:
    rows: 1
  namespace: "{{ ( read( taskrun.items ) ) | jq('.namespace') | first }}"
  flowId: "{{ ( read( taskrun.items ) ) | jq('.flowId') | first }}"
  inputs:
    input1: "{{ ( read( taskrun.items ) ) | jq('.input1') | first }}"
    input2: "{{ ( read( taskrun.items ) ) | jq('.input2') | first }}"
    execution_parent_id: "{{ execution.id }}"
```
