### ISSUE TITLE
Downstream task doesn't run if Pause task fails while having allowFailure set to true

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#9416]
Repro:

```yaml
id: repro1
namespace: company.team

tasks:
  - id: pause
    type: io.kestra.plugin.core.flow.Pause
    allowFailure: true
    timeout: "PT1S"
    onResume:
      - id: a
        type: INT
      - id: b
        type: STRING

  - id: after_pause
    runIf: "{{ tasks.pause.state == 'FAILED' }}"
    type: io.kestra.plugin.core.log.Log
    message: "Error {{ execution.id }}"
```
The after_pause task is not executed.

The same with no `runIf` condition:

```yaml
id: repro2
namespace: company.team

tasks:
  - id: pause
    type: io.kestra.plugin.core.flow.Pause
    allowFailure: true
    timeout: "PT1S"
    onResume:
      - id: a
        type: INT
      - id: b
        type: STRING

  - id: after_pause
    type: io.kestra.plugin.core.log.Log
    message: "Error {{ execution.id }}"
```

The `Pause.errors` doesn't seem to work as expected on `Pause` too:

```yaml
id: raven_641599
namespace: company.team

tasks:
  - id: pause
    type: io.kestra.plugin.core.flow.Pause
    allowFailure: true
    timeout: "PT1S"
    onResume:
      - id: a
        type: INT
      - id: b
        type: STRING
    errors:
      - id: run_after_failure
        type: io.kestra.plugin.core.log.Log
        message: running after failure
``` 

Using on a flow level works though:

```yaml
id: repro3
namespace: company.team

tasks:
  - id: pause
    type: io.kestra.plugin.core.flow.Pause
    allowFailure: true
    timeout: "PT1S"
    onResume:
      - id: a
        type: INT
      - id: b
        type: STRING

errors:
  - id: run_after_failure
    type: io.kestra.plugin.core.log.Log
    message: running after failure
```

and:

```yaml
id: repro4
namespace: company.team

tasks:
  - id: pause
    type: io.kestra.plugin.core.flow.Pause
    allowFailure: true
    timeout: "PT1S"
    onResume:
      - id: a
        type: INT
      - id: b
        type: STRING

afterExecution:
  - id: run_after_failure
    runIf: "{{ tasks.pause.state == 'FAILED' }}"
    type: io.kestra.plugin.core.log.Log
    message: running after failure
```
