### ISSUE TITLE
Error: duplicate ix_service_id

### ISSUE THREAD

**Issue by PintjesB** [kestra-io/kestra#9420]
### Describe the issue

Looks like something went wrong after a minor Postgres update.
```
kestra-server  | 2025-06-09T20:47:05.441659508Z 20:47:05.496 WARN  service-liveness-coordinator-task s.AbstractServiceLivenessCoordinator Detected non-responding service [id=21TJDnROH2WopDPizQLLIJ, type=INDEXER, hostname=fc8bfeee466f] after timeout (3911719ms).
kestra-server  | 2025-06-09T20:47:05.471580562Z 20:47:05.189 ERROR service-liveness-coordinator-task i.k.c.s.AbstractServiceLivenessTask Unexpected error while executing 'service-liveness-coordinator-task'. Error: SQL [insert into service_instance ("key", "value") values (?, cast(? as jsonb)) on conflict ("key") do update set "value" = cast(? as jsonb)]; ERROR: duplicate key value violates unique constraint "ix_service_id"
kestra-server  | 2025-06-09T20:47:05.471635876Z   Detail: Key (service_id)=(6XEvkESFeVPDPfSGQHrOVH) already exists.
kestra-server  | 2025-06-09T20:47:05.471642721Z org.jooq.exception.IntegrityConstraintViolationException: SQL [insert into service_instance ("key", "value") values (?, cast(? as jsonb)) on conflict ("key") do update set "value" = cast(? as jsonb)]; ERROR: duplicate key value violates unique constraint "ix_service_id"
kestra-server  | 2025-06-09T20:47:05.471649211Z   Detail: Key (service_id)=(6XEvkESFeVPDPfSGQHrOVH) already exists.
kestra-server  | 2025-06-09T20:47:05.471654200Z 	at org.jooq_3.20.2.POSTGRES.debug(Unknown Source)
kestra-server  | 2025-06-09T20:47:05.471659187Z 	at org.jooq.impl.Tools.translate(Tools.java:3650)
kestra-server  | 2025-06-09T20:47:05.471664117Z 	at org.jooq.impl.Tools.translate(Tools.java:3640)
kestra-server  | 2025-06-09T20:47:05.471669063Z 	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:847)
kestra-server  | 2025-06-09T20:47:05.471674055Z 	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:363)
kestra-server  | 2025-06-09T20:47:05.471679157Z 	at org.jooq.impl.AbstractDelegatingQuery.execute(AbstractDelegatingQuery.java:115)
kestra-server  | 2025-06-09T20:47:05.471684082Z 	at io.kestra.repository.postgres.PostgresRepository.persist(PostgresRepository.java:76)
kestra-server  | 2025-06-09T20:47:05.471689119Z 	at io.kestra.jdbc.AbstractJdbcRepository.lambda$persist$0(AbstractJdbcRepository.java:84)
kestra-server  | 2025-06-09T20:47:05.471694122Z 	at org.jooq.impl.DefaultDSLContext.lambda$transaction$5(DefaultDSLContext.java:594)
kestra-server  | 2025-06-09T20:47:05.471699111Z 	at org.jooq.impl.DefaultDSLContext.lambda$transactionResult0$3(DefaultDSLContext.java:532)
kestra-server  | 2025-06-09T20:47:05.471703959Z 	at org.jooq.impl.Tools$3$1.block(Tools.java:6298)
kestra-server  | 2025-06-09T20:47:05.471708639Z 	at java.base/java.util.concurrent.ForkJoinPool.unmanagedBlock(Unknown Source)
kestra-server  | 2025-06-09T20:47:05.471735331Z 	at java.base/java.util.concurrent.ForkJoinPool.managedBlock(Unknown Source)
kestra-server  | 2025-06-09T20:47:05.471741350Z 	at org.jooq.impl.Tools$3.get(Tools.java:6295)
kestra-server  | 2025-06-09T20:47:05.471746265Z 	at org.jooq.impl.DefaultDSLContext.transactionResult0(DefaultDSLContext.java:580)
kestra-server  | 2025-06-09T20:47:05.471751178Z 	at org.jooq.impl.DefaultDSLContext.transactionResult(DefaultDSLContext.java:503)
kestra-server  | 2025-06-09T20:47:05.471757804Z 	at org.jooq.impl.DefaultDSLContext.transaction(DefaultDSLContext.java:593)
kestra-server  | 2025-06-09T20:47:05.471763058Z 	at io.kestra.jdbc.JooqDSLContextWrapper.lambda$transaction$1(JooqDSLContextWrapper.java:58)
kestra-server  | 2025-06-09T20:47:05.471768010Z 	at dev.failsafe.Functions.lambda$toCtxSupplier$11(Functions.java:243)
kestra-server  | 2025-06-09T20:47:05.471772893Z 	at dev.failsafe.Functions.lambda$get$0(Functions.java:46)
kestra-server  | 2025-06-09T20:47:05.471777618Z 	at dev.failsafe.internal.RetryPolicyExecutor.lambda$apply$0(RetryPolicyExecutor.java:74)
kestra-server  | 2025-06-09T20:47:05.471782635Z 	at dev.failsafe.internal.FallbackExecutor.lambda$apply$0(FallbackExecutor.java:51)
kestra-server  | 2025-06-09T20:47:05.471787547Z 	at dev.failsafe.SyncExecutionImpl.executeSync(SyncExecutionImpl.java:187)
kestra-server  | 2025-06-09T20:47:05.471792553Z 	at dev.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:376)
kestra-server  | 2025-06-09T20:47:05.471797350Z 	at dev.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:112)
kestra-server  | 2025-06-09T20:47:05.471802151Z 	at io.kestra.core.utils.RetryUtils$Instance.wrap(RetryUtils.java:144)
kestra-server  | 2025-06-09T20:47:05.471806916Z 	at io.kestra.core.utils.RetryUtils$Instance.runRetryIf(RetryUtils.java:103)
kestra-server  | 2025-06-09T20:47:05.471811642Z 	at io.kestra.jdbc.JooqDSLContextWrapper.transaction(JooqDSLContextWrapper.java:55)
kestra-server  | 2025-06-09T20:47:05.471816450Z 	at io.kestra.jdbc.AbstractJdbcRepository.persist(AbstractJdbcRepository.java:83)
kestra-server  | 2025-06-09T20:47:05.471821303Z 	at io.kestra.jdbc.repository.AbstractJdbcServiceInstanceRepository.save(AbstractJdbcServiceInstanceRepository.java:214)
kestra-server  | 2025-06-09T20:47:05.471826314Z 	at io.kestra.jdbc.repository.AbstractJdbcServiceInstanceRepository.update(AbstractJdbcServiceInstanceRepository.java:224)
kestra-server  | 2025-06-09T20:47:05.471831880Z 	at io.kestra.jdbc.repository.AbstractJdbcServiceInstanceRepository.mayUpdateStatusById(AbstractJdbcServiceInstanceRepository.java:321)
kestra-server  | 2025-06-09T20:47:05.471837180Z 	at io.kestra.jdbc.repository.AbstractJdbcServiceInstanceRepository.mayTransitServiceTo(AbstractJdbcServiceInstanceRepository.java:283)
kestra-server  | 2025-06-09T20:47:05.471842176Z 	at io.kestra.jdbc.runner.JdbcServiceLivenessCoordinator.lambda$handleAllNonRespondingServices$5(JdbcServiceLivenessCoordinator.java:124)
kestra-server  | 2025-06-09T20:47:05.471847133Z 	at java.base/java.lang.Iterable.forEach(Unknown Source)
kestra-server  | 2025-06-09T20:47:05.471851768Z 	at io.kestra.jdbc.runner.JdbcServiceLivenessCoordinator.lambda$handleAllNonRespondingServices$8(JdbcServiceLivenessCoordinator.java:124)
kestra-server  | 2025-06-09T20:47:05.471856939Z 	at org.jooq.impl.DefaultDSLContext.lambda$transaction$5(DefaultDSLContext.java:594)
kestra-server  | 2025-06-09T20:47:05.471868496Z 	at org.jooq.impl.DefaultDSLContext.lambda$transactionResult0$3(DefaultDSLContext.java:532)
kestra-server  | 2025-06-09T20:47:05.471874273Z 	at org.jooq.impl.Tools$3$1.block(Tools.java:6298)
kestra-server  | 2025-06-09T20:47:05.471879728Z 	at java.base/java.util.concurrent.ForkJoinPool.unmanagedBlock(Unknown Source)
kestra-server  | 2025-06-09T20:47:05.471884917Z 	at java.base/java.util.concurrent.ForkJoinPool.managedBlock(Unknown Source)
kestra-server  | 2025-06-09T20:47:05.471889747Z 	at org.jooq.impl.Tools$3.get(Tools.java:6295)
kestra-server  | 2025-06-09T20:47:05.471894499Z 	at org.jooq.impl.DefaultDSLContext.transactionResult0(DefaultDSLContext.java:580)
kestra-server  | 2025-06-09T20:47:05.471899377Z 	at org.jooq.impl.DefaultDSLContext.transactionResult(DefaultDSLContext.java:503)
kestra-server  | 2025-06-09T20:47:05.471904279Z 	at org.jooq.impl.DefaultDSLContext.transaction(DefaultDSLContext.java:593)
kestra-server  | 2025-06-09T20:47:05.471909200Z 	at io.kestra.jdbc.JooqDSLContextWrapper.lambda$transaction$1(JooqDSLContextWrapper.java:58)
kestra-server  | 2025-06-09T20:47:05.471914190Z 	at dev.failsafe.Functions.lambda$toCtxSupplier$11(Functions.java:243)
kestra-server  | 2025-06-09T20:47:05.471918957Z 	at dev.failsafe.Functions.lambda$get$0(Functions.java:46)
kestra-server  | 2025-06-09T20:47:05.471923674Z 	at dev.failsafe.internal.RetryPolicyExecutor.lambda$apply$0(RetryPolicyExecutor.java:74)
kestra-server  | 2025-06-09T20:47:05.471928423Z 	at dev.failsafe.internal.FallbackExecutor.lambda$apply$0(FallbackExecutor.java:51)
kestra-server  | 2025-06-09T20:47:05.471933150Z 	at dev.failsafe.SyncExecutionImpl.executeSync(SyncExecutionImpl.java:187)
kestra-server  | 2025-06-09T20:47:05.471937841Z 	at dev.failsafe.FailsafeExecutor.call(FailsafeExecutor.java:376)
kestra-server  | 2025-06-09T20:47:05.471942501Z 	at dev.failsafe.FailsafeExecutor.get(FailsafeExecutor.java:112)
kestra-server  | 2025-06-09T20:47:05.471947279Z 	at io.kestra.core.utils.RetryUtils$Instance.wrap(RetryUtils.java:144)
kestra-server  | 2025-06-09T20:47:05.471952106Z 	at io.kestra.core.utils.RetryUtils$Instance.runRetryIf(RetryUtils.java:103)
kestra-server  | 2025-06-09T20:47:05.471956911Z 	at io.kestra.jdbc.JooqDSLContextWrapper.transaction(JooqDSLContextWrapper.java:55)
kestra-server  | 2025-06-09T20:47:05.471961823Z 	at io.kestra.jdbc.repository.AbstractJdbcServiceInstanceRepository.transaction(AbstractJdbcServiceInstanceRepository.java:188)
kestra-server  | 2025-06-09T20:47:05.471966767Z 	at io.kestra.jdbc.runner.JdbcServiceLivenessCoordinator.handleAllNonRespondingServices(JdbcServiceLivenessCoordinator.java:116)
kestra-server  | 2025-06-09T20:47:05.471971716Z 	at io.kestra.core.server.AbstractServiceLivenessCoordinator.onSchedule(AbstractServiceLivenessCoordinator.java:75)
kestra-server  | 2025-06-09T20:47:05.471976615Z 	at io.kestra.jdbc.runner.JdbcServiceLivenessCoordinator.onSchedule(JdbcServiceLivenessCoordinator.java:60)
kestra-server  | 2025-06-09T20:47:05.471981425Z 	at io.kestra.core.server.AbstractServiceLivenessTask.run(AbstractServiceLivenessTask.java:62)
kestra-server  | 2025-06-09T20:47:05.471986230Z 	at io.kestra.core.server.AbstractServiceLivenessTask.run(AbstractServiceLivenessTask.java:49)
kestra-server  | 2025-06-09T20:47:05.471991085Z 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
kestra-server  | 2025-06-09T20:47:05.472002465Z 	at java.base/java.util.concurrent.FutureTask.runAndReset(Unknown Source)
kestra-server  | 2025-06-09T20:47:05.472008299Z 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
kestra-server  | 2025-06-09T20:47:05.472013382Z 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
kestra-server  | 2025-06-09T20:47:05.472018298Z 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
kestra-server  | 2025-06-09T20:47:05.472023153Z 	at java.base/java.lang.Thread.run(Unknown Source)
kestra-server  | 2025-06-09T20:47:05.472027877Z Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "ix_service_id"
kestra-server  | 2025-06-09T20:47:05.472032941Z   Detail: Key (service_id)=(6XEvkESFeVPDPfSGQHrOVH) already exists.
```

### Environment

- Kestra Version: v0.22.12
- Link to the Slack thread: https://kestra-io.slack.com/archives/C03FQKXRK3K/p1749502173691469
- This is my docker compose:
```
services:
  kestra-postgres:
    container_name: kestra-postgres
    restart: unless-stopped
    image: postgres:16.9
    volumes:
      - postgres_nfs:/var/lib/postgresql/data
    environment:
      TZ: Europe/Brussels
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - dockernet.home
  kestra:
    container_name: kestra-server
    restart: unless-stopped
    image: kestra/kestra:v0.22.12
    command: server standalone --worker-thread=128
    user: root
    volumes:
      - ansible_nfs:/ansible:ro
      - data_nfs:/app/storage
      - ~/.ssh:/ssh
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/kestra/:/tmp/kestra-wd
    environment:
      KESTRA_USER: ${KESTRA_USER}
      KESTRA_PASSWORD: ${KESTRA_PASSWORD}
      KESTRA_CONFIGURATION: |
        datasources:
          postgres:
            url: jdbc:postgresql://kestra-postgres:5432/kestra
            driverClassName: org.postgresql.Driver
            username: ${POSTGRES_USER}
            password: ${POSTGRES_PASSWORD}
        kestra:
          server:
            basic-auth:
              enabled: false
              username: ${KESTRA_USER}
              password: ${KESTRA_PASSWORD}
          repository:
            type: postgres
          storage:
            type: local
            local:
              base-path: "/app/storage"
          queue:
            type: postgres
          tasks:
            tmp-dir:
              path: /tmp/kestra-wd/tmp
          plugins:
            configurations:
              - type: io.kestra.plugin.scripts.runner.docker.Docker
                values:
                  volume-enabled: true
          tutorial-flows:
            enabled: false
    ports:
      - 8081:8080
      - 8082:8081
    depends_on:
      kestra-postgres:
        condition: service_healthy
    networks:
      - dockernet.home
networks:
  dockernet.home:
    external: true
volumes:
  postgres_nfs:
    driver_opts:
      type: "nfs"
      o: "addr=tower.home,tcp,suid,rw,timeo=1500,retrans=4,hard,fg,rsize=8192,wsize=8192,noatime,acregmin=0,acregmax=0,acdirmin=0,acdirmax=0,nfsvers=4.2"
      device: ":/mnt/user/docker/appdata/kestra_postgres_nfs"
  data_nfs:
    driver_opts:
      type: "nfs"
      o: "addr=tower.home,rw,tcp,timeo=1500,hard,async,noac,relatime,retrans=5,nfsvers=4.2"
      device: ":/mnt/user/docker/appdata/kestra_data_nfs"
  ansible_nfs:
    driver_opts:
      type: "nfs"
      o: "addr=tower.home,rw,tcp,timeo=1500,hard,async,noac,relatime,retrans=5,nfsvers=4.2"
      device: ":/mnt/user/docker/appdata/ansible_config"
```
