### ISSUE TITLE
io.kestra.plugin.kubernetes.PodCreate Fails with Exit Code 137 Despite Resource Limits

### ISSUE THREAD

**Issue by surya9teja** [kestra-io/kestra#9422]
### Describe the issue

Hi, 

We have deployed the kestra in EKS and it works fine but sometimes randomly I get the following error for a certain flow
`Pods terminated with status 'Failed', exitcode '137' & message 'null'`
After researching, I realized it is related to resources limit but the strange part is when i create a new execution with a same input parameters it works fine. Any retries/ restarts/ replays on the failed flow will resulted in fail again with same error. But it works fine if I start a new execution with same input parameters. I don't understand this inconsistency in the executions. 
If you need any logs or anything please let me know. 

Here is the flow that was having issues. 
```
id: image_cropper_pipeline
namespace: microform.internal

inputs:
  - id: tenant_name
    type: STRING
    displayName: "Tenant name"
    description: "The directory after micromform.production/post_processing"
    required: true
  - id: input_dir
    type: STRING
    displayName: "Input directory"
    description: "The input directory where the images are stored after micromform.production/post_processing/{tenant_name}/input"
    required: true
  - id: padding
    type: INT
    displayName: "Padding (in pixels)"
    defaults: 10
    description: "The padding to add to the images"
    required: false
  - id: dpi
    type: INT
    displayName: "DPI value"
    defaults: 300
    description: "The DPI to use for the images"
    required: false
  - id: grayscale
    type: SELECT
    displayName: "Output Grayscale Images"
    description: "Whether to save the images in grayscale"
    required: true
    defaults: "No"
    values:
      - "Yes"
      - "No"
  - id: deskew
    type: SELECT
    displayName: "Need deskew"
    description: "Whether to perform deskew on the images"
    required: true
    defaults: "No"
    values:
      - "Yes"
      - "No"
  - id: preserve_bottom
    type: SELECT
    displayName: "Preserve Bottom"
    description: "Preserve the bottom of the image without cropping"
    required: true
    defaults: "No"
    values:
      - "Yes"
      - "No"
tasks:
  - id: image_cropper_job_queue
    type: io.kestra.plugin.kubernetes.PodCreate
    namespace: dev
    metadata:
      labels:
        company: microform.internal
        task: image_cropper_pipeline
    waitRunning: PT4H
    waitUntilRunning: PT15M
    waitForLogInterval: PT1S
    resume: true
    inputFiles:
      send_to_process.py: "{{read('image_cropper/send_to_process.py')}}"
    spec:
      serviceAccount: kestra-sa
      containers:
        - name: image-cropper-job-queue
          image: 450209354956.dkr.ecr.eu-west-2.amazonaws.com/microform/internal:kestra-init-v1.2
          env:
            - name: TENANT_NAME
              value: "{{ inputs.tenant_name }}"
            - name: TASK_TYPE
              value: "post-processing"
            - name: BUCKET_NAME
              value: "microform.production"
            - name: AWS_REGION
              value: "eu-west-2"
            - name: KESTRA_API_URL
              value: "http://kestra-service.dev.svc.cluster.local:8080/api/v1/executions"
            - name: KESTRA_FLOW_ID
              value: "image_cropper_worker"
            - name: KESTRA_NAMESPACE
              value: "microform.internal"
            - name: BATCH_SIZE
              value: "200"
          command:
            - python
            - "{{workingDir}}/send_to_process.py"
            - "--input_dirs"
            - "{{inputs.input_dir}}"
            - "--dpi"
            - "{{inputs.dpi}}"
            - "--padding"
            - "{{inputs.padding}}"
            - "--grayscale"
            - "{{inputs.grayscale}}"
            - "--deskew"
            - "{{inputs.deskew}}"
            - "--preserve_bottom"
            - "{{inputs.preserve_bottom}}"
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "2Gi"
              cpu: "1"
            limits:
              memory: "2Gi"
              cpu: "1"
      nodeSelector:
        karpenter.sh/nodepool: tasks-cpu-node-pool
        resource-type: cpu
      restartPolicy: Never
```
Overview of what this flow does, It reads a list of images from the s3 and batch them into 200 and store those list in json format in s3. Then it will trigger another flow with json s3 file path as a input. Which is not a resource intense at all. Based on my observing this pipeline max usage of RAM was around 500MB.

### Environment

- Kestra Version:0.22.9 Kubernetes
- EKS Kubernetes version 1.33
- Mostly used spot instances for running the flow
