### ISSUE TITLE
Multiple version of the same plugins 

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#946]
A nice feature will be to support multiple version of the same plugins : 

```yaml 
id: "consume"
type: "io.kestra.plugin.kafka.Consume"
version: v0.1.3
```
I will allow to switch version smoothly for breaking change
