### ISSUE TITLE
WorkingDirectory are not cleaned inside the `worker_job_running` table

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#9493]
If start the flow below, you will see a row will stay on the `worker_job_running` at the end of the process, leading to be being restarted when you restart the server. 

We need to clean this rows at the end of the `WorkingDirectory` execution whatever the result is. 

```yaml
id: WorkingDirectory
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.core.flow.WorkingDirectory
    tasks:
      - id: python1
        type: io.kestra.plugin.scripts.python.Script
        script: | 
          print(1)
      - id: python2
        type: io.kestra.plugin.scripts.python.Script
        script: | 
          print(1)
```

**Comment by hebestreit** [comment]
Today we stumbled over exactly this problem that the executor re-emitted old WorkerTask and caused unexpected behavior. We are mainly using WorkingDirectory everywhere to share dynamically installed Python packages by caching the `venv` folder.

```yaml
tasks:
  - id: working_dir_execute_pipeline
    type: io.kestra.plugin.core.flow.WorkingDirectory
    disabled: false
    cache:
      patterns:
        - venv/**
      ttl: P5D
    tasks:
      - id: execute_pipeline
        type: io.kestra.plugin.scripts.python.Script
        taskRunner:
          type: io.kestra.plugin.core.runner.Process
        beforeCommands:
          - python -m venv venv
          - . venv/bin/activate
          - pip install boto3 kestra
        script: |
          import boto3
          import json
          from kestra import Kestra

          sts_client = boto3.client('sts')
          # ...
# ... additional tasks
```

I did a quick look into the  `worker_job_running` table and counted 5k rows which doesn't sound good, right? Do you think it is safe to purge the table to make sure the worker won't process all of them again before updating to [v0.23.0](https://github.com/kestra-io/kestra/releases/tag/v0.23.0)?
