### ISSUE TITLE
Can't read files containing non-ASCII chars from ​internal storage

### ISSUE THREAD

**Issue by yuri1969** [kestra-io/kestra#9550]
### Describe the issue

Using a script task reading an output generated by a previous task fails when the generated output file name contains a non-ASCII character (e.g. one of Traditional Chinese characters).

The file name gets truncated at the non-ASCII character and thus attempts to read it lead to _file not found_ errors.

This is a problem mainly when dealing with arbitrary-named files.

---

Reproduced on **MinIO** and **Local** internal storage implementations.

Note the generated file name is correct in both the Kestra Outputs view and the MinIO file browse view.

---

# Reproducer

```yaml
id: sparrow_479739
namespace: company.team

inputs:
  - id: file-name
    type: STRING
    defaults: "test-龍.txt" # FIXME: Example of a non-ASCII input
    #defaults: "test-dragon.txt" # Works

tasks:
  - id: generate-non-ascii-file
    type: io.kestra.plugin.scripts.shell.Commands
    description: Generate an output file using an externally defined name 
    outputFiles:
      - "{{ inputs['file-name'] }}"
    commands:
      -  "echo 'TEST' > '{{ inputs['file-name'] }}'"
  - id: print-non-ascii-file
    type: io.kestra.plugin.scripts.shell.Commands
    commands:
      - "cat '{{ outputs['generate-non-ascii-file']['outputFiles'][render(inputs['file-name'])] }}'"
```

# Exception

<details><summary>MinIO-based storage exception</summary>
<pre>
java.io.FileNotFoundException: kestra:///company/team/sparrow-479739/executions/53SlmBbRWuyeHgZ0sQiv74/tasks/generate-non-ascii-file/5QCi5A1MC1gACCIuIZFcNu/65GiAKSE1OBCd3FTwwR0Om-test- (File not found)
	at io.kestra.storage.minio.MinioStorage.reThrowMinioStorageException(MinioStorage.java:448)
	at io.kestra.storage.minio.MinioStorage.get(MinioStorage.java:85)
	at io.kestra.core.storages.InternalStorage.getFile(InternalStorage.java:101)
	at io.kestra.core.models.tasks.runners.ScriptService.saveOnLocalStorage(ScriptService.java:119)
	at io.kestra.core.models.tasks.runners.ScriptService.lambda$replaceInternalStorage$0(ScriptService.java:60)
	at io.kestra.core.utils.Rethrow.lambda$throwFunction$4(Rethrow.java:89)
	at java.base/java.util.regex.Matcher.replaceAll(Matcher.java:1304)
	at io.kestra.core.models.tasks.runners.ScriptService.replaceInternalStorage(ScriptService.java:59)
	at io.kestra.core.models.tasks.runners.ScriptService.lambda$replaceInternalStorage$3(ScriptService.java:105)
	at io.kestra.core.utils.Rethrow.lambda$throwFunction$4(Rethrow.java:89)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:722)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at io.kestra.core.models.tasks.runners.ScriptService.replaceInternalStorage(ScriptService.java:106)
	at io.kestra.plugin.scripts.exec.scripts.runners.CommandsWrapper.renderCommands(CommandsWrapper.java:279)
	at io.kestra.plugin.scripts.exec.scripts.runners.CommandsWrapper.run(CommandsWrapper.java:165)
	at io.kestra.plugin.scripts.shell.Commands.run(Commands.java:304)
	at io.kestra.plugin.scripts.shell.Commands.run(Commands.java:22)
	at io.kestra.core.runners.WorkerTaskCallable.doCall(WorkerTaskCallable.java:79)
	at io.kestra.core.runners.AbstractWorkerCallable.call(AbstractWorkerCallable.java:63)
	at io.kestra.core.runners.WorkerSecurityService.callInSecurityContext(WorkerSecurityService.java:10)
	at io.kestra.core.runners.Worker.lambda$callJob$19(Worker.java:854)
	at io.kestra.core.trace.NoopTracer.inCurrentContext(NoopTracer.java:15)
	at io.kestra.core.runners.Worker.callJob(Worker.java:850)
	at io.kestra.core.runners.Worker.runAttempt(Worker.java:808)
	at io.kestra.core.runners.Worker.run(Worker.java:655)
	at io.kestra.core.runners.Worker.handleTask(Worker.java:354)
	at io.kestra.core.runners.Worker.lambda$run$8(Worker.java:277)
	at io.micrometer.core.instrument.internal.TimedRunnable.run(TimedRunnable.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
</pre>
</details> 

### Environment

- Kestra Version: aea8d6e52
- `storage-minio-0.22.2`
-  `plugin-script-shell-0.22.0`

**Comment by loicmathieu** [comment]
There is no issue with Kestra per se, if you use a `Log` task instead of a `Commands` task you can see that the cat command is correctly emitted.

Moreover, you cannot cat a file from the internal storage and output files are files from the internal storage not a local file, that's part of the issue of your flow.

```yaml
id: sparrow_479739
namespace: company.team

inputs:
  - id: file-name
    type: STRING
    defaults: "test-龍.txt" # FIXME: Example of a non-ASCII input
    #defaults: "test-dragon.txt" # Works

tasks:
  - id: generate-non-ascii-file
    type: io.kestra.plugin.scripts.shell.Commands
    description: Generate an output file using an externally defined name 
    outputFiles:
      - "{{ inputs['file-name'] }}"
    commands:
      -  "echo 'TEST' > '{{ inputs['file-name'] }}'"
  - id: log
    type: io.kestra.plugin.core.log.Log
    message: "cat '{{ outputs['generate-non-ascii-file']['outputFiles'][inputs['file-name']] }}'"
  - id: print-non-ascii-file
    type: io.kestra.plugin.scripts.shell.Commands
    commands:
      - "cat '{{ outputs['generate-non-ascii-file']['outputFiles'][inputs['file-name']] }}'"
 ```
