### ISSUE TITLE
Fix editor validation for date-based properties like scheduleDate in a Subflow task

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#9553]
### Describe the issue

@Ben8t this might be a duplicate issue FYI

```yaml
id: repro
namespace: company.team

tasks:  
  - id: sleep
    type: io.kestra.plugin.core.flow.Subflow
    namespace: company.team
    flowId: child
    scheduleDate: "{{ now() | dateAdd(2, 'MINUTES') }}"
```

![Image](https://github.com/user-attachments/assets/1e396522-e779-4b52-912d-24dc5915ddc1)

### Environment

- Kestra Version: develop
