### ISSUE TITLE
Add core tasks to modify or delete/unset Execution Variables

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#9555]
### Feature description

Syntax we came up with during a meeting:

```yaml
id: variables_demo
namespace: company.team

variables:
  state: FAILED
  ansibleTicket: myticket
  nested:
    child: property
    unchanged: stay the same

tasks:  
  - id: request
    type: io.kestra.plugin.core.output.OutputValues
    values:
      ansibleTicket: new ticket value
      state: SUCCESS
  
  - id: updateVariables
    type: io.kestra.plugin.core.execution.SetVariables
    overwrite: true # true by default
    variables:
      state: "{{ outputs.request.values.state }}"
      ansibleTicket: "{{ outputs.request.values.ansibleTicket }}"
      nested:
        child: new value

  - id: deleteVariables
    type: io.kestra.plugin.core.execution.UnsetVariables
    variables:
      - state
      - ansibleTicket
      - nested.child # to remove only one from nested

  - id: confirmUpdate
    type: io.kestra.plugin.core.log.Log
    message: Hello "{{ vars }}"
```

The Variables will show on the Execution Overview page and if some tasks update them mid-run, their values will be updated (i.e. not fixed to the initial variable values).

![Image](https://github.com/user-attachments/assets/dbabdc1b-9158-4ad6-a0ee-adc3c7789093)
