### ISSUE TITLE
Flow doesn't save correctly when first saved

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#9563]
### Describe the issue

When I made a new flow, pasted a task in, and pressed save - it did not save. It instead tried to ask me to restore a flow that never existed.

It saves no problem if you save before pasting the task in.

https://github.com/user-attachments/assets/47b603ca-9d60-4748-a64d-f7c7e5916c88

Steps to reproduce:
1. Creat a new workflow that uses the default flow:
```yaml
id: squirrel_652088
namespace: company.team

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀
```

2. Paste in the following block and fix the indenting

```yaml
  - id: extract
    type: io.kestra.plugin.scripts.shell.Commands
    outputFiles:
      - "*.csv"
    taskRunner:
      type: io.kestra.plugin.core.runner.Process
    commands:
      - ls
```

3. Save the flow for the first time

### Environment

- Kestra Version: `develop` OSS

**Comment by wrussell1999** [comment]
Sometimes it's not even letting me save the default flow unedited:
https://github.com/user-attachments/assets/64578dcb-8e1f-42e5-b27c-6ea894a388b9

**Comment by munjalpatel** [comment]
I don't know if this is related, but I recently upgraded from `v0.22.13` to `v0.23.0` and now my local flow syncing stopped working. 

Meaning, when I do `docker compose up` and log in to Kestra instance, I don't see any flows. This used to work before I upgraded.

```
FROM openjdk:23-slim@sha256:7e7ee1ee0e0e4819beb1a4b04b4035f34df405410691459e05c10a859661dc35 AS stage-build

WORKDIR /

USER root

RUN apt-get update -y
RUN apt-get install git -y && \
  git clone https://github.com/simple-platform/plugin-nats.git

RUN cd plugin-nats && \
  git checkout 9d3e9f4cf0c2b6bf6638fdb73cff609f227c3037 && \
  ./gradlew :shadowJar

FROM kestra/kestra:v0.23.0-no-plugins@sha256:8eaf36878a5ceaf3f98fe7821e040c4f387a468cf261e8e5a5b477264cde34f2

RUN /app/kestra plugins install \
  io.kestra.plugin:plugin-notifications:LATEST \
  io.kestra.storage:storage-azure:LATEST

USER root

RUN mkdir -p /app/plugins

COPY --from=stage-build /plugin-nats/build/libs/plugin-nats-*.jar /app/plugins
```

```
services:
  simple-kestra:
    build: .
    image: simple.dev/kestra:dev
    container_name: simple-kestra
    restart: always
    user: root
    command: server standalone
    volumes:
      - ./flows:/flows
      - ./data/wd:/tmp/kestra-wd
      - ./data/storage:/app/storage
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - simple
    environment:
      KESTRA_SENDGRID_API_KEY: ${KESTRA_SENDGRID_API_KEY}
      KESTRA_SIMPLE_METADATA_NATS_USER: simple-kestra
      KESTRA_SIMPLE_METADATA_NATS_PASS: simple-kestra-simple-kestra
      KESTRA_SIMPLE_METADATA_NATS_URL: nats://simple-nats:4222
      KESTRA_CONFIGURATION: |
        datasources:
          postgres:
            url: jdbc:postgresql://simple-db-wus:5432/kestra
            driverClassName: org.postgresql.Driver
            username: kestra
            password: kestra
        micronaut:
          io:
            watch:
              enabled: true
              paths:
                - /flows
        kestra:
          url: http://localhost:8080/
          anonymousUsageReport:
            enabled: false
          tutorialFlows:
            enabled: false
          encryption:
            secretKey: 3+g1kYgJgJRFW8zPG/X8cEfU0jC31gH1vVh+3pKJYD8=
          environment:
            name: Development
            color: "#62748e"
          server:
            basicAuth:
              enabled: true
              username: user@domain
              password: password
          repository:
            type: postgres
          storage:
            type: local
            local:
              basePath: "/app/storage"
          queue:
            type: postgres
          tasks:
            tmpDir:
              path: /tmp/kestra-wd/tmp
    ports:
      - 8080:8080
      - 8081:8081

networks:
  simple:
    name: simple
    external: true
```

**Comment by Piyush-r-bhaskar** [comment]
@wrussell1999 can you check if still happening on develop   ? ...should be fixed with https://github.com/kestra-io/kestra/pull/9560. I am not able to reproduce.

**Comment by wrussell1999** [comment]
Still broken on 39d31f4. Broke with a completely new instance.

**Comment by wrussell1999** [comment]
Now flows don't seem to appear in the flows page at all, but I was able to execute this one.

https://github.com/user-attachments/assets/1f9c54e4-73d5-4338-a9e9-88e74145c6b5

**Comment by wrussell1999** [comment]
And original bug still present

https://github.com/user-attachments/assets/97484361-9d90-4a6a-9738-a5a441c82679

**Comment by wrussell1999** [comment]
Docker Compose used - it has local flow sync enabled like the user above. May be related:

```yaml
volumes:
  postgres-data:
    driver: local
  kestra-data:
    driver: local

services:
  postgres:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: kestra
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: k3str4
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 10

  kestra:
    image: kestra/kestra:develop
    pull_policy: always
    # Note that this setup with a root user is intended for development purpose.
    # Our base image runs without root, but the Docker Compose implementation needs root to access the Docker socket
    # To run Kestra in a rootless mode in production, see: https://kestra.io/docs/installation/podman-compose
    user: "root"
    command: server standalone
    volumes:
      - kestra-data:/app/storage
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/kestra-wd:/tmp/kestra-wd
      - /Users/wrussell/Documents/Repositories/kestra-server/example/example_flows:/local_flows
      - /Users/wrussell/Documents/Repositories/kestra-server/example/files:/files
    environment:
      KESTRA_CONFIGURATION: |
        datasources:
          postgres:
            url: jdbc:postgresql://postgres:5432/kestra
            driverClassName: org.postgresql.Driver
            username: kestra
            password: k3str4
        kestra:
          server:
            basic-auth:
              enabled: false
              username: "admin@kestra.io" # it must be a valid email address
              password: kestra
          repository:
            type: postgres
          storage:
            type: local
            local:
              base-path: "/app/storage"
          queue:
            type: postgres
          tutorial-flows:
            enabled: false 
          tasks:
            tmp-dir:
              path: /tmp/kestra-wd/tmp
          url: http://localhost:8080/
        micronaut:
          io:
            watch:
              enabled: true
              paths:
                - /local_flows

    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_started

```
