### ISSUE TITLE
[Post-Release on August 5th] Add Breaking Changes to GitHub Release Notes

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#9566]
## The Executions endpoint now requires a `filename` for `FILE`-type properties

To upload a file for an input of type FILE you should now use the part **name** for the input if, and the part **filename** attribute for the name of the file.

For example, when using cURL to start an execution for the following flow:
```yaml
id: file
namespace: company.team

inputs:
  - id: file
    type: FILE

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: "{{inputs.file}}"
```

**Before 0.24 - now deprecated**
```
curl -v "http://localhost:8080/api/v1/executions/company.team/file" \
    -H "Content-Type:multipart/form-data"    \ 
    -F "files=@/tmp/test.txt;filename=file"
```

**Since 0.24**
```
curl -v "http://localhost:8080/api/v1/executions/company.team/file" \
    -H "Content-Type:multipart/form-data" \
    -F "file=@/tmp/test.txt;filename=test.txt"
```

To read more: https://github.com/kestra-io/kestra/issues/5987

---

- [ ] https://github.com/kestra-io/kestra/pull/9565#issuecomment-2983969557
- [ ] Baisc auth is now required in OSS for increased security https://github.com/kestra-io/kestra/issues/10071
- [ ] Some EE endpoints have been streamlined in a way that might require changes https://github.com/kestra-io/kestra-ee/issues/4091 
- [ ] some API endpoints like /stats have been removed -- @Skraye can you provide details?

<details>
  <summary>Deferred till the next release </summary>

## The `defaults` property of all inputs is now dynamic

The change made in https://github.com/kestra-io/kestra/issues/9762 has implications for users who use a Pebble expression as a default value. Consider this use case:

```yaml
id: session
namespace: company.team

inputs:
  - id: sessionId
    type: STRING
    defaults: "{{ execution.id }}"   

tasks:
  - id: log
    type: io.kestra.plugin.core.log.Log
    message: "This is my session id: {{render(inputs.sessionId)}}"
```

Given that the `defaults` are now dynamically rendered, the above flow will fail in Kestra 0.24 and higher, unless you move the expression to the tasks as follows:

```yaml
id: session
namespace: company.team

inputs:
  - id: sessionId
    type: STRING
    required: false

tasks:
  - id: log
    type: io.kestra.plugin.core.log.Log
    message: "This is my session id: {{ inputs.sessionId ?? execution.id }}"
```

</details>

**Comment by NovytskyiD** [comment]
Hey. Will this code work correctly in 0.24 if I don't pass sessionId?

```
id: session
namespace: company.team

inputs:
  - id: sessionId
    type: STRING
    defaults: "{{ execution.id }}"   

tasks:
  - id: log
    type: io.kestra.plugin.core.log.Log
    message: "This is my session id: {{inputs.sessionId)}}"
```
