### ISSUE TITLE
Deactivate the "Backfill Executions" button on any Trigger page if the trigger is disabled in the source code

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#9572]
### Describe the issue

If the Schedule trigger is disabled via API call (via the Enabled toggle), the Backfill Executions button is nicely deactivated.

```yaml
id: scheduled_flow  
namespace: company.team

tasks:
  - id: label
    type: io.kestra.plugin.core.execution.Labels
    labels:
      scheduledDate: "{{trigger.date ?? execution.startDate}}"
  
  - id: external_system_export
    type: io.kestra.plugin.core.log.Log
    message: processing data for {{trigger.date ?? execution.startDate}}

triggers:  
  - id: schedule  
    type: io.kestra.plugin.core.trigger.Schedule  
    cron: "*/30 * * * *" 
```

![Image](https://github.com/user-attachments/assets/f6db2b0d-4c62-459c-b678-8fe8e7e6049a)

However, if the trigger is disabled from the source code, the Backfill Executions button is shown as active:

```yaml
id: scheduled_flow  
namespace: company.team

tasks:
... # same

triggers:  
  - id: schedule  
    type: io.kestra.plugin.core.trigger.Schedule  
    cron: "*/30 * * * *" 
    disabled: true
```

![Image](https://github.com/user-attachments/assets/7a573104-6c17-4cfb-9406-df3bb2ec84ef)

Let's validate if we can find a solution here as well. If I recall correctly, this seems not easy but maybe there's some creating solution like a new endpoint that checks the state of the trigger among both trigger-disabled-state and source code?

### Environment

- Kestra Version: develop
