### ISSUE TITLE
Save prompt comes up when navigating the documentation

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#9614]
### Describe the issue

When you have a flow with unsaved changes, such as starting to write a new task, the save alert comes up when navigating the docs. This is annoying as the example below has an invalid flow due to the new task not being completed. This means the user has to continue to dismiss the alerts while they navigate the docs and examples to finish the flow.

https://github.com/user-attachments/assets/50c9af9e-93e1-47d6-a8ff-78acb19d5e28

### Environment

- Kestra Version: develop

**Comment by starlightknown** [comment]
Hello, unable to reproduce this. Is it browser related?

**Comment by wrussell1999** [comment]
I was using Chrome on MacOS. I will try and reproduce it again on develop and latest.

**Comment by wrussell1999** [comment]
Not able to reproduce on 0.23.4

https://github.com/user-attachments/assets/040147f6-0b7c-447f-b894-fb56131f7d9e

**Comment by wrussell1999** [comment]
Reproducing on `develop` OSS

https://github.com/user-attachments/assets/c7357a49-217f-4941-9a89-6e51f0c31ea6

**Comment by Piyush-r-bhaskar** [comment]
@wrussell1999 I tried to reproduce it again on `Chrome` , `Firefox`, `Brave`..but it's not reproducible.

again , tried with `Running OSS develop PG in docker` as pointed in https://github.com/kestra-io/kestra/issues/10246 - Not reproducible at all.

with :
```
id: pony_246001
namespace: demo

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 

triggers:
  - id: flow
    type: io.kestra.plugin.core.trigger.Flow
    conditions:
      - 
```

from `Chrome`

https://github.com/user-attachments/assets/836ab537-a10c-44ee-a685-5e22c0035cc6

From `Brave`

https://github.com/user-attachments/assets/8e176c48-7954-44c2-85d2-e6719b2f681f
