### ISSUE TITLE
SLA in subflow doesn't trigger fail of parent flow

### ISSUE THREAD

**Issue by NovytskyiD** [kestra-io/kestra#9618]
### Describe the issue

I have a flow that calls a subflow, which in turn calls another subflow.
The last flow in this chain has an SLA rule. Today, it was triggered, and the last level flow was killed. However, the two parent flows don't have an SLA rule and have been in the Running state for a long time before I killed them manually. I expected that they should fail or be killed too, but not. 

![Image](https://github.com/user-attachments/assets/f016216d-efbe-4d22-a3ad-6461781baa32)

Reproducer

```
id: parentflow
namespace: test

concurrency:
  limit: 1
  

tasks:
    - id: parentflow2
      type: io.kestra.plugin.core.flow.Subflow
      namespace: test
      flowId: parentflow2
```

```
id: parentflow2
namespace: test

concurrency:
  limit: 1
  

tasks:
    - id: subflow1
      type: io.kestra.plugin.core.flow.Subflow
      namespace: test
      flowId: subflow1
```

```
id: subflow1
namespace: test

concurrency:
  limit: 1

sla:
  - id: maxDuration
    type: MAX_DURATION
    duration: PT1M
    behavior: FAIL
    labels:
      sla: miss
      reason: durationExceeded

tasks:
    - id: pythonwait
      type: io.kestra.plugin.scripts.python.Script
      script: |
        import time

        print("Sleeping for 10 minutes...")
        time.sleep(600)
        print("Done sleeping.")
```

### Environment

- Kestra Version: 0.22.2

**Comment by loicmathieu** [comment]
This can be reproduced with a more contrieved example:

Parent flow:
```yaml
id: parentflow
namespace: test

tasks:
    - id: subflow
      type: io.kestra.plugin.core.flow.Subflow
      namespace: test
      flowId: subflow
```

Subflow:
```yaml
id: subflow
namespace: test

sla:
  - id: maxDuration
    type: MAX_DURATION
    duration: PT10S
    behavior: FAIL

tasks:
    - id: sleep
      type: io.kestra.plugin.core.flow.Sleep
      duration: PT60S
```
