### ISSUE TITLE
[No-code] Array Input `default` don't work

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#9632]
### Describe the issue

No way to add `defaults` for `ARRAY` input of `itemType` `STRING`

![Image](https://github.com/user-attachments/assets/60dd9cb2-6123-4715-b037-2f883546a91d)

Produces the following YAML:
```yaml
inputs:
  - id: columns_to_keep
    type: ARRAY
    itemType: STRING
    defaults:
      - null
      - null
```

### Environment

- Kestra Version: 0.23.0 EE
