### ISSUE TITLE
[No-code] Documentation doesn't go back to flow when going to flow level properties

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#9633]
### Describe the issue

Steps to reproduce:
- Add the following workflow.
- Open the No-code and Documentation panels
- Click onto the task in no code
- Click out and go to the inputs - the docs stay on logs

It works as intended on the flow properties in the Flow code panel.

Workflow used:
```yaml
id: data-engineering-pipeline
namespace: tutorial
description: Data Engineering Pipelines
inputs:
  - id: columns_to_keep
    type: ARRAY
    itemType: STRING
    defaults:
      - hello

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀

```

![Image](https://github.com/user-attachments/assets/1c26940f-6940-463d-b3b9-8cf42a901d10)

### Environment

- Kestra Version: 0.23.0
