### ISSUE TITLE
[No-code] Radio Button Clear Selection only appears when new value added

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#9646]
### Describe the issue

Clear selection only appears when the default value is changed. Also the default value doesn't get added to the flow code when the selection is made even if it's still going to be used as it's the default. I would expect something that's explicitly selected by the user to appear.

https://github.com/user-attachments/assets/f0f33644-6da7-47b3-9223-e8fbbef80d63

### Environment

- Kestra Version: 0.23.0 EE

**Comment by pkaur91** [comment]
Hi Team ,  
I'm new to Kestra and exploring opportunities to contribute.  
This issue looks interesting and I’d love to take it up as my first contribution.  

Please assign it to me if it's still open.  
Thanks!  
— @pkaur91

**Comment by MilosPaunovic** [comment]
Hey @pkaur91,

There is already a PR opened which will solve this issue, but if you're eager to contribute, may I suggest that you check our [curated list of good first issues](https://go.kestra.io/contributing) to see if there is something you find interesting enough and think you can tackle independently. It can be further filtered by desired labels to narrow down the results (suggesting to filter by either `area/backend` or `area/frontend` ones, based on your preferences).

**Comment by MilosPaunovic** [comment]
@abhilashth I will assign you to this issue if you add a comment here (without it I am unable, due to GH security policies).

**Comment by MilosPaunovic** [comment]
Hey @wrussell1999,

Which task have you been using in the video, as I can not be able to find it for the life of me? 😢

**Comment by wrussell1999** [comment]
@MilosPaunovic ah yes, I should've included an example flow. It's the DuckDB Query task. I was using it in the Data Engineering Getting Started Blueprint: https://kestra.io/blueprints/data-engineering-pipeline

```yaml
id: data-engineering-pipeline
namespace: tutorial
description: Data Engineering Pipelines

inputs:
  - id: columns_to_keep
    type: ARRAY
    itemType: STRING
    defaults:
      - brand
      - price

tasks:
  - id: extract
    type: io.kestra.plugin.core.http.Download
    uri: https://dummyjson.com/products

  - id: transform
    type: io.kestra.plugin.scripts.python.Script
    containerImage: python:3.11-alpine
    inputFiles:
      data.json: "{{ outputs.extract.uri }}"
    outputFiles:
      - "*.json"
    script: |
      import json
      import os

      with open("data.json", "r") as file:
          data = json.load(file)

      filtered_data = [
          {column: product.get(column, "N/A") for column in {{ inputs.columns_to_keep }}}
          for product in data["products"]
      ]

      with open("products.json", "w") as file:
          json.dump(filtered_data, file, indent=4)

  - id: query
    type: io.kestra.plugin.jdbc.duckdb.Query
    inputFiles:
      products.json: "{{ outputs.transform.outputFiles['products.json'] }}"
    sql: |
      INSTALL json;
      LOAD json;
      SELECT brand, round(avg(price), 2) as avg_price
      FROM read_json_auto('{{ workingDir }}/products.json')
      GROUP BY brand
      ORDER BY avg_price DESC;
    fetchType: STORE
```
