### ISSUE TITLE
Use the new from interface to allow passing local files as defaults to FILE-type input

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#9681]
### Feature description

The idea is to specify `defaults` with a protocol:

```yaml
inputs:
  - id: local_file
    type: FILE
    defaults: file:///mydir/myfile.csv

inputs:
  - id: namespace_file
    type: FILE
    defaults: nsfile:///mydir/myfile.csv # TBD, don't know what's the prefix for NS Files
```

This will resolve issue on autocompletion + no-code we currently have https://github.com/kestra-io/kestra/issues/9222
