### ISSUE TITLE
Add a boolean property `autoSelectFirst` to SELECT and MULTISELECT inputs

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#9691]
### Feature description

Imagine you have a KV pair with a JSON array containing a single value:

![Image](https://github.com/user-attachments/assets/2e156e0e-8c02-45cf-a3e1-dc068afe0f45)

Some users would like to automatically select the first value as default:

![Image](https://github.com/user-attachments/assets/b71ca850-5309-4c7f-900d-43056eae7360)

We can enable this behavior with a simple new boolean property `autoSelectFirst` by default set to `false` to avoid a breaking change:

```yaml
id: repro
namespace: company.team

inputs:
  - id: select
    type: SELECT
    expression: "{{ kv('SELECT_VALUES') }}"
    autoSelectFirst: true
    # SELECT_VALUES is a JSON array with a single value ["first"]
    # User can avoid avoid hardcoding `defaults: first` to have the first value autoselected in the dropdown

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello {{ inputs.select }}
```

- [ ] We should apply that to both SELECT and MULTISELECT inputs
- [ ] Even for a JSON array with many values, often it's desirable to autoselect the first -- it helps especially with demo workflows or standardized workflows where values change often but the first value is the most sensible one to be used as a default

**Comment by vamsikrishna71** [comment]
For SELECT Inputs

inputs:
  - id: select
    type: SELECT
    expression: "{{ kv('SELECT_VALUES') }}"
    autoSelectFirst: true

For MULTISELECT Inputs

inputs:
  - id: multiselect
    type: MULTISELECT
    expression: "{{ kv('MULTISELECT_VALUES') }}"
    autoSelectFirst: true

Behavior: The first value in the array is automatically selected as the initial choice.

User can add/remove selections as needed.

Assume your dynamic values are:

SELECT_VALUES = ["prod", "dev", "test"]
MULTISELECT_VALUES = ["alpha", "beta", "gamma"]

Result
SELECT: "prod" is pre-selected.

MULTISELECT: ["alpha"] is pre-selected.

**Comment by MilosPaunovic** [comment]
@anna-geller Do we want to simplify this and do it only on the UI side (at least for now) and say - if the input is required - preselect first one - otherwise, no action (as if the input is not required, then the users will have to manually remove, which is basically the same step, only backwards)?

**Comment by anna-geller** [comment]
Smart suggestion @MilosPaunovic, but after reviewing it, I think **we need this new backend property**. To explain why: whenever we use SELECT without any `defaults`, this property is required and must be filled:
```yaml
id: repro2
namespace: company.team

inputs:
  - id: select
    type: SELECT
    expression: "{{ kv('SELECT_VALUES') }}"
    description: Note how this is not explicitly marked as required, yet it is required because it's a dropdown with no defaults

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello {{ inputs.select }}
```

 If we would preselect the first value automatically without `autoSelectFirst: true`, then user has no choice to keep the current behavior where no value is preselected and user must choose themselves.

![Image](https://github.com/user-attachments/assets/94f965d5-bb25-4999-b70e-349d44b9fd70)

With the explicit `autoSelectFirst: true`, the user would see here:

![Image](https://github.com/user-attachments/assets/8131ed52-b685-4411-9898-b1fc2610f86b)

TL;DR thanks to the new property, we add an explicit, declarative way to handle this without a Breaking Change 👍

**Comment by MilosPaunovic** [comment]
That now makes perfect sense!

**Comment by RedHolger** [comment]
Support for `autoSelectFirst` by updating `FlowInputOutput.resolveInputs()`. The idea would be: if no value or default is provided, and `autoSelectFirst` is true with a non-empty `values` list, then the first item can be assigned as the default.

**Comment by brian-mulier-p** [comment]
<img width="1576" height="1498" alt="Image" src="https://github.com/user-attachments/assets/2b3b44d0-6d27-43c8-9984-7734fdbed8a1" />

```
id: bear_890449
namespace: company.team
inputs:
  - id: select-radio-default
    type: SELECT
    isRadio: true
    defaults: b
    values:
      - a
      - b
      - c 
  - id: select-radio-autoselect-static
    type: SELECT
    isRadio: true
    autoSelectFirst: true
    values:
      - a
      - b
      - c 
  - id: select-radio-autoselect-dynamic
    type: SELECT
    isRadio: true
    autoSelectFirst: true
    expression: "{{http('https://dummyjson.com/products')|jq('.products[].title')}}"
  - id: select-default
    type: SELECT
    defaults: b
    values:
      - a
      - b
      - c 
  - id: select-autoselect-static
    type: SELECT
    autoSelectFirst: true
    values:
      - a
      - b
      - c 
  - id: select-autoselect-dynamic
    type: SELECT
    autoSelectFirst: true
    expression: "{{http('https://dummyjson.com/products')|jq('.products[].title')}}"
  - id: multiselect-default
    type: MULTISELECT
    defaults: ['b']
    values:
      - a
      - b
      - c 
  - id: multiselect-autoselect-static
    type: MULTISELECT
    autoSelectFirst: true
    values:
      - a
      - b
      - c 
  - id: multiselect-autoselect-dynamic
    type: MULTISELECT
    autoSelectFirst: true
    expression: "{{http('https://dummyjson.com/products')|jq('.products[].title')}}"

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: Hello World! 🚀
```
