### ISSUE TITLE
Flow schema validation issue with multiple conditions

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#970]
### Actual Behaviour

When using multiple conditions, the flow schema validator shows some warning but the flow works without issue.

![Capture d’écran du 2023-02-09 17-21-35](https://user-images.githubusercontent.com/1819009/217872637-b4b53cd9-f0da-4a65-b41c-bf1926678242.png)

### Steps To Reproduce

You can use the example multiple condition flow, it triggers the issue:

```yaml
id: trigger-multiplecondition-listener
namespace: io.kestra.tests

tasks:
  - id: onlyListener
    type: io.kestra.core.tasks.debugs.Return
    format: "let's go "

triggers:
  - id: multipleListenFlow
    type: io.kestra.core.models.triggers.types.Flow
    conditions:
      - id: multiple
        type: io.kestra.core.models.conditions.types.MultipleCondition
        window: P1D
        windowAdvance: P0D
        conditions:
          flow-a:
            type: io.kestra.core.models.conditions.types.ExecutionFlowCondition
            namespace: io.kestra.tests
            flowId: trigger-multiplecondition-flow-a
          flow-b:
            type: io.kestra.core.models.conditions.types.ExecutionFlowCondition
            namespace: io.kestra.tests
            flowId: trigger-multiplecondition-flow-b
```

### Environment Information

- Kestra Version: 0.6.1-SNAPSHOT
- Operating System (OS / Docker / Kubernetes): Linux
- Java Version (If not docker): 17
