### ISSUE TITLE
Rename retry.maxAttempt to retry.maxAttempts (with alias to avoid BC)

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#9729]
### Feature description

```yaml
    retry:
      type: constant
      maxAttempts: 3
      interval: PT1M # Retry every 1 minute
```
