### ISSUE TITLE
Allow reading local files in a read() Pebble function

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#9739]
### Describe the issue

- [x] allow reading: `{{ read(inputs.my_local_file) }}` as a follow up to https://github.com/kestra-io/kestra/pull/9727
- [x] add a configuration allowing to prohibit reading local files if needed for security-conscious users; this way, it can be enabled by default and disabled if needed

This will make this use case work:

```yaml
id: local_file_test
namespace: company.team

inputs:
  - id: local
    type: FILE
    defaults: file:///local/hello.txt

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: "{{read(inputs.local)}}"
```

### Environment

- Kestra Version: develop
