### ISSUE TITLE
Allow preview of local files on the Execution Overview page

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#9740]
### Feature description

This may be doable, but only if the file is globally allowed (not allowed for a plugin), as it would be done by the web server.

![Image](https://github.com/user-attachments/assets/eeade948-b003-4397-aff0-964faad5fbb3)

```yaml
id: local_file_test
namespace: company.team

inputs:
  - id: local
    type: FILE
    defaults: file:///local/hello.txt

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: "{{read(inputs.local)}}"
```

**Comment by loicmathieu** [comment]
@anna-geller can you confim if preview should be enabled or not by default?

**Comment by anna-geller** [comment]
sure, it's beneficial to enable it by default, agree? (to have the same behavior as with any FILE-type inputs)

**Comment by loicmathieu** [comment]
Preview will only be possible for namepace files.

```yaml
id: local_file_test
namespace: company.team

inputs:
  - id: local
    type: FILE
    defaults: nsfile:///test.txt

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: "{{read(inputs.local)}}"
```
