### ISSUE TITLE
Add support for Namespace Files as defaults in FILE-type inputs

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#9741]
### Feature description

As a follow-up to https://github.com/kestra-io/kestra/pull/9727, we want also to allow reading namespace files:

```yaml
id: local_file_test
namespace: company.team

inputs:
  - id: local
    type: FILE
    defaults: nsfile:///local/hello.txt

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: "{{read(inputs.local)}}"
```

1. `nsfile:///path-to/file.txt`: reads a specific namespace file of the current namespace
2. `nsfile://company.team.project.arbitrarilyy.long.namespace/path-to/file.txt`: reads a namespace file from another namespace (we use Allowed Namespaces concept to check if we can read that file)
3. Inheritance should work out of the box, i.e. if you specify `nsfile:///path-to/file.txt` in a flow from `company.team` namespace and we don't find it there, we look for that file in the `company` namespace. We should add a test to validate.
