### ISSUE TITLE
Cannot render variables in scheduled tasks since 0.22.15

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#9745]
After updating to EE-v0.22.15, a lot of our scheduled flows started failing. 
I've narrowed it down to using variables in schedules only. 
If you remove the trigger and manually execute this taks it works fine. However the schedule causes it to break.

the reproduction flow: 

```yaml 
id: variable_test
namespace: sandbox

variables:
  date: "{{ (trigger.date ?? execution.startDate) | date('yyyy-MM-dd') }}"

triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    recoverMissedSchedules: NONE
    cron: "*/10 * * * *"

tasks:
  - id: hello
    type: io.kestra.plugin.core.log.Log
    message: "{{ render(vars.date) }}"
```

Support [ticket](https://kestra-io.zendesk.com/agent/tickets/499)
