### ISSUE TITLE
OSS User request: add copy button to copy all execution logs to a clipboard

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#9756]
### Feature description

![Image](https://github.com/user-attachments/assets/aedd0737-ca8f-4f18-ada4-c1b1868a1fd6)

TODO: if feasible even with large amount of logs, let's add that copy button at the top

workaround until then:

![Image](https://github.com/user-attachments/assets/3fb96275-4c46-4628-99e9-3a9f5bab2497)

**Comment by elevatebart** [comment]
If the logs are paginated, copying more than one page is going to take some work.

If not, it seems like a quite simple feature.

**Comment by Piyush-r-bhaskar** [comment]
`/logs/{executionId}/download)` seems to be using a streaming approach. The `logService.getExecutionLogsAsStream()` method (`webserver/src/main/java/io/kestra/webserver/controllers/api/LogController.java`) returns ALL logs for an execution as a stream giving the complete log output in one response. @kestra-io/backend to provide input

So, we may call the `/download` endpoint which should bypass pagination then we may use  `Utils.copy()` to copy all logs. WDYT @elevatebart ??

**Comment by anna-geller** [comment]
> we may call the /download endpoint which should bypass pagination then we may use Utils.copy() to copy all logs

sounds like a quick win then?

**Comment by Piyush-r-bhaskar** [comment]
@anna-geller  / @Ben8t ..could you share a flow which generates loads of logs.

**Comment by Ben8t** [comment]
This one should be fine (you can adjuste the for loop range if you want way more logs):

```yaml
id: my_new_flow_python
namespace: dev.ben

tasks:
  - id: python
    type: io.kestra.plugin.scripts.python.Script
    description: my task description
    script: |
      for i in range(0,5000):
        print(i)
    taskRunner:
      type: io.kestra.plugin.core.runner.Process

```
