### ISSUE TITLE
[BC] Make the defaults property of all flow inputs dynamic

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#9762]
### Feature description

Use case: change whether backup_enabled `defaults` is true or false based on a condition or prior input (e.g. if release_env is `PROD`, set by default to `true`, if not PROD, set to `false`)

```yaml
id: infra
namespace: company.team

inputs:
  - id: release_env
    displayName: Release Environment
    type: SELECT
    values:
      - DEV
      - TEST
      - QA
      - PROD
    defaults: DEV

  - id: backup_enabled
    type: BOOL
    defaults: "{{ inputs.release_env == 'PROD' ? true : false }}"   
```

This issue https://github.com/kestra-io/kestra/issues/7972 will benefit from `dynamic` defaults too.

### Challenge

To construct a Pebble context, we need an execution. At input time, there is no execution created yet. 

However, we already have a workaround with conditional inputs, we may reuse the same approach here. It might be a matter of updating that class: https://github.com/kestra-io/kestra/blob/develop/core/src/main/java/io/kestra/core/runners/FlowInputOutput.java

**Comment by anna-geller** [comment]
at least 1 day of work

**Comment by fhussonnois** [comment]
To be able to use `inputs` in a pebble expression we have to use the `dependsOn` property.

Here is the corrected example is: 

```yaml
id: infra
namespace: company.team

inputs:
  - id: release_env
    displayName: Release Environment
    type: SELECT
    values:
      - DEV
      - TEST
      - QA
      - PROD
    defaults: DEV

  - id: backup_enabled
    type: BOOL
    defaults: "{{ inputs.release_env == 'PROD' ? true : false }}" 
    dependsOn:
      inputs:
        - release_env
     
```
