### ISSUE TITLE
Can not write a flow that has an optional input

### ISSUE THREAD

**Issue by hickey** [kestra-io/kestra#9787]
### Describe the issue

I have been going slightly crazy trying to create a flow that has a single optional input. For example, if one starts a flow with the following:

```yaml
id: injest
namespace: finance.stock_pipeline

inputs:
  - id: run_date
    type: DATE
    required: false
```

Then in a task one tries to reference `{{ inputs.run_date }}` or even `{{ inputs }}` then the Python script throws an exception and the execution states `Execution failed! Last error was: Unable to find inputs used in the expression`. 

I have tried several different ways to detect if there are inputs or not. I have run out of ideas. 

I was just reviewing the Kestra documentation related to inputs to once again see if I could find a method to detect when an input has been specified or not. There is one example (the first one under Dynamic Inputs) on the page https://kestra.io/docs/workflow-components/inputs that sets up a DATETIME input and sets a default value. But even this example that is in the documentation is not correct. The example sets the default to the return value of `now()`, but if one tries this example and error is displayed by the editor and the flow can not be saved. See the following screen dump. 

<img width="779" alt="Image" src="https://github.com/user-attachments/assets/8339c86a-cfd6-4fbb-920d-9edc602c2f7a" />

I would be happy to set a default so that my flow could work with or without the input being specified, but if `now()` can not be parsed correctly to pass the validation done in the editor, there is even less chance that `(now() | dateAdd(-1, 'DAYS')) | date('yyyy-MM-dd')` will pass the validation for the DATE data type. 

### Environment

- Kestra Version: 0.22.8

**Comment by Ben8t** [comment]
Hello, can you share your full flow so we can try to reproduce please?

**Comment by sjoerdsmink** [comment]
On https://kestra.io/docs/workflow-components/inputs it's mentioned that a default `now()` with a DATE type doesn't work. You need to change the type to STRING. 

You could consider using a variable, something like
```
id: injest
namespace: finance.stock_pipeline

inputs:
  - id: run_date
    type: DATE
    required: false

variables:
  time: "{{ (inputs.run_date ?? now()) | dateAdd(-1, 'DAYS') | date('yyyy-MM-dd') }}"

tasks:
  - id: log
    type: io.kestra.plugin.core.log.Log
    message: "Date: {{render(vars.time)}}"
```

It's not possible to use pebble expressions in inputs, as mentioned [here](https://kestra.io/docs/workflow-components/variables#:~:text=Therefore%2C%20you%20can%20use%20inputs%20within%20variables%2C%20but%20you%20can%27t%20use%20variables%20or%20Pebble%20expressions%20within%20inputs.).
